### ISSUE TITLE
Digital Ocean deploys are broken for new accounts

### ISSUE THREAD

**Issue by ndtob** [trailofbits/algo#100]
Tested several times and have received several errors relating to changes on the DigitalOcean side.

Making an attempt to run from scratch always fails on Digital Ocean.

**Comment by dguido** [comment]
Can you post the error? What branch of Algo are you using?

**Comment by ndtob** [comment]
DO deployments are alway failing on this step:


TASK [Install prerequisites] ***************************************************
fatal: [162.243.30.232]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh.", "unreachable": true}

I've tested on multiple machines, on multiple DO locations and have received the same feedback from others who have attempted to deploy on DO recently.

**Comment by gunph1ld** [comment]
Are you able to connect to the instance from your machine? try `ssh root@162.243.30.232`

**Comment by dguido** [comment]
This works fine for me.

**Comment by gunph1ld** [comment]
@ndtob any news?

**Comment by ndtob** [comment]
Just tested, worked flawlessly. FIXED!
