### ISSUE TITLE
Error while install

### ISSUE THREAD

**Issue by obsidum** [trailofbits/algo#1000]
### OS / Environment (where do you run Algo on)

Linux VPN 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux

### Cloud Provider (where do you deploy Algo to)

No typical cloud provider. VPS server from aruba.it 

### Summary of the problem

Error while install

### Steps to reproduce the behavior

1.  ./algo
2. provider: 7
3. machine: localhost
4. user: empty
5. ip: sever ip
6. widows 10 and linux clients: y, other question: n

### Full log

 [WARNING]: While constructing a mapping from /usr/algo/algo-master/roles
/cloud-scaleway/tasks/main.yml, line 73, column 11, found a duplicate dict key
(enable_ipv6). Using last defined value only.

PLAY [Configure the server] ****************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [Local pre-tasks] *********************************************************
included: /usr/algo/algo-master/playbooks/local.yml for localhost

TASK [Generate the SSH private key] ********************************************
ok: [localhost]

TASK [Generate the SSH public key] *********************************************
ok: [localhost]

TASK [Change mode for the SSH private key] *************************************
ok: [localhost]

TASK [Ensure the dynamic inventory exists] *************************************
ok: [localhost]

TASK [Local pre-tasks] *********************************************************
included: /usr/algo/algo-master/playbooks/local_ssh.yml for localhost

TASK [Ensure the local ssh directory is exist] *********************************
ok: [localhost]

TASK [Copy the algo ssh key to the local ssh directory] ************************
changed: [localhost]

TASK [local : Add the instance to an inventory group] **************************
skipping: [localhost]

TASK [local : Add the instance to an inventory group] **************************
changed: [localhost]

TASK [local : set_fact] ********************************************************
ok: [localhost]

TASK [local : Ensure the group local exists in the dynamic inventory file] *****
ok: [localhost]

TASK [local : Populate the dynamic inventory] **********************************
ok: [localhost]

PLAY [Configure the server and install required software] **********************

TASK [Common pre-tasks] ********************************************************
included: /usr/algo/algo-master/playbooks/common.yml for localhost

TASK [Check the system] ********************************************************
changed: [localhost]

TASK [Ubuntu pre-tasks] ********************************************************
included: /usr/algo/algo-master/playbooks/ubuntu.yml for localhost

TASK [Ubuntu | Install prerequisites] ******************************************
changed: [localhost] => (item=sleep 10)
failed: [localhost] (item=apt-get update -qq) => {"changed": true, "item": "apt-get update -qq", "msg": "non-zero return code", "rc": 100, "stderr": "W: The repository 'http://ppa.launchpad.net/wireguard/wireguard/ubuntu stretch Release' does not have a Release file.\nE: Failed to fetch http://ppa.launchpad.net/wireguard/wireguard/ubuntu/dists/stretch/main/binary-amd64/Packages  404  Not Found\nE: Some index files failed to download. They have been ignored, or old ones used instead.\n", "stdout": "", "stdout_lines": []}
changed: [localhost] => (item=apt-get install -qq -y python2.7 sudo)

TASK [debug] *******************************************************************
ok: [localhost] => {
    "fail_hint": [
        "Sorry, but something went wrong!",
        "Please check the troubleshooting guide.",
        "https://trailofbits.github.io/algo/troubleshooting.html"
    ]
}

TASK [fail] ********************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed as requested from task"}

PLAY RECAP *********************************************************************
localhost                  : ok=17   changed=3    unreachable=0    failed=2

```
PUT THE OUTPUT HERE
```

**Comment by adamluk** [comment]
The first failed task is addressed in pull request https://github.com/trailofbits/algo/pull/999/commits/7e240387c254ebc0be89305ac62dbc4a7d3cdf4f

The second is because Algo does not support Debian - use Ubuntu.
