### ISSUE TITLE
New Scaleway install fails on Task: wirestart enabled and started

### ISSUE THREAD

**Issue by amalap-r** [trailofbits/algo#1002]
### OS / Environment (where do you run Algo on)

Ubuntu 18.04 LTS
Linux mini 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Cloud Provider (where do you deploy Algo to)

Scaleway

### Summary of the problem
Install fails on TASK [wireguard : WireGuard enabled and started] 

fatal: [51.15.232.74]: FAILED! => {"changed": false, "msg": "Unable to start service wg-quick@wg0: Job for wg-quick@wg0.service failed because the control process exited with error code.\nSee \"systemctl status wg-quick@wg0.service\" and \"journalctl -xe\" for details.\n"}

### Steps to reproduce the behavior

1. Launch algo
2. Select Scaleway
3. Enter access key and organization
4. Choose options:
- VPN on demand for iOS = yes on wifi, yes on cellular
- Enter wireless network exceptions
- DNS to block ads: yes
5. Wait until it fails

### Full log
I am omitting many duplicate lines of "skipping: [localhost] => (item=None)".

(env) arnaud@mini:~/algo-master$ ./algo 

  What provider would you like to use?
    1. DigitalOcean
    2. Amazon EC2
    3. Microsoft Azure
    4. Google Compute Engine
    5. Scaleway
    6. OpenStack (DreamCompute optimised)
    7. Install to existing Ubuntu 16.04 server (Advanced)

Enter the number of your desired provider
: 5

Enter your auth token (https://www.scaleway.com/docs/generate-an-api-token/)
[pasted values will not be displayed]
[...]: 

Enter your organization name (https://cloud.scaleway.com/#/billing)
[pasted values will not be displayed]
[...]: 

Name the vpn server:
[algo.local]: 

  What region should the server be located in?
    1.   par1           Paris
    2.   ams1           Amsterdam
Enter the number of your desired region:
[1]: 1

Do you want macOS/iOS clients to enable "VPN On Demand" when connected to cellular networks?
[y/N]: y

Do you want macOS/iOS clients to enable "VPN On Demand" when connected to Wi-Fi?
[y/N]: y

List the names of trusted Wi-Fi networks (if any) that macOS/iOS clients exclude from using the VPN (e.g., your home network. Comma-separated value, e.g., HomeNet,OfficeWifi,AlgoWiFi)
: B566,B566-5

Do you want to install a DNS resolver on this VPN server, to block ads while surfing?
[y/N]: y

Do you want each user to have their own account for SSH tunneling?
[y/N]: 

Do you want the VPN to support Windows 10 or Linux Desktop clients? (enables compatible ciphers and key exchange, less secure)
[y/N]: 

Do you want to retain the CA key? (required to add users in the future, but less secure)
[y/N]: 
 [WARNING]: While constructing a mapping from /home/arnaud/algo-master/roles/cloud-scaleway/tasks/main.yml, line 73, column 11, found a duplicate dict key (enable_ipv6). Using last defined value
only.

PLAY [Configure the server] ***************************************************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************************************************
ok: [localhost]

TASK [Local pre-tasks] ********************************************************************************************************************************************************************************
included: /home/arnaud/algo-master/playbooks/local.yml for localhost

TASK [Generate the SSH private key] *******************************************************************************************************************************************************************
changed: [localhost]

TASK [Generate the SSH public key] ********************************************************************************************************************************************************************
ok: [localhost]

TASK [Change mode for the SSH private key] ************************************************************************************************************************************************************
ok: [localhost]

TASK [Ensure the dynamic inventory exists] ************************************************************************************************************************************************************
changed: [localhost]

TASK [cloud-scaleway : Check if server exists] ********************************************************************************************************************************************************
ok: [localhost]

TASK [cloud-scaleway : Set server id as a fact] *******************************************************************************************************************************************************

TASK [cloud-scaleway : Get the organization id] *******************************************************************************************************************************************************
ok: [localhost]

TASK [cloud-scaleway : Set organization id as a fact] *************************************************************************************************************************************************
ok: [localhost] => (item=None)

TASK [cloud-scaleway : Get total count of images] *****************************************************************************************************************************************************
ok: [localhost]

TASK [cloud-scaleway : Get images] ********************************************************************************************************************************************************************
ok: [localhost] => (item=1)
ok: [localhost] => (item=2)
ok: [localhost] => (item=3)
ok: [localhost] => (item=4)
ok: [localhost] => (item=5)
ok: [localhost] => (item=6)
ok: [localhost] => (item=7)
ok: [localhost] => (item=8)

TASK [cloud-scaleway : Set image id as a fact] ********************************************************************************************************************************************************
included: /home/arnaud/algo-master/roles/cloud-scaleway/tasks/image_facts.yml for localhost
included: /home/arnaud/algo-master/roles/cloud-scaleway/tasks/image_facts.yml for localhost
included: /home/arnaud/algo-master/roles/cloud-scaleway/tasks/image_facts.yml for localhost
included: /home/arnaud/algo-master/roles/cloud-scaleway/tasks/image_facts.yml for localhost
included: /home/arnaud/algo-master/roles/cloud-scaleway/tasks/image_facts.yml for localhost
included: /home/arnaud/algo-master/roles/cloud-scaleway/tasks/image_facts.yml for localhost
included: /home/arnaud/algo-master/roles/cloud-scaleway/tasks/image_facts.yml for localhost
included: /home/arnaud/algo-master/roles/cloud-scaleway/tasks/image_facts.yml for localhost

TASK [cloud-scaleway : Set image id as a fact] ********************************************************************************************************************************************************
skipping: [localhost] => (item=None) 
[...]

TASK [cloud-scaleway : Set image id as a fact] ********************************************************************************************************************************************************
skipping: [localhost] => (item=None) 
[...]

TASK [cloud-scaleway : Set image id as a fact] ********************************************************************************************************************************************************
skipping: [localhost] => (item=None) 
[...]

TASK [cloud-scaleway : Set image id as a fact] ********************************************************************************************************************************************************
skipping: [localhost] => (item=None) 
[...]
skipping: [localhost] => (item=None) 
ok: [localhost] => (item=None)
skipping: [localhost] => (item=None) 
[...]

TASK [cloud-scaleway : Set image id as a fact] ********************************************************************************************************************************************************
[...]

TASK [cloud-scaleway : Set image id as a fact] ********************************************************************************************************************************************************
[...]

TASK [cloud-scaleway : Set image id as a fact] ********************************************************************************************************************************************************
skipping: [localhost] => (item=None) 
[...]

TASK [cloud-scaleway : Set image id as a fact] ********************************************************************************************************************************************************
skipping: [localhost] => (item=None) 
[...]

TASK [cloud-scaleway : Create a server] ***************************************************************************************************************************************************************
ok: [localhost]

TASK [cloud-scaleway : Set server id as a fact] *******************************************************************************************************************************************************
ok: [localhost]

TASK [cloud-scaleway : Power on the server] ***********************************************************************************************************************************************************
ok: [localhost]

TASK [cloud-scaleway : Wait for the server to become running] *****************************************************************************************************************************************
FAILED - RETRYING: Wait for the server to become running (20 retries left).
ok: [localhost]

TASK [cloud-scaleway : set_fact] **********************************************************************************************************************************************************************
ok: [localhost]

TASK [cloud-scaleway : Add new instance to host group] ************************************************************************************************************************************************
changed: [localhost]

TASK [Local post-tasks] *******************************************************************************************************************************************************************************
included: /home/arnaud/algo-master/playbooks/post.yml for localhost

TASK [Wait until SSH becomes ready...] ****************************************************************************************************************************************************************
ok: [localhost]

TASK [A short pause, in order to be sure the instance is ready] ***************************************************************************************************************************************
Pausing for 20 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)
ok: [localhost]

TASK [include_tasks] **********************************************************************************************************************************************************************************
included: /home/arnaud/algo-master/playbooks/local_ssh.yml for localhost

TASK [Ensure the local ssh directory is exist] ********************************************************************************************************************************************************
ok: [localhost]

TASK [Copy the algo ssh key to the local ssh directory] ***********************************************************************************************************************************************
changed: [localhost]

PLAY [Configure the server and install required software] *********************************************************************************************************************************************

TASK [Common pre-tasks] *******************************************************************************************************************************************************************************
included: /home/arnaud/algo-master/playbooks/common.yml for 51.15.232.74

TASK [Check the system] *******************************************************************************************************************************************************************************
changed: [51.15.232.74]

TASK [Ubuntu pre-tasks] *******************************************************************************************************************************************************************************
included: /home/arnaud/algo-master/playbooks/ubuntu.yml for 51.15.232.74

TASK [Ubuntu | Install prerequisites] *****************************************************************************************************************************************************************
changed: [51.15.232.74] => (item=sleep 10)
changed: [51.15.232.74] => (item=apt-get update -qq)
changed: [51.15.232.74] => (item=apt-get install -qq -y python2.7 sudo)

TASK [Ubuntu | Configure defaults] ********************************************************************************************************************************************************************
changed: [51.15.232.74]

TASK [FreeBSD pre-tasks] ******************************************************************************************************************************************************************************
skipping: [51.15.232.74]

TASK [include_tasks] **********************************************************************************************************************************************************************************
included: /home/arnaud/algo-master/playbooks/facts/main.yml for 51.15.232.74

TASK [Gather Facts] ***********************************************************************************************************************************************************************************
ok: [51.15.232.74]

TASK [Ensure the algo ssh key exist on the server] ****************************************************************************************************************************************************
ok: [51.15.232.74]

TASK [Check if IPv6 configured] ***********************************************************************************************************************************************************************
ok: [51.15.232.74]

TASK [Set facts if the deployment in a cloud] *********************************************************************************************************************************************************
ok: [51.15.232.74]

TASK [Generate password for the CA key] ***************************************************************************************************************************************************************
changed: [51.15.232.74 -> localhost]

TASK [Generate p12 export password] *******************************************************************************************************************************************************************
changed: [51.15.232.74 -> localhost]

TASK [Define password facts] **************************************************************************************************************************************************************************
ok: [51.15.232.74]

TASK [Define the commonName] **************************************************************************************************************************************************************************
ok: [51.15.232.74]

TASK [common : include_tasks] *************************************************************************************************************************************************************************
included: /home/arnaud/algo-master/roles/common/tasks/ubuntu.yml for 51.15.232.74

TASK [common : Install software updates] **************************************************************************************************************************************************************
changed: [51.15.232.74]

TASK [common : Upgrade the ca certificates] ***********************************************************************************************************************************************************
ok: [51.15.232.74]

TASK [common : Check if reboot is required] ***********************************************************************************************************************************************************
changed: [51.15.232.74]

TASK [common : Reboot] ********************************************************************************************************************************************************************************
changed: [51.15.232.74]

TASK [common : Wait until SSH becomes ready...] *******************************************************************************************************************************************************
ok: [51.15.232.74 -> localhost]

TASK [common : Include unatteded upgrades configuration] **********************************************************************************************************************************************
included: /home/arnaud/algo-master/roles/common/tasks/unattended-upgrades.yml for 51.15.232.74

TASK [common : Install unattended-upgrades] ***********************************************************************************************************************************************************
ok: [51.15.232.74]

TASK [common : Configure unattended-upgrades] *********************************************************************************************************************************************************
changed: [51.15.232.74]

TASK [common : Periodic upgrades configured] **********************************************************************************************************************************************************
changed: [51.15.232.74]

TASK [common : Disable MOTD on login and SSHD] ********************************************************************************************************************************************************
changed: [51.15.232.74] => (item={u'regexp': u'^session.*optional.*pam_motd.so.*', u'line': u'# MOTD DISABLED', u'file': u'/etc/pam.d/login'})
changed: [51.15.232.74] => (item={u'regexp': u'^session.*optional.*pam_motd.so.*', u'line': u'# MOTD DISABLED', u'file': u'/etc/pam.d/sshd'})

TASK [common : Loopback for services configured] ******************************************************************************************************************************************************
changed: [51.15.232.74]

TASK [common : systemd-networkd enabled and started] **************************************************************************************************************************************************
changed: [51.15.232.74]

RUNNING HANDLER [common : restart systemd-networkd] ***************************************************************************************************************************************************
changed: [51.15.232.74]

TASK [common : Check apparmor support] ****************************************************************************************************************************************************************
changed: [51.15.232.74]

TASK [common : set_fact] ******************************************************************************************************************************************************************************
ok: [51.15.232.74]

TASK [common : set_fact] ******************************************************************************************************************************************************************************
ok: [51.15.232.74]

TASK [common : include_tasks] *************************************************************************************************************************************************************************
skipping: [51.15.232.74]

TASK [common : Install tools] *************************************************************************************************************************************************************************
ok: [51.15.232.74] => (item=git)
ok: [51.15.232.74] => (item=screen)
changed: [51.15.232.74] => (item=apparmor-utils)
ok: [51.15.232.74] => (item=uuid-runtime)
ok: [51.15.232.74] => (item=coreutils)
changed: [51.15.232.74] => (item=iptables-persistent)
changed: [51.15.232.74] => (item=cgroup-tools)
changed: [51.15.232.74] => (item=openssl,linux-headers-4.15.0-20-generic)

TASK [common : Sysctl tuning] *************************************************************************************************************************************************************************
changed: [51.15.232.74] => (item={u'item': u'net.ipv4.ip_forward', u'value': 1})
changed: [51.15.232.74] => (item={u'item': u'net.ipv4.conf.all.forwarding', u'value': 1})
changed: [51.15.232.74] => (item={u'item': u'net.ipv6.conf.all.forwarding', u'value': 1})

TASK [dns_encryption : Include tasks for Ubuntu] ******************************************************************************************************************************************************
included: /home/arnaud/algo-master/roles/dns_encryption/tasks/ubuntu.yml for 51.15.232.74

TASK [dns_encryption : Add the repository] ************************************************************************************************************************************************************
changed: [51.15.232.74]

TASK [dns_encryption : Install dnscrypt-proxy] ********************************************************************************************************************************************************
changed: [51.15.232.74]

TASK [dns_encryption : Ubuntu | Unbound profile for apparmor configured] ******************************************************************************************************************************
changed: [51.15.232.74]

TASK [dns_encryption : Ubuntu | Enforce the dnscrypt-proxy AppArmor policy] ***************************************************************************************************************************
ok: [51.15.232.74]

TASK [dns_encryption : Ubuntu | Ensure that the dnscrypt-proxy service directory exist] ***************************************************************************************************************
changed: [51.15.232.74]

TASK [dns_encryption : Ubuntu | Add capabilities to bind ports] ***************************************************************************************************************************************
changed: [51.15.232.74]

TASK [dns_encryption : Include tasks for FreeBSD] *****************************************************************************************************************************************************
skipping: [51.15.232.74]

TASK [dns_encryption : dnscrypt-proxy configured] *****************************************************************************************************************************************************
changed: [51.15.232.74]

TASK [dns_encryption : dnscrypt-proxy enabled and started] ********************************************************************************************************************************************
ok: [51.15.232.74]

RUNNING HANDLER [dns_encryption : restart dnscrypt-proxy] *********************************************************************************************************************************************
changed: [51.15.232.74]

TASK [dns_adblocking : The DNS tag is defined] ********************************************************************************************************************************************************
ok: [51.15.232.74]

TASK [dns_adblocking : Dnsmasq installed] *************************************************************************************************************************************************************
changed: [51.15.232.74]

TASK [dns_adblocking : Ensure that the dnsmasq user exist] ********************************************************************************************************************************************
changed: [51.15.232.74]

TASK [dns_adblocking : The dnsmasq directory created] *************************************************************************************************************************************************
changed: [51.15.232.74]

TASK [dns_adblocking : include_tasks] *****************************************************************************************************************************************************************
included: /home/arnaud/algo-master/roles/dns_adblocking/tasks/ubuntu.yml for 51.15.232.74

TASK [dns_adblocking : Ubuntu | Dnsmasq profile for apparmor configured] ******************************************************************************************************************************
changed: [51.15.232.74]

TASK [dns_adblocking : Ubuntu | Enforce the dnsmasq AppArmor policy] **********************************************************************************************************************************
changed: [51.15.232.74]

TASK [dns_adblocking : Ubuntu | Ensure that the dnsmasq service directory exist] **********************************************************************************************************************
changed: [51.15.232.74]

TASK [dns_adblocking : Ubuntu | Setup the cgroup limitations for the ipsec daemon] ********************************************************************************************************************
changed: [51.15.232.74]

TASK [dns_adblocking : include_tasks] *****************************************************************************************************************************************************************
skipping: [51.15.232.74]

TASK [dns_adblocking : Dnsmasq configured] ************************************************************************************************************************************************************
changed: [51.15.232.74]

TASK [dns_adblocking : Adblock script created] ********************************************************************************************************************************************************
changed: [51.15.232.74]

TASK [dns_adblocking : Adblock script added to cron] **************************************************************************************************************************************************
changed: [51.15.232.74]

TASK [dns_adblocking : Update adblock hosts] **********************************************************************************************************************************************************
changed: [51.15.232.74]

RUNNING HANDLER [dns_adblocking : restart dnsmasq] ****************************************************************************************************************************************************
changed: [51.15.232.74]

RUNNING HANDLER [vpn : daemon-reload] *****************************************************************************************************************************************************************
changed: [51.15.232.74]

TASK [dns_adblocking : Dnsmasq enabled and started] ***************************************************************************************************************************************************
ok: [51.15.232.74]

TASK [wireguard : WireGuard repository configured] ****************************************************************************************************************************************************
changed: [51.15.232.74]

TASK [wireguard : WireGuard installed] ****************************************************************************************************************************************************************
changed: [51.15.232.74]

TASK [wireguard : Ensure the required directories exist] **********************************************************************************************************************************************
changed: [51.15.232.74 -> localhost] => (item=private)
changed: [51.15.232.74 -> localhost] => (item=public)

TASK [wireguard : Delete the lock files] **************************************************************************************************************************************************************
skipping: [51.15.232.74] => (item=alpha) 
skipping: [51.15.232.74] => (item=beta) 
skipping: [51.15.232.74] => (item=gamma) 
skipping: [51.15.232.74] => (item=omega) 
skipping: [51.15.232.74] => (item=zeta) 
skipping: [51.15.232.74] => (item=51.15.232.74) 

TASK [wireguard : Generate private keys] **************************************************************************************************************************************************************
changed: [51.15.232.74] => (item=alpha)
changed: [51.15.232.74] => (item=beta)
changed: [51.15.232.74] => (item=gamma)
changed: [51.15.232.74] => (item=omega)
changed: [51.15.232.74] => (item=zeta)
changed: [51.15.232.74] => (item=51.15.232.74)
 [WARNING]: As of Ansible 2.4, the parameter 'executable' is no longer supported with the 'command' module. Not using 'bash'.

TASK [wireguard : Save private keys] ******************************************************************************************************************************************************************
changed: [51.15.232.74] => (item=None)
changed: [51.15.232.74] => (item=None)
changed: [51.15.232.74] => (item=None)
changed: [51.15.232.74] => (item=None)
changed: [51.15.232.74] => (item=None)
changed: [51.15.232.74] => (item=None)

TASK [wireguard : Touch the lock file] ****************************************************************************************************************************************************************
changed: [51.15.232.74] => (item=alpha)
changed: [51.15.232.74] => (item=beta)
changed: [51.15.232.74] => (item=gamma)
changed: [51.15.232.74] => (item=omega)
changed: [51.15.232.74] => (item=zeta)
changed: [51.15.232.74] => (item=51.15.232.74)

TASK [wireguard : Generate public keys] ***************************************************************************************************************************************************************
ok: [51.15.232.74] => (item=alpha)
ok: [51.15.232.74] => (item=beta)
ok: [51.15.232.74] => (item=gamma)
ok: [51.15.232.74] => (item=omega)
ok: [51.15.232.74] => (item=zeta)
ok: [51.15.232.74] => (item=51.15.232.74)

TASK [wireguard : Save public keys] *******************************************************************************************************************************************************************
changed: [51.15.232.74] => (item=None)
changed: [51.15.232.74] => (item=None)
changed: [51.15.232.74] => (item=None)
changed: [51.15.232.74] => (item=None)
changed: [51.15.232.74] => (item=None)
changed: [51.15.232.74] => (item=None)

TASK [wireguard : WireGuard configured] ***************************************************************************************************************************************************************
changed: [51.15.232.74]

TASK [wireguard : WireGuard reload-module-on-update] **************************************************************************************************************************************************
changed: [51.15.232.74]

TASK [wireguard : WireGuard users config generated] ***************************************************************************************************************************************************
changed: [51.15.232.74 -> localhost] => (item=(0, u'alpha'))
changed: [51.15.232.74 -> localhost] => (item=(1, u'beta'))
changed: [51.15.232.74 -> localhost] => (item=(2, u'gamma'))
changed: [51.15.232.74 -> localhost] => (item=(3, u'omega'))
changed: [51.15.232.74 -> localhost] => (item=(4, u'zeta'))

TASK [wireguard : WireGuard enabled and started] ******************************************************************************************************************************************************
fatal: [51.15.232.74]: FAILED! => {"changed": false, "msg": "Unable to start service wg-quick@wg0: Job for wg-quick@wg0.service failed because the control process exited with error code.\nSee \"systemctl status wg-quick@wg0.service\" and \"journalctl -xe\" for details.\n"}

RUNNING HANDLER [wireguard : restart wireguard] *******************************************************************************************************************************************************

PLAY RECAP ********************************************************************************************************************************************************************************************
51.15.232.74               : ok=70   changed=47   unreachable=0    failed=1   
localhost                  : ok=32   changed=4    unreachable=0    failed=0   

(env) arnaud@mini:~/algo-master$

**Comment by plgingembre** [comment]
Hi, it won't entirely solve the issue, but I found a way to workaround this issue. When it fails, go to your scaleway admin portal or ssh to your instance, reboot it. Once the instance is rebooted, you run the script again with the same parameters, it goes through. I think too much things were changed in 18.04, not that easy to catch everything and keep up.

**Comment by jackivanov** [comment]
Nothing to do with 18.04. That's shitty scaleway service with their own kernels. https://github.com/trailofbits/algo/issues/966 might be related, but it's fixed already

**Comment by amalap-r** [comment]
The same problem is still here today.

```
TASK [wireguard : WireGuard enabled and started] ******************************************************************************************************************************************************
fatal: [51.15.245.31]: FAILED! => {"changed": false, "msg": "Unable to start service wg-quick@wg0: Job for wg-quick@wg0.service failed because the control process exited with error code.\nSee \"systemctl status wg-quick@wg0.service\" and \"journalctl -xe\" for details.\n"}

RUNNING HANDLER [wireguard : restart wireguard] *******************************************************************************************************************************************************

PLAY RECAP ********************************************************************************************************************************************************************************************
51.15.245.31               : ok=70   changed=47   unreachable=0    failed=1   
localhost                  : ok=32   changed=4    unreachable=0    failed=0   

```

But the workaround provided by plgingembre did work: thanks!
