### ISSUE TITLE
Setting local DNS

### ISSUE THREAD

**Issue by jmeeter** [trailofbits/algo#1003]
### OS / Environment (where do you run Algo on)

```
Linux streisand 4.4.0-127-generic #153-Ubuntu SMP Sat May 19 10:58:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

### Cloud Provider (where do you deploy Algo to)

```
Digital Ocean
```

### Summary of the problem

Hello, this is my first time commenting on Github so I apologize if this is an improper avenue. I am interesting in deploying [pi-hole](https://github.com/pi-hole/pi-hole) in conjunction with algo, and I believe all I need to do is set a local DNS in algo's config - is this possible with algo? And if so where do I configure my DNS settings?

Thanks!

**Comment by dguido** [comment]
The proper place to get this kind of supper is on the gitter. DNS settings are found in the config.cfg file.
