### ISSUE TITLE
TASK [cloud-gce : Network configured] Fails

### ISSUE THREAD

**Issue by jadhavdinesh7** [trailofbits/algo#1004]
### OS / Environment (where do you run Algo on)
Windows 10
./algo

```
PUT THE OUTPUT HERE
```
 [WARNING]: While constructing a mapping from /home/dinu/algo/roles/cloud-scaleway/tasks/main.yml, line 73, column 11,
found a duplicate dict key (enable_ipv6). Using last defined value only.

PLAY [Configure the server] ********************************************************************************************

TASK [Gathering Facts] *************************************************************************************************
ok: [localhost]

TASK [Local pre-tasks] *************************************************************************************************
included: /home/dinu/algo/playbooks/local.yml for localhost

TASK [Generate the SSH private key] ************************************************************************************
ok: [localhost]

TASK [Generate the SSH public key] *************************************************************************************
ok: [localhost]

TASK [Change mode for the SSH private key] *****************************************************************************
ok: [localhost]

TASK [Ensure the dynamic inventory exists] *****************************************************************************
ok: [localhost]

TASK [cloud-gce : set_fact] ********************************************************************************************
ok: [localhost]

TASK [cloud-gce : set_fact] ********************************************************************************************
ok: [localhost]

TASK [cloud-gce : set_fact] ********************************************************************************************
ok: [localhost]

TASK [cloud-gce : Network configured] **********************************************************************************
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'client_email'\n\nThe error appears to have been in '/home/dinu/algo/roles/cloud-gce/tasks/main.yml': line 14, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Network configured\n      ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'dict object' has no attribute 'client_email'"}

TASK [cloud-gce : debug] ***********************************************************************************************
ok: [localhost] => {
    "fail_hint": [
        "Sorry, but something went wrong!",
        "Please check the troubleshooting guide.",
        "https://trailofbits.github.io/algo/troubleshooting.html"
    ]
}

TASK [cloud-gce : fail] ************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed as requested from task"}

PLAY RECAP *************************************************************************************************************
localhost                  : ok=10   changed=0    unreachable=0    failed=2

### Cloud Provider (where do you deploy Algo to)

Google Compute Engine

```
PUT THE OUTPUT HERE
```

### Steps to reproduce the behavior

1. After Installing All dependencies Run ./algo

### Full log

```
PUT THE OUTPUT HERE
```
 [WARNING]: While constructing a mapping from /home/dinu/algo/roles/cloud-scaleway/tasks/main.yml, line 73, column 11,
found a duplicate dict key (enable_ipv6). Using last defined value only.

PLAY [Configure the server] ********************************************************************************************

TASK [Gathering Facts] *************************************************************************************************
ok: [localhost]

TASK [Local pre-tasks] *************************************************************************************************
included: /home/dinu/algo/playbooks/local.yml for localhost

TASK [Generate the SSH private key] ************************************************************************************
ok: [localhost]

TASK [Generate the SSH public key] *************************************************************************************
ok: [localhost]

TASK [Change mode for the SSH private key] *****************************************************************************
ok: [localhost]

TASK [Ensure the dynamic inventory exists] *****************************************************************************
ok: [localhost]

TASK [cloud-gce : set_fact] ********************************************************************************************
ok: [localhost]

TASK [cloud-gce : set_fact] ********************************************************************************************
ok: [localhost]

TASK [cloud-gce : set_fact] ********************************************************************************************
ok: [localhost]

TASK [cloud-gce : Network configured] **********************************************************************************
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'client_email'\n\nThe error appears to have been in '/home/dinu/algo/roles/cloud-gce/tasks/main.yml': line 14, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Network configured\n      ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'dict object' has no attribute 'client_email'"}

TASK [cloud-gce : debug] ***********************************************************************************************
ok: [localhost] => {
    "fail_hint": [
        "Sorry, but something went wrong!",
        "Please check the troubleshooting guide.",
        "https://trailofbits.github.io/algo/troubleshooting.html"
    ]
}

TASK [cloud-gce : fail] ************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed as requested from task"}

PLAY RECAP *************************************************************************************************************
localhost                  : ok=10   changed=0    unreachable=0    failed=2

**Comment by jadhavdinesh7** [comment]
My bad

**Comment by TC1977** [comment]
@jadhavdinesh7 How did you resolve this issue?
