### ISSUE TITLE
Scripted deployment documentation - deploy-from-ansible.md - is missing wireguard role

### ISSUE THREAD

**Issue by digeratus** [trailofbits/algo#1008]
### deploy-from-ansible.md

At the moment, the documentation to deploy from ansible doesn't make any reference to wireguard as a role. That's missing.

If one were to run the current documented example for DigitalOcean without the wireguard tag, it won't create a wireguard setup at all:

```shell
ansible-playbook deploy.yml -t digitalocean,vpn,cloud -e 'do_access_token=my_secret_token do_server_name=algo.local do_region=ams2'
```

Server roles:

role: vpn, tags: vpn
role: dns_adblocking, tags: dns, adblock
role: security, tags: security
role: ssh_tunneling, tags: ssh_tunneling

What's missing is:

role: wireguard, tags: wireguard

**Comment by jackivanov** [comment]
Covered in https://github.com/trailofbits/algo/pull/976
