### ISSUE TITLE
Using email for the username causes login error

### ISSUE THREAD

**Issue by dannolan** [trailofbits/algo#1018]
### OS / Environment (where do you run Algo on)

```
Linux ip-172-31-45-190 4.4.0-1060-aws #69-Ubuntu SMP Sun May 20 13:42:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

### Cloud Provider (where do you deploy Algo to)

```
AWS instance
```

### Summary of the problem

I've spent the past couple of days trying to set up algo to no avail. I'm just running the standard latest version on Ubuntu 16.04. I've hit a serious roadblock, I tried to set the account with an email. I was unable to login and spent hours debugging. Changing back from an email to a normal name (dan, for example) worked perfectly. I feel this probably should be documented as a limitation!

### Steps to reproduce the behavior

1. Install Algo from scratch on a new machine (Ubuntu AMI on AWS)
2. Configure a user with a username that is an email address `dan@gmail.com` for example
3. Download the profile onto your mac
4. Try to connect
5. Recreate the users as say `happydan`
6. Download the profile onto your mac
7. You're now able to connect

**Comment by TC1977** [comment]
Is it the @, or the . that's causing the problem? Or both?

**Comment by jackivanov** [comment]
Fixed [here](https://github.com/trailofbits/algo/tree/email_in_subjectAltName). Will be merged after https://github.com/trailofbits/algo/pull/976

**Comment by dannolan** [comment]
@jackivanov thanks mate!
