### ISSUE TITLE
Make ECC certificates for SSH users

### ISSUE THREAD

**Issue by dguido** [trailofbits/algo#102]
If we use the optional SSH tunneling role, we should make ECC authorized_keys files, not RSA ones.

**Comment by dguido** [comment]
Of course, Putty doesn't support ECC authorized_keys.
http://www.chiark.greenend.org.uk/~sgtatham/putty/wishlist/ecdsa.html

**Comment by grempe** [comment]
I was curious reading this (have not tested putty at all). Wasn't that wishlist item `fixed-in: 2014-11-03`?

Here are relevant commits mentioning elliptic:

https://git.tartarus.org/?p=simon%2Fputty.git&a=search&h=HEAD&st=commit&s=elliptic

According to this page, support may only be in the release snapshots though? Not in the mainline downloads?

http://hakspek.blogspot.com/2016/03/authentication-using-ssh-and-putty.html

Snapshot docs describe support:

https://tartarus.org/~simon/putty-snapshots/htmldoc/Chapter8.html#puttygen-keytype

**Comment by dguido** [comment]
New release of Putty supports ECC keys as of today!
