### ISSUE TITLE
Feature request: Put back ability to create sswan files

### ISSUE THREAD

**Issue by TychoSchenkeveld** [trailofbits/algo#1020]
I just installed my Algo server fresh and I noticed Android support is now only provided via Wireguard.

However on a WiFi network I use regularly (and have no control over) wireguard is blocked, whereas they do permit IKEv2. Probably because this is used often in corporate environments (contractors connecting to their VPN etc).

I saw the changelog of 30 April:
_"StrongSwan profiles for Android are deprecated now. Use WireGuard"_
But why does it have to be exclusive? Just wondering why there was a need to stop creating the .sswan profiles? After all the IKEv2 services still run for all the other platforms so it's not like you're making the server side simpler.

I was able to set it up manually but it worked easier with the strongswan profiles.

PS: Samsung Android devices do support IKEv2 natively, though they need to be set up manually. Samsung added IKEv2 support to the Android VPN panel themselves so you can use always-on. It's been in there as far back as Android 5.1.1, or perhaps even earlier but this is the earliest one I have.

**Comment by zx2c4** [comment]
You can try running WireGuard on a different port, such as port 500. It's just UDP.

**Comment by dguido** [comment]
I understand the sentiment, but the pain of managing this feature is more than it's worth. Please stick with WireGuard.
