### ISSUE TITLE
How to run the client from Ubuntu 18.04 GUI

### ISSUE THREAD

**Issue by RonCan** [trailofbits/algo#1021]
### OS / Environment (where do you run Algo on)

```
Linux ronniekinsley-Inspiron-N5110 4.15.0-23-generic #25-Ubuntu SMP Thu May 31 16:36:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

### Cloud Provider (where do you deploy Algo to)

```
Azure
```

### Summary of the problem

I'm trying to configure the client for Ubuntu 18.04. I run the command
`ansible-playbook deploy_client.yml -e 'client_ip=localhost vpn_user=me server_ip=104.42.209.83 ssh_user=root'`

and it gives me the following output:

`PLAY RECAP *********************************************************************
localhost                  : ok=14   changed=2    unreachable=0    failed=0 `

So far so good. But I can't see the VPN connection in my network manager. Am I missing a step? Should I be running it some other way? 

### Steps to reproduce the behavior

1. Do this..
2. Do that..
3. 

### Full log

```
PUT THE OUTPUT HERE
```

**Comment by TC1977** [comment]
https://github.com/trailofbits/algo#linux-network-manager-clients-eg-ubuntu-debian-or-fedora-desktop

**Comment by trycrmr** [comment]
I had a similar experience to @RonCan initially when following the instructions in the repo. I ended up connecting to my Algo server through a WireGuard VPN tunnel following these instructions instead https://computingforgeeks.com/connecting-to-algo-vpn-server-from-linux-and-android-devices/ .

**Comment by davidemyers** [comment]
@trycrmr The instructions in that blog post seem [somewhat familiar](https://github.com/trailofbits/algo/blob/master/docs/client-linux-wireguard.md)... :smile:
