### ISSUE TITLE
Credentials are not created for Users

### ISSUE THREAD

**Issue by aliasad106** [trailofbits/algo#1023]
in config.cfg There's written that  "Add as many users as you want for your VPN server here **credentials will be generated for each one**" 
But when I install algo. There's no password generated in the User's folder and configuration file requires password to run on iphone and mac.

**Comment by jackivanov** [comment]
https://github.com/trailofbits/algo#configure-the-vpn-clients

**Comment by aliasad106** [comment]
Okay so the password was shown on the end of deployments for all users in console. The password was same for all users.
