### ISSUE TITLE
Migrate to python3

### ISSUE THREAD

**Issue by jackivanov** [trailofbits/algo#1024]
https://docs.ansible.com/ansible/2.5/reference_appendices/python_3_support.html
We need to get rid of python2 support.
Ansible 2.5 and above have support for Python 3. Previous to 2.5, the Python 3 support was considered a tech preview.

**Comment by dguido** [comment]
oooo controversial. Let's hold off on doing this until macOS Mojave comes out. I'm hoping python3 is included by default, which will make this a lot easier.

**Comment by jackivanov** [comment]
Oh sorry for misunderstanding. I meant to use python3 on the server side in order simplify the installation and get rid of some tasks as commented here - https://github.com/trailofbits/algo/pull/976#discussion_r200800708

**Comment by dguido** [comment]
Oh! Yeah that's totally fine.
