### ISSUE TITLE
DNS Resolution Fails for default EC2 install on commit e6281bc7

### ISSUE THREAD

**Issue by azundo** [trailofbits/algo#1025]
### OS / Environment (where do you run Algo on)

```
Linux ip-172-16-254-167 4.15.0-1010-aws #10-Ubuntu SMP Thu May 24 08:41:34 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

### Cloud Provider (where do you deploy Algo to)

```
AWS EC2
```

### Summary of the problem
Run through the default installation instructions on the latest master branch, selecting EC2.
Try connecting to the VPN. DNS does not work.

### Steps to reproduce the behavior

1. Download latest master branch (e6281bc7) Run `./algo` and install on EC2 with defaults
2. Connect on OSX using the mobileconfig
3. `ping google.com` hangs
4. `ping 8.8.8.8` succeeds

I backed up to commit d56f5018, reinstalled and everything worked fine.

### Full log

```
```

**Comment by jackivanov** [comment]
Related to how Ansible work with handlers. Fixed here -  https://github.com/trailofbits/algo/pull/976

**Comment by TC1977** [comment]
I just ran into this problem with a fresh cloud install onto AWS EC2 from Mac OS X High Sierra. Install works fine, VPN connection works fine, but I can't browse websites from client. I wonder if it's related to #1022. I selected adblocking, though. After I edited /etc/dnscrypt-proxy/dnscrypt-proxy.toml to comment out the "user=nobody" line, then restarted the service, I could browse websites from client fine.

**Comment by notDavid** [comment]
Fyi, i ran into this problem when installing [todays master](https://github.com/trailofbits/algo/tree/53d1113881e6b951cb5162ba987c5f583d918f9b) to my own Ubuntu 18.04 server (i selected the "block ads" option.)
No dns resolution on the Vpn clients, and on the algo server terminal, this did **not** work:
```
dig @127.0.0.1 -p 53 github.com
dig @172.16.0.1 -p 5353 github.com
```

The solution for me was to modify `/etc/dnscrypt-proxy/dnscrypt-proxy.toml` and set `ipv6_servers = false`, followed by `systemctl restart dnscrypt-proxy.service`.

Apparently dnscrypt just "stops" and doesn't use ipv4 either, if ipv6 isn't working (i have no idea why ipv6 isn't working by the way.) 🤷🏼‍♂️

**Comment by TC1977** [comment]
@notDavid That sounds a lot like it was mentioned in #930, although I didn't see any explanation for why dnscrypt-proxy will do that, and I couldn't find anything in the dnscrypt-proxy repo about it.
