### ISSUE TITLE
SMB Connection From one computer to another (client side)

### ISSUE THREAD

**Issue by SecKarma** [trailofbits/algo#1027]
### OS / Environment (where do you run Algo on)

```
Linux me 4.16.0-1-amd64 #1 SMP Debian 4.16.5-1 (2018-04-29) x86_64 GNU/Linux
```

### Cloud Provider (where do you deploy Algo to)

```
Digital Ocean, but i didnt use the script to deploy the whole thing, i manually set it up (using local installation)
```

### Summary of the problem
Lets say I have 2 servers/computers (contains data, files, dbs) that are connected as clients to a main server (algo server). let's call these computers 1 and 2.
how can i connect 1 to 2 or vice versa using SMB protocol. note that both servers have SMB enabled and are accessible locally. (used to work with openvpn).

edit: after i removed the following drop rules:

```
-A FORWARD -s 10.19.48.0/24 -d 10.19.48.0/24 -j DROP
-A FORWARD -s 10.19.48.0/24 -d 10.19.49.0/24 -j DROP
-A FORWARD -s 10.19.49.0/24 -d 10.19.48.0/24 -j DROP
-A FORWARD -s 10.19.49.0/24 -d 10.19.49.0/24 -j DROP
```

I was able to ssh to computer 2 from computer 1 through the VPN, and i was able to login via FTP, but still SMB not working.. it says "Server Timed out"

### Steps to reproduce the behavior
1. Connect to algo on both clients (computers 1 and 2)
2. try to access computer 2 from computer 1 via SMB

**Comment by hyperbart** [comment]
Experiencing this issue too, wasn't there when I was running Algo on Ubuntu 16.04 couple of weeks ago.

**Comment by SecKarma** [comment]
This shouldn't be closed as it didn't solve the issue.. https://github.com/trailofbits/algo/pull/1028#issuecomment-407017907

**Comment by SecKarma** [comment]
Worked, Thanks a lot for the quick fix!
