### ISSUE TITLE
Anyone know how to configure a VPN in Windows 10 S Mode?

### ISSUE THREAD

**Issue by Watney** [trailofbits/algo#1032]
I run an Algo server on a Digital Ocean droplet. I'd like to connect a new Windows on ARM laptop to the Algo server. My ARM laptop runs Windows 10 in S Mode. In S Mode, you don't have access to Power Shell, and you can only run apps from the Store. 

Does anyone have suggestions on how I might connect to my Algo Server? Thanks!

**Comment by SecKarma** [comment]
source: zdnet.com

> The Windows 10 S Driver Requirements page notes that a number of Windows components are “blocked from executing on Windows 10 S.”
> The long list includes the following tools that many IT pros and developers would consider essential:
> bash.exe, cdb.exe, cmd.exe, cscript.exe, csi.exe, dnx.exe, kd.exe, lxssmanager.dll, msbuild.exe, ntsd.exe, powershell.exe, powershell_ise.exe, rcsi.exe, reg.exe, regedt32.exe, windbg.exe, wmic.exe, wscript.exe.
> A colleague confirmed that even the Windows Command Processor, cmd.exe, can’t run interactively in Windows 10 S.

Link: https://www.zdnet.com/article/a-closer-look-at-what-windows-10-s-can-and-cant-do/

**Comment by Watney** [comment]
Thanks, SecKarma for reaching out. Please let me ask my question differently: 

Does anyone know how to add an Algo connection in Windows 10 from Settings>Network & Internet>VPN>Add a VPN connection? 

I have another Windows machine that connects to an Algo server, so I tried to copy the settings to my Windows in S Mode laptop. I ran `mmc.exe` and manually added `cacert.pem` as a root certificate and the `windows.p12` file as a user certificate for all users. Then I configured everything in the VPN connection the same. 

But, alas, it fails. I get various errors depending on the day. This morning, "policy match error." And, last night it was something about "VPN server ... is not responding." 

It looks like all of the tweaks the Windows installation setup script configures cannot be produced manually. Can anyone advise please? Thanks so much!!

**Comment by SecKarma** [comment]
No Problem, but if you're still asking about "how-to" for Windows S.. then you really need to open and read the link I provided as it explains why almost 85% of windows stuff won't work normally on S.
other than that you might want to notice that the reason of using powershell is to bypass execution policies.

Literally, there's **no way** Algo can run on Windows S

**Comment by Watney** [comment]
Thanks, cheers!

**Comment by dguido** [comment]
@Watney I'm sure there's a way to get an Algo config onto a Windows 10 S box. Yes, you can't just run a PowerShell script but there should be other ways to configure the relevant bits. I'm not a Windows admin so I'll wait to see if someone else can chime in here.

**Comment by SecKarma** [comment]
why all my answers are marked by you @dguido as off topic? i'm an IT admin, I'm not answering randomly and i'm aware of what I type. tell me 1 thing that is off topic in what i said up? and in all other opened issues

**Comment by dguido** [comment]
Sorry @SecKarma, I read and understood what you were trying to contribute but most of your answers were either answering questions the OP did not ask or were incorrect.

**Comment by jackivanov** [comment]
We've decided to deprecate IKEv2 for windows #1493. Please, use WireGuard
