### ISSUE TITLE
SIP over Algo VPN

### ISSUE THREAD

**Issue by monatis** [trailofbits/algo#1034]
### OS / Environment (where do you run Algo on)

```
Linux algo 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

### Cloud Provider (where do you deploy Algo to)

```
Digital Ocean
```

### Summary of the problem

SIP clients cannot register when connected to Algo VPN. I'm using softphone on my Android for VOIP communication for my company. Algo is running fine both on Windows 10 and Android; however, I cannot register my SIP client over Algo VPN connection. Do I need to open a port on my Algo server or something?

### Steps to reproduce the behavior

1. Run `./algo` script and install Algo on your provider.
2. Install PortSIP (or another softphone) app on your Android phone, and make sure that you can register your SIP account.
3. Install WireGuard app on your Android phone and connect to your Algo VPN using the provided WireGuard  configuration file.
4. Open your softphone app again, and see that the SIP account has already been unregistered, and it cannot re-register when connected to your Algo VPN.

**Comment by jackivanov** [comment]
Nothing to do with Algo. Check the firewall your sip server

**Comment by SimonBrazell** [comment]
@monatis I'm experiencing this same issue, did you end up resolving it? 

For me the SIP server URL resolves to an RFC1918 address, so for starters I needed to modify the `dnscrypt-proxy` `ip-blocklist` to allow the address range that it uses, pretty weird but that's the way the provider has done it...

This gets me a little further with registration requests now going out to the server but I never receive a response, works fine when not connected to Algo.
