### ISSUE TITLE
Unable to manually establish connection

### ISSUE THREAD

**Issue by djendacott** [trailofbits/algo#1036]
I am trying to incorporate my new algo VPN into an Apple Configurator profile for iOS. As such it does not allow the importing of mobileconfig files - the connection must be established manually.

I'm having trouble finding the right credentials to enter when setting up the VPN manually on iOS. Here's what I think it should be -

Connection type: IKEv2

Server: 123.45.678.90 (server IP)
Remote Identifier: 123.45.678.90 (server IP)
Local Identifier: john

Machine Authentication: None
Certificate Type: ECDSA384 
Server Certificate Issuer Common Name: john
Server Certificate Common Name: John

Enable EAP: No
Dead Peer Connection Rate: Medium

Disable Redirects: No
Disable Mobility and Multihoming: No
Use IPv4 / IPv6 Internal Subnet Attributes: No
Enable perfect forward secrecy: No
Enable certificate revocation check: No

IKE SA Params (Same settings for Child SA Params)
Encryption Algorithm: AES-256
Integrity Algorithm: SHA2-256
Diffie-Hellman Group: 14
Lifetime in Minutes:1440 

Proxy Setup: None

However I cannot establish a connection. Does anyone know what I am doing wrong?

**Comment by SecKarma** [comment]
use Airdrop to transfer the mobconfig file from a Mac to your iPhone, and the file will automatically be triggered as soon as it finishes being transferred.

**Comment by dguido** [comment]
@djendacott: You should be able to import the auto-generated Apple Profiles into Configurator to see what settings are required! The most important bits are to ensure the cipher strengths match up and that you have the right certificates imported.
