### ISSUE TITLE
Pyyaml Error When Installing

### ISSUE THREAD

**Issue by buggles333** [trailofbits/algo#1037]
### OS / Environment (where do you run Algo on)

```
Linux algo-vpn 4.4.0-130-generic #156-Ubuntu SMP Thu Jun 14 08:53:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

### Cloud Provider (where do you deploy Algo to)

```
DigitalOcean Ubuntu Droplet
```

### Summary of the problem
When attempting to setup Algo using the instructions provided, I run the following command...

```
python -m virtualenv --python=`which python2` env &&
    source env/bin/activate &&
    python -m pip install -U pip &&
    python -m pip install -r requirements.txt
```

And I get the following error...

`azure-cli-core 2.0.42 has requirement pyyaml~=4.2b4, but you'll have pyyaml 3.13 which is incompatible.`

Anyone any ideas how to resolve?

**Comment by TC1977** [comment]
It’s some dependency issue, and has been around for a couple of weeks, but hasn’t seemed to affect anything. Just proceed with the installation.

**Comment by buggles333** [comment]
Thanks for confirming, had suspected it wouldn't affect things but wanted to make sure
