### ISSUE TITLE
reinstall problem

### ISSUE THREAD

**Issue by xhdix** [trailofbits/algo#1050]
After installing through the following file:
https://github.com/trailofbits/algo/archive/master.zip

In Windows 10, I received the following error:
**Policy Match Error**

And I came to this address:
https://github.com/trailofbits/algo/commit/8e5e6d50884cab651ace243d1e0685082150a8db

To get the latest changes, I received the file again from git:
git clone https://github.com/trailofbits/algo.git

After completing the steps in ./algo, I got this error:
```
TASK [wireguard : Generate public keys] **********************************************************************************************************************
 [WARNING]: Unable to find 'configs/x.x.x.x/wireguard//private/username' in expected paths.

fatal: [localhost]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'file'. Error was a <class 'ansible.errors.AnsibleError'>, original message: could not locate file in lookup: configs/x.x.x.x/wireguard//private/username"}

```

**What should I do?** 
Error because // is in the address?

**Comment by xhdix** [comment]
I deleted the wireguard files
The message "Your Algo server is running" is displayed
But ` lsof -i:500` does not have active program.
I rebooted server and done the `./algo` steps again. But it's the same as before.
**How to manually run algo?**

**Comment by jackivanov** [comment]
The best way to reinstall or upgrade the instance is to rebuild it from scratch

**Comment by IlyaGulya** [comment]
For someone who will face the same problem.
You simply need to remove all *.lock files at /etc/wireguard/
```
sudo rm -rf /etc/wireguard/*.lock
```
