### ISSUE TITLE
Fix for windows 10 VPN connection problems "parameter is incorrect" error

### ISSUE THREAD

**Issue by alexmelSC** [trailofbits/algo#1051]
Hi,

Solved this issue myself but saw no mention on here. 

I recently moved to a new server where I have Algo VPN but kept getting a weird error "parameter is incorrect" when connection to it. 

SOLUTION:

If you install the Windows 10 ps1 file (as noted in the installation instructions) and when you try to connect is says "parameter is incorrect" then so the following:

1. Clear the Networking caches

Run windows cmd window (click windows start menu, type 'cmd', right click on 'Command Prompt' and select "Run as Administrator").

type command below
netsh int ip reset

then type
netsh int ipv6 reset

then type
netsh winsock reset

Restart your computer.

2. Reset Device Manager adaptors

    Open Device Manager
    Find Network Adapters
    Uninstall WAN Miniport drivers (IKEv2, IP, IPv6, etc)
    Click Action > Scan for hardware changes
    The adapters you just uninstalled should come back

The VPN connection then works. 

Hope this helps someone.

**Comment by nerrons** [comment]
Worked like a charm. Thank you dguido.

**Comment by saadat99** [comment]
It works but is there an easier fix? I don't like to do this on all my machines
What causes this issue?

**Comment by trottit** [comment]
Parameter  Incorrect is a problem I have and followed the fix instructions.Still getting the same message and starting to come to the conclusion that there is a corrupt  file on the system.Any ideas from any one who has been  tormented from this would be greatly appreciated. In the meantime good luck and  keep  up the brilliant work.Kind regards to you all.

**Comment by soulmercy** [comment]
> Parameter Incorrect is a problem I have and followed the fix instructions.Still getting the same message and starting to come to the conclusion that there is a corrupt file on the system.Any ideas from any one who has been tormented from this would be greatly appreciated. In the meantime good luck and keep up the brilliant work.Kind regards to you all.

First problem I meet  is modem problem. I first click the "reset network" in Setting -> Network and then restart PC, but problem turn to same with you(Parameter Incorrect). Then I tried this solution, after 1st step, the problem still occur. But after 2nd step the problem finally resolved.

**Comment by minblock** [comment]
It truly does

**Comment by qianniancc** [comment]
This is useful to me, thank you.

**Comment by teadrinkingbear** [comment]
AWESOME! Just signed up to thank you! This was so struggling as malfunctioning VPN is equivalent to death in China. You are my savior and make my day.

**Comment by kylekoren** [comment]
You are a godsend! Thank you so much!

**Comment by BrandX3** [comment]
Thanks!

**Comment by mushroomcaps** [comment]
@alexmelSC registered just to say thanks!  After spending an hour trying to mirror my desktop to my laptop (which worked fine) and spending a few minutes with IPVanish chat support to no avail, I finally stumbled across this thread and lo and behold... it worked!  Big thank you to you.  Much appreciated.

**Comment by SerenityFire** [comment]
Great Thank you :)

**Comment by MohammadBnei** [comment]
Thanks !

**Comment by 641bill** [comment]
Absolute genius!!! Many thanks, finally solved this : )

**Comment by davidlemaitre** [comment]
Thanks from 2020

**Comment by andyarcha** [comment]
Thank you so much. I have been on hours trying to get this working. Your post has made me so happy!!!!!!!

**Comment by wkj954** [comment]
Adding one more vote of thanks...just tried this after a lot of time wasted on other efforts and this worked immediately...thumbs up!

**Comment by rajagangavarapu1** [comment]
Thank you so much , it helped a lot

**Comment by rwperkinsjr** [comment]
Banging my head against the wall with this until I found your instructions. Boom, connection on every protocol now. After days of looking you saved me... thank you.

**Comment by rchinnuraj** [comment]
Thank you very much!! it's worked!!

**Comment by b4ku** [comment]
I made a Github account just to say that this worked great for me. Thanks bro

**Comment by Peanut-88** [comment]
Thanks a lot !

**Comment by rajthampi** [comment]
Thank you! I had many troubles post KB4557957 (Windows 10 v 2004) & one of them was connecting to work VPN on IKEV2. Man, don't have words to appreciate your tip. I'm a developer, got three different database technologies, half dozen development tools installed and configured...and was going to format the goddamn thing & landed on your solution!

**Comment by vvillagra** [comment]
Thanks!!!! I was thinking also of reinstalling everthing! It works perfectly!

**Comment by humberto-garza** [comment]
Worked like a charm! Thank you!!!

**Comment by aci20** [comment]
I love you.  Thanks!

**Comment by jwkunz** [comment]
Worked for me.  Thanks!

**Comment by magnusStillTrying** [comment]
Thanks! Been looking for a solution for a long time. Registered to say thank you.

**Comment by POLIROID** [comment]
Thanks man!, this fix my problem

**Comment by oppalla** [comment]
I had this issue, nothing related to algo, but you just save me a lot of time, after some wrong troubleshooting. thanks so much mate!

**Comment by nirav4119** [comment]
Thanks Man, this helped

**Comment by erwincadenas** [comment]
You have my gratitude! I hope you're doing well

**Comment by alexmelSC** [comment]
I am genuinely surprised people still find this useful. Merry Christmas all.

**Comment by xholicka** [comment]
Helped again. Thx.

**Comment by RookieZoe** [comment]
Very useful note, thanks bro.

**Comment by Pentadome** [comment]
Thanks.

Microsoft humor strikes yet again,

**Comment by pojusoi** [comment]
Made my VPN working  - great

**Comment by Dopewaffl3** [comment]
Thank you so much for updating this and telling us your solution! The first one helped my overall internet speeds and the 2nd set of steps actually fixed my VPN. Thank you so much!

**Comment by Hannes-Kruger** [comment]
Thanks for sharing

**Comment by rubert-lab** [comment]
Thanks from 2021!

**Comment by Tomah27** [comment]
Thanks :)

**Comment by norbertroamsys** [comment]
@alexmelSC : You made my day 👍.
One remark: My first try was to only delete the WLAN Miniport drivers that are relevant for me: IKEv2 and PPPOE.
This was not sufficient: After removing all WLAN Miniport drivers both protocols work again.
Thanks again!

**Comment by T-Six** [comment]
Thanks! 🙏

**Comment by Beckwithi** [comment]
Thanks for your post, "The parameter is incorrect." error had me baffled with Microsoft's AO VPN, I'd tries so many things and I'd got to the stage of almost giving up and rebuilding my computer (Windows 10 20H2 Enterprise). I'd already tried to uninstall and reinstall the IKEv2 WAN Miniport, but seeing your post I also uninstalled IP and IPv6 and hey presto, no reboot, Device and User Tunnels now connecting and back on AO VPN.

Thanks...

Reset Device Manager adaptors

Open Device Manager
Find Network Adapters
Uninstall WAN Miniport drivers (IKEv2, IP, IPv6 etc) <- I only needed to do IKEv2, IP and IPv6.
Click Action > Scan for hardware changes
The adapters you just uninstalled should come back

**Comment by MemnoCh242** [comment]
Did not work for me, unfortunately. :(
But I found another solution in https://serverfault.com/a/965275. So maybe you could add that.

**Comment by blazejwiecha** [comment]
Works well . Thank You

**Comment by JustoStyle** [comment]
Works perfect. Thanks!!!

**Comment by kshigapov** [comment]
For those, who still get error 87 after clearing the networking caches, check that Internet Connection Sharing ICS service is running.

**Comment by elpedrolu** [comment]
It works, thank you so much.

**Comment by tomsarduy** [comment]
man, you just saved me from a mental health institute

**Comment by JuanjoTarditi** [comment]
You're still saving people's lifes, man! Step 2 worked for me. Thank you very much!

**Comment by Swipe650** [comment]
Thanks, you just saved me a long drive to the office

**Comment by ProfessionelNoob** [comment]
Still works like a charm!

**Comment by ishrarg** [comment]
Thanks, this works for me. I spent 2 hours to find the issue. But I fixed it in 5 minutes by your solution. God bless you.

**Comment by abmdev86** [comment]
This helped me as well.. Crazy that this is been a 3 year issue? Thanks for the advice!
