### ISSUE TITLE
easy installer script

### ISSUE THREAD

**Issue by adamwbb** [trailofbits/algo#1054]
for those running on Ubuntu 18.04 heres a easy installer script that will do everything for you.

https://pastebin.com/JPnxJHqg

This script will doo all steps in the instrucitons with minimal input (only input is the editing of the configuration file and the steps in the ./algo file.)

**Comment by dguido** [comment]
Neat! You should include a brief reference in the comments to use stdin to preselect the options you want.

**Comment by adamwbb** [comment]
sadly my coding in bash is not at the level to figure out stdin yet however if someone knows how they are free to contribute to improve this script more.

**Comment by heyitswither** [comment]
Maybe use tar instead of unzip so you don't have something extra to install

**Comment by giteshraheja** [comment]
hey, the main guide tells to unzip the algo server. where should i unzip the files through filezilla?
