### ISSUE TITLE
failed with error code 1 in /tmp/pip-install-s53EdQ/pycairo/

### ISSUE THREAD

**Issue by isrro777** [trailofbits/algo#1057]
### Windows 10

```
Running virtualenv with interpreter /usr/bin/python2
New python executable in /home/ravi_debian/env/bin/python2
Not overwriting existing python script /home/ravi_debian/env/bin/python (you must use /home/ravi_debian/env/bin/python2)
Installing setuptools, pkg_resources, pip, wheel...done.
Collecting cryptography==1.7.1 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/82/f7/d6dfd7595910a20a563a83a762bf79a253c4df71759c3b228accb3d7e5e4/cryptography-1.7.1.tar.gz
Collecting enum34==1.1.6 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/c5/db/e56e6b4bbac7c4a06de1c50de6fe1ef3810018ae11732a50f15f62c7d050/enum34-1.1.6-py2-none-any.whl
Collecting idna==2.2 (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/6b/f4/bb42887fb16eb5f5957897fec9e16d18c56dd8cdd2a729c13947ed786b92/idna-2.2-py2.py3-none-any.whl
Collecting ipaddress==1.0.17 (from -r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/9c/06/9c02897c07943697e4be028c874565892f16756828e02c1178fad5384c32/ipaddress-1.0.17-py2-none-any.whl
Collecting keyring==10.1 (from -r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/89/1a/c8a755e54c91cd4106c17fe72f0389d5403164acad9a44e9171209f8fb0f/keyring-10.1-py2.py3-none-any.whl
Collecting keyrings.alt==1.3 (from -r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/cd/ce/09a5beb323578366f4d1cfd674311a865d3ba8aae2eb1ee5398a94d5d663/keyrings.alt-1.3-py2.py3-none-any.whl
Collecting pyasn1==0.1.9 (from -r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/69/be/e8946f7867b84b0e61a613f6fd56f63266190b1a470f945178f7cbc4d0ae/pyasn1-0.1.9-py2.py3-none-any.whl
Collecting pycrypto==2.6.1 (from -r requirements.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/60/db/645aa9af249f059cc3a368b118de33889219e0362141e75d4eaf6f80f163/pycrypto-2.6.1.tar.gz
Collecting pygobject==3.22.0 (from -r requirements.txt (line 9))
  Could not find a version that satisfies the requirement pygobject==3.22.0 (from -r requirements.txt (line 9)) (from versions: 3.27.0, 3.27.1, 3.27.2, 3.27.3, 3.27.4, 3.27.5, 3.28.0, 3.28.1, 3.28.2, 3.28.3, 3.29.1.dev0, 3.29.2.dev0)
No matching distribution found for pygobject==3.22.0 (from -r requirements.txt (line 9))
```

```
Collecting pygobject==3.28.3
  Using cached https://files.pythonhosted.org/packages/e0/e8/1e4f21800015a9ca153969e85fc29f7962f8f82fc5dbc1ecbdeb9dc54c75/PyGObject-3.28.3.tar.gz
Collecting pycairo>=1.11.1 (from pygobject==3.28.3)
  Using cached https://files.pythonhosted.org/packages/68/76/340ff847897296b2c8174dfa5a5ec3406e3ed783a2abac918cf326abad86/pycairo-1.17.1.tar.gz
Building wheels for collected packages: pygobject, pycairo
  Running setup.py bdist_wheel for pygobject ... error
  Complete output from command /home/ravi_debian/env/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-qUBl1z/pygobject/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-FHc8O8 --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/pygtkcompat
  copying pygtkcompat/__init__.py -> build/lib.linux-x86_64-2.7/pygtkcompat
  copying pygtkcompat/generictreemodel.py -> build/lib.linux-x86_64-2.7/pygtkcompat
  copying pygtkcompat/pygtkcompat.py -> build/lib.linux-x86_64-2.7/pygtkcompat
  creating build/lib.linux-x86_64-2.7/gi
  copying gi/__init__.py -> build/lib.linux-x86_64-2.7/gi
  copying gi/_constants.py -> build/lib.linux-x86_64-2.7/gi
  copying gi/_error.py -> build/lib.linux-x86_64-2.7/gi
  copying gi/_option.py -> build/lib.linux-x86_64-2.7/gi
  copying gi/_ossighelper.py -> build/lib.linux-x86_64-2.7/gi
  copying gi/_propertyhelper.py -> build/lib.linux-x86_64-2.7/gi
  copying gi/_signalhelper.py -> build/lib.linux-x86_64-2.7/gi
  copying gi/docstring.py -> build/lib.linux-x86_64-2.7/gi
  copying gi/importer.py -> build/lib.linux-x86_64-2.7/gi
  copying gi/module.py -> build/lib.linux-x86_64-2.7/gi
  copying gi/pygtkcompat.py -> build/lib.linux-x86_64-2.7/gi
  copying gi/types.py -> build/lib.linux-x86_64-2.7/gi
  creating build/lib.linux-x86_64-2.7/gi/repository
  copying gi/repository/__init__.py -> build/lib.linux-x86_64-2.7/gi/repository
  creating build/lib.linux-x86_64-2.7/gi/overrides
  copying gi/overrides/GIMarshallingTests.py -> build/lib.linux-x86_64-2.7/gi/overrides
  copying gi/overrides/GLib.py -> build/lib.linux-x86_64-2.7/gi/overrides
  copying gi/overrides/GObject.py -> build/lib.linux-x86_64-2.7/gi/overrides
  copying gi/overrides/Gdk.py -> build/lib.linux-x86_64-2.7/gi/overrides
  copying gi/overrides/Gio.py -> build/lib.linux-x86_64-2.7/gi/overrides
  copying gi/overrides/Gtk.py -> build/lib.linux-x86_64-2.7/gi/overrides
  copying gi/overrides/Pango.py -> build/lib.linux-x86_64-2.7/gi/overrides
  copying gi/overrides/__init__.py -> build/lib.linux-x86_64-2.7/gi/overrides
  copying gi/overrides/keysyms.py -> build/lib.linux-x86_64-2.7/gi/overrides
  running build_ext
  'pkg-config' not found.
  Arguments: ('pkg-config', '--print-errors', '--exists', u'glib-2.0 >= 2.38.0')

  ----------------------------------------
  Failed building wheel for pygobject
  Running setup.py clean for pygobject
  Running setup.py bdist_wheel for pycairo ... error
  Complete output from command /home/ravi_debian/env/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-qUBl1z/pycairo/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-B0_iO9 --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/cairo
  copying cairo/__init__.py -> build/lib.linux-x86_64-2.7/cairo
  copying cairo/__init__.pyi -> build/lib.linux-x86_64-2.7/cairo
  copying cairo/py.typed -> build/lib.linux-x86_64-2.7/cairo
  running build_ext
  'pkg-config' not found.
  Command ['pkg-config', '--print-errors', '--exists', 'cairo >= 1.13.1']

  ----------------------------------------
  Failed building wheel for pycairo
  Running setup.py clean for pycairo
Failed to build pygobject pycairo
Installing collected packages: pycairo, pygobject
  Running setup.py install for pycairo ... error
    Complete output from command /home/ravi_debian/env/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-qUBl1z/pycairo/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-2FreoL/install-record.txt --single-version-externally-managed --compile --install-headers /home/ravi_debian/env/include/site/python2.7/pycairo:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/cairo
    copying cairo/__init__.py -> build/lib.linux-x86_64-2.7/cairo
    copying cairo/__init__.pyi -> build/lib.linux-x86_64-2.7/cairo
    copying cairo/py.typed -> build/lib.linux-x86_64-2.7/cairo
    running build_ext
    'pkg-config' not found.
    Command ['pkg-config', '--print-errors', '--exists', 'cairo >= 1.13.1']

    ----------------------------------------
Command "/home/ravi_debian/env/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-qUBl1z/pycairo/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-2FreoL/install-record.txt --single-version-externally-managed --compile --install-headers /home/ravi_debian/env/include/site/python2.7/pycairo" failed with error code 1 in /tmp/pip-install-qUBl1z/pycairo/
```

```
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  pkg-config
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 63.3 kB of archives.
After this operation, 193 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian stretch/main amd64 pkg-config amd64 0.29-4+b1 [63.3 kB]
Fetched 63.3 kB in 3s (20.4 kB/s)
Selecting previously unselected package pkg-config.
(Reading database ... 25691 files and directories currently installed.)
Preparing to unpack .../pkg-config_0.29-4+b1_amd64.deb ...
Unpacking pkg-config (0.29-4+b1) ...
Setting up pkg-config (0.29-4+b1) ...
```
Collecting pygobject==3.28.3
  Using cached https://files.pythonhosted.org/packages/e0/e8/1e4f21800015a9ca153969e85fc29f7962f8f82fc5dbc1ecbdeb9dc54c75/PyGObject-3.28.3.tar.gz
Collecting pycairo>=1.11.1 (from pygobject==3.28.3)
  Using cached https://files.pythonhosted.org/packages/68/76/340ff847897296b2c8174dfa5a5ec3406e3ed783a2abac918cf326abad86/pycairo-1.17.1.tar.gz
Building wheels for collected packages: pygobject, pycairo
  Running setup.py bdist_wheel for pygobject ... error
  Complete output from command /home/ravi_debian/env/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-s53EdQ/pygobject/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-1KtNjL --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/pygtkcompat
  copying pygtkcompat/__init__.py -> build/lib.linux-x86_64-2.7/pygtkcompat
  copying pygtkcompat/generictreemodel.py -> build/lib.linux-x86_64-2.7/pygtkcompat
  copying pygtkcompat/pygtkcompat.py -> build/lib.linux-x86_64-2.7/pygtkcompat
  creating build/lib.linux-x86_64-2.7/gi
  copying gi/__init__.py -> build/lib.linux-x86_64-2.7/gi
  copying gi/_constants.py -> build/lib.linux-x86_64-2.7/gi
  copying gi/_error.py -> build/lib.linux-x86_64-2.7/gi
  copying gi/_option.py -> build/lib.linux-x86_64-2.7/gi
  copying gi/_ossighelper.py -> build/lib.linux-x86_64-2.7/gi
  copying gi/_propertyhelper.py -> build/lib.linux-x86_64-2.7/gi
  copying gi/_signalhelper.py -> build/lib.linux-x86_64-2.7/gi
  copying gi/docstring.py -> build/lib.linux-x86_64-2.7/gi
  copying gi/importer.py -> build/lib.linux-x86_64-2.7/gi
  copying gi/module.py -> build/lib.linux-x86_64-2.7/gi
  copying gi/pygtkcompat.py -> build/lib.linux-x86_64-2.7/gi
  copying gi/types.py -> build/lib.linux-x86_64-2.7/gi
  creating build/lib.linux-x86_64-2.7/gi/repository
  copying gi/repository/__init__.py -> build/lib.linux-x86_64-2.7/gi/repository
  creating build/lib.linux-x86_64-2.7/gi/overrides
  copying gi/overrides/GIMarshallingTests.py -> build/lib.linux-x86_64-2.7/gi/overrides
  copying gi/overrides/GLib.py -> build/lib.linux-x86_64-2.7/gi/overrides
  copying gi/overrides/GObject.py -> build/lib.linux-x86_64-2.7/gi/overrides
  copying gi/overrides/Gdk.py -> build/lib.linux-x86_64-2.7/gi/overrides
  copying gi/overrides/Gio.py -> build/lib.linux-x86_64-2.7/gi/overrides
  copying gi/overrides/Gtk.py -> build/lib.linux-x86_64-2.7/gi/overrides
  copying gi/overrides/Pango.py -> build/lib.linux-x86_64-2.7/gi/overrides
  copying gi/overrides/__init__.py -> build/lib.linux-x86_64-2.7/gi/overrides
  copying gi/overrides/keysyms.py -> build/lib.linux-x86_64-2.7/gi/overrides
  running build_ext
  Package glib-2.0 was not found in the pkg-config search path.
  Perhaps you should add the directory containing `glib-2.0.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'glib-2.0' found
  Command '('pkg-config', '--print-errors', '--exists', u'glib-2.0 >= 2.38.0')' returned non-zero exit status 1

  ----------------------------------------
  Failed building wheel for pygobject
  Running setup.py clean for pygobject
  Running setup.py bdist_wheel for pycairo ... error
  Complete output from command /home/ravi_debian/env/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-s53EdQ/pycairo/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-jPHRtH --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/cairo
  copying cairo/__init__.py -> build/lib.linux-x86_64-2.7/cairo
  copying cairo/__init__.pyi -> build/lib.linux-x86_64-2.7/cairo
  copying cairo/py.typed -> build/lib.linux-x86_64-2.7/cairo
  running build_ext
  Package cairo was not found in the pkg-config search path.
  Perhaps you should add the directory containing `cairo.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'cairo' found
  Command '['pkg-config', '--print-errors', '--exists', 'cairo >= 1.13.1']' returned non-zero exit status 1

  ----------------------------------------
  Failed building wheel for pycairo
  Running setup.py clean for pycairo
Failed to build pygobject pycairo
Installing collected packages: pycairo, pygobject
  Running setup.py install for pycairo ... error
    Complete output from command /home/ravi_debian/env/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-s53EdQ/pycairo/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-kJOBu1/install-record.txt --single-version-externally-managed --compile --install-headers /home/ravi_debian/env/include/site/python2.7/pycairo:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/cairo
    copying cairo/__init__.py -> build/lib.linux-x86_64-2.7/cairo
    copying cairo/__init__.pyi -> build/lib.linux-x86_64-2.7/cairo
    copying cairo/py.typed -> build/lib.linux-x86_64-2.7/cairo
    running build_ext
    Package cairo was not found in the pkg-config search path.
    Perhaps you should add the directory containing `cairo.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'cairo' found
    Command '['pkg-config', '--print-errors', '--exists', 'cairo >= 1.13.1']' returned non-zero exit status 1

    ----------------------------------------
Command "/home/ravi_debian/env/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-s53EdQ/pycairo/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-kJOBu1/install-record.txt --single-version-externally-managed --compile --install-headers /home/ravi_debian/env/include/site/python2.7/pycairo" failed with error code 1 in /tmp/pip-install-s53EdQ/pycairo/
```
<!--- 
python -m pip install --pre --upgrade pygobject==3.28.3
--->
### Cloud Provider (where do you deploy Algo to)
<!--- 
If you deploy to a cloud provider specify the provider here.
--->

```
PUT THE OUTPUT HERE
```

### Summary of the problem
<!--- I'm Trying to install algo, and i keep getting errors after errors. I tried to install requirements. while installing pugobject it gives errors -->



### Steps to reproduce the behavior
<!--- Describe the steps how to reproduce the problem. -->

1. Do this..
2. Do that..
3. 

### Full log
<!--- Put here the FULL LOG after you run the ./algo script -->

```
PUT THE OUTPUT HERE
```

**Comment by TC1977** [comment]
Don't know much about Win 10, but the usual install procedure is to `cd algo-master` before you install the dependencies. See https://github.com/trailofbits/algo/blob/master/docs/deploy-from-windows.md

**Comment by isrro777** [comment]
I didn't include that above, but yes, of course i did that.

**Comment by TC1977** [comment]
I'm just asking because from the first line you pasted it looks like everything is getting installed into `/home/ravi_debian/env/bin/python2`, which isn't the usual path. Usual path for me is `.../algo-master/env/bin/python`.

**Comment by dguido** [comment]
You can try asking in Gitter for support. Also, try the ansible2.5 branch.
