### ISSUE TITLE
Improve Windows client instructions

### ISSUE THREAD

**Issue by dguido** [trailofbits/algo#1059]
On https://github.com/trailofbits/algo/blob/master/docs/client-windows.md under Manual Installation, we could probably instead use `Set-ExecutionPolicy Unrestricted -Scope Process` for step 3 and then remove step 5

**Comment by moeinrahimi** [comment]
what software we can use for connecting to algo on windows 10 ?

**Comment by TC1977** [comment]
No software needed! It's native support. Just search for "VPN" in settings and click on the "Algo VPN" that's been installed, then click "Connect". Note that Win 10 doesn't support the nifty "Connect on demand" options that MacOS and iOS do, so you have to remember to do this when you want to activate the VPN. (I'm not by any means an expert though. Just installed my first Win10 client a few days ago.)
