### ISSUE TITLE
Cannot SSH into new Algo instance

### ISSUE THREAD

**Issue by gittalicious** [trailofbits/algo#1060]
Algo VPN successfully set up on Digital Ocean.

I attempt to SSH into the server from my Mac using terminal: ssh root@x.x.x.x -i ~/.ssh/algo.pem
This produces the following message:  Permission denied (publickey)

Any suggestions for how I can access the server via SSH?

**Comment by gittalicious** [comment]
And now when I try to SSH into it, there is no response:  connect to host x.x.x.x port 22: Operation timed out

VPN still works though

Any suggestions?

**Comment by TC1977** [comment]
Sorry if this is too basic, but did you copy algo.pem to the ~/.ssh/ directory? And is SSH access enabled in the DO firewall?

**Comment by gittalicious** [comment]
Yes, I did copy algo.pem to that directory. I have no idea whether SSH access is enabled in the DO firewall - the DO instance was set up using the instructions on this website, from the terminal in mac, using all the standard settings.  I have set up algo instances on DO before, and have not had any difficulty with SSH access.  But I have not been able to SSH into several algo instances that I have set up in the last few days (have tried setting up now instances several times over the last few days) - no difference in what I am doing at my end, suggesting that something has changed in the way Algo is being set up on DO.

**Comment by TC1977** [comment]
I don't follow the DO code changes very closely, but I don't think it's been messed with recently, and I'd suggest it's more likely to be a problem with the key permissions on your local machine. I get that error when I mistype the key file name. Check out this link (among many others): https://askubuntu.com/questions/311558/ssh-permission-denied-publickey

**Comment by TC1977** [comment]
Ping is disabled by default on my firewall thru AWS. So I'm not too surprised by that. The server is obviously there since VPN works. Check that the algo.pem permissions are set to 700 as in the link above.

**Comment by gittalicious** [comment]
Changed the permission and retried. The connection just times out, never connects at all.

**Comment by gittalicious** [comment]
The permissions fixed it. Thanks.

**Comment by TC1977** [comment]
Great! Close the issue?
