### ISSUE TITLE
Help on connecting to Algo VPN from my iOS app

### ISSUE THREAD

**Issue by dateattoken** [trailofbits/algo#1061]
Hello,

I did setup Algo VPN on my new DigitalOcean droplet and  I tried this VPN on both macOS/iOS using .mobileconfig  file, and it work well.

But I need to write a class to connect to my VPN from my iOS app. 

I followed this tutorial: http://blog.moatazthenervous.com/create-a-vpn-connection-with-apple-swift/ 
The VPN configuration has beend added to the device , but I can't connect to it . I tried both IPSEC/IKEv2 , tried authentication mode None/Certificate , I can't find the sharedSecret in Algo so I can't try sharedSecret mode.

I also tried to build wireguard for iOS, used the content of .conf file and paste into the app, but still cant connect

![img_8793](https://user-images.githubusercontent.com/39333428/44132012-be3f06dc-a080-11e8-8008-b5686251a030.jpg)

Can anyone give me the right direction to connect ?

Thank you very much

**Comment by dguido** [comment]
You might want to join the Empire Hacking Slack and ask there. This is not the right place.
