### ISSUE TITLE
Algo should generate wireguard client configs suitable for non-mobile clients

### ISSUE THREAD

**Issue by pvg** [trailofbits/algo#1068]
Currently the Algo generates a WG client configuration file for Android clients that does not enable WireGuard's connection keep-alive feature. This is presumably makes sense on a phone but for desktop clients behind NAT, you generally always want it enabled. The feature is briefly described here: 

https://www.wireguard.com/quickstart/#nat-and-firewall-traversal-persistence

To enable it in a client configuration, the [Peer] section should incline a line like 

`PersistentKeepalive = 25`

This would make the client send a send a keepalive every 25 seconds.

**Comment by davidemyers** [comment]
Could you explain the problem you're having that this option fixes?

**Comment by pvg** [comment]
Pretty much exactly what it says in the linked WG doc.
