### ISSUE TITLE
Wireguard client setup on macOS?

### ISSUE THREAD

**Issue by olalonde** [trailofbits/algo#1072]
Is it possible to setup a Wireguard client on Mac? I couldn't find from the docs. If not, are there any files (e.g. that `Config.conf` file from the tunsafe docs) that would be useful for me to set it up manually, e.g. using [tunsafe](https://tunsafe.com/osx)?

edit: there is a `<username>.conf` file in wireguard/ directory, going to try that

**Comment by olalonde** [comment]
`sudo tunsafe myusername.conf` works but it appears to be quite slow

**Comment by dguido** [comment]
I'd rather stick with the official clients.

**Comment by olalonde** [comment]
Sure, I thought tunsafe was the only macOS client.

**Comment by dguido** [comment]
`brew install wireguard-tools` uses the wireguard-go userspace driver
