### ISSUE TITLE
Update Users feature is stuck after todays update

### ISSUE THREAD

**Issue by dijeesh** [trailofbits/algo#1073]
### OS / Environment (where do you run Algo on)

```
Linux xxx 4.15.0-1020-aws #20-Ubuntu SMP Fri Aug 17 14:24:30 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

PLAY [User management] ************************************************************************************************************************************************

```

### Cloud Provider (where do you deploy Algo to)
<!--- 
AWS EC2
--->

```
PUT THE OUTPUT HERE
```

### Summary of the problem
<!--- Describe the problem -->

Unable to add new users, ./algo update-users is stuck at PLAY [User management]. This is started after today's updates.



### Steps to reproduce the behavior
<!--- Describe the steps how to reproduce the problem. -->

1. Add new users in config.cfg
2. Run ./algo update-users


### Full log
<!--- Put here the FULL LOG after you run the ./algo script -->

```
PUT THE OUTPUT HERE
```

**Comment by jackivanov** [comment]
You can't update users on your old servers with the new code. Use the old code before this release or rebuild the server from scratch

**Comment by dijeesh** [comment]
Issue No #1 :

1. Provisioned new Ubuntu 16.04 EC2 instance in VPC Public Subnet and attached EIP 

2. Ran following steps to install Algo

```sudo apt-get install software-properties-common && sudo apt-add-repository ppa:ansible/ansible
sudo apt-get update && sudo apt-get install ansible python-pip build-essential python-dev
pip install virtualenv
pip install --upgrade pip
git clone https://github.com/trailofbits/algo
cd algo
python -m virtualenv env && source env/bin/activate && python -m pip install -U pip && python -m pip install -r requirements.txt
./algo```

3. The installation will get failed at this point.

```
TASK [dns_encryption : Include tasks for Ubuntu] **********************************************************************************************************************
included: /root/algo/roles/dns_encryption/tasks/ubuntu.yml for localhost
FAILED - RETRYING: Add the repository (10 retries left).
FAILED - RETRYING: Add the repository (9 retries left).
FAILED - RETRYING: Add the repository (8 retries left).
FAILED - RETRYING: Add the repository (7 retries left).
FAILED - RETRYING: Add the repository (6 retries left).
FAILED - RETRYING: Add the repository (5 retries left).
FAILED - RETRYING: Add the repository (4 retries left).
FAILED - RETRYING: Add the repository (3 retries left).
FAILED - RETRYING: Add the repository (2 retries left).
FAILED - RETRYING: Add the repository (1 retries left).

TASK [dns_encryption : Add the repository] ****************************************************************************************************************************
fatal: [localhost]: FAILED! => {"attempts": 10, "changed": false, "msg": "Failed to connect to launchpad.net at port 443: [Errno -3] Temporary failure in name resolution"}

PLAY RECAP ************************************************************************************************************************************************************
localhost                  : ok=58   changed=28   unreachable=0    failed=1
```

**Comment by dijeesh** [comment]
And in Ubuntu 18.04,  Installation worked after selecting No for _Do you want to install a DNS resolver on this VPN server, to block ads while surfing?_  But update-user is still getting failed.

Ref https://github.com/trailofbits/algo/issues/1076
