### ISSUE TITLE
AWS cleanup documentation

### ISSUE THREAD

**Issue by hermitsy** [trailofbits/algo#1077]
I am wondering if someone would be able to contribute a AWS (or other cloud provider) cleanup script? 

I've been trying out with AlgoVPN for a bit now and its a pain to cleanup manually after testing. I will post one as soon as I can create it but I am curious if someone has already done it.

**Comment by jackivanov** [comment]
All that you need is just to delete the particular cloud formation stack. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-console-delete-stack.html

**Comment by jackivanov** [comment]
Should be added to the docs
