### ISSUE TITLE
macOS The certificate could not be verified

### ISSUE THREAD

**Issue by aliismayilov** [trailofbits/algo#1086]
### OS / Environment (where do you run Algo on)

```
Darwin Alis-MacBook-Pro.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
```

### Cloud Provider (where do you deploy Algo to)

```
digitalocean
```

### Summary of the problem

Cannot load mobileconfig on my macOS device. After series of confirmations, I input my CA password and confirm the installation with my local admin password. I get the following system error message:

* title: Profile installation failed.
* body: The certificate could not be verified (authentication error).

### Steps to reproduce the behavior

1. Double-click on .mobileconfig file.
2. Accept the installation steps.
3. Input CA password.
4. Accept the installation with local admin password.
5. Installation failed.

### Full log

<img width="667" alt="profiles" src="https://user-images.githubusercontent.com/993934/44770423-4c4f1600-ab68-11e8-8e5f-98741a3aae18.png">

**Comment by jackivanov** [comment]
Why are you putting the CA password? You need to input the p12, but no CA
