### ISSUE TITLE
Create vpn on Scaleway. Error

### ISSUE THREAD

**Issue by mximarch** [trailofbits/algo#1087]
### OS / Environment (where do you run Algo on)

```
Darwin MacBook-Pro.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
```

### Cloud Provider (where do you deploy Algo to)

```
Scaleway
```

### Summary of the problem

Error when i create vpn on scaleway

### Steps to reproduce the behavior

1. ./algo
2. answer question
3. and nothing

### Full log

```
PLAY [Ask user for the input] ********************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************
ok: [localhost]
[pause]
What provider would you like to use?
    1. DigitalOcean
    2. Amazon EC2
    3. Vultr
    4. Microsoft Azure
    5. Google Compute Engine
    6. Scaleway
    7. OpenStack (DreamCompute optimised)
    8. Install to existing Ubuntu 18.04 server (Advanced)
  
Enter the number of your desired provider
:
6

TASK [pause] *************************************************************************************************************************************************
ok: [localhost]

TASK [Set facts based on the input] **************************************************************************************************************************
ok: [localhost]
[pause]
Name the vpn server
[algo]
:


TASK [pause] *************************************************************************************************************************************************
ok: [localhost]
[pause]
Do you want macOS/iOS clients to enable "VPN On Demand" when connected to cellular networks?
[y/N]
:


TASK [pause] *************************************************************************************************************************************************
ok: [localhost]
[pause]
Do you want macOS/iOS clients to enable "VPN On Demand" when connected to Wi-Fi?
[y/N]
:


TASK [pause] *************************************************************************************************************************************************
ok: [localhost]
[pause]
Do you want to install a DNS resolver on this VPN server, to block ads while surfing?
[y/N]
:


TASK [pause] *************************************************************************************************************************************************
ok: [localhost]
[pause]
Do you want each user to have their own account for SSH tunneling?
[y/N]
:


TASK [pause] *************************************************************************************************************************************************
ok: [localhost]
[pause]
Do you want the VPN to support Windows 10 or Linux Desktop clients? (enables compatible ciphers and key exchange, less secure)
[y/N]
:


TASK [pause] *************************************************************************************************************************************************
ok: [localhost]
[pause]
Do you want to retain the CA key? (required to add users in the future, but less secure)
[y/N]
:


TASK [pause] *************************************************************************************************************************************************
ok: [localhost]

TASK [Set facts based on the input] **************************************************************************************************************************
ok: [localhost]

PLAY [Provision the server] **********************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************
ok: [localhost]

TASK [Generate the SSH private key] **************************************************************************************************************************
ok: [localhost]

TASK [Generate the SSH public key] ***************************************************************************************************************************
ok: [localhost]
[cloud-scaleway : pause]
Enter your auth token (https://www.scaleway.com/docs/generate-an-api-token/)
 (output is hidden):

TASK [cloud-scaleway : pause] ********************************************************************************************************************************
ok: [localhost]
[cloud-scaleway : pause]
Enter your organization name (https://cloud.scaleway.com/#/billing)
:
f245aa9f-0216-53ac-a2f2-5d39b9dd42d9

TASK [cloud-scaleway : pause] ********************************************************************************************************************************
ok: [localhost]
[cloud-scaleway : pause]
What region should the server be located in?
    1. par1
    2. ams1
  
Enter the number of your desired region
[par1]
:
2  

TASK [cloud-scaleway : pause] ********************************************************************************************************************************
ok: [localhost]

TASK [cloud-scaleway : Set scaleway facts] *******************************************************************************************************************
ok: [localhost]

TASK [cloud-scaleway : Check if server exists] ***************************************************************************************************************
ok: [localhost]

TASK [cloud-scaleway : Get the organization id] **************************************************************************************************************
ok: [localhost]

TASK [cloud-scaleway : Get total count of images] ************************************************************************************************************
ok: [localhost]

TASK [cloud-scaleway : Get images] ***************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'scaleway_auth_token' is undefined\n\nThe error appears to have been in '/Users/user/Downloads/algo-master/roles/cloud-scaleway/tasks/main.yml': line 51, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Get images\n      ^ here\n"}

TASK [cloud-scaleway : debug] ********************************************************************************************************************************
ok: [localhost] => {
    "fail_hint": [
        "Sorry, but something went wrong!", 
        "Please check the troubleshooting guide.", 
        "https://trailofbits.github.io/algo/troubleshooting.html"
    ]
}

TASK [cloud-scaleway : fail] *********************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed as requested from task"}

PLAY RECAP ***************************************************************************************************************************************************
localhost                  : ok=22   changed=0    unreachable=0    failed=2   
```

**Comment by mximarch** [comment]
TASK [cloud-scaleway : pause] **********************************************************************************************************************
ok: [localhost]
[cloud-scaleway : pause]
What region should the server be located in?
    1. par1
    2. ams1
  
Enter the number of your desired region
[par1]
:
2

TASK [cloud-scaleway : pause] **********************************************************************************************************************
ok: [localhost]

TASK [cloud-scaleway : Set scaleway facts] *********************************************************************************************************
ok: [localhost]

TASK [cloud-scaleway : Check if server exists] *****************************************************************************************************
ok: [localhost]

TASK [cloud-scaleway : Get the organization id] ****************************************************************************************************
ok: [localhost]

TASK [cloud-scaleway : Get total count of images] **************************************************************************************************
ok: [localhost]
ok: [localhost] => (item=1)
ok: [localhost] => (item=2)
ok: [localhost] => (item=3)
ok: [localhost] => (item=4)
ok: [localhost] => (item=5)
ok: [localhost] => (item=6)
ok: [localhost] => (item=7)
ok: [localhost] => (item=8)
ok: [localhost] => (item=9)
ok: [localhost] => (item=10)

TASK [cloud-scaleway : Get images] *****************************************************************************************************************

TASK [cloud-scaleway : Set image id as a fact] *****************************************************************************************************
included: /Users/user/Downloads/algo-master/roles/cloud-scaleway/tasks/image_facts.yml for localhost
included: /Users/user/Downloads/algo-master/roles/cloud-scaleway/tasks/image_facts.yml for localhost
included: /Users/user/Downloads/algo-master/roles/cloud-scaleway/tasks/image_facts.yml for localhost
included: /Users/user/Downloads/algo-master/roles/cloud-scaleway/tasks/image_facts.yml for localhost
included: /Users/user/Downloads/algo-master/roles/cloud-scaleway/tasks/image_facts.yml for localhost
included: /Users/user/Downloads/algo-master/roles/cloud-scaleway/tasks/image_facts.yml for localhost
included: /Users/user/Downloads/algo-master/roles/cloud-scaleway/tasks/image_facts.yml for localhost
included: /Users/user/Downloads/algo-master/roles/cloud-scaleway/tasks/image_facts.yml for localhost
included: /Users/user/Downloads/algo-master/roles/cloud-scaleway/tasks/image_facts.yml for localhost
included: /Users/user/Downloads/algo-master/roles/cloud-scaleway/tasks/image_facts.yml for localhost
ok: [localhost] => (item=None)
ok: [localhost] => (item=None)
ok: [localhost] => (item=None)
ok: [localhost] => (item=None)
ok: [localhost] => (item=None)

TASK [cloud-scaleway : Create a server] ************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'organization_id' is undefined\n\nThe error appears to have been in '/Users/user/Downloads/algo-master/roles/cloud-scaleway/tasks/main.yml': line 68, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Create a server\n      ^ here\n"}

TASK [cloud-scaleway : debug] **********************************************************************************************************************
ok: [localhost] => {
    "fail_hint": [
        "Sorry, but something went wrong!", 
        "Please check the troubleshooting guide.", 
        "https://trailofbits.github.io/algo/troubleshooting.html"
    ]
}

TASK [cloud-scaleway : fail] ***********************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed as requested from task"}

PLAY RECAP *****************************************************************************************************************************************
localhost                  : ok=36   changed=0    unreachable=0    failed=2

**Comment by jackivanov** [comment]
Sorry, can't reproduce. Check the organisation name you are putting in.

**Comment by ylixir** [comment]
@mximarch and for anyone else who stumbles across this issue, for the `scaleway_org` was not my organization id or my access key. it was simply my own name as listed in the billing page.
