### ISSUE TITLE
Add configuration option for "Always On VPN" mode without putting device into Supervised Mode

### ISSUE THREAD

**Issue by ndtob** [trailofbits/algo#109]
Somewhere in the ALGO question and answer script (or as a configuration option in the configuration file) an option should exist to force "always on VPN" mode.

Normally this is only possible when the device is wiped and put into "supervised" mode.

However with the following configuration profile XML it is possible to force an Always on VPN mode.

_**Connect to VPN when connected to a network over Cellular or WiFi network interface:**_

```
<key>OnDemandEnabled</key>
  <integer>1</integer>
<key>OnDemandRules</key>
  <array>
    <dict>
      <key>Action</key>
        <string>Connect</string>
      <key>InterfaceTypeMatch</key>
        <string>WiFi</string>
    </dict>
    <dict>
      <key>Action</key>
        <string>Connect</string>
      <key>InterfaceTypeMatch</key>
        <string>Cellular</string>
    </dict>
  </array>
```

Enable "on demand" option
If interface type = wifi or cellular
Action -> connect VPN.

Alternatively the "cellular" section may be set to "Disconnect" to only force VPN when connected to wifi, for instance this would always ensure the user was connected through a VPN when on any WiFi network (starbucks, home wifi or unsecured public wifi). This is highly desirable because it would always ensure a secure connection when routing through any wifi connection.

_**Connect to VPN only when connected to a network over the WiFi interface:**_

```
<key>OnDemandEnabled</key>
  <integer>1</integer>
<key>OnDemandRules</key>
  <array>
    <dict>
      <key>Action</key>
        <string>Connect</string>
      <key>InterfaceTypeMatch</key>
        <string>WiFi</string>
    </dict>
    <dict>
      <key>Action</key>
        <string>Disconnect</string>
      <key>InterfaceTypeMatch</key>
        <string>Cellular</string>
    </dict>
  </array>

```

Since a user is always connected to WiFi or Cellular the VPN will always be on.
If user puts device into airplane mode neither interface will be enabled.

Caveat:
If the VPN cannot be reached the device will have no network connectivity.
The user will have to go into the VPN options on the device and manually turn off "connect on demand" in order to get normal connectivity back.

There may be a way configure some ruleset to drop VPN connection if VPN cannot be reached but this requires further research.

**Comment by ndtob** [comment]
Example configuration of disabling VPN when on a known WiFi SSID (like your home WiFi) is connected.

Auto-enable VPN when connected to any other WiFi SSID and optionally when connected to cellular.


		```
		<key>OnDemandEnabled</key>
				<integer>1</integer>
				<key>OnDemandRules</key>
				<array>
					<dict>
						<key>Action</key>
						<string>Disconnect</string>
						<key>InterfaceTypeMatch</key>
						<string>WiFi</string>
						<key>SSIDMatch</key>
						<array>
							<string><!-- home wifi network name--></string>
						</array>
					</dict>
					<dict>
						<key>Action</key>
						<string>Connect</string>
						<key>InterfaceTypeMatch</key>
						<string>WiFi</string>
					</dict>
					<dict>
						<key>Action</key>
						<string>Connect</string>
						<key>InterfaceTypeMatch</key>
						<string>Cellular</string>
					</dict>
					<dict>
						<key>Action</key>
						<string>Ignore</string>
					</dict>
				</array>

```

**Comment by NoahO** [comment]
This would be pretty life-changing if it works.. 

However I have one question: would this stop you authenticating to public wifi captive portals?

**Comment by ndtob** [comment]
@NoahO it does work, I've been testing it without issue.

I have also recently tested it at Starbucks and another captive portal. It first prompts you through the captive portal first, after you connect it then auto-connects to the VPN.

Of course there may be some weird captive portal where this fails but you can also disable the VPN to go through captive portal first.

**Comment by gunph1ld** [comment]
OK, gentlemen.
Implemented in the [OnDemandRules_mobileconfig](https://github.com/trailofbits/algo/commit/29de003b2d47399c5f2f0a43bcccf02c339bd8b3) branch

There are 3 new options:
```
Do you want to enable VPN always when connected to Wi-Fi?
Do you want to exclude trust Wi-Fi networks from VPN usage? (eg: Your home network. Comma-separated value, eg: HomeMeganet,OfficeSuperWifi,AlgoWiFi)
Do you want to enable VPN always when connected to the cellular network?
```

**Comment by gunph1ld** [comment]
Merged

**Comment by noeltimothy** [comment]
Hi, I'm new to this product but the downside of the on demand VPN is that users can easily disable it by toggling the "connect on demand" switch. 
Has anyone tried the AlwaysOn vpn type on a non-supervised device? Apple don't explicitly mention supervised mode for this but other sources do.

**Comment by Jikodis** [comment]
@noeltimothy Look at this issue and you will see this topic discussed. My understanding is that Always On VPN can only work on a supervised device. There are some templates on the attached issue that you can fill in using the generated mobileconfig files from AlgoVPN as a reference.

#278
