### ISSUE TITLE
How can I make some IPs not use VPN?

### ISSUE THREAD

**Issue by LuGuoHuas** [trailofbits/algo#1091]
Hello ,I am from China, I often need to use a foreign VPN connection network to access Google or DuckDuckGo. If I have been driving a VPN, it will affect my visit to China's website, because China's network is not friendly to foreign countries.So I want to be able to skip some IP (for example, China's IP) without using a VPN, or there are other ways.
thank.

**Comment by TC1977** [comment]
My best guess is to do this, you will need to know what IP range you want to access without the VPN, and then edit /etc/ipsec.conf on your Algo server after you deploy it. Here's an example.
https://wiki.strongswan.org/projects/strongswan/wiki/UsableExamples

Hope someone else can think of a better way. Coming up with a range of all IP addresses in China will be pretty tough.

**Comment by LuGuoHuas** [comment]
Ok, thank you very much for your answer. Maybe this VPN solution is not suitable for me.
