### ISSUE TITLE
How can allow traffic only between connected clients with same user?

### ISSUE THREAD

**Issue by joesatriani10** [trailofbits/algo#1092]
Hello i have to connect two aplication between (Server app and Terminal app),  I set 
`BetweenClients_DROP: false`

and it works but all users can connect with all users, is there a way to allow traffic only between clients with same users but blocking traffic between clients with diferent users?

Like:

```
"User A client" <-------allow traffic with-------> "User A client"
"User B client" <-------allow traffic with-------> "User B client"
"User C client" <-------allow traffic with-------> "User C client"
```

```
"User A client" <-------block traffic with-------> "User B client"
"User A client" <-------block traffic with-------> "User C client"
"User B client" <-------block traffic with-------> "User C client"

```
Thank you

**Comment by jackivanov** [comment]
There is no native way unless you write an [up/down](https://wiki.strongswan.org/projects/strongswan/wiki/Updown) script specifically for your needs. Also, you would need to enable the updown plugin [here](https://github.com/trailofbits/algo/blob/master/roles/vpn/defaults/main.yml#L38)

**Comment by joesatriani10** [comment]
thank you @jackivanov
