### ISSUE TITLE
Installing to Lightsail (documentation)

### ISSUE THREAD

**Issue by cdolle** [trailofbits/algo#1094]
So, [people](https://twitter.com/axiomdata/status/1035024584070684672) [everywhere](https://twitter.com/ExtremePaperC/status/1034299244079792128) are wondering how to take advantage of Amazon's [new Lightsail pricing](https://aws.amazon.com/about-aws/whats-new/2018/08/amazon-lightsail-announces-50-percent-price-drop-and-two-new-instance-sizes/) by setting up an Algo instance.  Although it's not officially supported, it's actually really easy and only takes like 15 minutes to get up and running.

1. Create a key pair (see: [here](https://www.digitalocean.com/docs/droplets/how-to/add-ssh-keys/create-with-openssh/) if you need help with this step)
2. Log into Lightsail and upload your newly created SSH key to the region in which you plan to deploy your VPN server
3. Create a new $3.50/mo Ubuntu 16.04 LTS Lightsail instance in your desired location
4. Create and attach a static IP address to your new instance
5. Log into the newly created instance and run: `do-release-upgrade` - this will update the 16.04 instance to 18.04
6. Follow the directions in README.md to deploy the Algo server, selecting "Install Algo to existing Ubuntu 18.04 server" when prompted and using the user "ubuntu" when asked
7. Once Algo finishes installing, log into Lightsail and open UDP ports 500 and 4500.

#682

**Comment by axiomdata** [comment]
This is a nice breakdown but for some reason even following these instructions I get stuck here:

TASK [dns_encryption : Include tasks for Ubuntu] *************************************************************************************************************
included: /home/axiomdata/algo/roles/dns_encryption/tasks/ubuntu.yml for 52.38.3.195
FAILED - RETRYING: Add the repository (10 retries left).

It fails after 10 retries.

Any help getting past this spot would be great!

Thanks!

**Comment by jackivanov** [comment]
@axiomdata Could you file a separate issue? That's probably related to resolv.conf

**Comment by axiomdata** [comment]
@jackivanov Issue has been filed separately. Thanks.

**Comment by xytzw** [comment]
Tried the above in post #1. Installs OK. But can anyone share how to open upd ports 500 and 4500? Tried  `iptables -A INPUT -p udp -m multiport --dports 500,4500 -j ACCEPT` but it doesn't do the trick as my iphone still can't connect to the server.

@johnyluyte
worked for me as below:
when prompted 'enter the IP address' type: localhost
when prompted 'enter the public IP address' type your stastic ip address assigned to the instance

**Comment by johnyluyte** [comment]
@xytzw I remember entering both prompts with my public static IP address. That might be the problem. Thanks!

You can login to the AWS Lightsail web console, click lightsail instance, click Network, and open both UDP ports there.
https://lightsail.aws.amazon.com/ls/webapp/home/instances

**Comment by TC1977** [comment]
@xytzw You have to open UDP 500 and 4500 in the Lightsail console. The default firewall for Lightsail is (I believe) SSH access only.

**Comment by axiomdata** [comment]
@xytzw @johnyluyte Not sure if this is relevant but I've been having issues getting this to work for a while. I finally got it to work on Android Wireguard by also opening up port 51820 which is the port wireguard tries to connect on.

**Comment by Paleo-zz** [comment]
if you notice package installations failing due to version incompatibilities, selectively upgrade the failed packages:

        sudo -H python -m pip install [package] --upgrade

tends to happen with MarkupSafe, azure-cli-core, pyopenssl, azure-mgmt-resource

**Comment by staines** [comment]
if you notice package installations failing due to version incompatibilities, selectively upgrade the failed packages:

`
sudo -H python -m pip install [package] --upgrade
`

tends to happen with MarkupSafe, azure-cli-core, pyopenssl, azure-mgmt-resource

**Comment by drejohnson** [comment]
Thanks, works perfectly!

**Comment by awkwong-whi** [comment]
I just checked the list of Lightsail Blueprint list.
For Ubuntu, the list now includes Ubuntu 18.04 LTS (blueprintId: `ubuntu_18_04`).
Here's the entry from `aws lightsail get-blueprints`:
```json
{
    "group": "ubuntu_18",
    "description": "Ubuntu 18.04 LTS - Bionic. Lean, fast and powerful, Ubuntu Server delivers services reliably, predictably and economically. It is the perfect base on which to build your instances. Ubuntu is free and will always be, and you have the option to get support and Landscape from Canonical.",
    "platform": "LINUX_UNIX",
    "productUrl": "https://aws.amazon.com/marketplace/pp/B07CQ33QKV",
    "version": "18.04 LTS",
    "licenseUrl": "https://d7umqicpi7263.cloudfront.net/eula/product/3b73ef49-208f-47e1-8a6e-4ae768d8a333/7ca21cd7-5be3-43be-8e43-07809b2ea410.txt",
    "versionCode": "1",
    "blueprintId": "ubuntu_18_04",
    "minPower": 0,
    "type": "os",
    "isActive": true,
    "name": "Ubuntu"
},
```

**Comment by moshesiegel** [comment]
Anyone now what the CLI name is for the $5 instance? I know it can be modified in library/lightsail.py but for the life of me I can't find the correct CLI name in any of the documentation.

**Comment by davidemyers** [comment]
I installed the [aws-cli](https://github.com/aws/aws-cli) tool and ran `aws lightsail get-bundles`. Based on the output I think the bundle you want is `micro_2_0`. You can change the bundle name used by Algo in `config.cfg`.

**Comment by moshesiegel** [comment]
Perfect, thanks.

**Comment by strogonoff** [comment]
Note that deploying to Lightsail requires extra IAM policy rules, the ones recommended in docs for EC2 do not suffice.

As of now Lightsail installation will fail if user follows the docs (assuming IAM user, it will probably work if AWS root credentials are given).

I am not sure what is the minimum of policies required to deploy Algo to Lightsail. To make it work in meantime, I added "lightsail:*" to action list somewhere in the policy. Far from the best, but possibly better than root credentials.

**Comment by TC1977** [comment]
@strogonoff That's because you have to use [the policy for Lightsail](https://github.com/trailofbits/algo/blob/master/docs/deploy-from-ansible.md#lightsail), not EC2. 😄 

Agreed that this should be more obvious, perhaps by adding onto the EC2 install instructions page, or making a separate one for Lightsail.

**Comment by strogonoff** [comment]
Ahh I see, didn’t find it at the time.

I believe, since minimal policies differ, it might make sense to either have one doc for AWS split into subsections, or separate docs where one handles the EC2+CloudFormation policies & the other Lightsail’s.

Either way should be discoverable enough (OTOH if the doc with Lightsail’s policies is called EC2, they might take a few extra minutes to locate)
