### ISSUE TITLE
DNS ad blocking leaking DNS

### ISSUE THREAD

**Issue by ndtob** [trailofbits/algo#110]
Either the instructions are unclear or setting up DNSMasq for adblocking fails. Setting the DNS to 172.16.0.1 when using the VPN still yields ads and no discernible difference.

Running https://www.dnsleaktest.com and http://dnsleak.com also fail.

I'm unable to confirm that upon connecting to the VPN the internal resolver is used instead of the exiting DNS server specific by the current network connection. the "SearchDomains" parameter may need to be set in the resulting profile configuration as seen here: https://developer.apple.com/library/content/featuredarticles/iPhoneConfigurationProfileRef/Introduction/Introduction.html

**Comment by gunph1ld** [comment]
I've pushed some fixes, please check ads now

**Comment by ndtob** [comment]
DNSMasq is now blocking ads, functioning quickly with no slow down and overall working correctly however the dns leak tests linked above continue to say that DNS may be leaking. I am now unsure if those tests are actually accurate. We should confirm and close this out.

**Comment by gunph1ld** [comment]
> the dns leak tests linked above continue to say that DNS may be leaking.
No idea what does it mean.
But probably, because DNSmasq is a forwarder (to Google's public DNS in our case), but not a recursive resolver.

**Comment by ndtob** [comment]
ah, then we should clarify the message at the end of the install about testing DNS leaking via those websites to avoid confusion.
