### ISSUE TITLE
OS X client configuration error

### ISSUE THREAD

**Issue by zoof** [trailofbits/algo#1109]
### OS / Environment (where do you run Algo on)

```
Linux algo 4.15.0-1018-gcp #19-Ubuntu SMP Thu Aug 16 13:38:55 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

### Cloud Provider (where do you deploy Algo to)

```
GCE
```

### Summary of the problem

username.mobileconfig not working on OS X

### Steps to reproduce the behavior

1. Double click on username.mobileconfig
2. Pop-up window: 'Enter settings for certificate "username.p12"'
3. Not sure what to type.

### Full log

```
server configuration went without a hitch -- where are the install logs stored?
```

**Comment by zoof** [comment]
My user tried configuring by command line with

```
/usr/bin/profiles -I -F username.mobileconfig
profiles install for file:'username.mobileconfig' and user:'username' returned -1 (The payload 'com.apple.security.pkcs12.41D69376-62BF-5FFC-A72D-860A08037B5C' is missing the required key 'Password'.)
```

**Comment by davidemyers** [comment]
The p12 password was included in the "Congratulations" message that was printed when Algo completed:
```
The p12 and SSH keys password for new users is 1234abcd
```
It isn't saved anywhere so be sure to make a note of it after each Algo run.

**Comment by zoof** [comment]
Right -- fortunately I copied it.  I don't have any Apple devices myself or I would have paid more attention to the message.
