### ISSUE TITLE
Digital Ocean droplet start is unreliable

### ISSUE THREAD

**Issue by ndtob** [trailofbits/algo#111]
Myself and other users of Algo have run the script multiple times, receiving fatal errors usually revolving around a failure to connect back to the droplet. It happens at different parts in the Algo setup process. Immediately repeating the Algo installation on the same DO server location would sometimes result in a successful deployment.

This problem is not reproducible as it happens randomly and I am unable to pinpoint an exact cause other than it seems to be related to the Algo script attempting to login to the DO droplet and failing due to not being able to connect even though the droplet exists and previous steps were successful. Sometimes when repeating the installation Algo will progress further in the installation, fail at another point or succeed.

The Algo script should make multiple attempts if a connect failure occurs to prevent a fatal exit of the Algo installation.

--- UPDATE

My friend Andy was having these random failures on the NYC based DO servers. The installation process would fail at different steps. Upon switching to SF server location it failed at yet another step complaining about being unable to login. He ran it once more and it completed successfully.

It would seem Algo connect to the DO droplet sometimes fails, the Algo script should definitely attempt to re-connect after a short timeout to continue the installation process instead of terminating.

**Comment by dguido** [comment]
This sounds like an unfortunate reliability issue in Digital Ocean's droplet start that we will have to try and work around. FWIW, I have never experienced issues like this and always use the NYC3 region. It would help if you could get a log of the install process in a case where it failed.

**Comment by ndtob** [comment]
So of course it's working fine now. I just tested 5 times, 5 successes across 5 locations.

I know it must have been DO having problems but we need the Algo script to at least fail sanely. Currently it fails with an error that doesn't really explain if the user or DO did something wrong. We really need to either add a time-out retry 3x or fail with some message saying DO connect had problems. Just a UI/UX thing we should spruce up.

**Comment by gunph1ld** [comment]
OK, take a look on how it will work after this fix

**Comment by ndtob** [comment]
So far every install I've done has been working. I'm sure this SSH time out will fix the issue. If I encounter a problem I'll re-open this.
