### ISSUE TITLE
Digital Ocean - Policy Match error

### ISSUE THREAD

**Issue by lance0** [trailofbits/algo#1113]
Anyone have this?

### OS / Environment (where do you run Algo on)

```
PUT THE OUTPUT HERE
```

### Cloud Provider (where do you deploy Algo to)

```
PUT THE OUTPUT HERE
```

### Steps to reproduce the behavior

1. Do this..
2. Do that..
3. 

### Full log

```
PUT THE OUTPUT HERE
```

**Comment by TC1977** [comment]
Can you be more specific and also post some logs please? Searching the issues may also be helpful.
