### ISSUE TITLE
Allow users to specify which local SSH key to use

### ISSUE THREAD

**Issue by dguido** [trailofbits/algo#112]
Users may have multiple SSH keys on the machine running the deploy.

Scenario:
1. User has SSH keys A, B, and C. A is their default key. Keys B and C are not in ssh-agent.
2. User runs an Algo deploy and specifies key B.
3. Algo spins up a new server with their API token for DigitalOcean/EC2/GCE/etc.
4. Algo attempts to login to the new server with their default key A because none was specified
5. Algo installation fails.

This is admittedly a less common use case, so I want to make this as simple as possible for users with only a single SSH key to avoid. Maybe after the prompt for which SSH key they want to use for DigitalOcean we simply ask "Is this your default key (y/n)?" then, if not, ask them for the local path to that key?

**Comment by dguido** [comment]
Alternatively, an error message asking the user "did you add your key to ssh-agent?"

If you don't want to use ssh-agent, then `ansible_ssh_private_key_file` can specify a local private key to use in the config. https://docs.ansible.com/ansible/intro_inventory.html#list-of-behavioral-inventory-parameters

**Comment by defunctio** [comment]
See #126 , this may be a viable solution.

**Comment by artemdinaburg** [comment]
I just ran into this. It looks like Ansible will always try to use ~/.ssh/id_rsa if the key is not in ssh-agent. Can we add an entry for `ansible_ssh_private_key_file` if the user specifies a non-default ssh key?

Additionally, after setup fails, the created EC2 instance is still up and has to be manually deleted. Is it possible to have some kind of failure detection to remove the newly created instance?
