### ISSUE TITLE
Static IP address when creating a VM in GCE 

### ISSUE THREAD

**Issue by joesatriani10** [trailofbits/algo#1121]
**Is your feature request related to a problem? Please describe.**
In GCE when you create a VPN using algo, the VM get a ephemeral external IP address, sometimes can change (after some days of working),  causing the VPN stops working if the user does'n know they need to change it after creating the vpn server.

 **Describe the solution you'd like**
create a VPN with a static external IP address

**Comment by TC1977** [comment]
I have no idea how to change the deploy script, but you can "promote" your ephemeral external IP to a static one using these instructions: https://cloud.google.com/compute/docs/ip-addresses/reserve-static-external-ip-address#promote_ephemeral_ip

**Comment by Firifire** [comment]
From my use scenario, the external IP address does not change unless the VM is stopped from the GCP console. 
If you restart the VM using SSH, the external IP address does change.
