### ISSUE TITLE
Issues when attempting to install Algo on CentOS 7.x

### ISSUE THREAD

**Issue by AlexShapka** [trailofbits/algo#1135]
**Describe the bug**

Trying to install Algo on CentOS 7.x by following instructions for CentOS 6.x on https://github.com/trailofbits/algo/blob/master/docs/deploy-from-redhat-centos6.md. So far the givens steps work also for CentOS 7.x except that Python 2.7 comes by default with 7.x., so you do not have to Software Collections (SCL) package.

**To Reproduce**

I am not sure will it work further, however at the moment I've the following error on CLI just after running the `pip -q install -r requirements.txt` command:

```
pip -q install -r requirements.txt
azure-cli-core 2.0.46 has requirement azure-mgmt-resource==2.0.0, but you'll have azure-mgmt-resource 1.2.2 which is incompatible.
```

**Additional context**

Please create proper documentations for installing Algo on RHEL/CentOS 7.x branch.

**Comment by AlexShapka** [comment]
Also after running the `./algo` command you have only the following options to select:

```
What provider would you like to use?
    1. DigitalOcean
    2. Amazon EC2
    3. Vultr
    4. Microsoft Azure
    5. Google Compute Engine
    6. Scaleway
    7. OpenStack (DreamCompute optimised)
    8. Install to existing Ubuntu 18.04 server (Advanced)
```

so no option for CentOS. I am proceeding with option #8 hoping it will work.

**Comment by AlexShapka** [comment]
Logging further adventure of installing Algo on CentOS 7.x. Just hit the following error, because SSH was configured to custom port for security reasons:

`fatal: [localhost]: FAILED! => {"changed": false, "elapsed": 320, "msg": "Timeout when waiting for search string OpenSSH in my_server_ip:22"}`

so Algo seems to need the default port 22 to be open and sshd to be configured to listen to it.

**Comment by davidemyers** [comment]
The only Linux that Algo supports turning into a VPN server is Ubuntu 18.04.

The Algo scripts can be run from certain other Linuxes and from macOS in order to remotely deploy VPN servers on certain cloud providers, but those servers will all be running Ubuntu 18.04 under the hood.

**Comment by AlexShapka** [comment]
> The only Linux that Algo supports turning into a VPN server is Ubuntu 18.04.
> 
> The Algo scripts can be run from certain other Linuxes and from macOS in order to remotely deploy VPN servers on certain cloud providers, but those servers will all be running Ubuntu 18.04 under the hood.

David, thanks to your heads-up I can now leave CentOS in peace and try Ubuntu 18.04 instead. 

If you can please elaborate on one more thing. I had an impression all I could run Algo VPN between my MBP and a remote VPS. Do I have to have a cloud account as required by step 1 on https://github.com/trailofbits/algo?

**Comment by davidemyers** [comment]
What Algo does is create a remote VPS for you and turn it into a VPN server, which then provides secure connectivity out to the Internet at large to your various client devices. Your MBP will use its built-in IPsec support to connect securely to your Algo server and will tunnel all network traffic through it.

So you'll want an account with one of the supported cloud providers. DigitalOcean is the easiest to get started with, and at the bottom of the main Algo page is a link to a referral code that should get you a couple of free months of use.

**Comment by AlexShapka** [comment]
Got it. Thanks a lot!
