### ISSUE TITLE
What ports need to be left as open for Algo to function properly

### ISSUE THREAD

**Issue by AlexShapka** [trailofbits/algo#1139]
Unfortunately, I was not able to add more comments on the closed https://github.com/trailofbits/algo/issues/1136, so I hope it's ok to open a new issue, considering the subject matter was not properly addressed. 

Jack, thanks for the update, however:

1. I know how to change the ports, but the problem is that as I described as soon as I change the VPN falls. There is some kind of Algo-related configuration somewhere which sets port 22 to use and I need to get it changed. So please do not mark this issue as closed unless the issue has been resolved.

2. I travel a lot, so I have dynamic address. I do appreciate your advice, but would be really nice to concentrate on the asked question.

**Comment by AlexShapka** [comment]
The reported issue could also caused by my attempt to leave only the custom port open closing all other ports, including port 22.  So maybe it is not at all about the port where SSH deamon listens to. I wonder does Algo need some particular ports to be left open?

**Comment by jackivanov** [comment]
We use 22 ports for SSH only (and ssh tunnels if enabled) and neither IPsec nor WireGuard don't depend on this port.
The only ports you need to get IPsec working are 500 and 4500 UDP and 51820 for WireGuard

**Comment by AlexShapka** [comment]
Thanks for the update, however it didn't work. Even after digging into this little bit further and finding out I needed to also leave ports 50 and 51 open for TCP, unfortunately, as soon as the firewall starts the Internet is gone. Surprisingly, SSH connection to the remote VPN server is intact, so it is not about SSH port anymore. I am afraid some more ports need to be left as open.

Just to be sure I've included all involved ports both in TCP and UDP setting of my APF firewall like so:

```
# Common inbound (ingress) TCP ports
IG_TCP_CPORTS="22,50,51,500,4500,51820"

# Common inbound (ingress) UDP ports
IG_UDP_CPORTS="50,51,500,4500,51820"
```

with no success. 

I just wonder didn't anyone before hardened the remote Ubuntu server with Algo client running in it to know the exact ports?

**Comment by AlexShapka** [comment]
I've changed the title as it is not about SSH port 22 anymore. SSH works just fine both on the default port 22 or any other custom port. However, as soon as APF starts effectively closing all the ports except mentioned in its TCP and UDP configuration settings the whole things stops working - SSH connection to the Algo client is still intact, but Internet is not available through browser or pinging any other website via CLI.

**Comment by jackivanov** [comment]
Nothing we can really do, sorry. There is nothing related to Algo in your specific case

**Comment by davidemyers** [comment]
When deploying a server, Algo installs a carefully chosen set of firewall rules. It sounds like you're installing APF on the server and wiping out all of Algo's rules, which of course will break it.

**Comment by TC1977** [comment]
> 2. I travel a lot, so I have dynamic address. I do appreciate your advice, but would be really nice to concentrate on the asked question.

Actually, once you connect to the VPN you can SSH into the server at 172.16.0.1 from your client. So you don't have to worry about the dynamic IP issue.

**Comment by AlexShapka** [comment]
> When deploying a server, Algo installs a carefully chosen set of firewall rules. It sounds like you're installing APF on the server and wiping out all of Algo's rules, which of course will break it.

I didn't know that and was concerned the Ubuntu server where  Algo runs could be hacked. So if Algo already installs firewall rules, then I'll just ditch APF and leave everything intact. If I understood correctly there is no need to further harden security of Algo server, right?

**Comment by AlexShapka** [comment]
Thanks a lot, David!

**Comment by gamma-577** [comment]
> Once Algo has done its job the only thing left to do is configure your clients. You may never need to log in to an Algo server. It will even install security updates on its own and, if enabled in `config.cfg`, reboot if required by any of these updates (such as a kernel update).
> 
> While no additional external firewall is required, many cloud providers include one by default and Algo will configure it properly. DigitalOcean does not include an external firewall by default, but I add one in order to restrict SSH access to certain addresses. My firewall looks like this:
> 
> ![](https://camo.githubusercontent.com/69492741e90bb4c94c6919724dcc2a83f549543de1175e23fe9ec8c6d5281be3/68747470733a2f2f70686f746f732e736d75676d75672e636f6d2f70686f746f732f692d4b4d6b6d6234392f302f30333632623239362f4f2f692d4b4d6b6d6234392e6a7067)

Hi @davidemyers , Your rule table worked like a rocket ! Thank you! :-)
-Gamma
