### ISSUE TITLE
Include Algo generated password in client_windows.ps1 file for Windows 10

### ISSUE THREAD

**Issue by joesatriani10** [trailofbits/algo#1143]
I change a line to Include the Algo generated password in [algo/roles/vpn/templates/client_windows.ps1.j2](https://github.com/trailofbits/algo/blob/master/roles/vpn/templates/client_windows.ps1.j2) so the users do not need to manually enter the password when installing on Windows 10 computers.

I was always doing the same to mobileconfig as described in [here](https://github.com/trailofbits/algo/pull/1140), so I see that you include that and I want to share the way I do with client_windows.ps1

I changed line 88 to make easier the installation of the profile.
from:
`$Pkcs12DecryptionPassword = Read-Host -AsSecureString -Prompt "Pkcs12DecryptionPassword"`
 to:
`$Pkcs12DecryptionPassword = ConvertTo-SecureString '{{ p12_export_password }}' -asplaintext -force`

so now you can easy run (or create a client on Java or something) in just two lines on powershell:

1.- `Set-ExecutionPolicy Unrestricted -Scope Process`
2.-  `powershell -ExecutionPolicy ByPass -File C:\path\to\windows_USER.ps1`

**Comment by TC1977** [comment]
@joesatriani10 Wanna submit a PR? Or I can do it...

**Comment by jackivanov** [comment]
It's already there

**Comment by waltirus** [comment]
Hello all! I've long been addicted to Algo as my own vpn server but recently it looks like the government learned to block the WireGuard traffic (protocol apparently - cause I tried to use WireGuard with different IP of my server , it still does not work).
So, my question is - can I return to the old protocols Algo was working with , avoiding WireGuard. I remember , there were instructions to setup Windows client using Powershell command lines, working with ps1 files and p12. Can I setup my Windows machined using that method? Is it possible to use only p12 key as I don't see ps1 file in the IP folder any more..?
