### ISSUE TITLE
Possible to add basic filtering?

### ISSUE THREAD

**Issue by bmy** [trailofbits/algo#1150]
Hi, massive Algo fan here. I'm wondering how viable it would be to add basic filtering/detection of domain names to one's Algo server. I know one tool is already supported as part of the provisioning script, but rather than use a pre-existing list (which seems like it could break certain things i don't wanna break...) i was wondering how one might filter an arbitrary list...for example:

https://github.com/AmnestyTech/investigations/blob/master/2018-08-01_nso/indicators.csv

**Comment by TC1977** [comment]
Algo uses dnsmasq for ad blocking at the DNS level. You have to install using the "block ads" option. Please check #1138 if you want to add other lists.
