### ISSUE TITLE
local webserver

### ISSUE THREAD

**Issue by ars0nboi** [trailofbits/algo#1152]
I have a webserver running on port 80 on my computer which is a dynamic ip.  I connect to the static ip of Vultr through algo vpn. So at this point my computer has a dedicated ip. What can I do to  allow my webserver on my computer to connect because it will not? 

I was able to do so with OpenVPN with iptables but when i try with algo it does not allow my local webserver to connect on port 80 of my computer. I do not want to use a dynamic dns service.

**Comment by TC1977** [comment]
This sounds like #1142. I'm sorry, I can't give you a more specific way to do this. If not, please give a more detailed explanation of what you're trying to do (no real IP addresses though).

**Comment by ars0nboi** [comment]
I want to be connected to my algovpn on my local home computer, have my webserver running on my local computer, and be able to connect to it via my chrome browser. Currently, it was not connect, the page does not load.

**Comment by jackivanov** [comment]
Please use [gitter](https://gitter.im/trailofbits/algo) to get help for such kind of questions
