### ISSUE TITLE
Unable to use search domain

### ISSUE THREAD

**Issue by cbates291** [trailofbits/algo#1156]
**Describe the bug**

I am not sure if this is a bug per se or if I am missing something in the config. I am able to connect to my Algo VPN just fine (running a local Ubuntu 18 installation) and traffic passes, etc. I am able to ping by IP, and use RDP by IP. I am unable to use SMB (which could be something else). My main issue is that I cannot search by FQDN. The Ubuntu server is able to do this without issue and has the proper search domain set but when connected through the VPN, I am unable to use the FQDN at all. It simply says it cannot find it. I have tested this on a Mac but not on Windows yet, so I apologize if this is just a Mac issue. I will be able to test on Windows on Monday so I will follow up then to confirm.

Any thoughts?

**To Reproduce**

Connect to VPN, unable to ping by servername.domain.local

**Expected behavior**

I expect to be able to ping servername or at the very least servername.domain.local and be able to resolve the IP addresses.

**Additional context**

When setting up the VPN server I did set the local dns ip to my DNS server within the config file for algo. I did NOT setup the local dns resolver when asked when running through the setup script (I did enable it once, and it did not help so i turned it off again).

**Full log**

There is nothing to display in the log since it sets up perfectly fine.

**Comment by davidemyers** [comment]
It's unusual to point Algo's client DNS at a local server as that will typically result in that server in turn issuing unencrypted DNS queries.

Could you post the portion of the log output right below the line that says,
```
--> Please include the following block of text when reporting issues:
```

**Comment by TC1977** [comment]
Unless you install with the `dns_encryption` option set to false in `config.cfg`, Algo installs dnscrypt-proxy for DNS resolution. (If you also select ad blocking during the install, it also installs dnsmasq.) Therefore your issue with *.local names is actually a dnscrypt-proxy issue. Maybe this link will help: https://github.com/jedisct1/dnscrypt-proxy/wiki/Forwarding

**Comment by cbates291** [comment]
I will get the log on Monday. As for the dns encryption part. I changed that to false so that it wouldnt be used. If it is weird to point Algo to a local server for DNS, how would you do that normally? How would I ensure that I can use my search domain? Or do I always have to use IP with this VPN?

**Comment by davidemyers** [comment]
Don't worry about the log, I just wanted to confirm your setting for DNS encryption.

Typically an Algo server is installed at a cloud provider and uses a public encrypted DNS server. An Algo server is usually used for secure egress from a local network rather than ingress into a local network.

Although I install my Algo servers in the cloud I too wish to resolve my local domain so I leave `dns_encryption: true` and use the `dnscrypt-proxy` `forwarding_rules` feature that @TC1977 linked to above.

**Comment by davidemyers** [comment]
As for SMB, it's deliberately blocked by Algo. You'll need to edit the firewall rules files on your Algo server in `/etc/iptables` to remove the blocks, then reload the firewall with `sudo systemctl restart netfilter-persistent`.

**Comment by cbates291** [comment]
I have setup the dns_encryption to true for the algo setup and edited the template so that the forwarding rules value would load the forwarding_rules.txt file. If i run dnscrypt-proxy -resolve value.value it shows the correct IP addresses but the resolver IP still shows opendns or cloudflare.

ex.
![image](https://user-images.githubusercontent.com/30803925/47313537-2d6f7c00-d60d-11e8-8c71-0f8a6cea3abc.png)

the IP's it shows are correct but does that mean its resolving correctly? When i connect to the VPN and ping that same name it doesnt resolve and says it cannot find the host.

also as for the SMB. I am just trying to use finder and do the connect to server option and use smb://IP while connected to the VPN. Is this going to need those firewall rules?

**Comment by davidemyers** [comment]
Make sure `dnscrypt-proxy` loaded your forwarding rules correctly. Run:
```shell
systemctl status dnscrypt-proxy
```
And look for:
```
Loading the set of forwarding rules from [forwarding-rules.txt]
```

Try testing DNS with the command `host` on your Algo server:
```shell
# Through dnscrypt-proxy
host myhost.mydomain 172.16.0.1
# Directly to your DNS server
host myhost.mydomain mydnsserver.mydomain
```

I'm not clear where everything is running. Are your client and SMB server on the same network? Where is your Algo server?

**Comment by cbates291** [comment]
Thanks for heads up on the status command. that showed me that the IP was failing to bind and that was my own fault so dnscrypt was not even running. I was able to resolve that and dnscrypt is now running but I am still getting the same error when doing a ping.

What am i trying to achieve with the host command? it doesnt seem to give me any info?
![image](https://user-images.githubusercontent.com/30803925/47316192-8e4e8280-d614-11e8-90e9-39c9d53d999d.png)

P.S. sorry for my ineptitude if some of my questions should be easy to do.

**Comment by davidemyers** [comment]
The `host` command should return the correct IP address for the name you look up. If you didn't get an answer when querying your own DNS server directly then there's an issue with the Algo server being able to reach your DNS server. Can you even ping your DNS server from your Algo server?

Is your Algo server on your local network or is it  in the cloud?

**Comment by cbates291** [comment]
I just ran the host command again and point to a local DNS server and it did resolve and give me the IP address. but if i point it to the 172.16.0.1 it doesnt give anything.

![image](https://user-images.githubusercontent.com/30803925/47317502-ba1f3780-d617-11e8-8d88-00b199b0dc82.png)

my forwarding-rules.txt looks like:
![image](https://user-images.githubusercontent.com/30803925/47317561-e63ab880-d617-11e8-8a09-b78621e93389.png)

**Comment by cbates291** [comment]
i did find something odd. if i run `dnscrypt-proxy -check` it says:
![image](https://user-images.githubusercontent.com/30803925/47317915-ade7aa00-d618-11e8-866b-4b47924490e6.png)
i then ran the `dnscrypt-proxy -config /path/to/file.tom1` and it doesnt give any errors but it still continues to give the message above. maybe my dnscrypt is broken?

**Comment by davidemyers** [comment]
I would try removing .16 from `forwarding-rules.txt` because it doesn't appear to be a working DNS server, then running `sudo systemctl restart dnscrypt-proxy` and checking the status.

**Comment by cbates291** [comment]
it looks like it is working after removing the .16. Not sure why that wasnt resolving correctly as it is my backup DNS server on-prem. But now it is working and I can resolve my internal servers while on the vpn. 

My only issue now is the smb functionality, so ill start looking into that. 

Thanks so much for the help on all this.

**Comment by cbates291** [comment]
I went and edited the iptables rules and changed the SMB to ACCEPT rather than DROP and it seems to all be working!

thanks again for all the help. I think I should be good now. i still have some more testing on my end but those were the big issues hanging over me. I will considered this closed and completed.
