### ISSUE TITLE
Issues installing Python requirements

### ISSUE THREAD

**Issue by chriseng** [trailofbits/algo#1160]
**Describe the bug**

```
$ python -m virtualenv --python=`which python2` env &&
>     source env/bin/activate &&
>     python -m pip install -U pip &&
>     python -m pip install -r requirements.txt
Running virtualenv with interpreter /usr/bin/python2
New python executable in env/bin/python2
Not overwriting existing python script env/bin/python (you must use env/bin/python2)
Installing distribute..............................................................................................................................................................................................done.
Installing pip...............done.
/home/ceng/algo-master/env/bin/python: No module named pip.__main__; 'pip' is a package and cannot be directly executed
```

**To Reproduce**

1. Run the command above.

**Expected behavior**

Python requirements would install.

**Additional context**

 Debian 7.11, pip 1.1. All packages up to date.

**Full log**

Didn't get that far.

**Comment by arnoldsmyth** [comment]
I am having issues also. I am running on Mac OS 10.12.6 and am having issues installing. This command:
`python -m pip install --user --upgrade virtualenv`
produces this error:
`Could not find a version that satisfies the requirement virtualenv (from versions: )
  No matching distribution found for virtualenv`

**Comment by davidemyers** [comment]
Isn't Debian 7 really old, like from 2013? Those commands run fine for me on Debian 9.

**Comment by chriseng** [comment]
Debian 7.11 was released in June 2016. Old, but not ancient.

**Comment by conorsch** [comment]
Debian 7 was indeed [released in 2013](https://en.wikipedia.org/wiki/Debian_version_history#Debian_7_(Wheezy)). Even if 7.11 is newer than that, it's reached EOL, even if you account for [community LTS support](https://wiki.debian.org/LTS). That means the system isn't receiving security updates anymore. It's not realistic for the Algo maintainers to support Debian 7. Do consider upgrading. :slightly_smiling_face:

**Comment by chriseng** [comment]
As much as I appreciate the unhelpful comments, folks, I filed the ticket because @dguido asked me to.

**Comment by jackivanov** [comment]
Well, did you try to upgrade pip first?

**Comment by dguido** [comment]
Sorry Chris, we're going to avoid supporting operating systems this old. This would result in too many hacks making it into our software.
