### ISSUE TITLE
Include option to just set up wireguard

### ISSUE THREAD

**Issue by sebasmurphy** [trailofbits/algo#1162]
**Describe the solution you'd like**
I'm new to ansible, but it looks as if all of the IKE related code is still running along with the wireguard configuration. I was wondering if it'd be worth it to add an option to just enable wireguard and skip all of the other steps related to IKE, esp given the fact that wireguard has officially been submitted for inclusion into the kernel.

**Comment by sebasmurphy** [comment]
I already have this spec'd out. Just need to finish testing before sending a pull.

**Comment by jackivanov** [comment]
@sebasmurphy any progress on this? If not, I'll do that

**Comment by sebasmurphy** [comment]
@jackivanov I got everything spec'd out and broke out strongwan into a separate role but have not gotten everything working yet. If you want to take a look at what I have your welcome to. 
If not feel free to do it, as I don't think I'll have time this week to work on it.

**Comment by jackivanov** [comment]
OK, I'll do it as a part of next refactoring. thanks

**Comment by digeratus** [comment]
Is there a new branch for this by any chance?
