### ISSUE TITLE
Port forwarding from the server to a specific client

### ISSUE THREAD

**Issue by yassineim** [trailofbits/algo#1163]
Hi, thanks for this project, it's very useful.

Is there a way I can forward certain server inbound ports to a specific client? (either by username or MAC address).
Just like what you do with your home router. Something like this: https://mullvad.net/en/guides/port-forwarding-and-mullvad/
Thanks.

**Comment by yassineim** [comment]
OK FWIW I realized it's simply a general NAT forwarding problem, and followed this https://serverfault.com/a/140626.

**Comment by vitaly-zdanevich** [comment]
@ghost is it still the correct solution for Ubuntu in AWS?

```
iptables -t nat -A PREROUTING -p tcp -i ppp0 --dport 8001 -j DNAT --to-destination 192.168.1.200:8080
iptables -A FORWARD -p tcp -d 192.168.1.200 --dport 8080 -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT
```

**Comment by vitaly-zdanevich** [comment]
@jackivanov please review

**Comment by vitaly-zdanevich** [comment]
I think this is a pretty basic case - good to add to the readme.
