### ISSUE TITLE
It can't work with google.com

### ISSUE THREAD

**Issue by happy201807** [trailofbits/algo#1167]
Hello,
I am using GCE's Ubuntu 18 to work with algo. Install everything goes smoothly, the default settings. I work with IKEV2 and WIN10, IOS10, but all have the same problem, DNS can not resolve Google, through dnsleaktest.com query, only the default setting of the ISP's DNS, this DNS default can not resolve Google, ping = 1ms, Can you tell me what to do? Wireguard seems to be the same, only Google can not open.

**Comment by happy201807** [comment]
If I install the wireguard native script on github, I can open Google after logging in. What is the problem? It seems that my ISP has a strong blockade to access Google. What problem should I solve?

**Comment by TC1977** [comment]
Can you resolve sites other than Google?

**Comment by happy201807** [comment]
Most of them are ok, I can open amazon, facebook, twitter and other websites. At first I thought this was a DNS issue. I used simplifiednscrypt as the local DNS client and ended up with the same result. I don't understand that I use IPsec or wireguard for this result, but the official website's wireguard installation script will not have this problem when using VPS itself as DNS resolution.

Can I manually modify the DNS to VPS DNS after installing the Algo script?

**Comment by happy201807** [comment]
![work without google](https://user-images.githubusercontent.com/41731934/47604888-f1d01a00-da31-11e8-8578-d62a0c838fa0.jpg)

**Comment by jackivanov** [comment]
Probably related to MTU, https://github.com/trailofbits/algo/issues/1066

**Comment by happy201807** [comment]
thanks to everyone who helped
