### ISSUE TITLE
EC2: AWS env variables as default

### ISSUE THREAD

**Issue by defunctio** [trailofbits/algo#118]
Use the environment variables for AWS keys as defined by ansible if the keys are left undefined.

**Comment by dguido** [comment]
$100 bounty! Submit a pull request and email dan@trailofbits.com to claim it. Partial solutions may be rewarded.

**Comment by defunctio** [comment]
This is resolved in the ec2updates branch, it just needs to be reviewed to make sure there are no breaking changes and merged.
