### ISSUE TITLE
Transferring the config files to be used on another device 

### ISSUE THREAD

**Issue by Sparkenstein** [trailofbits/algo#1186]
I deployed the algo on my Google Cloud successfully from my "windows subsystem for linux" yesterday. and it works fine. now I want to connect to it from my another laptop which runs fedora 28.

for that I am following [this guide](https://github.com/trailofbits/algo/blob/master/docs/client-linux.md). Fortunately for some reason the Strongswan client was already there on my machine, maybe newer versions ship with it already. So as per given instructions, I just copied `cacert.pem`, `user-name.crt` and `user-name.key` files from my windows subsystem to my fedora machine, but it's failing to connect to VPN. Am I doing something incorrect? what to do when you want to use the configs on other devices?

The error includes "AVC denial" from SeLinux and before that it asks for some password which I don't know

PS: Also, can you update the RedHat/CentOS building instructions? (considerting `yum` is deprecated now) for some reason I was not able to build Algo on my fedora even after 4-5 tries so I had to do it on Windows. Thank you for you support!

**Comment by Sparkenstein** [comment]
Update: after running `chcon -t cert_t /your/certificates/dir/*` on the directory where files were stored the connection was successful but I can't browse anything the pages keep just loading. I can ping most of the sites though but can't ping the VPN

**Comment by TC1977** [comment]
Check the troubleshooting for MTU problems?

**Comment by Sparkenstein** [comment]
Closing this issue as it's not working with any configuration. Will look into another client for desktops like wireguard in future
