### ISSUE TITLE
Windows: Parameter is incorrect

### ISSUE THREAD

**Issue by YoshiByte** [trailofbits/algo#1189]
I am genuinely not sure why my previous issue was declined, but I'm going to report it again with a screenshot.

CMD is misspelled.

![image](https://user-images.githubusercontent.com/44642289/48037894-4e22f000-e13c-11e8-9373-e4b66df5a377.png)

There is no such thing as CDM and it was a typo.

Thank you for noticing this.

**Comment by jackivanov** [comment]
Thanks
