### ISSUE TITLE
Wireguard iOS TestFlight - please help test this

### ISSUE THREAD

**Issue by digeratus** [trailofbits/algo#1190]
Straight from the Wireguard mailing list....

Hey folks,

For the last few weeks, Roopesh and I have been hard at work on the
WireGuard for iOS app. Today we're happy to share a
likely-buggy-and-broken TestFlight that you can run on your phone:
<https://testflight.apple.com/join/63I19SDT>. As usual, use at your
own risk, especially since it's alpha quality.

Please let us know about any bugs as you find them -- you can send
them to me or to team@wireguard.com. Our current TODO list lives here
[1], linked via the main project TODO list [2], and if you're an iOS
person and want to contribute code, we'd be happy to have you on
board.

The app costs $3.99 and requires an email address to sign up; we
manage all your tunnels for you in the cloud. JUST KIDDING! Like the
rest of WireGuard, the iOS app is free and open source [3]. I make
this rather tasteless joke, because of the rather surprising
quantities of people encouraging me to do the iOS stuff as proprietary
paid software, because "apple users will pay" or because "open source
is cool, but iphone folks don't care about it so you can get away with
charging" or because "none of the other vpn players are doing open
source mobile implementations" or even because "apple is more likely
to accept paid software into its app store" and so on and so forth.
But, as usual, I much prefer for this to be a community project than a
closed one, and so like everything else, it's FLOSS.

Enjoy! And do let us know about the bugs as you run into them. I'm
sure there are plenty.

Regards,
Jason

[1] https://docs.google.com/document/d/1BnzImOF8CkungFnuRlWhnEpY2OmEHSckat62aZ6LYGY
[2] https://www.wireguard.com/todo/
[3] https://git.zx2c4.com/wireguard-ios/

**Comment by digeratus** [comment]
FYI - You need to have unique conf files if you're using multiple devices.

**Comment by hakusaro** [comment]
I just ran a fresh Algo setup today & the latest Testflight version of WireGuard (0.0.20181104 (4)) worked out of the box. Pretty sweet.

**Comment by TC1977** [comment]
Sure hope Wireguard turns out to be more reliable than strongSwan and these connecting/reconnecting loops (#963) that are driving me crazy.

**Comment by happy201807** [comment]
Since the beginning of this year, I have been interested in this project. When I added the test, I found that only ios12.0 or later is supported in testflight. Will you add support for the old ios10.0 in future versions?

**Comment by happy201807** [comment]
Will the startup VPN only be available from the app, not like the built-in VPN (Algo, L2TP, etc.) like most IOS?

**Comment by jackivanov** [comment]
@happy201807 It's not the right place to address app-related questions. Ask the wireguard developers instead

**Comment by digeratus** [comment]
@happy201807 While I understand why you would want to see iOS 10 supported, iOS 12 goes back to iPhone 5S, iPad mini 2 and even the iPod touch 6th gen.

As far as startup of the VPN is concerned, those features are coming. Might even be in the upcoming TestFlight test. Here's the todo list if you want to stay informed: 
https://docs.google.com/document/d/1BnzImOF8CkungFnuRlWhnEpY2OmEHSckat62aZ6LYGY/mobilebasic

**Comment by simoncarpinter** [comment]
I quickly hooked this up to a pre-generated config from [Mullvad](https://mullvad.net) using the `qrencode` method the app recommends.  So far, so good; their "am.i.mullvad.net" service tells me I'm getting bounced through their network and Wireguard itself seems pretty robust.  Cheers for this, I'm excited :).

**Comment by marca56** [comment]
Hi all... just loaded the iOS app via Testflight and figured out how to import the current config for the app. On my Mac, I copied the wireguard folder from algo-master into my iCloud Drive. Then, I clicked the add new tunnel button and selected Create from file or archive. In the file selector, I clicked to open the folder I created on iCloud Drive. I then double clicked on the named config file and the app built the working tunnel. I tested it and it works like a charm. Very cool!

**Comment by davidemyers** [comment]
Or... you could display the QR code image that Algo generated for you on your Mac, then capture it with the camera on your iOS device. That way's a bit quicker. :smiley:

**Comment by marca56** [comment]
I did not see the QR code anywhere. I must have setup Algo before the QR code but after the wireguard set went in the build.

**Comment by digeratus** [comment]
@marca56 QR codes for Wireguard are a relatively new feature in Algo. You can find them in <<algo setup folder>>/configs/<<algo server IP>>/wireguard

**Comment by marca56** [comment]
![image](https://user-images.githubusercontent.com/26097856/48583969-671a6680-e8dd-11e8-88d4-4c76c1a5a10e.png)

Must have been done in a later version :) But OK, it *would* be easier with a QR code

**Comment by marca56** [comment]
Some feedback is in order after testing a bit yesterday. I was transitioning from home WiFi to mobile broadband, to location or public WiFi and I see that the current implementation works on all but the automatic reconnect is not very good. What I mean is that a lot of times, the tunnel either does not connect or is dropped in the case of a network change. On the other hand, just stopping and starting it again establishes the tunnel properly. I am excited to say that the performance is very good and the battery drain is hardly noticeable. The phone does not get warm. I'm looking forward to impressive improvements in handover and reconnect. Then, it can be a full time thing and easy enough for my wife and other non-techie folks too.

**Comment by mrapplegate** [comment]
Fresh install on digital ocean, running Ubuntu 18.04. No problems yet.

**Comment by monouser7dig** [comment]
> Seems like it doesn’t work well for me when changing Wi-Fi networks or from Wi-Fi to mobile network.

Same here 

Disconnect/ connect helps

**Comment by mrapplegate** [comment]
@Rohmilchkaese I have had a few problems moving from my home WiFi to AT&T cellular. Like monouser7dig said disconnect/connect fixed it.

**Comment by kristallizer** [comment]
Has anyone noticed increased bandwidth consumption? I rarely ever go over my cellular data's bandwidth limit, but I hit it in less than 15 days this month with no significant change in usage pattern and more than 70% of it was consumed by the WireGuard app.

**Comment by davidemyers** [comment]
Try removing the `PersistentKeepalive` option from your client config. Most users shouldn't need it and perhaps it should be avoided for devices that use metered data.

**Comment by kristallizer** [comment]
Thanks, I'll try it out.

**Comment by digeratus** [comment]
@davidemyers AlgoVPN needs to change the default persistentkeepalive from 25 to 0. As it is, when you get the Wireguard profile it's set to 25

**Comment by digeratus** [comment]
@mrapplegate Latest version of Wireguard should fix your connect/disconnect problem.

**Comment by davidemyers** [comment]
You no longer need TestFlight, just search for "WireGuard" in the App Store.

**Comment by jackivanov** [comment]
Then we close it :) Thanks for everytone
