### ISSUE TITLE
Profile install error in Mojave 

### ISSUE THREAD

**Issue by seifreed** [trailofbits/algo#1191]
**Describe the bug**

I  can't install the profile for MacOSx Mojave

**To Reproduce**

1. Create a standard AlgoVPN configuration
2. Double click on the mobileconfig file
3. Enter the password to confirm the installation profile

**Expected behavior**

I got an error installing the mac profile in MacOSx Mojave

**Additional context**

<img width="421" alt="screenshot 2018-11-06 at 16 26 51" src="https://user-images.githubusercontent.com/1843119/48075630-fcce3b80-e1e3-11e8-9de0-ab6f16bee7aa.png">

**Full log**

**Comment by seifreed** [comment]
Closing the issue as the error was fixed on my side. Nothing related to algoVPN

**Comment by TC1977** [comment]
Glad to hear it’s working now. 

Can you tell us what the error was, to help other people who may have the same problem?

**Comment by seifreed** [comment]
Yeah, the problem was that I put wrong the password certificare
