### ISSUE TITLE
Win 10 - certs are installed to an incorrect, hard coded location.

### ISSUE THREAD

**Issue by ndtob** [trailofbits/algo#1193]
**Describe the bug**
Apparently algo has a bug when deploying to a win10 client. When the install script is run as a user who is an administrator all is good (elevation prompt and everything works). When it’s run as a non-admin user with admin creds provided for elevation the certs are installed to an incorrect but hard coded location and a misleading error is presented. 

**To Reproduce**
Install Algo on Win10 as a non-admin user providing admin credentials.

**Expected behavior**
Certs to be installed in correct location.

**Additional context**
The github bug in this issue has bad troubleshooting steps and is going down the wrong conclusion.

**Comment by TC1977** [comment]
Can you be more specific please? What's the wrong conclusion on the troubleshooting? How can it be fixed?

Should the docs be changed to simply specify that Win 10 installation should be done from an admin account?

**Comment by jackivanov** [comment]
ping @ndtob

**Comment by dguido** [comment]
We'll take a second look at the Windows instructions when we close this ticket: https://github.com/trailofbits/algo/issues/1059

Nick, I really need more specific information. Screenshots would be best.
