### ISSUE TITLE
MacOS manual configuration 

### ISSUE THREAD

**Issue by khonakr** [trailofbits/algo#1194]
I have my Algo VPN Setup on Ubuntu Server and I do have all the .mobileconfig files.
I tested it on my iPhone with iOS 12 and it works perfectly fine.

Problem:
But Profiles is blocked on my Mac. So I cannot set it up the conventional way by just double clicking it. I do have admin access on my Mac though, just that profiles are blocked.

1. I tried:
sudo profiles -I -F /Users/kkhona/Downloads/algo.mobileconfig 
but I get the following error:
profiles install for file:'/Users/kkhona/Downloads/algo.mobileconfig' and user:'root' returned -308 (The profile could not be validated.)

2. I also tried Wireguard Mac OS client as mentioned here:
https://github.com/trailofbits/algo/blob/master/docs/client-macos-wireguard.md
I think it does connect fine, but I do not have any internet connection in that case.

3. I tried TunSafe, but that always fails in handshake, may be because of some ipv6 support.

Is there a way to setup the VPN profile manually on Mac using the VPN option in Networks + installing the required certs? I tried a couple of ways for that, but it just keeps throwing Unexpected errors.

Or is there an alternative StrongSwan / Wireguard client I am not aware of?
Any ideas will be appreciated.

**Comment by jackivanov** [comment]
Can you just open the profile in Finder? That's the simplest way for most of users

**Comment by khonakr** [comment]
@jackivanov If by finder you mean by double clicking it, no I cannot. If I double click it tries to open it with the Profiles Setting app and that is blocked on my machine. So I just receive a error saying Profiles is blocked by my administrator.

**Comment by TC1977** [comment]
Try doing it from an admin account? Use a USB drive to move the mobileconfig files.

**Comment by dguido** [comment]
Please use WireGuard on macOS
