### ISSUE TITLE
pip install -r requirements.txt failed

### ISSUE THREAD

**Issue by gunph1ld** [trailofbits/algo#120]
The problem appeared after someone added `ansible>=2.1` into `requirements.txt`

**Comment by dguido** [comment]
Derp. That was me :-(.

**Comment by gunph1ld** [comment]
The problem is, that pip can't install requirements (`libssl-dev`) for the `cryptography` python package

**Comment by gunph1ld** [comment]
There are 2 ways, either move back to the ansible ppa or add `apt-get install libssl-dev` to README.md

**Comment by dguido** [comment]
yea just remove the ansible>=2.1 and move back to the ansible ppa.

**Comment by EricSchles** [comment]
Not sure if this is a stale issue.  Installing the package now and it appears to be fine with ansible 2.1 - tested on Mac OSX and Python 3.5

okay to close? @gunph1ld
