### ISSUE TITLE
Getting an ambiguous error while trying to set my local server as VPN server

### ISSUE THREAD

**Issue by isacikgoz** [trailofbits/algo#1200]
**Describe the bug**

I am getting a failure at the TASK [common : include_tasks] phase.

**To Reproduce**

1. execute command `./algo'
2. Choices are sequentially: `9` `y` `y` `` `y` `` `y` `` `localhost` `my public ip`

**Expected behavior**

I expect it to build the required configuration and software 

**Additional context**

I want to deploy it into a Ubuntu 18.04 Docker container. I have a Docker image which has built-in sudo and a sudo user. I am attaching to the container produced from this particular image, and downloading algo then following the instructions.

- I also tried running algo with sudo, got same error
- I tried [troubleshooting](https://trailofbits.github.io/algo/troubleshooting.html#docker-failed-to-connect-to-the-host-via-ssh), though it didn't seem relevant, got same error

**Full log**

```
TASK [common : Check the system] *******************************************************************************
changed: [localhost]

TASK [common : include_tasks] **********************************************************************************
included: /home/algo/git/algo/roles/common/tasks/ubuntu.yml for localhost
failed: [localhost] (item=[u'python2.7', u'sudo']) => {"changed": false, "item": ["python2.7", "sudo"], "module_stderr": "FATAL -> Failed to fork.\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 100}

TASK [common : Ubuntu | Install prerequisites] ****************************************************************

TASK [common : debug] ******************************************************************************************
ok: [localhost] => {
    "fail_hint": [
        "Sorry, but something went wrong!", 
        "Please check the troubleshooting guide.", 
        "https://trailofbits.github.io/algo/troubleshooting.html"
    ]
}

TASK [common : fail] ******************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed as requested from task"}

PLAY RECAP ****************************************************************************************************
localhost                  : ok=27   changed=3    unreachable=0    failed=2   
```

**Comment by TC1977** [comment]
Not sure what the answer is (maybe a python version issue?), but you [shouldn't use the local install option from within a Docker container.](https://github.com/trailofbits/algo/blob/master/docs/Docker.md)

**Comment by isacikgoz** [comment]
Didn't see that, I am closing this issue for now. Thanks btw.
