### ISSUE TITLE
Unable to install environment "Install Algo's remaining dependencies"

### ISSUE THREAD

**Issue by happy201807** [trailofbits/algo#1205]
**Describe the bug**
Install Algo's remaining dependencies failed
Ubuntu18.04LTS local installation Unknown error
**To Reproduce**

1. Do this..
2. Do that..
3. ..

**Expected behavior**

**Additional context**

**Full log**
wget https://github.com/trailofbits/algo/archive/master.zip
----  https://github.com/trailofbits/algo/archive/master.zip
Resolving github.com (github.com)... 13.250.177.223, 13.229.188.59, 52.74.223.119
Connecting to github.com (github.com)|13.250.177.223|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/trailofbits/algo/zip/master [following]
----  https://codeload.github.com/trailofbits/algo/zip/master
Resolving codeload.github.com (codeload.github.com)... 13.250.162.133, 13.229.189.0, 54.251.140.56
Connecting to codeload.github.com (codeload.github.com)|13.250.162.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: ‘master.zip.2’

master.zip.2            [ <=>                ]   1.03M  --.-KB/s    in 0.08s

 (12.1 MB/s) - ‘master.zip.2’ saved [1079918]

root@:~# apt install unzip
Reading package lists... Done
Building dependency tree
Reading state information... Done
unzip is already the newest version (6.0-21ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@:~# unzip master.zip
Archive:  master.zip
1c16554b41eb45608da76a6c70c99d0be568b34b
replace algo-master/.dockerignore? [y]es, [n]o, [A]ll, [N]one, [r]ename: error:  invalid response [cd algo-m]
replace algo-master/.dockerignore? [y]es, [n]o, [A]ll, [N]one, [r]ename:
]rror:  invalid response [aster
replace algo-master/.dockerignore? [y]es, [n]o, [A]ll, [N]one, [r]ename: A
  inflating: algo-master/.dockerignore
  inflating: algo-master/.github/ISSUE_TEMPLATE/bug_report.md
  inflating: algo-master/.github/ISSUE_TEMPLATE/feature_request.md
 extracting: algo-master/.gitignore
  inflating: algo-master/.travis.yml
  inflating: algo-master/CHANGELOG.md
  inflating: algo-master/CONTRIBUTING.md
  inflating: algo-master/Dockerfile
  inflating: algo-master/LICENSE
  inflating: algo-master/PULL_REQUEST_TEMPLATE.md
  inflating: algo-master/README.md
  inflating: algo-master/algo
  inflating: algo-master/algo-docker.sh
  inflating: algo-master/algo-showenv.sh
  inflating: algo-master/ansible.cfg
  inflating: algo-master/cloud.yml
  inflating: algo-master/config.cfg
 extracting: algo-master/configs/.gitinit
  inflating: algo-master/deploy_client.yml
  inflating: algo-master/docs/client-android.md
  inflating: algo-master/docs/client-linux-wireguard.md
  inflating: algo-master/docs/client-linux.md
  inflating: algo-master/docs/client-macos-wireguard.md
  inflating: algo-master/docs/client-windows.md
  inflating: algo-master/docs/cloud-amazon-ec2.md
  inflating: algo-master/docs/cloud-azure.md
  inflating: algo-master/docs/cloud-do.md
  inflating: algo-master/docs/cloud-gce.md
  inflating: algo-master/docs/cloud-vultr.md
  inflating: algo-master/docs/deploy-from-ansible.md
  inflating: algo-master/docs/deploy-from-docker.md
  inflating: algo-master/docs/deploy-from-fedora-workstation.md
  inflating: algo-master/docs/deploy-from-redhat-centos6.md
  inflating: algo-master/docs/deploy-from-windows.md
  inflating: algo-master/docs/deploy-to-freebsd.md
  inflating: algo-master/docs/deploy-to-ubuntu.md
  inflating: algo-master/docs/deploy-to-unsupported-cloud.md
  inflating: algo-master/docs/faq.md
  inflating: algo-master/docs/images/aws-ec2-attach-policy.png
  inflating: algo-master/docs/images/aws-ec2-new-policy-review.png
  inflating: algo-master/docs/images/aws-ec2-new-policy.png
  inflating: algo-master/docs/images/aws-ec2-new-user-confirm.png
  inflating: algo-master/docs/images/aws-ec2-new-user-csv.png
  inflating: algo-master/docs/images/aws-ec2-new-user-name.png
  inflating: algo-master/docs/images/aws-ec2-new-user.png
  inflating: algo-master/docs/images/do-api.png
  inflating: algo-master/docs/images/do-new-token.png
  inflating: algo-master/docs/images/do-view-token.png
  inflating: algo-master/docs/index.md
  inflating: algo-master/docs/setup-roles.md
  inflating: algo-master/docs/troubleshooting.md
  inflating: algo-master/input.yml
  inflating: algo-master/inventory
  inflating: algo-master/library/gce_region_facts.py
  inflating: algo-master/library/lightsail.py
  inflating: algo-master/library/lightsail_region_facts.py
  inflating: algo-master/logo.png
  inflating: algo-master/main.yml
  inflating: algo-master/playbooks/cloud-post.yml
  inflating: algo-master/playbooks/cloud-pre.yml
  inflating: algo-master/playbooks/win_script_rebuild.yml
  inflating: algo-master/requirements.txt
  inflating: algo-master/roles/client/handlers/main.yml
  inflating: algo-master/roles/client/tasks/main.yml
  inflating: algo-master/roles/client/tasks/systems/CentOS.yml
  inflating: algo-master/roles/client/tasks/systems/Debian.yml
  inflating: algo-master/roles/client/tasks/systems/Fedora.yml
  inflating: algo-master/roles/client/tasks/systems/Ubuntu.yml
  inflating: algo-master/roles/client/tasks/systems/main.yml
  inflating: algo-master/roles/cloud-azure/defaults/main.yml
  inflating: algo-master/roles/cloud-azure/files/deployment.json
  inflating: algo-master/roles/cloud-azure/tasks/main.yml
  inflating: algo-master/roles/cloud-azure/tasks/prompts.yml
  inflating: algo-master/roles/cloud-digitalocean/tasks/main.yml
  inflating: algo-master/roles/cloud-digitalocean/tasks/prompts.yml
  inflating: algo-master/roles/cloud-ec2/defaults/main.yml
  inflating: algo-master/roles/cloud-ec2/files/stack.yml
  inflating: algo-master/roles/cloud-ec2/tasks/cloudformation.yml
  inflating: algo-master/roles/cloud-ec2/tasks/encrypt_image.yml
  inflating: algo-master/roles/cloud-ec2/tasks/main.yml
  inflating: algo-master/roles/cloud-ec2/tasks/prompts.yml
  inflating: algo-master/roles/cloud-gce/tasks/main.yml
  inflating: algo-master/roles/cloud-gce/tasks/prompts.yml
  inflating: algo-master/roles/cloud-lightsail/tasks/main.yml
  inflating: algo-master/roles/cloud-lightsail/tasks/prompts.yml
  inflating: algo-master/roles/cloud-openstack/tasks/main.yml
  inflating: algo-master/roles/cloud-scaleway/defaults/main.yml
  inflating: algo-master/roles/cloud-scaleway/tasks/image_facts.yml
  inflating: algo-master/roles/cloud-scaleway/tasks/main.yml
  inflating: algo-master/roles/cloud-scaleway/tasks/prompts.yml
  inflating: algo-master/roles/cloud-vultr/tasks/main.yml
  inflating: algo-master/roles/cloud-vultr/tasks/prompts.yml
 extracting: algo-master/roles/common/defaults/main.yml
  inflating: algo-master/roles/common/handlers/main.yml
  inflating: algo-master/roles/common/tasks/facts.yml
  inflating: algo-master/roles/common/tasks/freebsd.yml
  inflating: algo-master/roles/common/tasks/main.yml
  inflating: algo-master/roles/common/tasks/ubuntu.yml
  inflating: algo-master/roles/common/tasks/unattended-upgrades.yml
  inflating: algo-master/roles/common/templates/10-algo-lo100.network.j2
  inflating: algo-master/roles/common/templates/10periodic.j2
  inflating: algo-master/roles/common/templates/50unattended-upgrades.j2
  inflating: algo-master/roles/common/templates/60unattended-reboot.j2
  inflating: algo-master/roles/dns_adblocking/handlers/main.yml
  inflating: algo-master/roles/dns_adblocking/tasks/freebsd.yml
  inflating: algo-master/roles/dns_adblocking/tasks/main.yml
  inflating: algo-master/roles/dns_adblocking/tasks/ubuntu.yml
 extracting: algo-master/roles/dns_adblocking/templates/100-CustomLimitations.conf.j2
  inflating: algo-master/roles/dns_adblocking/templates/adblock.sh.j2
  inflating: algo-master/roles/dns_adblocking/templates/dnsmasq.conf.j2
  inflating: algo-master/roles/dns_adblocking/templates/usr.sbin.dnsmasq.j2
  inflating: algo-master/roles/dns_encryption/defaults/main.yml
  inflating: algo-master/roles/dns_encryption/files/50-dnscrypt-proxy-unattended-upgrades
  inflating: algo-master/roles/dns_encryption/files/apparmor.profile.dnscrypt-proxy
  inflating: algo-master/roles/dns_encryption/handlers/main.yml
  inflating: algo-master/roles/dns_encryption/tasks/freebsd.yml
  inflating: algo-master/roles/dns_encryption/tasks/main.yml
  inflating: algo-master/roles/dns_encryption/tasks/ubuntu.yml
  inflating: algo-master/roles/dns_encryption/templates/dnscrypt-proxy.toml.j2
  inflating: algo-master/roles/dns_encryption/templates/ip-blacklist.txt.j2
  inflating: algo-master/roles/local/tasks/main.yml
  inflating: algo-master/roles/local/tasks/prompts.yml
  inflating: algo-master/roles/ssh_tunneling/handlers/main.yml
  inflating: algo-master/roles/ssh_tunneling/tasks/main.yml
  inflating: algo-master/roles/ssh_tunneling/templates/known_hosts.j2
  inflating: algo-master/roles/ssh_tunneling/templates/ssh_config.j2
  inflating: algo-master/roles/vpn/defaults/main.yml
  inflating: algo-master/roles/vpn/handlers/main.yml
 extracting: algo-master/roles/vpn/meta/main.yml
  inflating: algo-master/roles/vpn/tasks/client_configs.yml
  inflating: algo-master/roles/vpn/tasks/distribute_keys.yml
  inflating: algo-master/roles/vpn/tasks/ipsec_configuration.yml
  inflating: algo-master/roles/vpn/tasks/iptables.yml
  inflating: algo-master/roles/vpn/tasks/main.yml
  inflating: algo-master/roles/vpn/tasks/openssl.yml
  inflating: algo-master/roles/vpn/tasks/ubuntu.yml
 extracting: algo-master/roles/vpn/templates/100-CustomLimitations.conf.j2
  inflating: algo-master/roles/vpn/templates/client_ipsec.conf.j2
 extracting: algo-master/roles/vpn/templates/client_ipsec.secrets.j2
  inflating: algo-master/roles/vpn/templates/client_windows.ps1.j2
  inflating: algo-master/roles/vpn/templates/ipsec.conf.j2
 extracting: algo-master/roles/vpn/templates/ipsec.secrets.j2
  inflating: algo-master/roles/vpn/templates/mobileconfig.j2
  inflating: algo-master/roles/vpn/templates/openssl.cnf.j2
  inflating: algo-master/roles/vpn/templates/rules.v4.j2
  inflating: algo-master/roles/vpn/templates/rules.v6.j2
  inflating: algo-master/roles/vpn/templates/strongswan.conf.j2
  inflating: algo-master/roles/wireguard/defaults/main.yml
  inflating: algo-master/roles/wireguard/files/50-wireguard-unattended-upgrades 
  inflating: algo-master/roles/wireguard/files/wireguard.sh
  inflating: algo-master/roles/wireguard/handlers/main.yml
  inflating: algo-master/roles/wireguard/tasks/freebsd.yml
  inflating: algo-master/roles/wireguard/tasks/keys.yml
  inflating: algo-master/roles/wireguard/tasks/main.yml
  inflating: algo-master/roles/wireguard/tasks/ubuntu.yml
  inflating: algo-master/roles/wireguard/templates/client.conf.j2
  inflating: algo-master/roles/wireguard/templates/server.conf.j2
  inflating: algo-master/server.yml
  inflating: algo-master/tests/local-deploy.sh
  inflating: algo-master/tests/lxd-bridge
  inflating: algo-master/tests/update-users.sh
  inflating: algo-master/users.yml
root@:~# sudo apt-get update && sudo apt-get install \
>     build-essential \
>     libssl-dev \
>     libffi-dev \
>     python-dev \
>     python-pip \
>     python-setuptools \
>     python-virtualenv -y
Hit:1 http://mirrors.cloud.aliyuncs.com/ubuntu bionic InRelease
Hit:2 http://mirrors.cloud.aliyuncs.com/ubuntu bionic-updates InRelease
Hit:3 http://ppa.launchpad.net/wireguard/wireguard/ubuntu bionic InRelease
Hit:4 http://mirrors.cloud.aliyuncs.com/ubuntu bionic-security InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
build-essential is already the newest version (12.4ubuntu1).
libffi-dev is already the newest version (3.2.1-8).
python-dev is already the newest version (2.7.15~rc1-1).
python-setuptools is already the newest version (39.0.1-2).
python-virtualenv is already the newest version (15.1.0+ds-1.1).
libssl-dev is already the newest version (1.1.0g-2ubuntu4.1).
python-pip is already the newest version (9.0.1-2.3~ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@:~# python -m virtualenv --python=`which python2` env &&
>     source env/bin/activate &&
>     python -m pip install -U pip &&
>     python -m pip install -r requirements.txt
Running virtualenv with interpreter /usr/bin/python2
New python executable in /root/env/bin/python2
Also creating executable in /root/env/bin/python
Please make sure you remove any previous custom paths from your /root/.pydistutils.cfg file.
Installing setuptools, pkg_resources, pip, wheel...
  Complete output from command /root/env/bin/python2 - setuptools pkg_resources pip wheel:
  Collecting setuptools
  Downloading http://mirrors.aliyun.com/pypi/packages/e7/16/da8cb8046149d50940c6110310983abb359bbb8cbc3539e6bef95c29428a/setuptools-40.6.2-py2.py3-none-any.whl (573kB)
Collecting pkg_resources
Exception:
Traceback (most recent call last):
  File "/usr/share/python-wheels/pip-9.0.1-py2.py3-none-any.whl/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/share/python-wheels/pip-9.0.1-py2.py3-none-any.whl/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/share/python-wheels/pip-9.0.1-py2.py3-none-any.whl/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/share/python-wheels/pip-9.0.1-py2.py3-none-any.whl/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/share/python-wheels/pip-9.0.1-py2.py3-none-any.whl/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/share/python-wheels/pip-9.0.1-py2.py3-none-any.whl/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/share/python-wheels/pip-9.0.1-py2.py3-none-any.whl/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/share/python-wheels/pip-9.0.1-py2.py3-none-any.whl/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/share/python-wheels/pip-9.0.1-py2.py3-none-any.whl/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/usr/share/python-wheels/pip-9.0.1-py2.py3-none-any.whl/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/share/python-wheels/pip-9.0.1-py2.py3-none-any.whl/pip/index.py", line 795, in get_page
    resp.raise_for_status()
  File "/root/env/share/python-wheels/requests-2.18.4-py2.py3-none-any.whl/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: Not Found for url: http://mirrors.aliyun.com/pypi/simple/pkg-resources/
----------------------------------------
...Installing setuptools, pkg_resources, pip, wheel...done.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 2375, in <module>
    main()
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 724, in main
    symlink=options.symlink)
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 992, in create_environment
    download=download,
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 922, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 817, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /root/env/bin/python2 - setuptools pkg_resources pip wheel failed with error code 2
root@:~#

```
PUT THE OUTPUT HERE
```

**Comment by jackivanov** [comment]
Try to upgrade python as described [here](https://github.com/trailofbits/algo/blob/master/docs/troubleshooting.md#could-not-fetch-url--tlsv1_alert_protocol_version). 

And file another, properly formatted with the template, issue, please
