### ISSUE TITLE
Possible to enable linux client support afterward?

### ISSUE THREAD

**Issue by ronkot** [trailofbits/algo#1211]
**Is your feature request related to a problem? Please describe.**
We've set up a VPN using algo and it's been working like a charm, thanks for this project!

During setup we decided to answer **No** to question _Do you want the VPN to support Windows 10 or Linux Desktop clients? (enables compatible ciphers and key exchange, less secure)_. Now we just got a new team member who is using Linux and we'd like to enable the same VPN for him. 

**Describe the solution you'd like**
Would it be possible to somehow enable Windows 10 & Linux support afterward? It'd be probably also ok to re-create everything if usage of the same IP could be ensured somehow.

Additional info:
- VPN is setup to AWS

**Comment by jackivanov** [comment]
You can try to run Algo with the exact same parameters (provider, region, server name, etc..), but answer yes to the windows question. It's not a guaranteed way and Algo's official answer is rebuild it from scratch, so take the risks on your own.

**Comment by TC1977** [comment]
It sounds like what you want is to 1) add a user with a new cipher suite, 2) keep everyone else's certificates and keys the same, 3) keep the same AWS elastic IP. 

I *think* this can be done if you SSH into the server, create a private key and certificate just for that user, and add the ciphersuite to `/etc/ipsec.conf`. (This is assuming you kept the CA certificate from the original install, which is the last question.) This [link from the strongSwan docs]( https://wiki.strongswan.org/projects/strongswan/wiki/SimpleCA) might help you. You should also review the code to see what Algo uses for windows clients. Then after you're all done, either restart strongSwan using `sudo service strongswan stop; sudo ipsec reload; sudo service strongswan start` or simply reboot the instance.

Good luck! Personally I think it's easier to just reinstall from scratch and hand out new mobileconfigs to everyone.

**Comment by ronkot** [comment]
Thanks for tips! It might be easiest to reinstall from scratch 🤔 Unfortunately we've infromed our elastic ip to 3rd parties and need to re-do that also. But after all, it's just work! :-D
