### ISSUE TITLE
Can I use AlgoVPN as substitue to OpenVPN/FortiClient ?

### ISSUE THREAD

**Issue by kmmanto** [trailofbits/algo#1220]
I successfully installed Algo on my local Ubuntu server behind a Cisco router which also has a public facing IP which I used in the installation. Now I'm faced with these questions.

Questions:
- I can't seem to connect to the VPN server from a separate internet connection (not from the router)
- If I was able to connect to the VPN, can I use AlgoVPN to access some of the compute resources behind the router?
- Do I need to port-forward or NAT it from the Cisco router?

Thanks

**Comment by TC1977** [comment]
I think the answer to question #3 is yes, you probably need to forward ports as [listed in the FAQ](
https://github.com/trailofbits/algo/blob/master/docs/faq.md#what-inbound-ports-are-use). Don't forget also to check your firewall settings. There may be other settings to change on the Cisco router if you have further problems; see #520.
