### ISSUE TITLE
DNS stops working with ad blocking installed

### ISSUE THREAD

**Issue by davidemyers** [trailofbits/algo#1221]
Some users have reported issues with DNS not working either immediately upon deployment or after a few days. Some have reported that the problem does not occur if they deploy with `dns_encryption: false`.

@kristallizer [discovered](https://github.com/trailofbits/algo/issues/1130#issuecomment-441827271) in #1130 that `dnsmasq` failed to restart after `/usr/local/sbin/adblock.sh` had run. The failure appears to be during parsing of config files with `dnsmasq --test`:
```
root@algo-ny-2-encr:~# service dnsmasq status
● dnsmasq.service - dnsmasq - A lightweight DHCP and caching DNS server
   Loaded: loaded (/lib/systemd/system/dnsmasq.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/dnsmasq.service.d
           └─100-CustomLimitations.conf
   Active: failed (Result: signal) since Mon 2018-11-26 02:10:43 UTC; 20h ago
  Process: 25008 ExecStop=/etc/init.d/dnsmasq systemd-stop-resolvconf (code=exited, status=0/SUCCESS)
  Process: 20173 ExecStartPost=/etc/init.d/dnsmasq systemd-start-resolvconf (code=exited, status=0/SUCCESS)
  Process: 20152 ExecStart=/etc/init.d/dnsmasq systemd-exec (code=exited, status=0/SUCCESS)
  Process: 25015 ExecStartPre=/usr/sbin/dnsmasq --test (code=killed, signal=KILL)
 Main PID: 20170 (code=exited, status=0/SUCCESS)
      CPU: 210ms

Nov 26 02:10:39 algo-ny-2-encr systemd[1]: Starting dnsmasq - A lightweight DHCP and caching DNS server...
Nov 26 02:10:43 algo-ny-2-encr systemd[1]: dnsmasq.service: Control process exited, code=killed status=9
Nov 26 02:10:43 algo-ny-2-encr systemd[1]: dnsmasq.service: Failed with result 'signal'.
Nov 26 02:10:43 algo-ny-2-encr systemd[1]: Failed to start dnsmasq - A lightweight DHCP and caching DNS server.
Nov 26 02:10:43 algo-ny-2-encr systemd[1]: dnsmasq.service: Consumed 210ms CPU time
```

If `dns_encryption: true` then the file `/etc/dnsmasq.d/dnscrypt-proxy` is installed and will be read by `dnsmasq` at startup after `/etc/dnsmasq.d/block.hosts.conf`. Maybe something is going wrong with the creation of `block.hosts.conf` that upsets `dnsmasq` when it goes to read `dnscrypt-proxy`.

Could it be that multiple Algo servers running `adblock.sh` at 02:10 UTC are overloading one of the list download sites?

**Comment by TC1977** [comment]
@davidemyers Dunno if this helps, as my installation seems to be working fine, but every morning at 2:10 I'm getting error entries on `journalctl -p 3` as follows:
```ssh
Nov 18 02:10:08 ip-172-16-254-163 dnsmasq[7580]: chown of PID file /run/dnsmasq/dnsmasq.pid failed: Operation not permitted
```

and multiple error entries on `journalctl -p 4` throughout the day as follows:
```ssh
Nov 24 02:10:09 ip-172-16-254-163 systemd-resolved[20130]: Server returned error NXDOMAIN, mitigating potential DNS violation DVE-2018-0001, retrying transaction with reduced feature level UDP.
```

I'm running Ubuntu 18.04 on AWS, unattended upgrades enabled, adblocking and Wifi/LTE on demand enabled, WireGuard disabled.

**Comment by davidemyers** [comment]
I've noticed that latter log message on several different Ubuntu 18.04 instances ever since a `systemd` update a few months ago. I don't know what to make of it but it doesn't seem to impact DNS queries from system processes.

**Comment by davidemyers** [comment]
@vincentlu That's good information, thanks.

@kristallizer Are you using the default block lists or have you added a list that would cause more memory to be used?

**Comment by kristallizer** [comment]
Ah, no, I'm not using the default blocklist; I added 4-5 extra domains.

**Comment by vincentlu** [comment]
BTW I do have
dns_encryption: true

In fact, I also removed dns_servers.

**Comment by davidemyers** [comment]
@kristallizer @vincentlu So it sounds like the memory resource limit imposed on `dnsmasq` is what caused your problems. Hopefully #1228 takes care of that.

@notDavid Yours sounds like a different issue. Was that a "local" deployment or a cloud provider deployment?

**Comment by notDavid** [comment]
It was a "local" deployment on a vps with only an ipv4 network and no ipv6.
I couldn't find it earlier, but see: https://github.com/trailofbits/algo/issues/1025#issuecomment-414144929

**Comment by davidemyers** [comment]
@notDavid Please run the following commands from the Algo directory on the VPS where you had this issue and post the output:
```
source env/bin/activate
ansible localhost -m setup -a 'filter=ansible_default_ipv6'
```

**Comment by notDavid** [comment]
@davidemyers 

```
localhost | SUCCESS => {
    "ansible_facts": {
        "ansible_default_ipv6": {}
    },
    "changed": false
}
```

**Comment by davidemyers** [comment]
@notDavid Thank you. That appears correct, so it does not explain why Algo decided to enable IPv6 for `dnscrypt-proxy` for your local installation.

**Comment by notDavid** [comment]
@davidemyers

Setting `ipv4_servers = true` and `ipv6_servers = true` in `dnscrypt-proxy.toml`, and then disabling ipv6 entirely in `/etc/default/grub` and rebooting, causes dncrypt to stop resolving anything, even though ipv4 connectivity is working fine. You would think dnscrypt would switch to ipv4, but it doesn't.

What might have happened is, i remember having an ipv6 address on the vps, but for whatever reason i could not successfully `ping6 ipv6.google.com`.

So, if algo installation sees i have an ipv6 address and as a result sets `ipv6_servers = true`, but because of some network issues ipv6 public connectivity isn't working, that might explain what happened...?
(after the algo installation i disabled ipv6 entirely in /etc/default/grub as it wasn't working anyway.)

Anyway, lets consider the issue solved :-)

**Comment by davidemyers** [comment]
I'm closing this because #1227 and #1228 have been merged.
