### ISSUE TITLE
Aborting, target uses selinux but python bindings (libselinux-python) aren't installed!

### ISSUE THREAD

**Issue by masonesq** [trailofbits/algo#1222]
Unfortunately, algo.sh failed:
```
<Lightsail public IP>  : ok=56   changed=9    unreachable=0    failed=1   
localhost              : ok=33   changed=3    unreachable=0    failed=0   
```
The failure point was here:
```
TASK [wireguard : Generate private keys] **************************************
task path: /home/<username>/algo-master/roles/wireguard/tasks/keys.yml:11
```
and then at the end of this task:
```
"msg": "Aborting, target uses selinux but python bindings (libselinux-python) aren't installed!"
```

I edited `~/algo-master/.travis.yml` by adding a line with
```
- python-selinux
```
after the line with 
```
- python-dev
```
but that did not solve the problem.

To make it that far in the script, I had to change `~/algo-master/roles/wireguard/tasks/keys.yml` `block:` `name: Save private keys` as follows:  set `no_log` to `false`.  It was originally `true` which caused the script to fail.

```
Algo running on: Fedora 29 (Workstation Edition)
ZIP file created: 2018-11-27 01:09:33.000000000 -0500
Python 2.7.15
Runtime variables:
    algo_provider "lightsail"
    algo_ondemand_cellular "False"
    algo_ondemand_wifi "False"
    algo_ondemand_wifi_exclude "_null"
    algo_local_dns "True"
    algo_ssh_tunneling "False"
    algo_windows "False"
    wireguard_enabled "True"
    dns_encryption "True"
```

**Comment by jackivanov** [comment]
Please, follow [the docs](https://github.com/trailofbits/algo/blob/master/docs/deploy-from-fedora-workstation.md)

**Comment by austinsonger** [comment]
Follow this [doc](https://github.com/trailofbits/algo/blob/master/docs/deploy-from-redhat-centos6.md)
