### ISSUE TITLE
Syntax Error when generating p12 password

### ISSUE THREAD

**Issue by NightMachinary** [trailofbits/algo#1226]
```
TASK [common : Generate p12 export password][24/1514]
***************************                          
fatal: [localhost -> localhost]: FAILED! => {"changed
": true, "cmd": "openssl rand 8 | python -c 'import s
ys,string; chars=string.ascii_letters + string.digits
 + \"_@\"; print \"\".join([chars[ord(c) % 64] for c 
in list(sys.stdin.read())])'", "delta": "0:00:00.2421
92", "end": "2018-11-28 18:42:30.409862", "msg": "non
-zero return code", "rc": 1, "start": "2018-11-28 18:
42:30.167670", "stderr": "  File \"<string>\", line 1
\n    import sys,string; chars=string.ascii_letters +
 string.digits + \"_@\"; print \"\".join([chars[ord(c
) % 64] for c in list(sys.stdin.read())])\n          
                                                     
                  ^\nSyntaxError: invalid syntax", "s
tderr_lines": ["  File \"<string>\", line 1", "    im
port sys,string; chars=string.ascii_letters + string.
digits + \"_@\"; print \"\".join([chars[ord(c) % 64] 
for c in list(sys.stdin.read())])", "                
                                                     
            ^", "SyntaxError: invalid syntax"], "stdo
ut": "", "stdout_lines": []}        
          
```
I am installing this locally on my own Ubuntu 18 server.

**Comment by TC1977** [comment]
You don't include the entire log, or at least the environment information, but this kind of sounds like #902.

**Comment by NightMachinary** [comment]
I unfortunately only have an iPhone SE for some days, and it’s quite hard
to copy the whole log. :)
Indeed, I think this is a python env problem, but where should I activate
the needed env? I activated it before calling algo, I activate it in my
.bashrc and .zshenv. I can’t think of another place it needs activating. I
use conda, btw.

**Comment by davidemyers** [comment]
I think Algo assumes there is no virtual environment already activated when you run the setup commands that are run prior to first running `./algo`, as specified in the README. After running those commands Algo's environment will be initialized and activated.

For subsequent runs of `./algo`, you first run `source env/bin/activate` from the Algo directory.

So maybe something about your existing environment is tripping up Algo. Try setting up a new copy of Algo and make sure you `deactivate` any existing environment first.

This is a bit of a guess, because if you use conda you know much more about Python environments than I do. :smile:

**Comment by xmijo** [comment]
I am receiving this same error while trying to set up on a Vultr server from macOS mojave. I have tried to reinstall Algo and dependencies from scratch several times. Not sure what is causing this error. Is there any further information that I can provide to make it easier to pinpoint what goes wrong?

![image](https://user-images.githubusercontent.com/24359963/50758322-d76db480-129c-11e9-9a4b-143e41fe6eab.png)

**Comment by Neophy7e** [comment]
For me the issue was that my system default python version is `3` and apparently algo is made with python2 in mind. You may need to check your `algo/env/bin/`

**Comment by xmijo** [comment]
Thanks @Neophy7e that solved the issue. I had set `alias python='python3'` in my .bash_profile so I just unaliased it to make it work.
