### ISSUE TITLE
EC2: IAM inline policy

### ISSUE THREAD

**Issue by defunctio** [trailofbits/algo#123]
Provide an IAM inline policy for users to limit only the permissions Algo will need on AWS for deployment rather than granting `AmazonEC2FullAccess`

**Comment by dguido** [comment]
$100 bounty! Submit a pull request and email dan@trailofbits.com to claim it. Partial solutions may be rewarded.

**Comment by defunctio** [comment]
This is a start to an inline IAM policy that 'should' include all the necessary actions for Algo to perform the tasks it needs for deployment. However; additional resource restrictions should be implemented on actions that allow for it to limit the policy as much as possible. 

Note: Certain actions such as `CreateKeyPair`, `DeleteKeyPair`, `ImportKeyPair` and many others have no resource limitation filters.

I will not be claiming any bounties so feel free to use this partial solution to create a more complete solution and submit your PR to claim your bounty!

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "ec2:DescribeInstances",
                "ec2:DescribeImages",
                "ec2:DescribeKeyPairs",
                "ec2:DescribeVpcs",
                "ec2:DescribeSubnets",
                "ec2:DescribeSecurityGroups",
                "ec2:CreateSecurityGroup",
                "ec2:AuthorizeSecurityGroupEgress",
                "ec2:AuthorizeSecurityGroupIngress",
                "ec2:CreateTags",
                "ec2:CreateKeyPair",
                "ec2:DeleteKeyPair",
                "ec2:ImportKeyPair"
            ],
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": "ec2:RunInstances",
            "Resource": "*"
        }
    ]
}
```
