### ISSUE TITLE
What ports should be open for algo to work?

### ISSUE THREAD

**Issue by NightMachinary** [trailofbits/algo#1230]
When I enable ufw, algo doesn’t work anymore. Which ports should I open in ufw?
PS: I have ditched the default iptables algo installs, because I have other stuff on my server.

**Comment by TC1977** [comment]
This is answered [in the FAQ](https://github.com/trailofbits/algo/blob/master/docs/faq.md#what-inbound-ports-are-used). And as @davidemyers stated above, the default iptables rules are necessary for proper VPN operation. You really should look them over and install the ones that don't break existing services.
