### ISSUE TITLE
EC2: instance_initiated_shutdown_behavior

### ISSUE THREAD

**Issue by defunctio** [trailofbits/algo#124]
This feature has a dependacy on ansible 2.2 so for now it is blocked, but this is to serve as a reminder to change the default behavior on EC2 instances via instance_initiated_shutdown_behavior to terminate.

**Comment by defunctio** [comment]
I think we can probably bump the required version of ansible to 2.2 now since it has been out for awhile. This would permit us to enable the feature for this issue, any objections @gunph1ld @dguido ?

Even Ubuntu packages have been updated.
```
Package: ansible
Priority: optional
Section: admin
Installed-Size: 12329
Maintainer: Ansible, Inc. <info@ansible.com>
Architecture: all
Version: 2.2.0.0-1ppa~xenial
```

**Comment by gunph1ld** [comment]
Yes, I think `terminate` is more reasonable
