### ISSUE TITLE
No internet connection after connecting to the vpn server - LTE

### ISSUE THREAD

**Issue by xytzw** [trailofbits/algo#1240]
I run two servers on Amazon London region. One of them has been running for a year now. All clients (a mix of mobile devices and pcs) are served by LTE (4G). All worked as it should until two days ago.

What I observe is that all clients connect to servers and can talk to each other but the iternet connection depends on where geographically a client is (withing a city). To explain - I cannot connect to the internet while at home when using algo servers (internet works fine otherwise without algo vpn and clients also connect to algo servers sucsessfully at home) but outside my neighbourhood area (say at work a few km down the road) I do have internet connection when using algo. In effect nothing is changing apart from the physical location and LTE towers.

It looks like the LTE tower that is serving my neighbourhood is somehow a suspect but that is only a hunch.

Any suggestions how to attempt to fix/debug the issue?

**Comment by jackivanov** [comment]
Looks like an MTU problem. Have you look at the [troubleshooting guide](https://github.com/trailofbits/algo/blob/master/docs/troubleshooting.md#various-websites-appear-to-be-offline-through-the-vpn) yet?

**Comment by xytzw** [comment]
@jackivanov Thanks. I will check tonight.

**Comment by xytzw** [comment]
@jackivanov Mtu was the issue. Spun a new instance and opted for the lower value as in the config file and it’s connecting to the internet now. Thanks again.
