### ISSUE TITLE
vpn does not bypass the firewall timed schedules

### ISSUE THREAD

**Issue by bazillevdw** [trailofbits/algo#1249]
The boarding school where I live has a fortigate 50D firewall that from 23.00 h - 7.00 h restricts internet access. If you have a login you could go online pass that. I was wondering if I could bypass this with my algo vpn running in a ubuntu 18.04 droplet from digitalocean. And if so how do you this?

**Comment by jackivanov** [comment]
You are welcome in [gitter](https://gitter.im/trailofbits/algo) for such questions.
