### ISSUE TITLE
dnscrypt-proxy stops working at random

### ISSUE THREAD

**Issue by leontodd** [trailofbits/algo#1254]
I have installed Algo on a fresh instance of Ubuntu 18.04. The VPN works absolutely fine when I first start it. After a minute or two, DNS queries will stop resolving. I have narrowed the issue down to dnscrypt-proxy, as restarting dnscrypt-proxy will allow DNS queries to begin resolving again for a short time. The only logs I can find on dnscrypt-proxy indicate that it is running fine.

I have checked the logs for dnsmasq too, and dnsmasq is correctly directing requests to dnscrypt-proxy. When the server is first started, I can see requests in the logs and their corresponding replies:

```
Dec 17 20:40:53 sd-128198 dnsmasq[11375]: query[A] gov.uk from 10.19.48.1
Dec 17 20:40:53 sd-128198 dnsmasq[11375]: forwarded gov.uk to 172.16.0.1
Dec 17 20:40:53 sd-128198 dnsmasq[11375]: forwarded gov.uk to 127.0.2.1
Dec 17 20:40:53 sd-128198 dnsmasq[11375]: reply gov.uk is 23.235.37.144
Dec 17 20:40:53 sd-128198 dnsmasq[11375]: reply gov.uk is 23.235.33.144
```

After a minute or two all I see is this and no replies:

```
Dec 17 20:42:15 sd-128198 dnsmasq[11375]: query[A] textuploader.com from 10.19.48.1
Dec 17 20:42:15 sd-128198 dnsmasq[11375]: forwarded textuploader.com to 172.16.0.1
Dec 17 20:42:15 sd-128198 dnsmasq[11375]: forwarded textuploader.com to 127.0.2.1
```

Cached queries from dnsmasq still work, but new queries do not. Directing queries through dnsmasq directly to known working DNS servers lets the VPN work flawlessly. Trying to connect directly to IP addresses works too. It seems to be an issue with dnscrypt-proxy only.

Does anyone know what else I could look into on my system to solve this?

**Comment by davidemyers** [comment]
Please post the output of `systemctl status dnscrypt-proxy`. Also, if you still have it, the section of your installation output just below where it says,
```
--> Please include the following block of text when reporting issues:
```
Does your system have working IPv6? Please post the output of `grep ipv6_servers  /etc/dnscrypt-proxy/dnscrypt-proxy.toml`.

**Comment by leontodd** [comment]
The strange error was caused by IPv6 being unconfigured on the server, my mistake. Thank you for the response.
