### ISSUE TITLE
Custom DNS.

### ISSUE THREAD

**Issue by Ge0rges** [trailofbits/algo#1255]
Is it possible to set up wireguard traffic to use a hosted unbound recursive DNS instead of the optional ad-blocking one Algo provides? What configuration files need to be modified?

Specifically, I'm looking to run unbound+pihole as my recursive, ad-blocking solution and pairing that with wireguard.

**Comment by jackivanov** [comment]
There is only one [configuration](https://github.com/trailofbits/algo/blob/master/config.cfg#L71) file
