### ISSUE TITLE
OpenVPN confusion

### ISSUE THREAD

**Issue by keeponhacking** [trailofbits/algo#1260]
Hello,

I just installed Algo on a DigitalOcean droplet.

I enabled linux support during the installation.

I am a bit confused on how to connect using OpenVPN using linux.

In the config folder i have one user.pem and one user.pem.pub and a folder with ip (which is different than the eth0 ip from ifconfig)

What do I use to connect with OpenVPN:
1. The ip from ifconfig or the one from .config folder?
2. Do I use Password authentication and if yes is the password the same as the one for p12 and SSH connection shown after install? Which pem do I use for CA certificate , the one from .config root folder or the one from .config/IP/cacert.pem

**Comment by ipeacocks** [comment]
> Does not install Tor, OpenVPN, or other risky servers

Why OpenVPN is risky?

**Comment by benjaminshell** [comment]
> Why OpenVPN is risky?

Their [blog post](https://blog.trailofbits.com/2016/12/12/meet-algo-the-vpn-that-works/) referenced in the README answers this and discusses problems with other VPNs.
