### ISSUE TITLE
lan-passthrough is not working as expected

### ISSUE THREAD

**Issue by dhamukrish** [trailofbits/algo#1263]
**Describe the bug**

`lan-passthrough` configuration in `/etc/ipsec.conf` is not working as expected on Raspbian Stretch and not connecting SSH port including other ports via local network e.g. (`192.168.0.131`) after successful VPN connection. 

Below is the configuration.
```
conn lan-passthrough
    leftsubnet=192.168.0.0/23
    rightsubnet=192.168.0.0/23
    authby=never
    type=pass
    auto=route
```

**To Reproduce**

Steps to reproduce **positive** behavior:
1. Connect Raspberry PI without VPN to the local network
2. Try to telnet e.g. `192.168.0.131` on port `22` or do `ssh`

**Expected behavior**
1. Able to connect on port `22`

Steps to reproduce **negative** behavior:
1. Connect Raspberry PI with VPN via `ipsec up <conn-name>`
2. Try to telnet e.g. `192.168.0.131` on port `22` 

**Expected behavior**
1. Not able to connect on port `22`

**Additional context**
1. Ping is working for local IP e.g. `192.168.0.131` but ports are not accessible via `telnet` or `ssh`.

1. Edge devices are connecting to this Raspberry PI on MQTT port 1883 all failing to connect after VPN is established successfully.

**Comment by jackivanov** [comment]
It's not a use-case of Algo, but you can try to ask in [Gitter](https://gitter.im/trailofbits/algo)

**Comment by dhamukrish** [comment]
This issue has been solved by setting the Raspbian Pixel Desktop -> Start > Preferences -> Raspberry Pi Configuration -> Network at Boot -> Wait for network -> enabled.
