### ISSUE TITLE
Add documentation for using the Wireguard iOS client

### ISSUE THREAD

**Issue by dguido** [trailofbits/algo#1264]
https://itunes.apple.com/us/app/wireguard/id1441195209?ls=1&mt=8

https://lists.zx2c4.com/pipermail/wireguard/2018-December/003694.html

**Comment by zx2c4** [comment]
> OnDemand is available, but I didn't find a way to configure it through the config files

You should be generating the same .conf files as on Android, anyway, and then the instructions for everything can be unified and simple, since the flows and screens are all exactly the same.

**Comment by TC1977** [comment]
Is there a way to carry over the "excluded networks" from the Algo setup? AWS has a pretty low transfer limit on the free tier (30GB), so I'd like to exclude traffic from my home and work Wi-Fi. Otherwise, the on-demand settings, including Wi-Fi vs cellular vs both, are set in the WireGuard app.

**Comment by zx2c4** [comment]
Just construct the allowedIPs field in a way that excludes those networks: `0.0.0.0/0 % {yournetworks}`.

**Comment by zx2c4** [comment]
Sounds like you want the on-demand settings to filter by SSID? Perhaps we'll add that feature to the app settings at some point down the line.

**Comment by TC1977** [comment]
The ability to exclude specific SSIDs is now in the Wireguard iOS app as of two days ago. Existing connection settings can be easily updated using the iOS app, but perhaps it’s time to get that into the deploy process. See (#1328 specifically.) Thanks @zx2c4!
