### ISSUE TITLE
reduce_mtu fact not defined

### ISSUE THREAD

**Issue by TC1977** [trailofbits/algo#1267]
**Describe the bug**

There's a report on [gitter](https://gitter.im/trailofbits/algo) of a problem installing the latest commit from today on Lightsail. The log makes me wonder if there's a problem with the reduce_mtu fact from #1253.

**To Reproduce**

1. Download the latest commit from today.
2. Install on Lightsail, Ubuntu 18.04.

**Expected behavior**

Successful install.

**Full log**

```
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'reduce_mtu' is undefined\n\nThe error appears to have been in '/root/algo-master/roles/common/tasks/facts.yml': line 32, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Check size of MTU\n  ^ here\n"}
```

**Comment by davidemyers** [comment]
`reduce_mtu` is defined in `config.cfg`. Can the user confirm it's there (and they're not using an older copy of `config.cfg` they saved from an earlier install)?

**Comment by unixfy** [comment]
> `reduce_mtu` is defined in `config.cfg`. Can the user confirm it's there (and they're not using an older copy of `config.cfg` they saved from an earlier install)?

I was the original reporter. I can confirm that the error is caused by `reduce_mtu` not being defined in my config, which I created several days ago. Perhaps this should be mentioned in the commit or elsewhere?

**Comment by TC1977** [comment]
I think having this issue documented is enough, for now. If I get time over the weekend, I could submit a PR adding something to the effect of "please delete your algo-master folder and download an entirely new one with a fresh install" to [this part of the FAQ](https://github.com/trailofbits/algo/blob/master/docs/faq.md#i-deployed-an-algo-server-can-you-update-it-with-new-features).
