### ISSUE TITLE
IPv6 broken by #1256

### ISSUE THREAD

**Issue by davidemyers** [trailofbits/algo#1270]
I think PR #1256 has broken IPv6. I deployed to DigitalOcean but IPv6 does not work from IPsec clients and `net.inet6.ip6.forwarding` was not added to `/etc/sysctl.conf`.

```
TASK [common : Set IPv6 support as a fact] *****************************************************************************
ok: [165.227.222.22]

TASK [common : Check size of MTU] **************************************************************************************
ok: [165.227.222.22]
changed: [165.227.222.22] => (item={u'item': u'net.ipv4.ip_forward', u'value': 1})
changed: [165.227.222.22] => (item={u'item': u'net.ipv4.conf.all.forwarding', u'value': 1})
```
Other templates that check `ipv6_support` are correct (I checked `/etc/wireguard/wg0.conf`, `/etc/ipsec.conf`, `/etc/iptables/rules.v6`, and `/etc/dnscrypt-proxy/dnscrypt-proxy.toml`).

Running `sysctl -w net.ipv6.conf.all.forwarding=1` gets IPv6 working again.

**Comment by TC1977** [comment]
Kind of sad, but I just noticed now that my Algo server, set up on an EC2 instance on December 21 (after #1256) didn't have IPv6 enabled either. `/etc/sysctl.conf` also had `net.inet6.ip6.forwarding=1` commented out and not added at the bottom. `sudo sysctl -w net.ipv6.conf.all.forwarding=1` got it working again as per [ipv6-test](http://www.ipv6-test.com) or [icanhazip](https://ipv6.icanhazip.com).
