### ISSUE TITLE
Algo Authentication Issue

### ISSUE THREAD

**Issue by army2000** [trailofbits/algo#1279]
I have attached two screenshots of my Terminal window indicating the error messages.  The "401" error message appears to be related to authentication issues, but I'm not clear if it's related to my Digital Ocean droplet.  I am using MacOS 10.13.4.  

Please advise on correcting this error.
![algo error1](https://user-images.githubusercontent.com/35558471/50543529-deb00680-0ba8-11e9-8d4f-a9dbda8ad8be.png)
![algo error2](https://user-images.githubusercontent.com/35558471/50543530-df489d00-0ba8-11e9-81b7-191e6f072d98.png)

**Comment by TC1977** [comment]
Sounds like you need to confirm that your DO account is active and working first.

**Comment by army2000** [comment]
Thanks, now I can successfully connect!  I apparently had two DO VPN servers which was causing the problem.
