### ISSUE TITLE
Unsintalling (to reinstall) algo on a local installation.

### ISSUE THREAD

**Issue by Ge0rges** [trailofbits/algo#1280]
As an example, I need to add new users but didn't save the CA key so I need to reinstall. What would be the proper procedure to reinstall algo?

**Comment by TC1977** [comment]
The "correct" way depends on your cloud provider. AWS, for example, uses CloudFormation, so I suppose the way that leaves the least garbage around would be to simply go to CloudFormation and delete the whole stack. But you could just go into the Instances page on the EC2 console and terminate the instance there, and be done much faster.

The proper way to reinstall would be to download the newest version onto your local machine, into a new folder, and then run the cloud install from there.

**Comment by Ge0rges** [comment]
Problem is I’m installing locally. Overwriting the previous install by just running it again fails.

**Comment by Ge0rges** [comment]
Went through and removed strongswan, Wireguard (didn’t install dnsmasq or dnscrypt) and deleted the Algo directory however going through the install process again fails. Deleting the entire installation is the clear option however in my case isn’t really an option.
