### ISSUE TITLE
Is "mesh routing" possible?

### ISSUE THREAD

**Issue by ionlights** [trailofbits/algo#1282]
**Pretext:** My expertise is in machine learning and web development (mostly ML for the last few years). So it's easily possible I'm overlooking something.

**Is your feature request related to a problem? Please describe.**
I don't believe it's a problem and I think it's an unintended use of `algo`.

**Describe the solution you'd like**
- **Constraint:** I don't control my internet access, thus can't port forward.
- **Goals:**
  1. Block access to certain subdomains (like mesh.ionlights.com) without a specific IP[-range]
  1. Give teammates (and myself) remote access to my desktop/NAS as if it's on LAN.

**Describe alternatives you've considered**
Currently, I use `tinc` to achieve (ii), but that won't work for (i). `algo` achieves (i), per se, but I can't SSH into devices as if I'm on a LAN (i.e. without `tinc`).

**Additional context**
I guess I'm looking for a more enterprise-like VPN, which allows you to hop into a network and access devices like on a LAN – as opposed to one which is for privacy.

**Comment by TC1977** [comment]
"mesh networking", if you're talking about mesh Wi-Fi, is entirely unrelated to Algo or pretty much any VPN for that matter.

If you want to be able to access other devices that are also connected to the Algo server, you can deploy Algo setting the [BetweenClients_DROP flag](https://github.com/trailofbits/algo/blob/master/config.cfg#L95) to false.

**Comment by ionlights** [comment]
Sorry, no, by "mesh networking" I guess I mean "mesh routing" (terminology comes from [here][do-tinc] and [`tinc`'s][tinc] website).

The point of "mesh networking/routing" was that it creates an additional network which can be used as a LAN to access off-network devices.

Also, will give [`BetweenClients_DROP`][bcdrop] a go. Thanks! 👍 (**Also, would this have been something I could have found in the documentation?**) @TC1977 

[do-tinc]: https://www.digitalocean.com/community/tutorials/how-to-install-tinc-and-set-up-a-basic-vpn-on-ubuntu-14-04
[tinc]: https://tinc-vpn.org/
[bcdrop]: https://github.com/trailofbits/algo/blob/master/config.cfg#L95

**Comment by TC1977** [comment]
Ok, I see what you're talking about. Algo installs strongSwan and Wireguard, and neither of these (as far as I know) does "mesh routing" as described on those pages (sending traffic directly between two clients connected to a VPN server).

I don't believe `BetweenClients_DROP` is documented, nor are several other options in `config.cfg`, unless you search the issues and PRs. So it's not you. 😄

**Comment by ionlights** [comment]
There looks to be a comment right above `BetweenClients_DROP` in `config.cfg`; guess I glossed over it. 😅 

Seems as though
```yaml
...
BetweenClients_DROP: true
...
```
works.

😃
