### ISSUE TITLE
Activity Logs

### ISSUE THREAD

**Issue by Mustafa-C** [trailofbits/algo#1283]
**Is your feature request related to a problem? Please describe.**
It is not related to a problem.

**Describe the solution you'd like**
TXT or other common formats of activity logs.

**Describe alternatives you've considered**
Doing it with other services which monitor connections but to no avail.

**Additional context**
None available.

**Comment by TC1977** [comment]
strongSwan uses the syslogger. Try playing around with various versions of `grep charon /var/log/syslog`. One helpful one I've found, that will show you the times and IP addresses that client abc logged in, is `grep "charon.*IKE_SA ikev2-pubkey.*established.*abc" /var/log/syslog`. Keep in mind that you or others may not want any logging, in which case you'd want to change the log settings in `config.cfg` prior to deployment, or `/etc/ipsec.conf` after deployment.

I'm really not sure if Wireguard logs anything at all.
