### ISSUE TITLE
Optionally support TunSafe (Wireguard fork) with TCP mode and HTTPS obfuscation

### ISSUE THREAD

**Issue by janwerner** [trailofbits/algo#1287]
TunSafe is a fork of Wireguard. In [v1.5-rc2](https://tunsafe.com/downloads/ChangeLog.txt), they implemented an optional TCP mode as well as a possibility to obfuscate traffic to make it look like regular HTTPS data. This makes it possible to run Wireguard on port 443/tcp to establish a VPN connection in situations where other traffic is not allowed. This would also be helpful for users in China who need to bypass the great firewall.

Edit: Here, the dev explains why he chose to support TCP in TunSafe: [WireGuard TCP.txt](https://github.com/TunSafe/TunSafe/blob/master/docs/WireGuard%20TCP.txt)

**Comment by jackivanov** [comment]
Sorry, we're not interested in supporting this right now

**Comment by donileo** [comment]
Is there a reason why this wont be added? Different priorities at the moment?

**Comment by rvpn** [comment]
> Is there a reason why this wont be added? Different priorities at the moment?

BUMP

**Comment by urbaniak** [comment]
Also interested in running wireguard over tcp/443 to pass some restrictive firewalls

**Comment by gam-phon** [comment]
@urbaniak Check out this [dsvpn](https://github.com/jedisct1/dsvpn) one of its feature: Runs on TCP. Works pretty much everywhere, including on public WiFi where only TCP/443 is open or reliable.
