### ISSUE TITLE
Installation Frozen

### ISSUE THREAD

**Issue by tommyvange** [trailofbits/algo#1288]
Hello, I am trying to install or setup Algo and I have gotten through what seems like the whole installation, but it's currently stuck at `PLAY [Configure the server and install required software]`. It has been stuck there for almost 15 minutes now.

Is this normal or is my installation broken?

**Server Version**
Ubuntu 18.04 (Hetzner Cloud)

The CPU, Disk, Network, etc... usage seems normal as well.
https://i.gyazo.com/a3c933cc3ddf1ae85650ecf04d1f5c9f.png

Thanks in advance,
Tommy Vange

**Comment by tommyvange** [comment]
I just deleted the Linux instance and did the installation again, now it works :)

**Comment by zachBridges** [comment]
I experienced this when I had already created the droplet with my desired server name on DigitalOcean instead of letting the algo scripts handle it.
