### ISSUE TITLE
Deploy fails on 'Getting your SSH key ID on Digital Ocean...'

### ISSUE THREAD

**Issue by tmgbeu** [trailofbits/algo#129]
I'm trying to deploy from OS X, having installed the relevant dependencies. I get through the various options, then the deploy fails at this point:

```
TASK [cloud-digitalocean : Getting your SSH key ID on Digital Ocean...] ********
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'X509' object has no attribute '_x509'
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "'X509' object has no attribute '_x509'"}
```

I've double-checked I'm using the right SSH id name, and it's reporting correctly when I run a GET request to api.digitalocean.com/v2/account/keys. This SSH key also works fine if I SSH in from this machine, so I'm at a loss to figure out what I'm getting wrong here.

**Comment by gunph1ld** [comment]
ansivle version? dopy version?

**Comment by tmgbeu** [comment]
Ansible: 2.2.0.0
Dopy: 0.3.5

**Comment by fkt** [comment]
python -c 'import OpenSSL; print(OpenSSL.__version__)'
If it is < 0.14 it might be too old.

**Comment by tmgbeu** [comment]
'OpenSSL 0.9.8zh 14 Jan 2016'

**Comment by fkt** [comment]
Sorry markdown messed with the underscores. This gives the pyOpenSSL version, not OpenSSL.
`python -c 'import OpenSSL; print(OpenSSL.__version__)'`

**Comment by tmgbeu** [comment]
Aha! Yeah, OSX default pyOpenSSL version was 0.13.1
I installed python through Homebrew and that's bumped pyOpenSSL to 16.2.0
Works a treat now, thanks! :)

**Comment by samkelleher** [comment]
Just to assist with anyone not upto date with their openssl depdendency management.

Homebrew might report that the latest OpenSSL is happily installed, by python can't find it however.  So running `pip install pyopenssl` will install it (it wasn't installed for me automatically). Once installed, this error went away.

**Comment by dguido** [comment]
I have a fresh install of 10.12 and I ran into this issue. It was *very* difficult to get a newer version of pyopenssl installed. In the end, the command `sudo pip install --ignore-install pyopenssl` got me a newer version which did not run into this issue.
