### ISSUE TITLE
Consider Wireguard's "Blind Operator Mode"

### ISSUE THREAD

**Issue by dguido** [trailofbits/algo#1291]
https://git.zx2c4.com/blind-operator-mode/about/

I'm not certain this has a ton of value, but if it doesn't break anything then I'd consider turning it on. Really though, you can just delete the ssh credentials to access your AlgoVPN server and call it a day.

**Comment by jackivanov** [comment]
What if we just stop sshd and tty on the cloud deployments?

**Comment by zx2c4** [comment]
Noooooooo. Blind operator mode is snakeoil nonsense!

**Comment by zx2c4** [comment]
> What if we just stop sshd and tty on the cloud deployments?

This seems like a good idea though, in large part because it means people will be more inclined to just set up a new Algo when something goes wrong, rather than mucking around with all sorts of nobs and inadvertently making themselves less secure or something.
