### ISSUE TITLE
Does Wireguard log connections? If so, where does it write to? 

### ISSUE THREAD

**Issue by digeratus** [trailofbits/algo#1294]
Wireguard is quite a simple protocol, reminds me a lot of SSH. Unfortunately like Algo, it needs some help with documentation. I tried asking this on the forum but didn't get an answer, so I'm passing this on to a larger audience. Any help is appreciated.

Btw, if Wireguard itself doesn't log, is there a log of connections anywhere else in the system? syslog?

Thanks,

**Comment by jackivanov** [comment]
No, it doesn't. You are welcome for such kind of question in [Gitter](https://gitter.im/trailofbits/algo)
