### ISSUE TITLE
Wifi with emoji in name results in update-user failing

### ISSUE THREAD

**Issue by JMoVS** [trailofbits/algo#1297]
**Describe the bug**

When one enters a wifi with emoji in its name (yes, that's possible - my wifi is called W🥚f🥚), subsequent calles to algo update users fail with a "unable to read YAML" error.

**To Reproduce**

1. Setup algo and add a wifi with emoji to the on demand-exclusion list
2. Try to update users afterwards
3. experience error

**Additional context**

Probably some insufficient character escaping or missing unicode support or something.

**Comment by davidemyers** [comment]
What does the value for `algo_ondemand_wifi_exclude:` look like in the file `configs/<ip_addr>/config.yml`?

**Comment by JMoVS** [comment]
I don't know as I did throw away the whole algo server, started fresh by now. ;-) Do you maybe have a VM ready to check that quickly? I'm sorry

**Comment by jackivanov** [comment]
Closing for now. File another issue when you'll have more info please.

**Comment by JMoVS** [comment]
Can you not reproduce this?

**Comment by jackivanov** [comment]
Sorry, seems I misunderstood the problem first time

**Comment by jackivanov** [comment]
@JMoVS try out this PR please #1303

**Comment by JMoVS** [comment]
Before I try:

I already deployed it and manually added the wifi network to the mobileconfig (it works there), so my hunch is that it's really only an issue with the server.yml and I don't know if the i-Devices understand wifi networks when they're encoded in base64 - are you sure we need to encode the wifi network in base 64 for the mobileconfig file or am I misreading that code?
