### ISSUE TITLE
Install on google cloud error: get region

### ISSUE THREAD

**Issue by Tennyleaz** [trailofbits/algo#1300]
**Describe the bug**

I tried to install on a google cloud compute engine.
After I typed the location of my json file, algo script said 
`fatal: [localhost]: FAILED! => {"changed": false, "msg": "unknown locale: lzh_TW"}`

**Environment**
I tried on a kubuntu machine, Chinese(Taiwan) locale.

**Full log**

TASK [cloud-gce : Install requirements] **************************************************************************************************
changed: [localhost]
[cloud-gce : pause]
Enter the local path to your credentials JSON file
(https://support.google.com/cloud/answer/6158849?hl=en&ref_topic=6262490#serviceaccounts)
:
/home/user/xxx.json

TASK [cloud-gce : pause] *****************************************************************************************************************
ok: [localhost]

TASK [cloud-gce : set_fact] **************************************************************************************************************
ok: [localhost]

TASK [cloud-gce : set_fact] **************************************************************************************************************
ok: [localhost]

TASK [cloud-gce : set_fact] **************************************************************************************************************
ok: [localhost]

TASK [cloud-gce : Get regions] ***********************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "unknown locale: lzh_TW"}

TASK [cloud-gce : debug] *****************************************************************************************************************
ok: [localhost] => {
    "fail_hint": [
        "Sorry, but something went wrong!", 
        "Please check the troubleshooting guide.", 
        "https://trailofbits.github.io/algo/troubleshooting.html"
    ]
}

TASK [cloud-gce : fail] ******************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed as requested from task"}

PLAY RECAP *******************************************************************************************************************************
localhost                  : ok=22   changed=5    unreachable=0    failed=2

**Comment by jackivanov** [comment]
Can you provide the full log, but not a part of it?
