### ISSUE TITLE
DO install fails at vpn : Set facts for mobileconfigs

### ISSUE THREAD

**Issue by gittalicious** [trailofbits/algo#1315]
DO install goes along just fine on Mac
The following tasks complete:
TASK [vpn : Copy the keys to the strongswan directory]
TASK [vpn : Register p12 PayloadContent]

Then there is a failure at:
TASK [vpn : Set facts for mobileconfigs] ***************************************
ok: [159.89.123.189 -> localhost]
failed: [159.89.123.189] (item=None) => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
failed: [159.89.123.189] (item=None) => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
failed: [159.89.123.189] (item=None) => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
failed: [159.89.123.189] (item=None) => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
failed: [159.89.123.189] (item=None) => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
failed: [159.89.123.189] (item=None) => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
failed: [159.89.123.189] (item=None) => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
failed: [159.89.123.189] (item=None) => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
failed: [159.89.123.189] (item=None) => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
failed: [159.89.123.189] (item=None) => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
failed: [159.89.123.189] (item=None) => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
failed: [159.89.123.189] (item=None) => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
failed: [159.89.123.189] (item=None) => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
failed: [159.89.123.189] (item=None) => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
failed: [159.89.123.189] (item=None) => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
failed: [159.89.123.189] (item=None) => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}

TASK [vpn : Build the mobileconfigs] *******************************************

TASK [vpn : debug] *************************************************************
ok: [159.89.123.189] => {
    "fail_hint": [
        "Sorry, but something went wrong!", 
        "Please check the troubleshooting guide.", 
        "https://trailofbits.github.io/algo/troubleshooting.html"
    ]
}

TASK [vpn : fail] **************************************************************
fatal: [159.89.123.189]: FAILED! => {"changed": false, "msg": "Failed as requested from task"}

This has happened on multiple attempts with new droplets each time, and fresh downloads of Algo each time. Have tried rebooting my Mac, does not help.

Any suggestions?

**Comment by davidemyers** [comment]
Could you post your list of users from your `config.cfg`?

**Comment by gittalicious** [comment]
This is not very original, but here goes:
- Vpna
- Vpnb
- Vpnc
- Vpnd
- Vpne
- Vpnf
- Vpng
- Vpnh
- Vpni
- Vpnj
- Vpnk
- Vpnl
- Vpnm
- Vpnn

I am not sure why the user names would cause this error? I have previously used exactly the same list on other Algo installations on DO without this error.

**Comment by davidemyers** [comment]
I wanted to make sure there were no shell metacharacters in any of the user names, as that might break something. But clearly that's not the issue.

**Comment by gittalicious** [comment]
Ah, got it. Any idea what might be causing this error then?

BTW, do you have a list of these shell metacharacters? It would be good to know for future reference so I can avoid using in situations like this.

**Comment by davidemyers** [comment]
I don't know this for a fact, but I suspect any of the following could cause problems when used in Algo user names:
```
 |  & ; ( ) < > space tab
```
I usually run Algo from Ubuntu and just ran a test deploy that worked properly. I'm not sure what's up with your Mac.

**Comment by patrickstjohn** [comment]
I'm having the same problem with both GCE and DO doing an install from macOS Mojave. No problems previously. Seems there is some sort of error validating the XML when I turn on logging.

**Comment by aapeliv** [comment]
Same issue with EC2 on macOS Mojave.

**Comment by davidemyers** [comment]
@patrickstjohn Can you post the error messages?

I think LibreSSL was changed in 10.14.3 and I wonder if that has anything to do with this.

**Comment by davidemyers** [comment]
Are any of you using the option to exclude networks from "Connect On Demand"?
```
List the names of trusted Wi-Fi networks (if any) that macOS/iOS clients exclude from using the VPN
(e.g., your home network. Comma-separated value, e.g., HomeNet,OfficeWifi,AlgoWiFi)
```

**Comment by gittalicious** [comment]
Yes, I am excluding one network. It is called “Main” - no special characters or spaces. I have excluded the same network on previous Algo installs and it has never presented an issue. Is this somehow causing a problem now?

**Comment by davidemyers** [comment]
There was recently a change to how the the names of excluded networks are saved for later use. As a workaround try deploying without an excluded network.

You can also try to rewind a copy of Algo to before this change if you use `git` (which is not installed by default on macOS):
```
git clone https://github.com/trailofbits/algo.git
cd algo
git checkout a266b4d633493d4766e1cce6d0689cb755a0881d
```

@jackivanov The error I think I see is:
```
AnsibleError: Unexpected templating type error occurred on (content of mobileconfig.j2): Incorrect padding
```

**Comment by TC1977** [comment]
Can you run `./algo -vvv` and post the full output please?

**Comment by patrickstjohn** [comment]
I have an excluded Wi-Fi network as well. Here are the errors on:
```
"TASK [vpn : Set facts for mobileconfigs] ****************************************************************************************
```
```
failed: [XXX.XXX.XXX.XXX -> localhost] (item=[u'username', {'_ansible_parsed': True, 'stderr_lines': [], u'cmd': u'cat private/username.p12 | base64', u'end': u'2019-02-02 16:51:26.352140', '_ansible_no_log': False, '_ansible_delegated_vars': {'ansible_delegated_host': u'localhost', 'ansible_host': u'localhost'}, '_ansible_item_result': True, u'changed': True, u'stdout': '', 'item': u'username, u'delta': u'0:00:00.012781', u'stderr': u'', u'rc': 0, u'invocation': {u'module_args': {u'warn': True, u'executable': None, u'_uses_shell': True, u'_raw_params': u'cat private/username.p12 | base64', u'removes': None, u'creates': None, u'chdir': u'configs/XXX.XXX.XXX.XXX/pki/', u'stdin': None}}, 'stdout_lines': '', u'start': u'2019-02-02 16:51:26.339359', '_ansible_ignore_errors': None, 'failed': False}]) => {
```
```
"msg": "AnsibleError: Unexpected templating type error occurred on
```
Which then spits out the mobileconfig and ends up with this:
```
: Incorrect padding
```
I'm guessing there is a problem with roles/vpn/templates/mobileconfig.j2 and how it's templating out the excluded wifi network. 

```
{% if algo_ondemand_wifi_exclude|b64decode != '_null' %}
{% set WIFI_EXCLUDE_LIST = (algo_ondemand_wifi_exclude|b64decode|string).split(',') %}
```
I removed the templating from the above section manually entered in my wifi exclude list and it kicked through properly.

**Comment by gittalicious** [comment]
I was able to work around this by selecting "yes" for on demand, and not listing my excluded networks when asked. Then I manually edited the mobileconfig files after Algo successfully ran through the entire install process. A little bit more work this way, but it did solve the problem.
