### ISSUE TITLE
Wifi exceptions no longer working

### ISSUE THREAD

**Issue by mpblair** [trailofbits/algo#1317]
It appears that commit id c47dd4a7abc401388b8165989a2f6ef3ca7b88c4 (fix for wifi with emoji names) broke wifi exceptions.  My home wifi SSID has no emojis, and is of the form, "Word1 Word2" (space between Word1 and Word2).

I checked out the commit just prior to the wifi emoji fix (a266b4d633493d4766e1cce6d0689cb755a0881d), and the VPN does not connect on my home wifi (as expected).  I checked out the wifi emoji fix (https://github.com/trailofbits/algo/commit/c47dd4a7abc401388b8165989a2f6ef3ca7b88c4), and the VPN connects while on my home wifi (not expected).

1. Pull latest from master (which includes commit c47dd4a7abc401388b8165989a2f6ef3ca7b88c4)
2. Execute ./algo, and specify that iOS devices will connect to the VPN over WiFi
3. Specify SSID exclusions (no emojis, SSID of the form "Word1 Word2" (space between Word1 and Word2)
4. Once deployment is complete and profile is installed on iOS device, observe that the device connects to the VPN even when the device is on an excluded SSID

**Expected behavior**

SSID exclusions are honored for all allowable SSIDs.

**Comment by jackivanov** [comment]
Duplicate #1315

**Comment by TC1977** [comment]
Wonder if this was a Wireguard-related issue (#1328).
