### ISSUE TITLE
Lightsail IAM policy needs to allow GetRegions

### ISSUE THREAD

**Issue by psoberoi** [trailofbits/algo#1321]
Lightsail deployment fails using the IAM policy in docs/deploy-from-ansible.md with the following error:

TASK [cloud-lightsail : Get regions] *****************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AccessDeniedException: An error occurred (AccessDeniedException) when calling the GetRegions operation: User: arn:aws:iam::762540811739:user/algo is not authorized to perform: lightsail:GetRegions on resource: arn:aws:lightsail:us-east-1:762540811739:*
fatal: [localhost]: FAILED! => {"changed": false, "msg": "An error occurred (AccessDeniedException) when calling the GetRegions operation: User: arn:aws:iam::762540811739:user/algo is not authorized to perform: lightsail:GetRegions on resource: arn:aws:lightsail:us-east-1:762540811739:*"}

It succeeds when "lightsail:GetRegions" is added to the list of allowed actions. Here's the full policy I used:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "LightsailDeployment",
            "Effect": "Allow",
            "Action": [
                "lightsail:GetRegions",
                "lightsail:GetInstance",
                "lightsail:CreateInstances",
                "lightsail:OpenInstancePublicPorts"
            ],
            "Resource": [
                "*"
            ]
        }
    ]
}
```

**Comment by jackivanov** [comment]
Thanks!
