### ISSUE TITLE
BSOD after connecting to VPN

### ISSUE THREAD

**Issue by Zetsukaze** [trailofbits/algo#1322]
**Describe the bug**

After a short duration (<5min) connecting to the VPN, the two desktops that it is installed on (Win 10) gets BSOD.

**To Reproduce**

1. Connect to the VPN
2. BSOD

**Expected behavior**

Not BSOD

**Additional context**

Reinstalled multiple times. Restarted multiple times.

**Comment by jackivanov** [comment]
It's not related to AlgoVPN. You are welcome to ask such kind of questions on [gitter](https://gitter.im/trailofbits/algo)

**Comment by Zetsukaze** [comment]
How is it not related to AlgoVPN? The only action taken was to connect to it. I wait a short while, and it BSODs.

**Comment by TC1977** [comment]
It's related in that Algo is setting up a VPN connection, but it's a Windows problem. Try googling "Windows 10 VPN BSOD" and you'll find a bunch of error reports, none of them having to do with IPsec or Algo. Some of them might have helpful debug suggestions.
