### ISSUE TITLE
ssh tunnel closes immediately  

### ISSUE THREAD

**Issue by L3rchal** [trailofbits/algo#1324]
**Describe the bug**

After creating new fresh algo instance on aws ec2, trying to connect via ssh, connection closes immediately after successful login. 

**To Reproduce**

1. Based on aws ec2 tutorial in docs create new instance. 
2. Setup only user in config "jack"
3. During installation enable option to create separate ssh logins for users
4. copy all keys from configs
5. test vpn fine
6. login via ssh(`ssh jack@x.x.x.x -i jack.ssh.pem`), closes after succesful login

**Expected behavior**

Be able to ssh to machine and check logs for example

**Additional context**
>@L3rchal I googled your problem and wonder if it's because you created an "Alex" user for your droplet, but didn't create a home directory.
>Maybe this link will help you fix it: https://askubuntu.com/questions/1000220/ssh-without-a-home-directory
You may have to just blow it up and start over.

Tried to create different user in isolated clean environment. Bust the previous version and start again and the problem is still there via latest version on master/algo.

Wonder if anyone has same problem.
**Full log**

https://gist.github.com/L3rchal/cb3927f4c9349841b0edb8261643c70b

**Comment by davidemyers** [comment]
As it says in the [README](https://github.com/trailofbits/algo#setup-an-ssh-tunnel) (emphasis added):

> If you turned on the optional SSH tunneling role, then local user accounts will be created for each user in `config.cfg` and SSH authorized_key files for them will be in the `configs` directory (user.ssh.pem). SSH user accounts **do not have shell access**, cannot authenticate with a password, and only have limited tunneling options (e.g., `ssh -N` is required). This ensures that SSH users have the least access required to setup a tunnel and can perform no other actions on the Algo server.

**Comment by TC1977** [comment]
The user that you use to actually SSH into the server is root. See https://github.com/trailofbits/algo#ssh-into-algo-server

**Comment by L3rchal** [comment]
> Note the admin username is **ubuntu** instead of root on providers other than Digital Ocean.
 
🤦‍♂️🤦‍♂️🤦‍♂️

I was trying `root` whole time omg.  Anyway thanks for the explanation. 
Algo rocks! ❤️
