### ISSUE TITLE
How to restart algo after reboot on Ubuntu 18 local install?

### ISSUE THREAD

**Issue by chambm** [trailofbits/algo#1326]
I installed Algo on a t5.nano Ubuntu 18.04 instance on Alibaba Cloud. Worked great yesterday, but when I shut down the server and restarted it today, the VPN didn't come back up. When I tried to rerun ./algo it started creating a new server.

**Comment by TC1977** [comment]
I don't know how Alibaba Cloud works. When you restart a VM there, does it come back up with a new IP address?

**Comment by chambm** [comment]
It might, but in this case it didn't. Would that be a problem on the server-side?

**Comment by dguido** [comment]
Alibaba is not a supported cloud provider. Please use the Gitter for support.
