### ISSUE TITLE
On-demand wifi network exclusion doesn't work with WG

### ISSUE THREAD

**Issue by rodalpho** [trailofbits/algo#1328]
**Describe the bug**
I input my home wifi SSID to exclude from on-demand when building my config. I double-checked this was correct.

I then used the QR code to add the config to my iPhone. This all works fine, connects, etc. 

However when on-demand is active and I'm connected to my home wifi SSID, it immediately connects to wireguard. Does the wifi network exclusion functionality not work with the WG client, is it IKEv2 only?

**Expected behavior**
My iPhone should disconnect from the wireguard VPN when I connect to my home wifi.

**Comment by davidemyers** [comment]
You are correct that this feature is for IPsec only. Excluding SSIDs is on the WireGuard app [TODO](https://docs.google.com/document/d/1BnzImOF8CkungFnuRlWhnEpY2OmEHSckat62aZ6LYGY/edit) list, but I'm not sure if Algo will be able to set it or if, like "Connect on Demand", you'll need to set it from the WireGuard app.

Please leave this issue open and I'll submit a PR to clarify the Algo prompts.

**Comment by rodalpho** [comment]
Ahh, I suspected that was the case. And thank you for the excellent software!

**Comment by davidemyers** [comment]
Don't thank *me*, I just help out where I can. :smiley:

**Comment by rodalpho** [comment]
Well, thanks to the developers, then!

Also as long as you're submitting PRs to clarify documentation, the MacOS Wireguard client was happily released earlier today. It's in the Mac app store.

https://itunes.apple.com/us/app/wireguard/id1451685025?ls=1&mt=12

**Comment by davidemyers** [comment]
I submitted a PR already: #1327.

**Comment by TC1977** [comment]
Please reopen this issue. As of two days ago the Wireguard iOS app now supports the ability to exclude (or _include_, for that matter) specific Wi-Fi SSIDs.

**Comment by rodalpho** [comment]
The WG MacOS application supports this functionality also now.

**Comment by TC1977** [comment]
I don't see any obvious way to pass the exclusion list to the Wireguard iOS/macOS app, at least not through the wireguard config files. Should this just be documented separately for now? I could do this.

**Comment by jackivanov** [comment]
I'm closing this one as it's been documented
