### ISSUE TITLE
How would one use AES128 instead of AES256?

### ISSUE THREAD

**Issue by exabrial** [trailofbits/algo#1336]
We don't need AES256, we'd rather have AES128 to reduce CPU overhead and latency. I totally understand the manifesto behind algo, versioning > negotiation. 

If we wanted to modify the scripts to only support AES128, where would be need to make those changes at?

Thank you,
-Jonathan

**Comment by jackivanov** [comment]
You can find the ciphers configured [here](https://github.com/trailofbits/algo/blob/master/roles/vpn/defaults/main.yml#L61). Also, you may want to take a look at [ipsec.conf](https://github.com/trailofbits/algo/blob/master/roles/vpn/templates/ipsec.conf.j2) for any clarifications
