### ISSUE TITLE
Docker Optimization

### ISSUE THREAD

**Issue by johnwesley** [trailofbits/algo#1340]
**Is your feature request related to a problem? Please describe.**
To make deploying Algo with Docker more streamlined, I have written a `Makefile` to build, deploy, and clean.

In addition to the above, I had run into some issues with `algo` calling the `ansible-playbook` binary from within the **virtualenv**. I didn't see the need to activate a **virtualenv** within an image or a container, but realize this is exactly how the main `algo` script needs to operate for a desktop OS.

**Describe the solution you'd like**
The `Makefile` has four targets:

1. `docker-build`
2. `docker-deploy` (deploys server instance from container, bind-mounts, etc)
3. `docker-clean` (remove image)
4. `all` 

Remove `source env/bin/activate` from the `Dockerfile` letting Ansible install to `/usr/local/bin` in this ephemeral environment. This way `algo` can still activate an environment and call `ansible-playbook`; running normally.  

**Describe alternatives you've considered**
There's a reason for activating a virtualenv in a container I have missed.

**Additional context**
I have a branch ready for a PR that's been tested with OSX. If the maintainers think this is a worthwhile endeavor, I would be happy to provide further testing and documentation. 

It consists of two changes to date:

1. one `Makefile`
2. one line removed from `Dockerfile`

Thank you

**Comment by jackivanov** [comment]
Thanks, I think this would be a good enhancement. i don't see any reason to run virtualenv inside a docker container as well. Could you send a PR, please?

**Comment by johnwesley** [comment]
@jackivanov done and opened as a draft. The `make docker-clean` target needs logic to remove any stopped containers, in addition to any other concerns you may have. Thank you.

**Comment by johnwesley** [comment]
Got it. I'll get a branch up.

**Comment by jackivanov** [comment]
Closed by #1553
