### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by omarquadri** [trailofbits/algo#1349]
currently trying to install algo on azure but keep getting this error

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: IOError: [Errno 2] No such file or directory: '/home/uae/.azure/azureProfile.json'
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_tUqwQU/ansible_module_azure_rm_deployment.py\", line 664, in <module>\n    ma/ansible_module_azure_rm_deployment.py\", line 660, in main\n    AzureRMDeploymentManager()\n  File \"/tmp/ansible_tUqwQU/ansible_module_azure_rm_deployment.py\", line 434, in __init__\n    supports_checle_tUqwQU/ansible_modlib.zip/ansible/module_utils/azure_rm_common.py\", line 270, in __init__\n  File \"/tmp/ansible_tUqwQU/ansible_modlib.zip/ansible/module_utils/azure_rm_common.py\", line 576, in _gete_tUqwQU/ansible_modlib.zip/ansible/module_utils/azure_rm_common.py\", line 493, in _get_azure_cli_credentials\n  File \"/home/uae/algo/configs/.venvs/azure/lib/python2.7/site-packages/azure/common/crede_cli_credentials\n    profile = get_cli_profile()\n  File \"/home/uae/algo/configs/.venvs/azure/lib/python2.7/site-packages/azure/common/credentials.py\", line 28, in get_cli_profile\n    ACCOUNT.load(osfile.json'))\n  File \"/home/uae/algo/configs/.venvs/azure/lib/python2.7/site-packages/azure/cli/core/_session.py\", line 61, in load\n    self.save()\n  File \"/home/uae/algo/configs/.venvs/azure/lib/pyre/_session.py\", line 65, in save\n    with codecs_open(self.filename, 'w', encoding=self._encoding) as f:\n  File \"/home/uae/algo/env/lib/python2.7/codecs.py\", line 898, in open\n    file = __builtin\nIOError: [Errno 2] No such file or directory: '/home/uae/.azure/azureProfile.json'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}

**Comment by jackivanov** [comment]
I can't reproduce. Try to deploy from scratch using this [doc](https://trailofbits.github.io/algo/cloud-azure.html)

**Comment by arizzubair** [comment]
Did you follow the azure documentation? https://github.com/trailofbits/algo/blob/master/docs/cloud-azure.md
