### ISSUE TITLE
errors adding profile to Mac OS 10.12.1

### ISSUE THREAD

**Issue by jnelson** [trailofbits/algo#135]
I have a feeling I'm missing something obvious that isn't yet included in the docs or issues. I've tried running through the whole process both with and without a virtualenv. My default shell is zsh but I used an up-to-date homebrew bash subshell to run the `./algo` script. I used the default ssh identity. Please let me know if any further info would be helpful.

Edit: All options 'no' except unsupervised-updates.

### OS / Environment

Mac OS 10.12.1 (Sierra)

### Ansible version
`ansible 2.2.0.0`

### Version of components from `requirements.txt`
```
Name: boto
Version: 2.43.0
Summary: Amazon Web Services Library
Home-page: https://github.com/boto/boto/
Author: Mitch Garnaat
Author-email: mitch@garnaat.com
License: MIT
Location: /Users/jon/pyenv/base/lib/python2.7/site-packages
Requires:
---
Name: apache-libcloud
Version: 1.4.0
Summary: A standard Python library that abstracts away differences among multiple cloud provider APIs. For more information and documentation, please see http://libcloud.apache.org
Home-page: http://libcloud.apache.org/
Author: Apache Software Foundation
Author-email: dev@libcloud.apache.org
License: Apache License (2.0)
Location: /Users/jon/pyenv/base/lib/python2.7/site-packages
Requires:
---
Name: six
Version: 1.8.0
Summary: Python 2 and 3 compatibility utilities
Home-page: http://pypi.python.org/pypi/six/
Author: Benjamin Peterson
Author-email: benjamin@python.org
License: MIT
Location: /Users/jon/pyenv/base/lib/python2.7/site-packages
Requires:
```

### Summary of the problem
![image](https://cloud.githubusercontent.com/assets/235301/20691678/ca815900-b58f-11e6-9e41-fe9d922387d8.png)
"Profile installation failed. The 'VPN Service' payload could not be installed. The VPN service could not be created."

### Steps to reproduce the behavior
Double-click the `.mobileconfig` file and follow the instructions (including successful authentication).

### Expected behavior
The profile will be added and the VPN configuration will be available.

### Actual behavior
Failure.
```
default	16:53:49.842919 -0700	com.apple.preferences.configurationprofiles.remoteservice	CSSM Exception: -25264 MAC verification failed during PKCS12 import (wrong password?)
===related UI errors?===
default	16:53:51.985640 -0700	com.apple.preferences.configurationprofiles.remoteservice	CSSM Exception: -25264 MAC verification failed during PKCS12 import (wrong password?)
default	16:53:57.069288 -0700	mdmclient	ImportKeychainData SecKeychainItemImport returned: -25264
default	16:53:57.081219 -0700	mdmclient	<private>
default	16:53:57.081311 -0700	mdmclient	ProfileDomainPluginController.installProfileWithPlugin Finished installPayload; failedDomain: com.apple.vpn.managed
error	16:53:57.262190 -0700	mdmclient	CPProfileManager.installProfile returning error -319 (<private>)
error	16:53:57.569261 -0700	com.apple.preferences.configurationprofiles.remoteservice	[ERROR] Profile installation (35.161.109.146 IKEv2 (donut.local.850A3AA3-4422-5CE0-81B9-3164142418DB:FC5751C9-669A-59A4-A5AA-D334CCE6C41C)) (Error Domain=ConfigProfilePluginDomain Code=-319 "The 'VPN Service' payload could not be installed. The VPN service could not be created." UserInfo={NSLocalizedDescription=The 'VPN Service' payload could not be installed. The VPN service could not be created.})
===more related errors?===
```

**Comment by gunph1ld** [comment]
Can you show your mobileconfig? (You can revoke existing certificates)

**Comment by gunph1ld** [comment]
ping @jnelson

**Comment by attilagyorffy** [comment]
For the record, I also happen to have macOS 10.12.1 installed and the `.mobileconfig` file imported just fine. Something might be specific to the config @jnelson got.

**Comment by Jolg42** [comment]
I have the same window "Profile installation failed", with macOS 10.11.6 El Capitan 😢

**Comment by Jolg42** [comment]
@gunph1ld Fixed for me! 🎊  Thank you for the quick fix!

**Comment by Jolg42** [comment]
Apparently the origin of the issue was special chars in the password, so removing them did the trick for me but the fix is coming soon for specials chars anyway :)

**Comment by gunph1ld** [comment]
The behavior occurs due to special characters in the p12 password, the commit above should resolve the issue
