### ISSUE TITLE
Cloudflare 400 Bad Request: invalid header value when deploying to Digital Ocean

### ISSUE THREAD

**Issue by atti-dall-atto** [trailofbits/algo#1354]
I tried my first algo deployment - which failed with this

[cloud-digitalocean : pause]
Enter your API token. The token must have read and write permissions (https://cloud.digitalocean.com/settings/api/tokens):
 (output is hidden):

TASK [cloud-digitalocean : pause] **********************************************
ok: [localhost]

TASK [cloud-digitalocean : Set the token as a fact] ****************************
ok: [localhost]

TASK [cloud-digitalocean : Get regions] ****************************************
fatal: [localhost]: FAILED! => {"cf_ray": "<redacted>LHR", "changed": false, "connection": "close", "content": "400 Bad Request: invalid header value", "content_type": "text/plain; charset=utf-8", "date": "Tue, 12 Mar 2019 18:25:03 GMT", "expect_ct": "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"", "msg": "Status code was 400 and not [200]: HTTP Error 400: Bad Request: invalid header value", "redirected": false, "server": "cloudflare", "set_cookie": "__cfduid=<redacted>; expires=Wed, 11-Mar-20 xx:xx:xxGMT; path=/; domain=.digitalocean.com; HttpOnly", "status": 400, "transfer_encoding": "chunked", "url": "https://api.digitalocean.com/v2/regions"}

??? It doesn't say in the documentation what part of the token should be entered - the name or the long hexadecimal value. I entered the latter and it said OK, so I assume it is failing because the Ansible script is asking for a region list URL which is broken ???

**Comment by atti-dall-atto** [comment]
this appears to e a transient error - region list was displayed on second attempt some 30 mins later

**Comment by nudge7** [comment]
I'm having this exact same issue. I've tried again a few different times and no difference. I've previously successfully installed Algo from Windows to DO.
