### ISSUE TITLE
Setting up VULTR - ini file error message

### ISSUE THREAD

**Issue by hockeyczar** [trailofbits/algo#1359]
![SCR 2019-03-15 at 3 24 15 PM](https://user-images.githubusercontent.com/48587310/54424773-41478600-4746-11e9-8b28-a074b7cb2304.jpg)

Hello,  I am trying to create an ALGO wireguard VPN server on a Vultr instance using macOS terminal and during the process I get the following error message: 

 fatal: [localhost]: FAILED! => {"changed": false, "msg": "Config file not found. Tried : /Users/curtisbuckley/.vultr.ini, /Users/curtisbuckley/Downloads/algo-master/vultr.ini, 

https://api.vultr.com/v1/os/list"}

  ALGO directs me to this link with the following comments:

 Configuration file:   You need to create a configuration file in INI format with your api key (https://my.vultr.com/settings/#settingsapi)  [default] 
key = <your api key>

  Can anyone perhaps advise what I need to do to create an INI configuration file with my VULTR api key please? I am out of ideas and no amount of research has helped me thus far.

  Thank you.
U bUk

**Comment by jackivanov** [comment]
I suggest you to use [gitter](https://gitter.im/trailofbits/algo) for this kind of questions

**Comment by hockeyczar** [comment]
Oh, I suggest you explain why u deleted my issue?

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by hockeyczar** [comment]
twat

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
