### ISSUE TITLE
Can not figure out how to configure ubuntu 18 as a client

### ISSUE THREAD

**Issue by shivenigma** [trailofbits/algo#1367]
The docs show an easy way to configure android and iOS devices, but its not the case for ubuntu. I can not figure out how to use the created VPN in my machine, everything works fine with android though.

**Comment by davidemyers** [comment]
There are  instructions for configuring an Ubuntu WireGuard client on [this page](https://github.com/trailofbits/algo/blob/master/docs/client-linux-wireguard.md).

**Comment by shivenigma** [comment]
@davidemyers Thanks for your time, I followed them but I think I might have stuck somewhere as wireguard is failing to start. I can't find out any useful info in the systemctl status.

**Comment by davidemyers** [comment]
What error messages are you getting?

**Comment by shivenigma** [comment]
Found it, there was a typo in the configuratiton file. I fixed it and its working fine.
