### ISSUE TITLE
Crypto IP Sec tunnel Cisco IOS config

### ISSUE THREAD

**Issue by mohang2019** [trailofbits/algo#1368]
Looking module for IOS crypto config 

crypto map
crypto isakmp profile

**Comment by TC1977** [comment]
What does this mean? Are you looking for instructions on how to set up the IPsec mobileconfig for iOS? Try [this page](https://github.com/trailofbits/algo/blob/master/docs/client-apple-ipsec.md).

**Comment by mohang2019** [comment]
From Ansible...

**Comment by TC1977** [comment]
Do the ansible deploy, and then get the mobileconfig files from the directory as in the link above.

**Comment by mohang2019** [comment]
I was looking for python module to have the playbook shown below, to configure crypto IOS config

Test.yml
---
- hosts: localhost
  connection: local
  vars_prompt:
  - name: "keyring"
    prompt: "Enter Keyring"
  - name: "shared_key"
    prompt: "Enter Partner Shared key"
  - name: "suid"
    prompt: "Enter ACL id" 
  tasks:
  - name: Create Crypto Map
    crypto_map:
    ip_address: routerIP
    description: Partner Name
    set_peer: IP address (Partner IP)
    transform_set: encryption-key (string & int) (use existing)
    isakmp_profile: string&int
  
  - name: deploy acl configuration
    acl_config:
      parents: ip access-list extended
      lines:
        - permit tcp 192.168.122.10 0.0.0.0 any eq 22
      before: "no ip access-list extended

**Comment by jackivanov** [comment]
Ping @mohang2019. Did you manage to get that working?
