### ISSUE TITLE
Can't add a user to VPN. Ansible error.

### ISSUE THREAD

**Issue by evahlis** [trailofbits/algo#137]
### OS / Environment
OS X Sierra 

### Ansible version
ansible 2.2.0.0

### Summary of the problem
Setting up initial VPN works well, but adding a user to configs.cfg and running ./algo update-users fails

`TASK [Build the mobileconfigs] *************************************************
failed: [54.90.123.88] (item=(censored due to no_log)) => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result"}`

### Steps to reproduce the behavior
- Create VPN on AWS by running `./algo` and following the steps.
- Add a user to configs.cfg
- Run `./algo update-users`

### Actual behavior
`TASK [Build the mobileconfigs] *************************************************
failed: [54.90.123.88] (item=(censored due to no_log)) => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result"}`

**Comment by evahlis** [comment]
Upon disabling the no_log option in users.yml line 114, i get the following log output suffix:

```
...
"msg": "AnsibleUndefinedVariable: 'pkcs12_PayloadCertificateUUID' is undefined"
```

**Comment by alechangbiao** [comment]
I got this exception when trying to add users:
: ./algo: line 443: ansible-playbook: command not found

How to fix that?

**Comment by dguido** [comment]
https://github.com/trailofbits/algo/blob/master/docs/troubleshooting.md

**Comment by alechangbiao** [comment]
hey i did followed the direction to install algo, and cd into the 'algo-master' directory. but still get the  ": ./algo: line 443: ansible-playbook: command not found" 
Is there a way to fix it?
