### ISSUE TITLE
Adblock can not be temporarily disabled

### ISSUE THREAD

**Issue by malfini** [trailofbits/algo#1370]
I use ALGO VPN with adblock turned on. Occasionally, I visit websites which detect adblock and request that it should be turned off. In this case it is a streaming service, so if I don't turned it off, I can't watch it (and I can only watch it with VPN ...). 

1. In /usr/local/sbin/adblock.sh I edit BLOCKLIST_URLS line to:
BLOCKLIST_URLS=""
This should remove all blocklists. 

2. I run adblock.sh and confirm that /etc/dnsmasq.d/block.hosts.conf does not contain any list of blocked domains. dnsmasq is active. 

3. I restart VPN, reconnect to it, but websites still have no ads. It seems that adblock is still turned on. 

Any ideas? Is there any additional cache that need to be cleaned?

**Comment by TC1977** [comment]
Sounds like you also need to clear your browser cache (and turn off adblocking extensions in your browser, if any exist).

**Comment by TC1977** [comment]
Actually, you can leave dnsmasq and its adblocking enabled on the Algo server, and simply change the DNS server on your client.

**Comment by malfini** [comment]
1. "Sounds like you also need to clear your browser cache (and turn off adblocking extensions in your browser, if any exist)."

I used Chrome browser without any extensions and all cache was cleared. It still doesn't work. 

2. "Actually, you can leave dnsmasq and its adblocking enabled on the Algo server, and simply change the DNS server on your client. This won't work for macOS and iOS; forgot that when connected to the VPN the client will only accept the VPN's DNS server, and not any custom DNS (like 8.8.8.8) that you enter in Settings."

True.

BUT

You can edit Wireguard connection profile and change DNS server settings there. I set it to 9.9.9.9 and it works. That solved my problem. Thanks!

**Comment by aa6my** [comment]
> 1. /usr/local/sbin/adblock.sh



> I use ALGO VPN with adblock turned on. Occasionally, I visit websites which detect adblock and request that it should be turned off. In this case it is a streaming service, so if I don't turned it off, I can't watch it (and I can only watch it with VPN ...).
> 
> 1. In /usr/local/sbin/adblock.sh I edit BLOCKLIST_URLS line to:
>    BLOCKLIST_URLS=""
>    This should remove all blocklists.
> 2. I run adblock.sh and confirm that /etc/dnsmasq.d/block.hosts.conf does not contain any list of blocked domains. dnsmasq is active.
> 3. I restart VPN, reconnect to it, but websites still have no ads. It seems that adblock is still turned on.
> 
> Any ideas? Is there any additional cache that need to be cleaned?

> Hi, how i want to disable ads blocking in algo ?

`Disable ads in algo VPN`

```
ssh -F configs/<VPN_IP_ADDRESS>/ssh_config algo
sudo sed -i -e "s~BLOCKLIST_URLS=~#BLOCKLIST_URLS=~g" /usr/local/sbin/adblock.sh && sudo /usr/local/sbin/adblock.sh
```

`*please check blacklist contain in /etc/dnscrypt-proxy/blacklist.txt - its should be blank`
