### ISSUE TITLE
Is Python 2.7 still the default choice on RHEL/CentOS

### ISSUE THREAD

**Issue by upenr** [trailofbits/algo#1371]
The documentation to install Algo on RHEL/CentOS still references older versions of these operating systems and asks to rely on Python 2.7. The following message appears on 'pip' commands. Should the documentation be updated?
"DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
"

**Comment by jackivanov** [comment]
We will move the client's side to python3 later this year.
