### ISSUE TITLE
Windows VPN CLient DNS Resolve still showing my local country ISP DNS

### ISSUE THREAD

**Issue by Tabarane** [trailofbits/algo#1373]
Deployed ALGO over Digital Ocean using standard method, including DNS ad block

Deployed VPN Connection using Powershell script, Disabled IPV6 on the VPN Adapter

My IP is showing my ALGO Server, but using https://whoer.net/ is show me local country DNS

any idea? or what information you need to have?

**Comment by TC1977** [comment]
There's a bunch of old issues that might give you some ideas: #110, #565, #806, #896, among others. To summarize, main suggestions are to disable IPV6 on the VPN adapter (which you did), turn off WebRTC on Firefox, and check your browser extensions for leaks.

Please post a screenshot of whoer.net when connected to the VPN (black out your IP and location info), as well as a screenshot of the (https://dnsleaktest.com) extended test.

**Comment by Tabarane** [comment]
![image](https://user-images.githubusercontent.com/28815281/55080710-01728e00-50b8-11e9-90ba-8d72dc33aac6.png)
![image](https://user-images.githubusercontent.com/28815281/55080844-3e3e8500-50b8-11e9-82bc-223b0ebe5149.png)
pairin mind i manually changed DNS in windows adapter to opendns, and still the same happening

**Comment by TC1977** [comment]
So this shows that you're sometimes getting Cloudflare for DNS (which is through the VPN), and sometimes not. Could your router or computer be somehow overriding your DNS settings?

**Comment by TC1977** [comment]
@Tabarane Does [this link](https://www.thewindowsclub.com/what-is-dns-leak) help?

**Comment by TC1977** [comment]
@Tabarane I tried changing the DNS servers on the adapter as recommended in that article and it didn't help. Perhaps [this guide](https://www.neowin.net/news/guide-prevent-dns-leakage-while-using-a-vpn-on-windows-10-and-windows-8/) might help. Short answer: use Group Policy Editor to " turn off smart multi-homed name resolution".

If you're using Windows 10 Home, you don't have Group Policy Editor and have to download a freeware version called PolicyPlus.

Direct link to PolicyPlus from the article is [here](https://github.com/Fleex255/PolicyPlus).

**Comment by jackivanov** [comment]
We are moving to WireGuard for Windows and deprecating IKEv2. You may want to give it a try.
