### ISSUE TITLE
Possible to specify Azure Resource Group?

### ISSUE THREAD

**Issue by onpaws** [trailofbits/algo#1375]
**Is your feature request related to a problem? Please describe.**
Not sure if this should be considered a feature request -- I'll try and explain.

Over at MS Azure we have some VMs living inside a resource group. I'd like to specify to Algo, ostensibly as one of the "interview questions" asked on startup, what Azure Resource Group Algo gets provisioned inside of.

The idea is to keep the Algo instance co-located with the resources we intend to connect to. Among other reasons, I understand all traffic that occurs within the boundaries of a Virtual Network is free.

**Describe the solution you'd like**

If I'm understanding this right, it means surfacing [this field](https://github.com/trailofbits/algo/blob/30beadb9490342b1da9ca0fed187720adc71d0d1/roles/cloud-azure/tasks/main.yml#L25) in Algo's interview questions.
Maybe something like this (taken from an older Algo release):
```
$ ./algo

  What provider would you like to use?
    1. DigitalOcean
    2. Amazon EC2
    3. Google Compute Engine
    4. Microsoft Azure
    5. Install to existing Ubuntu server

Enter the number of your desired provider
: 4

Enter your azure secret (https://docs.ansible.com/ansible/guide_azure.html#authenticating-with-azure)
You can skip this step if you want to use your defaults credentials from ~/.azure/credentials
[...]:

Enter your azure tenant (https://docs.ansible.com/ansible/guide_azure.html#authenticating-with-azure)
You can skip this step if you want to use your defaults credentials from ~/.azure/credentials
[...]:

Enter your azure client_id (https://docs.ansible.com/ansible/guide_azure.html#authenticating-with-azure)
You can skip this step if you want to use your defaults credentials from ~/.azure/credentials
[...]:

Enter your azure subscription_id (https://docs.ansible.com/ansible/guide_azure.html#authenticating-with-azure)
You can skip this step if you want to use your defaults credentials from ~/.azure/credentials
[...]:
Enter the local path to your SSH public key (~/.ssh/id_rsa.pub):

Name the vpn server:
[algo]:

  What region should the server be located in?
    1.  South Central US
    2.  Central US
    3.  North Europe
    4.  West Europe
    5.  Southeast Asia
    6.  Japan West
    7.  Japan East
    8.  Australia Southeast
    9.  Australia East
    10. Canada Central
    11. West US 2
    12. West Central US
    13. UK South
    14. UK West
Enter the number of your desired region:
[1]: 2

Enter the desired Azure Resource Group Name (optional):
[algo]: MyResourceGroup

```

**Describe alternatives you've considered**
I was considering manually patching the [name](https://github.com/trailofbits/algo/blob/30beadb9490342b1da9ca0fed187720adc71d0d1/roles/cloud-azure/tasks/main.yml#L25) in the playbook, but given there are, I believe, network security group settings that come along as part of an Algo deploy, not 100% sure that will suffice.

Unless I'm missing some good reasons it's not possible, seems like it'd be possible and nice to allow this from the UI.

**Comment by jackivanov** [comment]
Hi,

Thanks for your attention. The request seems like a case specific, and doesn't fit to simple use cases that we try to follow to. Meanwhile, you can move the resources to another resource group as described [here](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-move-resources) to achieve your particular needs.
