### ISSUE TITLE
Mac OS El Capitan

### ISSUE THREAD

**Issue by AnderCrafter** [trailofbits/algo#1376]
Hello Dear Developers,
i need to connect an Home Server running Mac OSX El Capitan (can't be upgraded) to my Algo VPN. The Wireguard Software isn't available for El Capitan, the .mobileconfig doesn't work.

When configuring Wireguard on other devices i needed to change the dns to 1.1.1.1 to get an working connection. How can i do this on mobilconfigs?

**Comment by TC1977** [comment]
You don't have to change the DNS on the mobileconfigs. Change the `rightdns=` setting in `/etc/ipsec.conf` on the Algo server to `1.1.1.1`.

Please note that El Capitan isn't supported, so there's a lot of other stuff that might not work correctly. Good luck.

**Comment by AnderCrafter** [comment]
Hi,
Thanks @TC1977 ,
it is working, my Goal of being able to connect to the Media Server over the Nextcloud is.

Another Question,
at WireGuard I can just change "Allowed IPs" to only parse Traffic to VPN IPs to the VPN Server, no internet Connnections, how do i do this with the VPNs out of the Mobilconfigs?

**Comment by AnderCrafter** [comment]
and is it possible to configure Routes so i can type filesystem.vpn and it will redirect that to, well lets say my server (in the VPN) which shows me my personal files.

**Comment by TC1977** [comment]
If you check out the [Apple Configuration Reference](https://developer.apple.com/business/documentation/Configuration-Profile-Reference.pdf), you could try playing with the `SupplementalMatchDomains` array of strings to set up a split tunnel, which is what I think you're looking for. But it's "only available in macOS 10.12 and later."

You could also play with `/etc/strongswan.d/charon.conf` to set up a routing table. That's about as far as I can go.

**Comment by AnderCrafter** [comment]
Okay, i'll better not play with this kind of thing xD
Everything working, i configured the routes in /etc/hosts of the Computers and created Virtual Hosts so i must only type nextcloud.vpn and have al my files, wonderful, thanks for your help and the ongoing development on this tool.
