### ISSUE TITLE
GCE project was suspended because of a port scanning activity

### ISSUE THREAD

**Issue by MhdHejazi** [trailofbits/algo#1378]
I used Algo to create a personal VPN on a Google Compute Engine instance. It's great, and everything worked just fine until I got an email from Google saying this:

> Your Google Cloud Project VM vpn:us-east1-b has been performing intrusion attempts against a third-party and is violating our Terms of Service.
> We detected a port scanning on remote port 21 originating from your Compute Engine project (...), targeting more than 70 IP addresses between 03:58 and 03:59 (Pacific Time).

I just want to make sure what the reason for that could be.
1. Could Algo scripts do that under any circumstances? Or could it be that a website was doing that IP scanning?
2. Could we configure the VPN in a way to prevent such behaviour from happening again?

Thanks.

**Comment by davidemyers** [comment]
I can't think of any situation where an AlgoVPN would suddenly start to scan for vulnerabilities on its own. I think this traffic must have been on behalf of one of your VPN clients.

You might want to check your VPN clients for malware and find out if any of your users have been playing around with tools like Metasploit.

**Comment by MhdHejazi** [comment]
The thing is, at that time, only my iPhone was connected to this VPN. I can't think of a case where a non-jailbroken iPhone could have a hidden malware. So that leaves me with two possibilites:
1. Client: The active app on the phone (or a website if it's a browser app).
2. Server: Someone was able to break into the instance, or AlgoVPN.

I just wanted to understand what happened and prevent this from happening again.
If AlgoVPN may not do that, I would like to know if it can be configured in a way to block such traffic from the client.

**Comment by MhdHejazi** [comment]
After further investigation, I found out that a suspicious iOS app was responsible for the port scanning activity. I reported the app and will close this issue.

Thank you for the time and effort you put into maintaining AlgoVPN. It's really appreciated.
