### ISSUE TITLE
OnDemand settings in mobileconfig always connect to VPN on wired ethernet (laptop)

### ISSUE THREAD

**Issue by dbrwn** [trailofbits/algo#138]
I am unclear on how the mobileconfig is interpreted as there is an explicit action to Disconnect when on named wifi networks (home / work), and to Connect when on WiFi or Cellular network types.  The default must be to Connect?

Ideally my data while on home ethernet would not run through the VPN.

### OS / Environment
host is macOS Sierra // 10.12.1
vpn server is an ec2 instance

### Ansible version

```
ansible 2.2.0.0
  config file = 
  configured module search path = Default w/o overrides
```

### Version of components from `requirements.txt`

```
dopy 0.3.5
boto 2.43.0
azure 1.0.3
apache-libcloud 1.3.0
six 1.10.0
```

### Summary of the problem
With On Demand settings configured with multiple home network SSIDs and always enabled for Cellular, VPN is enabled when on wired ethernet.

### Steps to reproduce the behavior
1. Connect ethernet, disable wifi
2. VPN connection established

### Expected behavior
Ethernet would not use on demand connection to VPN.

### Actual behavior
Ethernet has on demand connection to VPN.

**Comment by dbrwn** [comment]
Incidentally, I am running off an ec2_updates branch about a month old.  I am happy to try to repro on the latest head if needed.

**Comment by defunctio** [comment]
I can't speak to the above  issue but the ec2_updates branch has been merged into master, you may want to switch to master anyways.

**Comment by gunph1ld** [comment]
@dbrwn Can you check this [branch](https://github.com/trailofbits/algo/tree/OnDemandEnabled_Ethernet)? 
there is no ethernet on my laptop

**Comment by dbrwn** [comment]
@gunph1ld this didn't work, although the mobileconfig looks reasonable:
```
/snip
              <key>OnDemandEnabled</key>
                <integer>1</integer>
              <key>OnDemandRules</key>
              <array>
                  <dict>
                      <key>Action</key>
                      <string>Disconnect</string>
                      <key>InterfaceTypeMatch</key>
                      <string>WiFi</string>
                      <key>SSIDMatch</key>
                      <array>
                          <string>SSID1</string>
                          <string>SSID2</string>
                          <string>SSID3</string>
                      </array>
                  </dict>
                  <dict>
                    <key>Action</key>
                      <string>Connect</string>
                      <key>InterfaceTypeMatch</key>
                      <string>WiFi</string>
                  </dict>
                  <dict>
                    <key>Action</key>
                      <string>Connect</string>
                      <key>InterfaceTypeMatch</key>
                      <string>Cellular</string>
                  </dict>
                  <dict>
                    <key>Action</key>
                      <string>Disconnect</string>
                    <key>InterfaceTypeMatch</key>
                      <string>Ethernet</string>
                  </dict>
                </array>
                <key>AuthenticationMethod</key>
                <string>Certificate</string>
/snip
```

After installing the profile, I disable Wifi, plug in my ethernet adapter (Thunderbolt 2 -> Ethernet).  Once the link comes up, the VPN connects and stays connected.
If I bring Wifi up, the VPN stays connected but once I unplug ethernet, the VPN connection is torn down (I am on my home Wifi).

**Comment by gunph1ld** [comment]
According to the apple docs, it should work. Can you collect some debug info?

**Comment by dbrwn** [comment]
I am happy to gather some debug info, but am not sure where to gather this from.  If there is something specific you are looking for, let me know.

From: https://developer.apple.com/library/content/featuredarticles/iPhoneConfigurationProfileRef/Introduction/Introduction.html#//apple_ref/doc/uid/TP40010206-CH1-SW36

> Whenever a network change is detected, the VPN On Demand service compares the newly connected network against the match network criteria specified in each dictionary **IN ORDER** to determine whether VPN On Demand should be allowed or not on the newly joined network. The matching criteria can include any of the following:
>
>DNS domain or DNS server settings (with wildcard matching)
>SSID
>Interface type
>reachable server detection

(caps mine)

So it may be that it's stopping when it matches the Connect / Wifi entry immediately after the Disconnect / Wifi / SSID's entry.  So maybe all the disconnects need to show up first? 

I tried a re-ordered version of the mobileconfig, and it seems to work, so the ordering must be important.  Below .mobileconfig snippet works while on Ethernet:
```
/snip
              <key>OnDemandEnabled</key>
                <integer>1</integer>
              <key>OnDemandRules</key>
              <array>
                  <dict>
                      <key>Action</key>
                      <string>Disconnect</string>
                      <key>InterfaceTypeMatch</key>
                      <string>WiFi</string>
                      <key>SSIDMatch</key>
                      <array>
                          <string>SSID1</string>
                          <string>SSID2</string>
                          <string>SSID3</string>
                      </array>
                  </dict>
                  <dict>
                    <key>Action</key>
                      <string>Disconnect</string>
                    <key>InterfaceTypeMatch</key>
                      <string>Ethernet</string>
                  </dict>
                  <dict>
                    <key>Action</key>
                      <string>Connect</string>
                      <key>InterfaceTypeMatch</key>
                      <string>WiFi</string>
                  </dict>
                  <dict>
                    <key>Action</key>
                      <string>Connect</string>
                      <key>InterfaceTypeMatch</key>
                      <string>Cellular</string>
                  </dict>
                </array>
/snip
```

**Comment by dbrwn** [comment]
@gunph1ld I am confused.  The profile generated by the latest commit on this branch seemed to work on my laptop with Ethernet & Wifi, but when installed on my phone it would not connect to VPN while on Cellular.  I tried a bit of file/rule manipulation without success.

**Comment by dguido** [comment]
I'll test this when I have access to a USB ethernet adapter.

**Comment by gunph1ld** [comment]
I confirm that the section with `Ethernet=Disconnect`, before `Cellular` or `WiFi` does not allow to use On Demand on iOS 10.2

**Comment by gunph1ld** [comment]
My OnDemand rules:
```
              <array>
                  <dict>
                      <key>Action</key>
                      <string>Disconnect</string>
                      <key>InterfaceTypeMatch</key>
                      <string>WiFi</string>
                      <key>SSIDMatch</key>
                      <array>
                          <string>meganet1</string>
                          <string>meganet_5G1</string>
                      </array>
                  </dict>
                  <dict>
                    <key>Action</key>
                      <string>Disconnect</string>
                    <key>InterfaceTypeMatch</key>
                      <string>Ethernet</string>
                  </dict>
                  <dict>
                    <key>Action</key>
                      <string>Connect</string>
                    <key>InterfaceTypeMatch</key>
                      <string>Cellular</string>
                  </dict>
                  <dict>
                    <key>Action</key>
                      <string>Connect</string>
                    <key>InterfaceTypeMatch</key>
                      <string>WiFi</string>
                  </dict>
                </array>
```

Debug from iPhone:
```
Feb  8 23:14:53 Jacks-iPhone nesessionmanager(NetworkExtension)[126] <Info>: NESMIKEv2VPNSession[Algo VPN ***** IKEv2:56194E16-AFF7-4044-AFDC-62FFA5AE939D]: handling configuration changed: {    name = <29-char-str>
identifier = 56194E16-AFF7-4044-AFDC-62FFA5AE939D
grade = 1
VPN = {
enabled = YES
onDemandEnabled = YES
onDemandRules = (
{
action = disconnect
interfaceTypeMatch = WiFi
SSIDMatch = (
<8-char-str>,
<11-char-str>,
)
},
{
action = disconnect
interfaceTypeMatch = any
},
{
action = connect
interfaceTypeMatch = cellular
},
{
action = connect
interfaceTypeMatch = WiFi
},
)
```

iOS makes `InterfaceTypeMatch Ethernet`  to `InterfaceTypeMatch any`

**Comment by gunph1ld** [comment]
@dbrwn So, here is only one way. You have to disconnect Wifi or add SSIDs to the exclude list in order to disconnect VPN when Ethernet is connected

**Comment by dguido** [comment]
Hey @dbrwn, I looked at this issue more closely with @gunph1ld and the only way to fully provide for your use case would be to create multiple mobileconfig files per user, one for macOS and one for iOS.

I think this is a less common use case, so rather than complicate the user interface, we are going to leave the functionality as is for now. In 1.1, I will write up instructions for creating your own mobileconfig with Configurator to customize how our generated mobileconfig operates.

As for your immediate problem, it looks like the information that @gunph1ld discovered should solve it and therefore I will close this ticket. Let me know if you can discover a way to make one universal mobileconfig for both macOS and iOS that works the way you want. Thanks!

**Comment by asmod3us** [comment]
Has anyone tried this with recent iOS builds and/or a URL probe for the wired connection rule? If you have a host that is only available in your home network, something like this might work:

```
...
                  <dict>
                      <key>Action</key>
                      <string>Disconnect</string>
                      <key>InterfaceTypeMatch</key>
                      <string>Ethernet</string>
                      <key>URLStringProbe</key>
                      <string>http://MYHOMEHOST/PATH</string>
                  </dict>
...
```
