### ISSUE TITLE
Is there a way to change the ports used?

### ISSUE THREAD

**Issue by bmy** [trailofbits/algo#1384]
I understand that the port used is about the VPN server configuration, and not specifically Algo...but I was hoping submit a pull request that would add a prompt during Algo setup that (if the user simply presses Enter) would default to the default ports for IPsec/WireGuard but (if the user inputs a custom port number, e.g. 443) could optionally configure the VPN services on a custom port. Without naming names, this would be for use in jurisdictions that employ widespread blocking of VPN protocols on other ports...

**Comment by davidemyers** [comment]
You can already change the WireGuard port in `config.cfg`.

The problem with changing the IPsec ports on the server side is that I don't think it's possible to set non-standard ports on some IPsec clients.

**Comment by TC1977** [comment]
It also isn't trivial to install a non-standard port on strongSwan. See https://wiki.strongswan.org/projects/strongswan/wiki/FAQ#Non-standard-IKE-ports
