### ISSUE TITLE
How to convert `max_mss` to `reduce_mtu`?

### ISSUE THREAD

**Issue by quinncomendant** [trailofbits/algo#1387]
Can we add a quick note to [troubleshooting.md](https://github.com/trailofbits/algo/blob/master/docs/troubleshooting.md) on how to convert from the old `max_mss` value to the new `reduce_mtu` value?

After a quick read of the troubleshooting.md page, it seems like I should subtract my ideal MTU from 1500: `1500 − max_mss = reduce_mtu`.

However, the [pull request](https://github.com/trailofbits/algo/pull/1253) for this feature mentions these calculations:

    WireGuard MTU = 1420 - reduce_mtu
    IPsec IPv4 MSS = 1400 - 40 - reduce_mtu
    IPsec IPv6 MSS = 1400 - 60 - reduce_mtu

Which contradicts the "1500 - MTU" suggested by troubleshooting.md.

I previously discovered `1280` is the best MTU value for my network. What should my `reduce_mtu` value be?

----

# Summary from comments below: how to convert a value from `max_mss` to `reduce_mtu`:

## If using IPsec:

`reduce_mtu` = `1400` - `max_mss`

(For IPsec, Algo uses MSS clamping in the server firewall rules for a reduced MTU.)

## If using WireGuard:

`reduce_mtu` = `1420` - `max_mss`

(For WireGuard, reduce_mtu causes the client MTU to be adjusted in WireGuard *.conf files, and leaves the server MTU at the default value.)

### If using both:

Set a `reduce_mtu` value that works for IPsec: `reduce_mtu` = `1400` - `max_mss`

Then manually configure the `MTU` value in the WireGuard *.conf files.

I'm using both IPsec and WireGuard, and I want a MTU of 1280, so I'm using a `reduce_mtu` value of   `120` and in the wireguard *.conf files I set `MTU=1280`.

**Comment by davidemyers** [comment]
There's no contradiction. The troubleshooting document specifies measuring your MTU *outside* of your VPN tunnel, so you're determining how much lower than 1500 your actual MTU is without worrying about VPN overhead. The PR, on the other hand, describes how the actual values are calculated in the code for each protocol *including* VPN overhead. 

The value of `reduce_mtu` should be set to how much less than 1500 your MTU is outside of any VPN, or put another way, `1500 - measured_mtu = reduce_mtu`. You shouldn't have to worry about calculating the MSS any more.

In terms of converting from the previous implementation `reduce_mtu = 1360 - max_mss`.

If your measured MTU is 1280, then `reduce_mtu = 1500 - 1280 = 220`.

**Comment by quinncomendant** [comment]
Hi David,

Previously, my `max_mss` value was `1280`. So, as per your instructions on converting from the previous implementation, I configured a new algo vpn with a `reduce_mtu` value of `80` (1360 - 1280 = 80).

Checking the MTU values of interfaces on the created server:

    # ifconfig | grep mtu
    eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
    lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
    wg0: flags=209<UP,POINTOPOINT,RUNNING,NOARP>  mtu 1420

So, the new MTU for the wg0 interface is `1420`. I understand that `MSS = MTU – 40 bytes`, so my new MSS is `1420 - 40 = 1380`, not `1280` as I want — a value 100 bytes greater than expected.

If my analysis above is correct, shouldn't the conversion calculation be: `reduce_mtu = 1460 - max_mss`?

----

Having said all that, I think what I really want is an *MTU* of 1280 (I may have been confusing MTU and MSS). So, should I use a `reduce_mtu` value of `220` (1500 - 1280 = 220)?

I'm often on slow, unreliable networks (currently working remote from Chiapas, MX), and want to prioritize reliability over efficiency of packet transmission. I also use a portable OpenWRT router that had lots of problems until I reduced Algo's `max_mss` value to 1280. I'd like to use the smallest MTU possible to ensure maximum compatibility with weird networks. [RFC 2460 states](https://tools.ietf.org/html/rfc2460#section-5), “IPv6 requires that every link in the internet have an MTU of 1280 octets or greater.”

**Comment by quinncomendant** [comment]
Ok, I just created a new algo server using a `reduce_mtu` value of `220` and this is the interface MTU values on the server:

    # ifconfig | grep mtu
    eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
    lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
    wg0: flags=209<UP,POINTOPOINT,RUNNING,NOARP>  mtu 1420

Notice it's the same MTU value as in my previous comment (of a server created with a `reduce_mtu` value of `80`). So `reduce_mtu` doesn't seem to have an affect?

**Comment by davidemyers** [comment]
For WireGuard, `reduce_mtu` causes the *client* MTU to be adjusted and leaves the *server* MTU at the default value. So check the WireGuard `*.conf` files that were generated to see the MTU that will be used on the clients. Note that you can experiment with the WireGuard client MTU without having to redeploy your Algo server.

While the typical default MTU of WireGuard is 1420, on iOS the WireGuard app will default to 1280 because, as you certainly know, there are a lot of strange networks out there. To have your WireGuard `*.conf` files generated with an MTU of 1280, set `reduce_mtu` to 140.

**Comment by quinncomendant** [comment]
Thanks, but I'm not concerned with WireGuard at the moment – I'm using IPsec + IKEv2 on MacOS. How do I set and confirm that the Algo server is using an MTU of 1280?

**Comment by davidemyers** [comment]
When you wrote:

> So, the new MTU for the wg0 interface is `1420`.

you led me to believe you were using WireGuard. You really should consider using WireGuard on macOS if you're running Mojave.

Whereas WireGuard can easily set the MTU in the client config file, IPsec cannot, so Algo has to resort to using MSS clamping in the server firewall rules in order to force the client to reduce the MTU (which is how the variable `max_mss` came to be in the first place, before WireGuard was added to Algo).

To reiterate, we're trying to change the behavior of the *client*, not set the MTU of the server. But with IPsec the server has to meddle with client TCP connections to make this happen.

Yes, this is all very confusing. :smiley:

So it sounds like you want to set the MTU of IPsec connections inside the tunnel to 1280. The default MTU for IPsec is 1400, so `reduce_mtu = 1400 - 1280 = 120`. This will generate firewall rules to limit MSS and put them in the firewall rules files found in `/etc/iptables`.

To test this, try visiting https://whoer.net, clicking on **Extended version**, scrolling down to the **OS** section, and seeing what it says for **TCP/IP**. I find that it usually figures out my MTU correctly.

**Comment by quinncomendant** [comment]
We haven't updated to Mojave yet, so stuck with IPsec. I'm using WireGuard on iOS. So this is a mixed environment: I'll want a MTU of 1280 for both IPsec and WireGuard. However, this doesn't seem possible based on what you wrote above:

**IPsec:** set `reduce_mtu = 120`

> The default MTU for IPsec is 1400, so reduce_mtu = 1400 - 1280 = 120

**WireGuard:** set `reduce_mtu = 140`

> To have your WireGuard *.conf files generated with an MTU of 1280, set reduce_mtu to 140

Since WireGuard is configured locally for clients, I guess I can use `reduce_mtu = 120` when generating the server, then manually modify the WireGuard `*.conf` files to have a MTU of 1280. Is that the best way to set the MTU the same for both IPsec and WireGuard?

With so much "magic" happening, `reduce_mtu` is not a very user-friendly interface, even for advanced users. Would it be hard to just allow the user to set their desired MTU value? 

Thanks for your help!

**Comment by davidemyers** [comment]
You're setting the MTU backwards from the way I think most people do. If you measure your actual MTU outside of any VPN, then set `reduce_mtu` based on how much less than 1500 you have, everything else is set optimally.

WireGuard and IPsec have different overheads, so if you set them both to 1280 *inside* their tunnels, you're actually using different MTUs for each type of traffic *outside* of the tunnels over the Internet. I think that's probably not what most people want.

As for WireGuard on iOS, as mentioned above the default MTU is 1280, so just delete the MTU setting from inside the app to get what you want.

**Comment by quinncomendant** [comment]
Cool, understood.

I can confirm using `reduce_mtu = 120` sets the MSS clamping correctly:

    # iptables -S -v -t mangle | grep mss
    […] --set-mss 1240

Thanks!

BTW, do you know if it's possible to hard-code all the answers to the questions when running `./algo` (i.e., non-interactive mode)? I always use the same options when generating a new VPN, and would prefer to run the command without interaction.

**Comment by davidemyers** [comment]
See [here](https://github.com/trailofbits/algo/blob/master/docs/deploy-from-ansible.md) for how to deploy non-interactively.

I'm not sure if it's documented, but many of the API keys can also be set as environment variables, which will bypass the prompts. These work:

```
export DO_API_TOKEN="xxxxxxxxxxxxxxxxxxxxxxxxxx"
export AWS_ACCESS_KEY_ID="yyyyyyyyyyyyyyyyyyyyy"
export AWS_SECRET_ACCESS_KEY="zzzzzzzzzzzzzzzzzzzzzz"
export GCE_CREDENTIALS_FILE_PATH="/path/to/gce.json"
export VULTR_API_CONFIG="/path/to/vultr.ini"
````
