### ISSUE TITLE
Support for EC2 spot instance as cloud host

### ISSUE THREAD

**Issue by glennschler** [trailofbits/algo#1399]
**Is your feature request related to a problem? Please describe.**
In 2018 EC2 implemented a new pricing model for Spot instances, along with simplified options for launching. Spot instances have extended lifetimes without the frequent terminations which occurred in the old pricing model. The same api endpoint which is used in the current algo cloud formation template is possible.
* As described in AWS blog post [Simplified purchasing without bidding and fewer interruptions](https://aws.amazon.com/blogs/compute/new-amazon-ec2-spot-pricing/)
* Cost is lowered to $2.25 USD per month when using a t3.micro instance type. My testing has proved continuous instance lifetime during the past month

**Describe the solution you'd like**
Use a new config.cfg variable to request a `spot` or the default `on-demand` instance

**Describe alternatives you've considered**
EC2 Lightsail is a cheap option, though still higher cost than spot instances and without the complete EC2 feature set

**Additional context**
I am currently testing [commited changes](https://github.com/glennschler/algo/tree/ec2-spot) to support this feature request

**Comment by TC1977** [comment]
...but Amazon can still interrupt the instance, and therefore your VPN service, with a 2-minute notification. Is that worth saving the money?

I was considering getting a t2.nano Reserved Instance myself. Standard 3-year term for $57 breaks down to $1.58 a month.

**Comment by glennschler** [comment]
But amazon does not interrupt if you do not set a max price or, I believe, once it reaches the on-demand price. Look at the historical price statistics from the past year to see this rarely occurs. The old model was based on price bidding with high and low limits, which caused frequent termination.

Really I do not need or want a full time VPN. I kick off a new Algo VPN as needed for a day or week when I am in leaving for a public environment. For $0.0031 per hour vs $0.013. Algo is implementing a full AWS Cloud Formation automated script to quickly launch a secure, disposable and remote Ubuntu server.
