### ISSUE TITLE
Add lightweight ad-blocking to the proxy

### ISSUE THREAD

**Issue by dguido** [trailofbits/algo#14]
Nothing too crazy, let's try to block some of the worst types of advertising with a configuration for the proxy. It should auto-update on a regular basis with a cron job.

**Comment by gunph1ld** [comment]
Also we can provide a PAC script, how do you think?

**Comment by dguido** [comment]
Sure, that would be helpful.

**Comment by gunph1ld** [comment]
Also, I would like to suggest to use the DNS based ad blocking system, because It will work with https and clients don't need to configure proxy settings in their browsers

**Comment by dguido** [comment]
Can you create the playbook for dns-based ad blocking, then make it optional to install it? Allow the user to select yes or no during setup.
