### ISSUE TITLE
Move Scaleway to the native ansible modules

### ISSUE THREAD

**Issue by jackivanov** [trailofbits/algo#1401]
https://docs.ansible.com/ansible/latest/modules/list_of_cloud_modules.html#scaleway

**Comment by remyleone** [comment]
How could we add testing to the Scaleway roles? Is there a way to launch algo in non interactive mode with a set of default to see if it can instantiate correctly a machine?

**Comment by jackivanov** [comment]
No, unless someone provide valid credentials to spin up a machine

**Comment by remyleone** [comment]
We could do that internally at Scaleway. If there is a CI/CD script that could be used to run it without human interaction I could run it.

**Comment by jackivanov** [comment]
We use Travis-ci for the tests - see [.travis.yml](https://github.com/trailofbits/algo/blob/master/.travis.yml)
