### ISSUE TITLE
./algo not working

### ISSUE THREAD

**Issue by DeadWolfQc** [trailofbits/algo#1402]
1. follows steps until step 6
2. follow step 6

when i do "./algo" i get the error: ERROR! an error occurred while trying to read the file '/home/clear/algo/config.cfg': [Errno 13] Permission denied: '/home/clear/algo/config.cfg'

all i did is change the users list and added an advanced user

and sorry i don't know where the full log is, pretty sure there is no log files as the "./algo" didn't even work in the first place

the output i get is as i stated the error above

i'm running the Ubuntu from the windows store, Ubuntu version 18.04

**Comment by davidemyers** [comment]
I don't know Windows or how the WSL is implemented, but it looks like maybe whatever you edited `config.cfg` with changed the file permissions. Could you post the output to the command:
```
ls -l algo config.cfg
```
Also I recall there being problems with installing Algo under `/mnt` when using WSL, but from the output you provided it looks like you haven't done that.

**Comment by DeadWolfQc** [comment]
when i enter your command it tells me :
-rwxrwxrwx 1 clear clear  485 Apr 22 14:48 algo
---------- 1 clear clear 6276 Apr 22 15:00 config.cfg

**Comment by davidemyers** [comment]
The permissions on `config.cfg` are wrong. Try the following and run `./algo` again:
```
chmod 664 config.cfg
```
It would probably have been safer to use a Linux editor, but the editors you can run in a terminal window are somewhat unfriendly. Try the editor `nano` in the future, e.g., `nano config.cfg`.

**Comment by DeadWolfQc** [comment]
thanks! it works now! although i don't understand really well how the nano editor works, i know how to edit the txt but when im done i don't know how to save or exit the editor

**Comment by TC1977** [comment]
https://wiki.gentoo.org/wiki/Nano/Basics_Guide 

Just remember, the Exit shortcut (control-X) is always listed at the bottom of the screen.
