### ISSUE TITLE
iptable rules

### ISSUE THREAD

**Issue by AnderCrafter** [trailofbits/algo#1408]
Hello, i accidentally flushed the iptables rules for Algo, which rules should i add?

The ones in the Docs do not solve the problem.

**Comment by davidemyers** [comment]
If you haven't deleted the file `/etc/iptables/rules.v4` either reboot or try running:
```
sudo systemctl restart netfilter-persistent
```

**Comment by AnderCrafter** [comment]
Unfortunetly i have, could someone send me theirs?

**Comment by davidemyers** [comment]
[rules.v4](https://pastebin.com/65v6siUK)
[rules.v6](https://pastebin.com/r3S9ZRWN)

**Comment by AnderCrafter** [comment]
Thank you!
