### ISSUE TITLE
update-users doesn't work

### ISSUE THREAD

**Issue by z01999** [trailofbits/algo#14108]
I selected yes for "Do you want to retain the keys (PKI)?" in the prompt during the deployment
and have done steps in the link below :
https://github.com/trailofbits/algo#adding-or-removing-users
but i get this error:
```

(.env) [user@algo2 algo]$ ./algo update-users
[WARNING]: Could not match supplied host pattern, ignoring: vpn-host
[WARNING]: Found variable using reserved name: no_log

PLAY [localhost] ********************************************************************************************************************************************************

TASK [Get list of installed config files] *******************************************************************************************************************************
ok: [localhost]

TASK [Verify servers] ***************************************************************************************************************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [Build list of installed servers] **********************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "Unexpected templating type error occurred on ([{% for i in _configs_list.files %}\n  {% set config  = lookup('file', i.path)|from_yaml %}\n  '{{ config.server }}'\n  {{ ',' if not loop.last else '' }}\n{% endfor %}]): a string or stream input is required"}

PLAY RECAP **************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

(.env) [user@algo2 algo]$ 



```

**Comment by davidemyers** [comment]
Is the system above where you're running `./algo update-users` the VPN server or is the VPN server a remote system?

Please post the output of:
```
grep server: configs/*/.config.yml
```

**Comment by z01999** [comment]
> Is the system above where you're running ./algo update-users the VPN server or is the VPN server a remote system?

I executed this command on local system (fedora 32) and this command must ssh to remote system but it doesn't

> Please post the output of:
> 
> `grep server: configs/*/.config.yml`

```
[user@algo2 algo]$ grep server: configs/*/.config.yml
server: 194.5.207.239
```

**Comment by davidemyers** [comment]
That output looks normal. I'm able to remotely deploy and add users from Fedora 32 so I'm not sure what's going on.

**Comment by z01999** [comment]
This problem didn't resolve after installing multiple times

**Comment by davidemyers** [comment]
Could you post your entire `configs/*/.config.yml` file?

**Comment by z01999** [comment]
I changed my fedora 32  workstation to debian and problem solved
Thank your for this project

**Comment by iamsid** [comment]
> Could you post your entire `configs/*/.config.yml` file?

I am facing a similar issue. My configs folder is empty.
I think I deleted its contents. Not sure.

The VPN itself is working fine. Was trying to add a new user and got below error:
```
[WARNING]: Could not match supplied host pattern, ignoring: vpn-host
[WARNING]: Found variable using reserved name: no_log

PLAY [localhost] ************************************************************************************************************************************************************************************************

TASK [Get list of installed config files] ***********************************************************************************************************************************************************************
ok: [localhost]

TASK [Verify servers] *******************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {
    "assertion": "_configs_list.matched > 0",
    "changed": false,
    "evaluated_to": false,
    "msg": "No servers found, nothing to update."
}

PLAY RECAP ******************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

**Comment by davidemyers** [comment]
@iamsid `update-users` will not work without the configuration files that were stored under `configs` when the VPN server was initially deployed.

**Comment by iamsid** [comment]
So what are my options here?
I configured this a year ago I think, and would like to avoid a complete re-install. 😓

**Comment by davidemyers** [comment]
If you're using WireGuard you might be able to add users manually by editing `/etc/wireguard/wg0.conf`. Use an existing client config file as an example for creating new ones. Refer to the manual page for `wg` and use the `genkey`, `genpsk`, and `pubkey` commands to create new keys.

If you're using IPsec you might be able to have multiple users connect using the same client config file.

**Comment by iamsid** [comment]
Thank you @davidemyers for your help.
I found a copy of the configs folder on my local machine. Placing that on the server worked.
Will remember to not play around the configs folder in future.
