### ISSUE TITLE
Unable To Connect To Server From Iran With Internet Censorship

### ISSUE THREAD

**Issue by fidividi32** [trailofbits/algo#14106]
Hello,

My wireguard with algo deployment seems to work from other countries I tried, but when I try to connect from Iran (a country with terrible state-powered internet censorship) the connect gets activated on wireguard, but no websites can be reached and nothing loads.

Has this to do with deep packet inspection and is there a way to get around this problem as I thought the whole idea is to get over packet inspections as such via a secure tunnel?

I don't have any control from the client side and using the Wireguard client application (unless a config value), so any ideas are welcome..

**Comment by davidemyers** [comment]
On WireGuard's [Known Limitations](https://www.wireguard.com/known-limitations/) page it's mentioned that WireGuard doesn't do anything to avoid Deep Packet Inspection.
