### ISSUE TITLE
WireGuard does not work on Android

### ISSUE THREAD

**Issue by mkf-simpson** [trailofbits/algo#14113]
**Describe the bug**

WireGuard on Android 10 connected to the newly created server (installed with no additional settings), but there is no connection to any website. But when I'm trying to connect on my mac using `configs/<ip>/ipsec/apple/user.mobileconfig`, everything is fine.

**To Reproduce**

1. Install Algo from master on DigitalOcean Frankfurt with default settings
2. Connect using a QR code and the latest WireGuard app on Android 10
3. Try to get anything from the internet

**Expected behavior**

Everything works even on Android.

**Additional context**

No additional context, I guess.

**Full log**

[Link to the full log of the ./algo script](https://gist.github.com/mkf-simpson/0d40e2016bb468d007c96c4a64f31fc4)

**Comment by davidemyers** [comment]
Does WireGuard work from your Mac?

**Comment by mkf-simpson** [comment]
Sorry for the late response.

Yes, it works on MacOS.

**Comment by davidemyers** [comment]
If both IPsec and WireGuard are working from macOS then it sounds like the AlgoVPN server is working properly.

I assume you've tried your Android on both the mobile data network and the same Wi-Fi network used by your Mac?
