### ISSUE TITLE
steps to erase the logs on the server and start again?

### ISSUE THREAD

**Issue by ravio** [trailofbits/algo#14112]
hi all,

is there an easier way to destroy the logs on the digital ocean droplet and recreate the VM? I don't have any experience in managing cloud VM and this is my first time doing anything in the server space.

P.S: I am not doing any illegal activities, just would like to know the art of possible.

**Comment by davidemyers** [comment]
Algo doesn't log anything interesting if your clients use WireGuard. With IPsec the IP addresses of clients will be logged.

I suggest you treat an AlgoVPN as disposable. If you wish to start over, destroy the Droplet and re-run Algo to deploy a new one.
