### ISSUE TITLE
Digital Ocean: best way to save on money when not using the VPN?

### ISSUE THREAD

**Issue by ravio** [trailofbits/algo#14111]
hey guys, i am not using the VPN all the time but the meter is always running for the digital ocean droplet. this is my first time dealing with server provisioning (cloud or anywhere) and I don't know what's the best solution.

online, one recommendation was to assign static ip, poweroff the droplet, take a snapshot, destroy the droplet and then possibly recreate it when needed. sounds too much of a hassle.

the console of the droplet asks for username and password and i am not sure which credentials to use.

is there an easy way?

**Comment by davidemyers** [comment]
The only way providers will stop charging you is if you delete the instance.

Algo does not arrange for you to be able to log in on the console (though it may be possible on certain providers such as Vultr). Instead use the SSH command that is displayed once Algo has completed.
