### ISSUE TITLE
Dynamic Variables for Users

### ISSUE THREAD

**Issue by brandinarsenault** [trailofbits/algo#14120]
**Is your feature request related to a problem? Please describe.**
Currently I am unaware of any dynamic variables we can use in the `config.cfg` which means each time I generate `desktop`, I have to rename it or remove the old profile in Wireguard or I have duplicate profiles. 

**Describe the solution you'd like**
I'd like to be able to use Dynamic Variables in the usernames in the `config.cfg` such as `{date}` or `{time}`, even `{provider}` `{region}`. I'm using algo to generate a new VPN daily for security, and this would help in WireGuard for differentiating between the different ones that were generated.

**Describe alternatives you've considered**
Manually changing the names before importing to WireGuard.

**Comment by jackivanov** [comment]
You can use whatever ansible supports - https://docs.ansible.com/ansible/latest/user_guide/playbooks_vars_facts.html
eg: `"test-{{ ansible_date_time.date }}"`

**Comment by davidemyers** [comment]
>`"test-{{ ansible_date_time.date }}"`

Wouldn't that cause all existing users to be deleted during `update-users`?

**Comment by jackivanov** [comment]
@davidemyers Oh, yes, this is correct. At the moment I don't see a way hot it can be implemented. We'll need to wait until wg-dynamic is generally available
