### ISSUE TITLE
Help with ALGO/DNS and split-horizon

### ISSUE THREAD

**Issue by drakes00** [trailofbits/algo#14143]
Hi,

Probably not really a bug report or a feature request but more an SOS call from my side, hopefully you can help.
I use an ALGO VPN server for a long time with default configuration.

I'd need to setup a personal DNS server to perform **split horizon** for specific personnal URL (returning LAN IP when I'm inside my LAN and public IP when I'm outside).

Could you give me your opinion on the best way to implement this alongside ALGO?

### Current Understanding of ALGO

Correct me if I'm wrong:

- DNS queries from my laptop are tunneled through Wireguard
- They are sent through DNScrypt to public DNS server such as Cloudflare
- How is routing done on VPN server to forward DNS queries to DNScrypt proxy (I didn't found it in iptables)?

### My idea for split horizon with ALGO

- Possibility 1: doable directly with DNScrypt ?
- Possibility 2: add an unbound DNS server alongside ALGO. I'd expect that unbound should listen to port 53 and forward to  DNScrypt who would listen on another port? Also, I'd expect unbound would just either answer with my LAN IP if needed or forward everything to DNScryp and not do any DNS queries by itself.

Hopefully this is not to confusing and you find time to help me understand better.
(I'm willing to help with PR later if any interesting feature above)

Kind regards,
Maxime

**Comment by davidemyers** [comment]
The way split DNS typically works is that when a client is on your local network your local DHCP server returns your local DNS server which contains records which override what's in your public DNS server.

With WireGuard DHCP is not used and the DNS server is specified in the tunnel configuration on the client, so the DNS server used is always the same regardless of which network the client is connected to.

For Algo the DNS server is an instance of `dnscrypt-proxy` running on the AlgoVPN server which receives queries forwarded over the WireGuard tunnel. These queries always come from the client's WireGuard interface address no matter which network the client is connected to, so I don't think there's any way for a process running on the AlgoVPN to make a decision about how to route DNS queries based on the network currently in use by the client.

The easiest solution to implement would be to create a duplicate WireGuard tunnel that specifies your local DNS server and manually switch tunnels when you switch networks.

**Comment by drakes00** [comment]
Hi David,
Thanks for your answer.

I see what you mean but I wouldn't expect it to be a problem in my case.
I'm experiencing an unreliable loopback on my ISP's box and if I have a DNS pointing to my LAN that I access from inside my LAN, then DNS queries correctly answer my public IP but accessing my public IP from inside the LAN seem impossible.

Thus, there are 3 possible cases:

1. No VPN inside LAN: source address for DNS queries is my public IP --> DNS answers with LAN IP so I bypass my ISP's box
2. No VPN outside LAN: source address for DNS queries is any other IP --> DNS answers with my public IP which will work correctly from outside LAN requests
3. VPN inside or outside LAN: source address is indeed VPN's client address and it is not possible to find out which network is used. However, HTTP connections appear as from outside for my ISP's box and I checked that the loopback problem does not occur so no problem.

I guess I could also always run my VPN from inside LAN to make it look that I'm outside but it seems a bit cumbersome performance wise.
My main usecase for this issue is more for when I'm not running behind the VPN and I hit the DNS server directly (and I ask here to make sure my modifications do not impact Algo that runs alongside).

**Comment by davidemyers** [comment]
It doesn't sound like your issue has anything to do with Algo if it only occurs when you're not using the VPN. I suggest you don't modify your AlgoVPN server at all.

See if your router has a setting for [NAT Reflection](https://en.wikipedia.org/wiki/Network_address_translation#NAT_hairpinning).

**Comment by drakes00** [comment]
Ok last quick question and I can close then. Is it ok to change DNScrypt in
Algo template to say 40 (also changing in client conf template) and have
another DNS server on 53 ? I'd expect them to run smoothly alongside.

Thank

Le mer. 3 févr. 2021 à 19:52, David Myers <notifications@github.com> a
écrit :

**Comment by davidemyers** [comment]
I don't know.

**Comment by drakes00** [comment]
I'll check NAT reflection, thanks for your time. :)
