### ISSUE TITLE
Users not revoked

### ISSUE THREAD

**Issue by restray** [trailofbits/algo#14164]
**update-users do not delete old users**

When I run the `./algo update-users` to add/revoke new/old users, it doesn't actually do it...

**To Reproduce**

1. Install algo on an Digiteal Ocean Server
2. Update the config.yml
3. run ./algo update-users
4. Remove users in config.yml
5. Re-run ./algo update-users
6. Try to connect with an old user, it should work (as I do)

**Expected behavior**

I can't find an "easy" way to delete an old user with the algo script...

The logs didn't output any errors or anything...

**Comment by davidemyers** [comment]
Are you using WireGuard or IPsec?

**Comment by restray** [comment]
Wireguard

**Comment by davidemyers** [comment]
Did you create the Droplet first and choose "12. Install to existing..." or did you install Algo elsewhere and choose "1. DigitalOcean" to let Algo create the Droplet?

**Comment by restray** [comment]
I did the option: `choose "1. DigitalOcean" to let Algo create the Droplet"`
Thanks!

**Comment by davidemyers** [comment]
I'm unable to reproduce the problem. I deployed with option 1, added a user, then was able to delete the user.

On the server, after deleting a user, do you still see an entry for the user in `/etc/wireguard/wg0.conf`?

**Comment by restray** [comment]
The user is not in the conf file, but why can I connect with it?
Okay, after experimenting some things, I can connect with the user but can't access to Internet... Okay!

Thanks for helping me and have a great day.
