### ISSUE TITLE
Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)

### ISSUE THREAD

**Issue by Alif112** [trailofbits/algo#14171]
I am trying to deploy server on my pc locally . After input of my public ip address its showing like this ....
I am using linux mint MATE, 20.0 .
**Full log**

```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to update apt cache: 
E:Failed to fetch http://packages.linuxmint.com/dists/ulyana/InRelease  
Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?), 
E:The repository 'http://packages.linuxmint.com ulyana InRelease' is no longer signed."}
```

**Comment by davidemyers** [comment]
```12. Install to existing Ubuntu 18.04 or 20.04 server (for more advanced users)```

You can only turn a system running Ubuntu Server 18.04 or 20.04 into an AlgoVPN.

**Comment by Alif112** [comment]
thanks . Now i am trying with ubuntu 18.04 .
