### ISSUE TITLE
Lightsail server capacity selection

### ISSUE THREAD

**Issue by f98pno** [trailofbits/algo#14186]
When installing on Lightsail, the script currently per default selects the cheapest option. Which in many cases is a good thing! However, just looking at the value for money, the 5usd/month price plan is offering a lot more value/money.

Would it be possible to update the script so users of Lightsail could choose between at least these two cheapest pricing plans? Once the instance is set up, upgrading to a higher tier looks quite painful.

**Comment by davidemyers** [comment]
You can change the instance size by editing the `cloud_providers` section in `config.cfg`. If you have the [AWS command line tool](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) installed you can view the options by running:
```
aws lightsail get-bundles
```
The one you want is `micro_2_0`.

**Comment by f98pno** [comment]
Oh, that is great, I missed that setting! Many thanks for your quick response!!
