### ISSUE TITLE
Region ap-south-1 not supported

### ISSUE THREAD

**Issue by aneeshjoy** [trailofbits/algo#14180]
Hi, I am trying to setup AlgoVPN on AWS EC2 ap-south-1 region. I get this error.
Can you please add  ap-south-1a & ap-south-1b to the regions list?

Error from cloudformation logs:

EC2Instance | CREATE_FAILED
-- | --
"Your requested instance type (t2.micro) is not supported in your requested Availability Zone (ap-south-1c). Please retry your request by not specifying an Availability Zone or choosing ap-south-1a, ap-south-1b. (Service: AmazonEC2; Status Code: 400; Error Code: Unsupported; "

**Comment by RMartires** [comment]
did u try adding the az from the error msgs?

**Comment by jackivanov** [comment]
You can switch to another instance type in the config file
