### ISSUE TITLE
Ubuntu server, all websites dead

### ISSUE THREAD

**Issue by DestruktorGitHub** [trailofbits/algo#14194]
After installing algo, that even don't work on my VPS, all sites that I had went offline and cloudflare is only showing up Error 522. I tried everything but nothing worked so I'm writing here.

**Comment by jackivanov** [comment]
This is expected. Local installation is for advanced users, switch to a cloud option.

https://github.com/trailofbits/algo/blob/master/docs/deploy-to-ubuntu.md#road-warrior-setup

> PLEASE NOTE: Algo is intended for use to create a dedicated VPN server. No uninstallation option is provided. If you install Algo on an existing server any existing services might break. In particular, the firewall rules will be overwritten. See AlgoVPN and Firewalls for more information.
