### ISSUE TITLE
Deployment fails 

### ISSUE THREAD

**Issue by neelg1193** [trailofbits/algo#14204]
**Describe the bug**

Deployment from WSL fails during "TASK [Ensure Ansible is not being run in a world writable directory]" due to "template error while templating string: expected token 'end of statement block', got 'integer'." I am baffled to not see this error anywhere else

**To Reproduce**
 
1. Follow [WSL instructions](https://github.com/trailofbits/algo/blob/master/docs/deploy-from-windows.md)
2. Follow Step 4 from [Deploy the Algo Server](https://github.com/trailofbits/algo#deploy-the-algo-server)
3. Attempt `./algo`
4. Observe error

Alternately:
1. Open Google Cloud Shell
2. Follow [deployment instructions](https://github.com/trailofbits/algo#deploy-the-algo-server) (Steps 2 & 4) 
3. Follow [GCP Setup](https://github.com/trailofbits/algo/blob/master/docs/cloud-gce.md), entering commands into google cloud shell.
4. Observe identical error after `./algo -e "provider=gce" -e "gce_credentials_file=$(pwd)/configs/gce.json"`

**Expected behavior**

TASK [Ensure Ansible is not being run in a world writable directory] passes because the directory has correct permissions. Deployment continues.

**Additional context**

This happens in google cloud shell in addition to WSL, so I don't believe it is related to #1637 despite failing at a similar point.

Output of `pip list` in both:
<table>
<thead>
  <tr>
    <th>WSL</th>
    <th>GCShell</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td>
<pre>
Package             Version
------------------- --------
ansible             2.9.7
appdirs             1.4.4
cffi                1.14.5
cryptography        3.4.7
distlib             0.3.1
filelock            3.0.12
importlib-metadata  4.0.1
importlib-resources 5.1.2
Jinja2              3.0.0
MarkupSafe          2.0.0
netaddr             0.8.0
pip                 21.1.1
pkg-resources       0.0.0
pycparser           2.20
PyYAML              5.4.1
setuptools          56.2.0
six                 1.16.0
typing-extensions   3.10.0.0
virtualenv          20.4.6
wheel               0.36.2
zipp                3.4.1
</pre>
</td>
    <td>
<pre>
Package            Version
------------------ --------
ansible            2.9.7
appdirs            1.4.4
cffi               1.14.5
cryptography       3.4.7
distlib            0.3.1
filelock           3.0.12
importlib-metadata 4.0.1
Jinja2             3.0.0
MarkupSafe         2.0.0
netaddr            0.8.0
pip                21.1.1
pycparser          2.20
PyYAML             5.4.1
setuptools         56.0.0
six                1.16.0
typing-extensions  3.10.0.0
virtualenv         20.4.6
wheel              0.36.2
zipp               3.4.1
</pre>
</td>
  </tr>
</tbody>
</table>

Output of `ansible --version` in WSL:
<pre>
ansible 2.9.7
  config file = /home/user/algo/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/algo/.env/lib/python3.6/site-packages/ansible
  executable location = /home/user/algo/.env/bin/ansible
  python version = 3.6.9 (default, Jul 17 2020, 12:50:27) [GCC 8.4.0]
</pre>

Output of `ansible --version` in GCShell:
<pre>
ansible 2.9.7
  config file = /home/user/algo/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/algo/.env/lib/python3.7/site-packages/ansible
  executable location = /home/user/algo/.env/bin/ansible
  python version = 3.7.3 (default, Jan 22 2021, 20:04:44) [GCC 8.3.0]
</pre>

**Full log**

WSL output:
```
$ ./algo
[WARNING]: Could not match supplied host pattern, ignoring: vpn-host

PLAY [localhost] *****************************************************************************

TASK [Gathering Facts] ***********************************************************************
ok: [localhost]

TASK [Playbook dir stat] *********************************************************************
ok: [localhost]

TASK [Ensure Ansible is not being run in a world writable directory] *************************
fatal: [localhost]: FAILED! => {"msg": "The conditional check '_playbook_dir.stat.mode|int <= 0775' failed. The error was: template error while templating string: expected token 'end of statement block', got 'integer'. String: {% if _playbook_dir.stat.mode|int <= 0775 %} True {% else %} False {% endif %}"}

PLAY RECAP ***********************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```
GCShell output:
```
$ ./algo -e "provider=gce" -e "gce_credentials_file=$(pwd)/configs/gce.json"
[WARNING]: Could not match supplied host pattern, ignoring: vpn-host

PLAY [localhost] *************************************************************************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************************************************************
ok: [localhost]

TASK [Playbook dir stat] *****************************************************************************************************************************************************************************
ok: [localhost]

TASK [Ensure Ansible is not being run in a world writable directory] *********************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "The conditional check '_playbook_dir.stat.mode|int <= 0775' failed. The error was: template error while templating string: expected token 'end of statement block', got 'integer'. String: {% if _playbook_dir.stat.mode|int <= 0775 %} True {% else %} False {% endif %}"}

PLAY RECAP *******************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

**Comment by cjdupreez** [comment]
Seeing the same issue on my end.

**Comment by jarrettprosser** [comment]
I'm seeing the same issue today. I deployed another host with an identical config a couple of days ago and it succeeded. I think the release of [jinja2 3.0.0](https://github.com/pallets/jinja/releases/tag/3.0.0) has caused a problem with this step. See the differences in dependencies:

<table>
<thead>
  <tr>
    <th>Algo deployed 09/05/2021</th>
    <th>Algo deployed 12/05/2021</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td><pre>Package       Version<br>------------- -------<br>ansible       2.9.7<br>appdirs       1.4.4<br>cffi          1.14.5<br>cryptography  3.4.7<br>distlib       0.3.1<br>filelock      3.0.12<br>Jinja2        2.8<br>MarkupSafe    1.1.1<br>netaddr       0.8.0<br>pip           21.1.1<br>pkg-resources 0.0.0<br>pycparser     2.20<br>pyOpenSSL     20.0.1<br>PyYAML        5.4.1<br>segno         1.3.3<br>setuptools    44.0.0<br>six           1.16.0<br>virtualenv    20.4.6<br>wheel         0.34.2</pre></td>
    <td><pre>Package       Version<br>------------- -------<br>ansible       2.9.7<br>appdirs       1.4.4<br>cffi          1.14.5<br>cryptography  3.4.7<br>distlib       0.3.1<br>filelock      3.0.12<br>Jinja2        3.0.0<br>MarkupSafe    2.0.0<br>netaddr       0.8.0<br>pip           21.1.1<br>pkg-resources 0.0.0<br>pycparser     2.20<br>PyYAML        5.4.1<br>setuptools    44.0.0<br>six           1.16.0<br>virtualenv    20.4.6<br>wheel         0.34.2</pre></td>
  </tr>
</tbody>
</table>

To confirm, I tried adding `jinja2==2.8` to `requirements.txt` at the start, and the task succeeds.  
```
TASK [Ensure Ansible is not being run in a world writable directory] *****************************************************************************************************************************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}
```

**Comment by mnihal22** [comment]
Tried this.

It worked once but when i tried again it failed with the same error as the issue

**Comment by davidemyers** [comment]
Another thing to try is to just delete the directory permissions check from [main.yml](https://github.com/trailofbits/algo/blob/70f9f911124c8c942b42eac945fcada6e16767ef/main.yml#L10).

**Comment by mnihal22** [comment]
I tried it after restarting the ssh session. The deployment proceeds without error

**Comment by requilium** [comment]
I can reproduce this on my machine.

```
Algo running on: macOS 11.3.1
Created from git clone. Last commit: 70f9f91 Fix typo (#14145)
Python 3.9.5
```

```
ll
drwxr-xr-x  38 richard  staff   1.2K 14 May 12:37 algo
```

```
~/Sources/algo(master*) » ./algo                                                                                             richard@Timber
[WARNING]: Could not match supplied host pattern, ignoring: vpn-host

PLAY [localhost] ***************************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************
ok: [localhost]

TASK [Playbook dir stat] *******************************************************************************************************************
ok: [localhost]

TASK [Ensure Ansible is not being run in a world writable directory] ***********************************************************************
fatal: [localhost]: FAILED! => {"msg": "The conditional check '_playbook_dir.stat.mode|int <= 0775' failed. The error was: template error while templating string: expected token 'end of statement block', got 'integer'. String: {% if _playbook_dir.stat.mode|int <= 0775 %} True {% else %} False {% endif %}"}

PLAY RECAP *********************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```

**Comment by kadektop2** [comment]
> Another thing to try is to just delete the directory permissions check from [main.yml](https://github.com/trailofbits/algo/blob/70f9f911124c8c942b42eac945fcada6e16767ef/main.yml#L10).

Yup this works for me, though I just commented out line 10-15.

**Comment by caewok** [comment]
Same problem; like others, commenting out lines 10–15 in main.yml works.

**Comment by ferasawadi** [comment]
thanks that solves the issue

**Comment by jruaaa** [comment]
didn't comment the check out but added jinja2==2.8 to requirements.txt at the start which worked for me it seems
