### ISSUE TITLE
Algo deployed in a Proxmox VM allows access to other CTs and VMs

### ISSUE THREAD

**Issue by gmcinalli** [trailofbits/algo#14208]
**Describe the bug**

Hi, I've installed Algo in a VM on Proxmox with Ubuntu Server 20.04.

I set `BetweenClients_DROP` to `true` but I can still reach the devices in the local network (in my case other VMs and CTs on the same Proxmox host).

Is this normal?

I don't know if it may be due to the fact that I'm in a VM inside Proxmox, something related to Proxmox networking, I don't know, or to my IP address class: `10.1.1.0/24`.

**To Reproduce**

Simply deploy AlgoVPN on a Proxmox VM and try to access other containers / VMs.

**Expected behavior**

I must not be able to reach other local network devices (CTs and VMs) and other clients connected via VPN.

**Comment by jackivanov** [comment]
This is expected behavior. Algo server just forwards all traffic out to the interface. You need to filter such kind of think on your proxmox installation

**Comment by gmcinalli** [comment]
Thanks @jackivanov, so just for clarification, the `BetweenClients_DROP` serves only to prevent communication between connected clients, it does not block anything else.

I solved by blocking everything through the firewall on Proxmox, sorry for the trouble.
