### ISSUE TITLE
Development issue

### ISSUE THREAD

**Issue by mnihal22** [trailofbits/algo#14205]
I am trying to install on Ubuntu 20.04.2

When i run ./algo I get the following error:
TASK [Ensure Ansible is not being run in a world writable directory] *****************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "The conditional check '_playbook_dir.stat.mode|int <= 0775' failed. The error was: template error while templating string: expected token 'end of statement block', got 'integer'. String: {% if _playbook_dir.stat.mode|int <= 0775 %} True {% else %} False {% endif %}"}

Full command and output below

(.env) root@cloud:~/algo# ./algo
[WARNING]: Could not match supplied host pattern, ignoring: vpn-host

PLAY [localhost] *********************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Playbook dir stat] *************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Ensure Ansible is not being run in a world writable directory] *****************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "The conditional check '_playbook_dir.stat.mode|int <= 0775' failed. The error was: template error while templating string: expected token 'end of statement block', got 'integer'. String: {% if _playbook_dir.stat.mode|int <= 0775 %} True {% else %} False {% endif %}"}

PLAY RECAP ***************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

**Comment by davidemyers** [comment]
This looks like the same issue reported in #14204. There's a suggested fix in that issue you can try.

**Comment by mnihal22** [comment]
That seems to work. I haven't finished installing yet. But the error does not appear upon editing requirements.txt as mentioned in the suggested fix
