### ISSUE TITLE
TASK [Ensure Ansible is not being run in a world writable directory] 

### ISSUE THREAD

**Issue by f98pno** [trailofbits/algo#14209]
Hi all!

I have been following the steps on:
https://www.howtoforge.com/how-to-install-and-configure-algo-vpn-server-on-ubuntu-20-04/
Both on Ubuntu 20.04 and 21.04. In both occations, I am getting the following error in the installation process:

TASK [Ensure Ansible is not being run in a world writable directory] ************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "The conditional check '_playbook_dir.stat.mode|int <= 0775' failed. The error was: template error while templating string: expected token 'end of statement block', got 'integer'. String: {% if _playbook_dir.stat.mode|int <= 0775 %} True {% else %} False {% endif %}"}
PLAY RECAP **********************************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0 

Below is my config.cfg file. I did set up an Algo VPN server a while ago according the the same instructions.

---------

users:
  - test1
  - test2
  - test3

ssh_port: 4160

ipsec_enabled: true

wireguard_enabled: true
wireguard_port: 989

alternative_ingress_ip: false

reduce_mtu: 0

adblock_lists:
 - "https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts"

dns_encryption: true

BetweenClients_DROP: true

block_smb: true

block_netbios: true

unattended_reboot:
  enabled: true
  time: 00:00

dnscrypt_servers:
  ipv4:
    - cloudflare
  ipv6:
    - cloudflare-ipv6

dns_servers:
  ipv4:
    - 1.1.1.1
    - 1.0.0.1
  ipv6:
    - 2606:4700:4700::1111
    - 2606:4700:4700::1001

pki_in_tmpfs: true

keys_clean_all: false

strongswan_log_level: 2

strongswan_network: 10.48.0.0/16
strongswan_network_ipv6: '2001:db8:4160::/48'

wireguard_PersistentKeepalive: 0

wireguard_network_ipv4: 10.49.0.0/16
wireguard_network_ipv6: 2001:db8:a160::/48

local_service_ip: "{{ '172.16.0.1' | ipmath(1048573 | random(seed=algo_server_name + ansible_fqdn)) }}"
local_service_ipv6: "{{ 'fd00::1' | ipmath(1048573 | random(seed=algo_server_name + ansible_fqdn)) }}"

no_log: true

congrats:
  common: |
    "#                          Congratulations!                            #"
    "#                     Your Algo server is running.                     #"
    "#    Config files and certificates are in the ./configs/ directory.    #"
    "#              Go to https://whoer.net/ after connecting               #"
    "#        and ensure that all your traffic passes through the VPN.      #"
    "#                     Local DNS resolver {{ local_service_ip }}{{ ', ' + local_service_ipv6 if ipv6_support else '' }}                   #"
  p12_pass: |
    "#        The p12 and SSH keys password for new users is {{ p12_export_password }}       #"
  ca_key_pass: |
    "#        The CA key password is {{ CA_password|default(omit) }}       #"
  ssh_access: |
    "#      Shell access: ssh -F configs/{{ ansible_ssh_host|default(omit) }}/ssh_config {{ algo_server_name }}        #"

SSH_keys:
  comment: algo@ssh
  private: configs/algo.pem
  private_tmp: /tmp/algo-ssh.pem
  public: configs/algo.pem.pub

cloud_providers:
  azure:
    size: Standard_B1S
    image:
      publisher: Canonical
      offer: 0001-com-ubuntu-server-focal-daily
      sku: 20_04-daily-lts
      version: latest
  digitalocean:
    size: s-1vcpu-1gb
    image: "ubuntu-20-04-x64"
  ec2:
    # Change the encrypted flag to "false" to disable AWS volume encryption.
    encrypted: true
    # Set use_existing_eip to "true" if you want to use a pre-allocated Elastic IP
    # Additional prompt will be raised to determine which IP to use
    use_existing_eip: false
    size: t2.micro
    image:
      name: "ubuntu-focal-20.04"
      owner: "099720109477"
  gce:
    size: f1-micro
    image: ubuntu-2004-lts
    external_static_ip: false
  lightsail:
    size: micro_2_0
    image: ubuntu_20_04
  scaleway:
    size: DEV1-S
    image: Ubuntu 20.04 Focal Fossa
    arch: x86_64
  hetzner:
    server_type: cx11
    image: ubuntu-20.04
  openstack:
    flavor_ram: ">=512"
    image:  Ubuntu-18.04
  cloudstack:
    size: Micro
    image: Linux Ubuntu 20.04 LTS 64-bit
    disk: 10
  vultr:
    os: Ubuntu 20.04 x64
    size: 1024 MB RAM,25 GB SSD,1.00 TB BW
  linode:
    type: g6-nanode-1
    image: linode/ubuntu20.04
  local:

fail_hint:
  - Sorry, but something went wrong!
  - Please check the troubleshooting guide.
  - https://trailofbits.github.io/algo/troubleshooting.html

booleans_map:
  Y: true
  y: true

>

**Comment by kadektop2** [comment]
Try disabling the directory permission check as described [here](https://github.com/trailofbits/algo/issues/14204#issuecomment-839681938).

**Comment by f98pno** [comment]
Great, thanks, adding jinja2==2.8 to requirements.txt solved it!
