### ISSUE TITLE
How to choose a different ec2 machine rather than the free tier one?

### ISSUE THREAD

**Issue by ramseth001** [trailofbits/algo#14214]
I have created algo VPN on AWS cloud and it's working awesome. Is there anyway that I could choose a different ec2 machine rather than the free tier one ?

**Comment by davidemyers** [comment]
You can specify a different instance size in the `cloud_providers` section of `config.cfg`.

**Comment by carevjr** [comment]
> I have created algo VPN on AWS cloud and it's working awesome. Is there anyway that I could choose a different ec2 machine rather than the free tier one ?

What sort of image did you use on amazon?I tried a cuple weeks ago but no sucess I'll try again this weekend

**Comment by ramseth001** [comment]
@carevjr I didn't do any customization. I just followed the [instructions](https://github.com/trailofbits/algo/blob/master/docs/cloud-amazon-ec2.md) and it worked fine. At which part you're getting the error?
