### ISSUE TITLE
Error Deploy

### ISSUE THREAD

**Issue by ferasawadi** [trailofbits/algo#14212]
Hello there, thanks for the efforts For the algo server.
few days ago I was able to deploy the server 
but today am getting this.
ModuleNotFoundError: No module named 'virtualenv.seed.via_app_data'
any ideas ?
warm regards

**Comment by ferasawadi** [comment]
Solved by 👍 pip3 install virtualenv==20.0.23

**Comment by davidemyers** [comment]
>`TASK [Ensure Ansible is not being run in a world writable directory] `

See #14204.

**Comment by ferasawadi** [comment]
thanks that soles the issue
