### ISSUE TITLE
Can Algo be used to implement site-to-site?

### ISSUE THREAD

**Issue by bboerner** [trailofbits/algo#1421]
Once Algo is deployed into the cloud can the Strongswan config be updated to add site-to-site?

Use case: dynamic IP user needs to setup site-to-site.

Cloud is static IP so setup Algo plus site-to-site. Client VPNs into Algo VPN and has access to the site-to-site networks.

Related question, can Algo be configured to configure only certain routes for client instead of default route ala Cisco Anywhere VPNs I've attached to?

Thanks!

**Comment by jackivanov** [comment]
We don't provide such functionality, sorry. You may try to ask in [gitter](https://gitter.im/trailofbits/algo) or follow the strongswan docs.
