### ISSUE TITLE
dnscrypt-proxy fails to start - signature problem

### ISSUE THREAD

**Issue by iamvishnurajan** [trailofbits/algo#14234]
**Describe the bug**

After creating an algo VPN instance on DigitalOcean, I was having frequent dns lookup problems. After logging into the server, I see that dnscrypt-proxy failed to start. Logging shows there is some kind of a signature issue.

algo@AlgoVPN-NYC3-20210627:~$ systemctl --failed
  UNIT                   LOAD   ACTIVE SUB    DESCRIPTION          
● dnscrypt-proxy.service loaded failed failed DNSCrypt client proxy

LOAD   = Reflects whether the unit definition was properly loaded.
ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
SUB    = The low-level unit activation state, values depend on unit type.

algo@AlgoVPN-NYC3-20210627:~$ journalctl -u dnscrypt-proxy
-- Logs begin at Sun 2021-06-27 05:54:40 UTC, end at Sun 2021-06-27 06:04:07 UTC. --
Jun 27 05:57:31 AlgoVPN-NYC3-20210627 systemd[1]: Started DNSCrypt client proxy.
Jun 27 05:57:31 AlgoVPN-NYC3-20210627 dnscrypt-proxy[2981]: [2021-06-27 05:57:31] [NOTICE] dnscrypt-proxy 2.0.31
Jun 27 05:57:31 AlgoVPN-NYC3-20210627 dnscrypt-proxy[2981]: [2021-06-27 05:57:31] [NOTICE] Network connectivity detected
Jun 27 05:57:32 AlgoVPN-NYC3-20210627 dnscrypt-proxy[2981]: [2021-06-27 05:57:32] [NOTICE] Source [/var/cache/dnscrypt-proxy/public-resolvers.md] loaded
Jun 27 05:57:32 AlgoVPN-NYC3-20210627 dnscrypt-proxy[2981]: [2021-06-27 05:57:32] [NOTICE] Firefox workaround initialized
Jun 27 05:57:32 AlgoVPN-NYC3-20210627 dnscrypt-proxy[2981]: [2021-06-27 05:57:32] [WARNING] Systemd sockets are untested and unsupported - use at your own r>
Jun 27 05:57:32 AlgoVPN-NYC3-20210627 dnscrypt-proxy[2981]: [2021-06-27 05:57:32] [NOTICE] Wiring systemd TCP socket #0, dnscrypt-proxy.socket, 127.0.2.1:53
Jun 27 05:57:32 AlgoVPN-NYC3-20210627 dnscrypt-proxy[2981]: [2021-06-27 05:57:32] [NOTICE] Wiring systemd UDP socket #1, dnscrypt-proxy.socket, 127.0.2.1:53
Jun 27 05:57:32 AlgoVPN-NYC3-20210627 dnscrypt-proxy[2981]: [2021-06-27 05:57:32] [NOTICE] [cloudflare] OK (DoH) - rtt: 3ms
Jun 27 05:57:32 AlgoVPN-NYC3-20210627 dnscrypt-proxy[2981]: [2021-06-27 05:57:32] [NOTICE] Server with the lowest initial latency: cloudflare (rtt: 3ms)
Jun 27 05:57:32 AlgoVPN-NYC3-20210627 dnscrypt-proxy[2981]: [2021-06-27 05:57:32] [NOTICE] dnscrypt-proxy is ready - live servers: 1
Jun 27 05:57:42 AlgoVPN-NYC3-20210627 dnscrypt-proxy[2981]: [2021-06-27 05:57:42] [NOTICE] Stopped.
Jun 27 05:57:42 AlgoVPN-NYC3-20210627 systemd[1]: Stopping DNSCrypt client proxy...
Jun 27 05:57:42 AlgoVPN-NYC3-20210627 systemd[1]: dnscrypt-proxy.service: Succeeded.
Jun 27 05:57:42 AlgoVPN-NYC3-20210627 systemd[1]: Stopped DNSCrypt client proxy.
Jun 27 05:57:42 AlgoVPN-NYC3-20210627 systemd[1]: Started DNSCrypt client proxy.
Jun 27 05:57:42 AlgoVPN-NYC3-20210627 dnscrypt-proxy[3347]: config option `refused_code_in_responses` is deprecated, use `blocked_query_response`
Jun 27 05:57:42 AlgoVPN-NYC3-20210627 dnscrypt-proxy[3347]: dnscrypt-proxy 2.0.31
Jun 27 05:57:42 AlgoVPN-NYC3-20210627 dnscrypt-proxy[3347]: Network connectivity detected
Jun 27 05:57:42 AlgoVPN-NYC3-20210627 dnscrypt-proxy[3347]: **Unable to retrieve source [public-resolvers]: [Invalid signature]**
Jun 27 05:57:42 AlgoVPN-NYC3-20210627 dnscrypt-proxy[3347]: **Invalid signature**
Jun 27 05:57:42 AlgoVPN-NYC3-20210627 systemd[1]: dnscrypt-proxy.service: Main process exited, code=exited, status=255/EXCEPTION
Jun 27 05:57:42 AlgoVPN-NYC3-20210627 systemd[1]: dnscrypt-proxy.service: Failed with result 'exit-code'.
Jun 27 05:57:43 AlgoVPN-NYC3-20210627 systemd[1]: Started DNSCrypt client proxy.
Jun 27 05:57:43 AlgoVPN-NYC3-20210627 dnscrypt-proxy[3417]: config option `refused_code_in_responses` is deprecated, use `blocked_query_response`
Jun 27 05:57:43 AlgoVPN-NYC3-20210627 dnscrypt-proxy[3417]: dnscrypt-proxy 2.0.31
Jun 27 05:57:43 AlgoVPN-NYC3-20210627 dnscrypt-proxy[3417]: Network connectivity detected
Jun 27 05:57:43 AlgoVPN-NYC3-20210627 dnscrypt-proxy[3417]: **Unable to retrieve source [public-resolvers]: [Invalid signature]**
Jun 27 05:57:43 AlgoVPN-NYC3-20210627 dnscrypt-proxy[3417]: **Invalid signature**
Jun 27 05:57:43 AlgoVPN-NYC3-20210627 systemd[1]: dnscrypt-proxy.service: Main process exited, code=exited, status=255/EXCEPTION
Jun 27 05:57:43 AlgoVPN-NYC3-20210627 systemd[1]: dnscrypt-proxy.service: Failed with result 'exit-code'.
Jun 27 05:57:44 AlgoVPN-NYC3-20210627 systemd[1]: Started DNSCrypt client proxy.
Jun 27 05:57:44 AlgoVPN-NYC3-20210627 dnscrypt-proxy[3450]: config option `refused_code_in_responses` is deprecated, use `blocked_query_response`
Jun 27 05:57:44 AlgoVPN-NYC3-20210627 dnscrypt-proxy[3450]: dnscrypt-proxy 2.0.31
Jun 27 05:57:44 AlgoVPN-NYC3-20210627 dnscrypt-proxy[3450]: Network connectivity detected
Jun 27 05:57:44 AlgoVPN-NYC3-20210627 dnscrypt-proxy[3450]: **Unable to retrieve source [public-resolvers]: [Invalid signature]**
Jun 27 05:57:44 AlgoVPN-NYC3-20210627 dnscrypt-proxy[3450]: **Invalid signature**
Jun 27 05:57:44 AlgoVPN-NYC3-20210627 systemd[1]: dnscrypt-proxy.service: Main process exited, code=exited, status=255/EXCEPTION
Jun 27 05:57:44 AlgoVPN-NYC3-20210627 systemd[1]: dnscrypt-proxy.service: Failed with result 'exit-code'.

**To Reproduce**

1. Deploy an algo VPN instance on DigitalOcean NYC3 datacenter
2. Select the option to enable adblock during the deployment
3. After deployment completes, dnscrypt-proxy fails to start

**Expected behavior**

1. DNS works with adblock as selected in the config options

**Additional Info**

It appears looking at the DNScrypt page here https://github.com/DNSCrypt/dnscrypt-resolvers/, updates were made around signing today (the commit just says "Sign") so I am guessing something needs to be updated in Algo to account for that. I am not sure where the update needs to be made however.

**Full log**

Attached below.
[algo_install_log.txt](https://github.com/trailofbits/algo/files/6721104/algo_install_log.txt)

**Comment by Tailzip** [comment]
Faced the same issue on Ubuntu 20.04 LTS instance. I had to update dnscrypt-proxy version from 2.0.31 (https://packages.ubuntu.com/focal/dnscrypt-proxy) from official Ubuntu repository to 2.0.45 (ppa:shevchuk/dnscrypt-proxy). 

I noticed there's a conditional check in Algo's dns role (https://github.com/trailofbits/algo/blob/master/roles/dns/tasks/ubuntu.yml#L20) to not add `ppa:shevchuk/dnscrypt-proxy` repo if Ubuntu version is 20.04 or more. I commented that line, and ran `./algo` again, it started working again. HTH

**Comment by davidemyers** [comment]
I've submitted issue [#519](https://github.com/DNSCrypt/dnscrypt-resolvers/issues/519) with dnscrypt-proxy.

**Comment by davidemyers** [comment]
The issue has been fixed.

**Comment by iamvishnurajan** [comment]
Great - thank you so much for helping out with this.
