### ISSUE TITLE
How to shutdown and remove services?

### ISSUE THREAD

**Issue by wanglongqi** [trailofbits/algo#1424]
After server start up, is there a way to control the server? Or at least, is there a way to stop and remove the services installed?

**Comment by davidemyers** [comment]
Algo provides no uninstall option. The normal use case is to delete your cloud instance when you're done with it.

I haven't tested this, but this command should stop the Algo services installed by default:
```
sudo systemctl disable --now ipsec wg-quick@wg0 dnscrypt-proxy netfilter-persistent
```

**Comment by wanglongqi** [comment]
Sure, but in my case the services are directly installed on my computer. I feel leave the ports open there are not that safe.

**Comment by davidemyers** [comment]
Well the command above removes the firewall that Algo installed and leaves *all* of your ports open, so you'll want to enable your own firewall after shutting down Algo.

**Comment by wanglongqi** [comment]
Thanks
