### ISSUE TITLE
how to get the connection credentials  

### ISSUE THREAD

**Issue by ferasawadi** [trailofbits/algo#14241]
Hello there and thank you for the awesome server.
I have one question if I want to connect to the ikev2 server how can I.I get the connection credentials.
the remote Id, localId , serverip, the username password and the shared key ?
warm regards

**Comment by davidemyers** [comment]
All client configuration files can be found under the `configs` directory once Algo finishes running.

**Comment by ferasawadi** [comment]
I saw that but am trying to enter the connection config manually using Swift Code on IOS.
any way to get the credentials ?
warm regards

**Comment by laosb** [comment]
in `configs/< your server name >/ipsec/manual` you'll find `.conf`, `.p12` and `.secrets` for users. Just use them.
