### ISSUE TITLE
Gcloud hangs when wireguard tunnel active and hosted on GCP

### ISSUE THREAD

**Issue by cosmopockets** [trailofbits/algo#14259]
**Describe the bug**

Issue Summary: 
I have a wireguard instance hosted on Google Cloud that is enabled by default when my machine boots up. I recently noticed that when running come gcloud commands the connection hangs for some time. I've not tested how long the connection.

When I stop the wireguard service and re-run the same command it runs successfully. You can also test this by running a ping command to "google.com" which is expected to hang, and "github.com" will show packets being sent. 

**To Reproduce**

1. Walk through algo setup process and create wg client on GCP
2. install the gcloud sdk, and run gcloud init if you have not done so
3. an example command is $ gcloud compute images list

**Expected behavior**

For gcloud to output the expected results given all fields are correct. 

**Additional context**

I suspect this has to do with firewall rules / traffic when wireguard initially setup the client. I'm able to use any web browser to access the Google Cloud Console and run the same command in the Active Shell. 

**Full log**

```
➜  ~ ping google.com -v       
PING google.com(2607:f8b0:4023:1006::71 (2607:f8b0:4023:1006::71)) 56 data bytes
^C
--- google.com ping statistics ---
11 packets transmitted, 0 received, 100% packet loss, time 10240ms

➜  ~ ping github.com -v
PING github.com (192.30.255.112) 56(84) bytes of data.
64 bytes from lb-192-30-255-112-sea.github.com (192.30.255.112): icmp_seq=1 ttl=48 time=64.8 ms
64 bytes from lb-192-30-255-112-sea.github.com (192.30.255.112): icmp_seq=2 ttl=48 time=65.4 ms
64 bytes from lb-192-30-255-112-sea.github.com (192.30.255.112): icmp_seq=3 ttl=48 time=66.0 ms
64 bytes from lb-192-30-255-112-sea.github.com (192.30.255.112): icmp_seq=4 ttl=48 time=67.5 ms
^C
--- github.com ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3004ms
rtt min/avg/max/mdev = 64.827/65.939/67.539/1.008 ms

➜  ~ systemctl stop wg-quick@wg0.service 
➜  ~ ping google.com
PING google.com(dfw28s27-in-x0e.1e100.net (2607:f8b0:4000:800::200e)) 56 data bytes
64 bytes from dfw28s27-in-x0e.1e100.net (2607:f8b0:4000:800::200e): icmp_seq=1 ttl=114 time=60.6 ms
64 bytes from dfw28s27-in-x0e.1e100.net (2607:f8b0:4000:800::200e): icmp_seq=2 ttl=114 time=62.4 ms
64 bytes from dfw28s27-in-x0e.1e100.net (2607:f8b0:4000:800::200e): icmp_seq=3 ttl=114 time=62.1 ms
64 bytes from dfw28s27-in-x0e.1e100.net (2607:f8b0:4000:800::200e): icmp_seq=4 ttl=114 time=62.4 ms
^C
--- google.com ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3005ms
rtt min/avg/max/mdev = 60.570/61.878/62.412/0.763 ms

```

**Comment by davidemyers** [comment]
Could you clarify where things are running?

AlgoVPN server: GCP instance?

WireGuard client of AlgoVPN server where you're running `gcloud` and `ping`: A separate GCP instance? Also running Ubuntu Server?

Does `ping -4 google.com` work from the client with WireGuard up?

**Comment by cosmopockets** [comment]
Hey David,

I was able to resolve this issue, for a reason I haven't found yet. There was a discrepancy on how a vpn hosted on a GCP network can have issue pinging Google's domain. It has been several months since I tested this so it make have been resolved or a temporary issue.
