### ISSUE TITLE
nm-applet is missing added VPN

### ISSUE THREAD

**Issue by vitaly-zdanevich** [trailofbits/algo#14267]
VPN works after `sudo systemctl start wg-quick@wg0`, its ok for me, but casual users want GUI:

![image](https://user-images.githubusercontent.com/3514015/128168203-b3a695f6-4662-445a-acd2-4b3f99d4ccc4.png)

**Comment by jackivanov** [comment]
We can't affect that form the server side. It's a matter of every linux GUI's user to figure out on themself. Eg: [Gnome](https://mox.sh/sysadmin/wireguard-networkmanager-gnome/). On MacOS it's fine.
