### ISSUE TITLE
Is it possible to explicitly specify the public key for a user?

### ISSUE THREAD

**Issue by srevinsaju** [trailofbits/algo#14268]
**Is your feature request related to a problem? Please describe.**
Is it possible to specify the public key for Wireguard in the configuration so that, for multiple users, I will not have to send them the private key back.. and also, to keep the users happy (since they generate the private key on their machine).

**Describe the solution you'd like**
Allow providing the wireguard public key

**Describe alternatives you've considered**
Nothing else tbh, no clue.

**Additional context**
nil.

**Comment by srevinsaju** [comment]
This is the workaround I do now:
1. Apply this patch

```diff
diff --git a/roles/wireguard/tasks/keys.yml b/roles/wireguard/tasks/keys.yml
index 19f3c1e..8dffdfd 100644
--- a/roles/wireguard/tasks/keys.yml
+++ b/roles/wireguard/tasks/keys.yml
@@ -9,7 +9,7 @@
     - "{{ IP_subject_alt_name }}"

 - name: Generate private keys
-  command: wg genkey
+  command: echo "\$YOUR_PRIVATE_KEY"
   register: wg_genkey
   args:
     creates: "{{ config_prefix|default('/') }}etc/wireguard/private_{{ item }}.lock"
@@ -80,8 +80,8 @@
 - name: Generate public keys
   shell: |
     set -o pipefail
-    echo "{{ lookup('file', wireguard_pki_path + '/private/' + item) }}" |
-    wg pubkey
+    echo "{{ lookup('file', wireguard_pki_path + '/public/' + item) }}"
+
   register: wg_pubkey
   changed_when: false
   args:
```
2. Place the public key in `configs/$IPADDRESS/wireguard/.pki/public`
```bash
echo PUBLICKEY > configs/$IPADDRESS/wireguard/.pki/public/$username
```
3. Add the `$username` to `config.cfg`
4. Run `./algo update-users`

**Comment by jackivanov** [comment]
At the moment it's not possible, and we don't have plans to support it.
