### ISSUE TITLE
`sudo systemctl start wg-quick@wg0` fail if ipv6 is disabled

### ISSUE THREAD

**Issue by vitaly-zdanevich** [trailofbits/algo#14273]
Ubuntu 21.04

I added to `/etc/default/grub` to `GRUB_CMDLINE_LINUX_DEFAULT`: `ipv6.disable=1`, so now it:
`GRUB_CMDLINE_LINUX_DEFAULT="quiet pci=noaer ipv6.disable=1"`

And now on `sudo systemctl start wg-quick@wg0` I see:

    Job for wg-quick@wg0.service failed because the control process exited with error code.
    See "systemctl status wg-quick@wg0.service" and "journalctl -xe" for details.

`$ journalctl -xe` return

    No journal files were found.

`sudo systemctl status wg-quick@wg0` return

```
● wg-quick@wg0.service - WireGuard via wg-quick(8) for wg0
     Loaded: loaded (/lib/systemd/system/wg-quick@.service; disabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2021-08-11 19:07:03 +03; 13min ago
       Docs: man:wg-quick(8)
             man:wg(8)
             https://www.wireguard.com/
             https://www.wireguard.com/quickstart/
             https://git.zx2c4.com/wireguard-tools/about/src/man/wg-quick.8
             https://git.zx2c4.com/wireguard-tools/about/src/man/wg.8
    Process: 1732 ExecStart=/usr/bin/wg-quick up wg0 (code=exited, status=2)
   Main PID: 1732 (code=exited, status=2)
```

**Comment by davidemyers** [comment]
Is this system a client or is it your AlgoVPN server?

**Comment by vitaly-zdanevich** [comment]
A client.

**Comment by davidemyers** [comment]
It looks like your AlgoVPN server has IPv6 so Algo added IPv6 configuration information to the WireGuard configuration files it generated. Try removing all of the IPv6 addresses from the `wg0.conf` file on this client.

**Comment by jackivanov** [comment]
This is expected for provides that have IPv6 enabled. You can delete IPv6 addresses from the configs or pass `-e '{"ipv6_support": false}'` to the installer to disable it.
