### ISSUE TITLE
Set facts about the region fails with Azure initial setup

### ISSUE THREAD

**Issue by masterugwee** [trailofbits/algo#14274]
**Describe the bug**

When executing ./algo on Ubuntu machine to configure a setup with Azure, the script fails at "TASK [cloud-azure : Set facts about the regions]" 

**To Reproduce**

1. Install requirements and dependencies for algo 
2. run ./algo and complete prompt till SSH tunneling prompt 
3. get the error

**Full log**

TASK [cloud-azure : Set facts about the regions] *********************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "the field 'args' has an invalid value ({'azure_regions': \"{{ _azure_regions|from_json | sort(attribute='name') }}\"}), and could not be converted to an dict.The error was: Extra data: line 326 column 3 (char 7142)\n\nThe error appears to be in '/home/user/algo/roles/cloud-azure/tasks/prompts.yml': line 9, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n- block:\n  - name: Set facts about the regions\n    ^ here\n"}
included: /home/user/algo/playbooks/rescue.yml for localhost

**Comment by davidemyers** [comment]
I think there's a syntax error in [`roles/cloud-azure/defaults/main.yml`](https://github.com/trailofbits/algo/blob/4464be82599076e7b1cf57c10802bed1a4e0aea6/roles/cloud-azure/defaults/main.yml#L326), which was just changed with PR #14233.

Try applying the patch below to see if it fixes the problem for you. Save it to a file in your `algo` directory named, for example, `azure.patch`.

If you obtained your copy of Algo using `git clone` run:
```
git apply azure.patch
```
If you obtained Algo via downloading the ZIP file run:
```
patch -p1 < azure.patch
```

Here's the patch:
```plain
diff --git a/roles/cloud-azure/defaults/main.yml b/roles/cloud-azure/defaults/main.yml
index 54626d5..0eebbbd 100644
--- a/roles/cloud-azure/defaults/main.yml
+++ b/roles/cloud-azure/defaults/main.yml
@@ -322,9 +322,7 @@ _azure_regions: >
       "longitude": "-112.074036",
       "name": "westus3",
       "subscriptionId": null
-    }
-  ]
-
+    },
     {
       "displayName": "North Central US",
       "latitude": "41.8819",
```

**Comment by wesmi** [comment]
I'm...not sure how that happened, that the extra (previous version?) of the file got added onto the end yet my test still worked locally back in June. There are so many entries, I didn't see the duplication. I've submitted a change to remove the extra blocks.
