### ISSUE TITLE
Failed to update apt cache

### ISSUE THREAD

**Issue by superfalcon18** [trailofbits/algo#14279]
**So I was trying to run algo on my local ubuntu 20 system (not a vm) and i encountered this issue**
LOG:
```
TASK [common : Install tools] **************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to update apt cache: W:Updating from such a repository can't be done securely, and is therefore disabled by default., W:See apt-secure(8) manpage for repository creation and user configuration details., E:The repository 'http://ppa.launchpad.net/webupd8team/java/ubuntu focal Release' does not have a Release file."}
included: /home/super/vpn/algo/playbooks/rescue.yml for localhost

TASK [debug] *******************************************************************
ok: [localhost] => {
    "fail_hint": [
        "Sorry, but something went wrong!",
        "Please check the troubleshooting guide.",
        "https://trailofbits.github.io/algo/troubleshooting.html"
    ]
}

TASK [Fail the installation] ***************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed as requested from task"}

PLAY RECAP *********************************************************************
localhost                  : ok=49   changed=3    unreachable=0    failed=1    skipped=18   rescued=1    ignored=0   

```
I tried restarting my pc and closing all apps that might be using APT
sorry but i am quite new to linux :)

**Comment by davidemyers** [comment]
Are you attempting a [Local Installation](https://github.com/trailofbits/algo/blob/master/docs/deploy-to-ubuntu.md#local-installation)? The repository `http://ppa.launchpad.net/webupd8team/java/ubuntu` that's causing the error is not used by Ubuntu Server 20.04 by default.

**Comment by superfalcon18** [comment]
> Are you attempting a [Local Installation](https://github.com/trailofbits/algo/blob/master/docs/deploy-to-ubuntu.md#local-installation)? The repository `http://ppa.launchpad.net/webupd8team/java/ubuntu` that's causing the error is not used by Ubuntu Server 20.04 by default.

ohh ya i fixed it tho
by uninstalling the package :)

**Comment by nrv9999** [comment]
> > Are you attempting a [Local Installation](https://github.com/trailofbits/algo/blob/master/docs/deploy-to-ubuntu.md#local-installation)? The repository `http://ppa.launchpad.net/webupd8team/java/ubuntu` that's causing the error is not used by Ubuntu Server 20.04 by default.
> 
> ohh ya i fixed it tho by uninstalling the package :)

Please describe (i hope you not mean algo as package). Installing on debian i got that problem.
