### ISSUE TITLE
WireGuard clients unreachable

### ISSUE THREAD

**Issue by researchimotion** [trailofbits/algo#14285]
Communication between WireGuard clients isn't possible, despite roadwarrior set in algo script (for IPsec).

However, it works for IPsec

![image](https://user-images.githubusercontent.com/81270358/131794601-87ec9617-b7bb-4f6c-9ed4-1c6af3161f2f.jpeg)

Tested on iOS and macOS

Thanks for your work!

**Comment by davidemyers** [comment]
Could you be having this issue described in #14229?

**Comment by researchimotion** [comment]
Ok it works now

Thanks. Can be closed
