### ISSUE TITLE
Regenerating private CA cert and key on deployment machine

### ISSUE THREAD

**Issue by ethindp** [trailofbits/algo#1428]
So, I made a mistake -- a very, very horrible mistake. And its entirely my fault and my stupidity to blame. :P So, here's what happened:

* I updated the user list
* I typed ./algo update-users
* I foolishly overrode the file containing the password to my private CA key on the machine I was doing the deployment from with the log of the user updates -- which, for obvious reasons, does not display the CA cert password again.

Normally, I'd never do this kind of thing, and I've never done something so foolish ever before. But it had to happen sometime, and I suppose its better I learn what to do now then later. Luckally for me the VPN I have going was just set up today and isn't in huge major deployments. My question:

1. I assume that there is no way to recover the CA password. However, I'll ask anyway -- is there such a way? I'd assume not but I don't know the inner-workings of Algo.
2. If my assumption is true -- and I get the feeling that it is -- is there a way I can regenerate the certificate and update the server, if I need to do that?

If option two is a go, what would I need to do to regenerate the certificate and get the server updated with it?

Edit: I'm attempting data recovery but my hopes aren't very high, and I don't want to have to redeploy the VPN again just to solve this problem.

**Comment by jackivanov** [comment]
1. No
2. You can set `keys_clean_all` to true in config.cfg, and run `./algo` with the same parameters. Don't forget to set `keys_clean_all` to false after the script

**Comment by ethindp** [comment]
I did that, and it didn't give me a new CA certificate password. Does
that mean that the CA cert password is no longer there?

On 5/7/19, Jack Ivanov <notifications@github.com> wrote:
> 1. No
> 2. You can set `keys_clean_all` to true in config.cfg, and run `./algo` with
> the same parameters. Don't forget to set `keys_clean_all` to false after the
> script
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/trailofbits/algo/issues/1428#issuecomment-490347431


-- 
Signed,
Ethin D. Probst

**Comment by ethindp** [comment]
Update: nevermind, I think I know how it works now. Feel free to reply
anyway if you'd like though.

On 5/8/19, Ethin Probst <harlydavidsen@gmail.com> wrote:
> I did that, and it didn't give me a new CA certificate password. Does
> that mean that the CA cert password is no longer there?
>
> On 5/7/19, Jack Ivanov <notifications@github.com> wrote:
>> 1. No
>> 2. You can set `keys_clean_all` to true in config.cfg, and run `./algo`
>> with
>> the same parameters. Don't forget to set `keys_clean_all` to false after
>> the
>> script
>>
>> --
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub:
>> https://github.com/trailofbits/algo/issues/1428#issuecomment-490347431
>
>
> --
> Signed,
> Ethin D. Probst
>


-- 
Signed,
Ethin D. Probst
