### ISSUE TITLE
cloud-ec2 : Copy to an encrypted image

### ISSUE THREAD

**Issue by tomciopp** [trailofbits/algo#1434]
**Describe the bug**
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ClientError: An error occurred (UnauthorizedOperation) when calling the CopyImage operation: You are not authorized to perform this operation.

```bash
fatal: [localhost]: FAILED! => {
  "boto3_version": "1.9.148",
  "botocore_version": "1.12.148", 
  "changed": false, 
  "error": {
    "code": "UnauthorizedOperation", 
    "message": "You are not authorized to perform this operation."
  }, 
  "msg": "Could not copy AMI: An error occurred (UnauthorizedOperation) when calling the CopyImage operation: You are not authorized to perform this operation.", 
  "response_metadata": {
    "http_headers": {
      "date": "Wed, 15 May 2019 15:52:14 GMT", 
      "server": "AmazonEC2", 
      "transfer-encoding": "chunked"
    }, 
    "http_status_code": 403, 
    "request_id": "3df69980-bced-49b7-9fbb-d6182cf4e8a0", 
    "retry_attempts": 0
  }
}
```

**To Reproduce**

Starting from a completely empty aws account. I followed the instructions in the following guide: https://github.com/trailofbits/algo/blob/master/docs/cloud-amazon-ec2.md

**Expected behavior**

Ansible should run through all of its tasks and everything should work

**Full log**

```
PUT THE OUTPUT HERE
```

**Comment by jackivanov** [comment]
It's covered [here](https://github.com/trailofbits/algo/blob/master/config.cfg#L145-L150). 

What If we just add `ec2:CopyImage` to the minimum required policies? Is there anything we can lose in security reasons?

**Comment by tomciopp** [comment]
Is that added to `PreDeployment` or `CloudFormationEC2Access`?

**Comment by TC1977** [comment]
@tomciopp It's added to the `PreDeployment` section. So the relevant snippet should read something like:
```aws
...
"Action": [
   "ec2:DescribeImages",
   "ec2:CopyImage",
   "ec2:DescribeKeyPairs",
   "ec2:DescribeRegions",
   "ec2:ImportKeyPair"
...
```

@jackivanov I also think it would be simpler to just add `ec2:CopyImage` to the minimum required policies. The main reason why I didn't suggest that back in the day of #1102  is because I didn't want to ask @michael-myers to make another screenshot so soon he updated it.

**Comment by TC1977** [comment]
@michael-myers Would you mind updating https://github.com/trailofbits/algo/blob/master/docs/images/aws-ec2-new-policy.png to add in the new policy as in 3ce92f9? Thanks.

**Comment by michael-myers** [comment]
Thanks @TC1977 and sorry for not getting around to that — I had a bit too much going on lately.
