### ISSUE TITLE
[Question] Android "IKEv2/IPSec RSA"

### ISSUE THREAD

**Issue by tiolan** [trailofbits/algo#14342]
Android 12 offers those two certificate based VPN methods:
- IKEv2/IPSec RSA
- IKEv2/IPSec MSCHAPv2

Should any of those work with algo, having WireGuard disabled and IKEv2 enabled?

I tried of course but failed, so just want to be sure it could work.

**Comment by davidemyers** [comment]
Algo is intended to be used only with WireGuard on Android.

**Comment by tiolan** [comment]
Understood, but what is the IKEv2 option in the config file then meant for?

**Comment by davidemyers** [comment]
IPsec works pretty well with macOS and iOS clients, though I think WireGuard works better. IPsec also works with Linux clients but WireGuard is much easier to configure.
