### ISSUE TITLE
Algo local server install destroys servers

### ISSUE THREAD

**Issue by kevinmcmurtrie** [trailofbits/algo#14349]
**Describe the bug**

Installing algo drops all incoming packets except port 22!!!

**To Reproduce**

Configure algo config file for Wireguard and no extra features.
Run algo installer on a local Ubuntu server

Server is no longer a server anymore.  There is no response to any inbound packets not on port 22.
Problem persists after restart and uninstall.

**Expected behavior**
- Wireguard VPN added without extreme side effects.
- Log of critical system changes.

**Additional context**
This absolutely must not be added to /etc/iptables/rules.v4 and rules.v6
```
# By default, drop packets that are destined for this server
:INPUT DROP [0:0]
```

**Full log**
Absolutely no logs, just the silent death of a server that can not accept incoming packets anymore.

**Comment by davidemyers** [comment]
The documentation page [Local Installation](https://github.com/trailofbits/algo/blob/master/docs/deploy-to-ubuntu.md) says:

>**PLEASE NOTE**: Algo is intended for use to create a _dedicated_ VPN server. No uninstallation option is provided. If you install Algo on an existing server any existing services might break. In particular, the firewall rules will be overwritten. See [AlgoVPN and Firewalls](/docs/firewalls.md) for more information.

**Comment by kevinmcmurtrie** [comment]
I read the section on [firewalls](https://github.com/trailofbits/algo/blob/master/docs/firewalls.md).  I have no static rules and my dynamic rules will interfere with Wireguard or VPN.  According to that document, everything should be fine.

Algo is setting rules that are outside the scope of maintaining a VPN.  That needs to be removed or documented clearly.

**Comment by davidemyers** [comment]
>**PLEASE NOTE**: Algo is intended for use to create a _dedicated_ VPN server. No uninstallation option is provided. If you install Algo on an existing server any _**EXISTING SERVICES MIGHT BREAK**_. In particular, the _**FIREWALL RULES WILL BE OVERWRITTEN**_. See [AlgoVPN and Firewalls](/docs/firewalls.md) for more information.

Better? :smiley:
