### ISSUE TITLE
"Unexpected templating type error occurred" while running algo

### ISSUE THREAD

**Issue by jauderho** [trailofbits/algo#1435]
**Describe the bug**

Error encountered while trying to run ./algo

**To Reproduce**

1. Download master.zip per README on 5/15/2019
2. Edit config.cfg to taste. Set up to install to local 18.04 VM.
3. Run ./algo

**Expected behavior**

Successful config did not happen.

**Additional context**

Should I be using the v1.0.zip instead?

**Full log**

```
TASK [wireguard : Generate public keys] ************************************************************************************************************************
ok: [localhost] => (item=ars)
fatal: [localhost]: FAILED! => {"msg": "Unexpected templating type error occurred on (set -o pipefail\n echo \"{{ lookup('file', wireguard_pki_path + '/private/' + item) }}\" |\n wg pubkey): coercing to Unicode: need string or buffer, int found"}
included: /home/wg/algo/algo-master/playbooks/rescue.yml for localhost

TASK [debug] ***************************************************************************************************************************************************
ok: [localhost] => {
    "fail_hint": [
        "Sorry, but something went wrong!", 
        "Please check the troubleshooting guide.", 
        "https://trailofbits.github.io/algo/troubleshooting.html"
    ]
}

TASK [Fail the installation] ***********************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed as requested from task"}

PLAY RECAP *****************************************************************************************************************************************************
localhost                  : ok=62   changed=23   unreachable=0    failed=2   
```

**Comment by jackivanov** [comment]
What's in your config.cfg? Is there any integer in the users variable?

**Comment by jauderho** [comment]
Yes, I have multiple users corresponding to hostnames with numbers. Eg. 5, 125. 

Should I change those to names instead? The weird part is it seems that the private keys were created. The script is just flaming out on the public key creation.

**Comment by jackivanov** [comment]
Python interpreters the numbers as integers, but it should be strings. You need to escape them with double quotes, eg:

```yaml
users:
  - phone
  - "5"
  - "125"
```

We need to cover it in the docs

**Comment by jauderho** [comment]
I just came back to report that changing the name to be more than a single integer fixes it but you had already followed up =)
