### ISSUE TITLE
error saying this

### ISSUE THREAD

**Issue by arpan20032009** [trailofbits/algo#14367]
TASK [debug] ***********************************************************************************************************ok: [localhost] => {
    "fail_hint": [
        "Sorry, but something went wrong!",
        "Please check the troubleshooting guide.",
        "https://trailofbits.github.io/algo/troubleshooting.html"
    ]
}

TASK [Fail the installation] *******************************************************************************************fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed as requested from task"}

PLAY RECAP *************************************************************************************************************localhost                  : ok=30   changed=2    unreachable=0    failed=1    skipped=5    rescued=1    ignored=0

**Comment by davidemyers** [comment]
There should have been a message with the actual error before the message you posted was displayed.
