### ISSUE TITLE
Constantly Receiving Error Upon Install: "Can only concatenate str"

### ISSUE THREAD

**Issue by ItsActuallyTJ** [trailofbits/algo#14376]
TASK [wireguard : Generate public keys] **********************************************************************************************************************************************************************************************************
fatal: [35.236.16.184]: FAILED! => {"msg": "Unexpected templating type error occurred on (set -o pipefail\necho \"{{ lookup('file', wireguard_pki_path + '/private/' + item) }}\" |\nwg pubkey\n): can only concatenate str (not \"int\") to str"}

TASK [include_tasks] *****************************************************************************************************************************************************************************************************************************
included: /home/[USER]/algo/playbooks/rescue.yml for [IP ADDRESS]

TASK [debug] *************************************************************************************************************************************************************************************************************************************
ok: [IP ADDRESS] => {
    "fail_hint": [
        "Sorry, but something went wrong!",
        "Please check the troubleshooting guide.",
        "https://trailofbits.github.io/algo/troubleshooting.html"
    ]
}

TASK [Fail the installation] *********************************************************************************************************************************************************************************************************************
fatal: [IP ADDRESS]: FAILED! => {"changed": false, "msg": "Failed as requested from task"}

PLAY RECAP ***************************************************************************************************************************************************************************************************************************************
[IP ADDRESS]              : ok=54   changed=31   unreachable=0    failed=1    skipped=13   rescued=1    ignored=0
localhost                  : ok=45   changed=9    unreachable=0    failed=0    skipped=8    rescued=0    ignored=0

**Comment by davidemyers** [comment]
Post your list of users from `config.cfg`.

**Comment by ItsActuallyTJ** [comment]
omg they were all just number values, are users required to have string values as names?

**Comment by ItsActuallyTJ** [comment]
I'm facepalming so hard rn, I see it clearly says they have to have quotes

**Comment by ItsActuallyTJ** [comment]
Thanks for the insight
