### ISSUE TITLE
Missing .config.yml to update user

### ISSUE THREAD

**Issue by FabienO** [trailofbits/algo#14379]
No config.yml file in configs. Is it possible for me to create this myself manually as the server is already up an running. I also didn't find the cloudformation template in there. So I manually grabbed it from AWS and pasted it in. 

**To Reproduce**

1. Normal install on Ubuntu 18.04 VM using current master version.

**Expected behavior**

A config yml file to be produced.

**Full log**

PLAY [localhost] ***********************************************************************************************************************************************************************************

TASK [Get list of installed config files] **********************************************************************************************************************************************************
ok: [localhost]

TASK [Verify servers] ******************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {
    "assertion": "_configs_list.matched > 0",
    "changed": false,
    "evaluated_to": false,
    "msg": "No servers found, nothing to update."
}

PLAY RECAP *****************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

**Comment by davidemyers** [comment]
So you still have the `configs/<ip_addr>` directory that Algo created with all the client config files, but that directory is missing the file `.config.yml`?

Here's what one of my `configs/<ip_addr>/.config.yml` files looks like, edited for privacy:
```
server: <ip_addr>
server_user: algo
ansible_ssh_port: "4160"
ansible_ssh_private_key_file: configs/algo.pem
algo_provider: lightsail
algo_server_name: vpn3.<mydomain>
algo_ondemand_cellular: True
algo_ondemand_wifi: True
algo_ondemand_wifi_exclude: 
algo_dns_adblocking: False
algo_ssh_tunneling: False
algo_store_pki: True
IP_subject_alt_name: <ip_addr>
ipsec_enabled: True
wireguard_enabled: True

```

**Comment by FabienO** [comment]
That's correct. 

configs/<ip>/ipsec/
configs/<ip>/ssh-tunnel/
configs/<ip>/wireguard/
configs/<ip>/ssh_config
configs/algo.pem

And thank you for the sample file.
