### ISSUE TITLE
Unable to connect to multiple devices

### ISSUE THREAD

**Issue by folliejester** [trailofbits/algo#14381]
Hi I'm trying to connect to the VPN using the same account/qr code from two different device. However, once connected to two device, it would stop working and when I disconnect it from the 2nd device, it resumes working fine in device 1. Is it a bug or a feature? I'm trying to make a public VPN so I need one user to allow multiple connections.

**Comment by davidemyers** [comment]
As it says in the [README](https://github.com/trailofbits/algo#deploy-the-algo-server):

> Create a unique user for each device you plan to connect to your VPN.

This requirement is also mentioned in [`config.cfg`](https://github.com/trailofbits/algo/blob/de1e9093ab6326b18df162e9bdff85c76e429e3c/config.cfg#L4).

See WireGuard's explanation of [Cryptokey Routing](https://www.wireguard.com/#cryptokey-routing) for the reasons why.

**Comment by folliejester** [comment]
Is there any way I can create new users over API or connect to multiple devices with one user.

**Comment by davidemyers** [comment]
You might be able to use a single IPsec user config on multiple devices, but WireGuard does not allow this by design.

Of course if one of your users behaves badly and needs to be excluded there will be no way to revoke access for just that one person.

Algo is not great at user management.

**Comment by folliejester** [comment]
Can I add new users over API?

**Comment by davidemyers** [comment]
There is no API.

**Comment by folliejester** [comment]
Any way i can create users without using the CLI?                                                       --        Sent from Syden Secure Mail                                                                   On Sunday, Dec 12, 2021 at 11:35 PM, David Myers ***@***.******@***.***> wrote:                                 There is no API.       —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.       ***@***.***": ***@***.***": "EmailMessage","potentialAction": ***@***.***": "ViewAction","target": "https://github.com/trailofbits/algo/issues/14381#issuecomment-991943680","url": "https://github.com/trailofbits/algo/issues/14381#issuecomment-991943680","name": "View Issue"},"description": "View this Issue on GitHub","publisher": ***@***.***": "Organization","name": "GitHub","url": "https://github.com"}}]

**Comment by davidemyers** [comment]
The procedure for adding or removing users is documented in the [README](https://github.com/trailofbits/algo#adding-or-removing-users). There is no other undocumented user management function.
