### ISSUE TITLE
Use an existing EIP for ec2 deployment

### ISSUE THREAD

**Issue by FabienO** [trailofbits/algo#14380]
**Is your feature request related to a problem? Please describe.**
No problem.

**Describe the solution you'd like**
Allow us to choose or use an existing EIP in AWS when deploying to ec2. 

**Additional context**
If the server where the code hosting algo is old, or lost, we need to redeploy the algo server, but we have a specific EIP we have whitelisted everywhere. So it's hassle to create a new Algo server, then switch over all the IP addresses and settings in the configs and so on. Also, it is an issue when we have already maxed out our EIPs because install will fail.  So to use an existing would be awesome.

**Comment by davidemyers** [comment]
Try using the `use_existing_eip` setting in `config.cfg`.

Algo will still generate all new WireGuard and IPsec keys when you deploy a new server so you will still have to change all of the client configs.

**Comment by FabienO** [comment]
D'oh. Thank you!
