### ISSUE TITLE
Can connect to local resources via direct IP but cannot access via pc name

### ISSUE THREAD

**Issue by seanwil12** [trailofbits/algo#14396]
for example, if i want to access a network share or remote desktop on my local network I am VPN'd into, I can by typing in the direct IP address of that computer. I don't usually remember direct IPs so I would like to be able to use PC names as if I were sitting at my desktop. Nothing I do seems to work and allow me to resolve pc names on my network when connected to the VPN.

**Comment by jackivanov** [comment]
Algo's DNS resolver knows nothing about your local network. You can configure DNS to point to your router/dns resolver in config.cfg
