### ISSUE TITLE
Failed in Adding new user in WireGuard

### ISSUE THREAD

**Issue by ateymoori** [trailofbits/algo#14391]
Hi
I am using algo in Ubuntu 20 with DigitalOcean cloud.
everything is ok but when I add a new user in config.cfg then I tried to update users list, I am getting an error:

`TASK [strongswan : Build the client's pair] ******************************************************************************************************
ok: [localhost] => (item=phone)
ok: [localhost] => (item=laptop)
ok: [localhost] => (item=desktop)
failed: [localhost] (item=amir) => {"ansible_loop_var": "item", "changed": true, "cmd": "umask 077; openssl req -utf8 -new -newkey ec:ecparams/secp384r1.pem -config <(cat openssl.cnf <(printf \"[basic_exts]\\nsubjectAltName=email:amir@4d0060b9-9cd5-5fb6-bd69-e5e387875912.algo\")) -keyout private/amir.key -out reqs/amir.req -nodes -passin pass:\"omit\" -subj \"/CN=amir\" -batch && openssl ca -utf8 -in reqs/amir.req -out certs/amir.crt -config <(cat openssl.cnf <(printf \"[basic_exts]\\nsubjectAltName=email:amir@4d0060b9-9cd5-5fb6-bd69-e5e387875912.algo\")) -days 3650 -batch -passin pass:\"omit\" -subj \"/CN=amir\" && touch certs/amir_crt_generated\n", "delta": "0:00:00.024608", "end": "2021-12-24 23:58:16.605731", "item": "amir", "msg": "non-zero return code", "rc": 1, "start": "2021-12-24 23:58:16.581123", "stderr": "Generating an EC private key\nwriting new private key to 'private/amir.key'\n-----\nUsing configuration from /dev/fd/62\nunable to load CA private key\n139818776560960:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:../crypto/evp/evp_enc.c:610:\n139818776560960:error:23077074:PKCS12 routines:PKCS12_pbe_crypt:pkcs12 cipherfinal error:../crypto/pkcs12/p12_decr.c:62:\n139818776560960:error:2306A075:PKCS12 routines:PKCS12_item_decrypt_d2i:pkcs12 pbe crypt error:../crypto/pkcs12/p12_decr.c:93:\n139818776560960:error:0907B00D:PEM routines:PEM_read_bio_PrivateKey:ASN1 lib:../crypto/pem/pem_pkey.c:88:", "stderr_lines": ["Generating an EC private key", "writing new private key to 'private/amir.key'", "-----", "Using configuration from /dev/fd/62", "unable to load CA private key", "139818776560960:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:../crypto/evp/evp_enc.c:610:", "139818776560960:error:23077074:PKCS12 routines:PKCS12_pbe_crypt:pkcs12 cipherfinal error:../crypto/pkcs12/p12_decr.c:62:", "139818776560960:error:2306A075:PKCS12 routines:PKCS12_item_decrypt_d2i:pkcs12 pbe crypt error:../crypto/pkcs12/p12_decr.c:93:", "139818776560960:error:0907B00D:PEM routines:PEM_read_bio_PrivateKey:ASN1 lib:../crypto/pem/pem_pkey.c:88:"], "stdout": "", "stdout_lines": []}

`

Can you please help me?

**Comment by davidemyers** [comment]
This error is occurring when attempting to add the new user to IPsec, not WireGuard. It looks like WireGuard succeeded if you got this far.

Make sure you entered the CA private key password correctly at the prompt:
```
Enter the password for the private CA key
```
