### ISSUE TITLE
Python 3.8 requirement not registering Python 3.8

### ISSUE THREAD

**Issue by BenjaminDay** [trailofbits/algo#14403]
I do know what else I can try. I've reinstalled ubuntu 18.04 LTS multiple times and it always comes with 3.6.9 as default so I install 3.8 and it still doesnt register it. I even downgraded ansible versions because it was getting caught on those as well but no luck.

![image](https://user-images.githubusercontent.com/69356549/148409523-9c8be0eb-66fb-4019-9c34-4b6b2c6495e2.png)

Shouldn't the 18.04 LTS come with this by default? What am I doing wrong? Followed instructions to the T.

**Comment by davidemyers** [comment]
Ubuntu Server 18.04 is pretty old. Use 20.04 if you can.

If you must use 18.04, try setting up a new download of Algo like this:

```
PYTHON="python3.8"
${PYTHON} -m virtualenv --python="$(command -v ${PYTHON})" .env &&
    source .env/bin/activate &&
    ${PYTHON} -m pip install -U pip virtualenv &&
    ${PYTHON} -m pip install -r requirements.txt
```

**Comment by BenjaminDay** [comment]
Ah I see, so this comment is no longer accurate in that case then? 
"(at this time Ubuntu 20.04 LTS does not work with Algo when running under WSL)."
Will give it a shot

**Comment by davidemyers** [comment]
As I don't have Windows I don't know what's currently up with WSL. If it works please report back.

**Comment by BenjaminDay** [comment]
20.04 LTS launched correctly and came with 3.8 installed already, I suggest the docs get updated to avoid further confusion for other Windows users like myself. I am currently deploying Algo onto Digital Ocean so it seems to have worked! Thank you for your help!
