### ISSUE TITLE
Add/remove users from lambda

### ISSUE THREAD

**Issue by AlessandroAnnini** [trailofbits/algo#14409]
**Is your feature request related to a problem? Please describe.**
I would like to be able to programmatically add or remove users **using the CLI of the lambda**.

**Describe the solution you'd like**
I would like to be able to use a **lambda with a layer** configured to use Algo. I could read my configurations from somewhere else (S3 or EC2) and copy them where they need to be, then I could use the same commends you propose for the CLI but on the lambda function.

**Describe alternatives you've considered**
An alternative could be fire this process with a **git-action**.
Another one could be access via ssh from the lambda to the EC2 (?)

**Comment by jackivanov** [comment]
You can deploy from lambda using Docker - https://github.com/trailofbits/algo/blob/master/docs/deploy-from-docker.md
