### ISSUE TITLE
Linode stopped on stackscript creation

### ISSUE THREAD

**Issue by onesign12** [trailofbits/algo#14416]
**Describe the bug**

TASK [cloud-linode : Create a stackscript] ******************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unable to query the Linode API. Saw: 401: You must be authenticated to find your StackScripts.; "}

**Comment by davidemyers** [comment]
Make sure your Access Token has permission to read and write StackScripts as mentioned in [this document](https://github.com/trailofbits/algo/blob/master/docs/cloud-linode.md), which isn't linked from the main README so you probably missed it.

**Comment by onesign12** [comment]
Yes, I am sure I use access token with full privileges.

**Comment by onesign12** [comment]
Tried  "Install to existing Ubuntu 18.04 or 20.04 server" and it also failed 

TASK [Create a symlink if deploying to localhost] ***********************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "gid": 0, "group": "root", "mode": "0755", "msg": "the directory configs/localhost is not empty, refusing to convert it", "owner": "root", "path": "configs/localhost", "size": 4096, "state": "directory", "uid": 0}

...

**Comment by onesign12** [comment]
Solved with normal installation, by some reasons pasting in terminal added some weird characters to api token but as it is invisible I did not see it.

**Comment by davidemyers** [comment]
If you plan to deploy to Linode often you can set an environment variable in your shell that Algo will read instead of prompting you for the token. For example:
```
export LINODE_API_TOKEN="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
```
