### ISSUE TITLE
wireguard client does not work on ubuntu 18.10

### ISSUE THREAD

**Issue by sepisoad** [trailofbits/algo#1442]
I have setup wire guard client following the documentation on both Ubuntu 18.04 and Ubuntu 18.10, however it does not work on Ubuntu 18.10.

I have installed it this way:

```bash
sudo add-apt-repository ppa:wireguard/wireguard
sudo apt update
sudo apt install wireguard openresolv
```
then installed my config file as follows:

```bash
sudo install -o root -g root -m 600 wg0.conf /etc/wireguard/wg0.conf
sudo systemctl start wg-quick@wg0
sudo systemctl status wg-quick@wg0 # seems to be ok
sudo wg # also seems to be ok
curl ipv4.icanhazip.com # DOES NOT WORK
```

my `wg0.conf` looks like this:

```bash
[Interface]
PrivateKey = kIwLWh2/6DSyHiVz+Of833FMUtpxNe/tz6PbVrmM2ms=
Address = 10.19.49.48/24,fd9d:bc11:4021::48/48
DNS =  1.1.1.1,1.0.0.1,2606:4700:4700::1111,2606:4700:4700::1001 

[Peer]
PublicKey = 1ObT03rfLCw/xdXs5/i9zCZGXKOc1lFS1zypfQITNRU=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = [MY-SERVER-IP]:51820
```

after bringing up wg interface my /etc/resolve.conf looks like this:

```bash
# Generated by resolvconf
nameserver 1.1.1.1
nameserver 1.0.0.1
nameserver 2606:4700:4700::1111
nameserver 2606:4700:4700::1001
```

**Comment by davidemyers** [comment]
Could you be more specific than "does not work"? Is it that DNS lookups are failing? Can you ping `1.1.1.1`?

**Comment by sepisoad** [comment]
no ping does not work

**Comment by davidemyers** [comment]
When you ping a numerical address, DNS should not be involved. Also, when you install `openresolv` then `system-resolved` should be getting bypassed on the client when WireGuard is up. Your `/etc/resolv.conf` looks correct to me.

I assume `ping 1.1.1.1` works when run on the AlgoVPN server itself?

It looks like you have added very many users to `config.cfg`. Double-check to be sure no two clients are using the same WireGuard config file.

**Comment by jackivanov** [comment]
I can't reproduce, it orks well on Ubuntu 18.10. It's related to your specific environment @sepisoad

**Comment by AliAkhtari78** [comment]
I have the same problem,
and I don't know how to fix it.
