### ISSUE TITLE
Unable to ssh into Algo created Linode

### ISSUE THREAD

**Issue by ralphel** [trailofbits/algo#14456]
My linode created by algo doesn't respond to SSH. _ssh root@xx.xx.xx.xxx_ times out, _ssh -F configs/xx.xx.xx.xxx/ssh_config vpn_ reponds with no such file or directory, and any other combination or variation on SSH either fails or starts a debugging instance and fails when it attempts to bind to a port.

Anyone have any wisdom?

**Comment by davidemyers** [comment]
Make sure you're in the directory where you ran `./algo` when you run 
```
ssh -F configs/<server_ip>/ssh_config <hostname>
```

**Comment by ralphel** [comment]
Ive figured it out and its actually a bug that I am going to proceed to report. The node that algo creates causes an issue from the upstream GRUB2 configuration that causes Linux to read disks asynchronously. I was able to fix it by switching to the latest kernel instead of the faulty GRUB2 one.
