### ISSUE TITLE
IPSec does not generate crt and key files

### ISSUE THREAD

**Issue by aligit** [trailofbits/algo#14479]
**The file generator does not generate IPSec files that are referred in documentation**

The files generated for IPSec are p12, conf and secrets. However the documentation is expecting crt and key files. I'm not able to find the password that was immediately displayed after first execution of install.

**To Reproduce**
`python3 -m virtualenv --python="$(command -v python3)" .env &&
  source .env/bin/activate &&
  python3 -m pip install -U pip virtualenv &&
  python3 -m pip install -r requirements.txt`

1. Run the command that generates configuration files for users listed in config.cfg

**Expected behavior**

In addition to user.conf, user.crt and user.key are also generated.

**Full log**
```
Can't find the log file
```

**Comment by davidemyers** [comment]
See #14191 for the correct location of those files.

The CA key password is only displayed one time when Algo completes. If you didn't record it then you won't be able to add or remove users from your AlgoVPN instance.

**Comment by aligit** [comment]
Thank you for your answer. When I was prompted for `Do you want to retain the keys (PKI)?` I pressed no. So I can't use IPSec protocol?

**Comment by davidemyers** [comment]
If you need those files to set up IPsec on Linux it will probably be easiest to deploy a new AlgoVPN.
