### ISSUE TITLE
Any chance of being able to get a CentOS/RHEL (GCE) server up with this?

### ISSUE THREAD

**Issue by lazerl0rd** [trailofbits/algo#1448]
**Describe the solution you'd like**
Ofc some of the notable changes would be the firewalld->iptables switch and SELinux changes.

**Describe alternatives you've considered**
None if you want/require the server to be Enterprise Linux-based.

**Comment by jackivanov** [comment]
Duplicate #227

**Comment by lazerl0rd** [comment]
> Duplicate #227

Ah, yes. My bad.
