### ISSUE TITLE
dns via cname

### ISSUE THREAD

**Issue by mariowitdoek** [trailofbits/algo#14497]
**Describe the bug**

I was following the script and it blocked on my dns name. My dns name is a cname to a dyndns registration.

On my ubuntu 22.04 I had to start the script in the venv with sudo or i halted with error.

**To Reproduce**

road warrior setup on ubuntu 20.02
no user/ssh and no adblocking

Suggestion: split tunnel question (for allowedips)

**Comment by jackivanov** [comment]
It seems like your post is missing a question? Please youse the correct bug report template if that's a bug
