### ISSUE TITLE
AWS chosen region in config.cfg file

### ISSUE THREAD

**Issue by TacetVenator** [trailofbits/algo#14490]
**Why this is useful**
I'm writing a mini-tool to manage the deployments. I started with AWS.

**It would be easier for a tool to use the config file to populate env variables**
Having the region as an environment variable would simplify the subsequent API calls to AWS.

**Possible solution: Finding existing ressources based on name**
Not a good idea. 

**Help adoption**
Helping me with this feature, will motivate me to do a pull request to share the tool I'm building. I will then be able to support multiple Cloud provider if that kind of logic is in place.

**Comment by Bozkurttt** [comment]
> **Why this is useful** I'm writing a mini-tool to manage the deployments. I started with AWS.
> 
> **It would be easier for a tool to use the config file to populate env variables** Having the region as an environment variable would simplify the subsequent API calls to AWS.
> 
> **Possible solution: Finding existing ressources based on name** Not a good idea.
> 
> **Help adoption** Helping me with this feature, will motivate me to do a pull request to share the tool I'm building. I will then be able to support multiple Cloud provider if that kind of logic is in place.

**Comment by jackivanov** [comment]
You can use a region variable 
- https://github.com/trailofbits/algo/blob/master/docs/deploy-from-ansible.md
