### ISSUE TITLE
site2site vpn

### ISSUE THREAD

**Issue by mariowitdoek** [trailofbits/algo#14498]
**Is your feature request related to a problem? Please describe.**
I have tried to setup a site2site vpn (source: https://www.procustodibus.com/blog/2020/12/wireguard-site-to-site-config/) between a vm debian and a pi4 but it did not work :( Probably some installation issues.
The configs from algo worked out of the box :p

**Describe the solution you'd like**
script to instal with eg option siteA, siteb, ...

**Describe alternatives you've considered**
Oh I tried ... from docker to bare metal.
Even the softether vpn with L3 virtual switch (it worked for windows machines, not linux).

**Additional context**
just when I gave up (after one week in my holiday searching to make it work, not a good WAF I can tell you that) i have found algo vpn. Some challenges aside (cfr registered issue) it was click click yes no ... and voilà my wg server was up and running.
It would be a dream to have a site2site config ... because my chromecast 4 does not like filemanagers and custom uploads.

**Comment by jackivanov** [comment]
We don't support site2site
