### ISSUE TITLE
Set DO VPC at minimum Droplet size

### ISSUE THREAD

**Issue by RRBlum** [trailofbits/algo#14505]
The Algo script used to create DO droplets at the minimum droplet size but Digital Ocrean recently added a smaller droplet size.  Droplets can be resized but not sized to a smaller disk size.  Changing the Algo script to create Algo VPN droplets at the minimum size would allow use of VPN's at the minimum charge or resizing droplets to a larger size to meet demand requirements.  Thanks for considering this and for all your hard work over the years.

**Comment by jackivanov** [comment]
s-1vcpu-512mb-10gb has a poor region coverage, I don't want to make it default. You can change the size in [config.cfg](https://github.com/trailofbits/algo/blob/master/config.cfg#L174)
