### ISSUE TITLE
[Amazon AWS EC2] Support more new regions?

### ISSUE THREAD

**Issue by lakaf** [trailofbits/algo#1450]
Currently Algo supports these EC2 regions:

![image](https://user-images.githubusercontent.com/8853814/58440878-73ad2200-80ab-11e9-9aa0-d9af83b21afa.png)

While Amazon had added couple new ones:

![image](https://user-images.githubusercontent.com/8853814/58440885-89224c00-80ab-11e9-9ac9-5f95d2f021bd.png)

**Comment by jackivanov** [comment]
Duplicate https://github.com/trailofbits/algo/issues/1413
