### ISSUE TITLE
Cannot reach my website after installing algo

### ISSUE THREAD

**Issue by 4n1qz5skwv** [trailofbits/algo#14502]
**Describe the bug**

I have ubuntu vps/server from linode. and my server ip is say 123.456.789.000. I have a website running on this server using nginx unit. So If I visit the IP (123.456.789.000), I can see my website. But it's not working after installing algo on this server. I have to put this IP during algo setup and the vpn is working. But now i cannot open the website by visiting the ip

**To Reproduce**

1. host a website on ubuntu vps server using nginx unit.
2. setup algo vpn on same server.
3. visit the server ip to open website

**Expected behavior**

I can visit the website.

**Additional context**

I think some how algo is blocking connection to the ip address from outside world. If i try to curl http://ip from the server, it actually works.

**Comment by TeddyBearSays** [comment]
I have nginx installed on vm and adding 80/433 rule to iptables did work:
```
iptables -I INPUT -p tcp -m tcp --dport 80 -j ACCEPT
iptables -I INPUT -p tcp -m tcp --dport 433 -j ACCEPT
```

**Comment by jackivanov** [comment]
Algo scripts modify the firewall, this is by design. 
- https://github.com/trailofbits/algo/blob/master/docs/deploy-to-ubuntu.md#local-installation

> PLEASE NOTE: Algo is intended for use to create a dedicated VPN server. No uninstallation option is provided. If you install Algo on an existing server any existing services might break. In particular, the firewall rules will be overwritten. See [AlgoVPN and Firewalls](https://github.com/trailofbits/algo/blob/master/docs/firewalls.md) for more information.

**Comment by bkaufx** [comment]
In case anyone sees that and is having trouble, the comment above has the wrong port for SSL.  It should be 443 not 433.  That really messed with me ngl.

You also have to run `netfilter-persistent save` to get it to save across reboot.
