### ISSUE TITLE
Feature Request: Support daisy chaining VPNs.

### ISSUE THREAD

**Issue by MicahZoltu** [trailofbits/algo#1451]
**Is your feature request related to a problem? Please describe.**
I would like to be able to setup multiple Algo VPNs (on multiple machines, in multiple regions, hosted by multiple providers) and daisy chain them so if the edge VPN server is compromised (e.g., wire tap), I am still protected from tracing the connection back to me unless they can tap every node in my chain.

**Describe the solution you'd like**
During Algo configuration, I would like to be able to point it at another instance of Algo running somewhere else and have it chain through that.

**Describe alternatives you've considered**
I2P and Tor, but in those cases I get virtually no performance guarantees.

**Comment by jackivanov** [comment]
Thanks for you interest! AlgoVPN's major goal is to provide privacy, and not anonymity or censorship avoidance. We are not currently interested in implementing something like this, but we may consider it in the future.

**Comment by jackivanov** [comment]
I'm going to close this one. I may once come up with a solution, but it would be a fork of [Algo-ng](https://github.com/trailofbits/algo-ng)

**Comment by OItsMAK** [comment]
Any updates/guides/tips on this?

I'm planning to try and figure out the routing needed, but would definitely appreciate any thoughts.
