### ISSUE TITLE
Suggestions for a whole-browser / just-browser-tab extension / plugin to make a VPN connection to Algo instance?

### ISSUE THREAD

**Issue by theschles** [trailofbits/algo#14534]
**Is your feature request related to a problem? Please describe.**

Hi there,

Sometimes I don’t want my entire computer to behave it’s located at a different IP address.  I see there’s a way to configure a SOCKS proxy — and thus a whole-web-browser.

However I’d like to make it easier by just activating a browser extension that makes the VPN connection…preferably making browser extension VPN connections on per-tab basis even!

**Describe the solution you'd like**

Someone please suggest a browser extension that allows me to configure one or more Algo instances’ VPN details so I could activate that browser extension with a few clicks — and thus that browser … possibly only that browser tab … has the VPN connection

**Describe alternatives you've considered**

Googled a bit, searched this repo’s README.md, searched this repo’s Github Issues…found nothing…

**Additional context**

Thank you for your help!

**Comment by jackivanov** [comment]
Can you elaborate on why SOCKS won't work for you, pelase?

**Comment by theschles** [comment]
> Can you elaborate on why SOCKS won't work for you, please? You can use PAC to route specific sites through the proxy

I'll have to read up on the guide for SOCKS and Algo -- and find out what "PAC" is...
