### ISSUE TITLE
Windows IKEv2 over IPSec doesn't provide a IPv6 connection

### ISSUE THREAD

**Issue by lazerl0rd** [trailofbits/algo#1453]
**Describe the bug**

When connecting via IPSec to the VPN on Windows where my physical network is IPv4 only, I do not end up with a dual-stack connection.

**To Reproduce**

1. ./algo
2. Install .ps1 file for Windows VPN
3. Connect using Settings

**Expected behavior**

A dual-stack connection after routing through the VPN.

**Additional context**

As above, my physical network is IPv4-only. I DO get an IPv6 address using Wireguard on my Android device (kernel-level [rooted] wireguard) and my iPad (iOS wireguard client).

![image](https://user-images.githubusercontent.com/24303423/58499244-a6245100-8177-11e9-8824-08d22b271205.png)

**Comment by jackivanov** [comment]
Windows doesn't add the default route for ipv6. I'll prepare a fix for the powershell script, but for now you can use the following workaround:

`::/0` does'n work for some reason. 
```
Add-VpnConnectionRoute -ConnectionName "<algo connection name>" -DestinationPrefix ::/1
Add-VpnConnectionRoute -ConnectionName "<algo connection name>" -DestinationPrefix 8000::/1
```
Change `<algo connection name>` to your connection name

**Comment by jackivanov** [comment]
@lazerl0rd Does it work for you? https://github.com/trailofbits/algo/pull/1490

**Comment by jackivanov** [comment]
We've decided to deprecate IKEv2 for windows https://github.com/trailofbits/algo/issues/1493

**Comment by lazerl0rd** [comment]
@jackivanov sorry, it does work. Sad to see it’s deprecated as WG for Windows is still a bit buggy in it’s stopping and starting and the Wintun drivers are seemingly causing issues with some unreleased software I’m testing.
