### ISSUE TITLE
Alpine Linux as a local target

### ISSUE THREAD

**Issue by cobbzilla** [trailofbits/algo#14543]
**Is your feature request related to a problem? Please describe.**
When installing using the "local" cloud, there is explicit support for Ubuntu and FreeBSD. Can support for Alpine Linux also be added?

**Describe the solution you'd like**
When installing using the "local" cloud on an Alpine Linux system, it successfully installs AlgoVPN.

**Describe alternatives you've considered**
The Dockerfile in the Algo repo is based on the "python:3-alpine" image, which is promising! But alas a Docker-based install won't work for my use-case; I must install to the host OS.

**Additional context**
One of my later use cases will be to install onto a Raspberry Pi running Alpine Linux, would be great to test on a regular system first before trying on the Rπ.

**Comment by jackivanov** [comment]
We won't be able to support more systems, sorry.
