### ISSUE TITLE
AppArmor dnscrypt-proxy profile - SSL open DENIED

### ISSUE THREAD

**Issue by cokeflash** [trailofbits/algo#1455]
My dnscrypt-proxy AppArmor profile does not work again. 

Now this AppArmor warning appears: 

type=1400 audit(1559204668.183:78): apparmor="DENIED" operation="open" profile="/etc/dnscrypt-proxy/dnscrypt-proxy" name="/usr/local/ssl/certs/ca-certificates.crt" pid=5093 comm="dnscrypt-proxy" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
type=1400 audit(1559204668.183:79): apparmor="DENIED" operation="open" profile="/etc/dnscrypt-proxy/dnscrypt-proxy" name="/usr/local/ssl/certs/" pid=5093 comm="dnscrypt-proxy" requested_mask="r" denied_mask="r" fsuid=0 ouid=0

I have add these lines to my profile but the message appears again and again:

  /usr/local/ssl/certs/ca-certificates.crt r,
  /usr/local/ssl/certs/ r,
  
Which line must I add/edit to get it work?

Please help, thanks!

**Comment by jackivanov** [comment]
The profile provided by Algo works well. Sorry, but we can't help you to build your own custom profile.
