### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by Neustradamus** [trailofbits/algo#14572]
Dear @trailofbits team,

In first, I wish you a Happy New Year!

Have you planned to create a new release?

Last is 1.1 (2019-07-31):
- https://github.com/trailofbits/algo/releases

Can you do a cleaning of branches?
- https://github.com/trailofbits/algo/branches/all

Thanks in advance.

**Comment by uhlhosting** [comment]
It seems slowly this is a dead end project. Just another spark in the pile of github old projects who made big fuss and then left to users to figure out what and how this will end. From what I see here and on discussions its clearly not maintained. And in terms of updates surely stuff for a vpn had to be up to date. Such a pitty. They should at least make a call for maintainers.

**Comment by jackivanov** [comment]
We're no longer following semver. Branch out of master.
