### ISSUE TITLE
Windows IKEv2 help with weak encryption protocols

### ISSUE THREAD

**Issue by KBapna** [trailofbits/algo#14577]
I have read lots of issues regarding IKEv2 policy mismatch error and I get that it is almost impossible to support it currently with strong encryption protocols but I also found that earlier it was supported with weak encryption and I would like to use that if possible. I have tried number of things listed below but cant get it to work. 
1) Added ciphers manually in main.yaml
2) Tried to install algo v1.0 (failed)
3) Multiple fixes on the issues posted here but none of them seem to work with stronger encryption.

If anyone has any idea how to use algo with weak encryption on windows 10/11 please provide the steps.

**Comment by dguido** [comment]
Please use Wireguard on Windows!
