### ISSUE TITLE
BEWARE: NO WAY TO UNINSTALL

### ISSUE THREAD

**Issue by Brandon4466** [trailofbits/algo#14606]
Just a forewarning for all the people that think this is a reasonable solution for a VPN server... There is no way to uninstall, no way to remove anything, and it immediately breaks everything on the server once you install. The solution by the devs is "wipe".

Just a warning.

**Comment by Blackskyliner** [comment]
As stated in the release announcement linked in the very top of the readme it's a system `Designed to be disposable`. So yea its for spinning up a fresh VM, also as implied by the documentation on blog post, and to be disposed of after not needing it anymore.
