### ISSUE TITLE
Chain two Algo VPN servers (different ingress/egress point)?

### ISSUE THREAD

**Issue by kilo6eight** [trailofbits/algo#1461]
I am trying to figure out how to go about chaining two different Algo VPN servers I have so that my ingress point is separate from my egress point. Simply put, 

User --> (ingress) Algo VPN Server Location #1 ---> Algo VPN Server Location #2 (egress) --> internet/website

I also want to ensure that if the ingress server is unable to access egress server that under this scenario no internet should be accessible for any user connected to the VPN chain. 

Anyone have a recommendation on how to do this or what I should be researching to find most straight forward solution?

**Comment by TC1977** [comment]
Is this something like #1047?

**Comment by jackivanov** [comment]
and another answer is https://github.com/trailofbits/algo/issues/1451

**Comment by OItsMAK** [comment]
Any updates/guides/tips on this?

I'm planning to try and figure out the routing needed, but would definitely appreciate any thoughts.

(I'm also following #1451)

**Comment by kilo6eight** [comment]
> Any updates/guides/tips on this?
> 
> I'm planning to try and figure out the routing needed, but would definitely appreciate any thoughts.
> 
> (I'm also following #1451)

Nothing but if you are able to come up with a solution please do share 

Thank you
