### ISSUE TITLE
Add support for MacOS Deployment

### ISSUE THREAD

**Issue by xinwhyi** [trailofbits/algo#14691]
**Is your feature request related to a problem? Please describe.**
I want to deploy the VPN on my spare mac and couldn't do it right now.

**Describe the solution you'd like**
Add support for macOS deployment

**Describe alternatives you've considered**
N/A. I can try to deploy to cloud, but I really want to use my own machine.

**Additional context**
I'd like to try working on this feature request. However, I don't have previous knowledge on OS or networking. Trying to get a sense of whether this is possible? If so, I'd like to learn what subtasks are needed for this feature and what's the anticipated challenges there. Thank you!

**Comment by jackivanov** [comment]
Sorry, the only supported target system is Ubuntu. We don't have plans to support any other systems.
