### ISSUE TITLE
AppArmor bug persists

### ISSUE THREAD

**Issue by CreativeStreet** [trailofbits/algo#14719]
I've used AlgoVPN for years and this is the first time I come across this error. I've tried it with Hetzner and Exoscale and the error still persists. I think the problem is with AppArmor. Does anyone have tips?

failed: [194.xxx.xxx.xx] (item=/usr/lib/ipsec/lookip) => {"ansible_loop_var": "item", "changed": false, "cmd": ["aa-enforce", "/usr/lib/ipsec/lookip"], "delta": "0:00:00.348106", "end": "2024-05-07 20:59:24.107730", "item": "/usr/lib/ipsec/lookip", "msg": "non-zero return code", "rc": 1, "start": "2024-05-07 20:59:23.759624", "stderr": "Traceback (most recent call last):\n  File \"/usr/sbin/aa-enforce\", line 33, in <module>\n    tool.cmd_enforce()\n  File \"/usr/lib/python3/dist-packages/apparmor/tools.py\", line 134, in cmd_enforce\n    for (program, prof_filename, output_name) in self.get_next_for_modechange():\n  File \"/usr/lib/python3/dist-packages/apparmor/tools.py\", line 97, in get_next_for_modechange\n    aaui.UI_Info(_('Profile for %s not found, skipping') % output_name)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: 'NoneType' object is not callable\n\n\nAn unexpected error occurred!\n\nFor details, see /tmp/apparmor-bugreport-ds9b4_es.txt\nPlease consider reporting a bug at https://gitlab.com/apparmor/apparmor/-/issues\nand attach this file.", "stderr_lines": ["Traceback (most recent call last):", "  File \"/usr/sbin/aa-enforce\", line 33, in <module>", "    tool.cmd_enforce()", "  File \"/usr/lib/python3/dist-packages/apparmor/tools.py\", line 134, in cmd_enforce", "    for (program, prof_filename, output_name) in self.get_next_for_modechange():", "  File \"/usr/lib/python3/dist-packages/apparmor/tools.py\", line 97, in get_next_for_modechange", "    aaui.UI_Info(_('Profile for %s not found, skipping') % output_name)", "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^", "TypeError: 'NoneType' object is not callable", "", "", "An unexpected error occurred!", "", "For details, see /tmp/apparmor-bugreport-ds9b4_es.txt", "Please consider reporting a bug at https://gitlab.com/apparmor/apparmor/-/issues", "and attach this file."], "stdout": "", "stdout_lines": []}
ok: [194.xxx.xxx.xx] => (item=/usr/lib/ipsec/stroke)

TASK [include_tasks] ***********************************************************************************************************************************************************************
included: /home/palanca/algo/playbooks/rescue.yml for 194.xxx.xxx.xx

TASK [debug] *******************************************************************************************************************************************************************************
ok: [194.xxx.xxx.xx] => {
    "fail_hint": [
        "Sorry, but something went wrong!",
        "Please check the troubleshooting guide.",
        "https://trailofbits.github.io/algo/troubleshooting.html"
    ]
}

TASK [Fail the installation] ***************************************************************************************************************************************************************
fatal: [194.xxx.xxx.xx]: FAILED! => {"changed": false, "msg": "Failed as requested from task"}

**Comment by jackivanov** [comment]
@CreativeStreet what ubuntu version is this?

**Comment by CreativeStreet** [comment]
> @CreativeStreet what ubuntu version is this?

It's Ubuntu 22.04.4 LTS @jackivanov

**Comment by CreativeStreet** [comment]
For those that are wondering, the issue seems to be incompatibility with Ubuntu 22.04.4 LTS. I downgraded to Ubuntu 22.04 LTS 64-bit and it works fine

**Comment by dantheman0207** [comment]
> For those that are wondering, the issue seems to be incompatibility with Ubuntu 22.04.4 LTS. I downgraded to Ubuntu 22.04 LTS 64-bit and it works fine

I had a similar issue using 24.04 LTS, downgrading to 22.04 LTS fixed it for me.
