### ISSUE TITLE
Authenticity issue with Amazon EC2 cloud setup

### ISSUE THREAD

**Issue by codedmon** [trailofbits/algo#1475]
I am following the Amazon EC2 cloud setup guide [here](https://github.com/trailofbits/algo/blob/master/docs/cloud-amazon-ec2.md).   After choosing the region, the setup continues then gets to 

```
The authenticity of host 'xxxxxxxxx' can't be established.
ECDSA key fingerprint is SHA256:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.
Are you sure you want to continue connecting (yes/no)? fatal: [xxxxxxxxxxx]: FAILED! => {"msg": "Timeout (12s) waiting for privilege escalation prompt: "}
```

Any ideas why this is failing?

**Comment by TC1977** [comment]
Seems like a timeout issue, but not on the ec2 side as in #892. Can you run it again with `./algo -vvv` and post the whole log please?

**Comment by codedmon** [comment]
> Seems like a timeout issue, but not on the ec2 side as in #892. Can you run it again with `./algo -vvv` and post the whole log please?

I ended up choosing "Yes" and it completed the install.   After googling some, it appears to be a normal response the first time you connect to a server with SSH.   To make sure, I logged into the Amazon EC2 dashboard and viewed the 'Instances'.  The "IPv4 Public IP" listed matched the IP address shown in the authenticity message.

Was this the correct thing to do?   Regarding a log, is there a file saved after setup?  I am unable to locate it.

**Comment by TC1977** [comment]
It is indeed a normal question the first time your computer connects to an SSH host, but you shouldn’t have to hit yes or anything - Ansible is supposed to just log in and do its job. 

Since your deploy succeeded, I guess you’re all set. But in the future you should save the output from Terminal (or Putty, or whatever program) in a text file for future reference. Specifically your CA key and p12 password can come in very handy later on.

**Comment by codedmon** [comment]
I did remember several warnings about Ansible.  I just ran ./algo again, here are the warnings.

_userxyz@DESKTOP-T8GIVMD:~/algo$ ./algo
 [WARNING] Ansible is being run in a world writable directory (/home/userxyz/algo), ignoring it as an ansible.cfg source. For more information see https://docs.ansible.com/ansible/devel/reference_appendices/config.html#cfg-in-world-writable-dir
 [WARNING]: Unable to parse /etc/ansible/hosts as an inventory source

 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match
'all'_

**Comment by TC1977** [comment]
What kind of system is this? WSL? I'm pretty sure macOS would have that directory locked down by default.

Anyway, I think that might be the issue, that your ansible.cfg wasn't being read. So if you want to get rid of that error, try changing the directory permissions to something that isn't world-writeable. Something like `chmod 755 ~/algo` (although that might not be ideal). The link in the Ansible docs is here: https://docs.ansible.com/ansible/devel/reference_appendices/config.html#avoiding-security-risks-with-ansible-cfg-in-the-current-directory

**Comment by codedmon** [comment]
> What kind of system is this? WSL? I'm pretty sure macOS would have that directory locked down by default.
> 
> Anyway, I think that might be the issue, that your ansible.cfg wasn't being read. So if you want to get rid of that error, try changing the directory permissions to something that isn't world-writeable. Something like `chmod 755 ~/algo` (although that might not be ideal). The link in the Ansible docs is [here](https://docs.ansible.com/ansible/devel/reference_appendices/config.html#avoiding-security-risks-with-ansible-cfg-in-the-current-directory).
> 
> If you're deploying from Windows, please check the [Windows instructions](https://github.com/trailofbits/algo/blob/master/docs/deploy-from-windows.md) and see if there's anything you've missed.

Appreciate you helping me out.   Yes, I am using a WSL with Ubuntu.  I followed [this guide](https://lifehacker.com/how-to-set-up-your-own-completely-free-vpn-in-the-cloud-1794302432), which has the same commands as the Windows instructions that you linked to.

**Comment by codedmon** [comment]
Also, thanks, the chmod 755 solved the issue.  I just ran algo again to create a new instance and did not have any issues.   Any ideas what may have caused this?  Should WSL set this directory (and other directories) permissions automatically or does the algo install do this?

**Comment by TC1977** [comment]
I don't have answer to either of these questions. I do know that permissions in WSL are [rather complicated](https://devblogs.microsoft.com/commandline/chmod-chown-wsl-improvements/). Enjoy the deployment.
