### ISSUE TITLE
Intermittent missing apt lists on EC2

### ISSUE THREAD

**Issue by defunctio** [trailofbits/algo#148]
### Ansible version
2.2.0.0

### Summary of the problem

```
PLAY [Post-provisioning tasks] *************************************************

TASK [Install prerequisites] ***************************************************
fatal: [54.91.17.10]: FAILED! => {"changed": true, "failed": true, "rc": 100, "stderr": "Warning: Permanently added '54.91.17.10' (ECDSA) to the list of known hosts.\r\nShared connection to 54.91.17.10 closed.\r\n", "stdout": "E: can not open /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial_InRelease - fopen (2: No such file or directory)\r\n", "stdout_lines": ["E: can not open /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_xenial_InRelease - fopen (2: No such file or directory)"]}```

```

### Steps to reproduce the behavior
Deploy Algo on EC2.

### Expected behavior
Deploys.

### Actual behavior
This is an intermittent issue reported by artem, it seems sometimes apt lists do not exist yet during the 'Install prerequisites' stage. My best guess is this could populated/updated by cloud-init populating ec2 apt servers and it becomes a race condition between the prerequisite install and cloud-init.

**Comment by gunph1ld** [comment]
Should be fixed in https://github.com/trailofbits/algo/commit/4419f65b1707251a63d76bbfed3b710c72df9492 and https://github.com/trailofbits/algo/commit/d55878147327df3e8902c2b6e18dd90f92ce7b2b
