### ISSUE TITLE
Apple ID url blocked – 502 bad gateway

### ISSUE THREAD

**Issue by foofoo2** [trailofbits/algo#1483]
Hi,

Algo (with Ad blocking enabled) appears to be blocking the Apple ID Sign In page using a standard steup and config (https://appleid.apple.com/). This results in a  502 Bad gateway page from the Apple server.

Any way to whitelist this page or fix the error?

**Comment by davidemyers** [comment]
It's not Algo, it's Apple blocking your cloud provider. I've found this URL blocked from DigitalOcean and  Vultr, but it works from EC2. This blocking also affects your ability to change your Apple ID settings in the iOS Settings app. It's very inconvenient.

**Comment by foofoo2** [comment]
Thanks for the quick diagnosis. I didn't suspect it would be Apple's end server filtering requests... Any thoughts why they do this? (To help contextualise the issue and offer relavance here).

**Comment by davidemyers** [comment]
Blocking like what Apple's started doing was previously discussed in #803.

My guess is that low-priced cloud providers are attractive to bad actors so some organizations just ban whole ASNs.

I find that I have fewer blocks on EC2, but some sites are blocked from there too (e.g., Lowe's and Houzz).
