### ISSUE TITLE
Cannot install Python dependency

### ISSUE THREAD

**Issue by happycoffeebean** [trailofbits/algo#1486]
I reviewed issue #1160.  I'm having the same issue with a modern Ubuntu based distro, Pop!_OS. 
 
![screen](https://user-images.githubusercontent.com/8798898/59794380-d22e8000-92a6-11e9-8e2f-245a954217f0.jpg)

**Comment by jackivanov** [comment]
python-virtualenv is coming form [the step 3](https://github.com/trailofbits/algo#deploy-the-algo-server), did you follow it?
