### ISSUE TITLE
fails to ask for API token and Location

### ISSUE THREAD

**Issue by tellyolly** [trailofbits/algo#1488]
**Describe the bug**

running macOS 10.14, fails to ask for API token and Location

**To Reproduce**

followed all the steps in the guide, haven't previously created a VPN, after choosing 1 (digital ocean), it skipped crucial next steps

**Expected behavior**

to ask for API token and then location 

**Additional context**

**Full log**

(env) macbook:algo-master admin$ ./algo

PLAY [localhost] ***************************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [Ensure the requirements installed] ***************************************
ok: [localhost]

TASK [Verify Ansible meets Algo VPN requirements.] *****************************
ok: [localhost] => {
    "changed": false, 
    "msg": "All assertions passed"
}

PLAY [Ask user for the input] **************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]
[Cloud prompt]
What provider would you like to use?
    1. DigitalOcean
    2. Amazon Lightsail
    3. Amazon EC2
    4. Vultr
    5. Microsoft Azure
    6. Google Compute Engine
    7. Scaleway
    8. OpenStack (DreamCompute optimised)
    9. Install to existing Ubuntu 18.04 or 19.04 server (Advanced)
  
Enter the number of your desired provider
:

TASK [Cloud prompt] ************************************************************
ok: [localhost]

TASK [Set facts based on the input] ********************************************
ok: [localhost]
[VPN server name prompt]
Name the vpn server
[algo]
:

TASK [VPN server name prompt] **************************************************
ok: [localhost]
[Cellular On Demand prompt]
Do you want macOS/iOS IPsec clients to enable "Connect On Demand" when connected to cellular networks?
[y/N]
:

TASK [Cellular On Demand prompt] ***********************************************
ok: [localhost]
[Wi-Fi On Demand prompt]
Do you want macOS/iOS IPsec clients to enable "Connect On Demand" when connected to Wi-Fi?
[y/N]
:

TASK [Wi-Fi On Demand prompt] **************************************************
ok: [localhost]
[Compatible ciphers prompt]
Do you want the VPN to support Windows 10 or Linux Desktop clients? (enables compatible ciphers and key exchange, less secure)
[y/N]
:

TASK [Compatible ciphers prompt] ***********************************************
ok: [localhost]
[Retain the CA key prompt]
Do you want to retain the CA key? (required to add users in the future, but less secure)
[y/N]
:

TASK [Retain the CA key prompt] ************************************************
ok: [localhost]
[DNS adblocking prompt]
Do you want to enable DNS ad blocking on this VPN server?
[y/N]
:

TASK [DNS adblocking prompt] ***************************************************
ok: [localhost]
[SSH tunneling prompt]
Do you want each user to have their own account for SSH tunneling?
[y/N]
:

TASK [SSH tunneling prompt] ****************************************************
ok: [localhost]

TASK [Set facts based on the input] ********************************************
ok: [localhost]

PLAY [Provision the server] ****************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

--> Please include the following block of text when reporting issues:

Algo running on: Mac OS X 10.14.5
ZIP file created: Jun 19 22:06:32 2019
Python 2.7.10
Runtime variables:
    algo_provider "digitalocean"
    algo_ondemand_cellular "False"
    algo_ondemand_wifi "False"
    algo_ondemand_wifi_exclude "X251bGw="
    algo_windows "False"
    algo_dns_adblocking "False"
    algo_ssh_tunneling "False"
    wireguard_enabled "True"
    dns_encryption "True"

TASK [Display the invocation environment] **************************************
changed: [localhost -> localhost]

TASK [Install the requirements] ************************************************
changed: [localhost -> localhost]

TASK [Generate the SSH private key] ********************************************
changed: [localhost]

TASK [Generate the SSH public key] *********************************************
changed: [localhost]

TASK [cloud-digitalocean : Install requirements] *******************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to find required executable virtualenv in paths: /Users/admin/Desktop/algo-master/env/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"}
included: /Users/admin/Desktop/algo-master/playbooks/rescue.yml for localhost

TASK [debug] *******************************************************************
ok: [localhost] => {
    "fail_hint": [
        "Sorry, but something went wrong!", 
        "Please check the troubleshooting guide.", 
        "https://trailofbits.github.io/algo/troubleshooting.html"
    ]
}

TASK [Fail the installation] ***************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed as requested from task"}

PLAY RECAP *********************************************************************
localhost                  : ok=21   changed=4    unreachable=0    failed=2   

```
PUT THE OUTPUT HERE
```
can someone help me determine the solution, thanks

**Comment by jackivanov** [comment]
`virtualenv` is missing. Did you skip [the 3d step](https://github.com/trailofbits/algo#deploy-the-algo-server)?

**Comment by TC1977** [comment]
Dunno if this has anything to do with it, but you should upgrade your python to the newest version for Mac, version 2.7.16, available [here](https://www.python.org/downloads/mac-osx/).
