### ISSUE TITLE
SSH tunneling setup fails on EC2

### ISSUE THREAD

**Issue by artemdinaburg** [trailofbits/algo#149]
### OS / Environment

MacOS client, EC2 us-east-1 remote

### Ansible version
```
ansible 2.2.0.0
  config file = /Users/artem/git/algo/ansible.cfg
  configured module search path = Default w/o overrides
```

### Summary of the problem

When specifying 'yes' to "Do you want each user to have their own account for SSH tunneling?", the installation fails with:

```
TASK [ssh_tunneling : Change mode for SSH private keys] ************************
failed: [54.152.86.148 -> localhost] (item=artem) => {"failed": true, "item": "artem", "msg": "file (configs/localhost_artem.ssh.pem) is absent, cannot continue", "path": "configs/localhost_artem.ssh.pem", "state": "absent"}

RUNNING HANDLER [security : restart ssh] ***************************************

RUNNING HANDLER [dns_adblocking : restart dnsmasq] *****************************

PLAY RECAP *********************************************************************
54.152.86.148              : ok=84   changed=75   unreachable=0    failed=1
localhost                  : ok=8    changed=2    unreachable=0    failed=0
```

### Steps to reproduce the behavior

Use the EC2 option, and say yes to the "Do you want each user to have their own account for SSH tunneling?" option

### Expected behavior

The installation completes

### Actual behavior
```

TASK [ssh_tunneling : Change mode for SSH private keys] ************************
failed: [54.152.86.148 -> localhost] (item=artem) => {"failed": true, "item": "artem", "msg": "file (configs/localhost_artem.ssh.pem) is absent, cannot continue", "path": "configs/localhost_artem.ssh.pem", "state": "absent"}

RUNNING HANDLER [security : restart ssh] ***************************************

RUNNING HANDLER [dns_adblocking : restart dnsmasq] *****************************

PLAY RECAP *********************************************************************
54.152.86.148              : ok=84   changed=75   unreachable=0    failed=1
localhost                  : ok=8    changed=2    unreachable=0    failed=0
```

# Thoughts

I suspect this is due to the variable `IP_subject_alt_name` being bound to different values for remote actions and local actions in roles/ssh_tunneling/tasks/main.yml (compare line 57 vs line 61)

**Comment by gunph1ld** [comment]
So, do you use remote or local installation? 
Can't reproduce your issue, works well for me both ways.
Ensure that you enter the right public ip address on the step:
`Enter the public IP address of your server: (IMPORTANT! This IP is used to verify the certificate)`

**Comment by gunph1ld** [comment]
@artemdinaburg  Try again and send the full log here, please, if will not work

**Comment by mryraghi** [comment]
Same on DigitalOcean with _yes_ to the "Do you want each user to have their own account for SSH tunneling?" option (if it is the thing that it's causing the error). 
```
TASK [ssh_tunneling : Change mode for SSH private keys] ************************
failed: [<droplet ip> -> localhost] (item=Romeo) => {"failed": true, "item": "Romeo", "msg": "file (configs/localhost_Romeo.ssh.pem) is absent, cannot continue", "path": "configs/localhost_Romeo.ssh.pem", "state": "absent"}
```
I can observe that among other files only ```config/<droplet ip>_Romeo.ssh.pem``` exists, not ```localhost_Romeo.ssh.pem```.

**Comment by gunph1ld** [comment]
@mryraghi send the full log, please, especially of the initial prompts

**Comment by artemdinaburg** [comment]
Attaching log file of failure, just tried with latest master:
[algo.txt](https://github.com/trailofbits/algo/files/647176/algo.txt)

**Comment by artemdinaburg** [comment]
This also fails for me using the GCE provisioner

**Comment by mryraghi** [comment]
Here's the log: https://gist.github.com/mryraghi/828482dc90801225bd634b9f3ce65c1f
