### ISSUE TITLE
WireGuard for Windows is mature enough to start using

### ISSUE THREAD

**Issue by dguido** [trailofbits/algo#1493]
https://www.wireguard.com/install/

We should start to deprecate IKEv2 for Windows. It's always been a user support disaster and it'll cut a few steps out of our setup process (no more PowerShell!).

**Comment by TC1977** [comment]
The next question is if it's time to deprecate IKEv2 entirely and leave it as an advanced option (changing `ipsec_enabled` in `config.cfg` to `false`) or even remove it completely.

**Comment by jackivanov** [comment]
@TC1977 I'm pretty sure there is a lot of apple users who still prefer IKEv2 native clients enabled by default

**Comment by dguido** [comment]
@jackivanov Let's do this soon. We get a lot of new users every year in late July because of Blackhat USA (www.blackhat.com).

**Comment by jackivanov** [comment]
OK, let's release this into 1.1 then

**Comment by jackivanov** [comment]
Moreover it's not in pre-alpha anymore
