### ISSUE TITLE
Limit the privileges of the strongSwan daemon even further

### ISSUE THREAD

**Issue by dguido** [trailofbits/algo#15]
https://github.com/projectatomic/bubblewrap

**Comment by dguido** [comment]
We may be able to get some of these benefits simply by running StrongSwan as a non-root user and then limiting its capabilities only to `cap_net_admin`.

**Comment by Thermi** [comment]
You also need cap_net_raw, if you use connmark. It's required by the iptables library that plugin uses.

**Comment by dguido** [comment]
This is a subtask of #12 , closing it to clean up some issue cruft.
