### ISSUE TITLE
 IPv6 leaking

### ISSUE THREAD

**Issue by siftuser** [trailofbits/algo#1500]
Ipv6leak.com shows ipv4 from the server block, but ipv6 test shows "Looks like your IPv6 is leaking" any help ? Thanks

**Comment by jackivanov** [comment]
What's your OS?

**Comment by TC1977** [comment]
I've seen that site. Keep in mind it's run by a VPN service, which has a vested interest in telling you there's a leak. To confirm they're right, you need to know whether they're showing your actual IPv6, or one that's assigned by your Algo server.

**Comment by siftuser** [comment]
> What's your OS?

OSX, Android

**Comment by davidemyers** [comment]
That site seems bogus to me, too. It tells me IPv6 is leaking but shows my AlgoVPN IPv6 address. When I refresh the page it decides that my IPv6 is not leaking after all.

**Comment by siftuser** [comment]
Thanks all for your help! Verified v6 address shown by ipv6leak does not match with v6 IP of my android. Further ipv6test.google.com shows no issues :)

Sorry for bothering :(
