### ISSUE TITLE
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020

### ISSUE THREAD

**Issue by averasko** [trailofbits/algo#1504]
**Description**

* Installing algo depenencies on fully updated Linux/Ubuntu 18.04 
Linux 4.18.0-25-generic #26~18.04.1-Ubuntu SMP Thu Jun 27 07:28:31 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
yields:

```
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020
```

**To Reproduce**

* get a clean installation of Ubuntu 18.04 with all updates
* follow the instructions at https://github.com/trailofbits/algo to install algo and its dependencies
* at step 4. Install Algo's remaining dependencies, you'll get DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.

**Expected behavior**
* needs to be run on all up-to-date software due to possible security issues; it won't be the case after 01.01.2020

```
python -m virtualenv --python=`which python2` env &&
>     source env/bin/activate &&
>     python -m pip install -U pip virtualenv &&
>     python -m pip install -r requirements.txt
Running virtualenv with interpreter /usr/bin/python2
New python executable in /home/user/workspace/algo/env/bin/python2
Also creating executable in /home/user/workspace/algo/env/bin/python
Installing setuptools, pkg_resources, pip, wheel...
done.
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
```

**Comment by TC1977** [comment]
Duplicate #1371
