### ISSUE TITLE
open certain ports during algo installation?

### ISSUE THREAD

**Issue by crapthings** [trailofbits/algo#1505]
i want to install other service on vps

maybe we can have a config for that purpose?

**Comment by jackivanov** [comment]
Sorry, I don't see any reason in adding this. You may always edit the rules manually before or after the installation

**Comment by dkrutsko** [comment]
Would it be possible to add documentation on how to do this? I would like to open some ports to our internal network for things like [telegraf](https://github.com/influxdata/telegraf) and other software.
