### ISSUE TITLE
Firewall settings get overwritten?

### ISSUE THREAD

**Issue by Thobro** [trailofbits/algo#1509]
Everytime I restart my server the firewall settings are somehow overwritten. After boot I run a port scan and only port 22 is open. Then I run `sudo ufw status` and it returns `disabled`. Which I find strange. I then type `sudo ufw disable`. And only then am I able to connect to my Nginx server that is also hosted on the same machine as Algo. Can I prevent Algo from auto starting at system boot?

**Comment by jackivanov** [comment]
https://github.com/trailofbits/algo/blob/master/docs/firewalls.md
