### ISSUE TITLE
Poor Performance and unresponsiveness when using VPN [Ubuntu 19.04 Server localhost]

### ISSUE THREAD

**Issue by DanysP** [trailofbits/algo#1511]
#### Describe the bug
Algo has been successfully deployed and installed to Windows 10 and iOS 12. However, when 
I connect to the VPN and use it, all clients feel very slow and sluggish when browsing or doing anything internet-related and pages typically take several seconds to load. Pages take a noticeable amount of time to load, and on rare occasions will time out. Running a `tracert` test on google.com in Windows Command Prompt will result in an average hop time of 20-30ms, with one or two hops timing out. 

The server hardware is a Raspberry Pi 3B+, which features a 1.4 GHz onboard CPU and 1GB of system RAM. It's connected by Gigabit Ethernet to my router using a Cat5e cable, and my home's internet speed is 100mbps down/100mbps up with an average ping of 5ms (tested with speedtest.net while not connected). When connected to the VPN Server, speedtest.net reports anywhere from 20-40mbps down/20-40mbps up with an average ping of 5ms, which should be more than enough for responsive browsing. Speedtest.net will also commonly fail to test due to a Latency error (could be timeout).
However, websites and browsing continue to be very slow. So far I've only tested from my home network, so results may vary when testing outside of the network and from further geographical locations.

What could be the cause of this? Is Algo/IKEv2 or any component of it (StrongSwan, WireGuard, etc.) resource heavy, and is being bottlenecked by the CPU or RAM? It is an RPi after all which isn't the most robust system, so that would explain it. 

**To Reproduce**

1. Installed profile onto a relevant device (Windows 10 or iOS 12 with On Demand)
2. Activated VPN profile
3. Began browsing and observed response + user experience

**Expected behavior**

Responsive browsing with little to no lag at all, expected all webpages to load and have no issues with timeouts. 

**Additional context**

Server is using default DNS configuration as defined by the deployment script. DNS-level Ad blocking is not enabled.

-Block of information displayed during Algo not available

**Comment by davidemyers** [comment]
Have you tried WireGuard on iOS?

**Comment by jackivanov** [comment]
Algo is supposed to be a cloud solution, not sure if anyone ever tested it on RPi properly

**Comment by DanysP** [comment]
> Have you tried WireGuard on iOS?

Yes, and I've imported the same profile twice - once by QR code, once by `*.conf`. For whatever reason, the profiles imported into WireGuard don't seem to be set up correctly, as they display the following data:

- Server: `[my DDNS address]:51820`
- Server Address: `127.0.0.1`
- Address: `[auto-generated 10.x.x.x address]`


Whereas if you compare this to the data created by the `*.mobileconfig` profile:

- Server: `[my DDNS address]` (note absence of :51820)
- Server Address: `[my IPv4 public address which my DDNS resolves to]`
- Address: `[auto-generated 10.x.x.x address]`
- Address: `[auto-generated fd9d:x:x:x address]` (note that an IPv6 address did not appear in the WireGuard profiles)

The `*.conf` and QR codes were created at the same time as the `*.mobileconfig`, and all three were extracted from the same location - it seems strange that the different profiles have different configurations. Ports 22/TCP, 500/UDP, 4500/UDP and 51820/UDP have been port forwarded to the Server (RPi) and rules have been made in ufw to allow these ports to accept communications.

While my testing took place, I asked someone outside of the network to connect using an Android device with WireGuard. They could successfully import the profile and connect, but could not load any data and servers timed out. Their connection stats also showed sent data, but no received data, so the VPN doesn't seem to work outside of the local network where the server is deployed for some reason. 







> Algo is supposed to be a cloud solution, not sure if anyone ever tested it on RPi properly

Surely, having the option to install to a local Ubuntu 18.04 or 19.04 server would allow for Algo to be used beyond cloud solutions? I'm by no means an expert, but it would be unusual to have the ability to install to Ubuntu locally if this was not a supported or intended feature.
As far as RPi testing goes, I suppose that makes me a pioneer in a way - paving the road for future Algo+RPi enthusiasts :) Oh well, issues aside - I guess it provides information for future development.

**Comment by davidemyers** [comment]
Are you using `ufw` on the RPi? Do not use any additional firewall package on an Algo VPN. See [here](https://github.com/trailofbits/algo/blob/master/docs/firewalls.md).

Also, some UK ISPs use smaller than typical MTUs. Do you know what the MTU of your ISP connection is?

**Comment by DanysP** [comment]
> Are you using `ufw` on the RPi? Do not use any additional firewall package on an Algo VPN. See [here](https://github.com/trailofbits/algo/blob/master/docs/firewalls.md).
> 
> Also, some UK ISPs use smaller than typical MTUs. Do you know what the MTU of your ISP connection is?

I am indeed using ufw and no other firewall (to my knowledge). By default, it's configured to deny all incoming traffic and to allow all outgoing traffic, unless rules are added. When entering `ufw status`, this is my output:
`WARN: uid is 0 but '/' is owned by 1001`
`Status: active`

`To                         Action      From`
`--                         ------      ----`
`80                         ALLOW       Anywhere`
`443                        ALLOW       Anywhere`
`OpenSSH                    ALLOW       Anywhere`
`22/tcp                     ALLOW       Anywhere`
`500/udp                    ALLOW       Anywhere`
`4500/udp                   ALLOW       Anywhere`
`51820/udp                  ALLOW       Anywhere`
`80 (v6)                    ALLOW       Anywhere (v6)`
`443 (v6)                   ALLOW       Anywhere (v6)`
`OpenSSH (v6)               ALLOW       Anywhere (v6)`
`22/tcp (v6)                ALLOW       Anywhere (v6)`
`500/udp (v6)               ALLOW       Anywhere (v6)`
`4500/udp (v6)              ALLOW       Anywhere (v6)`
`51820/udp (v6)             ALLOW       Anywhere (v6)`

I've allowed all ports relevant to Algo, allong with OpenSSH and the HTTP (80) and HTTPS (443).

**Comment by davidemyers** [comment]
You have broken your AlgoVPN by using `ufw`. Consider reinstallation from scratch, though it might be possible to clear out and disable `ufw` completely.

Algo expects to turn a standard installation of Ubuntu Server into a dedicated VPN server. When you mess around with other firewalls (or disable `systemd-resolved` like before) you're going to have problems.

**Comment by DanysP** [comment]
> You have broken your AlgoVPN by using `ufw`. Consider reinstallation from scratch, though it might be possible to clear out and disable `ufw` completely.
> 
> Algo expects to turn a standard installation of Ubuntu Server into a dedicated VPN server. When you mess around with other firewalls (or disable `systemd-resolved` like before) you're going to have problems.

For what it's worth, I recently added the additional `ufw` rules in an attempt to fix connection outside of LAN after I deployed Algo and created this issue ticket. I'll see if I can reset `ufw` and restore default settings. Most guides suggest configuring `ufw` to deny all incoming traffic and allow all outgoing traffic and then add rules as needed, all of which is done to improve security - should I do this, or leave `ufw` exactly as it is when first intalled?

`systemd-resolved` has remained untouched since I upgraded to Ubuntu 19.04, but good memory.

**Comment by davidemyers** [comment]
`ufw` is great for most Ubuntu deployments, but Algo does its own thing and you need to leave `ufw` disabled as it is on a fresh Ubuntu Server installation.

**Comment by DanysP** [comment]
> `ufw` is great for most Ubuntu deployments, but Algo does its own thing and you need to leave `ufw` disabled as it is on a fresh Ubuntu Server installation.

Okay, I'll keep this in mind. I won't access Algo for today, so I'll try tomorrow and report back about `ufw`. Aside from this, what else could be causing inability to connect outside of LAN?

**Comment by davidemyers** [comment]
If Algo's firewall rules are not in place there's no point in doing further diagnosis. Have a look at [Algo's IPv4 rules template](https://github.com/trailofbits/algo/blob/master/roles/common/templates/rules.v4.j2) to see the kind of functions that are needed for a VPN server to operate. It's much more than just opening ports.
