### ISSUE TITLE
connect from the iphone client without file.mobileconfig

### ISSUE THREAD

**Issue by ddi98** [trailofbits/algo#1513]
hi, if I want to connect to the vpn by entering the connection parameters manually on my iphone (after having installed the certificate.p12, and cacert.pem) the connection is not performed by returning the error that I have attached in the screenshot, if instead I use the file.mobileconfig works all very well .. how come? thank you so much

![IMG_2568](https://user-images.githubusercontent.com/43742625/60963527-5659ad80-a311-11e9-9b4c-da3390b759a9.png)

**Comment by TC1977** [comment]
What is the issue or bug that’s being reported?

**Comment by jackivanov** [comment]
There is no way to create a connection without the mobileconfig file.
