### ISSUE TITLE
is DOH working with algo VPN?

### ISSUE THREAD

**Issue by riyaz** [trailofbits/algo#1514]
**Describe the bug**

OS : macOS Mojave 10.14.5 (18F132)

With Algo's VPN on when I check status of DNS security here https://www.cloudflare.com/ssl/encrypted-sni/ I get below screenshot

<img width="1164" alt="Screenshot 2019-07-10 at 8 12 18 PM" src="https://user-images.githubusercontent.com/22842/60978997-92abfe80-a34f-11e9-8e3b-bee2c0536c4b.png">

**To Reproduce**

1. Connect to Algo vpn server
2. Go to  https://www.cloudflare.com/ssl/encrypted-sni/

**Expected behavior**

Expecting screenshot like below, I got this when I have installed cloudflared locally and configured it as DNS server without connecting to VPN.

<img width="876" alt="Screenshot 2019-07-10 at 8 17 53 PM" src="https://user-images.githubusercontent.com/22842/60979385-431a0280-a350-11e9-9d0a-5090ce15f2b7.png">

**Additional context**

I have even tried to setup local dns in wireguard app still getting not secure.

**Comment by TC1977** [comment]
So, when I connect via Wireguard to my VPN and check that page with Safari I get the expected results.

![Screen Shot 2019-07-10 at 6 43 07 PM](https://user-images.githubusercontent.com/37350377/61010023-bcaaf400-a342-11e9-9e3d-80e9dfcb7eb4.png)

**Comment by Omoeba** [comment]
For me the DNSSEC test timed out. I am using Chrome on Windows 10.

**Comment by TC1977** [comment]
The OP was using macOS Mojave on IKEv2 and Wireguard. We need more info, as far as install details (cloud provider, options, download date, etc.) I get the expected results with macOS Mojave or iOS 12.3.1, Wireguard or IKEv2.
