### ISSUE TITLE
The error was: 'p12_export_password' is undefined

### ISSUE THREAD

**Issue by willjgit** [trailofbits/algo#1515]
I get the following error when running ansible playbook:

TASK [debug] *******************************************************************
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'p12_export_password' is undefined\n\nThe error appears to have been in '/home/mark/algo/server.yml': line 83, column 11, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n        - debug:\n          ^ here\n"}

1. Fresh VM Ubuntu 18.04 LTS
2. Install all dependencies
3. Running a manual ansible-playbook with just tags -t wireguard,dns_adblocking

**Comment by jackivanov** [comment]
tag `common` should be specified as well.

**Comment by willjgit** [comment]
How do you use variables to just install wireguard (not the strongswan alt vpn)? Can't figure out what to pass through reading the docs in ansible -- seems like role tags are the only way to install just wirguard?

**Comment by willjgit** [comment]
> We don't really advice to use tags, use the [variables](https://github.com/trailofbits/algo/blob/master/docs/deploy-from-ansible.md#variables) instead.

How do you use variables to just install wireguard (not the strongswan alt vpn)? Can't figure out what to pass through reading the docs in ansible -- seems like role tags are the only way to install just wirguard?

**Comment by TC1977** [comment]
Try passing through the variable `ipsec_enabled=false`.

**Comment by jackivanov** [comment]
@willjgit You can find it in [config.cfg](https://github.com/trailofbits/algo/blob/master/config.cfg#L25)
