### ISSUE TITLE
Local network blocked upon connection

### ISSUE THREAD

**Issue by mvniekerk** [trailofbits/algo#1516]
### Steps
1. Set up a VPN on a VPS using the existing Ubuntu option. Changes to config.yml:
- Own users
- BetweenClients_DROP: false
2. Manual IPSec set up client side (Ubuntu 18.04)
- Can connect to the VPN
- Can do client **->** client + server **->** client comms

### Expected result:
1. Can do client local network **->** client comms when connected to the VPN
2. Can do client **->** local network comms when connected to the VPN

### Actual result:
1. No connection (times out)
2. No connection (times out)

**Comment by davidemyers** [comment]
Do you have a section in your client `/etc/ipsec.conf` like the `conn lan-passthrough` example shown [here](https://github.com/trailofbits/algo#linux-strongswan-clients-eg-openwrt-ubuntu-server-etc)?

**Comment by mvniekerk** [comment]
Added that section, it is working now.
Thank you.
