### ISSUE TITLE
support generating of iOS profiles (.mobileconfig) for WireGuard

### ISSUE THREAD

**Issue by boschkundendienst** [trailofbits/algo#1517]
**Is your feature request related to a problem? Please describe.**
As stated in [Installing WireGuard tunnels using Configuration Profiles](https://github.com/WireGuard/wireguard-apple/blob/master/MOBILECONFIG.md) WireGuard also supports Apple Profiles (.mobileconfig).

**Describe the solution you'd like**
Algo should also generate .mobileconfig for WireGuard. This would make profile distribution (eg. via Enterprise Mobile Devicemanagement) possible and easy.

Thanks for the good work!

**Comment by jackivanov** [comment]
> Configurations added via .mobileconfig will not be migrated into keychain until the WireGuard application is opened once.

Might be an insecure solution. As @zx2c4 noted, iOS may leave around a copy of the original config.
