### ISSUE TITLE
Loss of internet connection when switching from extender to main router and vice-versa

### ISSUE THREAD

**Issue by Omoeba** [trailofbits/algo#1522]
**Describe the bug**

No internet access and latest handshake timer going up when using WireGuard 

**To Reproduce**

1. Add more users in config.cfg and enable auto reboot
2. Disable IPSec in config.cfg
3. Run ./algo
4. Choose digitalocean as the cloud provider
5. Enable ad blocking and disable SSH tunneling
6. Choose SFO2 as the region
7. Import the generated configuration file to IPhone XR
8. Turn on on-demand for both Wi-Fi and cellular
9. Switch from extender network with same SSID and channel as the main router

**Expected behavior**

Internet access

**Additional context**

Persistent-keepalive is not enabled

**Comment by davidemyers** [comment]
This could be a WireGuard client bug rather than a problem with Algo.

Have you tried using a different SSID for the extender network?

Using the same channel for the main and extender networks seems like an error to me.

**Comment by Omoeba** [comment]
It is one of those netgear mesh extenders that automatically match the existing network. I already tried changing the SSID.

**Comment by davidemyers** [comment]
Is it the kind of extender that gives the client a different IP address than the main network?

If you turn off the VPN on the client (and let On Demand turn it right back on) does the connection start working again?

These questions are just out of curiosity, I don't actually have an idea of what the problem is.

**Comment by Omoeba** [comment]
the extender I use is this https://www.netgear.com/home/products/networking/wifi-range-extenders/EX8000.aspx. Turning it off fixes the problem.

**Comment by davidemyers** [comment]
I suggest reporting the problem to the WireGuard Team. Here's what I would do:

* Make note of the time. Reboot the phone in range of the main router. Verify connectivity.

* Move the phone into range of the extender. Verify loss of connectivity.

* In the WireGuard app, save the log file. Edit the file to remove everything before the most recent reboot.

* Mail the log and a detailed description of the problem and your network configuration to team@wireguard.com.

**Comment by Omoeba** [comment]
I reported the bug to wireguard and went back to using IKEv2 on IOS for the time being.
