### ISSUE TITLE
Failure to connect

### ISSUE THREAD

**Issue by shadowsaw** [trailofbits/algo#1523]
![image](https://user-images.githubusercontent.com/53093421/61552337-9551d680-aa68-11e9-969e-25e584468ed7.png)
What am I missing out here? Please help I have tried several times.  The template seems to have completed perfectly fine on AWS, but it always ends with this error.

**FULL Log**
noelsam14@DESKTOP-FQ25G3T:~/algo$ ./algo
 [WARNING] Ansible is being run in a world writable directory (/home/noelsam14/algo), ignoring it as an ansible.cfg source. For more information see https://docs.ansible.com/ansible/devel/reference_appendices/config.html#cfg-in-world-writable-dir
 [WARNING]: Unable to parse /etc/ansible/hosts as an inventory source

 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match
'all'

PLAY [localhost] *******************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************
ok: [localhost]

TASK [Ensure the requirements installed] *******************************************************************************
ok: [localhost]

TASK [Verify Ansible meets Algo VPN requirements.] *********************************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

PLAY [Ask user for the input] ******************************************************************************************

TASK [Gathering Facts] *************************************************************************************************
ok: [localhost]

TASK [Cloud prompt] ****************************************************************************************************
[Cloud prompt]
What provider would you like to use?
    1. DigitalOcean
    2. Amazon Lightsail
    3. Amazon EC2
    4. Vultr
    5. Microsoft Azure
    6. Google Compute Engine
    7. Scaleway
    8. OpenStack (DreamCompute optimised)
    9. Install to existing Ubuntu 18.04 or 19.04 server (Advanced)

Enter the number of your desired provider
:
ok: [localhost]

TASK [Set facts based on the input] ************************************************************************************
ok: [localhost]

TASK [VPN server name prompt] ******************************************************************************************
[VPN server name prompt]
Name the vpn server
[algo]
:
ok: [localhost]

TASK [Cellular On Demand prompt] ***************************************************************************************
[Cellular On Demand prompt]
Do you want macOS/iOS IPsec clients to enable "Connect On Demand" when connected to cellular networks?
[y/N]
:
ok: [localhost]

TASK [Wi-Fi On Demand prompt] ******************************************************************************************
[Wi-Fi On Demand prompt]
Do you want macOS/iOS IPsec clients to enable "Connect On Demand" when connected to Wi-Fi?
[y/N]
:
ok: [localhost]

TASK [Trusted Wi-Fi networks prompt] ***********************************************************************************
skipping: [localhost]

TASK [Compatible ciphers prompt] ***************************************************************************************
[Compatible ciphers prompt]
Do you want the VPN to support Windows 10 or Linux Desktop clients? (enables compatible ciphers and key exchange, less secure)
[y/N]
:
ok: [localhost]

TASK [Retain the PKI prompt] *******************************************************************************************
[Retain the PKI prompt]
Do you want to retain the keys (PKI)? (required to add users in the future, but less secure)
[y/N]
:
ok: [localhost]

TASK [DNS adblocking prompt] *******************************************************************************************
[DNS adblocking prompt]
Do you want to enable DNS ad blocking on this VPN server?
[y/N]
:
ok: [localhost]

TASK [SSH tunneling prompt] ********************************************************************************************
[SSH tunneling prompt]
Do you want each user to have their own account for SSH tunneling?
[y/N]
:
ok: [localhost]

TASK [Set facts based on the input] ************************************************************************************
ok: [localhost]

PLAY [Provision the server] ********************************************************************************************

TASK [Gathering Facts] *************************************************************************************************
ok: [localhost]

TASK [Display the invocation environment] ******************************************************************************

--> Please include the following block of text when reporting issues:

Algo running on: Ubuntu 18.04.2 LTS (Virtualized: wsl)
Created from git fork. Last commit: 37e4f46 Update deploy-from-ansible.md (#1518)
Python 2.7.15+
Runtime variables:
    algo_provider "ec2"
    algo_ondemand_cellular "False"
    algo_ondemand_wifi "False"
    algo_ondemand_wifi_exclude "X251bGw="
    algo_windows "True"
    algo_dns_adblocking "True"
    algo_ssh_tunneling "True"
    wireguard_enabled "True"
    dns_encryption "True"
changed: [localhost -> localhost]

TASK [Install the requirements] ****************************************************************************************
ok: [localhost -> localhost]

TASK [Generate the SSH private key] ************************************************************************************
ok: [localhost]

TASK [Generate the SSH public key] *************************************************************************************
ok: [localhost]

TASK [Include a provisioning role] *************************************************************************************

TASK [cloud-ec2 : Clean up the environment] ****************************************************************************
skipping: [localhost]

TASK [cloud-ec2 : Install requirements] ********************************************************************************
ok: [localhost]

TASK [cloud-ec2 : pause] ***********************************************************************************************
[cloud-ec2 : pause]
Enter your aws_access_key (http://docs.aws.amazon.com/general/latest/gr/managing-aws-access-keys.html)
Note: Make sure to use an IAM user with an acceptable policy attached (see https://github.com/trailofbits/algo/blob/master/docs/deploy-from-ansible.md)
 (output is hidden):
ok: [localhost]

TASK [cloud-ec2 : pause] ***********************************************************************************************
[cloud-ec2 : pause]
Enter your aws_secret_key (http://docs.aws.amazon.com/general/latest/gr/managing-aws-access-keys.html)
 (output is hidden):
ok: [localhost]

TASK [cloud-ec2 : set_fact] ********************************************************************************************
ok: [localhost]

TASK [cloud-ec2 : Get regions] *****************************************************************************************
ok: [localhost]

TASK [cloud-ec2 : Set facts about the regions] *************************************************************************
ok: [localhost]

TASK [cloud-ec2 : Set the default region] ******************************************************************************
ok: [localhost]

TASK [cloud-ec2 : pause] ***********************************************************************************************
[cloud-ec2 : pause]
What region should the server be located in?
(https://docs.aws.amazon.com/general/latest/gr/rande.html#ec2_region)
    1. ap-northeast-1
    2. ap-northeast-2
    3. ap-south-1
    4. ap-southeast-1
    5. ap-southeast-2
    6. ca-central-1
    7. eu-central-1
    8. eu-north-1
    9. eu-west-1
    10. eu-west-2
    11. eu-west-3
    12. sa-east-1
    13. us-east-1
    14. us-east-2
    15. us-west-1
    16. us-west-2

Enter the number of your desired region
[13]
:
ok: [localhost]

TASK [cloud-ec2 : Set algo_region and stack_name facts] ****************************************************************
ok: [localhost]

TASK [cloud-ec2 : Get existing available Elastic IPs] ******************************************************************
skipping: [localhost]

TASK [cloud-ec2 : set_fact] ********************************************************************************************
skipping: [localhost]

TASK [cloud-ec2 : pause] ***********************************************************************************************
skipping: [localhost]

TASK [cloud-ec2 : set_fact] ********************************************************************************************
skipping: [localhost]

TASK [cloud-ec2 : Locate official AMI for region] **********************************************************************
ok: [localhost]

TASK [cloud-ec2 : Check if the encrypted image already exist] **********************************************************
skipping: [localhost]

TASK [cloud-ec2 : Copy to an encrypted image] **************************************************************************
skipping: [localhost]

TASK [cloud-ec2 : Set the ami id as a fact] ****************************************************************************
ok: [localhost]

TASK [cloud-ec2 : Deploy the template] *********************************************************************************
changed: [localhost]

TASK [cloud-ec2 : set_fact] ********************************************************************************************
ok: [localhost]

TASK [Set subjectAltName as afact] *************************************************************************************
ok: [localhost]

TASK [Add the server to an inventory group] ****************************************************************************
changed: [localhost]

TASK [Additional variables for the server] *****************************************************************************
changed: [localhost]

TASK [Wait until SSH becomes ready...] *********************************************************************************
ok: [localhost]

TASK [MacOS | set OS specific facts] ***********************************************************************************
skipping: [localhost]

TASK [MacOS | mount a ram disk] ****************************************************************************************
skipping: [localhost]

TASK [Linux | set OS specific facts] ***********************************************************************************
skipping: [localhost]

TASK [Set config paths as facts] ***************************************************************************************
skipping: [localhost]

TASK [Update config paths] *********************************************************************************************
skipping: [localhost]

TASK [debug] ***********************************************************************************************************
ok: [localhost] => {
    "IP_subject_alt_name": "15.188.17.98"
}

TASK [A short pause, in order to be sure the instance is ready] ********************************************************
Pausing for 20 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)
ok: [localhost]

PLAY [Configure the server and install required software] **************************************************************

TASK [common : Check the system] ***************************************************************************************
The authenticity of host '15.188.17.98 (15.188.17.98)' can't be established.
ECDSA key fingerprint is SHA256:yYPpmbSP7jjiyvujoFuR4ZONJ8xxzQ6loEgOaYnHBJk.
Are you sure you want to continue connecting (yes/no)? yes
fatal: [15.188.17.98]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: Permanently added '15.188.17.98' (ECDSA) to the list of known hosts.\r\nubuntu@15.188.17.98: Permission denied (publickey).", "unreachable": true}
        to retry, use: --limit @/home/noelsam14/algo/main.retry

PLAY RECAP *************************************************************************************************************
15.188.17.98               : ok=0    changed=0    unreachable=1    failed=0
localhost                  : ok=38   changed=4    unreachable=0    failed=0

**Comment by davidemyers** [comment]
WSL seems to have strange issues with file and directory permissions. This issue sounds a lot like #1475.

You might be able to get going again by running these commands while in the `algo` directory (on the other hand these might not be enough to fix everything):

`chmod 700 ~/.ssh`
`chmod 755 .`
`chmod 600 configs/algo.pem`

**Comment by shadowsaw** [comment]
That seems to have fixed it. Thanks a lot! I think this needs to be added in permanently to the windows installation guide. 
A quick question.... Do we expect speeds of less than 1mbps using the free tier in AWS? Cos it seems like that's the best I get on any device. It worked fast for the first 5 mins after installation but then, has been stalling since then.
I tried running Algo on a different server but the end results are the same.

**Comment by TC1977** [comment]
@shadowsaw AWS has much higher speeds, often in the 100Mbps-plus range. Try installing speedtest-cli onto your Algo server to see the speeds there, and then try to narrow it down from there.
