### ISSUE TITLE
cloud_providers.ec2.image is not honoured when encrypted image already exists

### ISSUE THREAD

**Issue by dne** [trailofbits/algo#1528]
A change of EC2 image is not respected if an existing encrypted image already exists in your AWS account.

**To Reproduce**

1. Enable `cloud_providers.ec2.encrypted`
2. Deploy Algo on EC2 with default Ubuntu image (ubuntu-disco-19.04)
3. Change image to "ubuntu-bionic-18.04"
4. Deploy Algo on EC2 again

**Expected behavior**

The first Algo instance running Ubuntu 19.04, and the second one running Ubuntu 18.04. Instead you end up with two instances running 19.04.

**Proposed solution**

Tag the encrypted image with the source image's name (and owner?), and add that to the filter in the "Check if the encrypted image already exist" task.

**Comment by jackivanov** [comment]
Thanks for reporting @dne! Can you try this PR out, please? #1530

**Comment by dne** [comment]
> Thanks for reporting @dne! Can you try this PR out, please? #1530

Really sorry for not being more helpful – currently vacationing (and using Algo of course!)…

#1530 LGTM though.
