### ISSUE TITLE
Extremely high latency

### ISSUE THREAD

**Issue by shadowsaw** [trailofbits/algo#1529]
**Describe the bug**
Extremely high latency (Almost 5-10 seconds). No matter which server I choose. 

**To Reproduce**
Can reproduce the issue on Wireguard on Android, Wireguard on iOS, on windows after running the .ps1 script.

1. Successfully deploy Algo in **_any_** AWS region.
2. Install on iOS or Android using import with QR code. Or install on windows by running the .ps1 script.
3. Try to browse anything at all.

**Expected behavior**
Low latency smooth browsing from one website to another.

**Additional context**

- I'm not sure if the issue is due to DNS delays, because the webpage loads in a flash after the period of 5-10 seconds of latency.

- Once inside a website (subdomain), browsing within the same subdomain **at times** is lag free but again, is inconsistent and difficult to reproduce.

**Comment by davidemyers** [comment]
Do you observe this behavior when your clients are on different networks (e.g., both Home Wi-Fi and LTE)?

What kind of response times do you see when using `ping`, consistent or wildly varying? Is there packet loss? (I assume Windows has `ping`?)

Have you changed anything in `config.cfg` other than adding users?

**Comment by shadowsaw** [comment]
Hey @davidemyers I think I figured the issue. It seems like changing the MTU settings on my router manually to a lower value (1350) seems to have done the trick.

**Comment by davidemyers** [comment]
I am very jealous of that 1.1 ms RTT. :smiley:
