### ISSUE TITLE
SSH port change issues

### ISSUE THREAD

**Issue by calgaryy** [trailofbits/algo#1531]
Hi there, 

I try to change the port for SSH by first adding the input rule in iptables then adding it to my security group before restarting the ssh service after editing sshd_config. 

Following this, I continue to get connection refused and the only traffic back to my machine is a TCP reset.

Have I missed something?

**Comment by jackivanov** [comment]
Hello,

It's a general linux question and not related to Algo specifically. You may try to ask on [gitter](https://gitter.im/trailofbits/algo) or another linux community.

Thanks!
