### ISSUE TITLE
Restarting a stopped Algo instance with a new Elastic/public IP

### ISSUE THREAD

**Issue by shadowsaw** [trailofbits/algo#1532]
A Hypothetical situation: someone is running multiple Algo VPN servers in various AWS regions. In order to lower costs, they decide to stop a few instances. However since each instance of Algo is associated with an Elastic IP, it will be charged at $.005/hr as long as the instance is stopped. 
Is there a way to disassociate an Elastic IP from an algo instance and later reassign a new public/Elastic IP and get it running again? What changes would have to be made in the config files in order to be able to manually set up the client devices with respect to the new server IP?

**Describe the solution you'd like**
1. If it is possible and feasible to achieve what I asked.
2. If yes, detailed steps would benefit others as well.

**Describe alternatives you've considered**
Deleting each stack and starting over with a new one each time. If there's a way to save 10 mins setting up new Algo servers each time, it would be nice.

**Comment by shadowsaw** [comment]
#485

**Comment by TC1977** [comment]
See my comments there. If you wanted to associate the elastic IP with a different server, and then bring it back when you restart the Algo server, that would work. There's probably a way of assigning a new elastic IP and somehow getting the server to work with new certificates, but you'd have to redistribute config files or QR codes to all clients which will take a lot longer than 10 minutes.

If you find that the installs are taking too long, try [running the cloud-init script at startup](https://github.com/trailofbits/algo/blob/master/docs/deploy-from-script-or-cloud-init-to-localhost.md), or try your hand at the [non interactive Ansible deploy commands](https://github.com/trailofbits/algo/blob/master/docs/deploy-from-ansible.md). I know the DO cloud-init deploy was extremely fast - like 4 minutes?

**Comment by shadowsaw** [comment]
Thanks!! I'll try that.

**Comment by jackivanov** [comment]
I think, the best way is to create a domain, and enter it when also asks for the endpoint to use.  Although it might be a bit tricky for IPsec, because it's currently not possible to specify a domain for a cloud installation, so you need to use the local deployment with a floating IP attached to the server. Then, when you decide to start your instance again, and allocate a new floating IP, you just point that domain name to that new floating IP and without hassle with the certificates continue using WireGuard.
