### ISSUE TITLE
Unable to locate  package python-pip

### ISSUE THREAD

**Issue by clearclarencs** [trailofbits/algo#1533]
During step 3 on Ubuntu 18.04.2 it produces the following errors:

Package python-virtualenv is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Unable to locate package python-pip
E: Package 'python-virtualenv' has no installation candidate

This is what i entered:

ubuntu@ubuntu:~/Downloads/algo-master$ sudo apt-get update && sudo apt-get install \
>     build-essential \
>     libssl-dev \
>     libffi-dev \
>     python-dev \
>     python-pip \
>     python-setuptools \
>     python-virtualenv -y

![final](https://user-images.githubusercontent.com/53274728/61820549-bdfd1600-ae44-11e9-88e6-ec84007da7fb.png)

**Comment by jackivanov** [comment]
Probably you faced a known ubuntu [bug](https://bugs.launchpad.net/subiquity/+bug/1783129). The universe repository should be enabled in /etc/apt/sources.list.  Run `sudo add-apt-repository universe` or add it manually
