### ISSUE TITLE
ALgo installation , losing SSH accesss

### ISSUE THREAD

**Issue by alexferguson1** [trailofbits/algo#1534]
hello , guys , I m new to linux , and Algo ,I have two probles:first:
 I install it , but every time I install the ALgo , I lose my access to my vps via the ssh , and I have to ask the vps provider to give me console access to reset to the defaults , 
second: when they give reset the vps to the default they change something in the network  , that makes problesm and I cant update the users , etc.

any help? 

regards

**Comment by alexferguson1** [comment]
FOr user update I see this error :

failed: [localhost -> localhost] (item=None) => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
failed: [localhost -> localhost] (item=None) => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
fatal: [localhost]: FAILED! => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
, :(

**Comment by davidemyers** [comment]
It would help if you would post everything output to the terminal when you ran `./algo` to create your server.

**Comment by jackivanov** [comment]
Use the cloud deployment, please. The local one is for advanced users. If the problem still persists file a new issue with all the information attached. Thanks!
