### ISSUE TITLE
Fails at "[wireguard : Generate public keys]" task on aws

### ISSUE THREAD

**Issue by mrphs** [trailofbits/algo#1535]
**Describe the bug**

Algo fails at `[wireguard : Generate public keys]` task on aws with the following message:

`FAILED! => {"msg": "Unexpected templating type error occurred on (set -o pipefail\n echo \"{{ lookup('file', wireguard_pki_path + '/private/' + item) }}\" |\n wg pubkey): coercing to Unicode: need string or buffer, int found"}`

**To Reproduce**

1. Run algo with aws variables:

```
./algo -e "server_name=$server_name
                 dns_adblocking=true
                 ssh_tunneling=true
                 region=us-east-1
                 aws_secret_key=$secret_key
                 aws_access_key=$access_key"
```

2. Pick Amazon EC2 as the cloud provider
3. Watch it fail at `TASK [wireguard : Generate public keys]`

**Expected behavior**

Wireguard should generate public key and algo should move on to the next task

**Comment by davidemyers** [comment]
Could this be the issue with user names discussed in #1435?

**Comment by mrphs** [comment]
@davidemyers ah I do indeed have numbers in my usernames
