### ISSUE TITLE
Error on setting up Algo's remaining dependencies

### ISSUE THREAD

**Issue by hiricx** [trailofbits/algo#1537]
Hi there

So i was trying to install the Algo's remaining dependencies, and got an error, seems that "requirement.txt" does not exist?  Setting up on Azure VM. Ubuntu 18.04 LTS.

Any solutions? Thanks for any help.

Best,

------

rick@venus:~# python -m virtualenv --python=`which python2` env &&
>     source env/bin/activate &&
>     python -m pip install -U pip virtualenv &&
>     python -m pip install -r requirements.txt
Running virtualenv with interpreter /usr/bin/python2
New python executable in /root/env/bin/python2
Also creating executable in /root/env/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Requirement already up-to-date: pip in ./env/lib/python2.7/site-packages (19.2.1)
Collecting virtualenv
  Downloading https://files.pythonhosted.org/packages/db/9e/df208b2baad146fe3fbe750eacadd6e49bcf2f2c3c1117b7192a7b28aec4/virtualenv-16.7.2-py2.py3-none-any.whl (3.3MB)
     |████████████████████████████████| 3.3MB 32.1MB/s 
Installing collected packages: virtualenv
Successfully installed virtualenv-16.7.2
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

**Comment by hiricx** [comment]
Problem solved.

**Comment by hylimR** [comment]
Hi @hiricx , mind sharing what's the solution?

**Comment by hiricx** [comment]
Hi there

Make sure you enter where you install algo first then try to install all the other dependencies. E.g. cd /algo

Hope this helps,

2019年8月8日 +0800 23:56 Lim Hong Yun <notifications@github.com>，写道：
