### ISSUE TITLE
Can't run ./algo, Abort trap: 6

### ISSUE THREAD

**Issue by michaelst** [trailofbits/algo#1539]
I went through all of the steps listed and when I run `./algo` I get this error

```
./algo: line 23: 39148 Abort trap: 6           ansible-playbook ${PLAYBOOK} "${ARGS[@]}"
```

I am running the Mac Catalina beta so I'm not sure if it might have something to do with that.

**Comment by TC1977** [comment]
This just came up on [Gitter chat](https://gitter.im/trailofbits/algo) yesterday. Yes, it's the beta. Go back to Mojave and see what happens.

**Comment by michaelst** [comment]
Yep it works fine on Mojave

**Comment by TC1977** [comment]
Total guess, but I wonder if it's related to the [upcoming deprecation of python2.7 in macOS 10.15](https://www.macobserver.com/analysis/macos-catalina-deprecates-unix-scripting-languages/) and its overall EOL as in #1371.

**Comment by dguido** [comment]
I guess it’s time to update Ansible so we can use Python3.

**Comment by ZTfer** [comment]
same here...

macOS Catalina doesn't work.....

**Comment by jackivanov** [comment]
@ZTfer Can you check out this PR #1549, please?

**Comment by kiratp** [comment]
#1549 is merged to master but still running into failures on Catalina:

`
TASK [cloud-gce : Install requirements] *****************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "/Users/kiratpandya/code/github/algo/configs/.venvs/gce/bin/pip install -U apache-libcloud pycrypto", "msg": "\n:stderr: dyld: Library not loaded: @executable_path/../.Python\n  Referenced from: /Users/kiratpandya/code/github/algo/configs/.venvs/gce/bin/python2.7\n  Reason: image not found\n"}
`

**Comment by davidemyers** [comment]
@kiratp It looks like you're using a copy of Algo that was previously initialized for Python 2. Try downloading a new copy of Algo and use the updated instructions in the README to initialize it for Python 3.

**Comment by kiratp** [comment]
@davidemyers - Yup - that was the issue.

I just ran a git pull on my working copy and got no complaints from git. Looks like there may be state left behind from previous runs.

Anyway - confirming that everything runs OK on Catalina.
