### ISSUE TITLE
Role unit testing

### ISSUE THREAD

**Issue by defunctio** [trailofbits/algo#154]
A good point brought up by @artemdinaburg is it really would be nice to have some automated testing to ensure no breaking changes are introduced into master.

While provider cloud infrastructure deployment roles might be a bit more finicky to implement tests for, we should at least look at doing unit testing for core functionality to start with. I'd recommend [Test Kitchen](http://kitchen.ci), while the original design is for Chef it not tool agnostic and works with Ansible just as well. Eventually roll this into CI and slap 100 badges/shields on our github page so we be like the cool kids.

Open to other suggestions if anyone has any.

**Comment by dguido** [comment]
There's a $250 bounty on role unit tests for the core functionality as described above. We've run into lots of minor issues that this kind of testing would have caught, so this would be a big improvement for the project. Submit a pull request and email dan@trailofbits.com to claim it.

**Comment by defunctio** [comment]
@gunph1ld any status updates on this?

**Comment by gunph1ld** [comment]
Test kitchen is overhead for our way. We can use jenkins

**Comment by dguido** [comment]
I don't want to setup infrastructure for this. If we can use a cloud service like Test Kitchen, then let's do it.

**Comment by dguido** [comment]
These look fairly similar. It looks like either way we will probably have to build the server inside a docker container on either Travis-CI or Semaphore.

https://semaphoreci.com/community/tutorials/testing-ansible-roles-with-semaphore
https://www.ansible.com/blog/testing-ansible-roles-with-docker

**Comment by dguido** [comment]
This is great! We can consider this issue closed for now.
