### ISSUE TITLE
Multicast traffic to VPN clients?

### ISSUE THREAD

**Issue by JamesBedwell** [trailofbits/algo#1540]
I have set up AlgoVPN and on a virtual server in my LAN, and I have modified the strongswan / ipsec files to to provide myself with “Roadwarrior” access to my LAN.

I have Bonjour/mDNS services running within my LAN that I’d like to make available to my VPN clients, but currently I can not see them.

Does anyone have suggestions for how to enable this?
I’ve heard of avahi, but I have no idea where to begin and don’t want to mess anything up with my existing AlgoVPN server.

Thank you!

**Comment by jackivanov** [comment]
You will need to configure the [forecast plugin](https://wiki.strongswan.org/projects/strongswan/wiki/Forecast) additionally. We don't provider it by default

**Comment by xytzw** [comment]
Does anyone know what files to edit before algo deployment to successfully enable the forecast plugin? Is it possible to deploy it on the already existing server?

**Comment by JamesBedwell** [comment]
@xytzw, I would love to know if you find out?

**Comment by jackivanov** [comment]
Sorry, we don't have any recommendations on enabling this. You would need to follow the official documentation.
