### ISSUE TITLE
Opening new remote server

### ISSUE THREAD

**Issue by Yijia-Chen** [trailofbits/algo#1541]
I'm on a Macbook Pro, and I need to change my Algo address to a new DigitalOcean droplet. Which step of the setup should I start from (e.g. changing the config file, reinstall algo)?

**Comment by davidemyers** [comment]
If you've already run `./algo` to successfully create an AlgoVPN on a DigitalOcean droplet, then running `./algo` again will create another AlgoVPN on a new droplet. A new set of configuration files will be created in `configs`. Any existing AlgoVPNs will not be changed.
