### ISSUE TITLE
Avoiding sshguard issues

### ISSUE THREAD

**Issue by kelbyludwig** [trailofbits/algo#1543]
**Is your feature request related to a problem? Please describe.**

I was using Algo to deploy (via Docker, if that matters) a VPN in GCE. I was having several issues with this process as the tasks like `Configure the server and install required software` would often hang forever without error.

After increasing verbosity it seemed to be an issue with establishing an SSH connection to the new GCE VM. This lead me to an overzealous (default for the GCE Ubuntu image) `sshguard` rule. The issue was fixed after I added my client IP to the `sshguard` whitelist and restarted the `sshguard` service.

**Describe the solution you'd like**

`sshguard` is arguably a security feature, so I understand not wanting to disable it completely. However, some possible improvements could be:

* Disabling `sshguard` during the installation process and then re-enabling it.

* Configuring `sshguard` to be less aggressive in blocking connection attempts.

* Adding documentation or troubleshooting steps for this potential issue.

**Describe alternatives you've considered**

I'm sure there are other possible solutions that I have not considered.

**Additional context**

The log entries from `/var/log/auth.log` that clued me in on the issue.
```
Aug 12 01:03:12 algo sshguard[584]: Attack from "X.X.X.X" on service 100 with danger 10.
Aug 12 01:03:12 algo sshguard[584]: Attack from "X.X.X.X" on service 110 with danger 10.
Aug 12 01:03:13 algo sshguard[584]: Attack from "X.X.X.X" on service 110 with danger 10.
Aug 12 01:03:13 algo sshguard[584]: Blocking "X.X.X.X/32" for 120 secs (3 attacks in 1 secs, after 1 abuses over 1 secs.)
```

After editing `/etc/sshguard/whitelist` and adding my client IP address, restarting the service, the installation continued without issue.

I'm not certain this is relevant but after whitelisting my IP, these `auth.log` log entries seemed interesting. These occurred even though Algo was functioning properly.
```
Aug 12 01:29:54 algo sudo: pam_unix(sudo:session): session opened for user root by ubuntu(uid=0)
Aug 12 01:29:57 algo sshd[3159]: Did not receive identification string from X.X.X.X port 50586
Aug 12 01:29:59 algo sshd[3184]: Did not receive identification string from X.X.X.X port 50597
Aug 12 01:30:04 algo sshd[3193]: Did not receive identification string from X.X.X.X port 50587
Aug 12 01:30:11 algo sshd[3686]: Did not receive identification string from X.X.X.X port 50589
```

**Comment by jackivanov** [comment]
Seems like it takes too long for GCP to populate the `authorized_keys` file from the metadata, meanwhile Ansible attempts to connect with no success, and therefore sshguard blocks the IP. I'll disable sshguard completely with cloud-init.

**Comment by jackivanov** [comment]
Hi @kelbyludwig. Thanks for reporting! Try out this PR, please #1548

**Comment by kelbyludwig** [comment]
@jackivanov That change worked for me on the first attempt!.Thank you and great work!
