### ISSUE TITLE
Any particular reason why ipv6 isn't the default route?

### ISSUE THREAD

**Issue by shadowsaw** [trailofbits/algo#1544]
**Is your feature request related to a problem? Please describe.**
It's not a problem but an improvement suggestion.

**Describe the solution you'd like**
Right now it seems like ipv6 support is enabled but would only work if ipv6 only sites are browsed. The default used is ipv4 for all net traffic.

**Describe alternatives you've considered**
None

**Comment by davidemyers** [comment]
I believe the choice of which protocol to use is up to the individual application, in this case your browser.

**Comment by shadowsaw** [comment]
Thanks. My VPN keeps hanging often and takes a long time to load webpages. I tried changing MTU values, tried different browsers, different dns providers, but still has the same problems. VPN works well on setup and but soon degrades in performance. Any advice? Anything I might be missing? Should I try with ipv6 disabled?

**Comment by TC1977** [comment]
Sounds like you need more general troubleshooting help. Please file a new issue with some more details of your setup (cloud provider, client os, home router model, Algo install options) or hop on the Gitter chat. Or just rename this issue to something more reflecting what you need.

**Comment by shadowsaw** [comment]
@TC1977 I set up Streisand as well. It seems like Wireguard still has to develop more... Idk. All other protocols seem to work flawlessly except Wireguard. I've got hopes for it in the future but for now, it seems like when it works, it's amazing.  It, however, more often than not rarely works smoothly.
