### ISSUE TITLE
Essential Services and Websites Not Respond Under Algo Tunnel

### ISSUE THREAD

**Issue by kilo6eight** [trailofbits/algo#1550]
**Describe the bug**

Services such as Apple iOS Software update do not connect. Some Apps are extremely unreliable. For example, WSJ. 

**To Reproduce**

1. Register Account at Bithost or Bitlaunch
2. Setup Algo on Digital Ocean or Vultr server
3. Do localhost provision
4. Use

**Expected behavior**

Seamless connectivity with only some hit on latency

**Additional context**

I have tried probably about 20 different servers. Multiple different iOS devices. iPod Touch, iPad Pro, iPhone XS, iPhone SE. The same problem is same with each. 

Issue will fix itself if I use cellular data and do not connect to WiFi. My WiFi is a OpenWRT router with a network wide Wireguard VPN installed. I have also tested with different providers such as PIA, NordVPN, etc. it does seem to change the issue it still occurs. 

**Full log**

```
PUT THE OUTPUT HERE
```

**Comment by davidemyers** [comment]
So you're having problems when running your AlgoVPN tunnel inside of another VPN tunnel, but your AlgoVPN works fine when run outside of a second tunnel like normal?

What do you use for the MTU on the inside of each tunnel?

Also, you don't say whether you're using WireGuard or IPsec on iOS.

**Comment by kilo6eight** [comment]
David,

Thank you so much for replying. I was not really expecting a response. 

You are correct in your description of my networking environment. My main router is configured to route all activity over a VPN. That is a Wireguard VPN. On my iOS devices, i only exclusively use IKEv2 connection because when device is in supervise mode you can use Apple Configurator to set IKEv2 VPN to "Always On" mode which is much better and stricter than "Always-On" vpn on non-supervise device. So I prefer to keep it this way. 

David, regarding the MTU I am not sure. On my router or on my iOS devices I do not override any of the default settings. I believe the default is 1500. Do you suspect this to be the source of my internet connectivity problems? 

Thank you.

**Comment by davidemyers** [comment]
If your non-tunnel MTU is 1500 then the MTU inside your WireGuard tunnel is probably the default of 1420, but your IPsec clients don't know that all 1500 is not available to them.

In your Algo `config.cfg` try setting `reduce_mtu: 80` and deploying a new AlgoVPN.

The reason I asked about your clients is because the default MTU of WireGuard for iOS is 1280, in which case your network MTU of 1420 should have been enough. But I can understand the need for "Always On".

**Comment by TC1977** [comment]
@kilo6eight Just a thought, but if Apple Configurator allows you to have a "trusted Wi-Fi network" then you could turn off the IKEv2 when on your home Wi-Fi, and use the home Wireguard-ed connection instead.

**Comment by kilo6eight** [comment]
@davidemyers

David,

Thank you for your recommendation. From what I can see performance has improved greatly. I really appreciate your assistance. I am just curious but is a simple explanation why tunneling a VPN over another VPN causes such problems?

**Comment by jackivanov** [comment]
@kilo6eight It happens because of the encapsulation. I'm closing the issue as it seems to be solved.
