### ISSUE TITLE
Integration of PiHole into Algo

### ISSUE THREAD

**Issue by vkvkvkx** [trailofbits/algo#1551]
**Is your feature request related to a problem? Please describe.**

Slightly insecure about using a fork for something security related like a VPS, would feel much safer if this feature was implemented by ToB itself.

Also the fork will not be updated and maintained as frequently as the master.

**Describe the solution you'd like**

Integration of PiHole into the master code.

**Describe alternatives you've considered**

I am currently using a fork: https://github.com/rodeodomino/algo-pihole itself built on: https://github.com/dan-v/algo

**Additional context**

The user dan-v expressed his willingness to develop and clean up the code further if the maintainers showed interest. Hoping someone might reach out or themselves code it in.

Thanks.

**Comment by TC1977** [comment]
Related to #1258.

What do you like about Pi-Hole compared to the existing adblocking solution using dnscrypt-proxy?

**Comment by vkvkvkx** [comment]
The ad-blocking did not work for me, I figured there was some wireguard configuration or something that I didn’t know about or understand. Going over the installation again with a closer look I realized I didn’t use uppercase N in the [y/N] prompt, so it never actually installed before!

Also I suppose pihole’s web ui is a pretty nifty feature to consider? Either way now that I got it to work I suppose its not a big deal anymore.

Before this gets closed, can someone point me to instructions for editing the ad blocking lists?

Thanks.

**Comment by TC1977** [comment]
Um, I'm not sure that's how it works, but if you've got adblocking working for you, I'll leave it at that. 😄 

Instructions for editing the ad block lists, either before or after deploy, are somewhat buried in `config.cfg`, above the variable called `adblock_lists`.

**Comment by vkvkvkx** [comment]
Thanks again.
