### ISSUE TITLE
Can I admin manager panel on algo vpn?

### ISSUE THREAD

**Issue by firepmi** [trailofbits/algo#1555]
Can I have the admin manager panel on algo vpn?
for example: I should be able to block end enable for each connection.
and should be able to check the connection status.

Please give me the advise.

Thank you

**Comment by TC1977** [comment]
Algo VPN by default creates and deploys onto an Ubuntu server, which doesn't have a GUI installed and therefore no "Manager Panel" per se. You can check connection status by SSH'ing into the server and typing `sudo wg` for Wireguard and `sudo ipsec statusall` for IPsec.

There isn't an easy one-click solution to blocking and enabling a specific connection. And I'm not sure why you would want to temporarily disable someone's access to a VPN on the server-side. Perhaps could use dnscrypt-proxy to not serve DNS to the virtual IP of the peer you want to block? Or modify `/etc/ipsec.conf` and `/etc/wireguard.conf` to remove or comment out the peer that you want to block?

If you want to permanently revoke access, of course, you can just remove the user's name from `config.cfg` and the run `./algo update-users`. Then if you want to add them back on, you'd have to add them back into `config.cfg` and give them the new config file(s).

**Comment by firepmi** [comment]
I am planning to develop parental app using algo vpn.
parent can block their kid's network and enable when it is needed.

**Comment by TC1977** [comment]
If you're going to do that, wouldn't the kid just disable the VPN on their client and get around it?

But if you can figure out a way to keep the kid from doing that, rather than shut down their connection (so that all attempts at using the Internet simply time out), a better way might be to figure out how to get dnscrypt-proxy to redirect all requests to a page saying something along the lines of, "You've been shut down".

**Comment by firepmi** [comment]
I think algo vpn support on demand connection, but actually I can not see that option after I installed on my iphone.
parents should be able to disable/enable their kids network remotely.
I don't have knowledge about dnscypt-proxy, can you explain me more about it?

**Comment by firepmi** [comment]
I searched out Fail2ban for blocking network.
can I use it on algo vpn for my purpose?

**Comment by firepmi** [comment]
https://www.fail2ban.org/wiki/index.php/Main_Page

**Comment by TC1977** [comment]
You can use it on your Algo VPN server, but it won't help you with what you're trying to do. Good luck.

**Comment by jackivanov** [comment]
I'm closing this. Use [gitter](https://gitter.im/trailofbits/algo), please.
