### ISSUE TITLE
Algo VPN Swag (e.g. stickers)

### ISSUE THREAD

**Issue by lanaschuhmacher** [trailofbits/algo#1567]
Do you have templates for Algo VPN swag?
I am looking especially for stickers but anything else is appreciated too.
As you do not have a swag shop I would love to print Algo VPN swag myself. 😊

**Comment by TC1977** [comment]
Well there's the [logo](https://github.com/trailofbits/algo/blob/master/logo.png), but I would suggest checking out the [licensing terms](https://github.com/trailofbits/algo/blob/master/LICENSE) before you try selling anything.

**Comment by lanaschuhmacher** [comment]
Thanks for your reply, @TC1977. 
I do not plan to sell Algo VPN stickers. My idea is to use them myself and hand them out at meetups.
If no one comes up with already prepared design files I might use the [logo](https://github.com/trailofbits/algo/blob/master/logo.png), as you suggested, and give it to the designers at Stickermule. 🤔

**Comment by jackivanov** [comment]
I think @dguido got some stickers

**Comment by jackivanov** [comment]
https://twitter.com/AlgoVPN/status/1055504501661204481
I'm closing this for now
