### ISSUE TITLE
requirements.txt not working on Mac

### ISSUE THREAD

**Issue by nauticatt** [trailofbits/algo#1570]
When running the core dependency commands in terminal, everything goes fine, however, the requirements.txt part of the command in step 4 yeilds "ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'"

To reproduce this - take a mac and do the installation process step by step and things get spicy.

I expected the ./algo to give me the prompt stated in the installation guide, however, my computer has decided that requirements.txt won't work today

I am new to this stuff and am trying to get into networking, and I thought a google cloud compute based VPN would be a good start to learning these things. 

algo-master copy/env/bin/activate not found.  Did you follow documentation to install dependencies?
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

PLEASE HELP, I DON'T SEE WHAT'S WRONG WITH THE REQUIREMENTS.TXT

**Comment by jackivanov** [comment]
Use [gitter](https://gitter.im/trailofbits/algo) for this kind of questions, please.

**Comment by TC1977** [comment]
You have to `cd algo-master`- first part of step 3.
