### ISSUE TITLE
Please generate key pairs for EC2 deployment

### ISSUE THREAD

**Issue by zaygozi** [trailofbits/algo#1572]
So EC2 sets a really ugly & long hostname, something like "ec2-amazonaws......com". Amazon wont allow me to ssh into the instance and change it, since there were no key pairs associated with the instance. If a key pair is automatically generated during deployment, users will be able to ssh into the instance & make any required changes. Thank you and you people have done a really great job in creating an easily deployable & secure vpn for the masses.

**Comment by davidemyers** [comment]
The SSH key for the instance should be in `configs/algo.pem`. When your deployment finished, part of the final message should have been something like:

```
Shell access: ssh -i configs/algo.pem ubuntu@AAA.BBB.CCC.DDD  
```

**Comment by zaygozi** [comment]
@davidemyers @jackivanov Apparently the key is generated in the configs folder but no key pair is associated with the EC2 instance. The cloudformation stack has created 0 key pairs. I have tried deploying on AWS 2 more times before re-opening this issue (just to be sure). Here are some screenshots for you all to refer. I am confident you can reproduce this issue.

[Local Configs Folder](https://transcoz.s3.ap-south-1.amazonaws.com/algo-config.png)
[AWS Dashboard](https://transcoz.s3.ap-south-1.amazonaws.com/aws-dashboard.png)

**Comment by jackivanov** [comment]
The key pair is injected via https://github.com/trailofbits/algo/blob/master/roles/cloud-ec2/files/stack.yaml#L152-L160cloudformation-init

**Comment by TC1977** [comment]
AWS doesn't get the key from Algo, so you won't ever see it on (or be able to use it from) the AWS console unless you upload it there manually.
