### ISSUE TITLE
Getting billed for AWS

### ISSUE THREAD

**Issue by dantuluri** [trailofbits/algo#1585]
I've tried this twice just to ensure its reproducibility (both times within the last two month), but I'm getting charged for `$0.090 per GB - first 10 TB / month data transfer out beyond the global free tier` often charging me $6-20 per month for this data transfer. Does this mean I can't use AlgoVPN on free tier while transferring data out (interestingly I don't recall transferring that much data if any at all "out")?

**Comment by TC1977** [comment]
That's correct. Read the [AWS Free Tier fine print carefully](https://aws.amazon.com/free/faqs/) - last item. You only get 15GB of data transfer out/month for free with AWS, and with a VPN server that doesn't require a huge hard drive or memory, that's probably the most important thing. Lightsail gives you [1TB on the $3.50/month instance](https://aws.amazon.com/lightsail/pricing/), and Digital Ocean [does as well](https://www.digitalocean.com/pricing/).

So if you're using EC2 to host an Algo server for your phone while traveling, and not watching any movies or video, you'll be unlikely to have a problem. But if you've set up your router with Wireguard, or you're using it to stream YouTube on your phone or Netflix on your notebook, it'll cost much more than you expected.

**Comment by dantuluri** [comment]
Thanks for the clarification. Was initially confused on whether or not it was normal.
