### ISSUE TITLE
IKEv2 on Windows 10 

### ISSUE THREAD

**Issue by TarekSalama** [trailofbits/algo#1592]
What happened to the instructions?
How do I use the IKEv2 profiles on Windows now?

**Comment by davidemyers** [comment]
Please see #1521.

**Comment by TarekSalama** [comment]
I see. But is there a way to use the certificates and config files in the manual folder to get it to work on Windows 10?

**Comment by shadowsaw** [comment]
https://wiki.strongswan.org/projects/strongswan/wiki/WindowsClients @TarekSalama

**Comment by TarekSalama** [comment]
The instructions are totally different from what I see on Windows 7, specifically the Console Root; it's completely empty on my machine.

**Comment by jackivanov** [comment]
We don't support it anymore, sorry. Use WireGuard
