### ISSUE TITLE
How to see stats about users?

### ISSUE THREAD

**Issue by Berokas** [trailofbits/algo#1600]
Good day!

I am not sure if I am in correct section but I have a quistion! 
How can I see information about users on my Ubuntu server? For example if a user is online and how much is the Bandwidth? Is there a web GUI for eample that I can use?

Many thnx,
Bero

**Comment by TC1977** [comment]
There isn't a GUI built into the Algo server, it's all command line. Your best chances at measuring per-user bandwidth usage, at least since most recent reboot, are `sudo ipsec statusall` for IKEv2 connections and `sudo wg` for Wireguard connections.
