### ISSUE TITLE
Missing documentation on how to connect without "client software"

### ISSUE THREAD

**Issue by turbozapekanka** [trailofbits/algo#1606]
The first paragraph on the main page says "does not require client software on most devices".
What exactly did you mean by this statement?
I assume this does not mean that most devices implement it in hardware, but instead you mean "3rd party client software", but then I scroll down and see that all client instructions refer to Wireguard, which is a 3rd party client to almost all devices I can think of.
How come?

**Comment by TC1977** [comment]
It's a legacy statement from last year when IKEv2 was the primary choice for all operating systems. IKEv2 still doesn't require client software, but nowadays is definitely second choice for macOS, iOS, Android, and removed for Windows altogether. The readme should be revised.

**Comment by turbozapekanka** [comment]
Are you saying windows IKEv2 support is dropped? Why?

**Comment by TC1977** [comment]
See #1521 .

**Comment by turbozapekanka** [comment]
I see, so I can use it, it's just not advertised.
I personally never had any problems with IKEv2 in Windows. But I do have issues with Android and Mikrotik connecting to Libreswann, that's why I was looking into Algo. I hate installing additional software so forcing to use Wiregurad would be a deal breaker to me.

**Comment by powerlemming** [comment]
I’ve been looking into setting up Algo with IKEv2 too. The fact that it integrates natively into Windows is a big plus for me and I’ve been wondering where the documentation as been for setting it up. Let me know if you get it working (and how you did)

**Comment by toddlikesdesign** [comment]
@powerlemming See above, IKEv2 support in Windows is dropped. Use Wireguard.

**Comment by turbozapekanka** [comment]
We don't want Wireguard, can someone please point me to the commit when Wireguard was added, I will simply reset back to that commit

**Comment by TC1977** [comment]
Just go back and find the commit before #1521 was merged. On July 31st.

You can always install without Wireguard, either that commit or the current commit, by setting `wireguard_enabled` to `false` in `config.cfg` before deployment.

**Comment by powerlemming** [comment]
I set up an Algo server using WireGuard on a ubuntu machine hosted on my home network. I successfully installed the server and was wondering what config files to use : (the ones in the directory named after my external IP address or the one named "localhost"?)

**Comment by toddlikesdesign** [comment]
Wireguard configs are contained at algo/configs/SERVER-IP/wireguard/USERNAME.conf

BTW, what's the point of a VPN on your LAN?

**Comment by TC1977** [comment]
@powerlemming Assuming you ran Algo on the same Ubuntu machine that you've set up the server on, and assuming you properly set up the local install, then you should use the client conf files in the "configs/localhost" directory.

@toddlikesdesign It sometimes make sense for a [road warrior](https://en.wikipedia.org/wiki/Road_warrior_(computing)) to set up a VPN on their LAN, so they can "phone home" when out on the road. Of course there's some additional work to be done (i.e. port forwarding on the router), and the Internet speed will be limited to your upload speed, which is probably very low unless you're on a gigabit-class connection.

**Comment by powerlemming** [comment]
I use it to connect to my home LAN in order to access my NAS and other peripherals (such as printers) from outside the network, it also ecrypts the data when using public wifi. 

PS; I don't know if i did something wrong but I used the config files in the  algo/configs/localhost/wireguard directory instead of the one named after the server's IP. 
Anyways, it worked fine nevertheless..

It looks like algo/configs/localhost and algo/configs/Server-IP have the sames content...

**Comment by powerlemming** [comment]
@TC1977  You're totally right, it's exactly the use case I have for my VPN. I replaced my OpenVPN server with Algo and gave it a shot (works great so far). On my end I'm not really concerned about my upload speed since I have fiber to the home and have ~1 Gb/s connection...

**Comment by Watney** [comment]
> You can always install without Wireguard, either that commit or the current commit, by setting `wireguard_enabled` to `false` in `config.cfg` before deployment.

I am unable to use WireGuard since it’s not supported by Win ARM-64, so I am planning to install the certificates as a native Windows 10 VPN. Can you please confirm: if the algo scripts are run with the default config.cfg settings, can you still successfully configure Windows 10 VPN manually? Or, *must* the configuration file be changed prior to creating the VPN?

Thanks so much for your help!

**Comment by toddlikesdesign** [comment]
> See #1521 .
