### ISSUE TITLE
Document how to use Algo behind another router using that router's DNS

### ISSUE THREAD

**Issue by colindean** [trailofbits/algo#1609]
_broken out of #624…_

**Is your feature request related to a problem? Please describe.**

When I connect to my Algo VPN that is set up within my home network, I can reach other hosts within my home network LAN by IP but not by hostname.

**Describe the solution you'd like**

One of two:

1. A configuration that sets Algo into "home network mode" wherein it uses DNS provided by DHCP.
2. The documentation explains to set `dns_encryption` to `false` and `dns_servers` to `192.168.1.1` or `10.1.1.1` or whatever the DNS server on the LAN is in the appropriate IPv4 and IPv6 fields in the configuration.

**Describe alternatives you've considered**

1. Set the DNS manually on each client. 🙅‍♂ 
2. Set the DNS manually in each client.conf. 🙅‍♂ 
3. Script automatically changing client.conf post-generation. 🙅‍♂ 
4. Modify how Algo generates client.conf in Ansible scripts. 🙅‍♂ 

**Additional context**

See comments on #624.

**Comment by davidemyers** [comment]
I use the `forwarding_rules` feature of `dnscrypt-proxy` to forward requests for hosts in my local domain to my internal DNS server. The only disadvantage of this approach is you have to use FQDNs with WireGuard since there's no way to set a DNS search domain in a WireGuard configuration file.

**Comment by TC1977** [comment]
I can add solution #2 (documentation) to #1607 if and when I ever get home.
