### ISSUE TITLE
How to apply changes made to the config file after install.

### ISSUE THREAD

**Issue by powerlemming** [trailofbits/algo#1610]
How can I apply changes I've made to the config file (change DNS server, add/remove users, change network settings) without having to reinstall everything?

**Comment by TC1977** [comment]
#1607

**Comment by powerlemming** [comment]
If I understand correctly, I have to run the install.sh script? When I do so, it hangs up at the curl command after ''grep DigitalOcean". Am I doing something wrong (I probably am btw...)

**Comment by TC1977** [comment]
Actually my point was that other than updating user lists, you really can’t update config.cfg options without deploying a new server.  (Well you can, but it requires some expertise with strongSwan and WireGuard. Easier and faster to simply re-deploy.)

**Comment by powerlemming** [comment]
Thanks for your support ! I’ll be looking into deploying a new server (with the right config.cfg file, modified beforehand)
