### ISSUE TITLE
FYI: WireGuard for macOS on Catalina -> tunnels disappear

### ISSUE THREAD

**Issue by shawnyeager** [trailofbits/algo#1615]
Not an issue for algo, but FYI that I've confirmed with a handful of others that their WireGuard tunnels are repeatedly disappearing on Catalina. 

Mine will vanish within 24-48 hours after I add them (back).

**Comment by davidemyers** [comment]
A new version of WireGuard for macOS (1.0.7) was released today. Does it still have this issue?

**Comment by shawnyeager** [comment]
Thanks for the heads-up; hadn't seen the update until now. It references keychain fixes, so. makes sense. I'll report back in day or two.

**Comment by gittalicious** [comment]
I have noticed the same issue. Every time I reboot the computer, the tunnels are gone from WireGuard. WireGuard app version 0.0.20191012 (14) (listed as 1.0.7 in the App Store)

**Comment by shawnyeager** [comment]
The new version of WireGuard seems to have resolved the problem for me. Oddly, I still see the tunnel manager dialog pop up after I wake my MacBook Pro from sleep, but my tunnels are intact.
