### ISSUE TITLE
How to configure Wireguard to use port 53?

### ISSUE THREAD

**Issue by vkvkvkx** [trailofbits/algo#1619]
My old algo vpn server functioned on port 51820, however many public wifis were blocking said port. So I was reading online that port 53 is a good bet to circumvent this and saw a suggestion to edit the WG port in config.cfg. 

So I did this while spinning up a brand new algo server and I get the following message: 

TASK [wireguard : WireGuard enabled and started] ********************************************************************************************fatal: [35.182.166.209]: FAILED! => {"changed": false, "msg": "Unable to start service wg-quick@wg0: Job for wg-quick@wg0.service failed because the control process exited with error code.\nSee \"systemctl status wg-quick@wg0.service\" and \"journalctl -xe\" for details.\n"}

I re-tried with port 51820 in config.cfg and the install goes through, but doesn’t for port 53.

Any help would be appreciated, or even alternate suggestions to deal with public wifi blocks.

FYI I am running my server on Lightsail and client is WG app on iphone and ipad.

Edit: I see a fee threads down some work was done regarding this exact same issue. How do I make use of that pull request, does it have to be merged first? Do i have to do it myself?

Thanks.

**Comment by jackivanov** [comment]
Duplicate #1593
