### ISSUE TITLE
Unable to delete ikev2 profile on iOS

### ISSUE THREAD

**Issue by vadiof** [trailofbits/algo#1620]
**Describe the bug**

I can't delete old Algo ikev2 profile since there is no Delete(Remove) button in settings. Is there another way how one can remove it?

**To Reproduce**

1. Open iOS Settings -> VPN
2. Tap on ℹ️ right side of AlgoVPN algo IKEv2 string
3. Behold there is no Delete(Remove) button

**Expected behavior**
There should be a way to delete Algo profiles(Delete button or such)

**Comment by davidemyers** [comment]
Try Settings -> General -> Profiles.

**Comment by vadiof** [comment]
Oh, right! This helped! iOS settings are so sophisticated!
