### ISSUE TITLE
Username and Password Authentication

### ISSUE THREAD

**Issue by austinsonger** [trailofbits/algo#1623]
I'm always frustrated that the user configurations have no username and password authentication for connecting to the VPN
- Is there a username and password authentication module that I'm missing from this?
- It would be nice if there was a way of authenticating of LDAP or other directory

**Comment by TC1977** [comment]
Wireguard doesn't support usernames and passwords. 

strongSwan (IPsec) *does* support usernames and passwords, but Algo installs using `leftauth=pubkey` and `rightauth=pubkey`. You'd have to modify strongSwan yourself to use `psk` after deploying the Algo server. [Here's a sample walkthrough.](https://serverfault.com/questions/867509/how-to-configure-strongswan-ikev2-vpn-with-psk-pre-shared-key)

**Comment by Sahand1365** [comment]
Please let me username and password free
