### ISSUE TITLE
WARNING: UNPROTECTED PRIVATE KEY FILE! 

### ISSUE THREAD

**Issue by msuiche** [trailofbits/algo#1627]
```
PLAY [Configure the server and install required software] **************************************************************

TASK [common : Check the system] ***************************************************************************************
The authenticity of host 'xxxxxxxxxxxxxxxxx' can't be established.
ECDSA key fingerprint is SHA256:7v7YF3gvR+B56BMipQYGe+AvsyrwWWaLeaYmExNjm0M.
Are you sure you want to continue connecting (yes/no)? yes
fatal: [xxxxxxxxxxxxxxxxx]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: Permanently added 'xxxxxxxxxxxxxxxxx' (ECDSA) to the list of known hosts.\r\n@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\r\n@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @\r\n@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\r\nPermissions 0777 for 'configs/algo.pem' are too open.\r\nIt is required that your private key files are NOT accessible by others.\r\nThis private key will be ignored.\r\nLoad key \"configs/algo.pem\": bad permissions\r\nubuntu@xxxxxxxxxxxxxxxxx: Permission denied (publickey).", "unreachable": true}
```

Running `./algo` with Google Cloud Platform and/or Hertzner as a target Cloud in a Windows WSL console. 

**Expected behavior**

That `algo.pem` does not have 777 as permissions so it can go forward?

Any ideas of which file to update in the ansible scripts?

**Comment by davidemyers** [comment]
The Ansible scripts are correct, it's WSL that gets it wrong:

```yaml
- name: Generate the SSH private key
  openssl_privatekey:
    path: "{{ SSH_keys.private }}"
    size: 2048
    mode: "0600"
    type: RSA
  when: algo_provider != "local"
```

This project needs a determined Windows user to figure out exactly what's going on and document a solution. In the mean time, try this:

Make sure to use `/home` and not `/mnt`.

Once you clone or unzip the Algo files, make sure they're not all world writable, including the `algo` (or `algo-master`) directory itself. Alternately, try setting this from the directory before running `./algo`:
```
export ANSIBLE_CONFIG=$(pwd)/ansible.cfg
```

But be sure not to use `/mnt`.

**Comment by msuiche** [comment]
Correct. This seems a known issue with WSL:
- https://blogs.msdn.microsoft.com/commandline/2018/01/12/chmod-chown-wsl-improvements/
- https://github.com/Microsoft/WSL/issues/3181

I'm closing the issue. Thanks @davidemyers !
