### ISSUE TITLE
Local Ubuntu Installation - VPN server not getting traffic and client cannot resolve DNS

### ISSUE THREAD

**Issue by garymalaysia** [trailofbits/algo#1628]
Steps to reproduce:

1. Spawn up Ubuntu server 18.04.3
2. Git clone algo repo
3. Download add dependencies
4. Run ```sudo ./algo``` inside algo repo
5. Selected ```11``` for local VPN installation
6. ```Enter the IP address of your server: (or use localhost for local installation): [localhost]``` -> localhost
7. ```Enter the public IP address or domain name of your server: (IMPORTANT! This is used to verify the certificate)``` -> my Public IP
8. Installation completed

Ifconfig output:
```wg0: flags=209<UP,POINTOPOINT,RUNNING,NOARP>  mtu 1420
        inet 10.19.49.1  netmask 255.255.255.0  destination 10.19.49.1
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 1000  (UNSPEC)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

Client logged in with VPN via 4G: ```Site cannot be reached```

Background:
- I do not have firewall in place in from of my router.
- I tried setting ```wireguard_PersistentKeepalive:``` to 1 since I am behind NAT and also ```wireguard_PersistentKeepalive:``` to 0 to test. Both return the same result.
- Performed ```mtu``` test (using ping) and lower to 1474 in client. Prior was ```auto```.

**Comment by TC1977** [comment]
Did you set up port forwarding UDP/51820 from your router to the Algo box?

**Comment by garymalaysia** [comment]
Yes, i did that too for UDP protocol

**Comment by garymalaysia** [comment]
> Don't forget UDP/51820 should be open to incoming connections on your Algo server as well.

I enabled that port at Algo server after reading the response above. However, I removed the rule from ```ufw``` and still no connection.

**Comment by davidemyers** [comment]
Make sure you disable `ufw` completely and reboot. This command should produce no output:
```
sudo iptables-save | grep -i ufw
```
Also, your WireGuard client MTU should never be more than 1420. Try testing with the client set to 1280.

**Comment by garymalaysia** [comment]
Thank you very much for the help thus far. 
I disable all firewall from my router, and server side ufw (rebooted as well) and port forwarded 51820 to Algo server. 

This is the output of my client my unit
```tun0: flags=81<UP,POINTOPOINT,RUNNING>  mtu 1280
        inet 10.19.49.2  netmask 255.255.255.0  destination 10.19.49.2
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 500  (UNSPEC)
        RX packets 0  bytes 0 (0.0 B)
```

Still no connection..

**Comment by garymalaysia** [comment]
Here are further analysis:

- After connected to Wireguard VPN, Ping from client IP ```10.19.49.2``` to Algo server ```wg0``` interface has no response in return
- After connected to Wireguard VPN, Ping from client IP ```10.19.49.2``` to Algo server ```ens33``` interface has no response in return
- In Algo server, ping ```8.8.8.8``` from ```wg0``` interface shows the following:
```
$ ping -I wg0 8.8.8.8
PING 8.8.8.8 (8.8.8.8) from 10.19.49.1 wg0: 56(84) bytes of data.
ping: sendmsg: Required key not available
ping: sendmsg: Required key not available
ping: sendmsg: Required key not available
ping: sendmsg: Required key not available
```

**Comment by garymalaysia** [comment]
This issue is now resolved. Turned out Spectrum does not recognize ```0.0.0.0``` same as ```*``` in IP block

**Comment by garymalaysia** [comment]
Thank you for your help looking into this
