### ISSUE TITLE
certificate verify failed: unable to get local issuer certificate 

### ISSUE THREAD

**Issue by NikonMcFly** [trailofbits/algo#1631]
This morning my algo vpn repeatedly turned on and off after a minute of being on. My algo vpn on my phone was fine. So I deleted both vpns and updated to macOS Catalina and python3. Now im getting certificate verify failed when connecting to digitalocean [Get regions]

**Short description of what the bug is:**

fatal: [localhost]: FAILED! => {"changed": false, "content": "", "elapsed": 0, "msg": "Status code was -1 and not [200]: Request failed: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)>", "redirected": false, "status": -1, "url": "https://api.digitalocean.com/v2/regions"}

**Here is the a short error message when i run ./algo -vvv**

Thanks for the help if any.
 
fatal: [localhost]: FAILED! => {
    "changed": false,
    "content": "",
    "elapsed": 1,
    "invocation": {
        "module_args": {
            "attributes": null,
            "backup": null,
            "body": null,
            "body_format": "raw",
            "client_cert": null,
            "client_key": null,
            "content": null,
            "creates": null,
            "delimiter": null,
            "dest": null,
            "directory_mode": null,
            "follow": false,
            "follow_redirects": "safe",
            "force": false,
            "force_basic_auth": false,
            "group": null,
            "headers": {
                "Authorization": "Bearer ***********************************************************",
                "Content-Type": "application/json"
            },
            "http_agent": "ansible-httpget",
            "method": "GET",
            "mode": null,
            "owner": null,
            "regexp": null,
            "remote_src": null,
            "removes": null,
            "return_content": false,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": null,
            "status_code": [
                "200"
            ],
            "timeout": 30,
            "unix_socket": null,
            "unsafe_writes": null,
            "url": "https://api.digitalocean.com/v2/regions",
            "url_password": null,
            "url_username": null,
            "use_proxy": true,
            "validate_certs": true
        }
    },
    "msg": "Status code was -1 and not [200]: Request failed: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)>",
    "redirected": false,
    "status": -1,
    "url": "https://api.digitalocean.com/v2/regions"
}

**Comment by davidemyers** [comment]
Did you get your Python 3 from Homebrew or python.org? If python.org, which version did you choose and did you run `Install Certificates.command`?

**Comment by NikonMcFly** [comment]
@davidemyers I got it from homebrew

**Comment by NikonMcFly** [comment]
@davidemyers is that a better option? Also it seems like i have python 2 and python 3 installed via homebrew if that helps

**Comment by davidemyers** [comment]
Try `brew update; brew upgrade` if you haven't since the OS upgrade.

**Comment by NikonMcFly** [comment]
Yeah I have tried all the commands reference at #1612 at the bottom

**Comment by NikonMcFly** [comment]
Should I post everything that ive got when I run ./algo -vvv ?

**Comment by davidemyers** [comment]
I'm not sure how Homebrew's Python is getting messed up. Please post the output of the following commands from a new Terminal window or tab (not the tab where you're trying to run Algo):
```
ls -l $(which python3)
grep -c BEGIN /usr/local/etc/openssl@1.1/cert.pem
```

I don't think the full `./algo -vvv` output is useful at this point.

**Comment by NikonMcFly** [comment]
lrwxr-xr-x  1 root  admin  9 Apr  9  2019 /Library/Frameworks/Python.framework/Versions/3.7/bin/python3 -> python3.7
172

**Comment by davidemyers** [comment]
Yeah, that's not Homebrew.

**Comment by NikonMcFly** [comment]
Do i supposed to which it to homebrew?

**Comment by davidemyers** [comment]
How about:
```
ls -l /usr/local/bin/python3
```

**Comment by NikonMcFly** [comment]
``` 
lrwxr-xr-x  1 stevenosborne  admin  34 Nov  1 15:50 /usr/local/bin/python3 -> ../Cellar/python/3.7.5/bin/python3
```

**Comment by davidemyers** [comment]
When you install the python.org package, which you have apparently done at some point, one of the things it does is edit `~/.bash_profile` to modify your `PATH`. Try to undo what it did, then start a new Terminal window or tab.

When you run `ls -l $(which python3)` you should get just what you posted above this message (that's the Homebrew version of Python 3).

Then download a new copy of Algo and run the setup commands from the Algo directory again.

**Comment by NikonMcFly** [comment]
Thanks @davidemyers I've got it to work.
