### ISSUE TITLE
Algo on The Changelog?!

### ISSUE THREAD

**Issue by jerodsanto** [trailofbits/algo#1632]
Howdy from [The Changelog](https://changelog.com/podcast)! 👋 

_(Never heard of The Changelog? We've been interviewing the hackers, leaders, and innovators of open source and software development since '09.)_

This is _such_ a cool project! I want more folks to be able to benefit from it. We'd love to have you on the show sometime soon. Who would be best person to join us to talk about Algo and all the cool stuff y'all are up to?

Please email editors@changelog.com to coordinate. 

Looking forward to it! 💚

**Comment by dguido** [comment]
Ah! I just saw this Issue. Emailing now.
