### ISSUE TITLE
Adding users with docker version broken or not documented

### ISSUE THREAD

**Issue by DavHau** [trailofbits/algo#1633]
I could not figure out how to add users by using the docker version of algo.
The docker version seems to function quite differently than the normal one. It uses a different executable and different data/config paths. I guess this breaks some functionality.
If not, then it would be nice to have some documentation for correct usage of the docker version. There is none currently.

**Comment by jackivanov** [comment]
Isn't this sufficient? https://trailofbits.github.io/algo/deploy-from-docker.html#managing-an-algo-server-with-docker

**Comment by DavHau** [comment]
Oh, i didn't. The Additional Documentation section did not really jump into my eye. Thank you ;)
