### ISSUE TITLE
Custom port for ssh access

### ISSUE THREAD

**Issue by the-holger** [trailofbits/algo#1635]
**Is your feature request related to a problem? Please describe.**
Running anything on port 22 on my digitalOcean droplet results in mile long attempts to login via ssh from all over the world. This is kind of frustrating, since I'm sure 99% of those attempts are simple port scanning and dicitonary attacks and nothing to worry about, except for the miles and miles of log files. Moving the sshd to any other port than 22 is an instant fix for that problem.

**Describe the solution you'd like**
Let users choose to run sshd on a different port. 

**Describe alternatives you've considered**
I managed to move it manually by changing the port in the sshd_config and adding an accept rule with the new port to the iptables, but I worry that I broke algo's installer and won't be able to e.g. add/remove users from my local machine now (at least not without moving sshd ports and poking holes into the DO firewall again)

**Additional context**
I hope I didn't miss anything when searching the repo and googling a bit. All I found so far was a "nope, you can't configure that".

**Comment by davidemyers** [comment]
Nope, you can't configure that. :smile:

I agree that having the logs fill up with SSH attempts is annoying. There are other ways to cut down on SSH attempts using your cloud provider's external firewall:

* If you have a static address, only allow SSH access from that address. This is what I do. Not all cloud providers allow you to limit access by address (looking at you, Lightsail).

* If both you and your cloud provider have IPv6, block SSH access from IPv4 and only SSH over IPv6.

* If you block SSH access completely at the firewall you can still SSH to your server from a VPN client connected to that server.

In the latter two cases you'll need to re-enable IPv4 SSH access whenever you need to add users.

**Comment by jackivanov** [comment]
I’m planning to do this with cloud-init soon
