### ISSUE TITLE
Windows WSL: "Ansible is being run in a world writable directory"

### ISSUE THREAD

**Issue by rhearmas** [trailofbits/algo#1637]
**The bug**
After following the instructions for installing Algo through WSL, I get greeted with this nice error:
![image](https://user-images.githubusercontent.com/34490428/69248222-e63e1c80-0b79-11ea-9bd0-98b125095fc0.png)
I followed all the instructions as-written by copy-pasting what I had seen.

**Reproduction Steps**
1. [Install Algo into WSL.](https://github.com/trailofbits/algo/blob/master/docs/deploy-from-windows.md)
2. Attempt to run Algo with `./algo`.
3. Wait a few seconds, then observe.

**What was expected**
The check would pass, and Algo's initialization would proceed as normal.

**Additional information**
This is a fresh install; I followed all instructions by copying and pasting what I had seen. I did _not_ clone the repository until after installing the additional prerequisites.

**Full Console Log**

```
(.env) rhearmas@Rhearmas-Laptop:~/algo$ ./algo
 [WARNING]: Ansible is being run in a world writable directory (/home/rhearmas/algo), ignoring it as an ansible.cfg
source. For more information see https://docs.ansible.com/ansible/devel/reference_appendices/config.html#cfg-in-world-
writable-dir

 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match
'all'

 [WARNING]: Could not match supplied host pattern, ignoring: vpn-host


PLAY [localhost] *******************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************
ok: [localhost]

TASK [Playbook dir stat] ***********************************************************************************************
ok: [localhost]

TASK [Ensure Ansible is not being run in a world writable directory] ***************************************************
fatal: [localhost]: FAILED! => {
    "assertion": "_playbook_dir.stat.mode|int <= 0775",
    "changed": false,
    "evaluated_to": false,
    "msg": "Ansible is being run in a world writable directory (/home/rhearmas/algo), ignoring it as an ansible.cfg source. For more information see https://docs.ansible.com/ansible/devel/reference_appendices/config.html#cfg-in-world-writable-dir\n"
}

PLAY RECAP *************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

**Comment by davidemyers** [comment]
Try to correct the problem by running the following while in the `algo` directory:
```
chmod o-w .
```

**Comment by rhearmas** [comment]
> Try to correct the problem by running the following while in the `algo` directory:
> 
> ```
> chmod o-w .
> ```

I tried doing this, but got the following error:
```
(.env) rhearmas@Rhearmas-Laptop:~/algo$ chmod -o -w
chmod: missing operand
Try 'chmod --help' for more information.
```

**Comment by rhearmas** [comment]
For information to any new viewers, I did what @davidemyers suggested and ran `chmod o-w .` (include the `.` in the command!) inside of the `algo` directory.

**Comment by TC1977** [comment]
@davidemyers Perhaps we should modify the [Windows instructions](https://github.com/trailofbits/algo/blob/master/docs/deploy-from-windows.md) to specify cloning the repository into a directory other than `~`? Specifically the line reading:
```shell
cd ~ && git clone https://github.com/trailofbits/algo && cd algo
```

**Comment by davidemyers** [comment]
@TC1977 I'm reluctant to write any documentation I can't test, and I don't have Windows so I'm not able to figure out what's really going on. This issue has been frustrating.

I doubt telling people to use their home directories is the problem. At least it keeps them from using `/mnt` which we know is worse.

The answer might be running `umask 0002` as the first step, but something tells me it's not that simple.

Adding the `chmod` to the instructions might help, but I'd sure like to understand the root cause of the permission problems on WSL. Not enough to buy a Windows machine, though. :smiley:

I also think the instructions have users installing way more prerequisite packages than are required.

**Comment by TC1977** [comment]
@davidemyers I've got a laptop running Win10 Pro, so if you write it I can test it.

**Comment by davidemyers** [comment]
@TC1977 That would be great. I'll get to work on it a little later, and perhaps create a PR where we can go over it.

First thing, though: On a freshly started WSL image, please post the following from your home directory:

```
ls -la
umask
```
Thanks.

**Comment by TC1977** [comment]
~~~shell
tc1977@HP15:~$ ls -la
total 8
drwxr-xr-x 1 tc1977 tc1977  512 Nov 22 03:16 .
drwxr-xr-x 1 root      root       512 Nov 22 03:16 ..
-rw-r--r-- 1 tc1977 tc1977  220 Nov 22 03:16 .bash_logout
-rw-r--r-- 1 tc1977 tc1977 3771 Nov 22 03:16 .bashrc
-rw-r--r-- 1 tc1977 tc1977 807 Nov 22 03:16 .profile
tc1977@HP15:~$ umask
0000
~~~

**Comment by davidemyers** [comment]
Maybe it *is* as simple as setting the `umask`. One more test. Please run these commands (no need to post the output):
```
umask 0002
git clone https://github.com/trailofbits/algo.git
```
Then rerun and post the output of:
```
ls -la
umask
```
Thanks.

**Comment by TC1977** [comment]
```shell
tc1977@HP15:~$ umask
0002
```

**Comment by davidemyers** [comment]
That all looks correct. Have a look at PR #1640.

**Comment by TC1977** [comment]
Installing onto Lightsail without "world-writable directory" or "publickey permission" or any other errors so far.

Please note, by default `umask` does _not_ get preserved between sessions, so it's best to keep `umask 0002` in the actual copy-paste directions.

Speaking of which, copy-and-paste into the terminal window doesn't work out of the box like it does in the macOS Terminal.app. It might be helpful for WSL noobs like myself to have directions on how to enable shift-ctrl-v to paste into the bash window, or at least [a link to the directions](https://stackoverflow.com/questions/38832230/copy-paste-in-bash-on-ubuntu-on-windows). Otherwise manually typing in those AWS keys is a pain.

I'd also suggest adding in instructions on copying the config files to the Windows drive for further use/distribution, i.e. something like `cp -r configs/xxx.xxx.xxx.xxx /mnt/c/Users/<yourusernamehere>`.

**Comment by davidemyers** [comment]
Thanks for the testing and comments, I've revised the PR. If it's good enough I say we "ship it" to finally get rid of the permissions problems.

**Comment by dmwyatt** [comment]
I just cloned the repo and I am still running into this issue.

**Comment by benjaminpreiss** [comment]
Enable chmod in WSL: [](https://devblogs.microsoft.com/commandline/chmod-chown-wsl-improvements/)

**Comment by netgain-justin-trantham** [comment]
@benjaminpreiss are you able to elaborate what more you did to fix this? Every time I either have to set the EXPORT variable. 

I understand there are permissions between the mount directory and writable configuration ansible is looking for. If I enter the command you have in terminal where the ansible directory is located I still get that error :'(.

Any help would be greatly appreciated.

**Comment by EHoegee** [comment]
As I needed to combine a few things this worked for me:

First unmound it:
`sudo umount /mnt/c`
Mound
`sudo mount -t drvfs C: /mnt/c -o metadata`

Go to the folder where you get the error and change the permissions. (Maybe better to add it to the root ?)

`sudo chmod o-w . `

**Comment by safeblood** [comment]
> WSL by default doesn't want to touch permissions of shared folders between linux and windows (e.g. `/mnt/c...`). There is a way to disable this standard behaviour though.
> 
> 1. Enable chmod in WSL: https://devblogs.microsoft.com/commandline/chmod-chown-wsl-improvements/
> 2. Then `sudo chmod o-w .`

it helps

**Comment by mreiche** [comment]
You can enable `metadata` directly in your `wslconfig` https://learn.microsoft.com/en-us/windows/wsl/wsl-config#wslconfig
