### ISSUE TITLE
Activity logging (Session login, logout)

### ISSUE THREAD

**Issue by eric-gm** [trailofbits/algo#1638]
I'd like to view logs showing when a client is connected and when they disconnect. Most importantly IP, username and timestamp. Is this possible - how do I do this?

I'm not able to find out this info from FAQ, troubleshooting docs, or an existing issue. I've tried to search online as well but to no avail. 

Kindly assist

**Comment by TC1977** [comment]
It's in #1607.

**Comment by eric-gm** [comment]
Great thanks! Found a good enough solution (`sudo wg`) in #1216.
