### ISSUE TITLE
Adding Bahrain region for AWS deploy.

### ISSUE THREAD

**Issue by ShantanuNair** [trailofbits/algo#1642]
Please add the Middle East region me-south-1 (Bahrain) to enable deployment to the only Middle Eastern AWS region. 

Note: A note should be given to the user that the region, like Hong Kong, needs to be activated first via the AWS console.

**Comment by ShantanuNair** [comment]
My bad, looks like Algo already pulls the list of the IAM user's activated regions. I just had to activate me-south-1 and it showed up in the regions list.

**Comment by ShantanuNair** [comment]
Looks like this hasn't been solved yet. We need to set the default instance to t3.micro as t2.micro is not available on me-south-1 AWS EC2 options.

**Comment by jackivanov** [comment]
We will not change the default instance size, sorry.
