### ISSUE TITLE
Running Algo Server in a docker container

### ISSUE THREAD

**Issue by powerlemming** [trailofbits/algo#1648]
I can only get the provisioning setup working (to deploy to a cloud provider) but was wondering if there was a way to run the server itself in a container?

**Comment by TC1977** [comment]
According to [the official docs](https://github.com/trailofbits/algo/blob/master/docs/deploy-from-docker.md) you can't.

A quick google search gives me [this tutorial](https://nbsoftsolutions.com/blog/leaning-on-algo-to-route-docker-traffic-through-wireguard) but I don't know anything about Docker, haven't tried it, and can't vouch for it.

**Comment by jackivanov** [comment]
It's not supported, sorry.

**Comment by chipironcin** [comment]
Hi team,
Appreciate this is not supported at the moment, but is it technically doable?

I've been trying my best at understanding the current limitations.
Would enabling `CAP_NET_ADMIN` in the container be enough to let Algo use the kernel IPSEC stack?
