### ISSUE TITLE
How to decrypt private key from PKCS#12

### ISSUE THREAD

**Issue by taducquang** [trailofbits/algo#1658]
**Describe the bug**
I'm decrypting from "ipsec/manual/user.p12"to get user.crt & user.key from user.p12 after set up algo. But after that i got the private key like this:
-----BEGIN ENCRYPTED PRIVATE KEY-----

-----END ENCRYPTED PRIVATE KEY-----
After that i was unable to use openssl to decrypt the key, what can i do to decrypt it? I need them for my draytek vigor vpn router.
I think i got the wrong password for "Enter PEM pass phrase:" but i only have password for p12 and CA key
**To Reproduce**
Using openssl to decrypt with command: "openssl pkcs12 -info -in user.p12" and i got encrypted private key which i don't know what to do to decrypt it.

**Comment by taducquang** [comment]
Nevermind, i add -nodes in later openssl and it works. Closed this issue.

**Comment by usptact** [comment]
For those still getting the error message
```
rror outputting keys and certificates
80DB0DA4BE7C0000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:../crypto/evp/evp_fetch.c:349:Global default library context, Algorithm (RC2-40-CBC : 0), Properties ()
```
adding a parameter `-legacy` did the trick.
