### ISSUE TITLE
Error msg "The API key is not speicied. Please refer to the documentation." 

### ISSUE THREAD

**Issue by takkaneko** [trailofbits/algo#1671]
Algo running on: Ubuntu 18.04.3 LTS (Virtualized: kvm)
Created from git clone. Last commit: b66c9f5 Update CHANGELOG.md
Python 3.6.9
Runtime variables:
    algo_provider "vultr"
    algo_ondemand_cellular "False"
    algo_ondemand_wifi "False"
    algo_ondemand_wifi_exclude "X251bGw="
    algo_dns_adblocking "True"
    algo_ssh_tunneling "False"
    wireguard_enabled "True"
    dns_encryption "True"

The output at the end of the ansible playbook run is the following:

================
TASK [cloud-vultr : Upload the SSH key] *****************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "The API key is not speicied. Please refer to the documentation."}
included: /home/takumi/algo/playbooks/rescue.yml for localhost

TASK [debug] ********************************************************************************************************************************************************
ok: [localhost] => {
    "fail_hint": [
        "Sorry, but something went wrong!",
        "Please check the troubleshooting guide.",
        "https://trailofbits.github.io/algo/troubleshooting.html"
    ]
}

TASK [Fail the installation] ****************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed as requested from task"}

PLAY RECAP **********************************************************************************************************************************************************
localhost                  : ok=33   changed=5    unreachable=0    failed=1    skipped=1    rescued=1    ignored=0

**Comment by davidemyers** [comment]
Clearly the problem is that you didn't speicie your API key. You must always speicie the key. :smiley:

But seriously, have you tried recreating your `vultr.ini` file (per the [documentation](https://github.com/trailofbits/algo/blob/master/docs/cloud-vultr.md))? Maybe there's a typo in the file.
