### ISSUE TITLE
Fail2ban addition

### ISSUE THREAD

**Issue by dan1elhughes** [trailofbits/algo#1672]
**Is your feature request related to a problem? Please describe.**
After deploying the server, the first thing I did was SSH in and install `fail2ban`, to block IPs which failed to SSH into the server.

**Describe the solution you'd like**
Include a simple playbook which installs a basic `fail2ban` SSH configuration.

**Describe alternatives you've considered**
Rely on existing publickey protection for SSH.

**Additional context**
None

**Comment by dan1elhughes** [comment]
I'm happy to have a go at this, but would like to know if it'd be considered before putting the time in. Love the project. 😸

**Comment by TC1977** [comment]
This is a good time to point out that SSH is wide open to the world by default. Even if you close off cloud provider firewalls (which can't be done on Lightsail for instance), it's also wide open to any connected WireGuard/IPsec clients. Although an attacker can't get in without the private key, you're still vulnerable to DDOS attacks.

**Comment by davidemyers** [comment]
PR #1636 moves the SSH port from 22. That should help reduce the probes.

**Comment by dan1elhughes** [comment]
@TC1977 
> Although an attacker can't get in without the private key, you're still vulnerable to DDOS attacks.

Wouldn't fail2ban mitigate exactly this, by banning the IP? 🙂

**Comment by dan1elhughes** [comment]
@davidemyers Would you (collectively) consider also having fail2ban? Or is moving the port be considered sufficient?

**Comment by TC1977** [comment]
> @TC1977
> 
> > Although an attacker can't get in without the private key, you're still vulnerable to DDOS attacks.
> 
> Wouldn't fail2ban mitigate exactly this, by banning the IP? 🙂 It drops them earlier in the process from my understanding, at the firewall level instead of processing their auth and failing there.

Yes, that's my point exactly.

**Comment by davidemyers** [comment]
> Wouldn't fail2ban mitigate exactly this, by banning the IP?

WireGuard doesn't log failed connection attempts and I don't see a filter for strongSwan in the fail2ban source so I don't think it would help an AlgoVPN for protocols other than SSH.

Algo has its own custom set of firewall rules so there would need to be testing to confirm that fail2ban's rules don't conflict.

> Would you (collectively) consider also having fail2ban? Or is moving the port be considered sufficient?

It's not up to me, I just wanted to point out that something was already in the works to cut down on SSH probes.

Also, #1548 was recently implemented to *remove* sshguard, which is similar to fail2ban, from Google Cloud instances. If you add fail2ban you must take care that it doesn't start doing any banning until the necessary SSH keys are put in place by cloud-init or whatever takes care of it on a particular cloud provider.

**Comment by dan1elhughes** [comment]
> I don't think it would help an AlgoVPN for protocols other than SSH

Agree! Sorry, poor clarification on my part - I do mean purely for SSH 🙂

Oh that's super interesting that an SSH blocking feature has been considered and removed already. I'm afraid I wouldn't be confident enough in my `cloud-init` knowledge to confidently state that adding fail2ban would or wouldn't impact that 🤔

**Comment by jackivanov** [comment]
Fail2ban add no security enhancements in current implementation

**Comment by sethgoldin** [comment]
@jackivanov Can you elaborate? How does the current implementation mitigate against a suspicious number of password failures, etc., for which people usually use fail2ban?
