### ISSUE TITLE
Name constraint on CA certificate

### ISSUE THREAD

**Issue by netheril96** [trailofbits/algo#1673]
**Is your feature request related to a problem? Please describe.**
Currently, if we keep the PKI, we take the risk that someone steals the CA private key and uses it to sign server certificates our client devices will trust. They would be able to sign any server certificate, including well known ones like google.com, microsoft.com, apple.com, etc.

**Describe the solution you'd like**
Setting [name constraint](https://tools.ietf.org/html/rfc5280#section-4.2.1.10) on CA certificate so that it can only be used to sign our server certificate. Stealing CA private key will then result in no more damage than stealing the server certificate key.

**Describe alternatives you've considered**
We can choose to discard CA key, but then we cannot add more users.

**Additional context**

**Comment by jackivanov** [comment]
Might be related #75

**Comment by jackivanov** [comment]
Merged
