### ISSUE TITLE
algo directory missing when run locally

### ISSUE THREAD

**Issue by tsinf0** [trailofbits/algo#1679]
**Describe the bug**

Missing config files when installed locally.

**To Reproduce**

1. Create a new Lightsail instance manually
2.
```
sudo apt update && sudo apt upgrade
export METHOD=local
export ONDEMAND_CELLULAR=true
export ONDEMAND_WIFI=true
export ENDPOINT=some.domain
export USERS=list,of,users
curl -s https://raw.githubusercontent.com/trailofbits/algo/master/install.sh | sudo -E bash -x
```
3. After the script finishes itself and says that algo has successfully installed and config files can be found in ./configs/ or something, I tried to cd into algo but the directory doesn’t seem to exist.

**Expected behavior**

The algo directory should be created (at least that’s what happened on a automated deployment).

**Full log**

I have already deleted the instance, I will run it again and post it here later.

```
PUT THE OUTPUT HERE
```

**Comment by TC1977** [comment]
As per [the docs](https://github.com/trailofbits/algo/blob/master/docs/deploy-from-script-or-cloud-init-to-localhost.md), the Algo directory will be found on the new instance in `/opt/algo`. Try that next time.
