### ISSUE TITLE
Profile installation failed on Mac OS

### ISSUE THREAD

**Issue by nmalkin** [trailofbits/algo#168]
### OS / Environment
Mac OS 10.10.5 (Yosemite)

### Ansible version
ansible 2.2.0.0

### Version of components from `requirements.txt`

(up-to-date)

### Summary of the problem

I have been having problems installing the generated profile on Mac OS. The symptoms look very similar to #135:

> Profile installation failed.
> The 'VPN Service' payload could not be installed. The VPN service could not be created.

<img width="423" alt="screen shot 2016-12-15 at 18 42 50" src="https://cloud.githubusercontent.com/assets/903179/21254274/1a682066-c319-11e6-81fd-ef60c789dad6.png">

However, this seems to be a distinct issue: the recent fix to #135 has not solved the problem. (The original password also didn't have special characters.)

In an extra twist, I was able to install the same profile successfully on a different machine. So it seems related to how my system is configured.

### Steps to reproduce the behavior

Double-click the .mobileconfig file and follow the instructions (including successful authentication).

### The way of deployment (cloud or local)

Cloud

### Expected behavior

The profile will be added and the VPN configuration will be available.

### Actual behavior

Failure.

### Full log

Here are the relevant entries from the system log:

```
mdmclient[5409]: Error: Error Domain=ConfigProfilePluginDomain Code=-319 "The 'VPN Service' payload could not be installed. The VPN service could not be created." UserInfo=0x7ff090f95770 {NSLocalizedDescription=The 'VPN Service' payload could not be installed. The VPN service could not be created.} from: InstallPayload in NEProfileIngestionPlugin
mdmclient[5409]: *** ERROR *** [SCEPPlugin:501] XPC request to mdmclient to remove cert trust returned: -25300 (Error Domain=NSOSStatusErrorDomain Code=-25300 "The operation couldn’t be completed. (OSStatus error -25300.)" (errKCItemNotFound / errSecItemNotFound:  / The item cannot be found.) UserInfo=0x7ff090ec5190 {CallStackSymbols=(
    "0   mdmclient                           0x000000010bec3cc4 mdmclient + 31940",
    "1   mdmclient                           0x000000010bee44c6 mdmclient + 165062",
    "2   mdmclient                           0x000000010bed3b09 mdmclient + 97033",
    "3   mdmclient                           0x000000010bee3c3b mdmclient + 162875",
    "4   mdmclient                           0x000000010bee03b9 mdmclient + 148409",
    "5   libdispatch.dylib                   0x00007fff93610e73 _dispatch_client_callout + 8",
    "6   libdispatch.dylib                   0x00007fff9361fee9 _dispatch_sync_f_invoke + 39",
    "7   mdmclient                           0x000000010bee02e8 mdmclient + 148200",
    "8   mdmclient                           0x000000010bee073d mdmclient + 149309",
    "9   libxpc.dylib                        0x00007fff8f7bcd15 _xpc_connection_call_event_handler + 58",
    "10  libxpc.dylib                        0x00007fff8f7bc893 _xpc_connection_mach_event + 1901",
    "11  libdispatch.dylib                   0x00007fff93616ba8 _dispatch_client_callout4 + 9",
    "12  libdispatch.dylib                   0x00007fff93617c9f _dispatch_mach_msg_invoke + 445",
    "13  libdispatch.dylib                   0x00007fff936143bc _dispatch_queue_drain + 571",
    "14  libdispatch.dylib                   0x00007fff93616540 _dispatch_mach_invoke + 232",
    "15  libdispatch.dylib                   0x00007fff93613bef _dispatch_root_queue_drain + 463",
    "16  libdispatch.dylib                   0x00007fff93613a1c _dispatch_worker_thread3 + 91",
    "17  libsystem_pthread.dylib             0x00007fff94eeaa9d _pthread_wqthread + 729",
    "18  libsystem_pthread.dylib             0x00007fff94ee83dd start_wqthread + 13"
), IsInternalError=true, InternalErrorMsg=ProcSetCertTrustSettings})
mdmclient[5409]: CPProfileManager.installProfile returning error -319 (The 'VPN Service' payload could not be installed. The VPN service could not be created.)
com.apple.preferences.configurationprofiles.remoteservice[5398]: *** ERROR *** [CPInstallerUI:501] Profile installation (<~~IP ADDRESS~~> IKEv2 (donut.local.FB894866-DA5F-5B35-95E1-55E5DB42AF51:589CA309-97A3-5EB0-87EE-81E0351AA8A6)) (Error Domain=ConfigProfilePluginDomain Code=-319 "The 'VPN Service' payload could not be installed. The VPN service could not be created." UserInfo=0x600000271980 {NSLocalizedDescription=The 'VPN Service' payload could not be installed. The VPN service could not be created.})
```

Happy to provide additional information that would help with figuring this out.

Thanks!

**Comment by gunph1ld** [comment]
Can't reproduce. Send me your .mobileconfig, please.

**Comment by nmalkin** [comment]
Here you go: https://gist.github.com/nmalkin/cf6e4892a9b4aa88dc73869edc7d38e6
(The associated cloud instance has been deleted.)

Thanks for taking a look!

**Comment by gunph1ld** [comment]
This config was successfully installed on Sierra.
Can someone use Yosemite in order to debug this file in the apple configurator ?

**Comment by nmalkin** [comment]
This matches my experience (that the config works fine on Sierra).

I tried to install the Apple Configurator, to see if I could poke at the profile in it, and found that it seems to be [only available for macOS 10.11 and up](https://itunes.apple.com/us/app/apple-configurator-2/id1037126344). I wonder if that's just a coincidence, or if the configuration in later versions is somehow different, and the configs are therefore incompatible.

**Comment by dguido** [comment]
It's pretty likely that we're using features in the Apple profile that only work on 10.11 and up. I would rather not maintain backward capability with older operating systems, since using an older OS is a security risk in itself. We do this on Windows by only really supporting version 10 too. I'm going to close this ticket for now unless people find issues with 10.11 or 10.12.

**Comment by kennwhite** [comment]
FWIW, this profiled installed fine for me on El Capitan. I was able to use both the Profiles menu in Settings as well as command line:
/usr/bin/profiles -I -F algo.mobileconfig
Also, a delta between this profile and my own didn't show anything structurally unexpected, though the OnDemandEnabled section wasn't present in mine.
<img width="286" alt="screen shot 2016-12-19 at 2 09 26 pm" src="https://cloud.githubusercontent.com/assets/326990/21325878/5a760878-c5f6-11e6-84b2-a6f952daf65c.png">
<img width="669" alt="screen shot 2016-12-19 at 2 09 07 pm" src="https://cloud.githubusercontent.com/assets/326990/21325879/5aa43108-c5f6-11e6-9dc2-0d71942706de.png">

**Comment by dagdu123** [comment]
I'm having the same problem on macOS 10.12.5.Profile installation failed. VPN service payload could not be installed.

**Comment by alex-miro** [comment]
Have the same problem - unfortunately upgrading MacOs is not an option for me. 

How to configure my VPN connection by hand ? ( without mobileconfig)

**Comment by anderm3** [comment]
I just experienced this issue as well on macOS 10.12.6, Looking in the system log I found this;
```
NEProfileIngestionPlugin.installVPNConfiguration failed to fill in cert references: uuids {
    "_PayloadCertificateRef" = "BBA99752-0BC3-5AAF-93CF-440D7E55743D";
}, certs {
}
```

**Comment by anderm3** [comment]
It turns out my issue was I was supplying a bad password for my p12 file. When I added more users all of the configs were updated with the new p12 and SSH key password and macOS does not expose the incorrect password in a more useable way.
