### ISSUE TITLE
Consider using the plain dnscrypt-proxy binary instead of the PPA repo (it's outdated).

### ISSUE THREAD

**Issue by pguizeline** [trailofbits/algo#1682]
**Describe the bug**
Please consider using the mainline binary from the dnscrypt-proxy release page instead of the PPA repository, it's unmaintained and outdated.

**To Reproduce**

1. run on the shell: dnscrypt-proxy -version.

**Expected behavior**

The version displayed should be 2.0.36, when this issue was opened. 

**Additional context**

There are other positive outcomes from making this change:

1) Algo wouldn't need systemd socket activation to work anymore, since the plain binary ditched it.

2) Since version 2.0.34 it has the capability to block CNAME Cloaked domains for adblocking. 

3) It's pretty easy to keep dnscrypt-proxy up-to-date by using a simple update script provided at the official wiki.

4) The dnscrypt-proxy.toml can be further updated to use ip-blocklists from malware services, the ip-blacklist.txt provided by Algo is mitigating against dns-rebinding, and dnscrypt-proxy already does that by default.

5) The blacklist.txt could be using a bigger blocklist that has daily updates.

6) One final change would be to use the "Load balancing" feature with the "ph" switch, instead of using all queries directed to Cloudflare, this way no resolver would have the full log of requests of Algo.

**Comment by rodeodomino** [comment]
I've been trying to get this to work here, but I'm just unable to get it to pass tests: https://github.com/rodeodomino/algo-pihole/commit/c39219b61f619a7b475eb1829667b5ddf0647eac

Open to any ideas if you see what i'm doing wrong and I can try fixing and opening a pull request

**Comment by jackivanov** [comment]
We aim for simplicity, and adding extra tasks that need some support is not a way we'd like to go. Starting from 20.04 Ubuntu repos have dnscrypt-proxy 2 included, we'll leverage that instead of using the extra PPA.
