### ISSUE TITLE
Policy match error on Windows 10 using Strongswan (IKEv2)

### ISSUE THREAD

**Issue by 0804d23d** [trailofbits/algo#1688]
**Is your feature request related to a problem? Please describe.**
*It's more like get help rather than feature request, please forgive me for asking my question here.*

I know setting up IKEv2 connection on Windows 10 is depreciated, but I have already deployed my VPN server and don't want extra software running on it.

I used the following [commands ](https://github.com/trailofbits/algo/pull/1521/files)in the PowerShell:

```
$VpnServerAddress = "1.2.3.4"

$UserP12Path = "$Home\Downloads\USER.p12"

$CaCertPath = "$Home\Downloads\cacert.pem"

$VpnName = "Algo VPN $VpnServerAddress IKEv2"

$p12Pass = Read-Host -AsSecureString -Prompt "User p12 password"

Import-PfxCertificate -FilePath $UserP12Path -CertStoreLocation Cert:\LocalMachine\My -Password $p12Pass

Import-Certificate -FilePath $CaCertPath -CertStoreLocation Cert:\LocalMachine\Root

$addVpnParams = @{
    Name = $VpnName
    ServerAddress = $VpnServerAddress
    TunnelType = "IKEv2"
    AuthenticationMethod = "MachineCertificate"
    EncryptionLevel = "Required"
}

Add-VpnConnection @addVpnParams

$setVpnParams = @{
    ConnectionName = $VpnName
    AuthenticationTransformConstants = "GCMAES256"
    CipherTransformConstants = "GCMAES256"
    EncryptionMethod = "AES256"
    IntegrityCheckMethod = "SHA384"
    DHGroup = "ECP384"
    PfsGroup = "ECP384"
    Force = $true
}

Set-VpnConnectionIPsecConfiguration @setVpnParams
```

But when I tried to connect to my Algo VPN, I got `Policy match error` instead.

**Describe the solution you'd like**
I was hoping someone can look up the way I set up my Windows machine and see what am I missing, I guess there are some new changes since setting up IKEv2 on Windows 10 got depreciated.

**Describe alternatives you've considered**
I guess I can always try to redeploy a new VPS with WireGuard enabled, but I'd rather see if someone has a solution to my problem, since I only use Windows like once every month or so.

**Additional context**
I actually have a "pristine, up-to-date, Windows 10 with a single admin-privileged user and nothing else" like dguido mentioned [here](https://github.com/trailofbits/algo/pull/1521), and yet, Windows still failed to connect to my Algo VPN, so that sucks.

**Additional request**
Can anyone can give me a walk-through on how the Algo script got executed? I like those one file script where I can change anything I want. But with Algo. I just don't know where to start.

**Comment by jackivanov** [comment]
Windows doesn't support the ciphers we use for IKEv2. The only way to get this working is to reconfigure your Algo server manually with the compatible [ciphers](https://github.com/trailofbits/algo/pull/1521/files#diff-ffdddaca4f7fbb7e0ebf5ae8847f68fcL42-L44) or checkout before #1521 .

For further questions I suggest you to use [Gitter](https://gitter.im/trailofbits/algo)
