### ISSUE TITLE
'linux-headers-4.15.0-68-generic' 

### ISSUE THREAD

**Issue by suguer** [trailofbits/algo#1689]
fatal: [localhost]: FAILED! => {"changed": false, "msg": "No package matching 'linux-headers-4.15.0-68-generic' is available"}

**Comment by TC1977** [comment]
Can you give more details please? Such as, what system are you running Algo on, what cloud provider are you deploying onto, etc?

The debug information that's printed would be helpful. Or even just a copy-and-paste of the entire install log from `./algo` on.

**Comment by ahonecker76** [comment]
I have the same topic. Its ubuntu 18.04 LTS own server.
if i look at uname -a it says:
4.15.0 #1 SMP Mon Mar 16 15:39:59 MSK 2020 x86_64 x86_64 x86_64 GNU/Linux

TASK [common : Install headers] ****************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "No package matching 'linux-headers-4.15.0' is available"}
included: /algo/playbooks/rescue.yml for localhost

Is it may possible to exclude this out of the installation script. If so, what file is this call inside? I could not find it.
Thank you
