### ISSUE TITLE
Installation on Ubuntu Azure server stuck at "TASK [Display the invocation environment]"

### ISSUE THREAD

**Issue by tiiiko** [trailofbits/algo#1690]
**OS / Environment (where do you run Algo on)**

> Linux (ubuntu 18.04) on server, accessed via Mac with macOS Catalina v10.15.2 with python 3.7.4 installed

**Cloud Provider (where do you deploy Algo to)**

> Azure

**Summary of the problem**

> Installation gets stuck at "TASK [Display the invocation environment]" - please let me know if you need further information, thank you~

**Steps to reproduce the behavior**

**Full log**

> ~/algo$ ./algo
>  [WARNING]: Could not match supplied host pattern, ignoring: vpn-host
> 
> 
> PLAY [localhost] *******************************************************************************************************************************************************************************************
> 
> TASK [Gathering Facts] *************************************************************************************************************************************************************************************
> ok: [localhost]
> 
> TASK [Playbook dir stat] ***********************************************************************************************************************************************************************************
> ok: [localhost]
> 
> TASK [Ensure Ansible is not being run in a world writable directory] ***************************************************************************************************************************************
> ok: [localhost] => {
>     "changed": false,
>     "msg": "All assertions passed"
> }
> 
> TASK [Ensure the requirements installed] *******************************************************************************************************************************************************************
> ok: [localhost]
> 
> TASK [Set required ansible version as a fact] **************************************************************************************************************************************************************
> ok: [localhost] => (item=ansible==2.8.3)
> 
> TASK [Verify Python meets Algo VPN requirements] ***********************************************************************************************************************************************************
> ok: [localhost] => {
>     "changed": false,
>     "msg": "All assertions passed"
> }
> 
> TASK [Verify Ansible meets Algo VPN requirements] **********************************************************************************************************************************************************
> ok: [localhost] => {
>     "changed": false,
>     "msg": "All assertions passed"
> }
> 
> PLAY [Ask user for the input] ******************************************************************************************************************************************************************************
> 
> TASK [Gathering Facts] *************************************************************************************************************************************************************************************
> ok: [localhost]
> [Cloud prompt]
> What provider would you like to use?
>     1. DigitalOcean
>     2. Amazon Lightsail
>     3. Amazon EC2
>     4. Microsoft Azure
>     5. Google Compute Engine
>     6. Hetzner Cloud
>     7. Vultr
>     8. Scaleway
>     9. OpenStack (DreamCompute optimised)
>     10. CloudStack (Exoscale optimised)
>     11. Install to existing Ubuntu 18.04, 19.04, or 19.10 server (Advanced)
>   
> Enter the number of your desired provider
> :
> 
> TASK [Cloud prompt] ****************************************************************************************************************************************************************************************
> ok: [localhost]
> 
> TASK [Set facts based on the input] ************************************************************************************************************************************************************************
> ok: [localhost]
> [Cellular On Demand prompt]
> Do you want macOS/iOS IPsec clients to enable "Connect On Demand" when connected to cellular networks?
> [y/N]
> :
> 
> TASK [Cellular On Demand prompt] ***************************************************************************************************************************************************************************
> ok: [localhost]
> [Wi-Fi On Demand prompt]
> Do you want macOS/iOS IPsec clients to enable "Connect On Demand" when connected to Wi-Fi?
> [y/N]
> :
> 
> TASK [Wi-Fi On Demand prompt] ******************************************************************************************************************************************************************************
> ok: [localhost]
> [Retain the PKI prompt]
> Do you want to retain the keys (PKI)? (required to add users in the future, but less secure)
> [y/N]
> :
> 
> TASK [Retain the PKI prompt] *******************************************************************************************************************************************************************************
> ok: [localhost]
> [DNS adblocking prompt]
> Do you want to enable DNS ad blocking on this VPN server?
> [y/N]
> :
> 
> TASK [DNS adblocking prompt] *******************************************************************************************************************************************************************************
> ok: [localhost]
> [SSH tunneling prompt]
> Do you want each user to have their own account for SSH tunneling?
> [y/N]
> :
> 
> TASK [SSH tunneling prompt] ********************************************************************************************************************************************************************************
> ok: [localhost]
> 
> TASK [Set facts based on the input] ************************************************************************************************************************************************************************
> ok: [localhost]
> 
> PLAY [Provision the server] ********************************************************************************************************************************************************************************
> 
> TASK [Gathering Facts] *************************************************************************************************************************************************************************************
> ok: [localhost]
> 
> --> Please include the following block of text when reporting issues:
> 
> Algo running on: Ubuntu 18.04.3 LTS (Virtualized: microsoft)
> Created from git clone. Last commit: 62d0090 Update main.yml
> Python 3.6.9
> Runtime variables:
>     algo_provider "local"
>     algo_ondemand_cellular "False"
>     algo_ondemand_wifi "False"
>     algo_ondemand_wifi_exclude "X251bGw="
>     algo_dns_adblocking "False"
>     algo_ssh_tunneling "False"
>     wireguard_enabled "True"
>     dns_encryption "True"
> 
> TASK [Display the invocation environment] ******************************************************************************************************************************************************************
> changed: [localhost -> localhost]
>

**Comment by jackivanov** [comment]
Azure is quite slow at resource provisioning. How long did you wait? Have you checked the portal to find out what resources are provisioned already?

**Comment by tiiiko** [comment]
> Azure is quite slow at resource provisioning. How long did you wait? Have you checked the portal to find out what resources are provisioned already?

Thank you for your quick response, I tried 3+ times and the longest time I waited was 30 minutes (i.e. during my latest attempt when writing this).

This is the data from Azure Portal: 

![thumbnail_image001](https://user-images.githubusercontent.com/60036961/72665634-574c6400-3a45-11ea-9969-6ae84bba987a.png)

My last attempt was around 10pm30. It seems the server eventually becomes inactive again. Since the time of the graph another 15 minutes have passed and the graphs have remained flat since. 

Should I still wait longer?

**Comment by jackivanov** [comment]
I just tried and the deployment took 1 minute 1 second. I suggest you to go to Deployments in the Resource Groups on the Azure Portal and find out what's going on there

**Comment by jackivanov** [comment]
Oh I see, it's actually stuck on the next step after "Display the invocation environment", which is [Install the requirements](https://github.com/trailofbits/algo/blob/master/playbooks/cloud-pre.yml#L19). There is something wrong going on in your environment that prevents you from installing those python dependencies

**Comment by tiiiko** [comment]
It lists 1 deployment as succeeded:

![thumbnail_image001-2](https://user-images.githubusercontent.com/60036961/72665864-8663d500-3a47-11ea-8d30-edd852765f7f.png)

Still, when I check the terminal the installation remains stuck at the same line that I pasted above. 

Should I abort the installation one more time, delete the successful deployment on the Azure Portal and install again with ./Algo?

**Comment by tiiiko** [comment]
> Oh I see, it's actually stuck on the next step after "Display the invocation environment", which is [Install the requirements](https://github.com/trailofbits/algo/blob/master/playbooks/cloud-pre.yml#L19). There is something wrong going on in your environment that prevents you from installing those python dependencies

That is a very useful hint, thank you for looking it up!

I executed the following on the server:

> sudo apt install -y python3-virtualenv
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-virtualenv is already the newest version (15.1.0+ds-1.1).
The following packages were automatically installed and are no longer required:
  grub-pc-bin libdumbnet1 linux-headers-4.15.0-72
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

Also, I executed the following on my local Mac:

> python3 -m pip install --upgrade virtualenv
Collecting virtualenv
  Downloading https://files.pythonhosted.org/packages/05/f1/2e07e8ca50e047b9cc9ad56cf4291f4e041fa73207d000a095fe478abf84/virtualenv-16.7.9-py2.py3-none-any.whl (3.4MB)
     |████████████████████████████████| 3.4MB 9.6kB/s 
Installing collected packages: virtualenv
Successfully installed virtualenv-16.7.9

It seems the Python virtual environment was properly installed on the server already, but not yet on my Mac. I will try again and post an update on whether the installation works now

**Comment by tiiiko** [comment]
I noticed the server displayed the message:

> *** System restart required ***

So I ran the command:

> sudo reboot now

Then I attempted another installation of Algo. However, same result of being stuck at the same line.

Anything else I could try?

**Comment by jackivanov** [comment]
Try to delete everything and start from scratch following the [steps](https://github.com/trailofbits/algo#deploy-the-algo-server)

**Comment by tiiiko** [comment]
Thanks! Now I got past the point where I was stuck last time. 

I also made sure all the Python packages are installed, so I referred to an older instruction by AlgoVPN that did not yet assume that my Ubuntu server has it all installed already:

> sudo apt-get update && sudo apt-get install \
build-essential \
libssl-dev \
libffi-dev \
python-dev \
python-pip \
python-setuptools \
python-virtualenv -y

**Comment by tiiiko** [comment]
Worked! Thank you for the support

> "\"#                          Congratulations!                            #\"",
            "\"#                     Your Algo server is running.                     #\"",
