### ISSUE TITLE
support armbian buster targets

### ISSUE THREAD

**Issue by senecaso** [trailofbits/algo#1692]
**Is your feature request related to a problem? Please describe.**
It would be great if users could use algo to build a VPN appliance (using things like Nanopi or Raspberry Pi).  Right now, if your appliance is running Armbian, the deploy fails in several places.

**Describe the solution you'd like**
I would like to be able to deploy algo to Armbian Buster based targets to allow easily building a consistent/secure VPN appliance

**Describe alternatives you've considered**
Manually setting up the VPN and securing the appliance, but so much work has already been put into algo, and its such a great project, it would be far better to leverage it than reinvent the wheel

**Additional context**
none

**Comment by jackivanov** [comment]
We're not interested in supporting any new (especially non-cloud) systems at this moment, sorry.
