### ISSUE TITLE
DNS leaks

### ISSUE THREAD

**Issue by codedmon** [trailofbits/algo#1695]
**Describe the bug**

When running dnsleak.com or dnsleaktest.com, the same DNS provider comes up (different locations) when the VPN is on or off.   The provider is Cloudflare.

**To Reproduce**
1.  Install AlgoVPN on DigitalOcean droplet
2.  Install Wireguard Android app and import config file.
3.  Run test on dnsleak.com or dnsleaktest.com from Android phone
- Tried this connected to my home WiFi and mobile network and receive the same result.

**Expected behavior**

I expected the DigitalOcean DNS provider to be displayed when running these test.

**Comment by codedmon** [comment]
> The expected behavior is for AlgoVPN clients to only use the DNS provider(s) specified in `config.cfg`, which by default is:
> 
> ```
> dnscrypt_servers:
>   ipv4:
>     - cloudflare
> #   - google
>   ipv6:
>     - cloudflare-ipv6
> ```

I see.  So the results I am getting is nothing to be concerned about, correct?  Since Cloudflare is used by both the VPN and my home network.

**Comment by davidemyers** [comment]
It doesn't look like you have a leak.
