### ISSUE TITLE
AloVPN stopped working at home

### ISSUE THREAD

**Issue by Will201711** [trailofbits/algo#1697]
algo vpn stopped working at home but works fine anywhere else, please can anyone help.

**Comment by Will201711** [comment]
When I try to connect to Algo VPN using Wireguard on laptop or any other device to my Home Wifi it doesn't have any internet access but when I switch to my Phones Hotspot the VPN works.
So what I currently do to get it to work is the following
 1.)I connect to my Laptop using my Phones Hotspot 
 2 .) on my Laptop switch on VPN 
 3.) Test the internet connection then it works
 4.) Then While VPN is activated on laptop I switch to my Homes Wifi 
 5.) Then it works with no Issues
Please assist as it look like having issues with the initial  connect from Home Wifi

The VPN is setup in Azure

**Comment by jackivanov** [comment]
There is nothing we can do, sorry, it's not a bug in Algo. Please, you [Gitter](https://gitter.im/trailofbits/algo) to ask questions.
