### ISSUE TITLE
Ubuntu 16.10 Client?

### ISSUE THREAD

**Issue by jessekrembs** [trailofbits/algo#170]
Not sure if I missed something here or not, but does this server deployment work with Ubuntu (16.10) as a client? I had no trouble spinning up Algo in a EC2 device but getting a an Ubuntu laptop to work seems non-trivial for a normal end user.  I have a feeling that due to issues with StrongSwan in Ubuntu I think the answer is no there is no client software that makes this easy, but I'm not sure. There is no mention of a Linux client config in the documents. Any confirmation would be great. 

Thank you.

**Comment by dguido** [comment]
Yes, we support Linux clients but they are advanced users only at the moment. We don't have explicit instructions for how to configure them yet.

In the section of the readme titled "StrongSwan Clients", you'll find all the raw materials you need to build a Linux client: https://github.com/trailofbits/algo#strongswan-clients-eg-openwrt

At a high level, you can probably just apt-get install strongswan and replace the configuration with the one that was generated by Algo.
