### ISSUE TITLE
Connection Issues

### ISSUE THREAD

**Issue by jalvarez212** [trailofbits/algo#1704]
Deployed Algo on a local server. But connection doesn't seem to work. 

Logs read that the "handshake' can not be completed after 5 seconds and restarts/retries. 

Anyone have any insight into this? I've tried disabling firewalls and connecting from different devices.

**Comment by TC1977** [comment]
We need some details.

- Just making sure - where are you trying to connect from? Not from your home LAN, right? 
- Are you talking about the WireGuard client or IPsec? and which devices have you tried?
- What brand/model of router do you have on your LAN?
- Can you post some of the error messages you get?

**Comment by jalvarez212** [comment]
Silly oversight on my end. Was trying to connect from within my LAN. Seems to be working now. 

Thanks for your attention.
