### ISSUE TITLE
Discord on Lightsail Virginia US-East

### ISSUE THREAD

**Issue by TarekSalama** [trailofbits/algo#1710]
**Describe the bug**

Visiting https://www.discordapp.com/ while Wireguard is hosted on Virginia Lightsail, will result in a distorted page with broken CSS and no formatting. The Discord app will have missing assets as well.

**To Reproduce**

1. Host Algo on Lightsail - Virginia region
2. Try to visit Discord's website or using the Discord app

**Expected behavior**

Discord website and app look good

**Additional context**

I tried changing my DNS to other providers other than Cloudflare since I read somewhere that Amazon's East US servers' DNS can mess with Cloudflare's but it didn't fix it. In fact it made pinging google.com give me worse numbers.

I know this may be unrelated to Algo but I am hoping someone can shed some light and help me since I am out of options. Most other providers are blacklisted by some local websites and Apple's App Store and Developer websites so it's so inconvenient to use DO or any of the others providers.
I have also tried contacting Discord's support but they couldn't help.

**Comment by TC1977** [comment]
I can confirm this, running an older version of Algo on Lightsail (still auto-updated to current versions of WireGuard though). The webpage is broken, and stays broken even when changing the DNS server to 8.8.8.8.

I personally have no interest in using Discord, so I can't really troubleshoot further. Have you tried IPsec? Have you tried DO or another cloud provider? What if you try a Mac or PC?

**Comment by TarekSalama** [comment]
It doesn't matter which device, it's still the same.
It does work fine on other providers and other regions in Lightsail but Lightsail has been the best for me due to factors like price and that every other site works fine. Other providers are blacklisted by a few of the frequent websites I use.

**Comment by TarekSalama** [comment]
Is there anything that I can do about it?

**Comment by TC1977** [comment]
So there's only a problem with one specific region in Lightsail? What about US-west (Oregon)?
