### ISSUE TITLE
Absolute paths in SSH config to support Include directive

### ISSUE THREAD

**Issue by dan1elhughes** [trailofbits/algo#1713]
**Is your feature request related to a problem? Please describe.**
When I use the following in my `~/.ssh/config`:

```
Include ~/src/github.com/trailofbits/algo/configs/*/ssh_config
```

I get this error:

```
> ssh algo
no such identity: configs/algo.pem: No such file or directory
algo@999.999.999.999: Permission denied (publickey).
```

This is because the generated config refers to `configs/algo.pem` by relative path:

```
Host 999.999.999.999 algo
  HostName 999.999.999.999
  User algo
  Port 4160
  IdentityFile configs/algo.pem // <-- This value.
  KeepAlive yes
  ServerAliveInterval 30
```

**Describe the solution you'd like**
Use an absolute path in the config file to support Include directive.

**Describe alternatives you've considered**
None.

**Additional context**
I would like this so that I can always `ssh algo` without having to `cd` or tweak config files, even after creating a new server.

**Comment by jackivanov** [comment]
I don't think it would make life easier. If you're moving the config files, my only suggestion would be to just add `configs/algo.pem` to ssh-agent

**Comment by dan1elhughes** [comment]
@jackivanov Sorry for not being clear - I'm not moving my config files, I'm including the generated SSH config into my "main" `~/.ssh/config` using the directive in the original post. If the `IdentifyFile` was an absolute path, this would work great 👌 As it is though, I can only use `ssh algo` if I'm _already in_ the algo directory:

```
~/src/github.com/trailofbits/algo ❯ ssh algo -v
OpenSSH_7.9p1, LibreSSL 2.7.3
debug1: Reading configuration data /Users/danhughes/.ssh/config
debug1: Reading configuration data /Users/danhughes/src/github.com/dan1elhughes/algo/configs/xxx.xxx.xxx.xxx/ssh_config
debug1: /Users/danhughes/src/github.com/dan1elhughes/algo/configs/xxx.xxx.xxx.xxx/ssh_config line 1: Applying options for algo
<snip>
debug1: Offering public key: configs/algo.pem RSA SHA256:[redacted] explicit
debug1: Server accepts key: configs/algo.pem RSA SHA256:[redacted] explicit
<snip>
algo@algo-server:~$
```

Otherwise, it'll try to load `pwd` + `configs/algo.pem`:

```
~/ ❯ ssh algo -v
OpenSSH_7.9p1, LibreSSL 2.7.3
debug1: Reading configuration data /Users/danhughes/.ssh/config
debug1: Reading configuration data /Users/danhughes/src/github.com/dan1elhughes/algo/configs/xxx.xxx.xxx.xxx/ssh_config
debug1: /Users/danhughes/src/github.com/dan1elhughes/algo/configs/xxx.xxx.xxx.xxx/ssh_config line 1: Applying options for algo
<snip>
debug1: Trying private key: configs/algo.pem
no such identity: configs/algo.pem: No such file or directory
debug1: No more authentication methods to try.
algo@xxx.xxx.xxx.xxx: Permission denied (publickey).<snip>
```

Does it makes sense? 🙂 I believe if the `IdentityFile` option was absolute, there's be no need to do anything with ssh-agent; just include the configs and it'll all "just work" even if you destroy and create a new Algo server 🎉

**Comment by dan1elhughes** [comment]
To help me understand - do you have a preference for relative path here? Does it enable something I'm not aware of? 🙏

**Comment by dan1elhughes** [comment]
With a little bit of playing, it looks like the only change needed is on [this line](https://github.com/trailofbits/algo/blob/master/server.yml#L35):

From:

```
IdentityFile {{ SSH_keys.private }}
```

To

```
IdentityFile {{ SSH_keys.private | realpath }}
```

I will create a PR for this 👍
