### ISSUE TITLE
Slow internet speed China

### ISSUE THREAD

**Issue by davidbonachera** [trailofbits/algo#1724]
I'm connecting to a Vultr instance in Los Angeles from China, Shenzhen. I've also seen #1588 .

I've got a 100Mbps fiber internet connection. With Wireguard on, my speedtest drop to 0.8Mbps download and 2.6Mbps for the upload.

This is totally random and one time I had 70Mbps with Wireguard on. But it's mainly an average of ~1Mbps and inferior to it for each tunnels connection.

Without Wireguard I'm at 90Mbps download.

I also realized that the listening port is attribute during the connection and it's always different.
Would it be possible to tweak those listening port? Did anyone experience that?

Server: Ubuntu 19.10
Laptop: Mac Os Catalina 10.15.2

**Comment by davidbonachera** [comment]
After some research, it may just be related to the Cloud Provider that doesn't provide a good peering with china. Bandwidth throttling may still be a thing here. As my download is affected but not my upload.

A possible solution: Find a CN2 / CN2 GIA network peering.

**Comment by romain130492** [comment]
> After some research, it may just be related to the Cloud Provider that doesn't provide a good peering with china. Bandwidth throttling may still be a thing here. As my download is affected but not my upload.
> 
> A possible solution: Find a CN2 / CN2 GIA network peering instance with a different provider (Vultr is too slow for that use case).

What provider would you recommend for China then?

**Comment by etc** [comment]
@davidbonachera and @romain130492 I am curious whether either of you have found a good setup. I recently tried DigitalOcean through their Singapore server location. Connecting through Wireguard on IOS from my cell network works great, but connecting through Wireguard on OS X from my home network works terribly. Hard to troubleshoot because my Chinese telecom provider won't allow me to look at the router configuration.

**Comment by davidbonachera** [comment]
@romain130492 @etc , at the end I found a private proxy provider for my daily use which is cheaper than maintaining my own.

**Comment by etc** [comment]
Thanks—willing to share which one? I was exploring Algo because ExpressVPN has become unusable.

**Comment by davidbonachera** [comment]
Mail'd you.
