### ISSUE TITLE
The SNAT IPv4 address not found. Cannot proceed with the alternative ingress ip."

### ISSUE THREAD

**Issue by WA7P-7** [trailofbits/algo#1726]
I got this error when trying to set up EC2 Instance on AWS.
The SNAT IPv4 address not found. Cannot proceed with the alternative ingress ip."

**Comment by jackivanov** [comment]
First, the reason we ask to complete the issue template is to gather as much information as possible to find out where the problem really is. Next time, complete the issue template, please.

Second, DigitalOcean is the only supported provider for alternative ingress IP.
