### ISSUE TITLE
want to configure algo vpn on router

### ISSUE THREAD

**Issue by tahseen2k8** [trailofbits/algo#1729]
hello guys  first of all bundle of thanks for such a fantastic project.
so i have deployed my vpn and using it on mobile and machine successfully now thinking to configure it on router level so all traffic would be route from algo .
i have read couple of articles on it and figured out that this can be possible from a router having **openwrt** firmware  . so I can install wireguard and via wireguard I can configure algo setup 

What I need is .

- expert suggestion is this possible to configure and am i moving in right direction .?

- any one have tried if yes please share steps. because i am unable to find algo specific article on net

- if it is possible please suggest me high spec router in some decent amount.
sharing experience is highly encourage because i really want to have some solid knowledge before spending on router .

**Comment by jackivanov** [comment]
Both WireGuard and IPsec possible. You can use [this instructions](https://github.com/trailofbits/algo/blob/8bdd99c05dc0afde9847c002e6cbce880c05b632/docs/client-linux-ipsec.md) for IPsec. We don't have instruction for WireGuard on OpenWRT, but the client installation should be trivial - https://openwrt.org/docs/guide-user/services/vpn/wireguard/client.

We appreciate if you can send a PR for WireGuard OpenWRT client docs. Thanks!
