### ISSUE TITLE
nothing

### ISSUE THREAD

**Issue by matthemattix** [trailofbits/algo#1730]

**Comment by davidemyers** [comment]
Make sure your API token has write access:

![DO API Token](https://user-images.githubusercontent.com/26753976/74938733-93644300-53bc-11ea-8799-ca14deed50db.jpg)
Also check the [DO Status Page](https://status.digitalocean.com) to make sure there weren't any issues in your region at the time of the error.

**Comment by matthemattix** [comment]
Hey David!

Thanks for the quick response!  Appears there was maintenance going on at the time of my install for my region!

I am now getting this error:

fatal: [localhost]: FAILED! => {"changed": false, "elapsed": 320, "msg": "Timeout when waiting for search string OpenSSH in 157.245.93.157:4160"}

Any ideas?

Thanks!

-Matt
