### ISSUE TITLE
Installation gets stuck at the very beginning. 

### ISSUE THREAD

**Issue by amihos** [trailofbits/algo#1732]
**Describe the bug**

the code gets stuck at the first stage:

Algo running on: Ubuntu 18.04.4 LTS (Virtualized: microsoft)
Created from git clone. Last commit: 28d95ea Update main.yml (#1727)
Python 3.6.9
Runtime variables:
    algo_provider "local"
    algo_ondemand_cellular "False"
    algo_ondemand_wifi "False"
    algo_ondemand_wifi_exclude "X251bGw="
    algo_dns_adblocking "False"
    algo_ssh_tunneling "False"
    wireguard_enabled "True"
    dns_encryption "True"

TASK [Display the invocation environment] ***************************************************************************changed: [localhost -> localhost]

nothing happens after here

**To Reproduce**
On azure make a VM and then follow the instruction on GIThub to install algo. after runnning ./algo

**Expected behavior**

It finishes the installation and provide credentials and required info.

**Additional context**

**Full log**

 [WARNING]: Could not match supplied host pattern, ignoring: vpn-host

PLAY [localhost] ****************************************************************************************************
TASK [Gathering Facts] **********************************************************************************************ok: [localhost]

TASK [Playbook dir stat] ********************************************************************************************ok: [localhost]

TASK [Ensure Ansible is not being run in a world writable directory] ************************************************ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [Ensure the requirements installed] ****************************************************************************ok: [localhost]

TASK [Set required ansible version as a fact] ***********************************************************************ok: [localhost] => (item=ansible==2.8.3)

TASK [Verify Python meets Algo VPN requirements] ********************************************************************ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [Verify Ansible meets Algo VPN requirements] *******************************************************************ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

PLAY [Ask user for the input] ***************************************************************************************
TASK [Gathering Facts] **********************************************************************************************ok: [localhost]
[Cloud prompt]
What provider would you like to use?
    1. DigitalOcean
    2. Amazon Lightsail
    3. Amazon EC2
    4. Microsoft Azure
    5. Google Compute Engine
    6. Hetzner Cloud
    7. Vultr
    8. Scaleway
    9. OpenStack (DreamCompute optimised)
    10. CloudStack (Exoscale optimised)
    11. Install to existing Ubuntu 18.04 or 19.10 server (for more advanced users)

Enter the number of your desired provider
:

TASK [Cloud prompt] *************************************************************************************************ok: [localhost]

TASK [Set facts based on the input] *********************************************************************************ok: [localhost]
[Cellular On Demand prompt]
Do you want macOS/iOS clients to enable "Connect On Demand" when connected to cellular networks?
[y/N]
:
N^M
TASK [Cellular On Demand prompt] ************************************************************************************ok: [localhost]
[Wi-Fi On Demand prompt]
Do you want macOS/iOS clients to enable "Connect On Demand" when connected to Wi-Fi?
[y/N]
:

TASK [Wi-Fi On Demand prompt] ***************************************************************************************ok: [localhost]
[Retain the PKI prompt]
Do you want to retain the keys (PKI)? (required to add users in the future, but less secure)
[y/N]
:

TASK [Retain the PKI prompt] ****************************************************************************************ok: [localhost]
[DNS adblocking prompt]
Do you want to enable DNS ad blocking on this VPN server?
[y/N]
:

TASK [DNS adblocking prompt] ****************************************************************************************ok: [localhost]
[SSH tunneling prompt]
Do you want each user to have their own account for SSH tunneling?
[y/N]
:

TASK [SSH tunneling prompt] *****************************************************************************************ok: [localhost]

TASK [Set facts based on the input] *********************************************************************************ok: [localhost]

PLAY [Provision the server] *****************************************************************************************
TASK [Gathering Facts] **********************************************************************************************ok: [localhost]

--> Please include the following block of text when reporting issues:

Algo running on: Ubuntu 18.04.4 LTS (Virtualized: microsoft)
Created from git clone. Last commit: 28d95ea Update main.yml (#1727)
Python 3.6.9
Runtime variables:
    algo_provider "local"
    algo_ondemand_cellular "False"
    algo_ondemand_wifi "False"
    algo_ondemand_wifi_exclude "X251bGw="
    algo_dns_adblocking "False"
    algo_ssh_tunneling "False"
    wireguard_enabled "True"
    dns_encryption "True"

TASK [Display the invocation environment] ***************************************************************************changed: [localhost -> localhost]

**Comment by davidemyers** [comment]
Issue #1690 sounds similar but I'm not sure the solution shown for that issue is the right one.

Did you make sure the operating system was up-to-date first by running `sudo apt update; sudo apt upgrade`? Are you running `./algo` as `root` (which you usually want to do for a local install)?

When it hangs, can you SSH in from another window and see if any processes are hanging? Maybe see if there's output from the command `ps aux | grep apt | grep -v grep`.
