### ISSUE TITLE
Deployment: Task [Debug]

### ISSUE THREAD

**Issue by mrmmg** [trailofbits/algo#1735]
**Describe the bug**

the script is waiting a long time on Task Debug. why?

**Expected behavior**

**Additional context**

**Full log**

![Annotation 2020-02-26 162105](https://user-images.githubusercontent.com/30490118/75346479-0afe0a80-58b4-11ea-8a2e-a150e39ba3ee.png)
```
PUT THE OUTPUT HERE
```

**Comment by TC1977** [comment]
Can you include the basic debug info - the text block that starts `--> Please include the following block of text when reporting issues:`?
