### ISSUE TITLE
Is there a way to set a quota for each user?

### ISSUE THREAD

**Issue by iLevye** [trailofbits/algo#1739]
**Is your feature request related to a problem? Please describe.**
Digital Ocean has 1 TB  bandwidth limit. Let's say, I have 10 users, I want to set 100gb limit for each user.

**Describe the solution you'd like**
I would like to set a bandwidth config. It can automatically stop traffic for the user when user hit the limit. 

**Describe alternatives you've considered**
If I can see which user spend how much traffic, I can delete user with a crontab.

**Comment by TC1977** [comment]
There's no easy way to do this, with either WireGuard or IPsec. Maybe set up a crontab to continually run `sudo wg` and `sudo ipsec statusall`, parse the output, and disconnect the users that go over a set amount? 

I think, however, strongSwan resets the data counter when there's a new connection. Meanwhile, WireGuard never resets the data counter, so you'd have to restart the server at the start of every month.

**Comment by jackivanov** [comment]
You can use tc to control the traffic - https://linux.die.net/man/8/tc
We don’t provide a way to configure this with Algo, sorrt

**Comment by iLevye** [comment]
> Trun `sudo wg` and `sudo ipsec statusall`

@TC1977 this is what exactly I need. But I can't match peers with my users. I searched the code in config files but I couldn't find any part. 

```
peer: qDLOsW/YFb0A0LHmj/Q8SHe9x2w19zL46gh/iD8/uQI=
  preshared key: (hidden)
  endpoint: 151.135.*.*:55269
  allowed ips: 10.19.49.2/32, fd9d:bc11:4021::2/128
  latest handshake: 8 seconds ago
  transfer: 80.44 MiB received, 471.65 MiB sent

peer: yy/hEVsv4j/NV1WlAovMzoiaJs2TqoTMh/4Js3aqpkA=
  preshared key: (hidden)
  endpoint: 195.244.*.*:56756
  allowed ips: 10.19.49.4/32, fd9d:bc11:4021::4/128
  latest handshake: 2 hours, 1 minute, 3 seconds ago
  transfer: 1.54 GiB received, 29.50 GiB sent
```

**Comment by TC1977** [comment]
Well you have one peer connected to `10.19.49.2`, which hasn't used much overall but has an active connection, and another peer connected to `10.19.49.4`, which has uploaded a whole crapload of data but not in a couple of hours. You'd have to go back to your config files and figure out which is which. I believe 10.19.49.1 is the server itself, so ...2 is the first client listed in `config.cfg`, and ...4 is the third client listed.

**Comment by jackivanov** [comment]
For WireGuard we put peer's name into [the server config](https://github.com/trailofbits/algo/blob/master/roles/wireguard/templates/server.conf.j2#L11-L12), so you can parse it to math user-ip. For IPsec no static matching possible for now.
