### ISSUE TITLE
Consider smaller GCE instance size?

### ISSUE THREAD

**Issue by kennwhite** [trailofbits/algo#175]
The current GCE instance is set to: n1-standard-1 (https://github.com/trailofbits/algo/blob/cd5b096ab73f4ea976fe72bf62d41dc83584965d/roles/cloud-gce/tasks/main.yml#L9) but this is probably overkill, and the monthly costs are $25 (https://cloud.google.com/compute/pricing). Should this be type: f1-micro ?

**Comment by dguido** [comment]
:+1:
