### ISSUE TITLE
Explain how to manually set an IKEv2 VPN (without .mobileconfig) given certificates and .conf files

### ISSUE THREAD

**Issue by karipov** [trailofbits/algo#1750]
It's not always possible to install a profile on Apple devices, so it would be great if there is an explanation of how to set up an IKEv2 VPN on a client manually with the provided certificate and .conf files. If this is not possible on mobile devices, then an explanation can be included on how it is accomplished on MacOS.

**Comment by jackivanov** [comment]
Unfortunately, most of options that we support can not be enabled/changed without profiles. I believe that there's no simple way to do that on MacOS either. It's not a general use case, so I'm closing the issue. If you'll have more info, send a PR please.
