### ISSUE TITLE
Updating configuration

### ISSUE THREAD

**Issue by zillemarco** [trailofbits/algo#1751]
I setup Algo on a Windows Server using WSL.

How can the configuration be updated after the initial setup?
In my case I had to update the `config.cfg` to set `BetweenClients_DROP`, `block_smb` and `block_netbios` to `false` and I run `./algo` again after removing the VM from DigitalOcean. Is this the right way to go?

Also a related question, after a server reboot (the Windows Server where I setup Algo) should I run `./algo` again to restart the VPN?

**Comment by jackivanov** [comment]
There's not recommended way to update your configure as everything is set up during the initial installation and then it's on your own to manage the server. You can try to change the settings and run ./algo with the same parameters that you ran the initial setup with. This may work out for DigitalOcean, but not guaranteed. We recommend to rebuild the server entirely if you need to change anything or change it manually. You don't need to run ./algo again after server reboot.
