### ISSUE TITLE
Egress performance fix for AWS 

### ISSUE THREAD

**Issue by delmonij** [trailofbits/algo#1752]
I found that the default MTU setting on lightsail [ec2] was 9001 which led to the default MTU on wg0 being very high. I got good upload performance tests but bad download performance on phone/laptop.

I ended up creating a file on the vpn server/instance named /etc/rc.local with the following contents:

#!/bin/sh
ip link set dev eth0 mtu 1500
exit 0

I ran chmod 755 /etc/rc.local and then rebooted the instance to get excellent performance. 

Maybe this helps you too :)

**Comment by davidemyers** [comment]
What are you using to test performance?

Do you get the same results if instead of changing the MTU of `eth0` you add `MTU = 1420` to `/etc/wireguard/wg0.conf`?

**Comment by delmonij** [comment]
I used 2 popular public website tools and iperf3. I got the same [excellent] performance by setting MTU = 1420 on wg0 on the algo instance and restarting wg-quick. The MTU ends up the same in case of script above or application of that setting although I couldn't figure out a working way to set it automatically through the deployment.
