### ISSUE TITLE
How to install on same instance instead of creating new instance?

### ISSUE THREAD

**Issue by reckoner** [trailofbits/algo#1756]
**Is your feature request related to a problem? Please describe.**

On Vultr, algo script creates a new instance.

**Describe the solution you'd like**

is it possible to configure the script to install the VPN (wire guard) on the *same* instance. This avoids additional charges.

**Describe alternatives you've considered**

N/A.

**Additional context**

N/A.

**Comment by jackivanov** [comment]
If you use the same parameters as you specified during the initial setup it should be actually idempotent for most of cloud providers. I tested on DigitalOcean and AWS. Apparently Vultr may not support it and there's nothing we can do, sorry. The only suggested method is to destroy the existing instance and create a new one with parameters needed.
