### ISSUE TITLE
Attaching static IP manually cause the script to hang

### ISSUE THREAD

**Issue by 0804d23d** [trailofbits/algo#1757]
**Is your feature request related to a problem? Please describe.**
The algo scripts hang when I attach a static IP to the newly created instance. Also, in lightsail's ap-southeast-2 region, the minimal size is `nano_2_2`, not `nano_1_0`.

**Describe the solution you'd like**
Offer an option to attach a static IP to the instance before proceeding to `PLAY [Configure the server and install required software]`.

**Describe alternatives you've considered**
Wait a certain amount of time to allow manual changes to the instance before proceeding, and detect any changes to the public IP in case a static IP was attached manually.

**Additional context**
I'm trying to setup a new algo install on Lightsail (ap-southeast-2). Initially, I didn't change the size (bundleid) in the `config.cfg`, and the script failed, so I changed the relevant size to nano_2_2. After that, the script successfully created the instance. But when I manually attached a static IP to it (happened after `TASK [Wait 600 seconds for target connection to become reachable/usable]` shown `ok` with the original IP), and now, it stuck at `PLAY [Configure the server and install required software]`. I got it working by rerun the script and attaching the static IP I wanted afterwards, but the downside of this is I have to edit all of those config files manually to match the public IP the instance currently has.

**Comment by jackivanov** [comment]
We do not support static IPs for Lightsail at the moment. Although, if you're an advanced user, you can the [local installation method](https://github.com/trailofbits/algo/blob/master/docs/deploy-to-ubuntu.md) to the instance with manually assigned static IP.
