### ISSUE TITLE
Loading of cacert.pem fails in strongSwan due to X509v3 Name Constraints

### ISSUE THREAD

**Issue by jaj42** [trailofbits/algo#1758]
**Describe the bug**

The cacert.pem certificate provided by Algo cannot be loaded in strongSwan 5.7.1 due to the X509v3 Name Constraints extension in the certificate which is marked Critical.
This was previously reported to strongSwan issues: https://wiki.strongswan.org/issues/3304

**To Reproduce**

Deploy algo vpn and configure a strongSwan client on Linux according to the official documentation.

**Expected behavior**

IKEv2 IPSEC tunnel established.

**Actual behavior**

Connection fails due to absent CA cert which was not loaded.

**Additional context**

Running on Ubuntu 19.04 Disco Dingo.

**Full log**

$ tail /var/log/syslog
charon: 11[CFG] rereading ca certificates from '/etc/ipsec.d/cacerts'
charon: 11[LIB] found unsupported critical X.509 extension: X509v3 Name Constraints
charon: 11[LIB] OpenSSL X.509 parsing failed
charon: 11[LIB] building CRED_CERTIFICATE - X509 failed, tried 4 builders
charon: 11[CFG]   loading ca certificate from '/etc/ipsec.d/cacerts/cacert.pem' failed

$ openssl x509 -in cacert.pem -text    
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            37:74:5d:77:f7:42:44:2a:de:73:52:ce:8d:97:f6:30:81:14:3f:0d
        Signature Algorithm: ecdsa-with-SHA256
        Issuer: CN = 35.180.187.116
        Validity
            Not Before: Mar 14 08:56:35 2020 GMT
            Not After : Mar 12 08:56:35 2030 GMT
        Subject: CN = 35.180.187.116
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (384 bit)
                pub:
                    04:da:1e:6d:1d:13:0d:be:b6:39:10:3d:be:81:c4:
                    e8:ff:1d:56:07:e3:86:08:cf:e7:00:28:d1:c5:38:
                    26:14:c3:18:a9:d6:c5:ae:8f:f3:41:13:fd:1e:6b:
                    53:02:f9:c9:db:f8:0f:c2:db:58:f5:92:5e:4a:ed:
                    62:22:cd:70:a2:3e:42:83:4c:ff:07:47:a9:bc:20:
                    23:2f:a2:b8:dd:91:b2:70:18:49:86:60:00:2a:49:
                    a3:f1:a6:3a:b1:ec:cb
                ASN1 OID: secp384r1
                NIST CURVE: P-384
        X509v3 extensions:
            X509v3 Subject Key Identifier: 
                2B:8B:56:94:98:42:44:4B:C6:8B:B9:A8:C2:6E:89:FF:45:A2:D0:BB
            X509v3 Authority Key Identifier: 
                keyid:2B:8B:56:94:98:42:44:4B:C6:8B:B9:A8:C2:6E:89:FF:45:A2:D0:BB
                DirName:/CN=35.180.187.116
                serial:37:74:5D:77:F7:42:44:2A:DE:73:52:CE:8D:97:F6:30:81:14:3F:0D

            X509v3 Basic Constraints: critical
                CA:TRUE, pathlen:0
            X509v3 Name Constraints: critical
                Permitted:
                  IP:35.180.187.116/255.255.255.255
                  DNS:bf504b30-0553-50be-9154-972c934e4a02.algo
                  email:bf504b30-0553-50be-9154-972c934e4a02.algo
                Excluded:
                  IP:0:0:0:0:0:0:0:0/0:0:0:0:0:0:0:0

            X509v3 Key Usage: 
                Certificate Sign, CRL Sign
    Signature Algorithm: ecdsa-with-SHA256
         30:65:02:30:53:0e:4f:2e:f0:ef:d7:57:0c:3b:bc:31:28:80:
         cb:0a:80:d0:72:e8:e5:70:75:fa:ba:b2:5c:a7:d5:e3:dd:94:
         b8:f4:7d:74:95:f1:27:2e:c5:26:0a:6e:52:e5:78:b6:02:31:
         00:f1:e5:60:88:07:d3:70:fd:4b:89:7c:c5:d7:c2:a5:0a:a5:
         d5:8a:32:46:73:ae:55:ba:9e:22:4e:64:87:09:8d:aa:35:18:
         73:f0:6b:c0:57:24:27:be:60:c5:5e:97:ad
-----BEGIN CERTIFICATE-----
MIICrDCCAjKgAwIBAgIUN3Rdd/dCRCrec1LOjZf2MIEUPw0wCgYIKoZIzj0EAwIw
GTEXMBUGA1UEAwwOMzUuMTgwLjE4Ny4xMTYwHhcNMjAwMzE0MDg1NjM1WhcNMzAw
MzEyMDg1NjM1WjAZMRcwFQYDVQQDDA4zNS4xODAuMTg3LjExNjB2MBAGByqGSM49
AgEGBSuBBAAiA2IABNoebR0TDb62ORA9voHE6P8dVgfjhgjP5wAo0cU4JhTDGKnW
xa6P80ET/R5rUwL5ydv4D8LbWPWSXkrtYiLNcKI+QoNM/wdHqbwgIy+iuN2RsnAY
SYZgACpJo/GmOrHsy6OCATkwggE1MB0GA1UdDgQWBBQri1aUmEJES8aLuajCbon/
RaLQuzBUBgNVHSMETTBLgBQri1aUmEJES8aLuajCbon/RaLQu6EdpBswGTEXMBUG
A1UEAwwOMzUuMTgwLjE4Ny4xMTaCFDd0XXf3QkQq3nNSzo2X9jCBFD8NMBIGA1Ud
EwEB/wQIMAYBAf8CAQAwgZwGA1UdHgEB/wSBkTCBjqBmMAqHCCO0u3T/////MCuC
KWJmNTA0YjMwLTA1NTMtNTBiZS05MTU0LTk3MmM5MzRlNGEwMi5hbGdvMCuBKWJm
NTA0YjMwLTA1NTMtNTBiZS05MTU0LTk3MmM5MzRlNGEwMi5hbGdvoSQwIocgAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwCwYDVR0PBAQDAgEGMAoGCCqG
SM49BAMCA2gAMGUCMFMOTy7w79dXDDu8MSiAywqA0HLo5XB1+rqyXKfV492UuPR9
dJXxJy7FJgpuUuV4tgIxAPHlYIgH03D9S4l8xdfCpQql1YoyRnOuVbqeIk5khwmN
qjUYc/BrwFckJ75gxV6XrQ==
-----END CERTIFICATE-----

**Comment by jaj42** [comment]
Same behavior confirmed with strongSwan 5.7.2 on Ubuntu Eoan Ermine.
This seems to be a duplicate of issue #1745 .

**Comment by aleks-mariusz** [comment]
same issue on CentOS 7.7, which currently has this for the strongswan package:


```
[root@limey ~]# rpm -qi strongswan
Name        : strongswan
Version     : 5.7.2
Release     : 1.el7
Architecture: x86_64
[...]
Signature   : RSA/SHA256, Wed 09 Jan 2019 18:38:37 GMT, Key ID 6a2faea2352c64e5
Source RPM  : strongswan-5.7.2-1.el7.src.rpm
Build Date  : Wed 09 Jan 2019 18:17:06 GMT
[...]
```

output of `strongswan rereadcacerts`: 

```
Apr  3 18:07:56 limey charon: 13[CFG] rereading ca certificates from '/etc/strongswan/ipsec.d/cacerts'
Apr  3 18:07:56 limey charon: 13[LIB] found unsupported critical X.509 extension: X509v3 Name Constraints
Apr  3 18:07:56 limey charon: 13[LIB] OpenSSL X.509 parsing failed
Apr  3 18:07:56 limey charon: 13[LIB] building CRED_CERTIFICATE - X509 failed, tried 6 builders
Apr  3 18:07:56 limey charon: 13[CFG]   loading ca certificate from '/etc/strongswan/ipsec.d/cacerts/mycertname.pem' failed
```

**Comment by aleks-mariusz** [comment]
work-around found.. created a file `/etc/strongswan/strongswan.d/libstrongswan-relax-constraints.conf` with the following contents: ```
libstrongswan {
  x509 {
    enforce_critical = no
  }
}
```

unsure of what the security impact of this is, but the connection at least establishes now.. would be better if algo didn't use this constraint (unless it's needed for some purpose i'm not fully understanding)

**Comment by jackivanov** [comment]
It's been introduced in https://github.com/trailofbits/algo/pull/1675 and we set `enforce_critical = no` on the server side already. Need a PR to document the client config changes

**Comment by JACKHAHA363** [comment]
Thank you @jackivanov  @aleks-mariusz! Change the strongwan config file works for me.

**Comment by aleks-mariusz** [comment]
> It's been introduced in #1675 and we set `enforce_critical = no` on the server side already. Need a PR to document the client config changes

https://github.com/trailofbits/algo/pull/1768

**Comment by jaj42** [comment]
I confirm that this "fixes" the issue for me as well. However, if I understand correctly, this disables the security check. Did this work at some point and is it a strongswan regression or am I the first one to connect to an algo instance using strongswan since January?

**Comment by Onozulus** [comment]
> **Describe the bug**
> 
> The cacert.pem certificate provided by Algo cannot be loaded in strongSwan 5.7.1 due to the X509v3 Name Constraints extension in the certificate which is marked Critical. This was previously reported to strongSwan issues: https://wiki.strongswan.org/issues/3304
> 
> **To Reproduce**
> 
> Steps to reproduce the behavior: Deploy algo vpn and configure a strongSwan client on Linux according to the official documentation.
> 
> **Expected behavior**
> 
> IKEv2 IPSEC tunnel established.
> 
> **Actual behavior**
> 
> Connection fails due to absent CA cert which was not loaded.
> 
> **Additional context**
> 
> Running on Ubuntu 19.04 Disco Dingo.
> 
> **Full log**
> 
> $ tail /var/log/syslog charon: 11[CFG] rereading ca certificates from '/etc/ipsec.d/cacerts' charon: 11[LIB] found unsupported critical X.509 extension: X509v3 Name Constraints charon: 11[LIB] OpenSSL X.509 parsing failed charon: 11[LIB] building CRED_CERTIFICATE - X509 failed, tried 4 builders charon: 11[CFG] loading ca certificate from '/etc/ipsec.d/cacerts/cacert.pem' failed
> 
> $ openssl x509 -in cacert.pem -text Certificate: Data: Version: 3 (0x2) Serial Number: 37:74:5d:77:f7:42:44:2a🇩🇪73:52:ce:8d:97:f6:30:81:14:3f:0d Signature Algorithm: ecdsa-with-SHA256 Issuer: CN = 35.180.187.116 Validity Not Before: Mar 14 08:56:35 2020 GMT Not After : Mar 12 08:56:35 2030 GMT Subject: CN = 35.180.187.116 Subject Public Key Info: Public Key Algorithm: id-ecPublicKey Public-Key: (384 bit) pub: 04:da:1e:6d:1d:13:0d:be:b6:39:10:3d:be:81:c4: e8:ff:1d:56:07:e3:86:08:cf:e7:00:28:d1:c5:38: 26:14:c3:18:a9:d6:c5:ae:8f:f3:41:13:fd:1e:6b: 53:02:f9:c9:db:f8:0f:c2:db:58:f5:92:5e:4a:ed: 62:22💿70:a2:3e:42:83:4c:ff:07:47:a9:bc:20: 23:2f:a2:b8:dd:91:b2:70:18:49:86:60:00:2a:49: a3:f1:a6:3a:b1:ec:cb ASN1 OID: secp384r1 NIST CURVE: P-384 X509v3 extensions: X509v3 Subject Key Identifier: 2B:8B:56:94:98:42:44:4B:C6:8B:B9:A8:C2:6E:89:FF:45:A2:D0:BB X509v3 Authority Key Identifier: keyid:2B:8B:56:94:98:42:44:4B:C6:8B:B9:A8:C2:6E:89:FF:45:A2:D0:BB DirName:/CN=35.180.187.116 serial:37:74:5D:77:F7:42:44:2A:DE:73:52:CE:8D:97:F6:30:81:14:3F:0D
> 
> ```
>         X509v3 Basic Constraints: critical
>             CA:TRUE, pathlen:0
>         X509v3 Name Constraints: critical
>             Permitted:
>               IP:35.180.187.116/255.255.255.255
>               DNS:bf504b30-0553-50be-9154-972c934e4a02.algo
>               email:bf504b30-0553-50be-9154-972c934e4a02.algo
>             Excluded:
>               IP:0:0:0:0:0:0:0:0/0:0:0:0:0:0:0:0
> 
>         X509v3 Key Usage: 
>             Certificate Sign, CRL Sign
> Signature Algorithm: ecdsa-with-SHA256
>      30:65:02:30:53:0e:4f:2e:f0:ef:d7:57:0c:3b:bc:31:28:80:
>      cb:0a:80:d0:72:e8:e5:70:75:fa:ba:b2:5c:a7:d5:e3:dd:94:
>      b8:f4:7d:74:95:f1:27:2e:c5:26:0a:6e:52:e5:78:b6:02:31:
>      00:f1:e5:60:88:07:d3:70:fd:4b:89:7c:c5:d7:c2:a5:0a:a5:
>      d5:8a:32:46:73:ae:55:ba:9e:22:4e:64:87:09:8d:aa:35:18:
>      73:f0:6b:c0:57:24:27:be:60:c5:5e:97:ad
> ```
> 
> -----BEGIN CERTIFICATE----- MIICrDCCAjKgAwIBAgIUN3Rdd/dCRCrec1LOjZf2MIEUPw0wCgYIKoZIzj0EAwIw GTEXMBUGA1UEAwwOMzUuMTgwLjE4Ny4xMTYwHhcNMjAwMzE0MDg1NjM1WhcNMzAw MzEyMDg1NjM1WjAZMRcwFQYDVQQDDA4zNS4xODAuMTg3LjExNjB2MBAGByqGSM49 AgEGBSuBBAAiA2IABNoebR0TDb62ORA9voHE6P8dVgfjhgjP5wAo0cU4JhTDGKnW xa6P80ET/R5rUwL5ydv4D8LbWPWSXkrtYiLNcKI+QoNM/wdHqbwgIy+iuN2RsnAY SYZgACpJo/GmOrHsy6OCATkwggE1MB0GA1UdDgQWBBQri1aUmEJES8aLuajCbon/ RaLQuzBUBgNVHSMETTBLgBQri1aUmEJES8aLuajCbon/RaLQu6EdpBswGTEXMBUG A1UEAwwOMzUuMTgwLjE4Ny4xMTaCFDd0XXf3QkQq3nNSzo2X9jCBFD8NMBIGA1Ud EwEB/wQIMAYBAf8CAQAwgZwGA1UdHgEB/wSBkTCBjqBmMAqHCCO0u3T/////MCuC KWJmNTA0YjMwLTA1NTMtNTBiZS05MTU0LTk3MmM5MzRlNGEwMi5hbGdvMCuBKWJm NTA0YjMwLTA1NTMtNTBiZS05MTU0LTk3MmM5MzRlNGEwMi5hbGdvoSQwIocgAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwCwYDVR0PBAQDAgEGMAoGCCqG SM49BAMCA2gAMGUCMFMOTy7w79dXDDu8MSiAywqA0HLo5XB1+rqyXKfV492UuPR9 dJXxJy7FJgpuUuV4tgIxAPHlYIgH03D9S4l8xdfCpQql1YoyRnOuVbqeIk5khwmN qjUYc/BrwFckJ75gxV6XrQ== -----END CERTIFICATE-----
