### ISSUE TITLE
Connectivity issues using a single config across multiple users.

### ISSUE THREAD

**Issue by xavidram** [trailofbits/algo#1759]
**Describe the bug**

**To Reproduce**

1. Generate a single configuration file for Algo & Wireguard
2. Connect multiple machines through this single Config
3. Attempt to do work...

**Expected behavior**

Assuming Algo supports multiple connections, I thought it would also handle multiple connections from a single config. I have tested this with different machines using their own individual configuration files generated by Algo for Wireguard. And those work fine.

**Additional context**

We are preparing to go full remote, and needed a way to mass deploy and configure a vpn connection to our non-technical employees without having to stress them out. Easiest thing we would think of is generate a wireguard config and deploy it as a service to all machines. This worked on by two test machines, but once I hit about 5 machines for testing, I started noticing network disconnects when trying to use resources across the vpn. For example, when RDPing into network VMs through the VPN connection, me and another developer were constantly getting "connection retry" attempts from the RDP.

Is is recommended that each user have their own config file?

**Comment by davidemyers** [comment]
Step 5 in the README says,
> Create a unique user for each device you plan to connect to your VPN.

**Comment by xavidram** [comment]
Hence why it is called a README. Got it. Thanks!
