### ISSUE TITLE
How to configure IPsec with ikev2?

### ISSUE THREAD

**Issue by PedroPCardoso** [trailofbits/algo#1760]
I created a ubuntu 18.04 server, now I need to use ipsec for an RV340 router.

But there are some fields that I don't know which options to use.

I tried to use the project https://github.com/davidemyers/algo-pfsense, but without success, I did not find in the documentation anything that would explain the steps to solve this type of problem.

Note: I created a .pem

![image_2020_03_19T14_27_47_786Z](https://user-images.githubusercontent.com/7657883/77355742-c7b48180-6d23-11ea-88d8-864cf2a26fb1.png)
![image_2020_03_19T14_30_18_671Z](https://user-images.githubusercontent.com/7657883/77355745-c97e4500-6d23-11ea-96f4-077db4e908eb.png)
![image_2020_03_19T14_30_45_471Z](https://user-images.githubusercontent.com/7657883/77355747-ca16db80-6d23-11ea-97e0-a210fcdc43f2.png)
![image_2020_03_19T14_33_43_792Z](https://user-images.githubusercontent.com/7657883/77355749-caaf7200-6d23-11ea-8a93-5cf994e66bbb.png)

**Comment by jackivanov** [comment]
You need to configure Certificate based authentication methods on your router and load the certs that Algo generate to your router.  Try to follow the documentation of your vendor
