### ISSUE TITLE
Out of disk space

### ISSUE THREAD

**Issue by markrrr** [trailofbits/algo#1761]
**Is your feature request related to a problem? Please describe.**
I've set up algo on a ubuntu server, following the 'local installation' instructions. The server has 2.7G storage. Installation went fine, wireguard VPN is running fine for 2 months... however the disk is now 100% full so I can't do an apt upgrade.

**Describe the solution you'd like**
1. I would like the instructions to include a minimal server spec (especially storage requirement)
2. I'd like to know what files / directories can be purged after a local installation to free up more disk space

**Describe alternatives you've considered**
I've used journalctl to purge and turn off logging, but the disk space just keeps filling up... there must be some other files growing somewhere.

**Comment by Joshfindit** [comment]
This is not an answer, and in no way represents the direction of algo (which I literally just found via hn), I just happen to know one or two things about cramped disk space:

- `du -hs` is installed by default in Ubuntu, creates no additional files, and allows you to (manually) drill down to find large folders and large files. Especially handy as `ds -hs *`
- `lsof` lets you see files that are currently open. `lsof | grep “<process or file>”` can be used for more granularity
- `apt-get autoclean` still works in current versions of Ubuntu to delete `apt`’s cruft, but needs space (a couple hundred MB is a comfortable margin)

**Comment by jackivanov** [comment]
Once you created a box using Algo it's on your own to manage it. You can try to ask on [gitter](https://gitter.im/trailofbits/algo)

**Comment by Bizzaro** [comment]
@markrrr if you're still looking for solutions, this is what I did:
There were no other files that showed up on my VM other than log files. I'm down to 7GB used on the entire VM.

Show disk usage on the the system in megabytes:
`df -m`

Retain only the last 500MB:
`journalctl --vacuum-size=500M`  

Find files on root partition `/` and display in megabytes `-m`, sort descending `sort -nr`, top 20 results `head -n 20` 
`sudo du / -m | sort -nr | head -n 20`
