### ISSUE TITLE
Cannot reach peers - Wireguard

### ISSUE THREAD

**Issue by blasrodri** [trailofbits/algo#1762]
**Describe the bug**
Cannot ping peers connected to the vpn from another peer. I can do it from the server. And I can ping the server from each peer.

**To Reproduce**

1. Get the peers ip. From the server, run `sudo wg`
2. ping -c1 peer_ip

**Expected behavior**

Get a successful response from the command

**Additional context**
I've been able to reach the server from peer1, and peer2, but cannot reach the peers from each other.
I've checked that the traffic is being forwarded on the server.
`/etc/sysctl.d/99-sysctl.conf`
```
net.ipv4.ip_forward=1
net.ipv4.conf.all.forwarding=1

```
The `AllowedIPs = 0.0.0.0/0` is set up for the two peers.
What am I missing?
server:

```
$ sudo wg
interface: wg0
  public key: VX8FBFlf/4seRurvmxHMIlK98qGZYBuOdFxGM7PYKiU=
  private key: (hidden)
  listening port: 56862
  fwmark: 0xca6c

peer: JHCqKOx4WoM9mCPmj28T8k8KoJksuyuIMDRxko3HFBc=
  preshared key: (hidden)
endpoint: server_host:server_port
  allowed ips: 0.0.0.0/0, ::/0
  latest handshake: 1 minute, 4 seconds ago
  transfer: 1.49 MiB received, 1.05 MiB sent
```

peer 1:
```
interface: wg0
  public key: <...>
  private key: (hidden)
  listening port: 56862
  fwmark: 0xca6c

peer: <...>
  preshared key: (hidden)
  endpoint: server_host:server_port
  allowed ips: 0.0.0.0/0, ::/0
  latest handshake: 3 seconds ago
  transfer: 14.71 KiB received, 22.97 KiB sent
```
peer2
```
sudo wg
interface: wg0
  public key: <>
  private key: (hidden)
  listening port: 47031
  fwmark: 0xca6c
peer: <>
  preshared key: (hidden)
  endpoint: server_host:server_port
  allowed ips: 0.0.0.0/0, ::/0
  latest handshake: 55 seconds ago
  transfer: 43.74 MiB received, 3.51 MiB sent
```

**Full log**

```
```

**Comment by davidemyers** [comment]
See `BetweenClients_DROP` in `config.cfg`.

**Comment by blasrodri** [comment]
@davidemyers Thanks a lot! I've found [How do I reach another connected client?](https://github.com/trailofbits/algo/blob/master/docs/faq.md#how-do-i-reach-another-connected-client) following your pointer.
