### ISSUE TITLE
Add COVID-19 Blocklists to DNS Adblocking

### ISSUE THREAD

**Issue by unstatusthequo** [trailofbits/algo#1765]
There's a significant uptick in COVID-19 related cyber threats.  Given that Algo already supports DNS adblocking, why not include dangerous COVID-19 related domains, IPs, and URLs (if the latter is possible). 

I am part of a [COVID-10 Cyber Threat Intelligence League](https://cti-league.com/) and think using our public release blocklist would be great.  My sense is this could be easily done. 

The blocklists are available here, and are human-vetted: [COVID-19 CTI Blocklists](https://github.com/COVID-19-CTI-LEAGUE/PUBLIC_RELEASE)

**Comment by jackivanov** [comment]
At the moment we're not going to change the defaults, but you can modify that for your setup [here](https://github.com/trailofbits/algo/blob/master/config.cfg#L50)
