### ISSUE TITLE
Installing algo in windows server 2019 Datacenter

### ISSUE THREAD

**Issue by imanvosghi** [trailofbits/algo#1767]
Hello,

Currently I want to deploy the ALGO in Ubunto 18.04 from WSL in windows server 2019 Datacenter.
My server is in Microsoft Azure. I opened the required ports (4500,500,4160) in my VM firewall and also configure them in windows internal firewall as well.

At the last part of the installing algo, I reached this error.
Would you please help me to solve this issue .

Thanks.

`
user@server:~/algo$ sudo ./algo
[WARNING]: Could not match supplied host pattern, ignoring: vpn-host

PLAY [localhost] *********************************************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************************************
ok: [localhost]

TASK [Playbook dir stat] *************************************************************************************************************************************************************
ok: [localhost]

TASK [Ensure Ansible is not being run in a world writable directory] *****************************************************************************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [Ensure the requirements installed] *********************************************************************************************************************************************
ok: [localhost]

TASK [Set required ansible version as a fact] ****************************************************************************************************************************************
ok: [localhost] => (item=ansible==2.8.8)

TASK [Verify Python meets Algo VPN requirements] *************************************************************************************************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [Verify Ansible meets Algo VPN requirements] ************************************************************************************************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

PLAY [Ask user for the input] ********************************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************************************
ok: [localhost]
[Cloud prompt]
What provider would you like to use?
    1. DigitalOcean
    2. Amazon Lightsail
    3. Amazon EC2
    4. Microsoft Azure
    5. Google Compute Engine
    6. Hetzner Cloud
    7. Vultr
    8. Scaleway
    9. OpenStack (DreamCompute optimised)
    10. CloudStack (Exoscale optimised)
    11. Install to existing Ubuntu 18.04 or 19.10 server (for more advanced users)

Enter the number of your desired provider
:

TASK [Cloud prompt] ******************************************************************************************************************************************************************
ok: [localhost]

TASK [Set facts based on the input] **************************************************************************************************************************************************
ok: [localhost]
[Cellular On Demand prompt]
Do you want macOS/iOS clients to enable "Connect On Demand" when connected to cellular networks?
[y/N]
:

TASK [Cellular On Demand prompt] *****************************************************************************************************************************************************
ok: [localhost]
[Wi-Fi On Demand prompt]
Do you want macOS/iOS clients to enable "Connect On Demand" when connected to Wi-Fi?
[y/N]
:

TASK [Wi-Fi On Demand prompt] ********************************************************************************************************************************************************
ok: [localhost]
[Trusted Wi-Fi networks prompt]
List the names of any trusted Wi-Fi networks where macOS/iOS clients should not use "Connect On Demand"
(e.g., your home network. Comma-separated value, e.g., HomeNet,OfficeWifi,AlgoWiFi)
:

TASK [Trusted Wi-Fi networks prompt] *************************************************************************************************************************************************
ok: [localhost]
[Retain the PKI prompt]
Do you want to retain the keys (PKI)? (required to add users in the future, but less secure)
[y/N]
:

TASK [Retain the PKI prompt] *********************************************************************************************************************************************************
ok: [localhost]
[DNS adblocking prompt]
Do you want to enable DNS ad blocking on this VPN server?
[y/N]
:

TASK [DNS adblocking prompt] *********************************************************************************************************************************************************
ok: [localhost]
[SSH tunneling prompt]
Do you want each user to have their own account for SSH tunneling?
[y/N]
:

TASK [SSH tunneling prompt] **********************************************************************************************************************************************************
ok: [localhost]

TASK [Set facts based on the input] **************************************************************************************************************************************************
ok: [localhost]

PLAY [Provision the server] **********************************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************************************
ok: [localhost]

--> Please include the following block of text when reporting issues:

Algo running on: Ubuntu 18.04.1 LTS (Virtualized: microsoft)
Created from git fork. Last commit: c231cd4 Bump ansible from 2.8.3 to 2.8.8 (#1736)
Python 3.6.9
Runtime variables:
    algo_provider "local"
    algo_ondemand_cellular "True"
    algo_ondemand_wifi "True"
    algo_ondemand_wifi_exclude "X251bGw="
    algo_dns_adblocking "True"
    algo_ssh_tunneling "True"
    wireguard_enabled "True"
    dns_encryption "True"

TASK [Display the invocation environment] ********************************************************************************************************************************************
changed: [localhost -> localhost]

TASK [Install the requirements] ******************************************************************************************************************************************************
ok: [localhost -> localhost]
[local : pause]
Enter the IP address of your server: (or use localhost for local installation):
[localhost]
:

TASK [local : pause] *****************************************************************************************************************************************************************
ok: [localhost]

TASK [local : Set the facts] *********************************************************************************************************************************************************
ok: [localhost]
[local : pause]
Enter the public IP address or domain name of your server: (IMPORTANT! This is used to verify the certificate)
[localhost]
:

TASK [local : pause] *****************************************************************************************************************************************************************
ok: [localhost]

TASK [local : Set the facts] *********************************************************************************************************************************************************
ok: [localhost]

TASK [Set subjectAltName as a fact] **************************************************************************************************************************************************
ok: [localhost]

TASK [Add the server to an inventory group] ******************************************************************************************************************************************
changed: [localhost]

TASK [debug] *************************************************************************************************************************************************************************
ok: [localhost] => {
    "IP_subject_alt_name": "22.XXX.222.XXX"
}
[WARNING]: Reset is not implemented for this connection

TASK [Wait 600 seconds for target connection to become reachable/usable] *************************************************************************************************************
ok: [localhost -> localhost] => (item=localhost)

PLAY [Configure the server and install required software] ****************************************************************************************************************************

TASK [common : Check the system] *****************************************************************************************************************************************************
ok: [localhost]
included: /home/user/algo/roles/common/tasks/ubuntu.yml for localhost

TASK [common : Gather facts] *********************************************************************************************************************************************************
ok: [localhost]

TASK [common : Install unattended-upgrades] ******************************************************************************************************************************************
ok: [localhost]

TASK [common : Configure unattended-upgrades] ****************************************************************************************************************************************
ok: [localhost]

TASK [common : Periodic upgrades configured] *****************************************************************************************************************************************
ok: [localhost]

TASK [common : Disable MOTD on login and SSHD] ***************************************************************************************************************************************
ok: [localhost] => (item={'regexp': '^session.*optional.*pam_motd.so.*', 'line': '# MOTD DISABLED', 'file': '/etc/pam.d/login'})
ok: [localhost] => (item={'regexp': '^session.*optional.*pam_motd.so.*', 'line': '# MOTD DISABLED', 'file': '/etc/pam.d/sshd'})

TASK [common : Loopback for services configured] *************************************************************************************************************************************
ok: [localhost]

TASK [common : systemd services enabled and started] *********************************************************************************************************************************
failed: [localhost] (item=systemd-networkd) => {"ansible_loop_var": "item", "changed": false, "item": "systemd-networkd", "msg": "failure 1 during daemon-reload: System has not been booted with systemd as init system (PID 1). Can't operate.\n"}
failed: [localhost] (item=systemd-resolved) => {"ansible_loop_var": "item", "changed": false, "item": "systemd-resolved", "msg": "failure 1 during daemon-reload: System has not been booted with systemd as init system (PID 1). Can't operate.\n"}
included: /home/user/algo/playbooks/rescue.yml for localhost

TASK [debug] *************************************************************************************************************************************************************************
ok: [localhost] => {
    "fail_hint": [
        "Sorry, but something went wrong!",
        "Please check the troubleshooting guide.",
        "https://trailofbits.github.io/algo/troubleshooting.html"
    ]
}

TASK [Fail the installation] *********************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed as requested from task"}

PLAY RECAP ***************************************************************************************************************************************************************************
localhost                  : ok=38   changed=2    unreachable=0    failed=1    skipped=20   rescued=1    ignored=0

user@server:~/algo$

'

**Comment by imanvosghi** [comment]
Hi,
This erro is now solved by changing the "localhost" to my actual local ip address.
After that, I had problem with SSH service on ubuntu. 
I install the ssh servie with this command `sudo apt install ssh`. Then I checked the SSH service with thiscommand 
`sudo /etc/init.d/ssh start                Starting OpenBSD Secure Shell server sshd                                                                     [ OK ]`

Bu it got this error : 
`TASK [Wait 600 seconds for target connection to become reachable/usable] ***********************************************
failed: [localhost -> 10.0.1.4] (item=10.0.1.4) => {"ansible_loop_var": "item", "changed": false, "elapsed": 780, "item": "10.0.1.4", "msg": "timed out waiting for ping module test success: Failed to connect to the host via ssh: Warning: Permanently added '10.0.1.4' (ECDSA) to the list of known hosts.\r\nmpadmin@10.0.1.4: Permission denied (publickey)."}
included: /home/mpadmin/algo/playbooks/rescue.yml for localhost`


Here is the full log: 

`user@MP-VM01:~/algo$ sudo ./algo

PLAY [localhost] *******************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************
ok: [localhost]

TASK [Playbook dir stat] ***********************************************************************************************
ok: [localhost]

TASK [Ensure Ansible is not being run in a world writable directory] ***************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [Ensure the requirements installed] *******************************************************************************
ok: [localhost]

TASK [Set required ansible version as a fact] **************************************************************************
ok: [localhost] => (item=ansible==2.8.8)

TASK [Verify Python meets Algo VPN requirements] ***********************************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [Verify Ansible meets Algo VPN requirements] **********************************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

PLAY [Ask user for the input] ******************************************************************************************

TASK [Gathering Facts] *************************************************************************************************
ok: [localhost]
[Cloud prompt]
What provider would you like to use?
    1. DigitalOcean
    2. Amazon Lightsail
    3. Amazon EC2
    4. Microsoft Azure
    5. Google Compute Engine
    6. Hetzner Cloud
    7. Vultr
    8. Scaleway
    9. OpenStack (DreamCompute optimised)
    10. CloudStack (Exoscale optimised)
    11. Install to existing Ubuntu 18.04 or 19.10 server (for more advanced users)

Enter the number of your desired provider
:

TASK [Cloud prompt] ****************************************************************************************************
ok: [localhost]

TASK [Set facts based on the input] ************************************************************************************
ok: [localhost]
[Cellular On Demand prompt]
Do you want macOS/iOS clients to enable "Connect On Demand" when connected to cellular networks?
[y/N]
:

TASK [Cellular On Demand prompt] ***************************************************************************************
ok: [localhost]
[Wi-Fi On Demand prompt]
Do you want macOS/iOS clients to enable "Connect On Demand" when connected to Wi-Fi?
[y/N]
:

TASK [Wi-Fi On Demand prompt] ******************************************************************************************
ok: [localhost]
[Trusted Wi-Fi networks prompt]
List the names of any trusted Wi-Fi networks where macOS/iOS clients should not use "Connect On Demand"
(e.g., your home network. Comma-separated value, e.g., HomeNet,OfficeWifi,AlgoWiFi)
:

TASK [Trusted Wi-Fi networks prompt] ***********************************************************************************
ok: [localhost]
[Retain the PKI prompt]
Do you want to retain the keys (PKI)? (required to add users in the future, but less secure)
[y/N]
:

TASK [Retain the PKI prompt] *******************************************************************************************
ok: [localhost]
[DNS adblocking prompt]
Do you want to enable DNS ad blocking on this VPN server?
[y/N]
:

TASK [DNS adblocking prompt] *******************************************************************************************
ok: [localhost]
[SSH tunneling prompt]
Do you want each user to have their own account for SSH tunneling?
[y/N]
:

TASK [SSH tunneling prompt] ********************************************************************************************
ok: [localhost]

TASK [Set facts based on the input] ************************************************************************************
ok: [localhost]

PLAY [Provision the server] ********************************************************************************************

TASK [Gathering Facts] *************************************************************************************************
ok: [localhost]

--> Please include the following block of text when reporting issues:

Algo running on: Ubuntu 18.04.1 LTS (Virtualized: microsoft)
Created from git fork. Last commit: c231cd4 Bump ansible from 2.8.3 to 2.8.8 (#1736)
Python 3.6.9
Runtime variables:
    algo_provider "local"
    algo_ondemand_cellular "True"
    algo_ondemand_wifi "True"
    algo_ondemand_wifi_exclude "X251bGw="
    algo_dns_adblocking "True"
    algo_ssh_tunneling "True"
    wireguard_enabled "True"
    dns_encryption "True"

TASK [Display the invocation environment] ******************************************************************************
changed: [localhost -> localhost]

TASK [Install the requirements] ****************************************************************************************
ok: [localhost -> localhost]
[local : pause]
Enter the IP address of your server: (or use localhost for local installation):
[localhost]
:

TASK [local : pause] ***************************************************************************************************
ok: [localhost]

TASK [local : Set the facts] *******************************************************************************************
ok: [localhost]
[local : pause]
What user should we use to login on the server? (note: passwordless login required, or ignore if you're deploying to localhost)
[root]
:

TASK [local : pause] ***************************************************************************************************
ok: [localhost]

TASK [local : Set the facts] *******************************************************************************************
ok: [localhost]
[local : pause]
Enter the public IP address or domain name of your server: (IMPORTANT! This is used to verify the certificate)
[10.0.1.4]
:

TASK [local : pause] ***************************************************************************************************
ok: [localhost]

TASK [local : Set the facts] *******************************************************************************************
ok: [localhost]

TASK [Set subjectAltName as a fact] ************************************************************************************
ok: [localhost]

TASK [Add the server to an inventory group] ****************************************************************************
changed: [localhost]

TASK [Wait until SSH becomes ready...] *********************************************************************************
ok: [localhost]

TASK [debug] ***********************************************************************************************************
ok: [localhost] => {
    "IP_subject_alt_name": "123.456.789.123"
}






TASK [Wait 600 seconds for target connection to become reachable/usable] ***********************************************
failed: [localhost -> 10.0.1.4] (item=10.0.1.4) => {"ansible_loop_var": "item", "changed": false, "elapsed": 780, "item": "10.0.1.4", "msg": "timed out waiting for ping module test success: Failed to connect to the host via ssh: Warning: Permanently added '10.0.1.4' (ECDSA) to the list of known hosts.\r\nuser@10.0.1.4: Permission denied (publickey)."}
included: /home/user/algo/playbooks/rescue.yml for localhost

TASK [debug] ***********************************************************************************************************
ok: [localhost] => {
    "fail_hint": [
        "Sorry, but something went wrong!",
        "Please check the troubleshooting guide.",
        "https://trailofbits.github.io/algo/troubleshooting.html"
    ]
}

TASK [Fail the installation] *******************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed as requested from task"}

PLAY RECAP *************************************************************************************************************
localhost                  : ok=32   changed=2    unreachable=0    failed=1    skipped=10   rescued=1    ignored=0

user@MP-VM01:~/algo$`

**Comment by jackivanov** [comment]
Local installation is for advanced users. It's not a bug so, for further questions use [Gitter](https://gitter.im/trailofbits/algo)

**Comment by jackivanov** [comment]
Moreover it seems like you're trying to install Algo on your local machine by using localhost/10.0.1.4.
