### ISSUE TITLE
Wrong server location set during deployment

### ISSUE THREAD

**Issue by SimoneBovi** [trailofbits/algo#1769]
I used the script provided on a Digital Ocean VPS and during the deployment script I chose the location of my server to be in Germany.
However, once connected to Wireguard, my IP results to be from United States.

Is this a known bug?
Is there a way to verify this or change the country?

Thanks in advance, this project is really great! :)

**Comment by alihazemfarouk** [comment]
Facing the same issue here, using DigitalOcean and WireGuard as well. It appears to be random, sometimes the IP results are from Germany, some other times the Unites States

**Comment by davidemyers** [comment]
If Algo created the server in the correct DigitalOcean region then it's working correctly.

IP location databases contain guesses as to where an IP is located and are often wrong.
