### ISSUE TITLE
Communicate clients within the VPN

### ISSUE THREAD

**Issue by b1tdreamer** [trailofbits/algo#1772]
simple question, how can I configure algoserver to allow clients see other clients in the VPN?

Once connected to the algo server I can't see the rest of the ips that are connected.

**Comment by b1tdreamer** [comment]
https://github.com/trailofbits/algo/issues/640

Here's some information ;)

**Comment by dellgusta** [comment]
I did not tested but there is an option that allows you to communicate with other connected clients. also allows you to commuicate with hosts in the same LAN as your Algo server.
Please check:
./algo/config.cfg
```
# Block traffic between connected clients. Change this to false to enable
# connected clients to reach each other, as well as other computers on the
# same LAN as your Algo server (i.e. the "road warrior" setup). In this
# case, you may also want to enable SMB/CIFS and NETBIOS traffic below.
BetweenClients_DROP: true
```
