### ISSUE TITLE
unable to telnet private ip while the public ip is working

### ISSUE THREAD

**Issue by tahseen2k8** [trailofbits/algo#1776]
**i have created a VPC in Digital Ocean and have multiple droplet including VPN . when i am trying to access any server via public ip it is working fine but private ip is not working at all . **

the telnet keep processing and not showing any result on private ip. but same work for public ip like charm. is there any setting whihc i need to enable to access private ip with VPN. ideally it should work if both are in same VPC.

**Comment by TC1977** [comment]
I'm not sure what this exactly means, but try deploying again with the option `BetweenClients_DROP` set to `false` in `config.cfg`.

**Comment by jackivanov** [comment]
Please ask questions on [Gitter](https://gitter.im/trailofbits/algo)
