### ISSUE TITLE
"Could not build wheels for cryptography which use PEP 517 and cannot be installed directly"

### ISSUE THREAD

**Issue by sethgoldin** [trailofbits/algo#1778]
**Describe the bug**

Trying to install for Ubuntu 18.04.4 LTS in Lightsail, but suffering some sort of dependency issue with PEP 517.

**To Reproduce**

1. Create Ubuntu 18.04 instance in Lightsail, attach static IP, SSH into it from a client with the private key.
2. `$ sudo apt update`
3. `$ sudo apt upgrade`
4. `$ git clone https://github.com/trailofbits/algo.git`
5. `$ cd algo/`
6. `$ sudo apt install -y python3-virtualenv`
7.  Run:

```
python3 -m virtualenv --python="$(command -v python3)" .env &&
  source .env/bin/activate &&
  python3 -m pip install -U pip virtualenv &&
  python3 -m pip install -r requirements.txt
```

**Expected behavior**

Dependencies should install.

**Additional context**

Not sure if relevant, but when upgrading, I choose to keep "local copy" of config files, since I presume they're specific to the Lightsail instances.

**Full log**

```
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.6m -I/home/ubuntu/algo/.env/include/python3.6m -c build/temp.linux-x86_64-3.6/_openssl.c -o build/temp.linux-x86_64-3.6/build/temp.linux-x86_64-3.6/_openssl.o -Wconversion -Wno-error=sign-conversion
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for cryptography
Successfully built ansible PyYAML
Failed to build cryptography
ERROR: Could not build wheels for cryptography which use PEP 517 and cannot be installed directly
```

**Comment by sethgoldin** [comment]
Running the commands separately instead of gluing them together with `&&`, I found it's the last one: `$ python3 -m pip install -r requirements.txt`. Going to take a look inside `requirements.txt` and see if I can have it install PEP 517.

**Comment by sethgoldin** [comment]
So to get [PEP 517](https://pypi.org/project/pep517/), turns out I just needed to run `$ pip install pep517` before running `$ python3 -m pip install -r requirements.txt`. Wondering if that should be added into the README.md as a step before `$ python3 -m pip install -r requirements.txt`.

**Comment by sethgoldin** [comment]
@davidemyers When you upgraded Ubuntu, did you choose each "local" config file?

**Comment by davidemyers** [comment]
I hit return at each prompt, which I believe preserves the local version of each file. I didn't reboot after the upgrades since you didn't mention rebooting.

**Comment by sethgoldin** [comment]
Oops, I should have specified--I did in fact let it reboot to restart whatever services the prompt was asking about during the upgrade. Should I update my original post?

**Comment by davidemyers** [comment]
I rebooted, deleted the `~/algo` and `~/.cache` directories, and was still able to set up Algo without error.

**Comment by sethgoldin** [comment]
Not sure what transient issues might be at play right now. I'm also not getting any prompt to retain or discard the encryption keys when I run `./algo`. Going to destroy the VM and try again, and see if the PEP 517 error comes up again.

**Comment by sethgoldin** [comment]
Chose to use maintainer's version of `grub` this time, and now installing `requirements.txt` works fine. Can't replicate. Not sure what might have happened.
