### ISSUE TITLE
No option to retain or discard keys during deployment

### ISSUE THREAD

**Issue by sethgoldin** [trailofbits/algo#1779]
**Describe the bug**

No prompt for `Do you want to retain the keys (PKI)?` when running `$ ./algo` on a Lightsail instance.

**To Reproduce**

1. Follow [README.md](README.md) for Lightsail, exactly.
2. `config.cfg` file has 11 users, `ipsec_enabled:` set to `false`
3. `config.cfg` file also has `BetweenClients_DROP:`, `block_smb:`, and `block_netbios:` all set to `false`.
3. When running `$ sudo apt update && sudo apt upgrade`, allow services to restart, keep local copy of `sshd` config file, and use maintainer's copy of `grub`.

**Expected behavior**

When running `$ ./algo`, I expect to see a prompt for `Do you want to retain the keys (PKI)?` at some point before "success" messsage.

**Additional context**

The prompt just doesn't come up as a step. Adding another user into `config.cfg` and then running `$ ./algo update-users` in the virtual environment does seem to work, so I guess the keys are indeed saved. I just figured I'd need to specify, and users may indeed prefer the ability to discard the keys for some hardened installations.

**Comment by davidemyers** [comment]
The PKI in question is used with IPsec, but you've disabled IPsec so there's nothing to retain.

**Comment by sethgoldin** [comment]
Makes sense. Thank you!
