### ISSUE TITLE
Provide choice of VM hardware config in Lightsail

### ISSUE THREAD

**Issue by sethgoldin** [trailofbits/algo#1780]
**Is your feature request related to a problem? Please describe.**
After connecting about five or six users, performance totally tanks on the Lightsail instance because it's just the bare bones $3.50/month instance. Theoretically 250 users are supported, but if I get stuck up into the burstable zone permanently with the $3.50/month server, this is a no-go.

I figured maybe the instance that gets created is just a clone of whatever the initial instance is, but alas, I tried with a bigger one for my initial vanilla Ubuntu install, and the one that Algo created was just the small $3.50/month one.

**Describe the solution you'd like**
I want to choose the specs for the Lightsail instance, perhaps as a prompt when running `$ ./algo` or as a setting in the `config.cfg` file.

**Describe alternatives you've considered**
I ran `$ ./algo` to get the bare bones $3.50/month VM created, but then created a snapshot and cloned it into a more powerful instance. Then after `scp`ing the `wireguard` folder out, I had to `sed s/original.endpoint.ip/new.endpoint.ip/g` for all the `.conf` files in that `wireguard` folder before distributing them out to users. This is definitely a headache if I ever want to add users...

I may be thinking about this the wrong way. I saw on Gitter a suggestion to just do a local install to a Lightsail instance that already has a static IP--then I can just clone a snapshot, detach the static IP, and then attach it to my new, beefier VM.

**Comment by davidemyers** [comment]
You can already specify the instance size you want in `config.cfg`. Near the bottom of the file see `cloud_providers:`, `lightsail:`, `size:`.

The trick is finding the right value for `size:`. There might be a better way, but I think you have to install the [AWS CLI](https://lightsail.aws.amazon.com/ls/docs/en_us/articles/lightsail-how-to-set-up-and-configure-aws-cli) tool and run something like [aws lightsail get-bundles](https://docs.aws.amazon.com/cli/latest/reference/lightsail/get-bundles.html).

**Comment by sethgoldin** [comment]
Interesting. Not even [the documentation](https://docs.aws.amazon.com/cli/latest/reference/lightsail/get-bundles.html) lists everything out.

Maybe this would be helpful for others:

```
BUNDLES nano_2_0        1       20      nano    True    Nano    300     3.5     0.5     1024
SUPPORTEDPLATFORMS      LINUX_UNIX
BUNDLES micro_2_0       1       40      micro   True    Micro   500     5.0     1.0     2048
SUPPORTEDPLATFORMS      LINUX_UNIX
BUNDLES small_2_0       1       60      small   True    Small   1000    10.0    2.0     3072
SUPPORTEDPLATFORMS      LINUX_UNIX
BUNDLES medium_2_0      2       80      medium  True    Medium  2000    20.0    4.0     4096
SUPPORTEDPLATFORMS      LINUX_UNIX
BUNDLES large_2_0       2       160     large   True    Large   3000    40.0    8.0     5120
SUPPORTEDPLATFORMS      LINUX_UNIX
BUNDLES xlarge_2_0      4       320     xlarge  True    Xlarge  4000    80.0    16.0    6144
SUPPORTEDPLATFORMS      LINUX_UNIX
BUNDLES 2xlarge_2_0     8       640     2xlarge True    2Xlarge 5000    160.0   32.0    7168
SUPPORTEDPLATFORMS      LINUX_UNIX
BUNDLES nano_win_2_0    1       30      nano    True    Nano    300     8.0     0.5     1024
SUPPORTEDPLATFORMS      WINDOWS
BUNDLES micro_win_2_0   1       40      micro   True    Micro   500     12.0    1.0     2048
SUPPORTEDPLATFORMS      WINDOWS
BUNDLES small_win_2_0   1       60      small   True    Small   1000    20.0    2.0     3072
SUPPORTEDPLATFORMS      WINDOWS
BUNDLES medium_win_2_0  2       80      medium  True    Medium  2000    40.0    4.0     4096
SUPPORTEDPLATFORMS      WINDOWS
BUNDLES large_win_2_0   2       160     large   True    Large   3000    70.0    8.0     5120
SUPPORTEDPLATFORMS      WINDOWS
BUNDLES xlarge_win_2_0  4       320     xlarge  True    Xlarge  4000    120.0   16.0    6144
SUPPORTEDPLATFORMS      WINDOWS
BUNDLES 2xlarge_win_2_0 8       640     2xlarge True    2Xlarge 5000    240.0   32.0    7168
SUPPORTEDPLATFORMS      WINDOWS
```
