### ISSUE TITLE
Unable to access internet while connected to VPN with misc DNS errors

### ISSUE THREAD

**Issue by MahmoudDolah** [trailofbits/algo#1784]
I've set up the VPN and generated the configs. The VPN has worked wonderfully for everyone that I've set it up with, but unfortunately, a team member in Brazil is able to connect successfully, but is having issues connecting to the internet

**To Reproduce**

1. Import wireguard conf
2. Attempt to access internt
3. Run into DNS errors

See here:
https://drive.google.com/file/d/1nWGMkZdyVQIwwYPF-CKbcDFsniSNJFND/view?usp=sharing

**Expected behavior**

Connect to VPN and able to access the web

**Additional context**
DNS network settings of problem machine
![Captura de Tela 2020-04-23 às 11 26 08](https://user-images.githubusercontent.com/16995169/80419693-97727c80-88a7-11ea-8816-e62a8b982ec8.png)

**Full log**
Here's a link to the wireguard logs
https://gist.github.com/MahmoudDolah/6cb7167d4b03bcd8b83c62c8d4f7b6be

**Comment by davidemyers** [comment]
Can the user connect to sites by IP address, such as https://1.1.1.1 ?
