### ISSUE TITLE
Azure Deployment Fails

### ISSUE THREAD

**Issue by abhay-ranawat** [trailofbits/algo#1786]
**Describe the bug**
It Fails to Deploy to Azure

**To Reproduce**
The Same Way Described in Documentation
**Expected behavior**

     "Sorry, but something went wrong!"

**Additional context**

**Full log**

fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "/home/ubuntu/.ansible/tmp/ansible-tmp-1588538260.9399483-277076763150528/
AnsiballZ_azure_rm_deployment.py:18: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for altern
ative uses\n  import imp\nTraceback (most recent call last):\n  File \"/home/ubuntu/movies/AlgoVPN/.env/lib/python3.7/site-packages/azure/cli
/core/_session.py\", line 39, in load\n    with codecs_open(self.filename, 'r', encoding=self._encoding) as f:\n  File \"/usr/local/lib/python3.7/codec
s.py\", line 898, in open\n    file = builtins.open(filename, mode, buffering)\nFileNotFoundError: [Errno 2] No such file or directory: '/home/s_himans
hu_02345/.azure/azureProfile.json'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File
 \"/home/ubuntu/.ansible/tmp/ansible-tmp-1588538260.9399483-277076763150528/AnsiballZ_azure_rm_deployment.py\", line 114, in <module>\n    _a
nsiballz_main()\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1588538260.9399483-277076763150528/AnsiballZ_azure_rm_deployment.py\", line 1
06, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1588538260
.9399483-277076763150528/AnsiballZ_azure_rm_deployment.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File 
\"/usr/local/lib/python3.7/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n  File \"/usr/local/lib/python3.7/imp.py\"
, line 169, in load_source\n    module = _exec(spec, sys.modules[name])\n  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n  File \"<frozen
 importlib._bootstrap_external>\", line 728, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n  File \
"/tmp/ansible_azure_rm_deployment_payload_kqxv7snr/__main__.py\", line 687, in <module>\n  File \"/tmp/ansible_azure_rm_deployment_payload_kqxv7snr/__m
ain__.py\", line 683, in main\n  File \"/tmp/ansible_azure_rm_deployment_payload_kqxv7snr/__main__.py\", line 456, in __init__\n  File \"/tmp/ansible_a
zure_rm_deployment_payload_kqxv7snr/ansible_azure_rm_deployment_payload.zip/ansible/module_utils/azure_rm_common.py\", line 318, in __init__\n  File \"
/tmp/ansible_azure_rm_deployment_payload_kqxv7snr/ansible_azure_rm_deployment_payload.zip/ansible/module_utils/azure_rm_common.py\", line 1030, in __in
it__\n  File \"/tmp/ansible_azure_rm_deployment_payload_kqxv7snr/ansible_azure_rm_deployment_payload.zip/ansible/module_utils/azure_rm_common.py\", lin
e 1259, in _get_credentials\n  File \"/tmp/ansible_azure_rm_deployment_payload_kqxv7snr/ansible_azure_rm_deployment_payload.zip/ansible/module_utils/az
ure_rm_common.py\", line 1170, in _get_azure_cli_credentials\n  File \"/home/ubuntu/movies/AlgoVPN/.env/lib/python3.7/site-packages/azure/com
mon/credentials.py\", line 46, in get_azure_cli_credentials\n    profile = get_cli_profile()\n  File \"/home/ubuntu/movies/AlgoVPN/.env/lib/p
ython3.7/site-packages/azure/common/credentials.py\", line 28, in get_cli_profile\n    ACCOUNT.load(os.path.join(azure_folder, 'azureProfile.json'))\n 
 File \"/home/ubuntu/movies/AlgoVPN/.env/lib/python3.7/site-packages/azure/cli/core/_session.py\", line 42, in load\n    self.save()\n  File 
\"/home/ubuntu/movies/AlgoVPN/.env/lib/python3.7/site-packages/azure/cli/core/_session.py\", line 46, in save\n    with codecs_open(self.file
name, 'w', encoding=self._encoding) as f:\n  File \"/usr/local/lib/python3.7/codecs.py\", line 898, in open\n    file = builtins.open(filename, mode, b
uffering)\nFileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/.azure/azureProfile.json'\n", "module_stdout": "", "msg": "M
ODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

```
PUT THE OUTPUT HERE
```
ok: [localhost] => {
    "fail_hint": [
        "Sorry, but something went wrong!",
        "Please check the troubleshooting guide.",
        "https://trailofbits.github.io/algo/troubleshooting.html"
    ]
}

**Comment by jackivanov** [comment]
Follow this [guide](https://trailofbits.github.io/algo/cloud-azure.html) to configure your environment

**Comment by abhay-ranawat** [comment]
Thanks
