### ISSUE TITLE
How does Algo generate Wireguard client keys?

### ISSUE THREAD

**Issue by mukberty** [trailofbits/algo#1787]
"Algo generates a WireGuard configuration file, wireguard/<username>.conf, and a QR code, wireguard/<username>.png, for each user defined in config.cfg."
What part of the code does this?
Thanks a lot.

**Comment by georgeperez** [comment]
https://github.com/trailofbits/algo/blob/master/roles/wireguard/tasks/main.yml

**Comment by mukberty** [comment]
Thanks a lot!
