### ISSUE TITLE
Issue: Trying to connect an AWS EC2 instance to a Microsoft Azure VPN -- AWS EC2 instance freezing after running "sudo systemctl start wg-quick@wg0"

### ISSUE THREAD

**Issue by Cannie322** [trailofbits/algo#1794]
What I am trying to accomplish: Create a VPN on a Microsoft Azure instance (Ubuntu 20.04) using Algo (check, I got this working)     Then ->    Create an AWS EC2 instance (Ubuntu 18.04) and connect this AWS EC2 (Ubuntu 18.04) instance to the Microsoft Azure VPN created before so that all the traffic going through the AWS EC2 routes through the Microsoft Azure VPN. 

I cannot seem to get the second part to work. I am following this guide: [https://github.com/trailofbits/algo/blob/eeda23be97fe1900ab60225ce1a3061572bc520d/docs/client-linux-wireguard.md](https://github.com/trailofbits/algo/blob/eeda23be97fe1900ab60225ce1a3061572bc520d/docs/client-linux-wireguard.md). I was able to get WireGuard installed and copy over my client config file. All the steps in that guide work up until this command: "sudo systemctl start wg-quick@wg0" (start WireGuard). It then freezes and I lose connection from the EC2. I thought this might be a firewall issue (WireGuard changing ufw rules possibly) so I created a script to check AWS EC2's ip address every second and upload the results to another EC2 that I can connect to (this is to see if the EC2 is actually frozen or not after running the command above that is giving me errors. If there was a firewall issue it should still be running the script and sending the results to my other EC2 instance. It does not seem to be a firewall issue, as the actual EC2 instance freezes after running "sudo systemctl start wg-quick@wg0" (the script I talked about above stops sending results to another EC2 instance). Any idea of what is going on here?

**Comment by davidemyers** [comment]
Bringing up WireGuard (via `wg-quick` when `AllowedIPs = 0.0.0.0/0`) will break existing connections with hosts not on the local network. Your client might not be freezing.

You may need to run the command to start WireGuard from the client's console, but I don't think you can get console access on EC2.

**Comment by Cannie322** [comment]
> Bringing up WireGuard (via `wg-quick` when `AllowedIPs = 0.0.0.0/0`) will break existing connections with hosts not on the local network. Your client might not be freezing.
> 
> You may need to run the command to start WireGuard from the client's console, but I don't think you can get console access on EC2.

I changed the script to start/stop WireGuard every five seconds and output the before/after ip addresses of the EC2. It worked --- The instance was not frozen. The connections through WireGuard were successful. How do I solve not being able to connect to the EC2 instance while it is connected to the VPN (while WireGuard is running)? Any networking configurations I can do in AWS with the EC2 instance to be able to access it through my local laptop's terminal?

**Comment by davidemyers** [comment]
You should be able to SSH into the EC2 client from the Azure server by using the client's `10.19.49.X` address. You might want to add `PersistentKeepalive = 25` to the client's `wg0.conf` so that's it's always connected to the server.

If you deploy your Algo server with `BetweenClients_DROP: false` and connect your laptop to it, then you should be able to SSH directly to the client from your laptop.
