### ISSUE TITLE
Connection from Windows 10

### ISSUE THREAD

**Issue by highpriv** [trailofbits/algo#1798]
Hey,

I'm gonna setup Algo VPN on my Ubuntu VPS but i'm confused. 
Am i need a client (wireguard) for connect on Windows 10? 
As i understood there is no client requirement on iOS and Android for connection.
Can i connect Algo VPN on Windows 10 just configuring with Windows' VPN setting and features without a client, program etc. ?

**Comment by davidemyers** [comment]
The [README](https://github.com/trailofbits/algo#windows) says:

### Windows

WireGuard is used to provide VPN services on Windows. Algo generates a WireGuard configuration file, `wireguard/<username>.conf`, for each user defined in `config.cfg`.

Install the [WireGuard VPN Client](https://www.wireguard.com/install/#windows-7-8-81-10-2012-2016-2019). Import the generated `wireguard/<username>.conf` file to your device, then setup a new connection with it.
