### ISSUE TITLE
Unable to deploy on Microsoft Azure

### ISSUE THREAD

**Issue by mukberty** [trailofbits/algo#1799]
When I run ./algo in the algo directory and finish deployment, I get an error-

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: FileNotFoundError: [Errno 2] No such file or directory: '/root/.azure/azureProfile.json'

What should I do??

Thanks a lot.

**Comment by davidemyers** [comment]
Did you run `az login` as documented [here](https://github.com/trailofbits/algo/blob/master/docs/cloud-azure.md#azure-cloud-setup)?

**Comment by mukberty** [comment]
Thanks! I did that from the instructions [here](https://github.com/twitchax/azure-docs-cli-python/blob/key_fix/docs-ref-conceptual/install-azure-cli-apt.md).
