### ISSUE TITLE
t2.micro vs t2.nano

### ISSUE THREAD

**Issue by dmd** [trailofbits/algo#180]
roles/cloud-ec2/tasks/main.yml specifies t2.micro.  Is there any reason not to use a t2.nano?

**Comment by dguido** [comment]
micro is free tier:

https://github.com/trailofbits/algo/pull/156

**Comment by defunctio** [comment]
Nope, nano works fine. The default actually used to be nano, but it was requested that it be switched to micro for AWS free tier. If you are like me and have long it lived the free year you may want to change it to nano, only downside is a few additional minutes to spin up a new instance.
