### ISSUE TITLE
Config files have not been created ??

### ISSUE THREAD

**Issue by mukberty** [trailofbits/algo#1801]
I have deployed the server with 2 users in config.cfg. But when I try and locate the files, I am unable to find them. 
I ran `ls` in the `algo/configs` directory but it only contained the following-
`40.117.83.59 algo.pem algo.pem.pub`. 
I have also tried to locate the files by filename, but am unable to locate them.
What should I do?
Thanks!

**Comment by ComputerJy** [comment]
You should find them in 40.117.83.59/wireguard/..

40.117.83.59 is a folder, not a file

**Comment by mukberty** [comment]
Thanks a lot!
