### ISSUE TITLE
symlink error

### ISSUE THREAD

**Issue by natechmain** [trailofbits/algo#1802]
I keep getting this error while following the guide.
-copy algo with git
-install depens
-./algo
all defaults

TASK [Create a symlink if deploying to localhost] ******************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "gid": 1000, "group": "ubuntu", "mode": "0775", "msg": "the directory configs/localhost is not empty, refusing to convert it", "owner": "ubuntu", "path": "configs/localhost", "size": 4096, "state": "directory", "uid": 1000}                                                       
included: /home/ubuntu/algo/playbooks/rescue.yml for localhost

TASK [debug] *******************************************************************************************************************************************************
ok: [localhost] => {
    "fail_hint": [
        "Sorry, but something went wrong!",
        "Please check the troubleshooting guide.",
        "https://trailofbits.github.io/algo/troubleshooting.html"
    ]
}

TASK [Fail the installation] ***************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed as requested from task"}

PLAY RECAP *********************************************************************************************************************************************************
localhost                  : ok=131  changed=67   unreachable=0    failed=1    skipped=50   rescued=1    ignored=0

**Comment by natechmain** [comment]
any ideas?

**Comment by jackivanov** [comment]
See this https://github.com/trailofbits/algo/issues/1463

**Comment by natechmain** [comment]
thank you. you'd think the default option would be safe =(
