### ISSUE TITLE
Need some advice on using Portainer

### ISSUE THREAD

**Issue by hdavy2002** [trailofbits/algo#1810]
Hi folks,
I am new to docker and portainer. Need some advice on what I need to enter for the volume area. I basically get the volume part as a datastore. Portainer was complainign about some config.cfg file. Now confusion was: Is this specific to Portainer or general config.cfg that comes with Algo?

Many thanks

Cheers

![1](https://user-images.githubusercontent.com/1983384/82712059-03909800-9c3c-11ea-8f0e-741cb2610ab3.PNG)
![2](https://user-images.githubusercontent.com/1983384/82712061-04292e80-9c3c-11ea-9f0a-bb556151db59.PNG)

**Comment by jackivanov** [comment]
[![Join the chat at https://gitter.im/trailofbits/algo](https://badges.gitter.im/trailofbits/algo.svg)](https://gitter.im/trailofbits/algo?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
