### ISSUE TITLE
Local host unreachable in Windows linux subsystem

### ISSUE THREAD

**Issue by scofieldm** [trailofbits/algo#1811]
Hello. I feel like this is a noob request (because im a noob to all these) and i wouldn't post it if i didn't need help, but i already paid digitalocean and my subscription will expire without trying algo out.

**Describe the error**

I'm getting an error exactly after hitting ./algo in Windows Linux Distribution Ubuntu app

**To Reproduce**

I don't really know how to reproduce this problem.

**Expected behavior**

Run smoothly since i followed every step exactly.

**Additional context**

I googled about this and i tried to add this line in ansible.cfg: " remote_tmp = /tmp/.ansible-${USER}/tmp "without any different results.

**Full log**

[WARNING]: Could not match supplied host pattern, ignoring: vpn-host

PLAY [localhost] **********************************************************************************************************************************************************************************

TASK [Gathering Facts] ****************************************************************************************************************************************************************************
fatal: [localhost]: UNREACHABLE! => {"changed": false, "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo /tmp/.ansible-${USER}/tmp/ansible-tmp-1590261449.6749623-237457969186535 `\" && echo ansible-tmp-1590261449.6749623-237457969186535=\"` echo /tmp/.ansible-${USER}/tmp/ansible-tmp-1590261449.6749623-237457969186535 `\" ), exited with result 1, stdout output: ansible-tmp-1590261449.6749623-237457969186535=/tmp/.ansible-user/tmp/ansible-tmp-1590261449.6749623-237457969186535\n", "unreachable": true}

PLAY RECAP ****************************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0

```

**Comment by davidemyers** [comment]
What versions of WSL and Ubuntu are you using? Ubuntu 18.04 under WSL1 should work, but I’ve not seen anyone report success with either WSL2 or Ubuntu 20.04 yet.

**Comment by jianjianerluka** [comment]
my Ubuntu version is 20.04. other info is here, Linux version 4.4.0-18362-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #836-Microsoft Mon May 05 16:04:00 PST 2020，

**Comment by scofieldm** [comment]
Hello, downgrading to Ubuntu 18.04 LTS worked like a charm, 0 errors after that. Thank you David. Closing.
