### ISSUE TITLE
Issue after running ./algo

### ISSUE THREAD

**Issue by Hababala** [trailofbits/algo#1818]
Hi all,

I am very new to all this.

I am running ./algo and I get following error output (tried couple times now).
Am I doing something wrong?

Hid ipv4 with _**xxxxx**_

TASK [Wait 600 seconds for target connection to become reachable/usable] ****************************************
failed: [localhost -> _**xxxxx**_] (item=_**xxxxx**_) => {"ansible_loop_var": "item", "changed": false, "elapsed": 778, "item": "_**xxxxx**_", "msg": "timed out waiting for ping module test success: Failed to connect to the host via ssh: Warning: Permanently added '_**xxxxx**_' (ECDSA) to the list of known hosts.\r\nroot@167.71.143.154: Permission denied (publickey,password)."}
included: /root/algo/playbooks/rescue.yml for localhost

TASK [debug] ****************************************************************************************************
ok: [localhost] => {
    "fail_hint": [
        "Sorry, but something went wrong!",
        "Please check the troubleshooting guide.",
        "https://trailofbits.github.io/algo/troubleshooting.html"
    ]
}

TASK [Fail the installation] ************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed as requested from task"}

PLAY RECAP ******************************************************************************************************
localhost                  : ok=31   changed=2    unreachable=0    failed=1    skipped=11   rescued=1    ignored=0

**Comment by davidemyers** [comment]
Please post the block of output immediately below the line which says:
```
--> Please include the following block of text when reporting issues:
```

**Comment by Hababala** [comment]
Algo running on: Ubuntu 20.04 LTS (Virtualized: kvm)
Created from git clone. Last commit: 3f86ae0 Few cosmetic change to readme (#1813)
Python 3.8.2
Runtime variables:
    algo_provider "local"
    algo_ondemand_cellular "False"
    algo_ondemand_wifi "False"
    algo_ondemand_wifi_exclude "X251bGw="
    algo_dns_adblocking "False"
    algo_ssh_tunneling "True"
    wireguard_enabled "True"
    dns_encryption "True"

TASK [Display the invocation environment] ***********************************************************************
changed: [localhost -> localhost]

TASK [Install the requirements] *********************************************************************************
ok: [localhost -> localhost]
[local : pause]
Enter the IP address of your server: (or use localhost for local installation):
[localhost]
:
**_xxxxx_**^M
TASK [local : pause] ********************************************************************************************
ok: [localhost]

TASK [local : Set the facts] ************************************************************************************
ok: [localhost]
[local : pause]
What user should we use to login on the server? (note: passwordless login required, or ignore if you're deploying to localhost)
[root]
:
^M
TASK [local : pause] ********************************************************************************************
ok: [localhost]

TASK [local : Set the facts] ************************************************************************************
ok: [localhost]
[local : pause]
Enter the public IP address or domain name of your server: (IMPORTANT! This is used to verify the certificate)
[**_xxxxx_**]
:

TASK [local : pause] ********************************************************************************************
ok: [localhost]

TASK [local : Set the facts] ************************************************************************************
ok: [localhost]

TASK [Set subjectAltName as a fact] *****************************************************************************
ok: [localhost]

TASK [Add the server to an inventory group] *********************************************************************
changed: [localhost]

TASK [Wait until SSH becomes ready...] **************************************************************************
ok: [localhost]

TASK [debug] ****************************************************************************************************
ok: [localhost] => {
    "IP_subject_alt_name": "**_xxxxx_**"
}

TASK [Wait 600 seconds for target connection to become reachable/usable] ****************************************
failed: [localhost -> **_xxxxx_**] (item=**_xxxxx_**) => {"ansible_loop_var": "item", "changed": false, "elapsed": 778, "item": "**_xxxxx_**", "msg": "timed out waiting for ping module test success: Failed to connect to the host via ssh: Warning: Permanently added '**_xxxxx_**' (ECDSA) to the list of known hosts.\r\nroot@**_xxxxx_**: Permission denied (publickey,password)."}
included: /root/algo/playbooks/rescue.yml for localhost

TASK [debug] ****************************************************************************************************
ok: [localhost] => {
    "fail_hint": [
        "Sorry, but something went wrong!",
        "Please check the troubleshooting guide.",
        "https://trailofbits.github.io/algo/troubleshooting.html"
    ]
}

TASK [Fail the installation] ************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed as requested from task"}

PLAY RECAP ******************************************************************************************************
localhost                  : ok=31   changed=2    unreachable=0    failed=1    skipped=11   rescued=1    ignored=0

(.env) root@demovpnserver:~/algo# ^C
(.env) root@demovpnserver:~/algo# ^C
(.env) root@demovpnserver:~/algo#

**Comment by davidemyers** [comment]
Are you trying to configure `demovpnserver` as your VPN server? If so, don't enter an IP address at the prompt:
```
Enter the IP address of your server: (or use localhost for local installation):
```

**Comment by Hababala** [comment]
Thanks I solved the issue like this!
