### ISSUE TITLE
problem with requirements.txt

### ISSUE THREAD

**Issue by macuser666** [trailofbits/algo#182]
Hi

When running the first step for installing Algo, I run into the following problem
"Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'"

Any suggestions on how to fix this?

Mac os Sierra 12.2

<ansible-2.1.1.0>
<pip 8.1.2>

### Steps to reproduce the behavior

sudo easy_install pip && sudo pip install --ignore-install -r requirements.txt

### The way of deployment (cloud or local)

local

### Full log

The directory '/Users/666/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/666/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

**Comment by dguido** [comment]
When you open the terminal to run that command, you have to `cd` into the directory that Algo is in first. Once you are in the same directory, then you can run that command.

**Comment by macuser666** [comment]
Thank you

I'll try that

**Comment by macuser666** [comment]
Ok
It starts running the command, but I get the fallowing error
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-sWAuQq/pycrypto/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-mXw6RU-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-sWAuQq/pycrypto/

**Comment by dguido** [comment]
Wild guess, you probably need to install XCode's command line tools.

**Comment by macuser666** [comment]
Hi

Today I installed the command line tools and now everything works
I have my Algo server up and running

Thank you for your time and advice

**Comment by dguido** [comment]
Glad it worked!
