### ISSUE TITLE
Want to change the ports of the algo vpn can it will be feasible with wiregaurd

### ISSUE THREAD

**Issue by jaki300** [trailofbits/algo#1824]
want to change the ports of vpn to other then the defaults ports

**Comment by davidemyers** [comment]
WireGuard only uses one port and you can change it by changing `wireguard_port` in the file `config.cfg`.

**Comment by jaki300** [comment]
can we change the udp ports to tcp like udp 4500 and 500 to tcp  2000-2001

**Comment by davidemyers** [comment]
Those ports are for IPsec, not WireGuard, and you can not change them.
