### ISSUE TITLE
Restore: p12 and SSH keys password

### ISSUE THREAD

**Issue by thejini3** [trailofbits/algo#1827]
Any way to restore "p12 and SSH keys password"?

I have lost my old passwords [forgot to take backup while changing (local) operating system] :|

Edit 1: I still have configuration files (./configs) and ssh access.

**Comment by davidemyers** [comment]
You can find the p12 password embedded in the `.mobileconfig` files in the `ipsec/apple` directory.

**Comment by thejini3** [comment]
Thanks <3
