### ISSUE TITLE
I tried to setup on my home network pc to access it from internet but i couldn't access it. Pls help !

### ISSUE THREAD

**Issue by ncrixz** [trailofbits/algo#1832]
I setup algo on my home network to access my home computer from from internet. These are steps i followed all steps as guide : 

1.Using windows 10 wsl 1 on home pc.
2.setup amazon ec2 user account and policy.
3.add user to config.
4.run with ./algo
5.enter access key and secret key of amazon.
6.received the congratulation screen with all data.
7.copy the wireguard user config file from the folder paste it on my work pc.
8.installed wireguard and added the config file to it.
9.i press activate and it gives me tick mark and activation.

but i can't access any website hosted on my home server.

**Comment by davidemyers** [comment]
You might need to change the following setting in `config.cfg`:
```yaml
# Block traffic between connected clients. Change this to false to enable
# connected clients to reach each other, as well as other computers on the
# same LAN as your Algo server (i.e. the "road warrior" setup). In this
# case, you may also want to enable SMB/CIFS and NETBIOS traffic below.
BetweenClients_DROP: true
```

**Comment by ncrixz** [comment]
> You might need to change the following setting in `config.cfg`:
> 
> ```yaml
> # Block traffic between connected clients. Change this to false to enable
> # connected clients to reach each other, as well as other computers on the
> # same LAN as your Algo server (i.e. the "road warrior" setup). In this
> # case, you may also want to enable SMB/CIFS and NETBIOS traffic below.
> BetweenClients_DROP: true
> ```

I changed it to false and also set
# Block SMB/CIFS traffic
block_smb: false

# Block NETBIOS traffic
block_netbios: false

But still i can't access the local network. Points to note here are :

1. My router doesn't have a permanent static ip.
2.My network doesn't have an active DHCP.
3.After making the wireguard active i get attached screen
![Untitled](https://user-images.githubusercontent.com/50003116/86274806-e9eb5480-bbda-11ea-9d42-acef0f09f52c.png)

What steps should take more to get access to my local network
