### ISSUE TITLE
Add instruction for python2 and need install pip pyopenssl

### ISSUE THREAD

**Issue by kwccoin** [trailofbits/algo#1836]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kwccoin** [comment]
Seems minor but for those new, I think suggest them to use python2 until the virtualenv has been created could be a good idea.

**Comment by jackivanov** [comment]
We don't support python2 anymore.
