### ISSUE TITLE
Error installing when using GCE JSOn file 

### ISSUE THREAD

**Issue by sharmaamitg** [trailofbits/algo#1839]
HI,I am facing similar issue when I am trying to install Algo VPN on Google Cloud Platform. i am new to development and dont know much of architecture/dev tools structure.

@jackivanov can you please help to detail the step required to overcome the issue...I am really unable to figure out what does exactly this issues mean..
where is the credentials file..
which local path is been talked about..
And which json file..
Also if something to update in json file how and what to update..any sample file ..if someone can please provide..

Again I am not developer but trying my hands on setting up private vpn..

Issues:
TASK [cloud-gce : Install requirements] **********************************************************************************************************************************************************
ok: [localhost]
[cloud-gce : pause]
Enter the local path to your credentials JSON file
(https://support.google.com/cloud/answer/6158849?hl=en&ref_topic=6262490#serviceaccounts)

![image](https://user-images.githubusercontent.com/55621595/86917811-4e1c9400-c158-11ea-855d-062ac6d6ff98.png)

![image](https://user-images.githubusercontent.com/55621595/86917840-596fbf80-c158-11ea-833b-c937e946b4bd.png)

**Comment by davidemyers** [comment]
Have you read [Google Cloud Platform setup](https://github.com/trailofbits/algo/blob/master/docs/cloud-gce.md)?

Also, consider trying DigitalOcean first, it's much easier to use than GCE.
