### ISSUE TITLE
Removing from Ubuntu server? 

### ISSUE THREAD

**Issue by wolphox** [trailofbits/algo#184]
OS / Environment
Ubuntu DO Droplet

Just a question - I installed this to an Ubuntu DO droplet via the "Ubuntu server" option #5 from the /.algo install script. 

Were there any changes made to the server that I'd have to undo? What would be the way to remove algo from this server if it was installed?

**Comment by defunctio** [comment]
This is not currently supported, changes made would be dependent on the features you selected during installation. But you can extract the information necessary to revert changes from the roles.
