### ISSUE TITLE
Prompt for AWS keys is ambiguous

### ISSUE THREAD

**Issue by erno** [trailofbits/algo#1840]
The setup script asks: "Enter your aws_access_key (http://docs.aws.amazon.com/general/latest/gr/managing-aws-access-keys.html)"

But in AWS terminology and also in the referenced doc, there are 2 concepts: AWS secret access key, and AWS access key id.

By grepping the repo contents I get this hit:

roles/cloud-ec2/tasks/prompts.yml:    access_key: "{{ aws_access_key | default(_aws_access_key.user_input|default(None)) | default(lookup('env','AWS_ACCESS_KEY_ID'), true) }}"

So I am guessing the right fix would be to change the prompt to ask for "Enter your AWS Access Key ID (NOT your AWS Secret Access Key)"

**Comment by davidemyers** [comment]
The terminology of the two AWS prompts can certainly be improved. How about:
```
Enter your AWS Access Key ID (http://docs.aws.amazon.com/general/latest/gr/managing-aws-access-keys.html)
Note: Make sure to use an IAM user with an acceptable policy attached (see https://github.com/trailofbits/algo/blob/master/docs/deploy-from-ansible.md)
```
```
Enter your AWS Secret Access Key (http://docs.aws.amazon.com/general/latest/gr/managing-aws-access-keys.html)
```
