### ISSUE TITLE
Unable to connect from wireguard client on macos

### ISSUE THREAD

**Issue by siftuser** [trailofbits/algo#1841]
Algo server was created using aws cloudformation script. Imported WG client conf on macOS v 10.14.6. Once connected, it snapped internet connectivity from the macOS client. Noticed algo server is assigning private IP to tunnel interface. Is this usual ? 

Appreciate any help to fix this. Thanks

If it helps, same conf works as expected from Android phone.

**Comment by davidemyers** [comment]
>If it helps, same conf works as expected from Android phone.

You must use a different WireGuard `.conf` for each client.

Is the Android on the same Wi-Fi network as the Mac?

**Comment by siftuser** [comment]
> You must use a different WireGuard `.conf` for each client.

Yes. I was using separate conf for both phone & mac. BTW, I configured ipsec client on the mac & is working as expected. Thanks

> Is the Android on the same Wi-Fi network as the Mac?

Yes, they're
