### ISSUE TITLE
Installer stops running at TASK debug w/ IP_subject_alt_name

### ISSUE THREAD

**Issue by onlineth** [trailofbits/algo#1845]
**Describe the bug**

The installer appears to stop running when the following step is reached,

```
TASK [debug] *************************************************************************************************
ok: [localhost] => {
    "IP_subject_alt_name": "server18.onlineth.com"
}
```

The installer hangs on this message providing no new output after several minutes of waiting.

**To Reproduce**

1. Launch a Ubuntu 18.04 LTS blueprint instance on AWS Lightsail
2. Apt-get update, upgrade, and install python3-virtualenv
3. Run the command found in the README step 4, "Install Algo's remaining dependencies"
4. Edit the config.cfg file
5. Run `./algo`

**Expected behavior**

Continue to provide output and eventually display the "Congratulations!" message.

**Additional context**

Using a AWS Lightsail instance with the Ubuntu 18.04 LTS blueprint.  The instance is the $10 monthly instance class.  The subdomain that is IP_subject_alt_name does point to the IP found in "Enter the public IP address or domain name of your server:".

**Full log**

```
Algo running on: Ubuntu 18.04.4 LTS (Virtualized: xen)
Created from git fork. Last commit: 3f86ae0 Few cosmetic change to readme (#1813)
Python 3.6.9
Runtime variables:
    algo_provider "local"
    algo_ondemand_cellular "True"
    algo_ondemand_wifi "True"
    algo_ondemand_wifi_exclude "X251bGw="
    algo_dns_adblocking "False"
    algo_ssh_tunneling "True"
    wireguard_enabled "True"
    dns_encryption "True"

TASK [Display the invocation environment] ********************************************************************
changed: [localhost -> localhost]

TASK [Install the requirements] ******************************************************************************
ok: [localhost -> localhost]
[local : pause]
Enter the IP address of your server: (or use localhost for local installation):
[localhost]
:

TASK [local : pause] *****************************************************************************************
ok: [localhost]

TASK [local : Set the facts] *********************************************************************************
ok: [localhost]
[local : pause]
What user should we use to login on the server? (note: passwordless login required, or ignore if you're deploying to localhost)
[root]
:

TASK [local : pause] *****************************************************************************************
ok: [localhost]

TASK [local : Set the facts] *********************************************************************************
ok: [localhost]
[local : pause]
Enter the public IP address or domain name of your server: (IMPORTANT! This is used to verify the certificate)
[54.166.XXX.XX]
:

TASK [local : pause] *****************************************************************************************
ok: [localhost]

TASK [local : Set the facts] *********************************************************************************
ok: [localhost]

TASK [Set subjectAltName as a fact] **************************************************************************
ok: [localhost]

TASK [Add the server to an inventory group] ******************************************************************
changed: [localhost]

TASK [Wait until SSH becomes ready...] ***********************************************************************
ok: [localhost]

TASK [debug] *************************************************************************************************
ok: [localhost] => {
    "IP_subject_alt_name": "serverXX.XXXXXXX.com"
}

```

**Comment by onlineth** [comment]
I have also checked out branch `v1.1` and the installer seems to hang on that as well when it reaches,

```
TASK [debug] *******************************************************************
ok: [localhost] => {
    "IP_subject_alt_name": "serverXX.XXXXXX.com"
}
Pausing for 20 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)

TASK [A short pause, in order to be sure the instance is ready] ****************
ok: [localhost]

PLAY [Configure the server and install required software] **********************
```

**Comment by SkyDiverCool** [comment]
Same issue just doesn't do anything when reaching TASK [debug] left it for about 24 hours and still nothing

**Comment by onlineth** [comment]
My fix was mentioned somewhere else, but essentially one of the prompts you have to type in the hostname (intuitively you just click enter, but don't do that).  It's like the second prompt asking for a hostname I think, it's been a while since I've done this.  @SkyDiverCool

**Comment by ozon-cloud** [comment]
Hi there,

I get the same pausing error. Can someone advise on solving this issue?

**Comment by ixonstater** [comment]
I was doing a local install and the first time that algo asked for my IP address I put the public address of the server instead of localhost and this caused it to hang at the aforementioned step.  By starting the installation over and entering localhost instead I was able to get it installed and running.

**Comment by glushchenko** [comment]
> I was doing a local install and the first time that algo asked for my IP address I put the public address of the server instead of localhost and this caused it to hang at the aforementioned step. By starting the installation over and entering localhost instead I was able to get it installed and running.

Works like a magic. Just do not enter ip.
