### ISSUE TITLE
Algo throws an exception on macOS 10.15.6

### ISSUE THREAD

**Issue by bmy** [trailofbits/algo#1848]
Hiya Algo. Huge fan here, I use algo all the time. Thanks so much for all your hard work.

The latest build seems to throw an error for me, as well as the last build in May. I will keep going back through versions until I find a working one.

I find this to be a somewhat common dynamic when pulling the latest version(s) and attempting to roll new Algo instances, though Lord knows across the various incidents it could have simply been on my end...something with Homebrew, changes Apple is making with their updates, etc.

Here is the non-verbose output:

```
[WARNING]: Could not match supplied host pattern, ignoring: vpn-host


PLAY [localhost] ***************************************************************
ERROR! Unexpected Exception, this is probably a bug: cannot pickle '_io.TextIOWrapper' object
to see the full traceback, use -vvv
```

Let me know if the more verbose output would be helpful.

Many thanks.

B

**Comment by davidemyers** [comment]
It looks like you recently ran `brew upgrade` which caused Python to be upgraded from 3.7 to 3.8, but Python 3.8 doesn't work with the outdated version of Ansible used by Algo. See #1777 and #1838.

While this is being addressed you can either try using the latest version of Ansible or you can downgrade your Python.

To use the latest Ansible start with a fresh copy of the latest Algo and before running any commands, edit `requirements.txt` and change the Ansible version to `2.9.11`. Algo has not yet been sufficiently tested with Ansible 2.9, but it might work anyway.

To downgrade Python run:
```
brew uninstall python3
brew install python@3.7
brew link --force python@3.7
```
Then start again with a fresh copy of the latest Algo.

**Comment by bmy** [comment]
I see, okay. Thanks for your reply.

I think it's likely that for most people the first command should be modified to read:

`brew uninstall python@3.8`

followed in most cases by:

`brew uninstall --ignore-dependencies python@3.8`

There is no `python3` formula installed, and for almost anyone using brew I suspect trying to uninstall Python will throw a warning about multiple dependencies. Hope I didn't just break all those other Python apps, but anyway I care more about getting this working...

**Comment by bmy** [comment]
That has indeed fixed it. Many thanks. 

I will monitor those other tickets. 

Thanks again for you and ToB's hard work – I will be joining the Patreon shortly, been meaning to for ages.
