### ISSUE TITLE
Wireguard does not connect to Algo server from my IP

### ISSUE THREAD

**Issue by smmsadrnezh** [trailofbits/algo#1850]
**Describe the bug**

I deployed Algo on Hetzner and DigitalOcean servers by its GitHub instruction without any errors, but I can't connect to my Algo server using WireGuard. SSH Tunneling and socks proxy works, and everything looks fine. When I connect to another VPN first, I can connect to the Algo server by WireGuard! How can I find the problem?
When I'm trying to connect on my phone, the log is:
```
Sending handshake initiation
Handshake did not complete after 5 seconds.
```

And `wg show` shows no connection to the server. The weird part is that it works when I connect to another VPN first!

I used Ubuntu 20.04 on my server, and I chose the following option during the installation:
```
Install to existing Ubuntu 18.04 or 20.04 server (for more advanced users)
```

**To Reproduce**

It's not reproducible because, as I said, I could connect to my Algo server if I was connected to another VPN first. I used different ISPs, but it didn't help. I can give you more logs or information if you ask.

**Comment by davidemyers** [comment]
What kind of phone are you using (Android or iPhone)?

What is this other VPN? Does it require an app that might be interfering with the WireGuard app? If so, can you uninstall it and try WireGuard again?

Can you connect to your AlgoVPN from a different client (like a Mac or PC)?

**Comment by smmsadrnezh** [comment]
1. Android.
2. The other VPN is Openconnect. Wireguard connects behind that VPN. I mean, my IP address will be changed before connecting to Algo.
3. I tested from Linux and Windows clients, and there was no difference.

**Comment by davidemyers** [comment]
Could your country be blocking WireGuard, as mentioned in #1588?

**Comment by smmsadrnezh** [comment]
I'm not sure because I have access to the other VPS, which someone else installed Algo on it. I don't have SSH access to that VPS, and its provider is not Hetzner or DigitalOcean, but the same instruction installs it.
Do you know a specific solution to test if it is blocked or not? If it's blocked, how does the other server works?

**Comment by davidemyers** [comment]
I don't know a good way to test for country-level blocking. Perhaps the blocking also depends on where the server is located.
