### ISSUE TITLE
Can not log in to droplet created with digital ocean API

### ISSUE THREAD

**Issue by dr-mcgillicuddy** [trailofbits/algo#1851]
**Describe the bug**

Can’t access console on DO droplet
**To Reproduce**

Run the script and create a DO droplet.
Then try to log in to the console either via the web interface or SSH.

**Expected behavior**

I should be able to log in. But the defaults have been changed and the change is not documented.

**Comment by davidemyers** [comment]
The exact SSH command to use should have been printed to the screen when the deployment completed. It's also shown [here](https://github.com/trailofbits/algo#ssh-into-algo-server).
