### ISSUE TITLE
Monitoring users logins/logouts

### ISSUE THREAD

**Issue by llugaric** [trailofbits/algo#1864]
I'm running Algo for my family and it works great. But given that I also take care of the costs for running it in the cloud, it would be nice to have a way to see usage by individual users - only the login and logout timestamps (with dates) should be sufficient. Is this something that can be done? 

I did my search of documentation and github here but didn't find much on this except that full user monitoring (i.e. traffic) is not possible, which I'm totally OK with.

**Comment by davidemyers** [comment]
WireGuard on the server doesn't log anything in normal operation, and the WireGuard protocol doesn't have the concept of "logout", so I don't think there's an easy way to do this.

There may be a way to create `iptables` rules to count the traffic used by each client IP address.

**Comment by davidemyers** [comment]
I should add that `sudo wg`on the server will show how much traffic each WireGuard client has used, but the counters will get reset at times, such as when the system is rebooted.

**Comment by ZenMinded1** [comment]
> I should add that `sudo wg`on the server will show how much traffic each WireGuard client has used, but the counters will get reset at times, such as when the system is rebooted.

That is great, thanks! Took me a while to figure out how to decode who is who from the peer public keys but I got there. Do you think it would be a good feature to implement and/or see the timeline?

Way to get around the reboot issue is maybe have the server update a table every few hours?

**Comment by davidemyers** [comment]
I'm not sure how many users would find this feature useful.

**Comment by luixo** [comment]
> Took me a while to figure out how to decode who is who from the peer public keys but I got there.

@llugaric Can you please share how did you end up decoding the public keys?
