### ISSUE TITLE
Website blocked

### ISSUE THREAD

**Issue by Hababala** [trailofbits/algo#1866]
Hi all,

Sorry I am not well versed in the vocabulary - if I can add something please let me know.

I am using a VM from digital ocean and I set up my VPN and everything was working fine for 2.5 months.

I use wireguard. I pull the config file in and everything works.

I did go abroad and used the this on different machines.

Now I went abroad again on a new machine. Activated the VPN, but it keeps blocking the most crucial website.

Everything works perfectly apart from this one website and only when the VPN is on. It always worked in the past.

Could someone tell me how I could fix this?

Error:

This site can’t be reached
xxx took too long to respond.
Try:
Checking the connection
Checking the proxy and the firewall
Running Windows Network Diagnostics
ERR_CONNECTION_TIMED_OUT

**Comment by davidemyers** [comment]
In the WireGuard app on your client try setting `MTU` to `1280`.

But the problem is more likely that the site is blocking all connections from DigitalOcean. Many sites block connections from cloud providers and there's nothing Algo can do about it.
