### ISSUE TITLE
Wrong endpoint/address characters

### ISSUE THREAD

**Issue by alexTaba** [trailofbits/algo#1867]
Wrong endpoint/address characters:
Can`t create tunnel on client device.

Ubuntu 20.04 on VPN with static IP, localhost by default.

![Screenshot_20200817_134456](https://user-images.githubusercontent.com/47259184/90389049-82f20400-e091-11ea-8590-68709e65e434.jpg)
![Screenshot_20200817_135108](https://user-images.githubusercontent.com/47259184/90389053-84233100-e091-11ea-8006-fe34bfef5a71.png)

**Comment by davidemyers** [comment]
Did you enter an IP address or a hostname at the prompt:
```
Enter the public IP address or domain name of your server:
```

**Comment by alexTaba** [comment]
```
root@vds:~# git clone https://github.com/trailofbits/algo.git           
Cloning into 'algo'...
remote: Enumerating objects: 6863, done.
remote: Total 6863 (delta 0), reused 0 (delta 0), pack-reused 6863
Receiving objects: 100% (6863/6863), 2.81 MiB | 3.11 MiB/s, done.
Resolving deltas: 100% (3932/3932), done.

root@vds:~# sudo apt install -y python3-virtualenv
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-virtualenv is already the newest version (20.0.17-1).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.

root@vds:~/algo# python3 -m virtualenv --python="$(command -v python3)" .env &&
>   source .env/bin/activate &&
>   python3 -m pip install -U pip virtualenv &&
>   python3 -m pip install -r requirements.txt

Enter the number of your desired provider
:
11

Do you want macOS/iOS clients to enable "Connect On Demand" when connected to cellular networks?
[y/N]
:
N

Do you want macOS/iOS clients to enable "Connect On Demand" when connected to Wi-Fi?
[y/N]
:
N

Do you want to retain the keys (PKI)? (required to add users in the future, but less secure)
[y/N]
:
N

Do you want to enable DNS ad blocking on this VPN server?
[y/N]
:
y

Do you want each user to have their own account for SSH tunneling?
[y/N]
:
N

Enter the IP address of your server: (or use localhost for local installation):
[localhost]
:
localhost

Enter the public IP address or domain name of your server: (IMPORTANT! This is used to verify the certificate)
[localhost]
:+1: 
45.89.xx.xx (my public IP)

 	    "\"#                          Congratulations!                                              #\"",
            "\"#                     Your Algo server is running.                                 #\"",
            "\"#    Config files and certificates are in the ./configs/ directory.     #\"",
            "\"#              Go to https://whoer.net/ after connecting                     #\"",
            "\"#        and ensure that all your traffic passes through the VPN.    #\"",
            "\"#                     Local DNS resolver xxx.xx.xx.x                             #\"",
```

**Comment by davidemyers** [comment]
The strange character sequences look sort of like terminal control sequences. Could you have perhaps used the arrow keys while entering this field? I don't think the text entry function accommodates anything more complicated than backspace and delete.

**Comment by alexTaba** [comment]
After full OS reinstall on VPS everything is ok, thanks.

**Comment by bowtiediguana** [comment]
Re-opening as I have a user with a similar issue. Likely not terminal control sequences because the IP address was passed like this, curling ifconfig.io (but no verification check on the output)

`curl -s https://raw.githubusercontent.com/trailofbits/algo/master/install.sh   | bash -x -s local false false _null false false false $(curl ifconfig.io) phone,tablet,laptop,pc,extradevice1,extradevice2`

If we can reproduce, what other debug info would be useful? The procedure we are following is to deploy a Ubuntu 20 LTS image and running:

`apt-get update && apt-get dist-upgrade -y && curl -s https://raw.githubusercontent.com/trailofbits/algo/master/install.sh   | bash -x -s local false false _null false false false $(curl ifconfig.io) phone,tablet,laptop,pc,extradevice1,extradevice2`

**Comment by davidemyers** [comment]
@bowtiediguana Does it work if you use `$(curl -4 ifconfig.io)`?
