### ISSUE TITLE
Option to choose instance type when creating service in cloud

### ISSUE THREAD

**Issue by saichander17** [trailofbits/algo#1872]
**Is your feature request related to a problem? Please describe.**
I'm trying to use Google cloud compute for launching the VPN server and the issue is it's always throwing ZONE_RESOURCE_POOL_EXHAUSTED error for the asia-south1. I tried more than 10-15 times in one full day and yet its throwing the same error. 

**Describe the solution you'd like**
I think there should be an option in the installation steps to choose an instance type as well along with a default type.

**Comment by davidemyers** [comment]
You can change the instance type in `config.cfg` in the `cloud_providers:` section.
