### ISSUE TITLE
Error screen from Google Search saying "unusual traffic" when algo enabled

### ISSUE THREAD

**Issue by codecachet** [trailofbits/algo#1874]
When algo is enabled (Mac, Ipad or Iphone), many times (not always), I get error screen from Google search, saying "Our systems have detected unusual traffic from your computer...". This usually requires me to do a captcha, and then search will work (if I did the captcha correctly!). If I turn off algo, I normally do not get this error screen.

This is using the latest algo master of a few days ago, on Digital Ocean, and running the standard Ansible install (via my Mac), with no changes to the config script, other than users.

Other than that, the VPN seems to work just fine on all devices (Mac, iPad Pro, iPad Air, iPhone 11). (Mac is running High Sierra, iOS are all 13.6.1).

Any help would be appreciated. Thanks!

**Comment by davidemyers** [comment]
When using a cloud provider your traffic comes from network addresses that might previously have been used to probe Google systems. With Google I've noticed you're more likely to see this issue over IPv6 from DigitalOcean. The captchas might go away over time.

I've never seen this issue with [DuckDuckGo](https://duckduckgo.com).
