### ISSUE TITLE
 Can't access a specific resource

### ISSUE THREAD

**Issue by sasha066** [trailofbits/algo#1875]
**Describe the bug**

can't get access to the resource 185.203.72.22

**To Reproduce**

1. Install Algo on some VDS as usual.
2. Try to ping the IP address 185.203.72.22.

**Expected behavior**

Hey. Today I have set up a VPN on my VDS running Ubuntu 20.04. I connected to the VPN from my Android device and everything works fine except for one resource. For some reason, through my VPN, I can't get access to the resource 185.203.72.22. Including, I can't even ping this address on the VDS itself. What could be the problem? Incorrect configuration or is there a problem with my VDS provider?

**Additional context**

**Full log**

```
PUT THE OUTPUT HERE
```

**Comment by davidemyers** [comment]
I can't ping that address from any of the following networks (without even using the VPN):

- Home ISP (AT&T)
- Google Cloud Engine
- Amazon EC2
- Oracle Cloud

So this issue might not be with Algo or the use of a VPN.

**Comment by sasha066** [comment]
> I can't ping that address from any of the following networks (without even using the VPN):
> 
> * Home ISP (AT&T)
> * Google Cloud Engine
> * Amazon EC2
> * Oracle Cloud
> 
> So this issue might not be with Algo or the use of a VPN.

apparently this resource specifically rejects ping requests. I pinged on http using the "httping" command and it seems my VDS has access to this resource, but through VPN I still cannot access this resource.

**Comment by davidemyers** [comment]
I can access the site from a browser through an AlgoVPN on EC2. Does your Android have problems over both Wi-Fi and mobile data?

**Comment by sasha066** [comment]
> I can access the site from a browser through an AlgoVPN on EC2. Does your Android have problems over both Wi-Fi and mobile data?

At the moment, I have no way to check the work via mobile data. I will check this a little later and report the result. At the moment I am having problems using Wi-Fi. Also, I will now install VNC on my VDS and check the operation of the site through the browser.

**Comment by sasha066** [comment]
> I can access the site from a browser through an AlgoVPN on EC2. Does your Android have problems over both Wi-Fi and mobile data?

Well I've tested mobile data access and it still doesn't work. Also I installed VNC on my VDS and tried to enter the site through Firefox browser and I got a strange message:
https://i.ibb.co/jyxfpN0/Screenshot-3.png

I also tested the work of this site on another VDS of the same provider, without Algo installed, and there I can access the site without any problems.

**Comment by davidemyers** [comment]
Are you installing Algo on Ubuntu Desktop? It's intended to be installed on Ubuntu Server. That may or may not have anything to do with the issue.

**Comment by sasha066** [comment]
> Вы устанавливаете Algo на рабочий стол Ubuntu? Он предназначен для установки на сервере Ubuntu. Это может иметь или не иметь ничего общего с проблемой.

Yes, i'm installing it on Ubuntu Server 20.04

**Comment by sasha066** [comment]
Is it possible to temporarily suspend Algo to test access to the site without it?

**Comment by davidemyers** [comment]
There's no easy way to disable all of Algo. It _might_ be sufficient just to disable the firewall (I have not tested this):
```
sudo systemctl disable netfilter-persistent.service
```

**Comment by davidemyers** [comment]
I should have written:
```
sudo systemctl stop netfilter-persistent.service
```

**Comment by sasha066** [comment]
> I should have written:
> 
> ```
> sudo systemctl stop netfilter-persistent.service
> ```

I executed this command, but nothing has changed, even the VPN continues its work as if nothing had happened. :/

**Comment by sasha066** [comment]
Please help me. I really need access to this site via VPN. :(
Maybe there is a way to look at some logs or something else like that to find out what the problem is with access to the site...

**Comment by davidemyers** [comment]
I'm out of ideas. Can you try another cloud provider?

**Comment by sasha066** [comment]
> I'm out of ideas. Can you try another cloud provider?

unfortunately, at the moment I cannot. But I will try.

**Comment by sasha066** [comment]
It turned out that the IP address of my VDS was blocked for some reason on the resource I needed. I changed the IP and everything works fine. This is not an Algo problem.
