### ISSUE TITLE
Add static IP assignment for certain users

### ISSUE THREAD

**Issue by bobbyl140** [trailofbits/algo#1882]
**Is your feature request related to a problem? Please describe.**
I have no way to reach other connected clients. 
**Describe the solution you'd like**
A way to assign an IP Address to a user so they always get that address when they connect
**Describe alternatives you've considered**
I can look in the syslog and find the address for each client, but that takes a long time.
**Additional context**
I would like to be able to send files between connected clients, but need a way to know how to get to them.

**Comment by jackivanov** [comment]
You can use WireGuard, the IPs are static in this protocol implementation
