### ISSUE TITLE
DNS AdBlocking doesnt seem to work anymore !!

### ISSUE THREAD

**Issue by aashishdamrait** [trailofbits/algo#1883]
Recently there seems to be issue with adblocking, ADs are not being blocked by the server

**Steps to reproduce the behavior:**
try opening domains listed in /etc/dnscrypt-proxy/blacklist.txt

Existing server doesnt seem to bock ads, So tried provisionnig new server same issue persists. Tried this on Linode.

**Comment by davidemyers** [comment]
Some browsers can be configured to ignore the system DNS settings and use DNS-over-HTTPS directly, which would bypass your AlgoVPN for DNS. What browser are you using?
