### ISSUE TITLE
Limiting access to specific urls?

### ISSUE THREAD

**Issue by alffares** [trailofbits/algo#1884]
Hi,
I really want to thank you for this amazing project! And I want to know if it is possible to limit the access to specific urls?
For example: http://google.com ?

Thanks

**Comment by davidemyers** [comment]
It might be possible to combine the whitelist and blacklist features of `dnscrypt-proxy` so that only certain domain names can be resolved, but a user can just change their DNS server setting and bypass Algo's DNS server if they wish.

**Comment by jackivanov** [comment]
Joins us on [gitter](https://gitter.im/trailofbits/algo) for questions like this please
