### ISSUE TITLE
Using Algo to install Wireguard on an existing server without DNS

### ISSUE THREAD

**Issue by Ge0rges** [trailofbits/algo#1886]
Hello all,

I'm trying to use Algo to install wireguard and configure it and the related settings necessary for it to function (firewall). I'm doing this on an existing Ubuntu 20.04 server which already has a web server and a DNS resolver hosted on it.

I understand algo will overwrite the firewall rules, but I have no issue with adding the ones I need when it's done. 

What is the best process to achieve this? I tried setting the necessary settings in the config file but when I go for install it fails with:

```
RUNNING HANDLER [dns : restart dnscrypt-proxy] ***********************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unable to start service dnscrypt-proxy: A dependency job for dnscrypt-proxy.service failed. See 'journalctl -xe' for details.\n"}
included: /root/algo/playbooks/rescue.yml for localhost
```

Can I instruct Algo not to do anything related to DNS?

**Comment by jackivanov** [comment]
see [config.cfg](https://github.com/trailofbits/algo/blob/master/config.cfg#L56)
