### ISSUE TITLE
DigitalOcean Region request API failed

### ISSUE THREAD

**Issue by prooshani** [trailofbits/algo#1888]
I have tried to create an Algo server using my DigitalOcean API token which failed several time.
The Error says:

_**TASK [cloud-digitalocean : Get regions] ****************************************
fatal: [localhost]: FAILED! => {"changed": false, "content": "", "elapsed": 1, "msg": "Status code was -1 and not [200]: Request failed: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)>", "redirected": false, "status": -1, "url": "https://api.digitalocean.com/v2/regions"}
included: /Users/*******/algo/playbooks/rescue.yml for localhost**_ 

Tried several different new API tokens from the DigitalOcean still failing and looks like something Unauthorized the region callback which leads to this fatal error.

Because I am pretty sure I have entered correct API tokens I can't see any user-related problem and maybe something changed in getting regions using DigitalOcean API.

**Comment by davidemyers** [comment]
It looks like you're running on macOS. Have you seen [these instructions](https://github.com/trailofbits/algo/blob/master/docs/deploy-from-macos.md)?

**Comment by prooshani** [comment]
> It looks like you're running on macOS. Have you seen [these instructions](https://github.com/trailofbits/algo/blob/master/docs/deploy-from-macos.md)?

Yep, I did. But it looks like there is nothing related to the ansible or python ...
I have tried pointing the link provided by the error message (https://api.digitalocean.com/v2/regions), which shows there is a problem getting cloud droplets' data and I think this is because of DigitalOcean's API misbehave.
It does not return [200] and says: you are not authorized instead.
I have checked my token, and created new one with no luck.

**Comment by davidemyers** [comment]
Where did your copy of Python come from? Could you post the output of:
```
which python3
python3 --version
```

**Comment by prooshani** [comment]
> which python3
> python3 --version

/Library/Frameworks/Python.framework/Versions/3.7/bin/python3
Python 3.7.9

**Comment by davidemyers** [comment]
Try running `Install Certificates.command` again, in `/Applications/Python 3.7`.

**Comment by prooshani** [comment]
> Try running `Install Certificates.command` again, in `/Applications/Python 3.7`.

Problem Solved. Thanks.
