### ISSUE TITLE
error if Install tools

### ISSUE THREAD

**Issue by Envel-Nikita-Gutsenkov** [trailofbits/algo#1904]
**Describe the bug**

localhost install

`TASK [common : Install tools] **********************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to update apt cache: W:Updating from such a repository can't be done securely, and is therefore disabled by default., W:See apt-secure(8) manpage for repository creation and user configuration details., E:The repository 'https://download.docker.com/linux/ubuntu(lsb_release -cs) Release' does not have a Release file."}
included: /home/ubuntu/algo/playbooks/rescue.yml for localhost`

**Comment by davidemyers** [comment]
It looks like you're trying to do a localhost install using Docker, which will not work.

**Comment by Envel-Nikita-Gutsenkov** [comment]
no O_o

**Comment by Envel-Nikita-Gutsenkov** [comment]
No mention of the docker was found during the configuration or installation process.

**Comment by davidemyers** [comment]
If you're not using Docker then the problem seems to be with a bad Docker-related repository on your system.

**Comment by Envel-Nikita-Gutsenkov** [comment]
Thank you, so it's worth rebuilding the system.

**Comment by davidemyers** [comment]
It's best to start with a fresh and updated installation of Ubuntu Server.
