### ISSUE TITLE
Lightsail deployment: Permission Denied (publickey), /home/algo/.ssh ownership problem.

### ISSUE THREAD

**Issue by friendship1** [trailofbits/algo#1905]
**Describe the bug**

On Lightsail with docker deployment, there is a problem that ssh connection to the "algo" server is not possible.
According to what I found out, user 'algo' home directory ownership was messed up, which caused wrong permission 
to /home/algo/.ssh/authorized_keys. 

**To Reproduce**
virtual machine deployment on amazon Lightsail.

**Expected behavior**
After creating user account on algo server, proper home directory ownership management should be done.

**Additional context**
To bypass (solve) this problem, I edited /algo/files/cloud-init/sshd_config  (located at docker container),
I deleted "AllowGroups algo" line.

Then I loggined with default user account (:ubuntu) and use "chown" command at /home/algo.

**Comment by jackivanov** [comment]
What way the home directory ownership was messed up? Was that done because of the Algo scripts? @friendship1
