### ISSUE TITLE
Deploying to Azure fails

### ISSUE THREAD

**Issue by benzin1984** [trailofbits/algo#1906]
**Describe the bug**
When deploying to Azure, fails with this msg:

TASK [common : Install tools] ****************************************************************
fatal: [xx.xx.xx.xx]: FAILED! => {"changed": false, "msg": "Failed to update apt cache: "}

**To Reproduce**

Try deploying to Azure

**Additional context**
I've tested that "sudo apt update" on the newly deployed server is failing. The dns isn't correctly set up by the algo scripts. I've tried to set dns to both use dnscrypt and not use dnscrypt in config.cfg, fails in both cases. Looks like systemd-resolved isn't properly set up to use the dns addresses. Maybe something has changed in the latest azure ubuntu images. I've tried the default latest daily 20.04, and just latest 20.04, same error.

**Comment by dasmart** [comment]
I am having the same issue on Azure. Any helpappreciated!

**Comment by jackivanov** [comment]
I can confirm that after `systemd-networkd` restart the DNS are gone

**Comment by dasmart** [comment]
Well, I'm pleased to know it's not just me.

**Comment by dasmart** [comment]
Works. Thank you, sir!
