### ISSUE TITLE
no internet within the VM after a successful installation of Algo over Azure

### ISSUE THREAD

**Issue by shaheenkdr** [trailofbits/algo#1909]
I built algo using the provided shell script, the server is running, i can see the configs , the png of QR is there, but even to test that , i need to move the png to a machine with head. However, when I try to deploy a basic python3 server, it runs but cant load the webpage. Anything simple that I am missing ?

**Comment by sethgoldin** [comment]
@shaheenkdr Running into something similar here. Any clues?
