### ISSUE TITLE
The error was: 'client_ip' is undefined

### ISSUE THREAD

**Issue by fabioselau077** [trailofbits/algo#1911]
my command:
ansible-playbook deploy_client.yml -e ' client_ip = localhost vpn_user = laptop server_ip = my_droplets_ip ssh_user = root '
![image](https://user-images.githubusercontent.com/57275833/98430620-33661780-2085-11eb-8953-3ddaf4cd352a.png)
Follow this doc https://github.com/trailofbits/algo/blob/master/docs/client-linux.md

**Comment by davidemyers** [comment]
There are a lot of extra spaces in your command. Try it like it says in the documentation.

**Comment by fabioselau077** [comment]
> There are a lot of extra spaces in your command. Try it like it says in the documentation.

You are right, my lack of attention.
Another thing, for creating an app to connect to Flutter there is a plugin but it only works with support type of connection ikev-2.
Does Algo support the ikev-2 connection or just Wireguard?
Thanks

**Comment by davidemyers** [comment]
By default an AlgoVPN supports both WireGuard and IPsec IKEv2 connections.

**Comment by fabioselau077** [comment]
> By default an AlgoVPN supports both WireGuard and IPsec IKEv2 connections.

ok, nice good.
I have one question.
How to generate IPsec IKEv2 connections? I not found in documentation.
Will AlgoVPN generate the access data to access the VPN?

**Comment by davidemyers** [comment]
See the documentation for setting up IPsec clients [here](https://github.com/trailofbits/algo#setup-vpn-clients-to-connect-to-the-server).

**Comment by fabioselau077** [comment]
ok, thanks for help.
Thanks for AlgoVPN, I appreciate your effort and work.
