### ISSUE TITLE
Proposition for Algo Discord Page for more robust discussions/AlgoVPN now only loads Google searches and can’t access any other domains.

### ISSUE THREAD

**Issue by vkvkvkx** [trailofbits/algo#1912]
Hi,

I noticed since 2 days ago pages no longer load for me through Algo. Only Google hits are coming through. I’ve rebooted my server multiple times to no avail.

Also want to propose the establishment of a Discord community page for better (informal) communication than on GitHub.

Thanks

**Comment by jackivanov** [comment]
You can join us on [gitter](https://gitter.im/trailofbits/algo?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
