### ISSUE TITLE
Using Algo to access resources in a private cloud

### ISSUE THREAD

**Issue by jarrettprosser** [trailofbits/algo#1913]
Hey all,

I'm working on a project for which we'd like to set up an AWS VPC with private EKS resources, and be able to access them only through a VPN. Algo looks like a great contender, but I'm having trouble configuring it correctly. If I set up Algo by following the guide [here](https://github.com/trailofbits/algo/blob/master/docs/deploy-from-script-or-cloud-init-to-localhost.md), I can connect to the VPN host with WireGuard and have normal internet connectivity. So far so good. 

When I try to access the EKS control plane, the DNS request (which normally is resolved by a private Route 53 endpoint in the VPC) fails to resolve to the IP of the control plane endpoint. Running `nslookup` on the DNS name when connected to the VPN includes an error message:
```
nslookup B21FF7021020539336C693F43EC57DAB.gr7.ap-southeast-2.eks.amazonaws.com
Server:		172.21.200.91
Address:	172.21.200.91#53
Non-authoritative answer:
B21FF7021020539336C693F43EC57DAB.gr7.ap-southeast-2.eks.amazonaws.com	hinfo = "This query has been locally blocked" "by dnscrypt-proxy"
```
Is there a way I can force dnscrypt-proxy to use the AWS Route 53 endpoint as the DNS server, when I'm bootstrapping the application with `install.sh`? I suspect I can pass in extra args but I'm not sure how.

Thanks!

**Comment by davidemyers** [comment]
Using your private DNS resolver with `dnscrypt-proxy` will likely be very difficult. Instead, edit `config.cfg`  and set `dns_encryption: false`, then change `dns_servers` to point to your resolver(s).

**Comment by jarrettprosser** [comment]
Thanks David, that was the guidance I needed. I found that I can do the following:
- clone Algo into `/opt/algo`
- customise `config.cfg` to disable the `dns_encryption` and add `dns_servers`
- run `install.sh` 

I was worried that running `install.sh` again would overwrite the changes to the config, but it checks to see if the folder `/opt/algo` already exists and won't clone again if it does.
