### ISSUE TITLE
Algo and AnGuard Home

### ISSUE THREAD

**Issue by grubeli** [trailofbits/algo#1916]
I'm using [AdGuard Home](https://github.com/AdguardTeam/AdGuardHome) as a local DNS server with filters and GUI, I've setup the algo on the  same VM but now adguard is not accessible, I enabled UFW and allow 53 port, but after reboot UFW was disabled, so I enabled it with ```sudo systemctl disable netfilter-persistent```, now UWF is enabled after reboot but DNS service is still unreachable from outside.

Port 53 is not used by algo, I disabled DNS while installation

**Comment by davidemyers** [comment]
[AlgoVPN and Firewalls](https://github.com/trailofbits/algo/blob/master/docs/firewalls.md#algovpn-and-firewalls) says:

> The use of conflicting firewall packages on the server such as `ufw` will likely break AlgoVPN.

[Local Installation](https://github.com/trailofbits/algo/blob/master/docs/deploy-to-ubuntu.md#local-installation) says:

> Make sure your target server is running an unmodified copy of the operating system version specified.

**Comment by adrianocr** [comment]
I'm actually also trying to install AdGuard home in my algo vpn VPS but can't seem to get it to work. 

Got it installed through docker and the logs seem to indicate that it installed correctly and is running, but if I try to access the management console through the VPS' IP address, I can't get to the admin panel

**Comment by grubeli** [comment]
solved.
Algo uses netfilter so we need to use netfilter as well instead of uwf.

my solution:
After installing and finishing Algo, open 53, 80 and 443 ports
`iptables -A INPUT -p udp --dport 53 -j ACCEPT`
`iptables -A INPUT -p tcp --dport 3000 -j ACCEPT`

and save it via:
`netfilter-persistent save`
`netfilter-persistent reload`

So, this way we not interfering Algo.

NOTE: disable (set `false`) DNS encryption during algo installation
