### ISSUE TITLE
Failing To Install Using Vultr: SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by mydigia** [trailofbits/algo#1919]
Hi,
Algo running on: macOS 11.0.1
Created from git clone. Last commit: ebec20e Multiple Azure fixes (#1908)
Python 3.7.3
Runtime variables:
algo_provider "vultr"
algo_ondemand_cellular "True"
algo_ondemand_wifi "True"
algo_ondemand_wifi_exclude "TXlEaWdpYSA1R0h6"
algo_dns_adblocking "True"
algo_ssh_tunneling "True"
wireguard_enabled "True"
dns_encryption "True"

I tried installing on vultr with my api key in place, but the install fails at this stage:
```
TASK [Copy the private SSH key to /tmp] ******************************************************************************************************************************************
ok: [localhost -> localhost]
[cloud-vultr : pause]
Enter the local path to your configuration INI file
(https://trailofbits.github.io/algo/cloud-vultr.html):
:

TASK [cloud-vultr : pause] *******************************************************************************************************************************************************
ok: [localhost]

TASK [cloud-vultr : Set the token as a fact] *************************************************************************************************************************************
ok: [localhost]

TASK [cloud-vultr : Get regions] *************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "content": "", "elapsed": 0, "msg": "Status code was -1 and not [200]: Request failed: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)>", "redirected": false, "status": -1, "url": "https://api.vultr.com/v1/regions/list"}
included: /Users/USER/algo/playbooks/rescue.yml for localhost
```

Any ideas?

**Comment by davidemyers** [comment]
Where did you get your copy of Python? Did you see the note about `CERTIFICATE_VERIFY_FAILED`  on the page [Deploy from macOS](https://github.com/trailofbits/algo/blob/master/docs/deploy-from-macos.md)?

**Comment by mydigia** [comment]
No I had completely missed that sorry.

I deleted my python3, completely deleted my algo clone and redone after install python3 using homebrew, I have gone further now. Thanks so much for your speedy reply.
