### ISSUE TITLE
Running also on Digital Ocean shows 'FAILED - RETRYING' message for SSH key deletion

### ISSUE THREAD

**Issue by grempe** [trailofbits/algo#192]
When running `./algo` against digital ocean, after having previously deployed an algo VPN server there, the following message shows in the output:

```
...
TASK [cloud-digitalocean : Delete the existing Algo SSH keys] ******************
FAILED - RETRYING: TASK: cloud-digitalocean : Delete the existing Algo SSH keys (10 retries left).
ok: [localhost]

TASK [cloud-digitalocean : Upload the SSH key] *********************************
changed: [localhost]
...
```

I would not expect to see the `FAILED - RETRYING` message.

While it seems to work fine after the deploy, the message could confuse someone to believe that something failed. Not sure what the expected behavior is in the case where `configs/algo.pem` did or did not exist prior to this running, or if the directory was emptied and a new SSH private key was generated.

**Comment by dguido** [comment]
Can you reproduce this issue reliably? We have lots of issues with all cloud providers failing intermittently on certain requests. We have increased timeouts and retries across the board, but sometimes the cloud providers we use simply suffer from low reliability and intermittent failures.

**Comment by kennwhite** [comment]
I'm able to reliably reproduce, but I think this is a UI thing. On my terminal, the message (in very dark charcoal color, almost indistinguishable from my black background):
FAILED - RETRYING: TASK: cloud-digitalocean : Delete the existing Algo SSH keys (10 retries left).

And after a few seconds, continues:

ok: [localhost]

and the build continues successfully. So it did fail, hence the retry to remove/re-push new keys.

**Comment by grempe** [comment]
Yes, I saw the same as @kennwhite on several builds of new algo servers (I was testing out install options).

**Comment by grempe** [comment]
PS - If I remove the SSH key from DO manually prior to running `algo` I do not see this message.

**Comment by gunph1ld** [comment]
It's not a bug. 
This task implemented in order to ensure that you don't have ssh keys with the same names.
http://docs.ansible.com/ansible/playbooks_loops.html#do-until-loops

**Comment by grempe** [comment]
So it's expected behavior to *always* see:

```
FAILED - RETRYING: TASK: cloud-digitalocean : Delete the existing Algo SSH keys (10 retries left)
```

Every time after ever deploying Algo to DO?

**Comment by dguido** [comment]
Yes. These messages come from Ansible, which we have no control over. It is simply a status message and it has no effect on the overall completion of the deploy.

**Comment by grempe** [comment]
ok. Thanks for the follow up.
