### ISSUE TITLE
Suggestion: Move from Gitter to GitHub Discussions

### ISSUE THREAD

**Issue by davidemyers** [trailofbits/algo#1923]
GitHub Discussions looks like it would be better than Gitter for supporting Algo users. Some of the reasons are:

- The way Gitter conversations are interleaved makes it difficult to troubleshoot multiple issues at once.
- Searching for similar issues and their resolutions is very difficult on Gitter. History tends to get lost or ignored.
- Pastes of Algo output swamp other conversations on Gitter.
- GitHub Issues can be converted into Discussions, rather than just closed with "Go to Gitter".

**Comment by jackivanov** [comment]
Sounds like a nice idea! cc @dguido

**Comment by jackivanov** [comment]
I've updated the readme and docs

**Comment by davidemyers** [comment]
I'll monitor Gitter for a while and redirect people to Discussions.

Thanks.
