### ISSUE TITLE
SSH To Vultr Servers Don't Work

### ISSUE THREAD

**Issue by mydigia** [trailofbits/algo#1925]
I've repeated this issue on more than one server on Vultr. It works on Hetzner for example, but using the Shell access command: ssh -F config/SERVER_IP/ssh_config server_name the SSH to vultr fails with error: algo@192.248.177.217: Permission denied (publickey).

Appreciate if this could be looked at as currently don't have access to the server. Thanks.

**Comment by davidemyers** [comment]
Can you look in the `configs` directory and confirm that the file `algo.pem` is not newer than the directory with the name of your server's IP address (e.g., `192.248.177.217`)?

**Comment by mydigia** [comment]
Confirmed. `algo.pem` is as old as my algo directory is.

**Comment by davidemyers** [comment]
SSH must have been working for Algo to have completed the installation so it's a mystery as to why it's no longer working.

This probably won't help, but try rebooting the server from the Vultr web interface. There was recently an update to the OpenSSL package and maybe that's causing the problem, though I doubt it.

**Comment by davidemyers** [comment]
You can also use the Vultr web interface to log in to the console as `root` (you might need to type the `root` password rather than paste it). Once logged in you can run:
```
ls -la ~algo/.ssh
```
and confirm that neither that directory nor the `authorized_keys` file have somehow become world writable.

**Comment by mydigia** [comment]
Thanks @davidemyers but I am able to repeat this on fresh installs on Vultr as well which makes me wonder if this is limited to me or a bug actually?

**Comment by davidemyers** [comment]
I just installed to Vultr an hour ago so it seems to be limited to you.

**Comment by mydigia** [comment]
Just spent sometime on this and managed to figure out it was the .ssh folder and authorized_keys file that had too wide permission.

Deployed from my mac on 11.0.1 and Python 3.9 to Vultr in London with SSH users/PKI questions answered with yes, on demand connection questions answered with no.

Completely fresh install and SSH was failing with your command in the success message:

```
ssh -F configs/SERVER_IP/ssh_config nh-lon-vpn                                INT ✘  18:32:15 
algo@SERVER_IP: Permission denied (publickey).
```

I logged in through vultr console as you also highlighted and turns out .ssh directory under /home/algo had the wrong permission and /home/algo/.ssh/authorized_keys also had the wrong permission.

Changed .ssh folder from `755` to `500`
Changed authorized_keys file from `644` to `400`

Errors were:
`Authentication refused: bad ownership or modes for file /home/algo/.ssh/authorized_keys`
and
`Authentication refused: bad ownership or modes for directory /home/algo/.ssh`

**Comment by davidemyers** [comment]
Good job figuring this out. What I don't understand is why it works for me with even more open permissions:
```
algo@vpn9:~$ ll .ssh
total 12
drwxrwxr-x 2 algo algo 4096 Dec 13 12:11 ./
drwxr-xr-x 5 algo algo 4096 Dec 13 12:20 ../
-rw-rw-r-- 1 algo algo  381 Dec 13 12:11 authorized_keys
```
In any event I've submitted PR #1927 which should hopefully fix this issue for providers like Vultr.

**Comment by mydigia** [comment]
Thanks @davidemyers bizarre that this is working for you as on my other servers the exact same wide permissions deny me SSH connection with key and that the same works for you on vultr..

**Comment by mydigia** [comment]
FYI I have been able to repeat the same exact problem on Linode as well.
