### ISSUE TITLE
could not locate file in lookup: configs/IP/wireguard//.pki//private/phone"}

### ISSUE THREAD

**Issue by MazenElzanaty** [trailofbits/algo#1926]
TASK [wireguard : Generate public keys] *****************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'file'. Error was a <class 'ansible.errors.AnsibleError'>, original message: could not locate file in lookup: configs/serverPublicIP/wireguard//.pki//private/phone"}

On local ubuntu 18

**Comment by davidemyers** [comment]
Try removing the files mentioned in the [Troubleshooting](https://github.com/trailofbits/algo/blob/master/docs/troubleshooting.md#wireguard-unable-to-find-configs-in-expected-paths) document.

**Comment by MazenElzanaty** [comment]
Thank you
