### ISSUE TITLE
Install from Windows

### ISSUE THREAD

**Issue by dguido** [trailofbits/algo#193]
I doubt this will work but it's worth a try. It looks like Ansible can run on the new Linux subsystem, which gives some hope that we can use this to launch Algo. I wonder if the dependencies are too much though.

http://www.jeffgeerling.com/blog/2016/using-ansible-through-windows-10s-subsystem-linux

**Comment by mutemule** [comment]
FWIW, this is how I've been provisioning my Algo instances: the Linux subsystem (manually updated to 16.04) coupled with virtualenv.

**Comment by dguido** [comment]
wow neat! Can you write up the commands you needed to set it up?

**Comment by mutemule** [comment]
Yup! Let me just dig up my notes and throw them together.

I believe the next major update roll-up will include an update to 16.04, which will make all of this easier.
