### ISSUE TITLE
Allow the algo script to use local ENV VARS for service API keys

### ISSUE THREAD

**Issue by grempe** [trailofbits/algo#195]
This is related to issue #191, but not dependent on it. It would make it easier and more secure to use though.

When the algo script runs, if appropriate environment variables are set, it should gather API keys to use from the environment instead of forcing the user to copy and paste the keys every time. This would reduce the friction of running the `algo` script.

I would imaging a set of documented env variable names, optimally the same as that service may use for its own CLI programs to accomplish the same thing. Whenever an algo setup script is running, it would first check for the presence of this env var key and use it if present, or prompt the user if not.

For example, AWS has a common documented set of env vars that their own CLI expects. This may be an env var that anyone who uses that CLI may already have set. See : https://github.com/aws/aws-cli

Other services that have a CLI client probably define such env vars as well.

e.g.

```
# Digital Ocean API Key
export DIGITAL_OCEAN_API_KEY=abc123

# AWS
export AWS_ACCESS_KEY_ID=<access_key>
export AWS_SECRET_ACCESS_KEY=<secret_key>

# OTHER SERVICES
...

```

When running the advanced ansible scripts this env var could also be substituted so that the API key does not persist in the shell history.

**Comment by kennwhite** [comment]
NB: This is already in place and working for EC2. Press/script enter when prompted for Access Key and Secret Key if these are set in the environment:
https://github.com/trailofbits/algo/blob/master/roles/cloud-ec2/tasks/main.yml#L3

**Comment by grempe** [comment]
Yes, thanks Ken, I see that feature exists now for both Azure and AWS using this search:

https://github.com/trailofbits/algo/search?utf8=✓&q=lookup%28%27env%27

So the feature request would be to

* add the same for Digital Ocean and GCE (and appropriate future services
* document (wiki?) that these env vars are checked when the script runs, and document which env vars are checked for each service

**Comment by gunph1ld** [comment]
Implemented actually
