### ISSUE TITLE
Github repo ValdikSS/easy-rsa-ipsec is installed from WIP branch. Should be locked to SHA1

### ISSUE THREAD

**Issue by grempe** [trailofbits/algo#205]
The `easy-rsa-ipsec` project is installed for every `algo` installation based on the HEAD commit on the `ipsec-with-patches ` branch. Since this is a WIP development branch algo installs will always be using a moving target which is dangerous from a security perspective and which may pull in WIP breaking changes.

See:

https://github.com/trailofbits/algo/blob/master/roles/vpn/tasks/main.yml#L100

The most recent commit on that branch is:

https://github.com/ValdikSS/easy-rsa-ipsec/commit/9ce736e3d74c96450f9a29f94cdeb3b976b814ac

I would replace the branch specified with the current SHA1 at the tip of that branch. Future upgrades would then need to be intentional by advancing the SHA1 of the desired commit. You might also consider forking that repo and fetching updates from upstream as needed to avoid possible branch deletion.

Changes:

```
# from
version: ipsec-with-patches
...
# to
version: 9ce736e3d74c96450f9a29f94cdeb3b976b814ac
```

This is documented here:

http://docs.ansible.com/ansible/git_module.html

**Comment by dguido** [comment]
We're eliminating the dependency on easy-rsa-ipsec in the local openssl tasks PR: https://github.com/trailofbits/algo/pull/169

**Comment by grempe** [comment]
👍🏼
