### ISSUE TITLE
Unexpected response: SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by turnersr** [trailofbits/algo#206]
### OS / Environment
OS X version 10.11.6

### Ansible version
ansible 2.2.0.0

### Summary of the problem
Unable to create server due to SSL: CERTIFICATE_VERIFY_FAILED

### Steps to reproduce the behavior
./algo

### Expected behavior
Google cloud instance created with VPN. 

### Actual behavior
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Unexpected response: (('[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)',)). Detail: Traceback (most recent call last):\n  File \"/var/folders/yl/xl_dbwtx5z96398jpjswfqvh0000gn/T/ansible_kXkNkn/ansible_modlib.zip/ansible/module_utils/gcp.py\", line 105, in gcp_connect\n    project=project_id)\n  File \"/Users/turnersr/anaconda2/lib/python2.7/site-packages/libcloud/compute/drivers/gce.py\", line 1697, in __init__\n    super(GCENodeDriver, self).__init__(user_id, key, **kwargs)\n  File \"/Users/turnersr/anaconda2/lib/python2.7/site-packages/libcloud/common/base.py\", line 1190, in __init__\n    self.connection = self.connectionCls(*args, **conn_kwargs)\n  File \"/Users/turnersr/anaconda2/lib/python2.7/site-packages/libcloud/compute/drivers/gce.py\", line 98, in __init__\n    credential_file=credential_file, **kwargs)\n  File \"/Users/turnersr/anaconda2/lib/python2.7/site-packages/libcloud/common/google.py\", line 765, in __init__\n    user_id, key, auth_type, credential_file, scopes, **kwargs)\n  File \"/Users/turnersr/anaconda2/lib/python2.7/site-packages/libcloud/common/google.py\", line 660, in __init__\n    self.token = self.oauth2_conn.get_new_token()\n  File \"/Users/turnersr/anaconda2/lib/python2.7/site-packages/libcloud/common/google.py\", line 537, in get_new_token\n    return self._token_request(request)\n  File \"/Users/turnersr/anaconda2/lib/python2.7/site-packages/libcloud/common/google.py\", line 368, in _token_request\n    data=data)\n  File \"/Users/turnersr/anaconda2/lib/python2.7/site-packages/libcloud/common/base.py\", line 860, in request\n    raise ssl.SSLError(str(e))\nSSLError: ('[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)',)\n"}

### Full log
bash-3.2$ ./algo

  What provider would you like to use?
    1. DigitalOcean
    2. Amazon EC2
    3. Google Compute Engine
    4. Microsoft Azure
    5. Install to existing Ubuntu server

Enter the number of your desired provider
: 3

Enter the local path to your credentials JSON file (https://support.google.com/cloud/answer/6158849?hl=en&ref_topic=6262490#serviceaccounts):
: /Users/turnersr/Downloads/algo1-asdf2134.json

Name the vpn server:
[algo]:

  What zone should the server be located in?
    1. Central US       (Iowa A)
    2. Central US       (Iowa B)
    3. Central US       (Iowa C)
    4. Central US       (Iowa F)
    5. Eastern US       (South Carolina B)
    6. Eastern US       (South Carolina C)
    7. Eastern US       (South Carolina D)
    8. Western Europe   (Belgium B)
    9. Western Europe   (Belgium C)
    10. Western Europe  (Belgium D)
    11. East Asia       (Taiwan A)
    12. East Asia       (Taiwan B)
    13. East Asia       (Taiwan C)
Please choose the number of your zone. Press enter for default (#8) zone.
[8]: 1

Do you want to enable VPN Always-On when connected to cellular networks?
[y/N]: N

Do you want to enable VPN Always-On when connected to Wi-Fi?
[y/N]: Y

Do you want to exclude trusted Wi-Fi networks from using the VPN? (e.g., your home network. Comma-separated value, e.g., HomeNet,OfficeWifi,AlgoWiFi)
:

Do you want to install a local DNS resolver to block ads while surfing?
[y/N]: N

Do you want each user to have their own account for SSH tunneling?
[y/N]: Y

Do you want to apply operating system security enhancements on the server?
[y/N]: Y

Do you want the VPN to support Windows 10 clients? (requires RSA certificates and key exchange, less secure)
[y/N]: N

PLAY [Configure the server] ****************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Generate the SSH private key] ********************************************
ok: [localhost -> localhost]

TASK [Generate the SSH public key] *********************************************
ok: [localhost -> localhost]

TASK [Change mode for the SSH private key] *************************************
ok: [localhost -> localhost]

TASK [cloud-gce : set_fact] ****************************************************
ok: [localhost]

TASK [cloud-gce : Creating a new instance...] **********************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Unexpected response: (('[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)',)). Detail: Traceback (most recent call last):\n  File \"/var/folders/yl/xl_dbwtx5z96398jpjswfqvh0000gn/T/ansible_kXkNkn/ansible_modlib.zip/ansible/module_utils/gcp.py\", line 105, in gcp_connect\n    project=project_id)\n  File \"/Users/turnersr/anaconda2/lib/python2.7/site-packages/libcloud/compute/drivers/gce.py\", line 1697, in __init__\n    super(GCENodeDriver, self).__init__(user_id, key, **kwargs)\n  File \"/Users/turnersr/anaconda2/lib/python2.7/site-packages/libcloud/common/base.py\", line 1190, in __init__\n    self.connection = self.connectionCls(*args, **conn_kwargs)\n  File \"/Users/turnersr/anaconda2/lib/python2.7/site-packages/libcloud/compute/drivers/gce.py\", line 98, in __init__\n    credential_file=credential_file, **kwargs)\n  File \"/Users/turnersr/anaconda2/lib/python2.7/site-packages/libcloud/common/google.py\", line 765, in __init__\n    user_id, key, auth_type, credential_file, scopes, **kwargs)\n  File \"/Users/turnersr/anaconda2/lib/python2.7/site-packages/libcloud/common/google.py\", line 660, in __init__\n    self.token = self.oauth2_conn.get_new_token()\n  File \"/Users/turnersr/anaconda2/lib/python2.7/site-packages/libcloud/common/google.py\", line 537, in get_new_token\n    return self._token_request(request)\n  File \"/Users/turnersr/anaconda2/lib/python2.7/site-packages/libcloud/common/google.py\", line 368, in _token_request\n    data=data)\n  File \"/Users/turnersr/anaconda2/lib/python2.7/site-packages/libcloud/common/base.py\", line 860, in request\n    raise ssl.SSLError(str(e))\nSSLError: ('[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)',)\n"}

PLAY RECAP *********************************************************************
localhost                  : ok=5    changed=0    unreachable=0    failed=1

**Comment by gunph1ld** [comment]
Can't reproduce, works well on my side. 
Can you try to re-install all the [requirements](https://github.com/trailofbits/algo/blob/master/requirements.txt)?

**Comment by gunph1ld** [comment]
@turnersr any updates?

**Comment by turnersr** [comment]
Sorry, the late response. It works now. I think the error was, oddly enough, actually with my configuration of the VM. Thanks for the awesome tool.

**Comment by dguido** [comment]
👍
