### ISSUE TITLE
VPN Setup script for Windows 7

### ISSUE THREAD

**Issue by eureki** [trailofbits/algo#212]
### OS / Environment
Ubuntu 16.04.1 LTS

### Ansible version
2.2.0.0

### Version of components from `requirements.txt`
Name: boto
Version: 2.38.0
Name: dopy
Version: 0.3.5
Name: azure
Version: 2.0.0rc5
Name: apache-libcloud
Version: 1.5.0
Name: six
Version: 1.10.0
Name: pyOpenSSL
Version: 16.2.0

### Summary of the problem
The generated Powershell script is not compatible with Windows 7. This is because the Powershell Cmdlets "Add-VpnConnection" and "Set-VpnConnectionIPsecConfiguration" are not available on Windows distributions below Windows 8.

Are you able to provide an alternate configuration script for Windows 7?

### Steps to reproduce the behavior
Attempt to run the user_windows.ps1 script on Windows 7. i.e

`Add-VpnConnection -name {name} -ServerAddress {ip-address} -TunnelType IKEv2 -AuthenticationMethod MachineCertificate -EncryptionLevel Required`
`Set-VpnConnectionIPsecConfiguration -ConnectionName "Algo" -AuthenticationTransformConstants SHA256128 -CipherTransformConstants AES256 -EncryptionMethod AES256 -IntegrityCheckMethod SHA256 -DHGroup Group14 -PfsGroup none`

### The way of deployment (cloud or local)
Local on a GCE instance

### Expected behavior
VPN connection to be configured for use.

### Actual behavior
Error:

`The term 'Add-VpnConnection' is not recognized as the name of a cmdlet, function, script file, or operable program`
`The term 'Set-VpnConnectionIPsecConfiguration' is not recognized as the name of a cmdlet, function, script file, or operable program`

**Comment by dguido** [comment]
We generally do not support older versions of clients beyond the most current. They have significantly weaker support for the crypto algorithms and modes we use and IKEv2 in general. I would recommend trying again with Windows 8.1 or 10.
