### ISSUE TITLE
Additional testing

### ISSUE THREAD

**Issue by jackivanov** [trailofbits/algo#213]
Need to extend [the testing script](https://github.com/trailofbits/algo/blob/master/.travis.yml)

- [x] Update-users
- [x] Try to up the ipsec connection
- [x] Try to lookup DNS
- [x] SSH tunnels
- [x] shellcheck
- [x] ansible-lint

**Comment by dguido** [comment]
Test that iptables rules were successfully set

**Comment by gunph1ld** [comment]
- [ ] shellcheck
- [ ] ansible-lint

**Comment by jackivanov** [comment]
- [ ] XML validation for Apple configuration files
- [ ] WireGuard config validation
