### ISSUE TITLE
Improve the MTU/MSS troubleshooting instructions

### ISSUE THREAD

**Issue by dguido** [trailofbits/algo#216]
This issue seems to be afflicting many more people than we realized and we need clear instructions for how to recognize when the situation occurs, how to measure for the correct MTU, and how to input the correct settings when you find them.

http://www.tech-wiki.net/index.php?title=MTU/MSS_-_How_to_test_using_PING
http://muzso.hu/2009/05/17/how-to-determine-the-proper-mtu-size-with-icmp-pings
http://www.cisco.com/c/en/us/support/docs/ip/generic-routing-encapsulation-gre/25885-pmtud-ipfrag.html
https://www.zeitgeist.se/2013/11/26/mtu-woes-in-ipsec-tunnels-how-to-fix/
https://wiki.strongswan.org/projects/strongswan/wiki/ForwardingAndSplitTunneling#MTUMSS-issues

**Comment by kiratp** [comment]
This might be helpful: https://cloud.google.com/compute/docs/vpn/advanced#maximum_transfer_unit_mtu_considerations

PS I seem to be running in the same issue. I have a working deployment on Azure but the same one on GCE seems to allow pings but DNS packets seem be lost. MTU on the tunnel client side is set to 1400.

**Comment by dguido** [comment]
Neat, GCE has a guide for making VPNs too: https://cloud.google.com/compute/docs/vpn/creating-vpns

**Comment by gaving** [comment]
Is there any additional debugging steps that can be done to figure this out? I've certain sites not loading e.g. (github.com) and others fine e.g. (bbc.co.uk).. I've tried messing about with my MTU settings on both the Digital Ocean algo server and my clients but not having any luck with that either.

**Comment by gaving** [comment]
@logannc 👍 🎆 your iptables command referenced under #422 sorted out my issues!

**Comment by dguido** [comment]
We added some extra commands for troubleshooting to the Troubleshooting doc.

**Comment by miltador** [comment]
By applying iptables rules from [this](https://www.zeitgeist.se/2013/11/26/mtu-woes-in-ipsec-tunnels-how-to-fix/) article I resolved all the issues and also got 3x boost in download speeds in tunnel.

**Comment by miltador** [comment]
For IPv6 I had to lower MTU to 1280 as per [this](https://blog.cloudflare.com/path-mtu-discovery-in-practice/) article in order to successfully pass all tests on http://test-ipv6.com/

**Comment by aleks-mariusz** [comment]
I was having issues getting ssh to work (would hang after `debug1: expecting SSH2_MSG_KEX_ECDH_REPLY` when ssh client expects the server host key) and ended up finding it was MTU related afterall.. 

I could not get the [iptables MTU mangling approach](https://www.zeitgeist.se/2013/11/26/mtu-woes-in-ipsec-tunnels-how-to-fix/) that @miltador initially proposed working on the server side ( went as low as 1200 before giving up).. so i used @miltador 's later approach to twiddle the MTU at the routing table level, and eventually determined the maximum mtu before ssh started failing again at 1438.

To make the setting change persistent, on the client i created file `/etc/strongswan/strongswan.d/fix-mtu.conf` with the following contents:

```
charon {
  plugins {
    kernel-netlink {
        mtu = 1438
    }
  }
}
```

resulting in those MTU settings being applied each time the client brings the connection up.
