### ISSUE TITLE
ERROR! no action detected in task

### ISSUE THREAD

**Issue by creativetags** [trailofbits/algo#218]
### OS / Environment
Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-53-generic x86_64)

### Ansible version

2.0.0.2-2ubuntu1

### Summary of the problem
Install failed

### The way of deployment (cloud or local)
local

### Full log

./algo

  What provider would you like to use?
    1. DigitalOcean
    2. Amazon EC2
    3. Google Compute Engine
    4. Microsoft Azure
    5. Install to existing Ubuntu server

Enter the number of your desired provider
: 5

Enter IP address of your server: (use localhost for local installation)
:            localhost

What user should we use to login on the server? (ignore if you're deploying to localhost)
[root]: 

Enter the public IP address of your server: (IMPORTANT! This IP is used to verify the certificate)
: MY_IP

Do you want to enable VPN Always-On when connected to cellular networks?
[y/N]: N

Do you want to enable VPN Always-On when connected to Wi-Fi?
[y/N]: N

Do you want to install a local DNS resolver to block ads while surfing?
[y/N]: N

Do you want each user to have their own account for SSH tunneling?
[y/N]: N

Do you want to apply operating system security enhancements on the server?
[y/N]: N

Do you want the VPN to support Windows 10 clients? (requires RSA certificates and key exchange, less secure)
[y/N]: N
ERROR! no action detected in task

The error appears to have been in '/root/algo-master/roles/cloud-azure/tasks/main.yml': line 6, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: Create a resource group
  ^ here

**Comment by dguido** [comment]
Did you install all the requirements as described in the readme? We don't support Ansible 2.0.0.

**Comment by creativetags** [comment]
Thanks, it seems I hadn't done **sudo apt-get update** before **sudo apt-get install ansible**
