### ISSUE TITLE
macOS 10.10.5 & iOS 7.1.2:  No auto setup with config file

### ISSUE THREAD

**Issue by knightknight** [trailofbits/algo#223]
### OS / Environment
* macOSX 10.10.5 YOSMITE
* iOS 7.1.2

### Ansible version
localhost:algo (master*) $ ansible --version 
ansible 2.2.0.0
  config file = /Users/andyc/python/algo/ansible.cfg
  configured module search path = Default w/o overrides

### Version of components from `requirements.txt`
localhost:algo (master*) $ pip show ansible  
---
Metadata-Version: 1.1
Name: ansible
Version: 2.2.0.0
Summary: Radically simple IT automation
Home-page: http://ansible.com/
Author: Ansible, Inc.
Author-email: info@ansible.com
License: GPLv3
Location: /usr/local/lib/python2.7/site-packages
Requires: paramiko, jinja2, PyYAML, setuptools, pycrypto
Classifiers:
  Development Status :: 5 - Production/Stable
  Environment :: Console
  Intended Audience :: Developers
  Intended Audience :: Information Technology
  Intended Audience :: System Administrators
  License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)
  Natural Language :: English
  Operating System :: POSIX
  Programming Language :: Python :: 2.6
  Programming Language :: Python :: 2.7
  Topic :: System :: Installation/Setup
  Topic :: System :: Systems Administration
  Topic :: Utilities
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

### Summary of the problem
ALGO has been installed on DIgital Ocean and the configuration files has been emailed to me via DropBox. I download the file, unzipped/decrypted and then double clicked to open it.

Opening xxx.xx.xxx.xxx_user_ipsec.conf on;

* macOSX 10.10.5, defaults to File Viewer
* iOS iPhone4S 7.1.2 defaults to Text Viewer

What do I need to open/read this file and import the correct settings??

### Steps to reproduce the behavior
macOSX 10.10.5, open file xxx.xx.xxx.xxx_user_ipsec.conf, default option is File Viewer.

### The way of deployment (cloud or local)
Local

### Expected behavior
From docs, 'On macOS, double-clicking a profile to install it will fully configure the VPN. On iOS, users are prompted to install the profile as soon as the AirDrop is accepted.'

### Actual behavior
File on macOSX 10.10.5 and iOS 7.1.2 is defaulting to File Viewer or Text Viewer.

In the File/Text Viewer I can see all the settings.

conn ikev2-xxx.xx.xxx.xxx
    fragmentation=yes
    rekey=no
    dpdaction=clear
    keyexchange=ikev2
    compress=yes
    dpddelay=35s

    ike=aes128gcm16-sha2_256-prfsha256-ecp256
    esp=aes128gcm16-sha2_256-ecp256

    right=xxx.xx.xxx.xxx
    rightid=xxx.xx.xxx.xxx
    rightsubnet=0.0.0.0/0
    rightauth=pubkey

    leftsourceip=%config
    leftauth=pubkey
    leftcert=xxx.xx.xxx.xxx_user.crt
    leftfirewall=yes
    left=%defaultroute

    auto=add

**Comment by dguido** [comment]
Your administrator emailed you the wrong files. What you have is not the mobileconfig file.

You should be aware, however, that I don't think the Always-On VPN settings work on macOS 10.10 or iOS 7. You should upgrade both to more recent versions before continuing.
