### ISSUE TITLE
No package matching 'cgroup-tools' is available

### ISSUE THREAD

**Issue by bdwilson** [trailofbits/algo#224]
### OS / Environment

Raspberry Pi / Rasbian 7

### Ansible version

2.2.1.0

### Version of components from requirements.txt

ansible>=2.1,<2.2.1
dopy==0.3.5
boto>=2.5
boto3
azure==2.0.0rc5
apache-libcloud
six
pyopenssl
jinja2==2.8

### Summary of the problem

Cannot complete installation. Finish all the questions. Missing package cgroup-tools. 

### Steps to reproduce the behavior

Attempt install on Raspbian 7.

### The way of deployment (cloud or local)

Local install, local RaspberryPI

### Full log

$ ./algo

What provider would you like to use?
1. DigitalOcean
2. Amazon EC2
3. Google Compute Engine
4. Microsoft Azure
5. Install to existing Ubuntu server

Enter the number of your desired provider
: 5

Enter IP address of your server: (use localhost for local installation)
: localhost

What user should we use to login on the server? (ignore if you're deploying to localhost)
[root]:

Enter the public IP address of your server: (IMPORTANT! This IP is used to verify the certificate)
: xxx.xxx.xxx.xxx

Do you want to enable VPN Always-On when connected to cellular networks?
[y/N]:

Do you want to enable VPN Always-On when connected to Wi-Fi?
[y/N]:

Do you want to install a local DNS resolver to block ads while surfing?
[y/N]:

Do you want each user to have their own account for SSH tunneling?
[y/N]:

Do you want to apply operating system security enhancements on the server?
[y/N]:

Do you want the VPN to support Windows 10 clients? (requires RSA certificates and key exchange, less secure)
[y/N]:

failed: [localhost] (item=[u'git', u'screen', u'apparmor-utils', u'uuid-runtime', u'coreutils', u'sendmail', u'iptables-persistent', u'cgroup-tools', u'openssl']) => {
    "failed": true,
    "invocation": {
        "module_args": {
            "allow_unauthenticated": false,
            "autoremove": false,
            "cache_valid_time": 0,
            "deb": null,
            "default_release": null,
            "dpkg_options": "force-confdef,force-confold",
            "force": false,
            "install_recommends": null,
            "name": [
                "git",
                "screen",
                "apparmor-utils",
                "uuid-runtime",
                "coreutils",
                "sendmail",
                "iptables-persistent",
                "cgroup-tools",
                "openssl"
            ],
            "only_upgrade": false,
            "package": [
                "git",
                "screen",
                "apparmor-utils",
                "uuid-runtime",
                "coreutils",
                "sendmail",
                "iptables-persistent",
                "cgroup-tools",
                "openssl"
            ],
            "purge": false,
            "state": "latest",
            "update_cache": false,
            "upgrade": null
        },
        "module_name": "apt"
    },
    "item": [
        "git",
        "screen",
        "apparmor-utils",
        "uuid-runtime",
        "coreutils",
        "sendmail",
        "iptables-persistent",
        "cgroup-tools",
        "openssl"
    ],
    "msg": "No package matching 'cgroup-tools' is available"
}

PLAY RECAP *********************************************************************
localhost                  : ok=9    changed=4    unreachable=0    failed=1

**Comment by gunph1ld** [comment]
Raspberry Pi / Rasbian 7 is not supported. We support Ubuntu 16.04 only

**Comment by bdwilson** [comment]
My 14.04 LTS machine doesn't have cgroup-tools either.  Question why cgroup-tools is in the main installation requirement when it's only used for dnsmasq and privoxy options?
