### ISSUE TITLE
Breaks use of local DNS server dnscrypt

### ISSUE THREAD

**Issue by quinncomendant** [trailofbits/algo#225]
I installed Algo rev 8d21923 installed to digitalocean from macOS 10.11.6.

After connecting to my newly setup Algo VPN, my local DNS resolver stops working. I'm using the [Cisco Umbrella](https://umbrella.cisco.com/products/features) Roaming Client (which is just [dnscrypt-proxy](https://dnscrypt.org/#dnscrypt-proxy), with some GUI). The local DNS server is configured to connect to OpenDNS servers 208.67.222.222 and 208.67.220.220 over port 443 (TCP and UDP).

Resolving using a remote DNS server still works:

    [q@localhost] dig @8.8.8.8 time.strangecode.com +short
    oak.strangecode.com.
    98.129.251.228

But resolving using 127.0.0.1 fails:

    [q@localhost] dig @127.0.0.1 time.strangecode.com +short
    ; <<>> DiG 9.8.3-P1 <<>> @127.0.0.1 time.strangecode.com +short
    ; (1 server found)
    ;; global options: +cmd
    ;; connection timed out; no servers could be reached

(NB: I added `127.0.0.1` to the *DNS Servers* setting of the Algo VPN in Network Settings, and is reflected in `/etc/resolv.conf`.)

Can you think why Algo might be blocking this?

**Comment by quinncomendant** [comment]
Fixed. I contacted the Umbrella support team, who were able to fix something on their end to allow local dns with Algo. It's working now (except their diagnostic tool still reports the DNS lookups are ’Unencrypted’; I'm doing followup with them to determine what that means and will post a new ticket if we find any issue with Algo).

**Comment by dguido** [comment]
Cool, thanks for looking into it.
