### ISSUE TITLE
Support for CentOS

### ISSUE THREAD

**Issue by vukasin-nikodijevic** [trailofbits/algo#227]
### OS / Environment
CentOS 7 - 3.10.0-514.6.1.el7.x86_64 #1 SMP Wed Jan 18 13:06:36 UTC 2017 x86_64

### Summary of the problem
I really expect to have possibility to install VPN on CentOS/RHEL as most deployed server distro. What I got is possibility to install only on Ubuntu server - really strange.

### Steps to reproduce the behavior
See log part

### The way of deployment (cloud or local)
local

### Expected behavior
To be able to install on RedHat Like distro

### Actual behavior
It offers only Ubuntu server.

### Full log

```
# ./algo 

  What provider would you like to use?
    1. DigitalOcean
    2. Amazon EC2
    3. Google Compute Engine
    4. Microsoft Azure
    5. Install to existing Ubuntu server

Enter the number of your desired provider
: 5

.
.
.

TASK [Install prerequisites] ***************************************************
fatal: [localhost]: FAILED! => {"changed": true, "failed": true, "rc": 1, "stderr": "sudo: apt-get: command not found\n", "stdout": "", "stdout_lines": []}
```

**Comment by gunph1ld** [comment]
#262 Should be merged first

**Comment by sashkab** [comment]
Yesterday I've spend couple hours trying to install Algo on my Centos 7.3 server. Well, it installed (crashed couple times on the way reporting missing paths), but in the end I've got not working installation:
1. ipsec was still disabled in the firewalld.
2. strongswan service wasn't enabled, and didn't start automatically.
3. there were couple of cases where paths were missing in the `/etc/ipsec.d`

Before running Algo, I followed [Algo pre-install steps for Red Hat/CentOS 6.x (currently 6.8)](https://github.com/trailofbits/algo/blob/master/docs/pre-install_redhat_centos_6.x.md) -- I've noticed 6.8 parth **after** installation failed. I didn't have much time to troubleshoot this, but fixing the three failures referenced above didn't get VPN up and running and I somewhat don't have time to troubleshoot this further, but if you'll point me into right direction -- would appreciate.

**Comment by Thermi** [comment]
Supporting firewalld is laborious at best and impossible at last. Just don't use it for IPsec. It's too complex for firewall frameworks.

The RHEL distros put strongSwan configuration files in `/etc/strongswan/`.

**Comment by dguido** [comment]
I think Algo is complicated enough already. Let's stick to just three server OS's: Ubuntu, FreeBSD, and OpenBSD.

**Comment by lazerl0rd** [comment]
@dguido isn't CentOS used quite widely as a server? Hopefully I'll try learn more about Ansibile but until then I'm cool to help out with CentOS stuff you need until then. I use it quite a lot.

We can still disable firewalld and switch to iptables if that's what you were talking about?

**Comment by lazerl0rd** [comment]
@sashkab sorry I'm a bit late but
1) don't use firewalld (switch to iptables/ip6tables instead and yum install iptables-services)
2) install epel prior to strongswan
3) prolly cause of 2)?
