### ISSUE TITLE
Unencrypted connections with dnscrypt-proxy

### ISSUE THREAD

**Issue by quinncomendant** [trailofbits/algo#229]
I installed Algo rev 8d21923 to digitalocean from macOS 10.11.6. I'm using the [Cisco Umbrella](https://umbrella.cisco.com/products/features) Roaming Client (which is just [dnscrypt-proxy](https://dnscrypt.org/#dnscrypt-proxy), with some GUI). The local DNS server is configured to connect to OpenDNS servers 208.67.222.222 and 208.67.220.220 over port 443 (TCP and UDP).

After connecting to my newly setup Algo VPN, the Roaming Client menubar shows a status of "Unencrypted," which means dnscrypt-proxy is unable to send DNS queries to 208.67.222.222 and 208.67.220.220 over port 443 (TCP and UDP). If the Roaming Client can't forward DNS over port 443, it falls back to using port 53 and displays the "Unencrypted" status. It seems there may be something with Algo that is preventing secure DNS connections. 

I wrote to Umbrella support, and they said, "the problem can be caused by your VPN utilizing the DNS of the network that you are connected to via VPN." Which I take to mean that the VPN may be enforcing use of its configured DNS servers. However, I'm not sure that is the case. When I'm connected to Algo, and while the Roaming Client is running in "Unencrypted" status, I see that my DNS is still using OpenDNS resolver addresses [1], albeit on port 53. If Algo enforced it's own DNS routing, it would be using Google resolvers (via 8.8.8.8).

Any ideas how to configure Algo to support DNS over port 443? 

[1] To test this I'm using `dig whoami.akamai.net` and `dig whoami.ultradns.net`.

**Comment by gunph1ld** [comment]
Actually, VPN it's just a routing level, and not affected on any other levels (applications as example).
The root of this problem may appears from the Cisco client.
Such behaviour reminds me [a bug with Little snitch](https://github.com/trailofbits/algo/blob/master/docs/TROUBLESHOOTING.md#3-little-snitch-is-broken-when-connected-to-the-vpn)

**Comment by quinncomendant** [comment]
@gunph1ld I understand what you mean, but that doesn't seem to be the case here. I'm using the following command to emulate the DNS queries made by the Cisco Umbrella Roaming Client:

    dig @208.67.222.222 -p 443 +time=10 debug.opendns.com txt

When connected to the Algo VPN, this query fails (*connection timed out; no servers could be reached*). When connected to a different VPN, the query succeeds.

I also doubt the VPN could be causing this, since it is such a basic network request. I just thought I'd ask if there was something I'm not considering.

**Comment by gunph1ld** [comment]
@quinncomendant Do you use DigitalOcean ? 
I just made a clean ubuntu droplet and for some reason it does not work from the DO's network. 
AWS works well

**Comment by quinncomendant** [comment]
@gunph1ld I am using DO. I've noticed many websites block http requests from DO's network, e.g., starwoodhotels.com and typepad.com, so perhaps Umbrella is doing that too. Are you using dnscrypt-proxy with Algo on AWS? I might just move mine there.

**Comment by gunph1ld** [comment]
@quinncomendant No, I'm not, I checked the request you sent on my test EC2 and DO instances, that's it.
We need to ask DO support I guess

**Comment by quinncomendant** [comment]
I can confirm that dnscrypt-proxy runs fine with Algo on AWS. The problem occurs only when using DigitalOcean. I've submitted a support request to them asking for their insight. 

I think this may be related to a broader issue with DigitalOcean's network. I've discovered more than a few http sites that are inaccessible when connected to a VPN at DigitalOcean, which do connect fine when using AWS. This may be related to a security policy used by a CDN (I've seen some clues that show Akamai is one network that blocks DigitalOcean). It may not be DigitalOcean's fault, but it will prevent me from recommending DigitalOcean for use as a VPN.

**Comment by quinncomendant** [comment]
Solved! DigitalOcean is blocking UDP packets over port 443 or 80 (this should be trouble for more than just dnscrypt, e.g., Chrome's QUIC protocol):

> ----- Forwarded message from DigitalOcean, 02 Mar 2017 13:54:14 -----
> The actual reason that this isn't working is that we don't allow UDP packets over port 443 or 80. Many network and service damaging attacks use UDP traffic over those ports and thus we block them to keep our environment safe. We do apologize for the inconvenience this causes.

**Comment by dguido** [comment]
Thanks for looking into this! This definitely deserves an FAQ entry.

**Comment by mholt** [comment]
Uhhh yikes, is that new?? I've been using QUIC on DO for some time now and am surprised if it just got blocked.

**Comment by quinncomendant** [comment]
BTW, I asked DigitalOcean if there is any possibility to remove the filtering of UDP on port 443/80 and they replied:

> Unfortunately we wouldn't be able to remove this filter as it exposes many security risks to the droplets running on the physical machine and to the network in general.

**Comment by quinncomendant** [comment]
Plot twist! 

DigitalOcean followed up on my earlier support request, this time with a positive twist. They were able to remove the port 80/443 UDP block for my account. They plan to remove the block entirely from their infrastructure, but in the meantime, anyone can request to have the block removed from their account. 

I've setup a new Algo VPN droplet, and DNS over port 443 UDP is working. 👍

Here's the full thread of our conversation:

On Sat, 04 Mar 2017 22:16:26 +0000, DigitalOcean (Jon Schwenn) wrote:
> I wanted to let you know that after more testing I believe I have 
> narrowed down the filtering issue. I'm going to see what we can do to 
> resolve that on Monday.

On Mon, 06 Mar 2017 21:41:18 +0000, DigitalOcean (Jon Schwenn) wrote:
> To follow up on our earlier conversation, I have narrowed down where 
> there is still a remaining block on that port and protocol 
> combination.  I've escalated a request to remove it for you.  I'll be 
> in touch when that is processed.  Also, I have a longer running task 
> of working with various teams to remove it on a more general basis as 
> we have done with the blocks in other areas of the network stack.

On Fri, 10 Mar 2017 06:33:44 +0530, Quinn Comendant wrote:
> Cool! I'll also need some certainty that future droplets created at DO 
> will not have this block if I am going to recommend DO to my colleagues. 
> Please let me know if you can make a statement that I can share publically.

On Fri, 10 Mar 2017 01:18:58 +0000, DigitalOcean (Jon Schwenn) wrote:
> As soon as my request is completed through engineering you'll be all 
> set and I'll update this ticket. All of your future Droplets would be 
> affected and will be able to pass the traffic. I do not have any 
> platform-wide answers or statements, but that is something we are 
> working on as well.  It's much faster to clear it for just a few 
> accounts, so that is what we are doing in the interim. The 
> engineering team specific to this work is a bit backed up and that is 
> why it's taking longer than I'd like.  Please know that it is 
> something that we are working on and I will be getting back to you 
> soon.

On Fri, 10 Mar 2017 08:08:52 +0530, Quinn Comendant wrote:
> I have a few collegues who are waiting on an answer to this as well. 
> I had suggested they go with DO, but then it's like, oh, wait, no. 
> After they setup their account, is it as simple as submitting a 
> request to have the block removed? Can you promise that will be 
> achievable for every new account?

On Fri, 10 Mar 2017 02:54:15 +0000, DigitalOcean (Jon Schwenn) wrote:
> The goal is to loosen this restriction platform wide.  We already 
> removed them from other areas of the platform, and this is the last 
> remaining place where it is blocked. At this time I can not make any 
> promises or give specific ETA's, but I don't foresee a problem 
> getting this done at the platform level. 

On Fri, 10 Mar 2017 10:15:35 +0530, Quinn Comendant wrote:
> When you say "from other areas of the platform" does that mean from 
> other regions? Eg., If N California has blocks, perhaps East coast 
> doesn't?

On Fri, 10 Mar 2017 04:57:03 +0000, DigitalOcean (Jon Schwenn) wrote:
> I apologize for not being clearer. The block was in place in multiple 
> locations within the platform. 
> 
> Some of the "locations" would be the edge routers in our Network, 
> hypervisors, and the virtual switch software that provides Droplets 
> with connectivity.  We've already had this block removed at the edge 
> routers and other areas of the network.
> 
> If and when we clear the remaining block, every region would be open 
> at that point.  

On Fri, 10 Mar 2017 19:25:16 +0000, DigitalOcean (Jon Schwenn) wrote:
> You should be good to create new Droplets to test this out further.  
> Please note that this was done for your account and is not yet a 
> default behavior for all accounts.  I'm still working on that and it 
> may take awhile until we're able to get that change put into 
> production.

**Comment by tam7t** [comment]
FYI these blocks have been lifted as of this afternoon. Going forward it should _just work_ without having to contact DO support.
