### ISSUE TITLE
Unable to import {user}.p12 cert on Android

### ISSUE THREAD

**Issue by Lange** [trailofbits/algo#237]
### OS / Environment
Ubuntu 14.04x64 for running `algo`
Nexus 5X running Android 7.1.1 for setting up the VPN connection

### Ansible version
2.2.0.0

### Version of components from `requirements.txt`
```
dopy 0.3.5
boto 2.45.0
boto3 1.4.4
azure 2.0.0.rc5
apache-libcloud 1.5.0
six 1.5.2
pyopenssl 0.13
jinja2 2.8
```

### Summary of the problem
My `{user}.p12` certificate cannot be imported on my Android phone, as it is grayed out and unselectable in the importer.

### Steps to reproduce the behavior
Below are my answers to the interactive portion of the `algo` script:
```
lange@DropLange:~/algo-master$ ./algo

  What provider would you like to use?
    1. DigitalOcean
    2. Amazon EC2
    3. Google Compute Engine
    4. Microsoft Azure
    5. Install to existing Ubuntu server

Enter the number of your desired provider
: 1

Enter your API token (https://cloud.digitalocean.com/settings/api/tokens):
[pasted values will not be displayed]
:
Name the vpn server:
[algo.local]: setec

  What region should the server be located in?
    1.  Amsterdam        (Datacenter 2)
    2.  Amsterdam        (Datacenter 3)
    3.  Frankfurt
    4.  London
    5.  New York         (Datacenter 1)
    6.  New York         (Datacenter 2)
    7.  New York         (Datacenter 3)
    8.  San Francisco    (Datacenter 1)
    9.  San Francisco    (Datacenter 2)
    10. Singapore
    11. Toronto
    12. Bangalore
Enter the number of your desired region:
[7]: 2

Do you want to enable VPN Always-On when connected to cellular networks?
[y/N]: y

Do you want to enable VPN Always-On when connected to Wi-Fi?
[y/N]: y

Do you want to exclude trusted Wi-Fi networks from using the VPN? (e.g., your home network. Comma-separated value, e.g., HomeNet,OfficeWifi,AlgoWiFi)
:

Do you want to install a local DNS resolver to block ads while surfing?
[y/N]: n

Do you want each user to have their own account for SSH tunneling?
[y/N]: y

Do you want to apply operating system security enhancements on the server?
[y/N]: y

Do you want the VPN to support Windows 10 clients? (requires RSA certificates and key exchange, less secure)
[y/N]: y

Do you want to store the CA key? (required for update-users script, but less secure)
[y/N]: n

PLAY [Configure the server] ****************************************************
```

I then copied my `configs` folder to my Windows 10 PC. From there, I sent my `{user}.p12` certificate to my Android device via a download link (because none of my cables for file transfer are working, naturally). Then, when attempting to import that certificate, it is grayed out and unselectable. The two screenshots below demonstrate this:

![screenshot](https://cloud.githubusercontent.com/assets/873012/22894086/6330e754-f1dd-11e6-87ec-a1c988365e1c.png)

### The way of deployment (cloud or local)
cloud

### Expected behavior
The `{user}.p12` certificate can be imported on Android, as per the instructions in the README.

### Actual behavior
The `{user}.p12` cert is grayed out and unselectable, preventing me from importing it.

### Additional Info
I spoke with @defunctio on Slack about this, and they were unable to reproduce the issue. I have successfully reproduced this issue, so I'm guessing there's something in my process here that is wrong.

**Comment by defunctio** [comment]
=Ahh... wrong place... create a new VPN profile, select IKEv2 Certificate as the VPN type and import the user certificate below that. Leave CA certificate field set to `Select automatically` and the CA cert included in the p12 will be used automatically.

**Comment by Lange** [comment]
Ahh okay. Though in doing this, I discovered that if I go directly to the "Downloads" shortcut in the "Open from" dialog, the .p12 is still grayed out. However, if I instead select "Nexus 5X" and _then_ navigate to the "Downloads" folder on the filesystem, I can select and import the certificate. Very odd. This should probably be documented in the Android instructions.

**Comment by Lange** [comment]
Another few useful things to document would be:

- [Project Fi users must first disable WiFi Assistant](https://wiki.strongswan.org/projects/strongswan/wiki/AndroidVPNClient)
- If another always-on VPN (such as PrivateInternetAccess) is currently active, then StrongSwan may silently fail to initiate a VPN connection. Tapping on a VPN profile in the app will just have no effect whatsoever until the existing always-on VPN is terminated.

**Comment by gunph1ld** [comment]
@Lange Test this commit please - https://github.com/trailofbits/algo/commit/aca036142fb14c037ea457a72881580b757745a9

Some info [here](https://wiki.strongswan.org/projects/strongswan/wiki/AndroidVPNClientProfiles)

**Comment by Lange** [comment]
@gunph1ld Sure thing, I can do that in an hour or two.

**Comment by Lange** [comment]
Got a bit held up, will be fairly late tonight or early tomorrow before I can test.

**Comment by Lange** [comment]
Hm, I don't think I'm understanding how to open these `.sswan` files in Android. I read the StrongSwan wiki page but I can't seem to figure out how I'm supposed to use this file.

**Comment by dguido** [comment]
Did we resolve the issue here?

**Comment by Lange** [comment]
Yes I would say this has been resolved by https://github.com/trailofbits/algo/pull/251, though I never did get to test aca0361, if you want to open a separate issue for tracking testing of that?

**Comment by dguido** [comment]
Great! Yes, I'll open a new ticket for testing Android VPN Profiles.
