### ISSUE TITLE
Provide an option to remove and revoke users' keys

### ISSUE THREAD

**Issue by mrphs** [trailofbits/algo#238]
I keep finding it useful at times to be able to revoke a certain user's key without affecting other users. It would be nice to have `--update-user` option to revoke users keys if their name is removed from config file.

**Comment by lgg** [comment]
@mrphs 
> Algo's own scripts can easily add and remove users from the VPN server.
> Update the users list in your config.cfg
> Run the command: ./algo update-users
> The Algo VPN server now contains only the users listed in the config.cfg file.

It won't affect other users. This script will only add/revoke new/removed users.
