### ISSUE TITLE
Update adblock blacklist

### ISSUE THREAD

**Issue by mrphs** [trailofbits/algo#239]
I love the adblocking feature of algo, however it came to my understanding that sometimes it fails and installing a new instance usually solves the problem. Does algo fetch the blacklist once and only once during the initial setup? would it be possible to update the list frequently? Say everyday?

**Comment by dguido** [comment]
It's already added to cron

https://github.com/trailofbits/algo/blob/master/roles/dns_adblocking/tasks/main.yml#L37-L52
