### ISSUE TITLE
Instructions with screenshots for setting up Android clients

### ISSUE THREAD

**Issue by quinncomendant** [trailofbits/algo#240]
Would someone be willing to make detailed step-by-step instructions with screenshots for setting up an Android phone to connect to Algo?

I've recently setup several Algo servers for friends. They all have Android devices, but I don't have access to one. I've been trying to help them get configured, remotely, by copy-pasting various instructions I find around the web, including the instructions here ("Import the corresponding user.p12 certificate to your device." …). They're all normal humans (not technical people), and respond with "how do I import a certificate?" It also doesn't help that the instructions elsewhere on the web for configuring StrongSwan differ by what values are required, so they've been further confounded by these.

It would be super helpful if someone could post a gist with instructions. We could link to it from the main Algo README.md. Thanks!

**Comment by dguido** [comment]
None of the primary dev team here use Android phones either :-x

**Comment by Lange** [comment]
I have an Android phone and would be happy to contribute step-by-step instructions, if that'd be helpful @dguido. (Also see #237)

**Comment by dguido** [comment]
Please do! Send me a pile of screenshots on Slack and we'll see what we can come up with.

**Comment by Lange** [comment]
I'll work on that today.

**Comment by tobiasbrunner** [comment]
@dguido @Lange With the latest release of the strongSwan Android app the installation of a VPN profile can be simplified by importing it together with the certificates from a single file (see [AndroidVPNClientProfiles](https://wiki.strongswan.org/projects/strongswan/wiki/AndroidVPNClientProfiles)).

**Comment by dguido** [comment]
Thanks for the tip! @Lange wrote up the following instructions so far: https://gist.github.com/Lange/41ad9362beeb5b1717cfd49ac716e8ce

**Comment by gunph1ld** [comment]
@tobiasbrunner Impossible to import password for p12

**Comment by gunph1ld** [comment]
@tobiasbrunner Sorry, it was my mistake. Works as expected. Test anyone, please.

**Comment by dguido** [comment]
Nice, this will make it so much easier for Android users.

**Comment by gunph1ld** [comment]
@Lange Can you send a [PR](https://github.com/trailofbits/algo/pulls) with additional [doc page](https://github.com/trailofbits/algo/tree/master/docs)?

**Comment by Lange** [comment]
I need to work on formatting it so that it's easier to read, but yes, I can do that later today.
