### ISSUE TITLE
 Create new user error and service start failed

### ISSUE THREAD

**Issue by ookangzheng** [trailofbits/algo#243]
I use vultr ubuntu 16.04 
I tried to create new user, I already edit the config.cfg file
but it show error when creating the new user
<img width="1158" alt="screenshot 2017-02-15 01 40 59" src="https://cloud.githubusercontent.com/assets/6301735/22956040/d3cbb370-f31f-11e6-8bbb-162d235a26ef.png">

----
service fail to start

<img width="1166" alt="screenshot 2017-02-15 02 28 24" src="https://cloud.githubusercontent.com/assets/6301735/22957117/83ee7750-f326-11e6-98d6-bbc3ea4e8a12.png">

**Comment by gunph1ld** [comment]
The errors are not related to each other. The first error just a debug message. You need to investigate on the VM why charon is not running.
And, please, file an issue with the [template](https://github.com/trailofbits/algo/blob/master/.github/ISSUE_TEMPLATE.md)
