### ISSUE TITLE
Wrong filenames for files for some usernames with leading zeros in nicknames

### ISSUE THREAD

**Issue by lgg** [trailofbits/algo#246]
### OS / Environment
Ubuntu 16.04, Digital Ocean

### Ansible version
ansible 2.2.0.0

### Version of components from `requirements.txt`
dopy 0.3.5
boto  2.45.0
boto3 1.4.4
azure  2.0.0rc5
apache-libcloud 1.5.0
six 1.10.0
pyopenssl 16.1.0
jinja2 2.8

### Summary of the problem
See screenshots:
![image](https://cloud.githubusercontent.com/assets/12018713/23064305/64513080-f520-11e6-8e75-89ac06fa1e67.png)
![image](https://cloud.githubusercontent.com/assets/12018713/23064314/75e0ce28-f520-11e6-82e3-01cdd8d1ec7b.png)

For some reason some filenames are right: e.g. 009 and 029
and some are wrong: 001 became 1, 004 became 4 and etc

### Steps to reproduce the behavior
* edit config.cfg
* add users like in screenshot above
* create mobileconfigs

### The way of deployment (cloud or local)
* git clone this repo
* ./algo
* provide Digital Ocean api token

### Expected behavior
Mobileconfig files will have the same filenames as their usernames.

### Actual behavior
Some mobileconfigs lose leading zeros in their filenames

**Comment by lgg** [comment]
The same thing is for all files: .mobileconfig, .p12 and others

**Comment by gunph1ld** [comment]
Python interprets numbers that start with a zero as octal and converts it to decimal. Escape it

```
users:
  - '001'
  - '002'
  - '003'
```
