### ISSUE TITLE
After attempting to install to my own VM, could not scp/ssh to retrieve certificates

### ISSUE THREAD

**Issue by zacc** [trailofbits/algo#249]
### OS / Environment
Ubuntu 16.04

### Ansible version

As per commit aca036

### Version of components from `requirements.txt`

As per commit aca036

### Summary of the problem
After installing algo onto my own cloud VM, I could not ssh or scp into it to retrieve the certificates.

### Steps to reproduce the behavior
1. SSH into the virtual machine you wish to install onto
2. Follow the installation steps choosing option 5 at step 1.
3. Choose "localhost" as IP address of the server (step 2)
4. Choose default options, except "Do you want to appliy operating system security enhancements" choose Yes.
5. After the install, attempt to scp into the virtual machine to copy the certificates back to your host computer. The virtual machine will refuse all new scp and ssh connections.

### The way of deployment (cloud or local)
SSH into cloud

### Expected behavior
If this is expected, the documentation should warn of this behaviour.
Perhaps the script could guide the user in copying the certs back to the host machine.

### Actual behavior
The virtual machine will refuse all new scp and ssh connections.

### Full log
(Sorry I deleted the log when I reformatted the VM)

**Comment by dguido** [comment]
We will add a warning to the operating system security enhancements feature, which replaces the sshd_config with one provided by Algo.
