### ISSUE TITLE
Deploy Error Debian

### ISSUE THREAD

**Issue by wilking2k7** [trailofbits/algo#256]
### OS / Environment
Debian X64

### Summary of the problem
PLAY [Configure the server] ****************************************************

TASK [cloud-digitalocean : Delete the existing Algo SSH keys] ******************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "The conditional check 'ssh_keys.changed != true' failed. The error was: error while evaluating conditional (ssh_keys.changed != true): 'dict object' has no attribute 'changed'"}

TASK [cloud-digitalocean : fail] ***********************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Please, ensure that your API token is not read-only."}

### Full log
TASK [setup] *******************************************************************
ok: [localhost]

TASK [Generate the SSH private key] ********************************************
changed: [localhost -> localhost]

TASK [Generate the SSH public key] *********************************************
ok: [localhost -> localhost]

TASK [Change mode for the SSH private key] *************************************
ok: [localhost -> localhost]

TASK [cloud-digitalocean : Set the DigitalOcean Access Token fact] *************
ok: [localhost]

TASK [cloud-digitalocean : Delete the existing Algo SSH keys] ******************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "The conditional check 'ssh_keys.changed != true' failed. The error was: error while evaluating conditional (ssh_keys.changed != true): 'dict object' has no attribute 'changed'"}

TASK [cloud-digitalocean : fail] ***********************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Please, ensure that your API token is not read-only."}

PLAY RECAP *********************************************************************
localhost                  : ok=5    changed=1    unreachable=0    failed=1

[https://www.dropbox.com/s/2hiot70qkmlnznr/Imagen%20de%20Portapapeles.jpg?dl=0](url)

**Comment by gunph1ld** [comment]
@wilking2k7 Your API key is not read-only, right?
Show the output here, please:
`curl -s -X DELETE -H "Content-Type: application/json" -H "Authorization: Bearer YOUR_API_KEY" "https://api.digitalocean.com/v2/account/keys/666000666"`

(Don't forget to change `YOUR_API_KEY`)

**Comment by wilking2k7** [comment]
![api key read write](https://cloud.githubusercontent.com/assets/23059133/23268478/e648f5f6-f9bb-11e6-8168-8e2ea7340861.jpg)
![output](https://cloud.githubusercontent.com/assets/23059133/23268481/e69c251e-f9bb-11e6-9294-2b29a329844e.jpg)

**Comment by wilking2k7** [comment]
![api key read write](https://cloud.githubusercontent.com/assets/23059133/23268574/28c39abc-f9bc-11e6-985d-a66cf990c703.jpg)

**Comment by Lange** [comment]
@wilking2k7 The "Name" of the token is not the part of the token actually used for authentication; it's just a label for you. Once a token has been generated, you can't retrieve its value from the web interface; you're expected to save it somewhere.

For Algo, I make a new token using the "Generate New Token" button, then delete that token when I'm done.

**Comment by wilking2k7** [comment]
![image](https://cloud.githubusercontent.com/assets/23059133/23270257/41c45812-f9c1-11e6-9908-9fc29f3e7c8e.png)

curl -s -X DELETE -H "Content-Type: application/json" -H "Authorization: Bearer 057a4f0760733472b7d919206a5aa542c387946318ab40a67e2fcf87afe92bb6" "https://api.digitalocean.com/v2/account/keys/666000666"

**Comment by Lange** [comment]
Yes, that is the token. Though, of course, now that you've shared that token, you must immediately delete it.

Try running the `algo` script again with a new token.

**Comment by wilking2k7** [comment]
@Lange thanks bro already working perfect this time.

![image](https://cloud.githubusercontent.com/assets/23059133/23270669/98634dc6-f9c2-11e6-8fe9-809012c65996.png)

**Comment by Lange** [comment]
@wilking2k7 Just to be on the safe side, the picture you posted contains passwords. You should delete that deployment of algo and make another one.

**Comment by wilking2k7** [comment]
@Lange deleting in progress.
