### ISSUE TITLE
Droplet ran out of memory during an unattended-upgrade

### ISSUE THREAD

**Issue by Lange** [trailofbits/algo#257]
### OS / Environment
Ubuntu 16.04 x64

### Summary of the problem
512mb DigitalOcean Droplets have the potential to run out of memory during an unattended upgrade.

### Steps to reproduce the behavior
Deploy to a 512mb DigitalOcean Droplet and wait for an unattended upgrade to happen. The issue will likely not occur with every single unattended upgrade.

### The way of deployment (cloud or local)
cloud

### Expected behavior
Unattended upgrades are successful.

### Actual behavior
The unattanded upgrade was killed while in-progress due to the Droplet running out of memory, and it seems to have left this particular deployment of algo in a broken, unrecoverable state.

A possible solution might be to add a swapfile, even if only temporarily. I don't know if `unattended-upgrade` provides any kind of hooks or events, but if it does, it would be possible to temporarily allocate a 1GB swapfile, and then unallocate it when the upgrade has completed. I have to do something similar when running `npm install` on large projects.

**Comment by dguido** [comment]
This is hilarious and bad.

**Comment by dguido** [comment]
Did you deploy with any optional roles when this happened?

**Comment by Lange** [comment]
Hm, this was a while ago so I'm not sure. I believe I used the same options as I did in this issue: https://github.com/trailofbits/algo/issues/237

**Comment by dguido** [comment]
That stinks. It's unbelievable that Ubuntu would just lockup like that. We'll have to do some profiling and see what we can remove to make things take up less memory.

**Comment by Lange** [comment]
If `unattended-upgrade` is anything like `npm install` for large projects, there might be no solution other than to create a swapfile. For instance, I have a particular automated deployment script that has to run `npm install` as part of its setup, and it has to first allocate a 1GB swap, then run `npm install`, then turn that swap back off. There's just no way to successfully run `npm install` for certain projects with only 512mb of RAM.

**Comment by Lange** [comment]
To elaborate a bit more, DigitalOcean explicitly advises against activating a swapfile on droplets: https://www.digitalocean.com/community/tutorials/how-to-add-swap-space-on-ubuntu-16-04

![image](https://cloud.githubusercontent.com/assets/873012/24333386/90c3c8ee-121c-11e7-8b50-bfb019d4d5d9.png)

However, when I spoke with DO support about the use case I outlined in my previous message, they more or less said "sure, go for it! not a problem at all!", so the messaging here is mixed.

**Comment by gunph1ld** [comment]
Fixed by https://github.com/trailofbits/algo/pull/785
