### ISSUE TITLE
Connect To ALGO Server using BitVise SSH Client  - Where i can find the public key?

### ISSUE THREAD

**Issue by wilking2k7** [trailofbits/algo#258]
### Full log
17:39:23.593 Current date: 2017-02-23
17:39:23.593 Started a new SSH2 session.
17:39:23.595 Connecting to SSH2 server XXX.XXX.XXX.XXX.
17:39:23.801 Connection established.
17:39:24.036 Server version: SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.1
17:39:24.036 First key exchange started. Cryptographic provider: Windows CNG (x86) with additions
17:39:24.785 Received host key from the server. Algorithm: ECDSA/nistp256, size: 256 bits, MD5 fingerprint: d8:47:eb:e6:4f:a8:06:7b:0d:e6:58:e2:45:50:5e:95, Bubble-Babble: xucil-medez-dysip-lyted-padyz-zykur-lapum-tytos-hefab-hofet-raxix, SHA-256 fingerprint: bJuqBm4WkR7RmiNLf0Bum+0hWZ80wzPTR1rs8TSisjk.
17:39:24.796 First key exchange completed using ecdh-sha2/nistp521. Session encryption and integrity: aes256-gcm, compression: none.
17:39:25.065 Attempting password authentication.
17:39:25.366 Authentication failed. Remaining authentication methods: 'publickey'.
17:39:56.627 Authentication aborted on user's request.
17:39:57.507 The SSH2 session has been terminated.

![imagen de portapapeles 1](https://cloud.githubusercontent.com/assets/23059133/23282447/30d2ebbc-f9ef-11e6-8d60-0050c001f4d8.jpg)

**Comment by dguido** [comment]
It's in `configs/ip_user.ssh.pem`

**Comment by wilking2k7** [comment]
@dguido I want to connect me and extract the user.p12 for use in Android

**Comment by wilking2k7** [comment]
@dguido I don't know where is the public key to access via ssh and create new users and extract the user.p12 for Android app

**Comment by dguido** [comment]
Please read the documentation. This information is covered in the README. You don't need to extract anything to get Algo working on Android. You only need to provide the StrongSwan app the user's p12 certificate. You can find extended instructions for how to do that in this open Pull Request: https://github.com/trailofbits/algo/pull/251

**Comment by wilking2k7** [comment]
OK thanks but how I can copy the user's.p12 certificate a import to Android app

**Comment by wilking2k7** [comment]
I can't access to my vps Algo Server using ssh because the root user login password is public key and I don't know where is this public key

**Comment by dguido** [comment]
That information is printed out to screen upon success. The part where is says "Congratulations". On the bottom of that it explains that if you want to access the shell, you should use the key in `configs/algo.pem`

**Comment by wilking2k7** [comment]
OK I will try and show you the results

**Comment by wilking2k7** [comment]
@dguido 
![imagen](https://cloud.githubusercontent.com/assets/23059133/23290227/3dedb402-fa1d-11e6-91e9-a63e0e52fc90.png)

i cant acccess via terminal help me please
