### ISSUE TITLE
AZURE - Clarify / document procedure for acquiring AZURE API key.

### ISSUE THREAD

**Issue by ndtob** [trailofbits/algo#261]
There is a major issue with users of Azure being unable to figure out how to acquire the correct API key within the Azure portal. We should describe this process and how to locate the API key in the setup script when we ask the user to input their API key.

**Comment by dguido** [comment]
SEVERITY: CRITICAL

**Comment by dguido** [comment]
Yeah none of this looks straightforward. Silly Microsoft:
https://docs.ansible.com/ansible/guide_azure.html#authenticating-with-azure
