### ISSUE TITLE
IPSEC fails to start on azure

### ISSUE THREAD

**Issue by cheavyio** [trailofbits/algo#264]
When deploying on azure the output says the deployment completed successfully, but I'm unable to connect to the vpn.  Logging into the server I see that ipsec failed to start.

**Comment by gunph1ld** [comment]
Why don't you use the [template](https://github.com/trailofbits/algo/blob/master/.github/ISSUE_TEMPLATE.md)? 
We need more info - logs from the server, your environments, etc..

**Comment by cheavyio** [comment]
Sorry, I'll try to fill out the template when I get more time.  For now when I ssh in this is what I see when I try to start ipsec manually - 
ipsec up ikev2-pubkey
unable to resolve %any, initiate aborted
tried to check-in and delete nonexisting IKE_SA
establishing connection 'ikev2-pubkey' failed

**Comment by gunph1ld** [comment]
You don't need to initiate the connection on the server, just start Strongswan - `systemctl start strongswan`

**Comment by cheavyio** [comment]
After further examination it appears the problem was there is no security group for UDP 500/4500.  Manually adding those two rules to the policy got this working.  Is this something that should be done by algo or manually afterwards?
