### ISSUE TITLE
Ubuntu 16.10 server fails installation due to not finding yakkety release of openvpn

### ISSUE THREAD

**Issue by frustratedpenguin** [trailofbits/algo#266]
> fatal: [x.x.x.x]: FAILED! => {"changed": true, "failed": true, "rc": 100, "stderr": "Warning: Permanently added 'x.x.x.x' (ECDSA) to the list of known hosts.\r\nShared connection to x.x.x.x closed.\r\n", "stdout": "W: The repository 'https://build.openvpn.net/debian/openvpn/stable yakkety Release' does not have a Release file.\r\nE: Failed to fetch https://build.openvpn.net/debian/openvpn/stable/dists/yakkety/main/binary-i386/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none\r\nE: Some index files failed to download. They have been ignored, or old ones used instead.\r\n", "stdout_lines": ["W: The repository 'https://build.openvpn.net/debian/openvpn/stable yakkety Release' does not have a Release file.", "E: Failed to fetch https://build.openvpn.net/debian/openvpn/stable/dists/yakkety/main/binary-i386/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none", "E: Some index files failed to download. They have been ignored, or old ones used instead."]}
https://build.openvpn.net/debian/openvpn/stable/dists/yakkety/main/binary-i386/Packages 

This are the latest ones: https://build.openvpn.net/debian/openvpn/stable/dists/

1. Jessie
2. Precise
3. Trusty
4. Wheezy
5. Xenial

**Comment by gunph1ld** [comment]
It's not a bug. You have to check the repositories you use. We don't provide openvpn support.
