### ISSUE TITLE
Failed to connect to the host via ssh: Warning

### ISSUE THREAD

**Issue by SquirrelCoder** [trailofbits/algo#268]
### OS / Environment
Ubuntu 16.04 x64 (from Vultr)
Linux 1 4.4.0-66-generic #87-Ubuntu SMP Fri Mar 3 15:29:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### Ansible version

ansible 2.2.1.0
  config file = /root/algo/ansible.cfg
  configured module search path = Default w/o overrides

### Version of components from `requirements.txt`

ansible (2.2.1.0)
ecdsa (0.13)
httplib2 (0.9.1)
Jinja2 (2.8)
MarkupSafe (0.23)
paramiko (1.16.0)
pip (9.0.1)
pycrypto (2.6.1)
PyYAML (3.11)
setuptools (20.7.0)
six (1.10.0)
virtualenv (15.0.1)

### Summary of the problem
I want to install Algo on my Ubuntu 16.04 Vultr VPS, but each time I get this error:

fatal: [A.B.C.D]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: Permanently added 'A.B.C.D' (ECDSA) to the list of known hosts.\r\nPermission denied (publickey,password).\r\n", "unreachable": true}

### Steps to reproduce the behavior

run ./algo

### The way of deployment (cloud or local)
local

### Expected behavior

to pass the error

### Actual behavior

apparently the server is unreachable.

### Full log

Enter the number of your desired provider
: 5

Enter the IP address of your server: (or use localhost for local installation)
: A.B.C.D

What user should we use to login on the server? (note: passwordless login required, or ignore if you're deploying to localhost)
[root]: root

Enter the public IP address of your server: (IMPORTANT! This IP is used to verify the certificate)
[A.B.C.D]: 

Was this server deployed by Algo previously?
[y/N]: 

Do you want to enable VPN Always-On when connected to cellular networks?
[y/N]: 

Do you want to enable VPN Always-On when connected to Wi-Fi?
[y/N]: 

Do you want to install a local DNS resolver to block ads while surfing?
[y/N]: 

Do you want each user to have their own account for SSH tunneling?
[y/N]: 

Do you want to apply operating system security enhancements on the server? (warning: replaces your sshd_config)
[y/N]: 

Do you want the VPN to support Windows 10 clients? (requires RSA certificates and key exchange, less secure)
[y/N]: 

Do you want to store the CA key? (required for update-users script, but less secure)
[y/N]: 

PLAY [Configure the server] ****************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Generate the SSH private key] ********************************************
ok: [localhost -> localhost]

TASK [Generate the SSH public key] *********************************************
ok: [localhost -> localhost]

TASK [Change mode for the SSH private key] *************************************
ok: [localhost -> localhost]

TASK [Ensure the dynamic inventory exists] *************************************
ok: [localhost]

TASK [Ensure the local ssh directory is exist] *********************************
skipping: [localhost]

TASK [Copy the algo ssh key to the local ssh directory] ************************
skipping: [localhost]

TASK [Configure the local ssh config] ******************************************
skipping: [localhost]

TASK [local : Add the instance to an inventory group] **************************
changed: [localhost]

TASK [local : Add the instance to an inventory group] **************************
skipping: [localhost]

TASK [local : set_fact] ********************************************************
ok: [localhost]

TASK [local : Ensure the group local exists in the dynamic inventory file] *****
ok: [localhost]

TASK [local : Populate the dynamic inventory] **********************************
ok: [localhost]

PLAY [Configure the server and install required software] **********************

TASK [Install prerequisites] ***************************************************
fatal: [A.B.C.D]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: Permanently added 'A.B.C.D' (ECDSA) to the list of known hosts.\r\nPermission denied (publickey,password).\r\n", "unreachable": true}

PLAY RECAP *********************************************************************
A.B.C.D                : ok=0    changed=0    unreachable=1    failed=0   
localhost                  : ok=9    changed=1    unreachable=0    failed=0   

A.B.C.D == My Server's Public IP. (The one I use to SSH into the VPS.)

**Comment by gunph1ld** [comment]
Are you able SSH to your server? `ssh root@A.B.C.D`

**Comment by SquirrelCoder** [comment]
@gunph1ld okay, so it's official. I am the most stupid human on Earth!
Add this stage, 
```
Enter the IP address of your server: (or use localhost for local installation)
: A.B.C.D
```
instead of typing "localhost" and entering enter, I entered my IP, which is wrong, because it's a lost installation :D.

Thanks for the help, and sorry for my stupid question.
