### ISSUE TITLE
python azure module missing

### ISSUE THREAD

**Issue by cheavyio** [trailofbits/algo#269]
### OS / Environment
macOS/Sierra

### Ansible version
ansible 2.2.0.0

### Version of components from `requirements.txt`
Name: setuptools
Version: 34.3.2
--
Name: ansible
Version: 2.2.0.0
--
Name: dopy
Version: 0.3.5
--
Name: boto
Version: 2.46.1
--
Name: boto3
Version: 1.4.4
--
Name: azure
Version: 2.0.0rc5
--
Name: msrest
Version: 0.4.1
--
Name: apache-libcloud
Version: 1.5.0
--
Name: six
Version: 1.10.0
--
Name: pyOpenSSL
Version: 16.2.0
--
Name: Jinja2
Version: 2.8

### Summary of the problem

ansible fails with the following message -
TASK [cloud-azure : Create a resource group] ***********************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Do you have azure==2.0.0rc5 installed? Try `pip install azure==2.0.0rc5`- No module named msrestazure.azure_exceptions"}

### Steps to reproduce the behavior

./algo

  What provider would you like to use?
    1. DigitalOcean
    2. Amazon EC2
    3. Google Compute Engine
    4. Microsoft Azure
    5. Install to existing Ubuntu server

Enter the number of your desired provider
: 4

Enter your azure secret id (https://github.com/trailofbits/algo/blob/master/docs/AZURE.md)
You can skip this step if you want to use your defaults credentials from ~/.azure/credentials
[...]:

Enter your azure tenant id (https://github.com/trailofbits/algo/blob/master/docs/AZURE.md)
You can skip this step if you want to use your defaults credentials from ~/.azure/credentials
[...]:

Enter your azure client id (application id) (https://github.com/trailofbits/algo/blob/master/docs/AZURE.md)
You can skip this step if you want to use your defaults credentials from ~/.azure/credentials
[...]:

Enter your azure subscription id (https://github.com/trailofbits/algo/blob/master/docs/AZURE.md)
You can skip this step if you want to use your defaults credentials from ~/.azure/credentials
[...]:
Name the vpn server:
[algo]: debug1

  What region should the server be located in?
    1.  South Central US
    2.  Central US
    3.  North Europe
    4.  West Europe
    5.  Southeast Asia
    6.  Japan West
    7.  Japan East
    8.  Australia Southeast
    9.  Australia East
    10. Canada Central
    11. West US 2
    12. West Central US
    13. UK South
    14. UK West
Enter the number of your desired region:
[1]: 1

Do you want to enable VPN Always-On when connected to cellular networks?
[y/N]:

Do you want to enable VPN Always-On when connected to Wi-Fi?
[y/N]:

Do you want to install a local DNS resolver to block ads while surfing?
[y/N]: Y

Do you want each user to have their own account for SSH tunneling?
[y/N]: n

Do you want to apply operating system security enhancements on the server? (warning: replaces your sshd_config)
[y/N]: Y

Do you want the VPN to support Windows 10 clients? (requires RSA certificates and key exchange, less secure)
[y/N]: N

Do you want to store the CA key? (required for update-users script, but less secure)
[y/N]: Y

### The way of deployment (cloud or local)

cloud

### Full log

PLAY [Configure the server] ****************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Generate the SSH private key] ********************************************
ok: [localhost -> localhost]

TASK [Generate the SSH public key] *********************************************
ok: [localhost -> localhost]

TASK [Change mode for the SSH private key] *************************************
ok: [localhost -> localhost]

TASK [Ensure the dynamic inventory exists] *************************************
ok: [localhost]

TASK [cloud-azure : set_fact] **************************************************
ok: [localhost]

TASK [cloud-azure : Create a resource group] ***********************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Do you have azure==2.0.0rc5 installed? Try `pip install azure==2.0.0rc5`- No module named msrestazure.azure_exceptions"}

PLAY RECAP *********************************************************************
localhost                  : ok=6    changed=0    unreachable=0    failed=1

**Comment by gunph1ld** [comment]
Can not reproduce. Did you follow [the steps](https://github.com/trailofbits/algo#deploy-the-algo-server) exactly? Could you ensure that you are in virtualenv?

**Comment by dguido** [comment]
@cheavyio Any update on this issue?

**Comment by jaytay79** [comment]
I have just come across this exact same issue... @gunph1ld should I open a new issue or can this one be used?

**Comment by jaytay79** [comment]
Thanks @dguido! OK, I have done some searching and found [this](https://github.com/Azure/azure-sdk-for-python/issues/644) which looks to be the root cause here....

**Comment by gunph1ld** [comment]
@jaytay79  So, Is the `pip install msrestazure` workaround?

**Comment by jaytay79** [comment]
@gunph1ld Yes, that seems to have it working OK.
