### ISSUE TITLE
iOS config file generator improvement

### ISSUE THREAD

**Issue by pwnsdx** [trailofbits/algo#270]
Hello,

I wanted to give you some ideas to improve the current iOS config file generator: 

- ChildSecurityAssociationParameters/IKESecurityAssociationParameters -> LifeTimeInMinutes to 20 instead of 1440
- DisableRedirect on 1 instead of 0 (https://developer.apple.com/library/content/featuredarticles/iPhoneConfigurationProfileRef/Introduction/Introduction.html)

Regarding the file itself, I think that instead of using:

```
              <key>OnDemandEnabled</key>
                <integer>1</integer>
              <key>OnDemandRules</key>
              <array>
                  <dict>
                    <key>Action</key>
                      <string>Connect</string>
                      <key>InterfaceTypeMatch</key>
                      <string>WiFi</string>
                  </dict>
                  <dict>
                    <key>Action</key>
                      <string>Connect</string>
                      <key>InterfaceTypeMatch</key>
                      <string>Cellular</string>
                  </dict>
                </array>
```

You could just use:

```
                <key>OnDemandEnabled</key>
                <integer>1</integer>
                <key>OnDemandRules</key>
                <array>
                    <dict>
                        <key>Action</key>
                        <string>Connect</string>
                    </dict>
                </array>
```

And the following text is misleading:

"Do you want to enable VPN Always-On when connected to cellular networks? Do you want to enable VPN Always-On when connected to Wi-Fi?"

What you're doing is in fact "On Demand" rules, not Always-On, Always-On mode is different and will completely block the network traffic if there is no VPN (it also block the local network etc).

Regards,
Sabri

**Comment by dguido** [comment]
Thanks @pwnsdx! Much appreciated. We'll take a look at this and incorporate whatever we can.

**Comment by gunph1ld** [comment]
> Regarding the file itself, I think that instead of using:

It will add more `if then` statements in the mobileconfig template. Let's keep it as is.
