### ISSUE TITLE
Offer the option to use a second IP as exit

### ISSUE THREAD

**Issue by pwnsdx** [trailofbits/algo#273]
### Summary of the problem

Because the exit IP is the same, it exposes the [IKEv2, SSH ports and ICMP](https://github.com/trailofbits/algo/blob/148686e8fdb0bb12e1f1d88475c15f1f1cc84771/roles/vpn/templates/rules.v4.j2#L21-L28) to anyone, making the fingerprinting of your server as a VPN trivial. It also allows attacks of many kind like bruteforce, DoS etc. A state-sponsored attacker can also correlate the traffic in a much easier way.

### Possible solution

Asking the user if he wants to use a second IP as exit. Most cloud providers have an API to request (paid) additional IPs.

For IPv4 I had to modify this line: https://github.com/trailofbits/algo/blob/148686e8fdb0bb12e1f1d88475c15f1f1cc84771/roles/vpn/templates/rules.v4.j2#L8 to:

```
-A POSTROUTING -s 10.19.48.0/24 -m policy --pol none --dir out -j SNAT --to [public ip]
```

and adding one more interface in `/etc/network/interfaces`:

```
auto lo:1
iface lo:1 inet static
    address [public ip]/32
```

**Comment by gunph1ld** [comment]
Not sure that we need it. This makes additional headache for non advanced users.
