### ISSUE TITLE
Install on Docker 16.04 64bit 

### ISSUE THREAD

**Issue by ookangzheng** [trailofbits/algo#276]
### OS / Environment
Vultr Ubuntu 16.04, Docker latest version
error log
<img width="886" alt="screen shot 2017-03-23 at 23 18 06" src="https://cloud.githubusercontent.com/assets/6301735/24272790/2f6fbb6a-101f-11e7-93b1-61262e79b332.png">
I also tried install on normal vps, also same prb

**Comment by dguido** [comment]
Thanks but we're not interested in installing to docker at this time. We may consider this in the future, but for now we chose Ansible to make running on bare hardware as easy as possible.
