### ISSUE TITLE
Documentation & release signature

### ISSUE THREAD

**Issue by daviddahl** [trailofbits/algo#279]
### OS / Environment

Linux, Any

### Summary of the problem

The docs tell me to download a zip file from https://github.com/trailofbits/algo/archive/master.zip - this is a red flag as you have not provided a formal release and you have not provided any kind of signature for the zip. When I went to curl the zip file, curl complained about be redirected. While this is probably not a real problem, it looks bad to security conscious folks.

**Comment by dguido** [comment]
Thanks for submitting this issue. I understand your concern, however, you should know that there are several mitigating factors and I consider the current method more than safe enough given the risks.

Github uses [certificate pinning, strict transport security, and a modern TLS protocol and cipher suite](https://www.ssllabs.com/ssltest/analyze.html?d=github.com) for all TLS connections to its website. The risk that any download would be intercepted and modified is minimal to non-existent.

Every code change to Algo is made over git and the [commit log is public](https://github.com/trailofbits/algo/commits/master). Algo is composed of plaintext scripts and the amount of code run is relatively low, especially if you don't choose optional features. The security critical bits (like [key generation](https://github.com/trailofbits/algo/blob/master/roles/vpn/tasks/openssl.yml)) are actually quite small. We don't accept PRs without review from an admin.

The main risk is that Github's own servers could be compromised and serving bad copies of Algo. If an attacker were able to compromise Github.com they could cause havoc on a much larger scale than personally trojaning your individual download of Algo to, for example, generate weak keys in hopes that some time later they could sniff your traffic and decrypt it. It's just not a likely scenario.

That said, we are planning to make an [official release](https://github.com/trailofbits/algo/milestones) in the future and I planned to use [Github's built-in support for PGP-signed releases](https://github.com/blog/2144-gpg-signature-verification) when we do.
