### ISSUE TITLE
User friendly provider UI 

### ISSUE THREAD

**Issue by defunctio** [trailofbits/algo#28]
A friendly wrapper around deploy.yml for deploying to different providers (EC2, DigitalOcean, etc) should be created.

Currently provider selection is done via passing a variable at the command line. 
Ex:  
ansible-playbook deploy.yml -e "provider=ec2"

While I fully support implementing all options configurable at the command line through variables for scripting purposes, we need a UI for this.

**Comment by dguido** [comment]
How have you seen other Ansible-based projects implement such a UI?

All I've seen is the Tinfoil website: https://www.tinfoilsecurity.com/vpn/new

**Comment by defunctio** [comment]
Nope I haven't, I was referring to a simple ansible playbook w/ prompt to act as a wrapper around provider selection mostly since I was too lazy to do it. 

However; as far as an actual GUI goes... If someone wanted to, maybe a QML GUI w/ python using ansible API? To act as a wrapper for configuring settings, saving and loading profiles etc.

http://docs.ansible.com/ansible/developing_api.html

Doesn't have to be QT since we may not want to add that as a requirement but something that is crossplatform / portable.

**Comment by dguido** [comment]
Ohhhh, yeah I think we can build a wrapper around cloud service selection. That's easy.

**Comment by gunph1ld** [comment]
Will done after #33

**Comment by gunph1ld** [comment]
My conclusion - there are now way to make a good UI without `bash`

**Comment by dguido** [comment]
Ok, I understand. Let's build a bash wrapper for selecting a cloud provider.
