### ISSUE TITLE
Azure region list is missing West US

### ISSUE THREAD

**Issue by joshmeisels** [trailofbits/algo#286]
### OS / Environment
Windows 10

### Ansible version
2.2.0.0

### Summary of the problem
Deployment for Azure is missing `West US`. Only `West US 2` is available, but `West US 2` does not support the type of VM that Algo tries to create in Azure. 

I suggest `West US 2` either be removed, annotated to indicate it isn't currently supported, or have it create a different size of VM for that region. The ideal case would be that if a certain size VM isn't available in whatever region you select, it chooses a different size that is available.

### Steps to reproduce the behavior
Run ./algo
Choose `4` to deploy to Azure.
Enter all the good stuff it asks for.

> What region should the server be located in?
>     1.  South Central US
>     2.  Central US
>     3.  North Europe
>     4.  West Europe
>     5.  Southeast Asia
>     6.  Japan West
>     7.  Japan East
>     8.  Australia Southeast
>     9.  Australia East
>     10. Canada Central
>     11. West US 2
>     12. West Central US
>     13. UK South
>     14. UK West

### The way of deployment (cloud or local)
Cloud (Azure)

### Expected behavior
Can choose `West US` as the region.
If you choose `West US 2` it should still work.

### Actual behavior
`West US` is not in the list
`West US 2` results in failure since it doesn't support VM size D1.

**Comment by joshmeisels** [comment]
I'm going to take a stab at making this change. It looks like there are a bunch of new Azure regions, so I'll try to update the list.

**Comment by intelinc** [comment]
Note also that the `Standard_D1` machine type looks to be getting phased-out in favor of the `Standard_D1_v2` type. I changed my machine type to the v2 version in main.yml and successfully deployed to Algo using `West US 2`. Aside from seeming to have better availability across regions, it is also actually slightly cheaper than the older D1 vm tier. Might be worthwhile to look at revising Algo's default Azure vm_size.

**Comment by dguido** [comment]
We resolved this in #332. We ended up going with the smaller VM size (A0) out of cost concerns.
