### ISSUE TITLE
Autopopulate list of zones/regions using a more authoritative list.

### ISSUE THREAD

**Issue by tariqajyusuf** [trailofbits/algo#291]
Some of the cloud providers list the available zones via an API. Using these can save the trouble of updating whenever new zones open up (See #286). We already get the API keys required to make this happen, we just need to change the order and grep the responses accordingly:

* **Google Cloud**: https://cloud.google.com/compute/docs/reference/latest/zones/list
* **DigitalOcean**: https://developers.digitalocean.com/documentation/v2/#list-all-regions
* **AWS EC2**: https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeRegions.html
* **Azure**: https://docs.microsoft.com/en-us/rest/api/apimanagement/regions

**Comment by jackivanov** [comment]
https://github.com/trailofbits/algo/issues/941
