### ISSUE TITLE
D1 VM size not available in some Azure regions

### ISSUE THREAD

**Issue by jaytay79** [trailofbits/algo#293]
Firstly, sorry but I didn't see much point in using the template for a relatively simple error!

I tried to set-up algo on a "UK South" Azure VM and eventually received:

`TASK [cloud-azure : Create an instance] ****************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Parameter error: vm_size Standard_D1 is not valid for your subscription and location."}`

It seems that neither a number of locations cannot accept a D1 VM looking at https://azure.microsoft.com/en-gb/pricing/details/virtual-machines/linux/

**Comment by joshmeisels** [comment]
I hit the same issue when using `US West 2`. I'm working on resolving this as part of #286, but I'm learning as I go. 

I am experimenting with a way to let the user choose their VM size - see my first crack at this in https://github.com/joshmeisels/algo/commit/a5dcb8d2869aeed72810042048ebcfaa14dd79b3. A more robust solution would be to fallback or prompt if the chosen size is not available. 

Also, if everything runs fine on an A0 size machine, that's way cheaper. I'm going to try it and see how it works. A0 is available in every region.

**Comment by dguido** [comment]
FYI I'm going to close this issue in favor of #286
