### ISSUE TITLE
Dynamic inventory for user management

### ISSUE THREAD

**Issue by defunctio** [trailofbits/algo#30]
The EC2 playbook is using the default users-management inventory.

While this is fine for now, in the future support for dynamic inventories with the user management playbook should be integrated. Not just for EC2 but for all providers.

**Comment by gunph1ld** [comment]
- [ ] azure
- [ ] digitalocean
- [ ] ec2
- [ ] gce
- [ ] local

**Comment by gunph1ld** [comment]
There is no way to count hosts dynamically for local and gce deployments, but there is another gce dynamic inventory [script](http://docs.ansible.com/ansible/guide_gce.html#gce-dynamic-inventory) though
