### ISSUE TITLE
Fedora client connects to server but no traffic passes through

### ISSUE THREAD

**Issue by molecularswords** [trailofbits/algo#300]
### OS / Environment
Fedora

### Ansible version

2.2.0.0

### Version of components from `requirements.txt`

setuptools 34.3.3
dopy 0.3.5
boto 2.46.1
boto3 1.4.4
azure 2.0.0rc5
msrest 0.4.1
apache-libcloud 1.5.0
six 1.10.0
pyopenssl 16.2.0
jinja2 2.8

### Summary of the problem
After deploying a client setup using the deploy_client.yml I can successfully make the connection to the VPN server (on a DO droplet) using the command "sudo strongswan up <my connection name here>" but no traffic goes through the server. The server is working fine as a VPN as assessed from my Android client, but nothing will resolve using the Fedora client.

### Steps to reproduce the behavior
1) Deploy the client with parameters client_ip=localhost, vpn_user=<the username I chose during setup>, server_ip=<the server's ip>, server_ssh_user=root.
2) Make the connection with the command "sudo strongswan up <my connection name here>" and receive confirmation that the connection was established.
3) Ping any domain, go to any website in a browser, or open a program that requires a working internet connection and nothing happens due to a lack of traffic getting through.

### The way of deployment (cloud or local)
cloud (DO droplet)

### Expected behavior
Given that the connection is successfully established I expect the traffic to properly route through the server.

### Actual behavior
The traffic does not properly route through the server.

**Comment by molecularswords** [comment]
I should mention that I tested the MTU/MSS fix that some people are experiencing, and it did not solve the problem.

**Comment by dguido** [comment]
There are more precise instructions for strongSwan clients on the readme. You should try them. What you're doing is generally unsupported by our project.

**Comment by molecularswords** [comment]
I have followed the instructions from the beginning without success on Fedora but with success on an Ubuntu VM. The only difference between what one has to do on Fedora and what the readme says is to use the "strongswan" command instead of the "ipsec" command because the former replaces the latter on Fedora. I also had to alter the location of the config files and certs since on Fedora the ipsec.d directory is under /etc/strongswan/ and not just /etc/. It works fine in an Ubuntu VM, and all the commands for strongswan and ipsec are the same. I'm not sure why what I'm doing is not supported since what I'm doing is essentially no different than the readme instructions. It seems to just be a difference between Fedora and Ubuntu that I have not yet discovered how to fix. If anyone has gotten it working on a Fedora client please give us some insight.
