### ISSUE TITLE
Windows client config instructions: where is the .ps1?

### ISSUE THREAD

**Issue by hillbrad** [trailofbits/algo#306]
### OS / Environment
Windows

### Summary of the problem
Instructions at https://github.com/trailofbits/algo#windows are unclear.  After installing on localhost in a Amazon Lightsail instance, I don't find a .ps1 anywhere in ./configs

There is no user_windows.ps1 file created anywhere in the algo-master directory tree and it's not referenced anywhere in the repo outside the readme.  All .ps1 files seem to be only in the ansible directory, none for user setup.

**Comment by dguido** [comment]
Weird! If you chose the Windows build option, the ps1 files should be in the configs directory. "User" will be replaced with the usernames you added to config.cfg. I'll run a deploy later and check these are created.

**Comment by hillbrad** [comment]
Maybe I missed a config option - was doing this late at night, I don't remember what options I picked and don't have any Windows boxes. I just looked today to try to let a friend use my setup and couldn't find the script.  

Does it only generate the Windows client script if you set up the server on Windows?  My server is Ubuntu on Lightsail; I assumed I could still connect a Windows client to that.

**Comment by hillbrad** [comment]
Can I generate it without re-installing?

**Comment by dguido** [comment]
The server does not support Windows unless you specifically ask it to, due to lower security standards that it supports. I would recommend just spinning down the existing one and running the installer again.

**Comment by hillbrad** [comment]
Aha, my bad.  Thanks.

**Comment by dguido** [comment]
No problem! Let me know if it works on the second go around.

**Comment by waltirus** [comment]
Hello guys! I have to join with the same problem. I cannot any more rely on WireGuard on my client Windows machine as it looks like its protocol/traffic has been successfully blocked/jammed by he government. So, I'd like to try Algo in work with the old method of manual setup of Windows client machine using the Powershell and files like p12 and ps1. In the config folder I do not see files of ps1 , only p12 is present there. is it possible to manually setup Windows client using p12 key only? If not, where can I get that ps1 file now? Can I ask to send it to me specifically then?  This seems the last chance for my Algo (I got used to it) as if I cannot try to setup my client without WireGuard protocol I would have to apply to other VPN solutions or services. Please, advise! Thank you!
