### ISSUE TITLE
LAN documentation

### ISSUE THREAD

**Issue by dmwyatt** [trailofbits/algo#308]
I thought it'd be a good idea to have an issue to track progress on some documentation for configuring a LAN (I'm thinking SOHO LANs here) for passing internet traffic through the algo VPN.

Of course, every router is different, but I think at the very least some sort of general overview would be very helpful.

A lot of the existing documentation focuses on roadwarrior type of scenarios.

**Comment by booleanbetrayal** [comment]
Loving Algo, but would also like to do a LAN passthrough. I'm having a hard time finding a router that supports IKEv2 client mode though. Would love to hear any recommendations.

**Comment by dguido** [comment]
There's already two tickets open for various routers, let's close this one and focus on getting one of those working. As long as your device supports IKEv2, ECC certificate auth, and the IKE and ESP cipher suites specified in [ipsec.conf](https://github.com/trailofbits/algo/blob/master/roles/vpn/templates/ipsec.conf.j2) then you should be fine. There's nothing magic about setting up a router with an Algo server.

**Comment by booleanbetrayal** [comment]
Thanks @dguido - It might be helpful to list routers that support IKEv2 client mode somewhere. I've only found PPTP / OpenVPN support in popular routers so far. Not sure what custom firmwares easily offer that support, etc.
