### ISSUE TITLE
No action detected in task...

### ISSUE THREAD

**Issue by lyoungblood** [trailofbits/algo#309]
### OS / Environment

Mac OS 10.12.4

### Ansible version

ansible 2.1.0.0
  config file = /Users/lukey/algo-master/ansible.cfg
  configured module search path = Default w/o overrides

### Version of components from `requirements.txt`
Name: boto3
Version: 1.4.4
Summary: The AWS SDK for Python
Home-page: https://github.com/boto/boto3
Author: Amazon Web Services
Author-email: UNKNOWN
License: Apache License 2.0
Location: /Users/lukey/algo-master/env/lib/python2.7/site-packages
Requires: botocore, jmespath, s3transfer

Name: apache-libcloud
Version: 1.5.0
Summary: A standard Python library that abstracts away differences among multiple cloud provider APIs. For more information and documentation, please see http://libcloud.apache.org
Home-page: http://libcloud.apache.org/
Author: Apache Software Foundation
Author-email: dev@libcloud.apache.org
License: Apache License (2.0)
Location: /Users/lukey/algo-master/env/lib/python2.7/site-packages
Requires: 

Name: six
Version: 1.10.0
Summary: Python 2 and 3 compatibility utilities
Home-page: http://pypi.python.org/pypi/six/
Author: Benjamin Peterson
Author-email: benjamin@python.org
License: MIT
Location: /usr/local/lib/python2.7/site-packages
Requires: 

Name: pyOpenSSL
Version: 16.0.0
Summary: Python wrapper module around the OpenSSL library
Home-page: https://pyopenssl.readthedocs.org/
Author: Hynek Schlawack
Author-email: hs@ox.cx
License: Apache License, Version 2.0
Location: /usr/local/lib/python2.7/site-packages
Requires: six, cryptography

### Summary of the problem

When attempting to provision an algo server in AWS EC2, get the following errors: (see below)

### Steps to reproduce the behavior

(env) f45c89b04cf3:algo-master lukey$ ./algo

  What provider would you like to use?
    1. DigitalOcean
    2. Amazon EC2
    3. Google Compute Engine
    4. Microsoft Azure
    5. Install to existing Ubuntu server

Enter the number of your desired provider
: 2

Enter your aws_access_key (http://docs.aws.amazon.com/general/latest/gr/managing-aws-access-keys.html)
Note: Make sure to use either your root key (recommended) or an IAM user with an acceptable policy attached
[pasted values will not be displayed]
[AKIA...]: 
Enter your aws_secret_key (http://docs.aws.amazon.com/general/latest/gr/managing-aws-access-keys.html)
Note: Make sure to use either your root key (recommended) or an IAM user with an acceptable policy attached
[pasted values will not be displayed]
[ABCD...]: 
Name the vpn server:
[algo]: 

  What region should the server be located in?
    1.   us-east-1           US East (N. Virginia)
    2.   us-east-2           US East (Ohio)
    3.   us-west-1           US West (N. California)
    4.   us-west-2           US West (Oregon)
    5.   ap-south-1          Asia Pacific (Mumbai)
    6.   ap-northeast-2      Asia Pacific (Seoul)
    7.   ap-southeast-1      Asia Pacific (Singapore)
    8.   ap-southeast-2      Asia Pacific (Sydney)
    9.   ap-northeast-1      Asia Pacific (Tokyo)
    10.  eu-central-1        EU (Frankfurt)
    11.  eu-west-1           EU (Ireland)
    12.  eu-west-2           EU (London)
    13.  sa-east-1           South America (São Paulo)
    14.  ca-central-1        Canada (Central)
Enter the number of your desired region:
[1]: 1

Do you want to enable VPN On Demand when connected to cellular networks?
[y/N]: y

Do you want to enable VPN On Demand when connected to Wi-Fi?
[y/N]: y

Do you want to exclude trusted Wi-Fi networks from using the VPN? (e.g., your home network. Comma-separated value, e.g., HomeNet,OfficeWifi,AlgoWiFi)
: 

Do you want to install a local DNS resolver to block ads while surfing?
[y/N]: 

Do you want each user to have their own account for SSH tunneling?
[y/N]: 

Do you want to apply operating system security enhancements on the server? (warning: replaces your sshd_config)
[y/N]: 

Do you want the VPN to support Windows 10 clients? (requires RSA certificates and key exchange, less secure)
[y/N]: 

Do you want to store the CA key? (required for update-users script, but less secure)
[y/N]: 
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/Users/lukey/algo-master/roles/cloud-digitalocean/tasks/main.yml': line 71, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: Tag the groplet
  ^ here

The error appears to have been in '/Users/lukey/algo-master/roles/cloud-digitalocean/tasks/main.yml': line 71, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: Tag the groplet
  ^ here

### The way of deployment (cloud or local)

local (from my Mac laptop to cloud)

### Expected behavior

Algo deploys a VPN server on EC2

### Actual behavior

Ansible error as above

**Comment by dguido** [comment]
Hmmm I wonder if it's related to @jmhale's PR from a few days ago? https://github.com/trailofbits/algo/pull/282

**Comment by lyoungblood** [comment]
Might be, although the error pops up in the digital ocean role, rather than the ec2 role.  I'm really looking forward to getting my algo VPN setup - does anyone know of a commit that works effectively with EC2?

This looks like an awesome project, but I think it might benefit from a release/stable branch and not just having everyone run master.  That helps to avoid regressions and unexpected issues for first time users like me.

**Comment by jmhale** [comment]
That's odd. I just checked master out on a fresh machine, running macOS 10.12.3 and Ansible 2.2.1.0, and I'm not getting the error.

FWIW, my change was pretty simple, so it would be easy to just revert that and test against that. I would, but I can't reproduce in the first place.

@lyoungblood Your local master is fully up to date, right?

I also ran ansible-lint against both the EC2 and DigitalOcean roles, and didn't come up with anything.

**Comment by jmhale** [comment]
Also, +1 on the release/stable branch idea.

**Comment by lyoungblood** [comment]
@jmhale yes, just checked out a fresh copy from master and ran through the setup steps to be sure.  It's possible my python environment is borked, so I will attempt to reproduce from an Ubuntu EC2 instance to see if that helps.  I'll report back in a few hours.

**Comment by dguido** [comment]
Are you using python3 by chance?

**Comment by lyoungblood** [comment]
Ran this on Ubuntu 16.04 with no issues - must be a problem with my Mac workstation - sorry to waste any time.

@dguido I am using Python 2.7.13.  My guess is that my homebrew installation is borked and needs to be fixed in some way.

**Comment by dguido** [comment]
That could be it. We tried to avoid a lot of these issues with virtualenv but it's not a foolproof solution.
