### ISSUE TITLE
Change Hostname?

### ISSUE THREAD

**Issue by astanciu** [trailofbits/algo#312]
Is it possible to change the hostname after installation? I didn't realize the value entered for:
```
Name the vpn server:
[algo.local]:
```
shows up on a reverse dns query.

**Comment by dguido** [comment]
It's just an Ubuntu server, so there should be instructions here somewhere: https://help.ubuntu.com/lts/serverguide/

You can also just redeploy

**Comment by madflow** [comment]
@astanciu For me changing the hostname in /etc/hostname and /etc/hostnames worked.
