### ISSUE TITLE
cannot launch instance on South America (EC2)

### ISSUE THREAD

**Issue by luizkowalski** [trailofbits/algo#314]
### OS / Environment
MacOS 10.12.4

### Ansible version

ansible 2.2.0.0

### Version of components from `requirements.txt`

Not sure how to do it...

### Summary of the problem
I see this error message when trying to launch an instance on sa-east-1
```
TASK [cloud-ec2 : Launch instance] *********************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Instance creation failed => Unsupported: Your requested instance type (t2.micro) is not supported in your requested Availability Zone (sa-east-1b). Please retry your request by not specifying an Availability Zone or choosing sa-east-1a, sa-east-1c."}

PLAY RECAP *********************************************************************
localhost                  : ok=11   changed=0    unreachable=0    failed=1
```

### Steps to reproduce the behavior
Just try to launch an instance on EC2 (Sao Paulo)

### The way of deployment (cloud or local)
Cloud

**Comment by dguido** [comment]
Can you submit a PR to remove that region? I want add a comment in the source code that it doesn't support the size instance we use.

**Comment by luizkowalski** [comment]
actually, when I opened the issue was because I would still like to use it on South America region...I thought that changing the AZ to one listed in the logs (`or choosing sa-east-1a, sa-east-1c`) would be fine. Am I wrong?
