### ISSUE TITLE
Cannot visit many sites even after configuring MTU

### ISSUE THREAD

**Issue by jasonhr13** [trailofbits/algo#317]
Ive installed and ran Algo to configure a VPN on my AWS account. Everything goes fine but most sites are unreachable. Ive checked my MTU value using `ping` and found a value that works for ping but when entering it into my wifi network advanced settins on my mac i still cant reach most sites. Do I need to set this MTU value on the router directly?

### OS / Environment
MacOS Sierra

**Comment by dguido** [comment]
Dupe of #216
