### ISSUE TITLE
Documentation, README.md out of date and lacks some details

### ISSUE THREAD

**Issue by eanxgeek** [trailofbits/algo#318]
### OS / Environment
Linux Mint 18.1

### Ansible version
Not applicable 

### Version of components from `requirements.txt`
Not applicable

### Summary of the problem
Linux documentation appears to be very obscure here, especially for the relatively new.  I'm a strong Linux user; however, I have rarely played in the space of VPN and I have never used StrongSwan; however, I can say that the documentation seems to lack some specifics and in some cases is wrong.

1. copy the included ... to your client device.
First, the source is not mentioned and should be, configs/<ip_addr>.  Second, destination is not mentioned, is it /etc/. or /etc/strongswan.d/. or some other combination that includes cert directories?

2. There's no mention on how to start strongswan, however, when I run ipsec start I get an error.
> /etc/strongswan.d/ipsec_<user>.conf:1: syntax error, unexpected NAME, expecting NEWLINE or '{' or '=' [ikev2-<ip_addr>]
> invalid config file '/etc/strongswan.conf'
> Starting strongSwan 5.3.5 IPsec [starter]...
> charon is already running (/var/run/charon.pid exists) -- skipping daemon start
> starter is already running (/var/run/starter.charon.pid exists) -- no fork done

3. There's no mention of what to do with the file <user>.sswan that exists in configs/<ip_addr>

4. The docs refer to user_ipsec.conf, user_ipsec.secrets, etc...; however, the filenames are actually ipsec_user.conf, ipsec_user.secrets, ...

**Comment by dguido** [comment]
Thanks for the note! We know that the guidance for Linux users is not very complete right now, however, they are not the intended audience of this project. If you admin your own Linux servers, you should know what to do when provided with a template configuration file. We're also not intended to duplicate the documentation available at the strongSwan website, which appears to be what you are looking for.

I would be very happy to accept pull requests that address these issues.
