### ISSUE TITLE
Installed Perfectly - Now What?

### ISSUE THREAD

**Issue by fuzzygroup** [trailofbits/algo#320]
Hi, 

Everything installed perfectly end to end so thank you very, very much -- I also tried Streisand which was a disaster and never installed at all.

### Summary of the problem
I'm using OSX for my client side OS and an ASUS RT-N66U router.  I can either secure all my client side devices (which is fine) or use the router's VPN client support.  Unfortunately I can't seem to figure out either approach. 

* I was able to import the generated certificates into OSX and create an IKEv2 VPN but it requires two fields -- server address and remote ID.  Server Address is clear - that should be the ip address of the AWS server I used.  What exactly remote ID should be set to though is not clear - should this also be set to the server address?  No matter what I set it to, I can never connect .  I've also tried using the ubuntu username and both generated passwords but nothing.  Thoughts?

* My router supports PPTP, L2TP and OpenVPN protocols so I'm guessing that this won't work at all but I thought I'd ask.

Overall I think that Algo is a fantastic product but the "You're installed now do THIS" is really missing -- VPNs are notoriously complex / finicky and I doubt I'm alone in my perspective that a bit more hand holding is needed.

### Steps to reproduce the behavior

1.  Install it.
2.  Be utterly confused at the end as to what to do.

### The way of deployment (cloud or local)

local onto AWS cloud

**Comment by joshwatson** [comment]
If you're on OSX, just install the .mobileconfig file that is generated, not the certificates. It will automatically set up the VPN. Then you just go into Network settings in System Preferences and connect to the VPN.

**Comment by mankins** [comment]
And to clarify: "install the .mobileconfig" means either clicking on it in Finder, or in Terminal typing "open path/to/.mobileconfig".
