### ISSUE TITLE
Algo fails while waiting for SSH on GCP

### ISSUE THREAD

**Issue by caseylang** [trailofbits/algo#324]
### OS / Environment
OS X El Capitan 10.11.6

### Ansible version
ansible 2.2.1.0

### Version of components from `requirements.txt`
setuptools - 32.1.0
dopy - 0.3.5
boto - 2.46.1
boto3 - 1.4.4
msrest - 0.4.1
apache-libcloud - 0.20.1
six -1.10.0
pyOpenSSL - 16.2.0

### Summary of the problem
Ansible times out while waiting for SSH to become available when attempting to install Algo on GCE

### Steps to reproduce the behavior
Run Algo on GCE

### The way of deployment (cloud or local)
Cloud - GCE

### Expected behavior
Ansible is able to connect to SSH and continue the install process

### Actual behavior
Ansible times out while waiting for SSH

### Full log
# ./algo

  What provider would you like to use?
    1. DigitalOcean
    2. Amazon EC2
    3. Google Compute Engine
    4. Microsoft Azure
    5. Install to existing Ubuntu server

Enter the number of your desired provider
: 3

Enter the local path to your credentials JSON file (https://support.google.com/cloud/answer/6158849?hl=en&ref_topic=6262490#serviceaccounts):
: /Users/snip/.gce/algo-test-service-account.json

Name the vpn server:
[algo]:

  What zone should the server be located in?
    1. Western US       (Oregon A)
    2. Western US       (Oregon B)
    3. Central US       (Iowa A)
    4. Central US       (Iowa B)
    5. Central US       (Iowa C)
    6. Central US       (Iowa F)
    7. Eastern US       (South Carolina B)
    8. Eastern US       (South Carolina C)
    9. Eastern US       (South Carolina D)
    10. Western Europe  (Belgium B)
    11. Western Europe  (Belgium C)
    12. Western Europe  (Belgium D)
    13. East Asia       (Taiwan A)
    14. East Asia       (Taiwan B)
    15. East Asia       (Taiwan C)
Please choose the number of your zone. Press enter for default (#3) zone.
[3]: 3

Do you want to enable VPN On Demand when connected to cellular networks?
[y/N]:

Do you want to enable VPN On Demand when connected to Wi-Fi?
[y/N]:

Do you want to install a local DNS resolver to block ads while surfing?
[y/N]:

Do you want each user to have their own account for SSH tunneling?
[y/N]:

Do you want to apply operating system security enhancements on the server? (warning: replaces your sshd_config)
[y/N]:

Do you want the VPN to support Windows 10 clients? (requires RSA certificates and key exchange, less secure)
[y/N]:

Do you want to store the CA key? (required for update-users script, but less secure)
[y/N]:

PLAY [Configure the server] ****************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Generate the SSH private key] ********************************************
ok: [localhost -> localhost]

TASK [Generate the SSH public key] *********************************************
ok: [localhost -> localhost]

TASK [Change mode for the SSH private key] *************************************
ok: [localhost -> localhost]

TASK [Ensure the dynamic inventory exists] *************************************
ok: [localhost]

TASK [cloud-gce : set_fact] ****************************************************
ok: [localhost]

TASK [cloud-gce : set_fact] ****************************************************
ok: [localhost]

TASK [cloud-gce : set_fact] ****************************************************
ok: [localhost]

TASK [cloud-gce : Creating a new instance...] **********************************
changed: [localhost]

TASK [cloud-gce : Add the instance to an inventory group] **********************
changed: [localhost]

TASK [cloud-gce : Firewall configured] *****************************************
ok: [localhost -> localhost]

TASK [cloud-gce : set_fact] ****************************************************
ok: [localhost]

TASK [cloud-gce : Ensure the group gce exists in the dynamic inventory file] ***
ok: [localhost]

TASK [cloud-gce : Populate the dynamic inventory] ******************************
changed: [localhost]

TASK [Wait until SSH becomes ready...] *****************************************
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "elapsed": 321, "failed": true, "msg": "Timeout when waiting for search string OpenSSH in 104.198.144.84:22"}

PLAY RECAP *********************************************************************
localhost                  : ok=14   changed=3    unreachable=0    failed=1

**Comment by dguido** [comment]
Is this a repeatable failure?

**Comment by caseylang** [comment]
I'm not positive you're asking me, so I apologize in advance for the extra comment, but yes, in my case this is repeatable.

**Comment by dguido** [comment]
Thanks. We're having a lot of issues with GCE. We recommend trying a different hosting provider for now.

**Comment by gunph1ld** [comment]
@caseylang Can you call ansible-playbook with -vvvv flags? I wan to see more verbose output. I can't reproduce on my environment. 
(You can run `bash -x ./algo` in order to get the exact ansible-playbook command, then abort the deployment and re-run the ansible-playbook with -vvvv flags)

**Comment by caseylang** [comment]
Here's the requested verbose output
[algo_verbose_log.txt](https://github.com/trailofbits/algo/files/894548/algo_verbose_log.txt)

**Comment by gunph1ld** [comment]
Can not reproduce. Are you able to SSH after the instance created? Try, please.
And use the latest commit

**Comment by caseylang** [comment]
No, I'm not able to SSH into the instance, either through `gcloud` locally, the Cloud Console feature in GCP, or by using `ssh` directly.

**Comment by gunph1ld** [comment]
Do any other cloud providers work? Are you able you use SSH to any other instances?

**Comment by caseylang** [comment]
I've resolved my problem locally and have a few suggested changes. I want to share them here before pushing the pull request, in case there is something I can change ahead of time.

Based on:
```
Note: Setting the sshKeys metadata value on the instance metadata instead of the project metadata is deprecated. Compute Engine will stop supporting this metadata value in March 2017. Set the ssh-keys instance metadata value to add ssh keys for users on individual instances instead.
```
https://cloud.google.com/compute/docs/instances/adding-removing-ssh-keys

and
```
By default, SSH access to instances as the root user is disabled even if you specify an SSH key in project or instance metadata for root.
...
By default, public images and most common operating systems do not allow root login over SSH. 
```
https://cloud.google.com/compute/docs/instances/ssh-keys#root

I've changed the configuration of the GCE instance 

```git
diff --git a/roles/cloud-gce/tasks/main.yml b/roles/cloud-gce/tasks/main.yml
index 9339113..eb88349 100644
--- a/roles/cloud-gce/tasks/main.yml
+++ b/roles/cloud-gce/tasks/main.yml
@@ -15,10 +15,10 @@
     zone: "{{ zone }}"
     machine_type: f1-micro
     image: ubuntu-1604
-    service_account_email: "{{ service_account_email  }}"
-    credentials_file: "{{ credentials_file_path  }}"
-    project_id: "{{ project_id  }}"
-    metadata: '{"sshKeys":"root:{{ ssh_public_key_lookup }}"}'
+    service_account_email: "{{ service_account_email }}"
+    credentials_file: "{{ credentials_file_path }}"
+    project_id: "{{ project_id }}"
+    metadata: '{"ssh-keys":"algo:{{ ssh_public_key_lookup }}"}'
@@ -27,7 +27,7 @@
   add_host:
     name: "{{ google_vm.instance_data[0].public_ip }}"
     groups: vpn-host
-    ansible_ssh_user: ubuntu
+    ansible_ssh_user: algo
     ansible_python_interpreter: "/usr/bin/python2.7"
     ansible_ssh_private_key_file: "{{ SSH_keys.private }}"
     cloud_provider: gce
```

Applying this change has resolved my issue. I can't account for the difference between mine and your test projects however.

If these changes are acceptable, please let me know and I'll submit the pull request.

**Comment by gunph1ld** [comment]
I'm quite sure that the user's metadata problem is not related to your initial problem. The `TASK [Wait until SSH becomes ready...] ` is trying to make a TCP connection and read the prompt and it's not using any credentials. More likely that you had some problem with your/ISP firewall or something

**Comment by caseylang** [comment]
Ok, then I'll close this issue. 

What is your opinion of my suggested changes. Even if you find them unrelated to the parent issue, the current in use ssh settings are suggested against by the GCP documentation

**Comment by gunph1ld** [comment]
Sure, send a PR, please.
