### ISSUE TITLE
Error during dependencies step of Algo install macOS

### ISSUE THREAD

**Issue by watkinsmd** [trailofbits/algo#326]
### OS / Environment

macOS Sierra 10.12.3

### Ansible version

Unknown: I don't think it installed properly in step 4. This is what I get when I try to view the version

Matthews-MacBook-Pro:algo-master watkinsm$ python ansible --version
/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'ansible': [Errno 2] No such file or directory

### Version of components from `requirements.txt`

setuptools>=11.3
ansible>=2.1,<2.2.1
dopy==0.3.5
boto>=2.5
boto3
azure==2.0.0rc5
msrest==0.4.1
apache-libcloud
six
pyopenssl
jinja2==2.8

### Summary of the problem

When I go to step 4 of the install instructions (dependencies), terminal stops here and gives me the following message. 

"Failed building wheel for pycrypto"

Detailed error:

Command "/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c "import setuptools, tokenize;__file__='/private/var/folders/3f/q33hl6_x6_nfyjg29fcl9qdr0000gp/T/pip-build-KlQHrx/pycrypto/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/3f/q33hl6_x6_nfyjg29fcl9qdr0000gp/T/pip-R8fRNE-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/3f/q33hl6_x6_nfyjg29fcl9qdr0000gp/T/pip-build-KlQHrx/pycrypto/

### Steps to reproduce the behavior

Numerous attempts to complete step 4 in the Algo setup resulting in the error above.

I have also tried running the command in step 8 under "Troubleshooting" here. Still get the same error. 

python -m pip install -r requirements.txt

### The way of deployment (cloud or local)

Cloud (Amazon EC3)

### Expected behavior

Expect to get past step #4 without getting the error. 

### Actual behavior

Error noted above from step 4 of install instructions. 

### Full log

  ----------------------------------------
  Failed building wheel for pycrypto
  Running setup.py clean for pycrypto
Failed to build pycrypto
Installing collected packages: pycparser, cffi, idna, enum34, asn1crypto, ipaddress, cryptography, pyasn1, paramiko, pycrypto, PyYAML, MarkupSafe, jinja2, ansible, requests, dopy, boto, python-dateutil, jmespath, docutils, botocore, futures, s3transfer, boto3, azure-nspkg, oauthlib, requests-oauthlib, certifi, chardet, keyring, isodate, msrest, PyJWT, adal, msrestazure, azure-common, azure-graphrbac, azure-batch, azure-mgmt-nspkg, azure-mgmt-keyvault, azure-mgmt-authorization, azure-mgmt-powerbiembedded, azure-mgmt-notificationhubs, azure-mgmt-scheduler, azure-mgmt-cognitiveservices, azure-mgmt-commerce, azure-mgmt-compute, azure-mgmt-batch, azure-mgmt-network, azure-mgmt-storage, azure-mgmt-cdn, azure-mgmt-logic, azure-mgmt-web, azure-mgmt-redis, azure-mgmt-resource, azure-mgmt, azure-servicebus, azure-storage, azure-servicemanagement-legacy, azure, apache-libcloud, pyopenssl
  Running setup.py install for pycrypto ... error
    Complete output from command /Users/watkinsm/algo-master/env/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/3f/q33hl6_x6_nfyjg29fcl9qdr0000gp/T/pip-build-DB5VZp/pycrypto/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/3f/q33hl6_x6_nfyjg29fcl9qdr0000gp/T/pip-2IOfMW-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/watkinsm/algo-master/env/bin/../include/site/python2.7/pycrypto:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.6-intel-2.7
    creating build/lib.macosx-10.6-intel-2.7/Crypto
    copying lib/Crypto/__init__.py -> build/lib.macosx-10.6-intel-2.7/Crypto
    copying lib/Crypto/pct_warnings.py -> build/lib.macosx-10.6-intel-2.7/Crypto
    creating build/lib.macosx-10.6-intel-2.7/Crypto/Hash
    copying lib/Crypto/Hash/__init__.py -> build/lib.macosx-10.6-intel-2.7/Crypto/Hash
    copying lib/Crypto/Hash/hashalgo.py -> build/lib.macosx-10.6-intel-2.7/Crypto/Hash
    copying lib/Crypto/Hash/HMAC.py -> build/lib.macosx-10.6-intel-2.7/Crypto/Hash
    copying lib/Crypto/Hash/MD2.py -> build/lib.macosx-10.6-intel-2.7/Crypto/Hash
    copying lib/Crypto/Hash/MD4.py -> build/lib.macosx-10.6-intel-2.7/Crypto/Hash
    copying lib/Crypto/Hash/MD5.py -> build/lib.macosx-10.6-intel-2.7/Crypto/Hash
    copying lib/Crypto/Hash/RIPEMD.py -> build/lib.macosx-10.6-intel-2.7/Crypto/Hash
    copying lib/Crypto/Hash/SHA.py -> build/lib.macosx-10.6-intel-2.7/Crypto/Hash
    copying lib/Crypto/Hash/SHA224.py -> build/lib.macosx-10.6-intel-2.7/Crypto/Hash
    copying lib/Crypto/Hash/SHA256.py -> build/lib.macosx-10.6-intel-2.7/Crypto/Hash
    copying lib/Crypto/Hash/SHA384.py -> build/lib.macosx-10.6-intel-2.7/Crypto/Hash
    copying lib/Crypto/Hash/SHA512.py -> build/lib.macosx-10.6-intel-2.7/Crypto/Hash
    creating build/lib.macosx-10.6-intel-2.7/Crypto/Cipher
    copying lib/Crypto/Cipher/__init__.py -> build/lib.macosx-10.6-intel-2.7/Crypto/Cipher
    copying lib/Crypto/Cipher/AES.py -> build/lib.macosx-10.6-intel-2.7/Crypto/Cipher
    copying lib/Crypto/Cipher/ARC2.py -> build/lib.macosx-10.6-intel-2.7/Crypto/Cipher
    copying lib/Crypto/Cipher/ARC4.py -> build/lib.macosx-10.6-intel-2.7/Crypto/Cipher
    copying lib/Crypto/Cipher/blockalgo.py -> build/lib.macosx-10.6-intel-2.7/Crypto/Cipher
    copying lib/Crypto/Cipher/Blowfish.py -> build/lib.macosx-10.6-intel-2.7/Crypto/Cipher
    copying lib/Crypto/Cipher/CAST.py -> build/lib.macosx-10.6-intel-2.7/Crypto/Cipher
    copying lib/Crypto/Cipher/DES.py -> build/lib.macosx-10.6-intel-2.7/Crypto/Cipher
    copying lib/Crypto/Cipher/DES3.py -> build/lib.macosx-10.6-intel-2.7/Crypto/Cipher
    copying lib/Crypto/Cipher/PKCS1_OAEP.py -> build/lib.macosx-10.6-intel-2.7/Crypto/Cipher
    copying lib/Crypto/Cipher/PKCS1_v1_5.py -> build/lib.macosx-10.6-intel-2.7/Crypto/Cipher
    copying lib/Crypto/Cipher/XOR.py -> build/lib.macosx-10.6-intel-2.7/Crypto/Cipher
    creating build/lib.macosx-10.6-intel-2.7/Crypto/Util
    copying lib/Crypto/Util/__init__.py -> build/lib.macosx-10.6-intel-2.7/Crypto/Util
    copying lib/Crypto/Util/_number_new.py -> build/lib.macosx-10.6-intel-2.7/Crypto/Util
    copying lib/Crypto/Util/asn1.py -> build/lib.macosx-10.6-intel-2.7/Crypto/Util
    copying lib/Crypto/Util/Counter.py -> build/lib.macosx-10.6-intel-2.7/Crypto/Util
    copying lib/Crypto/Util/number.py -> build/lib.macosx-10.6-intel-2.7/Crypto/Util
    copying lib/Crypto/Util/py21compat.py -> build/lib.macosx-10.6-intel-2.7/Crypto/Util
    copying lib/Crypto/Util/py3compat.py -> build/lib.macosx-10.6-intel-2.7/Crypto/Util
    copying lib/Crypto/Util/randpool.py -> build/lib.macosx-10.6-intel-2.7/Crypto/Util
    copying lib/Crypto/Util/RFC1751.py -> build/lib.macosx-10.6-intel-2.7/Crypto/Util
    copying lib/Crypto/Util/winrandom.py -> build/lib.macosx-10.6-intel-2.7/Crypto/Util
    creating build/lib.macosx-10.6-intel-2.7/Crypto/Random
    copying lib/Crypto/Random/__init__.py -> build/lib.macosx-10.6-intel-2.7/Crypto/Random
    copying lib/Crypto/Random/_UserFriendlyRNG.py -> build/lib.macosx-10.6-intel-2.7/Crypto/Random
    copying lib/Crypto/Random/random.py -> build/lib.macosx-10.6-intel-2.7/Crypto/Random
    creating build/lib.macosx-10.6-intel-2.7/Crypto/Random/Fortuna
    copying lib/Crypto/Random/Fortuna/__init__.py -> build/lib.macosx-10.6-intel-2.7/Crypto/Random/Fortuna
    copying lib/Crypto/Random/Fortuna/FortunaAccumulator.py -> build/lib.macosx-10.6-intel-2.7/Crypto/Random/Fortuna
    copying lib/Crypto/Random/Fortuna/FortunaGenerator.py -> build/lib.macosx-10.6-intel-2.7/Crypto/Random/Fortuna
    copying lib/Crypto/Random/Fortuna/SHAd256.py -> build/lib.macosx-10.6-intel-2.7/Crypto/Random/Fortuna
    creating build/lib.macosx-10.6-intel-2.7/Crypto/Random/OSRNG
    copying lib/Crypto/Random/OSRNG/__init__.py -> build/lib.macosx-10.6-intel-2.7/Crypto/Random/OSRNG
    copying lib/Crypto/Random/OSRNG/fallback.py -> build/lib.macosx-10.6-intel-2.7/Crypto/Random/OSRNG
    copying lib/Crypto/Random/OSRNG/nt.py -> build/lib.macosx-10.6-intel-2.7/Crypto/Random/OSRNG
    copying lib/Crypto/Random/OSRNG/posix.py -> build/lib.macosx-10.6-intel-2.7/Crypto/Random/OSRNG
    copying lib/Crypto/Random/OSRNG/rng_base.py -> build/lib.macosx-10.6-intel-2.7/Crypto/Random/OSRNG
    creating build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest
    copying lib/Crypto/SelfTest/__init__.py -> build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest
    copying lib/Crypto/SelfTest/st_common.py -> build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest
    creating build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/Cipher
    copying lib/Crypto/SelfTest/Cipher/__init__.py -> build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/Cipher
    copying lib/Crypto/SelfTest/Cipher/common.py -> build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/Cipher
    copying lib/Crypto/SelfTest/Cipher/test_AES.py -> build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/Cipher
    copying lib/Crypto/SelfTest/Cipher/test_ARC2.py -> build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/Cipher
    copying lib/Crypto/SelfTest/Cipher/test_ARC4.py -> build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/Cipher
    copying lib/Crypto/SelfTest/Cipher/test_Blowfish.py -> build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/Cipher
    copying lib/Crypto/SelfTest/Cipher/test_CAST.py -> build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/Cipher
    copying lib/Crypto/SelfTest/Cipher/test_DES.py -> build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/Cipher
    copying lib/Crypto/SelfTest/Cipher/test_DES3.py -> build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/Cipher
    copying lib/Crypto/SelfTest/Cipher/test_pkcs1_15.py -> build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/Cipher
    copying lib/Crypto/SelfTest/Cipher/test_pkcs1_oaep.py -> build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/Cipher
    copying lib/Crypto/SelfTest/Cipher/test_XOR.py -> build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/Cipher
    creating build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/Hash
    copying lib/Crypto/SelfTest/Hash/__init__.py -> build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/Hash
    copying lib/Crypto/SelfTest/Hash/common.py -> build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/Hash
    copying lib/Crypto/SelfTest/Hash/test_HMAC.py -> build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/Hash
    copying lib/Crypto/SelfTest/Hash/test_MD2.py -> build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/Hash
    copying lib/Crypto/SelfTest/Hash/test_MD4.py -> build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/Hash
    copying lib/Crypto/SelfTest/Hash/test_MD5.py -> build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/Hash
    copying lib/Crypto/SelfTest/Hash/test_RIPEMD.py -> build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/Hash
    copying lib/Crypto/SelfTest/Hash/test_SHA.py -> build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/Hash
    copying lib/Crypto/SelfTest/Hash/test_SHA224.py -> build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/Hash
    copying lib/Crypto/SelfTest/Hash/test_SHA256.py -> build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/Hash
    copying lib/Crypto/SelfTest/Hash/test_SHA384.py -> build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/Hash
    copying lib/Crypto/SelfTest/Hash/test_SHA512.py -> build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/Hash
    creating build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/Protocol
    copying lib/Crypto/SelfTest/Protocol/__init__.py -> build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/Protocol
    copying lib/Crypto/SelfTest/Protocol/test_AllOrNothing.py -> build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/Protocol
    copying lib/Crypto/SelfTest/Protocol/test_chaffing.py -> build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/Protocol
    copying lib/Crypto/SelfTest/Protocol/test_KDF.py -> build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/Protocol
    copying lib/Crypto/SelfTest/Protocol/test_rfc1751.py -> build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/Protocol
    creating build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/PublicKey
    copying lib/Crypto/SelfTest/PublicKey/__init__.py -> build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/PublicKey
    copying lib/Crypto/SelfTest/PublicKey/test_DSA.py -> build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/PublicKey
    copying lib/Crypto/SelfTest/PublicKey/test_ElGamal.py -> build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/PublicKey
    copying lib/Crypto/SelfTest/PublicKey/test_importKey.py -> build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/PublicKey
    copying lib/Crypto/SelfTest/PublicKey/test_RSA.py -> build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/PublicKey
    creating build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/Random
    copying lib/Crypto/SelfTest/Random/__init__.py -> build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/Random
    copying lib/Crypto/SelfTest/Random/test__UserFriendlyRNG.py -> build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/Random
    copying lib/Crypto/SelfTest/Random/test_random.py -> build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/Random
    copying lib/Crypto/SelfTest/Random/test_rpoolcompat.py -> build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/Random
    creating build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/Random/Fortuna
    copying lib/Crypto/SelfTest/Random/Fortuna/__init__.py -> build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/Random/Fortuna
    copying lib/Crypto/SelfTest/Random/Fortuna/test_FortunaAccumulator.py -> build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/Random/Fortuna
    copying lib/Crypto/SelfTest/Random/Fortuna/test_FortunaGenerator.py -> build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/Random/Fortuna
    copying lib/Crypto/SelfTest/Random/Fortuna/test_SHAd256.py -> build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/Random/Fortuna
    creating build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/Random/OSRNG
    copying lib/Crypto/SelfTest/Random/OSRNG/__init__.py -> build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/Random/OSRNG
    copying lib/Crypto/SelfTest/Random/OSRNG/test_fallback.py -> build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/Random/OSRNG
    copying lib/Crypto/SelfTest/Random/OSRNG/test_generic.py -> build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/Random/OSRNG
    copying lib/Crypto/SelfTest/Random/OSRNG/test_nt.py -> build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/Random/OSRNG
    copying lib/Crypto/SelfTest/Random/OSRNG/test_posix.py -> build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/Random/OSRNG
    copying lib/Crypto/SelfTest/Random/OSRNG/test_winrandom.py -> build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/Random/OSRNG
    creating build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/Util
    copying lib/Crypto/SelfTest/Util/__init__.py -> build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/Util
    copying lib/Crypto/SelfTest/Util/test_asn1.py -> build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/Util
    copying lib/Crypto/SelfTest/Util/test_Counter.py -> build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/Util
    copying lib/Crypto/SelfTest/Util/test_number.py -> build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/Util
    copying lib/Crypto/SelfTest/Util/test_winrandom.py -> build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/Util
    creating build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/Signature
    copying lib/Crypto/SelfTest/Signature/__init__.py -> build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/Signature
    copying lib/Crypto/SelfTest/Signature/test_pkcs1_15.py -> build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/Signature
    copying lib/Crypto/SelfTest/Signature/test_pkcs1_pss.py -> build/lib.macosx-10.6-intel-2.7/Crypto/SelfTest/Signature
    creating build/lib.macosx-10.6-intel-2.7/Crypto/Protocol
    copying lib/Crypto/Protocol/__init__.py -> build/lib.macosx-10.6-intel-2.7/Crypto/Protocol
    copying lib/Crypto/Protocol/AllOrNothing.py -> build/lib.macosx-10.6-intel-2.7/Crypto/Protocol
    copying lib/Crypto/Protocol/Chaffing.py -> build/lib.macosx-10.6-intel-2.7/Crypto/Protocol
    copying lib/Crypto/Protocol/KDF.py -> build/lib.macosx-10.6-intel-2.7/Crypto/Protocol
    creating build/lib.macosx-10.6-intel-2.7/Crypto/PublicKey
    copying lib/Crypto/PublicKey/__init__.py -> build/lib.macosx-10.6-intel-2.7/Crypto/PublicKey
    copying lib/Crypto/PublicKey/_DSA.py -> build/lib.macosx-10.6-intel-2.7/Crypto/PublicKey
    copying lib/Crypto/PublicKey/_RSA.py -> build/lib.macosx-10.6-intel-2.7/Crypto/PublicKey
    copying lib/Crypto/PublicKey/_slowmath.py -> build/lib.macosx-10.6-intel-2.7/Crypto/PublicKey
    copying lib/Crypto/PublicKey/DSA.py -> build/lib.macosx-10.6-intel-2.7/Crypto/PublicKey
    copying lib/Crypto/PublicKey/ElGamal.py -> build/lib.macosx-10.6-intel-2.7/Crypto/PublicKey
    copying lib/Crypto/PublicKey/pubkey.py -> build/lib.macosx-10.6-intel-2.7/Crypto/PublicKey
    copying lib/Crypto/PublicKey/RSA.py -> build/lib.macosx-10.6-intel-2.7/Crypto/PublicKey
    creating build/lib.macosx-10.6-intel-2.7/Crypto/Signature
    copying lib/Crypto/Signature/__init__.py -> build/lib.macosx-10.6-intel-2.7/Crypto/Signature
    copying lib/Crypto/Signature/PKCS1_PSS.py -> build/lib.macosx-10.6-intel-2.7/Crypto/Signature
    copying lib/Crypto/Signature/PKCS1_v1_5.py -> build/lib.macosx-10.6-intel-2.7/Crypto/Signature
    running build_ext
    running build_configure
    checking for gcc... gcc
    checking whether the C compiler works... no
    configure: error: in `/private/var/folders/3f/q33hl6_x6_nfyjg29fcl9qdr0000gp/T/pip-build-DB5VZp/pycrypto':
    configure: error: C compiler cannot create executables
    See `config.log' for more details
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/3f/q33hl6_x6_nfyjg29fcl9qdr0000gp/T/pip-build-DB5VZp/pycrypto/setup.py", line 456, in <module>
        core.setup(**kw)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/Users/watkinsm/algo-master/env/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install.py", line 563, in run
        self.run_command('build')
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build.py", line 127, in run
        self.run_command(cmd_name)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/private/var/folders/3f/q33hl6_x6_nfyjg29fcl9qdr0000gp/T/pip-build-DB5VZp/pycrypto/setup.py", line 251, in run
        self.run_command(cmd_name)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/private/var/folders/3f/q33hl6_x6_nfyjg29fcl9qdr0000gp/T/pip-build-DB5VZp/pycrypto/setup.py", line 278, in run
        raise RuntimeError("autoconf error")
    RuntimeError: autoconf error

**Comment by dguido** [comment]
"error: C compiler cannot create executables" you don't have a working compiler installed. Please see the troubleshooting docs for likely answers to your issue.
