### ISSUE TITLE
.mobileconfig does not work on iOS 10.3.2 Public Beta

### ISSUE THREAD

**Issue by l0n3r4n83r** [trailofbits/algo#328]
### OS / Environment

iOS 10.3.2 public beta

I was using iOS 10.3.2 Public beta and the VPN would not connect. The mobileconfig worked once I changed back to ios 10.3(14E277)

**Comment by suparngp** [comment]
For me, it doesn't even work on ios 10.3. The same profile works on mac 10.12.

**Comment by dguido** [comment]
Please use the issue template when reporting issues. We really do need a lot of that info to diagnose issues like this one. Please list the options you used to configure your Algo install.

**Comment by zadok0552** [comment]
Worked before 10.3.2 public beta. Fails after 10.3.2 public beta. Many on Apple dev forum report the same.

**Comment by dguido** [comment]
Thanks, we'll keep an eye on this as 10.3.2 goes through more testing.

**Comment by mshulman** [comment]
I'm seeing the same issue with 10.3.2 beta. The mobileconfig is not able to connect with 10.3.2.
