### ISSUE TITLE
Windows Powershell script fails to install cert due to permissions

### ISSUE THREAD

**Issue by joshmeisels** [trailofbits/algo#329]
### OS / Environment
Windows 10  - CLIENT setup

### Summary of the problem
Running the user powershell script created for Windows users does not install the user cert because this action requires elevation. The script should be updated to elevate before attempting to install the cert.

### Steps to reproduce the behavior
Set up a VPN server using Algo. Copy the Powershell script and cert files to the windows machine you want to join the VPN. Run the Powershell script.

### Expected behavior
Script should install cert and create the VPN connection in Windows.

### Actual behavior
Script shows an error on installing the cert due to lack of permissions.

**Comment by dguido** [comment]
Thanks, can you submit a PR to add that note to the readme?

**Comment by joshmeisels** [comment]
@dguido I couldn't figure out how to run as admin, so I just manually added the certs from certmgr.msc. I could add those instructions to the readme, but ideally the script should be able to request permissions.

**Comment by sregister** [comment]
@joshmeisels If you right click on powershell and select "run as administrator" you should be able to run scripts that require permissions.

**Comment by joshmeisels** [comment]
@sregister if you right-click on the script you can run with powershell, but not as admin. I can run powershell as an admin, cd to the directory with the script, but when I attempt to run it I'm told my computer is not set up to allow scripting. I could of course go change that, but it's another set of steps to change the security policies on the machine.

**Comment by xtrapwr** [comment]
To clarify, depending on whether or not a user has ever run Powershell on windows, there are 2 steps they will need to do.

1) Run Powershell as Administrator.
2) Change their execution policy.  (As laid out here https://msdn.microsoft.com/powershell/reference/5.1/Microsoft.PowerShell.Core/about/about_Execution_Policies)
