### ISSUE TITLE
Instructions for deploying on Dreamhost DreamCompute

### ISSUE THREAD

**Issue by joshuaiz** [trailofbits/algo#334]
### OS / Environment
MacOS Sierra 10.12.4
Remote server: DreamHost DreamCompute QuickLaunch Ubuntu 16.04

### Summary of the problem
Installed Algo successfully then added the profile but with the profile installed I cannot connect to the internet at all. Previously I installed Algo on an EC2 instance and was able to connect so perhaps there is something with the particular Ubuntu install.

### Steps to reproduce the behavior
1. Set up DreamCompute instance via DreamHost
2. Install ssh keys for passwordless login
3. Run Algo (successful)
4. Install profile from ~/algo/configs on local machine
5. Connect to VPN in System Preferences
6. Stalls on Connecting...

Not sure what to check now or even where to look to troubleshoot this. Is the problem local or remote?

**Comment by joshuaiz** [comment]
Updated everything on the Ubuntu instance and then reinstalled algo and still can't connect.

One thing to note, since I installed algo previously on EC2, when you install it again it does *not* update the ./ssh/config file with the additional host information. Don't know if it checks if that info is already there but in my case I had to delete the EC2 host info for it to write the new host info to that file.

**Comment by magicwave** [comment]
+1 I would also like to see instructions for setup on Dreamhost.

**Comment by joshuaiz** [comment]
Just a follow up, I could not get it to work on DreamCompute. Are there specific ports that need to be open like 1194 or something else? The documentation doesn't specify. 

I got OpenVPN working on the DreamCompute instance however the speeds weren't high enough so I kind of gave up on this.

**Comment by dguido** [comment]
This should work if you do a local install.
