### ISSUE TITLE
Problem with connection using mobileconfig

### ISSUE THREAD

**Issue by ashsecurity** [trailofbits/algo#339]
### OS / Environment
MAC OS X El Capitan 10.11.6

VPS:  Ubuntu 16.10 (GNU/Linux 4.8.0-45-generic x86_64)

### Version of components from `requirements.txt`

setuptools 26.1.1

### Summary of the problem

After importing mobileconfig on Mac OS, VPN does not start. Same happens after importing mobileconfig on IOS 

### Steps to reproduce the behavior
Installed Algo on VPS. 
Copied mobileconfig file and installed it on MAC OS as well as iOS device. 
Tried to press connect. 
Connection does not even start. 

### The way of deployment (cloud or local)
Cloud. ON VPS provided by hetzner hosting company.

### Expected behavior
Should at least start connecting and at the successfully connect.

Tested IPsec setup with password instead of certificate and it was working fine. 

### Actual behavior

Does not even start the connection. Perhaps problem with mobileconfig?

### Full log

From the Macbook:

kernel[0]: ipsec_ctl_connect: creating interface ipsec0
Apr  2 09:49:27 MacBook-Pro configd[53]: network changed
Apr  2 09:49:27 MacBook-Pro vmnet-bridge[2352]: Dynamic store changed
Apr  2 09:49:27 MacBook-Pro kernel[0]: SIOCPROTODETACH_IN6: ipsec0 error=6
Apr  2 09:49:27 MacBook-Pro configd[53]: network changed
Apr  2 09:49:27 MacBook-Pro vmnet-bridge[2352]: Dynamic store changed
Apr  2 09:49:27 MacBook-Pro symptomsd[223]: nw_interface_create_with_name netutil_ifname_to_ifindex(ipsec0) failed, dumping backtrace:
	        [x86_64] libnetcore-583.50.1
	    0   libsystem_network.dylib             0x00007fff8c05fde9 __nw_create_backtrace_string + 123
	    1   libsystem_network.dylib             0x00007fff8c0821f3 nw_interface_create_with_name + 179
	    2   Network                             0x00007fffa184bedc -[NWInterface initWithInterfaceName:] + 120
	    3   SymptomEvaluator                    0x00007fff93f262fc config_callback + 874
	    4   SystemConfiguration                 0x00007fff925dbfaf rlsPerform + 184
	    5   SystemConfiguration                 0x00007fff925ef3ab __SCDynamicStoreSetDispatchQueue_block_invoke_2 + 52
	    6   libdispatch.dylib                   0x00007fff906fa93d _dispatch_call_block_and_release + 12
	    7   libdispatch.dylib                   0x00007fff906ef40b _dispatch_client_callout + 8
	    8   libdispatch.dylib                   0x00007fff906f403b _dispatch_queue_drain + 754
	    9   libdispatch.dylib                   0x00007fff906fa707 _dispatch_queue_invoke + 549
	    10  libdispatch.dylib                   0x00007fff906f2d53 _dispatch_root_queue_drain + 538
	    11  libdispatch.dylib                   0x00007fff906f2b00 _dispatch_worker_thread3 + 91
	    12  libsystem_pthread.dylib             0x00007fff994724de _pthread_wqthread + 1129
	    13  libsystem_pthread.dylib             0x00007fff99470341 start_wqthread + 13
Apr  2 09:49:27 MacBook-Pro symptomsd[223]: -[NWInterface initWithInterfaceName:] nw_interface_create_with_name(ipsec0) failed, dumping backtrace:
	        [x86_64] libnetcore-583.50.1
	    0   libsystem_network.dylib             0x00007fff8c05fde9 __nw_create_backtrace_string + 123
	    1   Network                             0x00007fffa184bf46 -[NWInterface initWithInterfaceName:] + 226
	    2   SymptomEvaluator                    0x00007fff93f262fc config_callback + 874
	    3   SystemConfiguration                 0x00007fff925dbfaf rlsPerform + 184
	    4   SystemConfiguration                 0x00007fff925ef3ab __SCDynamicStoreSetDispatchQueue_block_invoke_2 + 52
	    5   libdispatch.dylib                   0x00007fff906fa93d _dispatch_call_block_and_release + 12
	    6   libdispatch.dylib                   0x00007fff906ef40b _dispatch_client_callout + 8
	    7   libdispatch.dylib                   0x00007fff906f403b _dispatch_queue_drain + 754
	    8   libdispatch.dylib                   0x00007fff906fa707 _dispatch_queue_invoke + 549
	    9   libdispatch.dylib                   0x00007fff906f2d53 _dispatch_root_queue_drain + 538
	    10  libdispatch.dylib                   0x00007fff906f2b00 _dispatch_worker_thread3 + 91
	    11  libsystem_pthread.dylib             0x00007fff994724de _pthread_wqthread + 1129
	    12  libsystem_pthread.dylib             0x00007fff99470341 start_wqthread + 13
Apr  2 09:49:27 MacBook-Pro symptomsd[223]: nw_interface_create_with_name netutil_ifname_to_ifindex(ipsec0) failed, dumping backtrace:
	        [x86_64] libnetcore-583.50.1
	    0   libsystem_network.dylib             0x00007fff8c05fde9 __nw_create_backtrace_string + 123
	    1   libsystem_network.dylib             0x00007fff8c0821f3 nw_interface_create_with_name + 179
	    2   Network                             0x00007fffa184bedc -[NWInterface initWithInterfaceName:] + 120
	    3   SymptomEvaluator                    0x00007fff93f262fc config_callback + 874
	    4   SystemConfiguration                 0x00007fff925dbfaf rlsPerform + 184
	    5   SystemConfiguration                 0x00007fff925ef3ab __SCDynamicStoreSetDispatchQueue_block_invoke_2 + 52
	    6   libdispatch.dylib                   0x00007fff906fa93d _dispatch_call_block_and_release + 12
	    7   libdispatch.dylib                   0x00007fff906ef40b _dispatch_client_callout + 8
	    8   libdispatch.dylib                   0x00007fff906f403b _dispatch_queue_drain + 754
	    9   libdispatch.dylib                   0x00007fff906fa707 _dispatch_queue_invoke + 549
	    10  libdispatch.dylib                   0x00007fff906f2d53 _dispatch_root_queue_drain + 538
	    11  libdispatch.dylib                   0x00007fff906f2b00 _dispatch_worker_thread3 + 91
	    12  libsystem_pthread.dylib             0x00007fff994724de _pthread_wqthread + 1129
	    13  libsystem_pthread.dylib             0x00007fff99470341 start_wqthread + 13
Apr  2 09:49:27 MacBook-Pro symptomsd[223]: -[NWInterface initWithInterfaceName:] nw_interface_create_with_name(ipsec0) failed, dumping backtrace:
	        [x86_64] libnetcore-583.50.1
	    0   libsystem_network.dylib             0x00007fff8c05fde9 __nw_create_backtrace_string + 123
	    1   Network                             0x00007fffa184bf46 -[NWInterface initWithInterfaceName:] + 226
	    2   SymptomEvaluator                    0x00007fff93f262fc config_callback + 874
	    3   SystemConfiguration                 0x00007fff925dbfaf rlsPerform + 184
	    4   SystemConfiguration                 0x00007fff925ef3ab __SCDynamicStoreSetDispatchQueue_block_invoke_2 + 52
	    5   libdispatch.dylib                   0x00007fff906fa93d _dispatch_call_block_and_release + 12
	    6   libdispatch.dylib                   0x00007fff906ef40b _dispatch_client_callout + 8
	    7   libdispatch.dylib                   0x00007fff906f403b _dispatch_queue_drain + 754
	    8   libdispatch.dylib                   0x00007fff906fa707 _dispatch_queue_invoke + 549
	    9   libdispatch.dylib                   0x00007fff906f2d53 _dispatch_root_queue_drain + 538
	    10  libdispatch.dylib                   0x00007fff906f2b00 _dispatch_worker_thread3 + 91
	    11  libsystem_pthread.dylib             0x00007fff994724de _pthread_wqthread + 1129
	    12  libsystem_pthread.dylib             0x00007fff99470341 start_wqthread + 13

**Comment by dguido** [comment]
You're using an unsupported cloud provider and an unsupported ubuntu 16.10 install. Please try again on a supported platform.
