### ISSUE TITLE
GCE setup is successful but once connected to VPN browsing does not work. 

### ISSUE THREAD

**Issue by fabianmurariu** [trailofbits/algo#345]
### OS / Environment
macOS

### Ansible version
ansible 2.2.0.0
  config file = /Users/murariuf/Source/algo/ansible.cfg
  configured module search path = Default w/o overrides

### Version of components from `requirements.txt`
adal (0.4.5)
ansible (2.2.0.0)
apache-libcloud (1.5.0)
appdirs (1.4.3)
asn1crypto (0.22.0)
azure (2.0.0rc5)
azure-batch (0.30.0rc5)
azure-common (1.1.4)
azure-graphrbac (0.30.0rc5)
azure-mgmt (0.30.0rc5)
azure-mgmt-authorization (0.30.0rc5)
azure-mgmt-batch (0.30.0rc5)
azure-mgmt-cdn (0.30.0rc5)
azure-mgmt-cognitiveservices (0.30.0rc5)
azure-mgmt-commerce (0.30.0rc5)
azure-mgmt-compute (0.30.0rc5)
azure-mgmt-keyvault (0.30.0rc5)
azure-mgmt-logic (0.30.0rc5)
azure-mgmt-network (0.30.0rc5)
azure-mgmt-notificationhubs (0.30.0rc5)
azure-mgmt-nspkg (1.0.0)
azure-mgmt-powerbiembedded (0.30.0rc5)
azure-mgmt-redis (0.30.0rc5)
azure-mgmt-resource (0.30.0rc5)
azure-mgmt-scheduler (0.30.0rc5)
azure-mgmt-storage (0.30.0rc5)
azure-mgmt-web (0.30.0rc5)
azure-nspkg (1.0.0)
azure-servicebus (0.20.2)
azure-servicemanagement-legacy (0.20.3)
azure-storage (0.32.0)
boto (2.46.1)
boto3 (1.4.4)
botocore (1.5.33)
certifi (2017.1.23)
cffi (1.10.0)
chardet (2.3.0)
cryptography (1.8.1)
docutils (0.13.1)
dopy (0.3.5)
enum34 (1.1.6)
futures (3.0.5)
idna (2.5)
ipaddress (1.0.18)
isodate (0.5.4)
Jinja2 (2.8)
jmespath (0.9.2)
keyring (10.3.1)
MarkupSafe (1.0)
msrest (0.4.1)
msrestazure (0.4.7)
oauthlib (2.0.2)
packaging (16.8)
paramiko (2.1.2)
pip (9.0.1)
pyasn1 (0.2.3)
pycparser (2.17)
pycrypto (2.6.1)
PyJWT (1.4.2)
pyOpenSSL (16.2.0)
pyparsing (2.2.0)
python-dateutil (2.6.0)
PyYAML (3.12)
requests (2.13.0)
requests-oauthlib (0.8.0)
s3transfer (0.1.10)
setuptools (34.3.3)
six (1.10.0)
wheel (0.29.0)

### Summary of the problem
google cloud VM does not seem to do IP forwarding.
ping works
ssh to remote box does
http doesn't
didn't try other protocols

### Steps to reproduce the behavior
run the setup for gce

### The way of deployment (cloud or local)
cloud

### Expected behavior
connecting via the macOS profile should connect to VPN and enable internet traffic

### Actual behavior
connection to VPN works but http does not to through

**Comment by fabianmurariu** [comment]
Duplicate of ??

**Comment by tehranian** [comment]
@fabianmurariu I think this is a dupe of #310, which then refers to #210 . 
You and I are not the only ones having issues with GCP.
