### ISSUE TITLE
Windows 10 Algo installation issues

### ISSUE THREAD

**Issue by bkgeist** [trailofbits/algo#347]
### OS / Environment
Windows 10

### Ansible version

?? cannot get Ansible to install..
### Version of components from `requirements.txt`

setuptools>=11.3
ansible>=2.1,<2.2.1
dopy==0.3.5
boto>=2.5
boto3
azure==2.0.0rc5
msrest==0.4.1
apache-libcloud
six
pyopenssl
jinja2==2.8

### Summary of the problem
Following installation instructions for Windows 10.  It appears ansible is not installing correctly:  from the log file:

.
.
.
 Running setup.py install for ansible
    Running command /home/bkgeist/algo/env/bin/python -c "import setuptools, tokenize;__file__='/home/bkgeist/algo/env/build/ansible/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-1bhtBR-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/bkgeist/algo/env/include/site/python2.7
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/bkgeist/algo/env/local/lib/python2.7/site-packages/setuptools/__init__.py", line 10, in <module>
        from six.moves import filter, map
    ImportError: No module named six.moves
    Complete output from command /home/bkgeist/algo/env/bin/python -c "import setuptools, tokenize;__file__='/home/bkgeist/algo/env/build/ansible/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-1bhtBR-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/bkgeist/algo/env/include/site/python2.7:
    Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/home/bkgeist/algo/env/local/lib/python2.7/site-packages/setuptools/__init__.py", line 10, in <module>

    from six.moves import filter, map

ImportError: No module named six.moves

### Steps to reproduce the behavior
I have tried the installation process indicated on algo github page on two Windows 10, with the same failure each time.  I am merely cutting and pasting into the bash window, so I do not believe I am incorrectly entering a command.  After getting a bash window up I paste the following:

sudo apt-get update && sudo apt-get install python-pip python-setuptools build-essential libssl-dev libffi-dev python-dev python-virtualenv git -y

git clone https://github.com/trailofbits/algo && cd algo

then:
python -m virtualenv env && source env/bin/activate && python -m pip install -r requirements.txt

(see terminating messages from log file given above-- something about six.moves not being installed, ansible is not successfully installed it appears.)  Next, issuing the command  "./algo"
results in this error: 

./algo: line 63: ansible-playbook: command not found
### Expected behavior
I expected to successfully install the vpn. 

### Actual behavior

installation failed.

**Comment by tuangd** [comment]
I have this same issue. 
Anyone can help fix this?
