### ISSUE TITLE
Algo wake after sleep and battery drain issues - IOS 10.3 / iPhone 7+

### ISSUE THREAD

**Issue by feoh** [trailofbits/algo#348]
### OS / Environment
IOS 10.3 / iPhone 7+

### Ansible version

ansible 2.2.0.0
  config file = /home/feoh/src/personal/algo/ansible.cfg
  configured module search path = Default w/o overrides

### Version of components from `requirements.txt`

feoh@amicable 02:07:00 ~/src/personal/algo |master U:1 ?:1 ✗| →  cat requirements.txt
setuptools>=11.3
ansible>=2.1,<2.2.1
dopy==0.3.5
boto>=2.5
boto3
azure==2.0.0rc5
msrest==0.4.1
apache-libcloud
six
pyopenssl
jinja2==2.8

### Summary of the problem

The iPhone is unable to utilize networking for 1-2 minutes after waking from a long sleep - say overnight.  Also battery consumption is MUCH higher than normal. 20% over the course of a couple of hours of streaming podcasts whereas normally I see maybe 7% drain in that time with that same usage pattern.

### Steps to reproduce the behavior

Wake after a long sleep (usually overnight). Observe that nothing involving networking (Firefox/Safari, Castro (streaming podcasts), Youtube, etc.) works. App either won't launch or launches with an error about network connectivity.

### The way of deployment (cloud or local)

Cloud. EC2 out of us-east-2.

### Expected behavior

Networking should work after waking phone from sleep and battery drain should not be massive.

### Actual behavior

See summary.

### Full log

Not sure how to get verbose logging from the phone.

Note that I can fix the networking issue by going into Settings and toggling the "VPN" button which flips to off and then immediately back to on, and networking starts working.

Also interestingly I haven't seen any of these problems on my iPad pro or the two Macs I have algo running great on.

Happy to provide any further debug info I can.

**Comment by dguido** [comment]
You can try #336 but there's nothing else I can suggest to change your situation. It probably has to do with weak signal strength on your phone wherever you leave it over night. We can only modify the settings via the Profile so our options here are limited. This is really Apple's problem to fix.

**Comment by feoh** [comment]
I totally get it. Sorry didn't mean to rub salt in an open wound. I've got algo running great on two iPads and three macs, and it's fantastic.

Do we know if there's a bug for this reported through Apple Radar? If there isn't I'm happy to create one.

**Comment by dguido** [comment]
I'm not aware of any bugs in radar. My guess is that your VPN tries to connect and can't succeed all night due to low signal strength FYI. But you would need to do more to debug it to know for sure.
