### ISSUE TITLE
Where are the ca.crt and user_windows.ps1 files

### ISSUE THREAD

**Issue by bwb1729** [trailofbits/algo#349]
Basic question: 

I'm trying to setup a Windows client for an active Algo VPN server. However, I can't seem to find the ca.crt and user_windows.ps1 files in the configs directory of my local Ubuntu 16.10 machine that I ran algo on. I do see a cacrt.pem file, which I assume is the same as the ca.crt, but I cannot find the .ps1 file.

Any help would be greatly appreciated.

**Comment by dguido** [comment]
You had to choose Windows support during setup

**Comment by bwb1729** [comment]
Thanks dguido for the fast response. 

I didn't see an option to choose Windows support during setup. Is there something to be set in the config.cfg file? What setup are you referring to exactly?

**Comment by dguido** [comment]
Run ./algo again

**Comment by bwb1729** [comment]
It worked! Thanks very much for the quick responses.

BTW, the CA certificate is still named cacert.pem. Is there a reason it's different from ca.crt as listed in the README?

**Comment by inb4ohnoes** [comment]
I'm having the same issue... I can't seem to find any sort of ca.crt file. I've do have the .ps1 file and have made absolutely sure that I allowed Windows clients during the setup. I've tried converting cacert.pem to something windows can install but that doesn't seem to work...

**Comment by bwb1729** [comment]
It worked for me using cacert.pem. Import cacert.pem to your Trusted Root certificate store just like in the README, no need to modify it. Then run the powershell script. It worked for me.

Though it is confusing that it's not named ca.crt

**Comment by inb4ohnoes** [comment]
I have tried that, but right at the beginning of running the script it encounters a file not found error, and when I try to proceed and connect the vpn I get a no certificate found error from windows.

**Comment by dguido** [comment]
It needs the user certificate alongside the script, you can't just run the script by itself

**Comment by inb4ohnoes** [comment]
Do they have to be in the same folder? I’m just running the script within the original folder structure which has the script at the top level then user.crt in pki/certs.

**Comment by dguido** [comment]
Doesn't the script reference the user.p12 file?

**Comment by inb4ohnoes** [comment]
Oops you’re right. But in that case they’re in the same to level folder so the script should be able to find it.

**Comment by inb4ohnoes** [comment]
It turns out I was being stupid and not following a step correctly. Sorry!

**Comment by dguido** [comment]
Send me a PR if the documentation could be clearer.

**Comment by inb4ohnoes** [comment]
I've made a PR. Please see https://github.com/trailofbits/algo/pull/377!
