### ISSUE TITLE
strongSwan Android Client connects to server but no traffic passes 

### ISSUE THREAD

**Issue by pungens** [trailofbits/algo#358]
### OS / Environment

Algo is running on Google Compute Platform
Client: Moto X 2nd Gen Android 5.1
Algo Install Script run from: lubuntu 16.10

### Ansible version

Name: ansible
Version: 2.2.0.0

### Version of components from `requirements.txt`

Name: msrestazure
Version: 0.4.7

Name: setuptools
Version: 34.3.3

Name: dopy
Version: 0.3.5

Name: boto
Version: 2.46.1

Name: boto3
Version: 1.4.4

Name: azure
Version: 2.0.0rc5

Name: msrest
Version: 0.4.1

Name: apache-libcloud
Version: 1.5.0

Name: six
Version: 1.10.0

Name: pyOpenSSL
Version: 16.2.0

Name: Jinja2
Version: 2.8

### Summary of the problem
Algo server is running & strongSwan is configured per guide. I can connect to server. Traffic does not seem to pass through. I can't navigate anywhere on my phone. Chrome browser on phone says DNS server cannot be reached. Problem occurs on Wi-Fi & when connected to cellular network. 

### Steps to reproduce the behavior
Install lubuntu 16.10
sudo apt-get update
sudo apt-get upgrade
Follow https://github.com/trailofbits/algo instructions to setup Algo on Google CP. 
Install strongSwan on phone
Connect usb cable to phone
Transfer .p12 file to phone
Follow https://github.com/trailofbits/algo/blob/master/docs/ANDROID.md to setup strongSwan on phone.
Connect
Phone shows it is connected
Open Web browser
navigate to google
DNS server cannot be reached

### The way of deployment (cloud or local)
cloud

### Expected behavior
view websites

### Actual behavior
DNS server cannot be reached

I have not tried to change MTU size. I'm not sure how to do that on Android.

**Comment by defunctio** [comment]
The MTU can be changed under the advanced section of your VPN profile. Try setting this to 1280 and provide an update on the results.

**Comment by pungens** [comment]
MTU changed to 1280 in stronSwan advanced. Same issue. 
ERR_NAME_NOT_RESOLVED server DNS address could not be found.

**Comment by kiratp** [comment]
You currently need to manually deploy to GCE with IP forwarding enabled 
https://cloud.google.com/compute/docs/networking#canipforward

Also works in the UI - when creating the instance, expand the advanced settings and look under Network

GCE also has some other issues that I am working on fixing so your milage may vary. Please do report success/failure.

**Comment by pungens** [comment]
I tried manually deploying GCE with IP forwarding enabled a few days ago. That seemed to require  a local install. I had the same issue, but I did not adjust the MTU and I've since deleted that instance. 
I was afraid that I improperly configured the local install at the time. 
I may have time to try a new GCE over the weekend.

**Comment by defunctio** [comment]
At this time we are fairly certain this is related to GCE deploys. @kiratp has done some work recently that should resolve these issues. We should see a PR on this soon.

Meanwhile if you can try deploying on another cloud provider to ensure the results are not the same that would be great. If not, you will need to wait for an update at this time.

**Comment by pungens** [comment]
Sure, I'll try an AWS later today.

**Comment by pungens** [comment]
Ended up using a DO droplet. Everything is working great on my phone with default MTU. So, it looks like this was likely the issues with the GCE deploys.

**Comment by defunctio** [comment]
Thanks for testing, I'm going to close this issue.

**Comment by fuzzmz** [comment]
@defunctio, considering that the bug hasn't been fixed and GCE is more or less unusable as a host for algo, why was this closed?

This issue being closed is making it hard for me to track when I can give algo another try.

**Comment by dguido** [comment]
There's a separate issue for GCE
