### ISSUE TITLE
Explain Why Aren't You Using OpenVPN in FAQ

### ISSUE THREAD

**Issue by fuzzyroddis** [trailofbits/algo#36]
The readme says

>Does not install Tor, OpenVPN, or other insecure servers

Implying OpenVPN is insecure.

However the FAQ only explains why you are not using Tor, Racoon, LibreSwan, or OpenSwan.

**Comment by dguido** [comment]
That is explained by the Anti-Feature line -- "Does not depend on the security of [TLS](https://tools.ietf.org/html/rfc7457)" -- but I will add something more explicit later. I do not trust OpenVPN for many reasons.

**Comment by dguido** [comment]
This is more fully explained in the FAQ: https://github.com/trailofbits/algo/blob/master/docs/faq.md#why-arent-you-using-openvpn
