### ISSUE TITLE
Python CLI interface

### ISSUE THREAD

**Issue by defunctio** [trailofbits/algo#360]
Ansible is written in python and can be invoked through the module APIs. We should consider rewriting the CLI interface and eliminate the dependency of bash for the sake of portability. In the past we have run across minor differences in bash versions that have resulted in operability issues. 

Let's aim for a rewrite of our CLI in python for a cleaner result using https://github.com/google/python-fire . If we want to keep an interactive CLI menu driven interface we can continue to maintain the bash script as well.

**Comment by dguido** [comment]
Saving this for a new major version
