### ISSUE TITLE
Algo base images built by CI

### ISSUE THREAD

**Issue by defunctio** [trailofbits/algo#366]
As deployment times to continue to grow, building base images from a repository with CI for ***optional*** use in both rapid deployment in production to reduce deployment times seem like a reasonable compromise between openness and performance.

This will require some role refactoring which is overdue anyway but I think the improvements we would see especially for speeding up development testing would be worth it in the long run. 

The end result is we have images rebuilt at a given interval from the latest repository release tag that provides us with a clean image that contains the necessary dependencies, hardening and base configurations in so that a new deploy only requires minimal system updates and key deployment.

**Comment by Thermi** [comment]
What kind of base image are you thinking about? An Ubuntu image with new Algo predeployed onto it or something like a liveCD? Either of that scenarios would require the deployment of new keys by the user with a different role (which I think is actually fine) onto the server which was provisioned with the image.

**Comment by defunctio** [comment]
Correct, an Ubuntu image built by CI (ex: AMI for EC2), consisting of pre-deployed base Algo (both stable and dev) with all the necessary dependencies installed. Where the instance is brought up and client side generated keys are transferred to the new host.

Optional features could then be installed/enabled post-deployment.

**Comment by jackivanov** [comment]
It might be superseded by https://github.com/trailofbits/algo/issues/1416
