### ISSUE TITLE
Update the CentOS instructions to use virtualenv

### ISSUE THREAD

**Issue by dguido** [trailofbits/algo#368]

**Comment by dguido** [comment]
I didn't test these but I think this works:
https://github.com/trailofbits/algo/commit/0256f3b31ca475985d2e3bcf48d67878955b829e

We should still probably run through this again and update where we deviate from the main instructions.

**Comment by gunph1ld** [comment]
Tested on Centos 6.9 x64 at DigitalOcean, works as expected.
Actually, we may consider adding instructions to run inside a docker, like https://github.com/trailofbits/algo/pull/331
Should be more easy

**Comment by dguido** [comment]
Great! Let's leave the docker-based install to a little later. I think that approach is still being refined and this works ok as is.
