### ISSUE TITLE
Own server deployment "Destination directory /etc/network/interfaces.d does not exist"

### ISSUE THREAD

**Issue by hailigsblechle** [trailofbits/algo#370]
I get the following error on installing algo for the first time on a local exiting ubuntu sever. I have a file called '/etc/network/interfaces' but not a directory called '/etc/network/interfaces.d'.
Is this some special virtual server configuration issue?

> TASK [common : Loopback for services configured] *******************************
> fatal: [localhost]: FAILED! => {"changed": true, "failed": true, "msg": "Destination directory /etc/network/interfaces.d does not exist"}
> 
> PLAY RECAP *********************************************************************
> localhost                  : ok=12   changed=2    unreachable=0    failed=1   
> 

### OS / Environment
Own server with Ubuntu 12.04.5 LTS

### The way of deployment (cloud or local)
local

  What provider would you like to use?
    1. DigitalOcean
    2. Amazon EC2
    3. Google Compute Engine
    4. Microsoft Azure
    5. Install to existing Ubuntu server

Enter the number of your desired provider
: 5

Enter the IP address of your server: (or use localhost for local installation)
: localhost

What user should we use to login on the server? (note: passwordless login required, or ignore if you're deploying to localhost)
[root]: 

Enter the public IP address of your server: (IMPORTANT! This IP is used to verify the certificate)
[localhost]: **.***.***.***

Was this server deployed by Algo previously?
[y/N]: N

Do you want macOS/iOS clients to enable "VPN On Demand" when connected to cellular networks?
[y/N]: N

Do you want macOS/iOS clients to enable "VPN On Demand" when connected to Wi-Fi?
[y/N]: N

Do you want to install a DNS resolver on this VPN server, to block ads while surfing?
[y/N]: y

Do you want each user to have their own account for SSH tunneling?
[y/N]: N

Do you want to apply operating system security enhancements on the server? (warning: replaces your sshd_config)
[y/N]: N

Do you want the VPN to support Windows 10 clients? (requires RSA certificates and key exchange, less secure)
[y/N]: N

Do you want to retain the CA key? (required to add users in the future, but less secure)
[y/N]: y

PLAY [Configure the server] ****************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Generate the SSH private key] ********************************************
ok: [localhost -> localhost]

TASK [Generate the SSH public key] *********************************************
ok: [localhost -> localhost]

TASK [Change mode for the SSH private key] *************************************
ok: [localhost -> localhost]

TASK [Ensure the dynamic inventory exists] *************************************
ok: [localhost]

TASK [Ensure the local ssh directory is exist] *********************************
skipping: [localhost]

TASK [Copy the algo ssh key to the local ssh directory] ************************
skipping: [localhost]

TASK [Configure the local ssh config] ******************************************
skipping: [localhost]

TASK [local : Add the instance to an inventory group] **************************
skipping: [localhost]

TASK [local : Add the instance to an inventory group] **************************
changed: [localhost]

TASK [local : set_fact] ********************************************************
ok: [localhost]

TASK [local : Ensure the group local exists in the dynamic inventory file] *****
ok: [localhost]

TASK [local : Populate the dynamic inventory] **********************************
ok: [localhost]

PLAY [Configure the server and install required software] **********************

TASK [Check the system] ********************************************************
changed: [localhost]

TASK [Ubuntu | Install prerequisites] ******************************************
skipping: [localhost]

TASK [FreeBSD / HardenedBSD | Install prerequisites] ***************************
skipping: [localhost]

TASK [FreeBSD / HardenedBSD | Configure defaults] ******************************
skipping: [localhost]

TASK [set_fact] ****************************************************************
skipping: [localhost]

TASK [Ensure the algo ssh key exist on the server] *****************************
ok: [localhost]

TASK [common : Gather Facts] ***************************************************
ok: [localhost]

TASK [common : Loopback for services configured] *******************************
fatal: [localhost]: FAILED! => {"changed": true, "failed": true, "msg": "Destination directory /etc/network/interfaces.d does not exist"}

PLAY RECAP *********************************************************************
localhost                  : ok=12   changed=2    unreachable=0    failed=1

**Comment by dguido** [comment]
We don't support Ubuntu 12.04, only 16.04. Sorry!
