### ISSUE TITLE
Failed to connect to the host

### ISSUE THREAD

**Issue by trantrungson** [trailofbits/algo#373]
### OS / Environment
Windows 10 using Digital Ocean Cloud

### Version of components from `requirements.txt`
```
pip show <package> (all the packages from requirements.txt)
PUT THE OUTPUT HERE. DON'T NEED TO PASTE requirements.txt
```

### Summary of the problem
fatal: [159.203.143.172]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Bad owner or permissions on /home/trantrungson/.ssh/config\r\n", "unreachable": true}

### Full log

PLAY RECAP *********************************************************************
159.203.143.172            : ok=0    changed=0    unreachable=1    failed=0
localhost                  : ok=20   changed=8    unreachable=0    failed=0

**Comment by dguido** [comment]
"Bad owner or permissions on /home/trantrungson/.ssh/config"

Please see the troubleshooting guide
