### ISSUE TITLE
host still unreachable

### ISSUE THREAD

**Issue by trantrungson** [trailofbits/algo#375]
### OS / Environment

Windows 10

### Version of components from `requirements.txt`
```
pip show <package> (all the packages from requirements.txt)
PUT THE OUTPUT HERE. DON'T NEED TO PASTE requirements.txt
```

### Full log

TASK [Check the system] ********************************************************
fatal: [159.203.143.172]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: Permanently added '159.203.143.172' (ECDSA) to the list of known hosts.\r\nPermission denied (publickey,password).\r\n", "unreachable": true}

PLAY RECAP *********************************************************************
159.203.143.172            : ok=0    changed=0    unreachable=1    failed=0
localhost                  : ok=20   changed=3    unreachable=0    failed=0

**Comment by dguido** [comment]
In order to file an issue, you must read the instructions and the troubleshooting guide, then follow the issue template when you file the issue.
