### ISSUE TITLE
[Feature] A way to block torrent traffic

### ISSUE THREAD

**Issue by talha-asad** [trailofbits/algo#379]
Algo VPN is super awesome, but a way to block torrent traffic would make it even better.

**Comment by dguido** [comment]
I'm not really certain I see the use case. It's your VPN, so you should just not open a torrent client while connected to it. How are you using Algo that you need this feature?

**Comment by deedeefink** [comment]
One argument is that in case the VPN is used for business purposes, you would want to block certain traffic from the company VPN
