### ISSUE TITLE
./algo: line 64: ansible-playbook: command not found

### ISSUE THREAD

**Issue by kfulk14** [trailofbits/algo#382]
### OS / Environment

Ec2 Instance US East (N. Virgina)

### Version of components from `requirements.txt`
```
pip show <package> (all the packages from requirements.txt)
PUT THE OUTPUT HERE. DON'T NEED TO PASTE requirements.txt
```
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

### Summary of the problem

Error occurs at the end of running ./algo

### The way of deployment (cloud or local)
cloud

### Expected behavior
Succesfull install

### Actual behavior
error displayed $ ./algo: line 64: ansible-playbook: command not found

**Comment by kfulk14** [comment]
Figure out need to install IPSEC VPN

**Comment by tuangd** [comment]
I have the same issue, but can't fix it. 
Can you help?

**Comment by kfulk14** [comment]
@tuangd I had to set up a IPSEC VPN server on my ubuntu machine then it worked here are the instructions I followed [https://raymii.org/s/tutorials/IPSEC_vpn_with_Ubuntu_16.04.html#Install_Strongswan](url)

**Comment by tuangd** [comment]
Thank you so much. I realized later that we are on different OS but thanks anyway. Mine is Windows10. ;P

**Comment by loganwedwards** [comment]
I am on MacOS and saw this when trying to setup Algo on EC2 (N. Virginia). Curiously, I did not see this issue when deploying to Digital Ocean.
