### ISSUE TITLE
add openssh upgrade info to mac os up to Yosemite in doc

### ISSUE THREAD

**Issue by takosuke** [trailofbits/algo#383]
### OS / Environment
OSX 10.10.5

Versions of OSX up to Yosemite include an older version of OpenSSH that can't make ed25519 keys, so playbook fails at generating SSH private keys task. Documentation should include an extra step for users of older OSX versions to upgrade openssh via homebrew via
```
tap homebrew/dupes
brew install openssl
brew install openssh
```

**Comment by dguido** [comment]
We don't support versions earlier than 10.11, sorry! But we will be dropping ed25519 keys.
