### ISSUE TITLE
Support Scaleway instances and API

### ISSUE THREAD

**Issue by ndtob** [trailofbits/algo#384]
I would like to consider adding support for Scaleway (https://www.scaleway.com) a cheap hosted service provider out of Europe that also supports hosting bare metal ARM servers on demand with an API:
https://developer.scaleway.com

**Comment by Nnyan** [comment]
I would love to see Scaleway supported.

**Comment by defunctio** [comment]
We rely on Ansible and [official cloud modules](https://docs.ansible.com/ansible/list_of_cloud_modules.html) for cloud deployments. Before we could implement support for Scaleway we would need to see support in Ansible. A cursory search shows no issues on the Ansible project or 3rd party projects in regards to this. If someone is interested in writing an ansible module for this provider, this might be a good opportunity. 

References:
* [Ansible module developer docs](https://docs.ansible.com/ansible/dev_guide/developing_modules.html)
* [Scaleway API docs](https://developer.scaleway.com/)

**Comment by gunph1ld** [comment]
I don't think it's a problem, I think it's an opportunity.
I used scaleway for a long time and ansible can handle it with the uri module

**Comment by defunctio** [comment]
I think the better solution to implement it with proper error checking and options in python as an ansible module but this is just my opinion. This could also be contributed back to ansible once finished.

**Comment by tarikd** [comment]
👍
