### ISSUE TITLE
Need help with TL-T600VPN router configuration

### ISSUE THREAD

**Issue by ireallydontexist** [trailofbits/algo#386]
Hi,

I know that routers are not officially supported but maybe some of you can help to find our to configure this router. I tried to find in the generated configs where the required parameters where hiding but not easy.

If I understand well, I first need to define an IKE policy:
* Policy Name: **algo ike policy**
* Exchange Mode: **Main** / Aggressive
* Authentication Algorithm: **AUTO** / MD5 / SHA1
* Encryption Algorithm: **AUTO** / DE**AUTO** / MD5 / SHA1S / 3DES / AES128 / AES192 / AES 256
* DH Group: DH1 / DH2 / DH5 ? **Which diffie-hellman-group ?**
* Pre-shared Key: **? I did not find any preshared key**
* SA Lifetime: **28800**
* DPD:	Enable    **Disable**

Then I could create an IPSEC policy:
* Policy Name: **algo policy**	
* Local Subnet: **? / ?** (I tried 192.168.0.0/24) 
* Remote Subnet: **algoserver Ip address** / **?**	
* Remote Gateway:	  **algoserver Ip address** (IP or domain name)
Exchange Mode:	**IKE**  /  Manual
Security Protocol:	AH / **ESP**
Authentication Algorithm: **AUTO** / MD5 / SHA1
Encryption Algorithm:  **AUTO** / NONE / DES / 3DES / AES128 / AES192 / AES 256		
IKE Security Policy:	   **algo ike policy** (see above)
PFS Group: NONE / DH1 / DH2 / DH5 **?**	
Lifetime:	**28800**
Status: **enable**	

I did not find where to set any certificate...

Any help VERY welcome....

-> User guides for the router: http://www.tp-link.com/lk/download/TL-R600VPN.html

**Comment by dguido** [comment]
I don't think this will work... You need to get it to use:

* Protocol: IKEv2
* Integrity: SHA2-256 (soon SHA2-512)
* Crypto: AES-GCM (or simply AES if you select our compat option)
* DH: Group 19 (or Group 14 with compat)
* PSK: We don't use PSK auth
* Certificate Auth: ECC certificate support (or RSA cert support with compat)
