### ISSUE TITLE
Special characters in Wifi name breaks mobileconfig files (MacOS & iOS)

### ISSUE THREAD

**Issue by tkrunning** [trailofbits/algo#388]
### OS / Environment

MacOS Sierra 10.12.4

### Version of components from `requirements.txt`
```
pip show <package> (all the packages from requirements.txt)
PUT THE OUTPUT HERE. DON'T NEED TO PASTE requirements.txt
```

### Summary of the problem
When adding wifi names with special characters (in my case & and !) during the setup process, both MacOS and iOS throw errors or do nothing when trying to install the .mobileconfig file

### Expected behavior
![screen shot 2017-04-11 at 4 05 19 pm](https://cloud.githubusercontent.com/assets/1646041/24916828/3981e55c-1ed3-11e7-9efa-6826429b00f6.png)

**Comment by gunph1ld** [comment]
@tkrunning check the patch, please
