### ISSUE TITLE
Digital ocean setup yields two droplets. Do both have to be running for VPN?

### ISSUE THREAD

**Issue by reckoner** [trailofbits/algo#389]
I got this running (it was straightforward) on  digital ocean, but now I have two droplets: the one I used to build algo and another one that algo created as the VPN. I can shutdown the first one (the one that I used to build algo), right?

Thanks! It works flawlessly on windows 10 client.

**Comment by defunctio** [comment]
Just be sure to grab the configs folder from the host you used to deploy algo with so you can configure the clients. If you don't need anything else from it, then it can be safely shut down.

**Comment by reckoner** [comment]
Thanks for your quick reply.  Quick question: if I snapshot and shutdown the VPN droplet and later spin it up again, it will have a new IP address. Does this mean I have to re-run the Powershell scripts again with the new IP address. Alternatively, I could destroy the VPN droplet and just create an entirely new VPN droplet. 

What do you recommend?

**Comment by dguido** [comment]
shut it down and make a new one
