### ISSUE TITLE
Windows 10 Mobile support

### ISSUE THREAD

**Issue by tabakerov** [trailofbits/algo#390]
### Summary of the problem
There is no way to run powershell script on Windows 10 Mobile device

### Steps to reproduce the behavior
Install Algo, deploy it, install certificates to W10M device (1703), try to connect - see "Policy error"

**Comment by dguido** [comment]
None of us have Windows 10 phones. It supports IKEv2, but I'm not sure about the cipher suite.

https://www.vpnuk.info/setup-windows-phone-10-ikev2.php

**Comment by tabakerov** [comment]
Could this be helpful?: 
- https://technet.microsoft.com/en-us/itpro/windows/keep-secure/vpn-guide
- https://technet.microsoft.com/en-us/itpro/windows/keep-secure/vpn-profile-options
- https://technet.microsoft.com/en-us/itpro/windows/keep-secure/vpn-connection-type
- https://technet.microsoft.com/library/ff687731.aspx

**Comment by dguido** [comment]
This is the most useful document:

* https://msdn.microsoft.com/windows/hardware/commercialize/customize/mdm/vpnv2-csp

It looks like it might support all the crypto we use, but someone needs to make a profile and test it. None of us have Windows 10 phones. If someone can create a profile using this spec and test it, I'd be happy to accept a PR to address this issue.

**Comment by tabakerov** [comment]
I have a W10M phone and some resources on Azure to provide VM if needed. But I'm a total novice in VPN profiles/ciphers/networking so I need clear instruction to try it out.

**Comment by BallistaMan** [comment]
Having the same policy error here. Would be happy to create the profile, but, like @tabakerov, I'd need some instruction on how to go about doing it.

**Comment by jauderho** [comment]
Looks like you may have to use something like Microsoft Intune to create an initial profile.

**Comment by dguido** [comment]
Ok this just is not going to happen.
