### ISSUE TITLE
Arch client configuration

### ISSUE THREAD

**Issue by cgiliberto** [trailofbits/algo#391]
Late last week the Algo folks reached out to me on Twitter about what I did to get Arch Linux working as a client. I've done a small (by no means comprehensive) writeup of what I did [here](https://github.com/cgiliberto/algo_arch)

Please note that I do not claim to be an infosec expert of any sort (I am a lowly undergraduate in mathematics), and may have horribly mangled something, so I make no claims to either completeness or correctness.

**Comment by gunph1ld** [comment]
If you can send a [PR](https://github.com/trailofbits/algo/pulls), please do!

**Comment by bshiznit** [comment]
Thank you @cgiliberto ! :)

**Comment by cgiliberto** [comment]
I'll submit a PR as soon as I get done with school stuff for this week, so on the weekend or Friday.

**Comment by cgiliberto** [comment]
I will also note a small difference I discovered when attempting to replicate. Attempting on another install, I needed to manually specify ciphers (e.g. as Galois counter mode aes + sha whatever + ECDH) in `client_ipsec.conf.j2` this time. I'll do a full debug as soon as I have a change so I can figure out why that differed between attempts before submitting my PR.

**Comment by dieManu** [comment]
thx for your writeup. Currently I also try to setup algo on Arch Linux and I thought I had installed strongswan correctly (I've done it as described on the strongswan instructions) but it seems that algo doesn't like it. I always get:

TASK [vpn: Install strongSwan]
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "failed to install strongswan"}

any ideas? I have no idea what to try else.

**Comment by dguido** [comment]
Closing this ticket since we're not going to support Arch officially in this version of Algo

**Comment by cgiliberto** [comment]
fwiw I gave up on Arch anyway out of frustration with other similar issues, so it's just as well. Currently using Algo on Windows, Ubuntu, and macOS.

**Comment by kamalhm** [comment]
I'm currently on arch and trying to install algo, is there any easier steps for me to follow?
