### ISSUE TITLE
How to update an existing algo installation to latest version?

### ISSUE THREAD

**Issue by ejheil** [trailofbits/algo#392]
### OS / Environment

MacOS Sierra => Digital Ocaean

### Version of components from `requirements.txt`
```
pip show <package> (all the packages from requirements.txt)
PUT THE OUTPUT HERE. DON'T NEED TO PASTE requirements.txt
```

### Summary of the problem

It would be helpful if the instructions indicated how, when, and whether to upgrade one's algo installation to take advantage of recent development.

### Steps to reproduce the behavior

Read the docs, didn't see anything related to this

**Comment by pguizeline** [comment]
Hi!

If you've selected the "Security Enhancements" role during deployment, the script will enable unattended-upgrades onto the server, enforcing automatic security updates onto the OS. But don't mix these updates with Algo updates, the unattended-upgrades are Ubuntu 16.04 LTS updates, not Algo.

If any chances are made on the Algo deployment scripts, like a new cipher suite for example, the best way is to destroy the Algo server and re-deploy.

Hope that helps with your question!

**Comment by ejheil** [comment]
Thank you, that's very helfpul!

I don't remember if I selected security enhancements -- this is my first usage of digitalocean -- I'll check on that.  But it's Algo updates I was concerned with.

Is there any way to know when/if there are vital updates to Algo which would necessitate destroying/re-deploying?  A mailing list or something?

And if I did destroy and re-deploy it, would I need to re-install the VPN in my devices for it to work again?

**Comment by pguizeline** [comment]
The best way to keep up with Algo development is by monitoring the pull requests and commits into the repository, if you see some important change, you can then trash and deploy a fresh server.

In case you are starting a new server, you need to go through the client install steps again, for every client, since the authentication depends on the server IP and certificate keys that are unique for every server.

**Comment by ejheil** [comment]
Thanks for the clarification!
