### ISSUE TITLE
EC2 Elastic IP

### ISSUE THREAD

**Issue by vouyang** [trailofbits/algo#394]
### OS / Environment

Amazon Linux AMI - EC2

### Summary of the problem
After the VPN EC2 instance has been automatically created after running ./algo, I am able to connect to the VPN using the public IP. However, if I try to assign an Elastic IP to the same instance, I cannot connect to the VPN. Rebooting the EC2 instance did not resolve the issue.

**Comment by dguido** [comment]
... Is this who I think it is? If so, hello!

Yes, the certificates are created for a single IP address (the one you started with). When you change the server IP, the certificates are essentially invalidated.

We would need to initially deploy the server on an Elastic IP. We may be able to handle this by being more clever during the install process.

**Comment by dguido** [comment]
Ah, there is an open PR to switch to using Elastic IPs. You can try testing it. We want to avoid defaulting to Elastic IPs though, since that incurs additional cost that is unnecessary for most users: https://github.com/trailofbits/algo/pull/385/files

**Comment by vouyang** [comment]
Thanks for the help! Just confirmed that the open PR is working. It was able to create an instance with an elastic IP. Also, there is no cost for Elastic IP addresses while in use.You only pay for the Elastic IP when it's not attached to an instance.

From AWS:
"To ensure efficient use of Elastic IP addresses, we impose a small hourly charge if an Elastic IP address is not associated with a running instance, or if it is associated with a stopped instance or an unattached network interface. While your instance is running, you are not charged for one Elastic IP address associated with the instance, but you are charged for any additional Elastic IP addresses associated with the instance."
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/elastic-ip-addresses-eip.html#eip-basics

**Comment by aboutte** [comment]
This can be closed....#385 has been merged.

**Comment by gunph1ld** [comment]
@aboutte #385 has not been merged and I'm going to implement EIP later
