### ISSUE TITLE
Link in README.MD To preinstall centos/red hat doc has a typo

### ISSUE THREAD

**Issue by robnee** [trailofbits/algo#396]

**Comment by dguido** [comment]
Can you submit a PR to fix it please?

**Comment by robnee** [comment]
I did just now.  It's a one character change but I'm not really a github expert so sorry if the PR isn't quite right procedurally

Rob

On Apr 13, 2017, at 18:42, Dan Guido <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you submit a PR to fix it please?

**Comment by dguido** [comment]
fixed
