### ISSUE TITLE
Copying keys to Strongswan directory fails due to wrong file path

### ISSUE THREAD

**Issue by robnee** [trailofbits/algo#406]
### OS / Environment

Linode Centos 7

### Ansible version

2.2.0.0

### Version of components from `requirements.txt`

Name: msrestazure
Version: 0.4.7
Requires: msrest, adal, keyring
---
Name: setuptools
Version: 34.4.1
Requires: six, appdirs, packaging
---
Name: ansible
Version: 2.2.0.0
Requires: paramiko, pycrypto, setuptools, PyYAML, jinja2
---
Name: dopy
Version: 0.3.5
Requires: requests
---
Name: boto
Version: 2.46.1
Requires:
---
Name: boto3
Version: 1.4.4
Requires: botocore, jmespath, s3transfer
---
Name: azure
Version: 2.0.0rc5
Requires: azure-storage, azure-servicemanagement-legacy, azure-servicebus, azure-mgmt, azure-graphrbac, azure-batch
---
Name: msrest
Version: 0.4.1
Requires: certifi, chardet, requests, isodate, keyring, enum34, requests-oauthlib
---
Name: six
Version: 1.10.0
Requires:
---
Name: pyOpenSSL
Version: 16.2.0
Requires: six, cryptography
---
Name: Jinja2
Version: 2.8
Requires: MarkupSafe

### Summary of the problem

Prep proceeds fine on Centos 7.  python 2.7 is default so upgrade from 2.6 is not needed.  Attempting a local install.  Fails with the following message:

TASK [vpn : Copy the keys to the strongswan directory] *************************
failed: [localhost] (item={u'dest': u'/etc/ipsec.d/cacerts/ca.crt', u'src': u'configs/45.33.95.120/pki/cacert.pem', u'group': u'root', u'mode': u'0600', u'owner': u'strongswan'}) => {"checksum": "0d61c7c86561d4715db742d0bb8af623ff1b56c3", "failed": true, "item": {"dest": "/etc/ipsec.d/cacerts/ca.crt", "group": "root", "mode": "0600", "owner": "strongswan", "src": "configs/45.33.95.120/pki/cacert.pem"}, "msg": "Destination directory /etc/ipsec.d/cacerts does not exist"}
failed: [localhost] (item={u'dest': u'/etc/ipsec.d/certs/45.33.95.120.crt', u'src': u'configs/45.33.95.120/pki/certs/45.33.95.120.crt', u'group': u'root', u'mode': u'0600', u'owner': u'strongswan'}) => {"checksum": "3b7a7b9627d393d549528da607bf42de14ef93cd", "failed": true, "item": {"dest": "/etc/ipsec.d/certs/45.33.95.120.crt", "group": "root", "mode": "0600", "owner": "strongswan", "src": "configs/45.33.95.120/pki/certs/45.33.95.120.crt"}, "msg": "Destination directory /etc/ipsec.d/certs does not exist"}
failed: [localhost] (item={u'dest': u'/etc/ipsec.d/private/45.33.95.120.key', u'src': u'configs/45.33.95.120/pki/private/45.33.95.120.key', u'group': u'root', u'mode': u'0600', u'owner': u'strongswan'}) => {"checksum": "78bc354d57824b4291cd063337546a7ba4565c02", "failed": true, "item": {"dest": "/etc/ipsec.d/private/45.33.95.120.key", "group": "root", "mode": "0600", "owner": "strongswan", "src": "configs/45.33.95.120/pki/private/45.33.95.120.key"}, "msg": "Destination directory /etc/ipsec.d/private does not exist"}

RUNNING HANDLER [vpn : restart strongswan] *************************************

PLAY RECAP *********************************************************************
localhost                  : ok=30   changed=18   unreachable=0    failed=1
  

The problem is that the following path is not present: /etc/ipsec.d  Those files *DO* appear to be present in /etc/strongswan:

[root strongswan]# pwd
/etc/strongswan
(env)
[root strongswan]# ls
ipsec.conf  ipsec.d  strongswan.conf  strongswan.d  swanctl

I do not know why the strongswan path is absent from the path being searched for.  It could be due to RedHat/Centos 7

### Steps to reproduce the behavior

Attempt install on RedHat 7/Centos 7

### The way of deployment (cloud or local)

local / localhost

### Expected behavior

reference ipsec.d in /etc/strongswan directory

### Actual behavior

attempt to reference ipsec.d in /etc

### Full log

[root@ algo-master]# ./algo

  What provider would you like to use?
    1. DigitalOcean
    2. Amazon EC2
    3. Microsoft Azure
    4. Google Compute Engine (only for testing, see issue #369)
    5. Install to existing Ubuntu 16.04 server

Enter the number of your desired provider
: 5

Enter the IP address of your server: (or use localhost for local installation)
: localhost

What user should we use to login on the server? (note: passwordless login required, or ignore if you're deploying to localhost)
[root]:

Enter the public IP address of your server: (IMPORTANT! This IP is used to verify the certificate)
[localhost]: xxxxxxxxxxxxxx

Was this server deployed by Algo previously?
[y/N]: n

Do you want macOS/iOS clients to enable "VPN On Demand" when connected to cellular networks?
[y/N]: y

Do you want macOS/iOS clients to enable "VPN On Demand" when connected to Wi-Fi?
[y/N]: y

List the names of trusted Wi-Fi networks (if any) that macOS/iOS clients exclude from using the VPN (e.g., your home network. Comma-separated value, e.g., HomeNet,OfficeWifi,AlgoWiFi)
:

Do you want to install a DNS resolver on this VPN server, to block ads while surfing?
[y/N]: n

Do you want each user to have their own account for SSH tunneling?
[y/N]:

Do you want to apply operating system security enhancements on the server? (warning: replaces your sshd_config)
[y/N]:

Do you want the VPN to support Windows 10 clients? (requires RSA certificates and key exchange, less secure)
[y/N]:

Do you want to retain the CA key? (required to add users in the future, but less secure)
[y/N]:

PLAY [Configure the server] ****************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Generate the SSH private key] ********************************************
ok: [localhost -> localhost]

TASK [Generate the SSH public key] *********************************************
ok: [localhost -> localhost]

TASK [Change mode for the SSH private key] *************************************
ok: [localhost -> localhost]

TASK [Ensure the dynamic inventory exists] *************************************
ok: [localhost]

TASK [Ensure the local ssh directory is exist] *********************************
skipping: [localhost]

TASK [Copy the algo ssh key to the local ssh directory] ************************
skipping: [localhost]

TASK [Configure the local ssh config] ******************************************
skipping: [localhost]

TASK [local : Add the instance to an inventory group] **************************
skipping: [localhost]

TASK [local : Add the instance to an inventory group] **************************
changed: [localhost]

TASK [local : set_fact] ********************************************************
ok: [localhost]

TASK [local : Ensure the group local exists in the dynamic inventory file] *****
ok: [localhost]

TASK [local : Populate the dynamic inventory] **********************************
ok: [localhost]

PLAY [Configure the server and install required software] **********************

TASK [Check the system] ********************************************************
changed: [localhost]

TASK [Ubuntu | Install prerequisites] ******************************************
skipping: [localhost]

TASK [FreeBSD / HardenedBSD | Install prerequisites] ***************************
skipping: [localhost]

TASK [FreeBSD / HardenedBSD | Configure defaults] ******************************
skipping: [localhost]

TASK [set_fact] ****************************************************************
skipping: [localhost]

TASK [common : Gather Facts] ***************************************************
ok: [localhost]

TASK [common : Loopback for services configured] *******************************
skipping: [localhost]

TASK [common : Loopback included into the network config] **********************
skipping: [localhost]

TASK [common : set_fact] *******************************************************
skipping: [localhost]

TASK [common : set_fact] *******************************************************
skipping: [localhost]

TASK [common : Loopback included into the rc config] ***************************
skipping: [localhost]

TASK [common : Enable the gateway features] ************************************
skipping: [localhost] => (item={u'value': u'"open"', u'param': u'firewall_type'})
skipping: [localhost] => (item={u'value': u'"YES"', u'param': u'firewall_enable'})
skipping: [localhost] => (item={u'value': u'"YES"', u'param': u'gateway_enable'})
skipping: [localhost] => (item={u'value': u'"YES"', u'param': u'natd_enable'})
skipping: [localhost] => (item={u'value': u'""', u'param': u'natd_interface'})
skipping: [localhost] => (item={u'value': u'"-dynamic -m"', u'param': u'natd_flags'})

TASK [common : Install tools] **************************************************

TASK [common : Sysctl tuning] **************************************************

TASK [vpn : Gather Facts] ******************************************************
ok: [localhost]

TASK [vpn : Enable IPv6] *******************************************************
ok: [localhost]

TASK [vpn : Generate password for the CA key] **********************************
changed: [localhost]

TASK [vpn : set_fact] **********************************************************
ok: [localhost]

TASK [vpn : Change the algorithm to RSA] ***************************************
skipping: [localhost]

TASK [vpn : Ensure that the strongswan group exist] ****************************
changed: [localhost]

TASK [vpn : Ensure that the strongswan user exist] *****************************
changed: [localhost]

TASK [vpn : set_fact] **********************************************************
skipping: [localhost]

TASK [vpn : Ubuntu | Install strongSwan] ***************************************
skipping: [localhost]

TASK [vpn : Ubuntu | Enforcing ipsec with apparmor] ****************************
skipping: [localhost] => (item=/usr/lib/ipsec/charon)
skipping: [localhost] => (item=/usr/lib/ipsec/lookip)
skipping: [localhost] => (item=/usr/lib/ipsec/stroke)

TASK [vpn : Ubuntu | Enable services] ******************************************
skipping: [localhost] => (item=apparmor)
skipping: [localhost] => (item=strongswan)
skipping: [localhost] => (item=netfilter-persistent)

TASK [vpn : Ubuntu | Ensure that the strongswan service directory exist] *******
skipping: [localhost]

TASK [vpn : Ubuntu | Setup the cgroup limitations for the ipsec daemon] ********
skipping: [localhost]

TASK [vpn : Iptables configured] ***********************************************
skipping: [localhost] => (item={u'dest': u'/etc/iptables/rules.v4', u'src': u'rules.v4.j2'})

TASK [vpn : Iptables configured] ***********************************************
skipping: [localhost] => (item={u'dest': u'/etc/iptables/rules.v6', u'src': u'rules.v6.j2'})

TASK [vpn : FreeBSD / HardenedBSD | Get the existing kernel parameters] ********
skipping: [localhost]

TASK [vpn : FreeBSD / HardenedBSD | Set the rebuild_needed fact] ***************
skipping: [localhost] => (item=IPSEC_NAT_T)
skipping: [localhost] => (item=IPSEC)
skipping: [localhost] => (item=crypto)

TASK [vpn : FreeBSD / HardenedBSD | Make the kernel config] ********************
skipping: [localhost]

TASK [vpn : FreeBSD / HardenedBSD | Ensure the all options are enabled] ********
skipping: [localhost] => (item=options  IPSEC)
skipping: [localhost] => (item=options IPSEC_NAT_T)
skipping: [localhost] => (item=device   crypto)

TASK [vpn : HardenedBSD | Determine the sources] *******************************
skipping: [localhost]

TASK [vpn : FreeBSD | Determine the sources] ***********************************
skipping: [localhost]

TASK [vpn : FreeBSD / HardenedBSD | Increase the git postBuffer size] **********
skipping: [localhost]

TASK [vpn : FreeBSD / HardenedBSD | Fetching the sources...] *******************
skipping: [localhost]

TASK [vpn : FreeBSD / HardenedBSD | Fetching the sources...] *******************
skipping: [localhost]

TASK [vpn : FreeBSD / HardenedBSD | The kernel is being built...] **************
skipping: [localhost]

TASK [vpn : FreeBSD / HardenedBSD | The kernel is being built...] **************
skipping: [localhost]

TASK [vpn : FreeBSD / HardenedBSD | Reboot] ************************************
skipping: [localhost]

TASK [vpn : FreeBSD / HardenedBSD | Enable strongswan] *************************
skipping: [localhost]

TASK [vpn : Install strongSwan] ************************************************
changed: [localhost]

TASK [vpn : Setup the config files from our templates] *************************
changed: [localhost] => (item={u'dest': u'/etc/strongswan.conf', u'src': u'strongswan.conf.j2', u'group': u'root', u'mode': u'0644', u'owner': u'root'})
changed: [localhost] => (item={u'dest': u'/etc/ipsec.conf', u'src': u'ipsec.conf.j2', u'group': u'root', u'mode': u'0644', u'owner': u'root'})
changed: [localhost] => (item={u'dest': u'/etc/ipsec.secrets', u'src': u'ipsec.secrets.j2', u'group': u'root', u'mode': u'0600', u'owner': u'strongswan'})

TASK [vpn : Get loaded plugins] ************************************************
changed: [localhost]

TASK [vpn : Disable unneeded plugins] ******************************************

TASK [vpn : Ensure that required plugins are enabled] **************************

TASK [vpn : Ensure the pki directory is not exist] *****************************
skipping: [localhost]

TASK [vpn : Ensure the pki directories are exist] ******************************
changed: [localhost -> localhost] => (item=ecparams)
changed: [localhost -> localhost] => (item=certs)
changed: [localhost -> localhost] => (item=crl)
changed: [localhost -> localhost] => (item=newcerts)
changed: [localhost -> localhost] => (item=private)
changed: [localhost -> localhost] => (item=reqs)

TASK [vpn : Ensure the files are exist] ****************************************
changed: [localhost -> localhost] => (item=.rnd)
changed: [localhost -> localhost] => (item=private/.rnd)
changed: [localhost -> localhost] => (item=index.txt)
changed: [localhost -> localhost] => (item=index.txt.attr)
changed: [localhost -> localhost] => (item=serial)

TASK [vpn : Generate the openssl server configs] *******************************
changed: [localhost -> localhost]

TASK [vpn : Build the CA pair] *************************************************
changed: [localhost -> localhost]

TASK [vpn : Copy the CA certificate] *******************************************
changed: [localhost -> localhost]

TASK [vpn : Generate the serial number] ****************************************
changed: [localhost -> localhost]

TASK [vpn : Build the server pair] *********************************************
changed: [localhost -> localhost]

TASK [vpn : Build the client's pair] *******************************************
changed: [localhost -> localhost] => (item=dan)
changed: [localhost -> localhost] => (item=jack)

TASK [vpn : Build the client's p12] ********************************************
changed: [localhost -> localhost] => (item=dan)
changed: [localhost -> localhost] => (item=jack)

TASK [vpn : Copy the p12 certificates] *****************************************
changed: [localhost -> localhost] => (item=dan)
changed: [localhost -> localhost] => (item=jack)

TASK [vpn : Copy the keys to the strongswan directory] *************************
failed: [localhost] (item={u'dest': u'/etc/ipsec.d/cacerts/ca.crt', u'src': u'configs/45.33.95.120/pki/cacert.pem', u'group': u'root', u'mode': u'0600', u'owner': u'strongswan'}) => {"checksum": "0d61c7c86561d4715db742d0bb8af623ff1b56c3", "failed": true, "item": {"dest": "/etc/ipsec.d/cacerts/ca.crt", "group": "root", "mode": "0600", "owner": "strongswan", "src": "configs/45.33.95.120/pki/cacert.pem"}, "msg": "Destination directory /etc/ipsec.d/cacerts does not exist"}
failed: [localhost] (item={u'dest': u'/etc/ipsec.d/certs/45.33.95.120.crt', u'src': u'configs/45.33.95.120/pki/certs/45.33.95.120.crt', u'group': u'root', u'mode': u'0600', u'owner': u'strongswan'}) => {"checksum": "3b7a7b9627d393d549528da607bf42de14ef93cd", "failed": true, "item": {"dest": "/etc/ipsec.d/certs/45.33.95.120.crt", "group": "root", "mode": "0600", "owner": "strongswan", "src": "configs/45.33.95.120/pki/certs/45.33.95.120.crt"}, "msg": "Destination directory /etc/ipsec.d/certs does not exist"}
failed: [localhost] (item={u'dest': u'/etc/ipsec.d/private/45.33.95.120.key', u'src': u'configs/45.33.95.120/pki/private/45.33.95.120.key', u'group': u'root', u'mode': u'0600', u'owner': u'strongswan'}) => {"checksum": "78bc354d57824b4291cd063337546a7ba4565c02", "failed": true, "item": {"dest": "/etc/ipsec.d/private/45.33.95.120.key", "group": "root", "mode": "0600", "owner": "strongswan", "src": "configs/45.33.95.120/pki/private/45.33.95.120.key"}, "msg": "Destination directory /etc/ipsec.d/private does not exist"}

RUNNING HANDLER [vpn : restart strongswan] *************************************

PLAY RECAP *********************************************************************
localhost                  : ok=30   changed=18   unreachable=0    failed=1

**Comment by dguido** [comment]
We only support Algo installs to Ubuntu 16.04

**Comment by robnee** [comment]
Is this something I could help get working?  I might just need a little direction as it seems it might be a small change?

Rob

On Apr 14, 2017, at 10:02, Dan Guido <notifications@github.com<mailto:notifications@github.com>> wrote:


We only support Algo installs to Ubuntu 16.04

**Comment by gunph1ld** [comment]
Will be implemented in 1.1 #227

**Comment by dguido** [comment]
Sorry, I just had to come back to this. The install script itself says this:

https://github.com/trailofbits/algo/blob/master/algo#L386

**Comment by robnee** [comment]
I know I was just hoping it would work so I tried it and when I saw that it was stuck on something minor I thought I would ask.

Rob

On Apr 16, 2017, at 13:26, Dan Guido <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorry, I just had to come back to this. The install script itself says this:

https://github.com/trailofbits/algo/blob/master/algo#L386
