### ISSUE TITLE
Installation fails with pip error.

### ISSUE THREAD

**Issue by daveloyall** [trailofbits/algo#409]
### OS / Environment
Debian 8 / AWS EC2

### Ansible version
    admin@somehost:~/algo-master$ ansible --version
    -bash: ansible: command not found

### Version of components from `requirements.txt`
    admin@somehost:~/algo-master$ for i in `sed 's/[=>].*//g' requirements.txt`; do pip show $i; done
    ---
    Name: setuptools
    Version: 5.5.1
    Location: /usr/lib/python2.7/dist-packages
    Requires: 
    ---
    Name: boto
    Version: 2.34.0
    Location: /usr/lib/python2.7/dist-packages
    Requires: 
    ---
    Name: six
    Version: 1.8.0
    Location: /usr/lib/python2.7/dist-packages
    Requires: 
    admin@somehost:~/algo-master$ 
    

### Summary of the problem
Step 4 in https://github.com/trailofbits/algo/blob/master/README.md fails with this error:

    admin@somehost:~/algo-master$ python -m virtualenv env && source env/bin/activate && python -m pip install -r requirements.txt
    Running virtualenv with interpreter /usr/bin/python2
    New python executable in env/bin/python2
    Also creating executable in env/bin/python
    Installing setuptools, pip...done.
    Downloading/unpacking msrestazure (from -r requirements.txt (line 1))
      Downloading msrestazure-0.4.7-py2.py3-none-any.whl
    Cleaning up...
    Exception:
    Traceback (most recent call last):
      File "/home/admin/algo-master/env/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
        status = self.run(options, args)
      File "/home/admin/algo-master/env/local/lib/python2.7/site-packages/pip/commands/install.py", line 290, in run
        requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
      File "/home/admin/algo-master/env/local/lib/python2.7/site-packages/pip/req.py", line 1266, in prepare_files
        req_to_install.extras):
      File "/home/admin/algo-master/env/lib/python-wheels/setuptools-5.5.1-py2.py3-none-any.whl/pkg_resources.py", line 2401, in requires
        dm = self._dep_map
      File "/home/admin/algo-master/env/lib/python-wheels/setuptools-5.5.1-py2.py3-none-any.whl/pkg_resources.py", line 2597, in _dep_map
        self.__dep_map = self._compute_dependencies()
      File "/home/admin/algo-master/env/lib/python-wheels/setuptools-5.5.1-py2.py3-none-any.whl/pkg_resources.py", line 2621, in _compute_dependencies
        parsed = next(parse_requirements(distvers))
      File "/home/admin/algo-master/env/lib/python-wheels/setuptools-5.5.1-py2.py3-none-any.whl/pkg_resources.py", line 49, in <lambda>
        next = lambda o: o.next()
      File "/home/admin/algo-master/env/lib/python-wheels/setuptools-5.5.1-py2.py3-none-any.whl/pkg_resources.py", line 2721, in parse_requirements
        "version spec")
      File "/home/admin/algo-master/env/lib/python-wheels/setuptools-5.5.1-py2.py3-none-any.whl/pkg_resources.py", line 2686, in scan_list
        raise ValueError(msg, line, "at", line[p:])
    ValueError: ('Expected version spec in', 'msrest ~=0.4.4', 'at', ' ~=0.4.4')
    
    Storing debug log for failure in /home/admin/.pip/pip.log
    

### Steps to reproduce the behavior

Blindly follow the README.md instructions.

### The way of deployment (cloud or local)
AWS EC2.

### Expected behavior

Installation finished.

### Actual behavior

Installation failed.

### Full log
Here's pip.log:

    Downloading/unpacking msrestazure (from -r requirements.txt (line 1))
      Getting page https://pypi.python.org/simple/msrestazure/
      URLs to search for versions for msrestazure (from -r requirements.txt (line 1)):
      * https://pypi.python.org/simple/msrestazure/
      Analyzing links from page https://pypi.python.org/simple/msrestazure/
        Skipping https://pypi.python.org/packages/00/7f/46a801f0322f49915202e99360872f61c41bb4fe817fdc1b5478c2e33657/msrestazure-0.2.1-py3-none-any.whl#md5=8bc7c495e51f000aa8d248399181e4b4 (from https://pypi.python.org/simple/msrestazure/) because it is not compatible with this Python
        Found link https://pypi.python.org/packages/04/66/4eb7d85850bf0177a01a722b0ab16214af5922c396666d8fc264bfd59902/msrestazure-0.1.1.zip#md5=435abb768b170f764f8e65e8f1fa3500 (from https://pypi.python.org/simple/msrestazure/), version: 0.1.1
        Found link https://pypi.python.org/packages/04/67/8ab1713acc26d666008ec4fc62815adf6aef611a553e74d181f851a13cdf/msrestazure-0.4.7.zip#md5=4a3c9506ebcc9a78685d78c8beab90eb (from https://pypi.python.org/simple/msrestazure/), version: 0.4.7
        Found link https://pypi.python.org/packages/04/d2/ba1a6b03fce53af172b61b91c7fd8dd324ba36aba3841cf43aad731649f3/msrestazure-0.4.0-py2-none-any.whl#md5=e6bc1ea2714fed8262d9e2ac66f536b4 (from https://pypi.python.org/simple/msrestazure/), version: 0.4.0
        Found link https://pypi.python.org/packages/0b/0e/4c59c6194cd498596faecaf948383d9d6fb06c4ff8317949dc60766f72cf/msrestazure-0.2.0.zip#md5=806866e872b2db5bdab4e5c1575f17bd (from https://pypi.python.org/simple/msrestazure/), version: 0.2.0
        Skipping https://pypi.python.org/packages/0e/28/a81bc8e4f2e936297175be8cf2a183e2c458b689a1c969f007a56c0996c0/msrestazure-0.1.0-py3-none-any.whl#md5=6b3e1f19a71306bb8f5c697e5d9f518d (from https://pypi.python.org/simple/msrestazure/) because it is not compatible with this Python
        Found link https://pypi.python.org/packages/0f/52/bfac1fca0e86d334a28424d43c2db08f9f658572699a7021b4233a2a1e7e/msrestazure-0.2.1.zip#md5=160f96c4b09150ad53120ebca9cbd421 (from https://pypi.python.org/simple/msrestazure/), version: 0.2.1
        Found link https://pypi.python.org/packages/18/ba/18c1fb6598333af1741cafa1588b6f0ee213063cd5a9db65449b0220a5a1/msrestazure-0.4.3-py2-none-any.whl#md5=492e4d0d83cf5e0dbf8c2f7e9ae83501 (from https://pypi.python.org/simple/msrestazure/), version: 0.4.3
        Skipping https://pypi.python.org/packages/1d/16/9d677fe7114ed4469d24042b9e13520433a310798cbe985e89d0a68a1b21/msrestazure-0.1.1-py3-none-any.whl#md5=fdef9dc3ba477bf4c39add8dc527d4f8 (from https://pypi.python.org/simple/msrestazure/) because it is not compatible with this Python
        Found link https://pypi.python.org/packages/22/49/e12fe90d5869eb6bfee308a21865d4dbaffea834f1d495166a073c353d5f/msrestazure-0.4.5.zip#md5=9ebcfe09076154cbf97e3eace66e91f2 (from https://pypi.python.org/simple/msrestazure/), version: 0.4.5
        Skipping https://pypi.python.org/packages/3f/59/6acaa3ca77f3a9fd35faef49c3eb96ae5a0f2080b123b60611fc3324071b/msrestazure-0.0.2-py3-none-any.whl#md5=fcec710bcf27bec56d1d9e0135c2b228 (from https://pypi.python.org/simple/msrestazure/) because it is not compatible with this Python
        Found link https://pypi.python.org/packages/44/49/b28ffffaf3e2bebefcdd795cfc54eaffd0edc4fd5a46a1c145fe31d3eacc/msrestazure-0.0.1-py2-none-any.whl#md5=046994cc4f9fd4f71b7abf80e435a366 (from https://pypi.python.org/simple/msrestazure/), version: 0.0.1
        Found link https://pypi.python.org/packages/4a/5b/63ff13883afcb3280a4f4ac542ca991d54869ce0611c07c47b6dca33229a/msrestazure-0.4.2-py2-none-any.whl#md5=eefd278b101efdf8f0ba8a9fe30772bd (from https://pypi.python.org/simple/msrestazure/), version: 0.4.2
        Found link https://pypi.python.org/packages/4b/ab/80b82f94f040615721aad663ff98082fe8bb6ed4af71d68d30d5a11904a0/msrestazure-0.1.2.zip#md5=5268bf0b1f6c896928c719e59286e80d (from https://pypi.python.org/simple/msrestazure/), version: 0.1.2
        Found link https://pypi.python.org/packages/51/b0/b395df993d674dd67031af25d13e679b2cdcdeda6ae8eedf69df43560a93/msrestazure-0.4.3.zip#md5=6a078e9b8f8eb97e0889b2b95274543f (from https://pypi.python.org/simple/msrestazure/), version: 0.4.3
        Found link https://pypi.python.org/packages/5a/32/2a4956b4893b44b3d9c0ed6ba59468b0b1cc9444e6c8f46433005d9e8b4c/msrestazure-0.4.1.zip#md5=3523a4a87e02a950b08d460a0aa70d25 (from https://pypi.python.org/simple/msrestazure/), version: 0.4.1
        Found link https://pypi.python.org/packages/62/88/b89889731b0d1f5f17eb0013de958cfb1a79898373f365dc1d72e39fb40c/msrestazure-0.4.6.zip#md5=bbd822548de78aebd00c7c54669707d1 (from https://pypi.python.org/simple/msrestazure/), version: 0.4.6
        Found link https://pypi.python.org/packages/64/18/8b22a1a29bb14007975a8076d1bc5090d359552b056fd0a808ac6f32fdc6/msrestazure-0.1.0.zip#md5=fbc9148fb90a4f5b06fe4db5cb809390 (from https://pypi.python.org/simple/msrestazure/), version: 0.1.0
        Skipping https://pypi.python.org/packages/6f/aa/6bfb32133ac07ede25cc86c11ccb43a4627734bf87fad41f2f585ce00b5e/msrestazure-0.1.2-py3-none-any.whl#md5=18b5cf1b6d47f9cde919256d501b3547 (from https://pypi.python.org/simple/msrestazure/) because it is not compatible with this Python
        Found link https://pypi.python.org/packages/71/7e/b28a42938246e704bc63607f6898f3723c7c36fa5e5f12b68e4600440d4e/msrestazure-0.4.1-py2-none-any.whl#md5=961058bb1e8128f67d1bae186af8388f (from https://pypi.python.org/simple/msrestazure/), version: 0.4.1
        Skipping https://pypi.python.org/packages/75/27/caa54089d72bcb05f29d7c7a91940763f6c2237d16e776b2393ccad4140d/msrestazure-0.4.3-py3-none-any.whl#md5=334a5ae31a1fcf9962fe7556ddd29b5d (from https://pypi.python.org/simple/msrestazure/) because it is not compatible with this Python
        Found link https://pypi.python.org/packages/75/a6/189eb7b315f33c9ece79d47b460bbd07a0a38e20c2d120f095d4a9322e78/msrestazure-0.3.0-py2-none-any.whl#md5=629255611eef41feee2016061cc5a02e (from https://pypi.python.org/simple/msrestazure/), version: 0.3.0
        Skipping https://pypi.python.org/packages/7f/99/cd553dced29f9e8d917672379465d4355e10d023615dc1d5b0decb83accf/msrestazure-0.4.2-py3-none-any.whl#md5=058412f8a7269298b584d29d8d7ceedd (from https://pypi.python.org/simple/msrestazure/) because it is not compatible with this Python
        Found link https://pypi.python.org/packages/80/f8/a25b1c3c19b8e1079840cc80d97b8616052f0342480524b644fea2367b8c/msrestazure-0.0.2-py2-none-any.whl#md5=c10c2a8f6224fb9859a34eee5c99c457 (from https://pypi.python.org/simple/msrestazure/), version: 0.0.2
        Skipping https://pypi.python.org/packages/83/b2/02376ebdd7074d041ab662560832e9f43b3ec67b435b8bde10a8cd9d922a/msrestazure-0.4.0rc1-py3-none-any.whl#md5=db278006012e29a990d6202a2e7b2664 (from https://pypi.python.org/simple/msrestazure/) because it is not compatible with this Python
        Skipping https://pypi.python.org/packages/85/a0/bceeb8ebdb34dba4b566bcc4e9adb2ef325b6bdfc15b72ed76a8cbc6d077/msrestazure-0.0.1-py3-none-any.whl#md5=abba047aab68ecc0389497515830ebb9 (from https://pypi.python.org/simple/msrestazure/) because it is not compatible with this Python
        Found link https://pypi.python.org/packages/88/4e/133596577a891b7ba6128dbbb77404d42c6796d06315ec771bd3c003503d/msrestazure-0.4.0rc1.zip#md5=e06c79a451fd5dbe6cf7b29831b0f011 (from https://pypi.python.org/simple/msrestazure/), version: 0.4.0rc1
        Found link https://pypi.python.org/packages/8b/44/01c7c2903010243222d3bee3d06069408955bed0042c005959e1c5280581/msrestazure-0.2.0-py2-none-any.whl#md5=99c7384deaf255e51676b619ce074812 (from https://pypi.python.org/simple/msrestazure/), version: 0.2.0
        Found link https://pypi.python.org/packages/8e/c9/76d41ba464c15300604dd98e1f5c0613198c6be37381e67df107dca1cd7e/msrestazure-0.4.4-py2-none-any.whl#md5=91d27431ffea6de08ec18ff3aa170f62 (from https://pypi.python.org/simple/msrestazure/), version: 0.4.4
        Found link https://pypi.python.org/packages/99/19/a66c7fbe7140d97e85122fa4f64e94542981c83de44f7671d695ff4caead/msrestazure-0.1.1-py2-none-any.whl#md5=72c1680a972d36af2dec1c880d60a34c (from https://pypi.python.org/simple/msrestazure/), version: 0.1.1
        Found link https://pypi.python.org/packages/99/5c/ca28fa1679ed00eec135b04a9e64fb68d52e426f15230c16a09269c18fba/msrestazure-0.4.6-py2.py3-none-any.whl#md5=1cce3ad7d78fbe77da9b184c7c5514c4 (from https://pypi.python.org/simple/msrestazure/), version: 0.4.6
        Found link https://pypi.python.org/packages/9b/fb/452ec3ec09bd35a3eb15e949700572153654a59adcd63672a8aba4d9416b/msrestazure-0.2.1-py2-none-any.whl#md5=2bf6d23adf4478ffde6228359660601c (from https://pypi.python.org/simple/msrestazure/), version: 0.2.1
        Found link https://pypi.python.org/packages/a5/57/4a5a016fb9a4f9c834247c48db20c1d5d89d2e1c4fc20eaccbc9a1a99619/msrestazure-0.1.2-py2-none-any.whl#md5=2c3c03df22c43a784336ef987db9acb4 (from https://pypi.python.org/simple/msrestazure/), version: 0.1.2
        Skipping https://pypi.python.org/packages/b2/89/3f3d31659fa6ebbe8337307f97fda8183537eabb776924c13f1e0ed0fcba/msrestazure-0.4.4-py3-none-any.whl#md5=d6c9851e7567829bea8aafb27eee8037 (from https://pypi.python.org/simple/msrestazure/) because it is not compatible with this Python
        Found link https://pypi.python.org/packages/b5/9b/706d60f17519b4aa8e1720ae1acdc474c88436cb9cbae5f7914c21b34d67/msrestazure-0.0.2.zip#md5=587f84609f49085ec201bc24d8c7e6c0 (from https://pypi.python.org/simple/msrestazure/), version: 0.0.2
        Found link https://pypi.python.org/packages/b6/c0/c83add10219b367a8a539b0b42051415fa5f85456c9a5424a72b47d934c8/msrestazure-0.4.0.zip#md5=bb8f2e95b6fd277d2156688dedbf586e (from https://pypi.python.org/simple/msrestazure/), version: 0.4.0
        Found link https://pypi.python.org/packages/b9/d9/cf6e6620bf3416896dcd5bdef5312e1836a4a2eed589ee580a2190d7f569/msrestazure-0.1.0-py2-none-any.whl#md5=40658b00034c6684b7f4925d289a2b38 (from https://pypi.python.org/simple/msrestazure/), version: 0.1.0
        Found link https://pypi.python.org/packages/ba/ae/5784c408ac093d4d8fc81315d77d666096f7da0120e41b9274005bb04ebb/msrestazure-0.4.0rc1-py2-none-any.whl#md5=1d38ae842bf7233f5cdfee200c65d10c (from https://pypi.python.org/simple/msrestazure/), version: 0.4.0rc1
        Found link https://pypi.python.org/packages/c2/d3/2270df7b3fb408ac4e208cb659978a07633e0d5c415ffd4d201885004db8/msrestazure-0.3.0.zip#md5=fc62b958627b79b5898f691fdcb3e8be (from https://pypi.python.org/simple/msrestazure/), version: 0.3.0
        Skipping https://pypi.python.org/packages/c5/ac/5453785f8429002c0354fac5259e97142cd74962ef60065b0a4f5628aa99/msrestazure-0.2.0-py3-none-any.whl#md5=26b933a486eb332b2b90928ae84f92f7 (from https://pypi.python.org/simple/msrestazure/) because it is not compatible with this Python
        Skipping https://pypi.python.org/packages/d3/37/6bf15f4e322bd2aa84ed98630a6e265f04784e40124aac5dae2e000553b0/msrestazure-0.4.1-py3-none-any.whl#md5=dfcb31ef2126de4db8bc38f91b447dc6 (from https://pypi.python.org/simple/msrestazure/) because it is not compatible with this Python
        Skipping https://pypi.python.org/packages/d6/0e/bc8ccfd6d04fcf18a49b093d534520f5533a0a71d66b3cb9845ecba1acb6/msrestazure-0.3.0-py3-none-any.whl#md5=667a7331cbe12d969e2bf9dabb9e484e (from https://pypi.python.org/simple/msrestazure/) because it is not compatible with this Python
        Found link https://pypi.python.org/packages/d9/96/fabd9eca171979f16f3a61c88820f6e35f9ea312c4156b3996fbf5487a51/msrestazure-0.4.5-py2.py3-none-any.whl#md5=2646718a5b3a4f0c41f64149f68c222e (from https://pypi.python.org/simple/msrestazure/), version: 0.4.5
        Found link https://pypi.python.org/packages/da/93/cef502197b335b69c6aacd27d0a69fde2ce2f184f1f9a94e92cd978b186f/msrestazure-0.4.4.zip#md5=61bbd45e53b7130ce0c11b545067b60e (from https://pypi.python.org/simple/msrestazure/), version: 0.4.4
        Found link https://pypi.python.org/packages/dd/66/5539b9024edb221f5fb4f82d397b88e73ba31b85ef97e791de665d69a9bd/msrestazure-0.4.2.zip#md5=ebdde7cd19f135badd0286edf3cc66c7 (from https://pypi.python.org/simple/msrestazure/), version: 0.4.2
        Found link https://pypi.python.org/packages/e4/ac/6e0dff597bcd87895346143d74785e51321b34aa52455ba3133aaf170aea/msrestazure-0.0.1.tar.gz#md5=4cdbb7d42c4814fd87c75eb9bfafe9ed (from https://pypi.python.org/simple/msrestazure/), version: 0.0.1
        Skipping https://pypi.python.org/packages/ea/c3/06fb015f30b86c0316cefd14836a33221467771a68ed5c3a6fe9b3e79c7a/msrestazure-0.4.0-py3-none-any.whl#md5=4468f0bb92ad2ca680e9cb2f22dace4e (from https://pypi.python.org/simple/msrestazure/) because it is not compatible with this Python
        Found link https://pypi.python.org/packages/f0/1c/2f3feb5aed4316919e72c32710a5f531f8fca3a17da173dd02f91f11c4a5/msrestazure-0.4.7-py2.py3-none-any.whl#md5=cbd5173358a66b8e646db490f6750585 (from https://pypi.python.org/simple/msrestazure/), version: 0.4.7
      Ignoring link https://pypi.python.org/packages/88/4e/133596577a891b7ba6128dbbb77404d42c6796d06315ec771bd3c003503d/msrestazure-0.4.0rc1.zip#md5=e06c79a451fd5dbe6cf7b29831b0f011 (from https://pypi.python.org/simple/msrestazure/), version 0.4.0rc1 is a pre-release (use --pre to allow).
      Ignoring link https://pypi.python.org/packages/ba/ae/5784c408ac093d4d8fc81315d77d666096f7da0120e41b9274005bb04ebb/msrestazure-0.4.0rc1-py2-none-any.whl#md5=1d38ae842bf7233f5cdfee200c65d10c (from https://pypi.python.org/simple/msrestazure/), version 0.4.0rc1 is a pre-release (use --pre to allow).
      Using version 0.4.7 (newest of versions: 0.4.7, 0.4.7, 0.4.6, 0.4.6, 0.4.5, 0.4.5, 0.4.4, 0.4.4, 0.4.3, 0.4.3, 0.4.2, 0.4.2, 0.4.1, 0.4.1, 0.4.0, 0.4.0, 0.3.0, 0.3.0, 0.2.1, 0.2.1, 0.2.0, 0.2.0, 0.1.2, 0.1.2, 0.1.1, 0.1.1, 0.1.0, 0.1.0, 0.0.2, 0.0.2, 0.0.1, 0.0.1)
      Downloading msrestazure-0.4.7-py2.py3-none-any.whl
      Downloading from URL https://pypi.python.org/packages/f0/1c/2f3feb5aed4316919e72c32710a5f531f8fca3a17da173dd02f91f11c4a5/msrestazure-0.4.7-py2.py3-none-any.whl#md5=cbd5173358a66b8e646db490f6750585 (from https://pypi.python.org/simple/msrestazure/)
    Cleaning up...
    Exception:
    Traceback (most recent call last):
      File "/home/admin/algo-master/env/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
        status = self.run(options, args)
      File "/home/admin/algo-master/env/local/lib/python2.7/site-packages/pip/commands/install.py", line 290, in run
        requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
      File "/home/admin/algo-master/env/local/lib/python2.7/site-packages/pip/req.py", line 1266, in prepare_files
        req_to_install.extras):
      File "/home/admin/algo-master/env/lib/python-wheels/setuptools-5.5.1-py2.py3-none-any.whl/pkg_resources.py", line 2401, in requires
        dm = self._dep_map
      File "/home/admin/algo-master/env/lib/python-wheels/setuptools-5.5.1-py2.py3-none-any.whl/pkg_resources.py", line 2597, in _dep_map
        self.__dep_map = self._compute_dependencies()
      File "/home/admin/algo-master/env/lib/python-wheels/setuptools-5.5.1-py2.py3-none-any.whl/pkg_resources.py", line 2621, in _compute_dependencies
        parsed = next(parse_requirements(distvers))
      File "/home/admin/algo-master/env/lib/python-wheels/setuptools-5.5.1-py2.py3-none-any.whl/pkg_resources.py", line 49, in <lambda>
        next = lambda o: o.next()
      File "/home/admin/algo-master/env/lib/python-wheels/setuptools-5.5.1-py2.py3-none-any.whl/pkg_resources.py", line 2721, in parse_requirements
        "version spec")
      File "/home/admin/algo-master/env/lib/python-wheels/setuptools-5.5.1-py2.py3-none-any.whl/pkg_resources.py", line 2686, in scan_list
        raise ValueError(msg, line, "at", line[p:])
    ValueError: ('Expected version spec in', 'msrest ~=0.4.4', 'at', ' ~=0.4.4')

**Comment by sydsyd** [comment]
I encountered this in the last 12 hours too.
Same step in guide, on a Debian Droplet on DigitalOcean
Gave up and installed it on MacOS 10.12.4 without error.

**Comment by gmittal** [comment]
Try updating to the latest version of ```pip```. That solved the issue for me.

**Comment by daveloyall** [comment]
I was using my distro's latest pip when I got the error message above.

Following your advice, maybe, I tried upgrading pip's copy of pip.  I ended up with root's copy being upgraded, but I wasn't able to upgrade my user's copy.

After that I deleted the instance.  I'll start over later.

My goal is to start this VM: https://aws.amazon.com/marketplace/fulfillment?productId=39d3917e-ff4e-4597-848e-4d0fdf8529e6 and then follow algo's README.md blindly, and get a working VPN out of it.

If you folks think that's a worthy goal, I'll help you alter the README.md until it works.  ...It's unfortunate that I don't know anything about python, or ansible, or pip, or virtualenv...

I do know a bit about AWS and Debian, though! ;)

**Comment by bshiznit** [comment]
Have a look at the steps kiratp mentions here... U basically update pip and install all of the requirements from requirements.txt outside the virtualenv.
https://github.com/trailofbits/algo/issues/369

**Comment by Aaron-B-Carter** [comment]
Ran into the same problem. Tried updating pip before doing step 4 and I still got the same error. So I tried installing the dependencies directly, and it all went well until I got this error:

> Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-hV0sKa/pycparser/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-8JOyV9-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-hV0sKa/pycparser/

I'll admit I barely understand what I'm doing here, so any help would be appreciated

**Comment by gmittal** [comment]
@daveloyall what version of python are you using?

**Comment by titan49ermbp** [comment]
I'm a newbie so I'm not sure if this is the right thread but after declining to retain the CA key, I get the following message during install:

./algo: line 73: ansible-playbook: command not found

What do I do next?

**Comment by gmittal** [comment]
Run ```pip install -r requirements.txt``` inside the virtualenv and run the script again. Your ansible dependency is not built.

**Comment by titan49ermbp** [comment]
Sorry, I don't understand -- again, total newbie -- but how do I go inside the virtualenv? Thanks.
