### ISSUE TITLE
Ubuntu desktop 17.04 Network manager not able to connect (as a client)

### ISSUE THREAD

**Issue by mathew19** [trailofbits/algo#418]
### OS / Environment

NA

### Version of components from `requirements.txt`

NA

### Summary of the problem
I upgraded to Ubuntu 17.04 hoping to use the network manager. I'm still able to connect via command line. However through the NM interface, I'm not able to get anything working. I'm using the user.crt, user.key; for the gateway I tried the <ip>.crt, user.crt, no certificate, the various .pem files; nothing seems to work

Any ideas? I haven't seen anything online either after some googling.

**Comment by dguido** [comment]
Yep, Network Manager does not support AES-GCM. We have an open ticket:

https://github.com/trailofbits/algo/issues/263
