### ISSUE TITLE
Add support for the now.sh cloud provider

### ISSUE THREAD

**Issue by psifertex** [trailofbits/algo#434]
### OS / Environment
nowhere right now, I'd /like/ to be able to run it on [now.sh](https://now.sh) though. 

### Ansible version
n/a

### Version of components from `requirements.txt`
n/a

### Summary of the problem
Would like to be able to deploy via now.sh

### Steps to reproduce the behavior
Try to run on now.sh

### The way of deployment (cloud or local)
```get clone https://github.com/trailofbits/algo
cd algo
now
```

### Expected behavior
```Ready! https://algo-hflkj21a.now.sh
```

### Actual behavior
I haven't actually tried, it definitely won't do the right thing since `now.sh` requires either a `Dockerfile` or a `package.json`

**Comment by marclipovsky** [comment]
👍

**Comment by dguido** [comment]
We don't support Docker-based deploys and package.json is for Node apps? How would this even work?
