### ISSUE TITLE
Unable to reach websites from OpenSUSE Linux client

### ISSUE THREAD

**Issue by hirozed** [trailofbits/algo#436]
### OS / Environment
Ubuntu 16.04 VPS on OVH hosting

### Ansible version
ansible 2.2.0.0

### Version of components from `requirements.txt`
Name: msrestazure
Version: 0.4.7
Name: setuptools
Version: 35.0.0
Name: ansible
Version: 2.2.0.0
Name: dopy
Version: 0.3.5
Name: boto
Version: 2.46.1
Name: boto3
Version: 1.4.4
Name: msrest
Version: 0.4.1
Name: apache-libcloud
Version: 1.5.0
Name: six
Version: 1.10.0
Name: pyOpenSSL
Version: 16.2.0
Name: Jinja2
Version: 2.8

### Summary of the problem
I have successfully set up Algo on an Ubuntu 16.04 server.  My iOS & OS X devices connect and can access the the internet without issue.  

Connecting via my Linux box (OpenSUSE Tumbleweed) through Network Manager fails.  I have installed Algo with Windows 10 settings, introducing the weaker encryption.  I'm honestly not sure if I am using the correct certificates, but I tried different ones.

Going via strongswan directly, connects to the server, but I don't seem to have access to DNS.  I can ping ip addresses, but not domain names.  

Since I have had better success via command line strongswan, that might be a better route to go.  I can provide any other information you need.

### Steps to reproduce the behavior
Set up a linux box and try connecting via Network Manager or strongswan cli.

### The way of deployment (cloud or local)
Local

### Expected behavior
Connect to VPN and successfully ping a domain.

### Actual behavior
Pinging returns nothing, not even an error message.  Pinging via IP goes through

### Full log
The installation itself seems sound, I unfortunately do not have the log.

Any help you can provide would be fantastic.

-Jim

**Comment by dguido** [comment]
As far as I can tell, OpenSuse Tumbleweed uses Network Manager 1.4.1 (https://software.opensuse.org/package/NetworkManager-strongswan) which is the same as every other current Linux distribution (Debian Stretch, Fedora 25, Ubuntu 17.04, etc). We have many reports of these Linux distributions working fine as long as you're not using AES-GCM (which Network Manager 1.4.1 does not support). I don't think this is a bug with Algo. You may want to join our Slack for helping troubleshooting this issue.

**Comment by molecularswords** [comment]
This is the same problem I have in Fedora 25 (see [#300](https://github.com/trailofbits/algo/issues/300)). I can ping IPs but not domains when connecting through the strongswan cli, and I can't connect at all through NetworkManager. Has there been any resolution to this?

**Comment by hirozed** [comment]
I haven't had the opportunity to get back to it.  I'm planning on hitting the slack channel this weekend and see if I can get some help.
