### ISSUE TITLE
Modular cloud provider support

### ISSUE THREAD

**Issue by defunctio** [trailofbits/algo#446]
I would really like to see cloud provider roles re-implemented in a provider agnostic modular design where the use of variables and options in roles are normalized. With this design there should be no portion of the Algo installation process that relies on details from provisioning the host. Templates can be generated for use in the development of community supported providers that can be loaded dynamically. 

This would benefit us in several ways
- Allow the core team to provide higher level of support and maintenance for the core cloud providers.
- Cloud provider module versioning without altering the core code base.
- Provide a template that promotes community developed and maintained cloud provider modules that can be contributed back to ansible.
- Minimize requirements with dynamic installation and loading of only desired providers. 
- An Algo cloud provider plugin repository. 

This should be considered during the implementation of #360.

**Comment by dguido** [comment]
See here: https://github.com/trailofbits/algo/issues/79#issuecomment-289852597

**Comment by dguido** [comment]
Saving this for a new major version
