### ISSUE TITLE
Add instructions for unsupported cloud providers

### ISSUE THREAD

**Issue by gunph1ld** [trailofbits/algo#451]
We have to add some instruction about how to check whether the vps is compatible with algo for unsupported cloud providers.

**Comment by gunph1ld** [comment]
Some related links:
https://wiki.strongswan.org/projects/strongswan/wiki/KernelModules

**Comment by hailigsblechle** [comment]
It would be nice to know which kinds of virtual server hypervisors (i.e. [OpenVZ](https://en.wikipedia.org/wiki/OpenVZ), [XEN](https://en.wikipedia.org/wiki/Xen), [KVM](https://en.wikipedia.org/wiki/Kernel-based_Virtual_Machine)) are supported in general or at least theoretically.
