### ISSUE TITLE
Cannot connect to on demand public networks that require login

### ISSUE THREAD

**Issue by adamoren** [trailofbits/algo#452]
### OS / Environment
Latest iOS

### Ansible version
N/A

### Version of components from `requirements.txt`
N/A

### Summary of the problem
The issue is with connecting on demand. when I'm connected (automaticaly) to a public wifi, it takes me to a landing page, but since the phone tries to connect to the VPN on demand on that wifi, it will fail until I click on the landing page, which makes it impossible to connect to that wi-fi network.

### Steps to reproduce the behavior

1. set your VPN to connect on demand
2. Use your iPhone to connect to a public wifi with a landing page

### The way of deployment (cloud or local)
either

### Expected behavior
the landing page will load using the cellular network and then switch to the VPN once it can connect to the VPN.

### Actual behavior
The landing page won't load because the VPN is being connected to immediately.

**Comment by dguido** [comment]
We merged a change a few days ago that alleviates this issue. The mobileconfig now comes with a URLStringProbe defined. iOS devices will attempt to load the URL defined in the URLStringProbe (Apple's hotspot-detect.html file). If it cannot load, the VPN will wait to connect. Try modifying your mobileconfig -- you can either redeploy, hand modify the files, or modify them in configurator. There are no server changes required.
