### ISSUE TITLE
Policy match error

### ISSUE THREAD

**Issue by hamishr** [trailofbits/algo#453]
### OS / Environment
Windows 10 Build 14393.953

### Summary of the problem
Algo setup using the latest download results in a "Policy match error" on Windows 10.

Using an older version of Algo (from April 17 PST) there is no "Policy match error".

### Steps to reproduce the behavior
Set up Algo using latest download. 

Algo configuration changes don't appear to make a difference.
This is being tested on a VM which is rolled back to a base configuration each time.

### The way of deployment (cloud or local)
Cloud (DigitalOcean SFO2)

### Expected behavior
Windows should be able to connect to Algo.

### Actual behavior
Windows cannot connect to Algo.

**Comment by gunph1ld** [comment]
Related to https://github.com/trailofbits/algo/commit/8e5e6d50884cab651ace243d1e0685082150a8db

**Comment by tony199555** [comment]
I too have this problem with the creator update. Any temporary solution to work around this?

**Comment by dguido** [comment]
Oops, I guess we have to set this back. Stupid Windows :/

**Comment by dguido** [comment]
@gun
