### ISSUE TITLE
Windows: Ability to undo/reverse everything

### ISSUE THREAD

**Issue by tony199555** [trailofbits/algo#454]
For now, that is a relatively easy way to add VPN. But to remove VPN plus all the CA Cert is bit more complicated. (At least for me)

So I wonder if we should add a powershell script that does exactly the opposite of the currently-implemented ps1.

P.S. Is there a easier way to run ps1 without run command first.

**Comment by gunph1ld** [comment]
@tony199555 Can you check the PR #510 ?

**Comment by tony199555** [comment]
@gunph1ld Yes, will do. Thank you.

**Comment by tony199555** [comment]
For run ps1 without the set-execution I have figure out how using a bat file. Here is the code I use:
```
@echo off

powershell set-executionpolicy %1 -Scope CurrentUser
```
just run 
```
$name.bat unrestricted/restricted
```

Maybe this could add into the code for ease of running.

P.S. For one time usage to run ps1 just do

```
@echo off

powershell set-executionpolicy unrestricted $user.ps1
```
