### ISSUE TITLE
Algo VPN through http proxy (windows client)

### ISSUE THREAD

**Issue by tiliarou** [trailofbits/algo#455]
### OS / Environment
Windows 7 x64 (client)

### Summary of the problem
Clients are connecting to the Internet via an authenticated http/s proxy, leaving only certain ports open.
With this setup, the VPN as setup in windows (client) is not able to go through the http proxy first, and thus cannot reach the VPN server. How can I specify in windows (client) that the VPN has to connect via the http proxy ?
IE, chrome, FF are able to recognize the proxy automatically and ask for username and password as expected, but the built in windows VPN is not able to connect via the proxy.

### The way of deployment (cloud or local)
cloud (Aruba), Ubuntu 16.04 Server

**Comment by dguido** [comment]
https://superuser.com/questions/842109/how-to-connect-to-vpn-through-proxy-server
