### ISSUE TITLE
Add FAQ about IPSEC not being backdoored

### ISSUE THREAD

**Issue by dguido** [trailofbits/algo#460]
Uninformed people think that IPSEC is backdoored. It's not (obviously). tqbf had a great writeup on Hacker News about it once and I need to find it.

https://twitter.com/tqbf/statuses/812756616353292288

**Comment by withzombies** [comment]
https://news.ycombinator.com/item?id=13251385

**Comment by Thermi** [comment]
Can we get that onto the strongSwan wiki, too? Then it's upstream as well.

**Comment by jackivanov** [comment]
I think it's [here](https://github.com/trailofbits/algo/blob/master/docs/faq.md#wasnt-ipsec-backdoored-by-the-us-government) already
