### ISSUE TITLE
Invalid payload received when connecting from Windows 10

### ISSUE THREAD

**Issue by wiiind** [trailofbits/algo#462]
### OS / Environment

Windows 10 Build 15063.138

### Summary of the problem
VPN connection from Windows 10 results in "Invalid payload received" error for both Azure and AWS on commit b94b455aba081e3fc4d35378253e61b9c01c3243. Older version of Algo (commit a5ea5d8bb5ffba78293224bd1f3e4af3fc92d378 from April 13 EST) didn't have this problem.

### Steps to reproduce the behavior
Set up Algo fresh on a new provider following the instructions. Connect from a windows 10 machine. (Mac and iOS works just fine with the mobileconfig)

### The way of deployment (cloud or local)
cloud

### Expected behavior
Be able to connect on windows 10

### Actual behavior
Not be able to connect on windows 10

**Comment by dguido** [comment]
None of the Algo developers use Windows. Can you try and track down the source of this issue?

**Comment by dguido** [comment]
(doing this from memory -- some modification may be required) You can SSH to the Algo server, `service ipsec stop`, then `ipsec start --nofork` to get a log of what happens when Windows connects on the server side.

**Comment by wiiind** [comment]
Will give that a shot and get some logs when I get home and have the ssh key!

**Comment by m52go** [comment]
I just had this issue. Running `service ipsec stop` returned `Failed to stop ipsec.service: Unit ipsec.service not loaded.

I can say that I'm running 10.0.14393, and my Android device set up just fine. I'm running Algo on DigitalOcean set up with the bundled scripts just following the directions.

I know very little about what's going on, but I poked around and found what I could. Maybe it's helpful, maybe it isn't. 

1. Full Windows error code is ERROR_IPSEC_IKE_INVALID_PAYLOAD13843 (0x3613) Invalid payload received. We already knew most of this, so not very helpful.

2. Logs from the Algo server's `/var/log/syslog`. Again, not sure if it's any help, but I've included output that seems like it may be meaningful. yy is Algo IP, and xx is my home IP.

```
Apr 21 23:29:16 bore2v charon: 13[IKE] received end entity cert "CN=bob"
Apr 21 23:29:16 bore2v charon: 13[CFG] looking for peer configs matching yy.yy.yy.yy[%any]...xx.xx.xx.xx[CN=bob]
Apr 21 23:29:16 bore2v charon: 13[CFG]   candidate "ikev2-pubkey", match: 1/1/28 (me/other/ike)
Apr 21 23:29:16 bore2v charon: 13[CFG] selected peer config 'ikev2-pubkey'
Apr 21 23:29:16 bore2v charon: 13[CFG]   using certificate "CN=bob"
Apr 21 23:29:16 bore2v charon: 13[CFG]   certificate "CN=bob" key: 2048 bit RSA
Apr 21 23:29:16 bore2v charon: 13[CFG]   using trusted ca certificate "CN=yy.yy.yy.yy"
Apr 21 23:29:16 bore2v charon: 13[CFG] checking certificate status of "CN=bob"
Apr 21 23:29:16 bore2v charon: 13[CFG] ocsp check skipped, no ocsp found
Apr 21 23:29:16 bore2v charon: 13[CFG] certificate status is not available
Apr 21 23:29:16 bore2v charon: 13[CFG]   certificate "CN=yy.yy.yy.yy" key: 2048 bit RSA
Apr 21 23:29:16 bore2v charon: 13[CFG]   reached self-signed root ca with a path length of 0
Apr 21 23:29:16 bore2v charon: 13[IKE] authentication of 'CN=bob' with RSA signature successful
Apr 21 23:29:16 bore2v charon: 13[IKE] processing INTERNAL_IP4_ADDRESS attribute
Apr 21 23:29:16 bore2v charon: 13[IKE] processing INTERNAL_IP4_DNS attribute
Apr 21 23:29:16 bore2v charon: 13[IKE] processing INTERNAL_IP4_NBNS attribute
Apr 21 23:29:16 bore2v charon: 13[IKE] processing INTERNAL_IP4_SERVER attribute
Apr 21 23:29:16 bore2v charon: 13[IKE] processing INTERNAL_IP6_ADDRESS attribute
Apr 21 23:29:16 bore2v charon: 13[IKE] processing INTERNAL_IP6_DNS attribute
Apr 21 23:29:16 bore2v charon: 13[IKE] processing INTERNAL_IP6_SERVER attribute
Apr 21 23:29:16 bore2v charon: 13[IKE] peer supports MOBIKE
Apr 21 23:29:16 bore2v charon: 13[IKE] authentication of 'yy.yy.yy.yy' (myself) with RSA signature successful
Apr 21 23:29:16 bore2v charon: 13[IKE] IKE_SA ikev2-pubkey[6] established between yy.yy.yy.yy[yy.yy.yy.yy]...xx.xx.xx.xx[CN=bob]
Apr 21 23:29:16 bore2v charon: 13[IKE] IKE_SA ikev2-pubkey[6] state change: CONNECTING => ESTABLISHED
Apr 21 23:29:16 bore2v charon: 13[IKE] sending end entity cert "CN=yy.yy.yy.yy"
Apr 21 23:29:16 bore2v charon: 13[IKE] peer requested virtual IP %any
Apr 21 23:29:16 bore2v charon: 13[CFG] reassigning offline lease to 'CN=bob'
Apr 21 23:29:16 bore2v charon: 13[IKE] assigning virtual IP 10.19.48.3 to peer 'CN=bob'
Apr 21 23:29:16 bore2v charon: 13[IKE] peer requested virtual IP %any6
Apr 21 23:29:16 bore2v charon: 13[CFG] reassigning offline lease to 'CN=bob'
Apr 21 23:29:16 bore2v charon: 13[IKE] building INTERNAL_IP4_DNS attribute
Apr 21 23:29:16 bore2v charon: 13[CFG] looking for a child config for 0.0.0.0/0 ::/0 === 0.0.0.0/0 ::/0
Apr 21 23:29:16 bore2v charon: 13[CFG] proposing traffic selectors for us:
Apr 21 23:29:16 bore2v charon: 13[CFG]  0.0.0.0/0
Apr 21 23:29:16 bore2v charon: 13[CFG]  ::/0
Apr 21 23:29:16 bore2v charon: 13[CFG] proposing traffic selectors for other:
Apr 21 23:29:16 bore2v charon: 13[CFG]  10.19.48.3/32
Apr 21 23:29:16 bore2v charon: 13[CFG]  fd9d:bc11:4020::3/128
Apr 21 23:29:16 bore2v charon: 13[CFG]   candidate "ikev2-pubkey" with prio 15+3
Apr 21 23:29:16 bore2v charon: 13[CFG] found matching child config "ikev2-pubkey" with prio 18
Apr 21 23:29:16 bore2v charon: 13[CFG] found matching child config "ikev2-pubkey" with prio 18
Apr 21 23:29:16 bore2v charon: 13[CFG] selecting proposal:
Apr 21 23:29:16 bore2v charon: 13[CFG]   no acceptable ENCRYPTION_ALGORITHM found
Apr 21 23:29:16 bore2v charon: 13[CFG] selecting proposal:
Apr 21 23:29:16 bore2v charon: 13[CFG]   no acceptable PSEUDO_RANDOM_FUNCTION found
Apr 21 23:29:16 bore2v charon: 13[CFG] selecting proposal:
Apr 21 23:29:16 bore2v charon: 13[CFG]   no acceptable PSEUDO_RANDOM_FUNCTION found
Apr 21 23:29:16 bore2v charon: 13[CFG] received proposals: ESP:AES_CBC_128/HMAC_SHA2_256_128/NO_EXT_SEQ
Apr 21 23:29:16 bore2v charon: 13[CFG] configured proposals: ESP:AES_GCM_16_128/ECP_256/NO_EXT_SEQ, ESP:AES_CBC_128/HMAC_SHA2_512_256/PRF_HMAC_SHA2_512/ECP_256/NO_EXT_SEQ, ESP:AES_CBC_128/HMAC_SHA
2_256_128/PRF_HMAC_SHA2_256/MODP_2048/NO_EXT_SEQ
Apr 21 23:29:16 bore2v charon: 13[IKE] no acceptable proposal found
Apr 21 23:29:16 bore2v charon: 13[IKE] failed to establish CHILD_SA, keeping IKE_SA
Apr 21 23:29:16 bore2v charon: 13[ENC] generating IKE_AUTH response 1 [ IDr CERT AUTH CPRP(ADDR ADDR6 DNS) N(MOBIKE_SUP) N(ADD_4_ADDR) N(ADD_6_ADDR) N(NO_PROP) ]
Apr 21 23:29:16 bore2v charon: 13[NET] sending packet: from yy.yy.yy.yy[4500] to xx.xx.xx.xx[4500] (1344 bytes)
Apr 21 23:29:16 bore2v charon: 05[NET] sending packet: from yy.yy.yy.yy[4500] to xx.xx.xx.xx[4500]
Apr 21 23:29:16 bore2v charon: 13[MGR] checkin IKE_SA ikev2-pubkey[6]
Apr 21 23:29:16 bore2v charon: 13[MGR] check-in of IKE_SA successful.
Apr 21 23:29:16 bore2v charon: 08[NET] received packet: from xx.xx.xx.xx[4500] to yy.yy.yy.yy[4500]
Apr 21 23:29:16 bore2v charon: 08[NET] waiting for data on sockets
Apr 21 23:29:16 bore2v charon: 12[MGR] checkout IKE_SA by message
Apr 21 23:29:16 bore2v charon: 12[MGR] IKE_SA ikev2-pubkey[6] successfully checked out
Apr 21 23:29:16 bore2v charon: 12[NET] received packet: from xx.xx.xx.xx[4500] to yy.yy.yy.yy[4500] (80 bytes)
Apr 21 23:29:16 bore2v charon: 12[ENC] parsed INFORMATIONAL request 2 [ D ]
Apr 21 23:29:16 bore2v charon: 12[IKE] received DELETE for IKE_SA ikev2-pubkey[6]
Apr 21 23:29:16 bore2v charon: 12[IKE] deleting IKE_SA ikev2-pubkey[6] between yy.yy.yy.yy[yy.yy.yy.yy]...xx.xx.xx.xx[CN=bob]
Apr 21 23:29:16 bore2v charon: 12[IKE] IKE_SA ikev2-pubkey[6] state change: ESTABLISHED => DELETING
Apr 21 23:29:16 bore2v charon: 12[IKE] IKE_SA deleted
Apr 21 23:29:16 bore2v charon: 12[ENC] generating INFORMATIONAL response 2 [ ]
Apr 21 23:29:16 bore2v charon: 12[NET] sending packet: from yy.yy.yy.yy[4500] to xx.xx.xx.xx[4500] (80 bytes)
Apr 21 23:29:16 bore2v charon: 12[MGR] checkin and destroy IKE_SA ikev2-pubkey[6]
Apr 21 23:29:16 bore2v charon: 12[IKE] IKE_SA ikev2-pubkey[6] state change: DELETING => DESTROYING
Apr 21 23:29:16 bore2v charon: 12[CFG] lease fd9d:bc11:4020::3 by 'CN=bob' went offline
Apr 21 23:29:16 bore2v charon: 12[CFG] lease 10.19.48.3 by 'CN=bob' went offline
Apr 21 23:29:16 bore2v charon: 12[MGR] check-in and destroy of IKE_SA successful
Apr 21 23:29:16 bore2v charon: 05[NET] sending packet: from yy.yy.yy.yy[4500] to xx.xx.xx.xx[4500]
Apr 21 23:29:46 bore2v charon: 14[MGR] checkout IKE_SA
```

**Comment by m52go** [comment]
Looks like y'all already made progress on this with #464...should've looked closer before responding.

**Comment by wiiind** [comment]
I can't seem to get pass the authentication with my ssh password when I issue the command "service ipsec stop". Here's the error log. I am guessing I did something really stupid just didn't realize it.

ubuntu@algo:~$ service ipsec stop
==== AUTHENTICATING FOR org.freedesktop.systemd1.manage-units ===
Authentication is required to stop 'ipsec.service'.
Authenticating as: Ubuntu (ubuntu)
Password: 
polkit-agent-helper-1: pam_authenticate failed: Authentication failure
==== AUTHENTICATION FAILED ===
Failed to stop ipsec.service: Access denied
See system logs and 'systemctl status ipsec.service' for details.

**Comment by tccack** [comment]
I need some help with this also.
I get the "invalid payload received" also.
I have ssh into the Algo server on digital ocean and stopped and started ipsec service
No errors noted there, but still nothing working at my windows 10 VPN.
Used the ps1 script to install the VPN which returned no errors. Also tried creating the VPN manually but this failed also.
Created several droplets/reran Algo several times as per the instructions and created the necessary certs and keys etc.

Not sure where to go. I'm not very familiar with linux stuff ( I can follow instructions though :-) )
Windows build is 14393.1066 64bit (perhaps this is the issue?)

**Comment by dguido** [comment]
> ubuntu@algo:~$ service ipsec stop

sudo service ipsec stop

**Comment by wiiind** [comment]
I cherry-picked the commit bd91f6606832399118aaf0e4860bb75c578dd1f2 from the pull request that would supposedly fix this issue. But I got the error in the screenshot below instead. 
![capture](https://cloud.githubusercontent.com/assets/1924587/25307087/094dcad8-2769-11e7-88ad-b5de1d2ba883.PNG)

When I ssh in and tried to get the log, I got this.
```
ubuntu@algo:~$ sudo service ipsec stop
Failed to stop ipsec.service: Unit ipsec.service not loaded.
```

**Comment by dguido** [comment]
@wiiind You didn't install the certificates correctly. You should check the directions again.

@m52go Thanks! This is the important line from that log:

```
Apr 21 23:29:16 bore2v charon: 13[CFG] received proposals:
ESP:AES_CBC_128/HMAC_SHA2_256_128/NO_EXT_SEQ

Apr 21 23:29:16 bore2v charon: 13[CFG] configured proposals:
ESP:AES_GCM_16_128/ECP_256/NO_EXT_SEQ
ESP:AES_CBC_128/HMAC_SHA2_512_256/PRF_HMAC_SHA2_512/ECP_256/NO_EXT_SEQ
ESP:AES_CBC_128/HMAC_SHA
2_256_128/PRF_HMAC_SHA2_256/MODP_2048/NO_EXT_SEQ
```

We have a few cipher-related problems to work on. We're working on it in #464

**Comment by Starz0r** [comment]
I was going to open a new issue for this same problem, but I decided to bump this issue instead, with some new information as well.

I decided to run a test, installed Algo on a Ubuntu 16.04.2 instance, did all the step required from this [article](https://github.com/trailofbits/algo/blob/master/docs/deploy-to-ubuntu.md), and copied the required files for a Windows VPN Connection. Upon storing the Certification in the proper Certification Storage, and running the Powershell script in a elevated console, I still received the "Invalid Payload" error.

When following the steps in the [Android](https://github.com/trailofbits/algo/blob/master/docs/client-android.md) Setup, there were no issues, and I was able to connect successfully without a problem.

This might be useful to @dguido to track down this issue, since I'm running Windows 10 on Redstone 2, it might only apply to Windows 10 users that have recently updated their Operating System.

**Comment by gunph1ld** [comment]
Windows support is broken in the master branch, some changes will come from #464, you can check it

**Comment by dguido** [comment]
Thanks, but what we need right now is the magic PowerShell incantation to get it to use the default cipher suite (AES-GCM 128, SHA2-512 PRF, and ECP256 DH with ECP certificates). That's in #464. If you find a way to get it to work, give us a shout.
