### ISSUE TITLE
iOS 10.3.2 Beta 3 Profile installation fails

### ISSUE THREAD

**Issue by marclipovsky** [trailofbits/algo#467]
### OS / Environment
MacOS Sierra 10.12.4 (16E195)
iOS 10.3.2 Beta 3 (14F5080a)

### Ansible version
ansible 2.2.0.0

### Version of components from `requirements.txt`
Name: setuptools
Version: 34.3.3
Summary: Easily download, build, install, upgrade, and uninstall Python packages
Home-page: https://github.com/pypa/setuptools
Author: Python Packaging Authority
Author-email: distutils-sig@python.org
License: UNKNOWN
Location: /Users/marclipovsky/Code/algo/env/lib/python2.7/site-packages
Requires: six, appdirs, packaging
Name: ansible
Version: 2.2.0.0
Summary: Radically simple IT automation
Home-page: http://ansible.com/
Author: Ansible, Inc.
Author-email: info@ansible.com
License: GPLv3
Location: /Users/marclipovsky/Code/algo/env/lib/python2.7/site-packages
Requires: paramiko, pycrypto, PyYAML, setuptools, jinja2
Name: dopy
Version: 0.3.5
Summary: Python client for the Digital Ocean API
Home-page: https://github.com/devo-ps/dopy
Author: Vincent Viallet
Author-email: vincent@devo.ps
License: The MIT License (MIT)
Location: /Users/marclipovsky/Code/algo/env/lib/python2.7/site-packages
Requires: requests
Name: boto
Version: 2.46.1
Summary: Amazon Web Services Library
Home-page: https://github.com/boto/boto/
Author: Mitch Garnaat
Author-email: mitch@garnaat.com
License: MIT
Location: /Users/marclipovsky/Code/algo/env/lib/python2.7/site-packages
Requires:
Name: boto3
Version: 1.4.4
Summary: The AWS SDK for Python
Home-page: https://github.com/boto/boto3
Author: Amazon Web Services
Author-email: UNKNOWN
License: Apache License 2.0
Location: /Users/marclipovsky/Code/algo/env/lib/python2.7/site-packages
Requires: botocore, jmespath, s3transfer
Name: azure
Version: 2.0.0rc5
Summary: Microsoft Azure Client Libraries for Python
Home-page: https://github.com/Azure/azure-sdk-for-python
Author: Microsoft Corporation
Author-email: ptvshelp@microsoft.com
License: MIT License
Location: /Users/marclipovsky/Code/algo/env/lib/python2.7/site-packages
Requires: azure-mgmt, azure-servicebus, azure-storage, azure-servicemanagement-legacy, azure-batch, azure-graphrbac
Name: msrest
Version: 0.4.1
Summary: AutoRest swagger generator Python client runtime.
Home-page: https://github.com/xingwu1/autorest/tree/python/ClientRuntimes/Python/msrest
Author: Microsoft Corporation
Author-email: UNKNOWN
License: MIT License
Location: /Users/marclipovsky/Code/algo/env/lib/python2.7/site-packages
Requires: isodate, requests, requests-oauthlib, certifi, chardet, keyring, enum34
Name: six
Version: 1.10.0
Summary: Python 2 and 3 compatibility utilities
Home-page: http://pypi.python.org/pypi/six/
Author: Benjamin Peterson
Author-email: benjamin@python.org
License: MIT
Location: /Users/marclipovsky/Code/algo/env/lib/python2.7/site-packages
Requires:
Name: pyOpenSSL
Version: 16.2.0
Summary: Python wrapper module around the OpenSSL library
Home-page: https://pyopenssl.readthedocs.io/
Author: Hynek Schlawack
Author-email: hs@ox.cx
License: Apache License, Version 2.0
Location: /Users/marclipovsky/Code/algo/env/lib/python2.7/site-packages
Requires: six, cryptography
Name: Jinja2
Version: 2.8
Summary: A small but fast and easy to use stand-alone template engine written in pure python.
Home-page: http://jinja.pocoo.org/
Author: Armin Ronacher
Author-email: armin.ronacher@active-4.com
License: BSD
Location: /Users/marclipovsky/Code/algo/env/lib/python2.7/site-packages
Requires: MarkupSafe

### Summary of the problem
Adding profile to MacOS works fine, VPN starts and internet connection is established. In iOS 10.3.2 Beta 3, installation itself fails with a message "The container "xxxxx.p12" must contain only one certificate and it's private key." See screenshot.
![img_bd81da9f2be7-1](https://cloud.githubusercontent.com/assets/112484/25302073/e2a40eb2-26e9-11e7-8321-04f2df3d9a3f.jpeg)

### Steps to reproduce the behavior
Ran algo command and selected
- AWS
- Virgina region
- no to on demand
- Saved CA file for updating users
- no to DNS level ad filtering
- no to windows setup

### The way of deployment (cloud or local)
Cloud - AWS

### Expected behavior
Should be able to install algo vpn profile on iOS 10.3.2 Beta 3

### Actual behavior
Error message during install algo vpn profile on iOS 10.3.2 Beta 3

**Comment by gunph1ld** [comment]
https://github.com/trailofbits/algo/issues/328
