### ISSUE TITLE
Systems aren't pingable

### ISSUE THREAD

**Issue by davidemyers** [trailofbits/algo#475]
Based on `rules.v4` and `rules.v6` it looks like the intention is for deployed systems to respond to external pings in a rate-limited fashion, but I believe for this to work the rules as written must end in `-j ACCEPT`.

**Comment by gunph1ld** [comment]
I see no reason to make it pingable

**Comment by dguido** [comment]
Can you describe more about the issue davidemyers?

**Comment by davidemyers** [comment]
The issue is that it looks like you want deployed systems to be pingable, but the rules you include don't accomplish this. I'm assuming since you went to the trouble of creating those rate-limited rules you had your reasons for wanting pings to work.

If you don't want systems to be pingable that's fine too, and I'll just have to live with not getting a perfect 20 out of 20 score when I visit http://ipv6-test.com. :-)

**Comment by dguido** [comment]
Sorry, I get what you're saying but can you excerpt the relevant rules from our iptables script and reference them here? It was a goal of ours to go through all of them and document the purpose behind each, but we haven't gotten there yet.

**Comment by Thermi** [comment]
"-A INPUT -p icmp --icmp-type echo-request -m hashlimit --hashlimit-upto 5/s --hashlimit-mode srcip --hashlimit-srcmask 32 --hashlimit-name icmp-echo-drop -j DROP" 
must use the `ACCEPT` target.
Similiar rule in `rules.v6` must call the `ACCEPT` target, too.

**Comment by davidemyers** [comment]
In [rules.v4.j2](https://github.com/trailofbits/algo/blob/master/roles/vpn/templates/rules.v4.j2), the rule I'm referring to is:
`-A INPUT -p icmp --icmp-type echo-request -m hashlimit --hashlimit-upto 5/s --hashlimit-mode srcip --hashlimit-srcmask 32 --hashlimit-name icmp-echo-drop -j DROP`

In [rules.v6.j2](https://github.com/trailofbits/algo/blob/master/roles/vpn/templates/rules.v6.j2) it's:
`-A INPUT -p icmpv6 --icmpv6-type echo-request -m hashlimit --hashlimit-upto 5/s --hashlimit-mode srcip --hashlimit-srcmask 32 --hashlimit-name icmp-echo-drop -j DROP`

I think these both need to end in `ACCEPT` to work as intended. Or get rid of them if you don't want ping responses. Or better yet comment them out so they can easily be added back if desired.

**Comment by FiloSottile** [comment]
Thanks, had top patch the saved iptables to get a tunnelbroker.net tunnel (which insists on pinging you).
