### ISSUE TITLE
Can't stay connected

### ISSUE THREAD

**Issue by machito** [trailofbits/algo#476]
### OS / Environment
macOS 10.12.4 - Python 2.7.10
Ubuntu 16.04.2 x64 on Digital Ocean

### Ansible version
ansible 2.2.0.0

### Version of components from `requirements.txt`
msrestazure 0.4.7
setuptools 35.0.1
ansible 2.2.0.0
dopy 0.3.5
boto 2.46.1
boto3 1.4.4
azure 2.0.0rc5
msrest 0.4.1
apache-libcloud 1.5.0
six 1.10.0
pyOpenSSL 17.0.0
Jinja2 2.8

### Summary of the problem
Can't stay connected for more than a second.

### Steps to reproduce the behavior
Click "Connect" in Network preferences pane

### The way of deployment (cloud or local)
Cloud

### Expected behavior
Stay connected.

### Actual behavior
Attempts to connect, says connected for 1 second, then disconnects.

### Full log
PLAY [Configure the server] ****************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Generate the SSH private key] ********************************************
ok: [localhost -> localhost]

TASK [Generate the SSH public key] *********************************************
ok: [localhost -> localhost]

TASK [Change mode for the SSH private key] *************************************
ok: [localhost -> localhost]

TASK [Ensure the dynamic inventory exists] *************************************
ok: [localhost]

TASK [cloud-digitalocean : Set the DigitalOcean Access Token fact] *************
ok: [localhost]

TASK [cloud-digitalocean : Delete the existing Algo SSH keys] ******************
FAILED - RETRYING: TASK: cloud-digitalocean : Delete the existing Algo SSH keys (10 retries left).
ok: [localhost]

TASK [cloud-digitalocean : Upload the SSH key] *********************************
changed: [localhost]

TASK [cloud-digitalocean : Creating a droplet...] ******************************
changed: [localhost]

TASK [cloud-digitalocean : Add the droplet to an inventory group] **************
changed: [localhost]

TASK [cloud-digitalocean : set_fact] *******************************************
ok: [localhost]

TASK [cloud-digitalocean : Tag the droplet] ************************************
changed: [localhost]

TASK [cloud-digitalocean : Get droplets] ***************************************
ok: [localhost]

TASK [cloud-digitalocean : Ensure the group digitalocean exists in the dynamic inventory file] ***
ok: [localhost]

TASK [cloud-digitalocean : Populate the dynamic inventory] *********************
changed: [localhost] => (item={u'status': u'active', u'kernel': None, u'volume_ids': [], u'locked': False, u'name': u'algo.local', u'backup_ids': [], u'created_at': u'2017-04-23T02:50:47Z', u'snapshot_ids': [], u'size_slug': u'512mb', u'networks': {u'v4': [{u'type': u'public', u'netmask': u'255.255.255.0', u'ip_address': u'198.211.117.111', u'gateway': u'198.211.117.1'}], u'v6': [{u'type': u'public', u'netmask': 64, u'ip_address': u'2604:A880:0400:00D0:0000:0000:1DE2:2001', u'gateway': u'2604:A880:0400:00D0:0000:0000:0000:0001'}]}, u'next_backup_window': None, u'vcpus': 1, u'size': {u'price_monthly': 5.0, u'available': True, u'transfer': 1.0, u'price_hourly': 0.00744, u'regions': [u'ams1', u'ams2', u'ams3', u'blr1', u'fra1', u'lon1', u'nyc1', u'nyc2', u'nyc3', u'sfo1', u'sfo2', u'sgp1', u'tor1'], u'vcpus': 1, u'memory': 512, u'disk': 20, u'slug': u'512mb'}, u'image': {u'min_disk_size': 20, u'name': u'16.04.2 x64', u'created_at': u'2017-04-17T16:04:33Z', u'slug': u'ubuntu-16-04-x64', u'regions': [u'nyc1', u'sfo1', u'nyc2', u'ams2', u'sgp1', u'lon1', u'nyc3', u'ams3', u'fra1', u'tor1', u'sfo2', u'blr1'], u'id': 24231613, u'distribution': u'Ubuntu', u'type': u'snapshot', u'public': True, u'size_gigabytes': 0.29}, u'memory': 512, u'region': {u'available': True, u'sizes': [u'512mb', u'1gb', u'2gb', u'4gb', u'8gb', u'16gb', u'32gb', u'48gb', u'64gb'], u'slug': u'nyc1', u'name': u'New York 1', u'features': [u'private_networking', u'backups', u'ipv6', u'metadata', u'install_agent', u'storage']}, u'disk': 20, u'id': 46628906, u'tags': [u'environment:algo'], u'features': [u'ipv6']})

TASK [Wait until SSH becomes ready...] *****************************************
ok: [localhost -> localhost]

TASK [A short pause, in order to be sure the instance is ready] ****************
Pausing for 10 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)
ok: [localhost]

TASK [Ensure the local ssh directory is exist] *********************************
ok: [localhost -> localhost]

TASK [Copy the algo ssh key to the local ssh directory] ************************
ok: [localhost -> localhost]

PLAY [Configure the server and install required software] **********************

TASK [Check the system] ********************************************************
changed: [198.211.117.111]

TASK [Ubuntu | Install prerequisites] ******************************************
changed: [198.211.117.111]

TASK [Ubuntu | Configure defaults] *********************************************
changed: [198.211.117.111]

TASK [FreeBSD / HardenedBSD | Install prerequisites] ***************************
skipping: [198.211.117.111]

TASK [FreeBSD / HardenedBSD | Configure defaults] ******************************
skipping: [198.211.117.111]

TASK [set_fact] ****************************************************************
skipping: [198.211.117.111]

TASK [Gather Facts] ************************************************************
ok: [198.211.117.111]

TASK [Ensure the algo ssh key exist on the server] *****************************
ok: [198.211.117.111]

TASK [Enable IPv6] *************************************************************
ok: [198.211.117.111]

TASK [Set facts if the deployment in a cloud] **********************************
ok: [198.211.117.111]

TASK [Generate password for the CA key] ****************************************
changed: [198.211.117.111 -> localhost]

TASK [Define password facts] ***************************************************
ok: [198.211.117.111]

TASK [Define the commonName] ***************************************************
ok: [198.211.117.111]

TASK [Change the algorithm to RSA] *********************************************
skipping: [198.211.117.111]

TASK [common : Gather Facts] ***************************************************
ok: [198.211.117.111]

TASK [common : Install software updates] ***************************************
changed: [198.211.117.111]

TASK [common : Check if reboot is required] ************************************
changed: [198.211.117.111]

TASK [common : Reboot] *********************************************************
skipping: [198.211.117.111]

TASK [common : Wait until SSH becomes ready...] ********************************
skipping: [198.211.117.111]

TASK [common : Disable MOTD on login and SSHD] *********************************
changed: [198.211.117.111] => (item={u'regexp': u'^session.*optional.*pam_motd.so.*', u'line': u'# MOTD DISABLED', u'file': u'/etc/pam.d/login'})
changed: [198.211.117.111] => (item={u'regexp': u'^session.*optional.*pam_motd.so.*', u'line': u'# MOTD DISABLED', u'file': u'/etc/pam.d/sshd'})

TASK [common : Loopback for services configured] *******************************
changed: [198.211.117.111]

TASK [common : Loopback included into the network config] **********************
changed: [198.211.117.111]

RUNNING HANDLER [common : restart loopback] ************************************
changed: [198.211.117.111]

TASK [common : set_fact] *******************************************************
ok: [198.211.117.111]

TASK [common : set_fact] *******************************************************
skipping: [198.211.117.111]

TASK [common : Loopback included into the rc config] ***************************
skipping: [198.211.117.111]

TASK [common : Enable the gateway features] ************************************
skipping: [198.211.117.111] => (item={u'value': u'"YES"', u'param': u'firewall_enable'})
skipping: [198.211.117.111] => (item={u'value': u'"open"', u'param': u'firewall_type'})
skipping: [198.211.117.111] => (item={u'value': u'"YES"', u'param': u'gateway_enable'})
skipping: [198.211.117.111] => (item={u'value': u'"YES"', u'param': u'natd_enable'})
skipping: [198.211.117.111] => (item={u'value': u'""', u'param': u'natd_interface'})
skipping: [198.211.117.111] => (item={u'value': u'"-dynamic -m"', u'param': u'natd_flags'})

TASK [common : Install tools] **************************************************
changed: [198.211.117.111] => (item=[u'git', u'screen', u'apparmor-utils', u'uuid-runtime', u'coreutils', u'sendmail', u'iptables-persistent', u'cgroup-tools', u'openssl'])

TASK [common : Sysctl tuning] **************************************************
changed: [198.211.117.111] => (item={u'item': u'net.ipv4.ip_forward', u'value': 1})
changed: [198.211.117.111] => (item={u'item': u'net.ipv4.conf.all.forwarding', u'value': 1})
changed: [198.211.117.111] => (item={u'item': u'net.ipv6.conf.all.forwarding', u'value': 1})

TASK [ssh_tunneling : Ensure that the sshd_config file has desired options] ****
changed: [198.211.117.111]

TASK [ssh_tunneling : Ensure that the algo group exist] ************************
changed: [198.211.117.111]

TASK [ssh_tunneling : Ensure that the jail directory exist] ********************
changed: [198.211.117.111]

TASK [ssh_tunneling : Ensure that the SSH users exist] *************************
changed: [198.211.117.111] => (item=machito)

TASK [ssh_tunneling : The authorized keys file created] ************************
changed: [198.211.117.111] => (item=machito)

TASK [ssh_tunneling : Generate SSH fingerprints] *******************************
changed: [198.211.117.111]

TASK [ssh_tunneling : Fetch users SSH private keys] ****************************
changed: [198.211.117.111] => (item=machito)

TASK [ssh_tunneling : Change mode for SSH private keys] ************************
changed: [198.211.117.111 -> localhost] => (item=machito)

TASK [ssh_tunneling : Fetch the known_hosts file] ******************************
changed: [198.211.117.111 -> localhost]

TASK [ssh_tunneling : Build the client ssh config] *****************************
changed: [198.211.117.111 -> localhost] => (item=machito)

TASK [vpn : Ensure that the strongswan group exist] ****************************
changed: [198.211.117.111]

TASK [vpn : Ensure that the strongswan user exist] *****************************
changed: [198.211.117.111]

TASK [vpn : set_fact] **********************************************************
ok: [198.211.117.111]

TASK [vpn : Ubuntu | Install strongSwan] ***************************************
changed: [198.211.117.111]

TASK [vpn : Ubuntu | Enforcing ipsec with apparmor] ****************************
skipping: [198.211.117.111] => (item=/usr/lib/ipsec/charon)
skipping: [198.211.117.111] => (item=/usr/lib/ipsec/lookip)
skipping: [198.211.117.111] => (item=/usr/lib/ipsec/stroke)

TASK [vpn : Ubuntu | Enable services] ******************************************
ok: [198.211.117.111] => (item=apparmor)
ok: [198.211.117.111] => (item=strongswan)
ok: [198.211.117.111] => (item=netfilter-persistent)

TASK [vpn : Ubuntu | Ensure that the strongswan service directory exist] *******
changed: [198.211.117.111]

TASK [vpn : Ubuntu | Setup the cgroup limitations for the ipsec daemon] ********
changed: [198.211.117.111]

TASK [vpn : Iptables configured] ***********************************************
changed: [198.211.117.111] => (item={u'dest': u'/etc/iptables/rules.v4', u'src': u'rules.v4.j2'})

TASK [vpn : Iptables configured] ***********************************************
changed: [198.211.117.111] => (item={u'dest': u'/etc/iptables/rules.v6', u'src': u'rules.v6.j2'})

TASK [vpn : FreeBSD / HardenedBSD | Get the existing kernel parameters] ********
skipping: [198.211.117.111]

TASK [vpn : FreeBSD / HardenedBSD | Set the rebuild_needed fact] ***************
skipping: [198.211.117.111] => (item=IPSEC)
skipping: [198.211.117.111] => (item=IPSEC_NAT_T)
skipping: [198.211.117.111] => (item=crypto)

TASK [vpn : FreeBSD / HardenedBSD | Make the kernel config] ********************
skipping: [198.211.117.111]

TASK [vpn : FreeBSD / HardenedBSD | Ensure the all options are enabled] ********
skipping: [198.211.117.111] => (item=options	IPSEC)
skipping: [198.211.117.111] => (item=options IPSEC_NAT_T)
skipping: [198.211.117.111] => (item=device	crypto)

TASK [vpn : HardenedBSD | Determine the sources] *******************************
skipping: [198.211.117.111]

TASK [vpn : FreeBSD | Determine the sources] ***********************************
skipping: [198.211.117.111]

TASK [vpn : FreeBSD / HardenedBSD | Increase the git postBuffer size] **********
skipping: [198.211.117.111]

TASK [vpn : FreeBSD / HardenedBSD | Fetching the sources...] *******************
skipping: [198.211.117.111]

TASK [vpn : FreeBSD / HardenedBSD | Fetching the sources...] *******************
skipping: [198.211.117.111]

TASK [vpn : FreeBSD / HardenedBSD | The kernel is being built...] **************
skipping: [198.211.117.111]

TASK [vpn : FreeBSD / HardenedBSD | The kernel is being built...] **************
skipping: [198.211.117.111]

TASK [vpn : FreeBSD / HardenedBSD | Reboot] ************************************
skipping: [198.211.117.111]

TASK [vpn : FreeBSD / HardenedBSD | Enable strongswan] *************************
skipping: [198.211.117.111]

TASK [vpn : Install strongSwan] ************************************************
ok: [198.211.117.111]

TASK [vpn : Get StrongSwan versions] *******************************************
changed: [198.211.117.111]

TASK [vpn : Setup the config files from our templates] *************************
changed: [198.211.117.111] => (item={u'dest': u'/etc/strongswan.conf', u'src': u'strongswan.conf.j2', u'group': u'root', u'mode': u'0644', u'owner': u'root'})
changed: [198.211.117.111] => (item={u'dest': u'/etc/ipsec.conf', u'src': u'ipsec.conf.j2', u'group': u'root', u'mode': u'0644', u'owner': u'root'})
changed: [198.211.117.111] => (item={u'dest': u'/etc/ipsec.secrets', u'src': u'ipsec.secrets.j2', u'group': u'root', u'mode': u'0600', u'owner': u'strongswan'})

TASK [vpn : Get loaded plugins] ************************************************
changed: [198.211.117.111]

TASK [vpn : Disable unneeded plugins] ******************************************
skipping: [198.211.117.111] => (item=pem)
skipping: [198.211.117.111] => (item=sha2)
skipping: [198.211.117.111] => (item=hmac)
changed: [198.211.117.111] => (item=sshkey)
changed: [198.211.117.111] => (item=constraints)
changed: [198.211.117.111] => (item=dnskey)
skipping: [198.211.117.111] => (item=pubkey)
skipping: [198.211.117.111] => (item=x509)
changed: [198.211.117.111] => (item=attr)
changed: [198.211.117.111] => (item=pkcs1)
changed: [198.211.117.111] => (item=connmark)
skipping: [198.211.117.111] => (item=stroke)
changed: [198.211.117.111] => (item=rc2)
skipping: [198.211.117.111] => (item=gcm)
changed: [198.211.117.111] => (item=agent)
changed: [198.211.117.111] => (item=xcbc)
skipping: [198.211.117.111] => (item=nonce)
skipping: [198.211.117.111] => (item=pgp)
skipping: [198.211.117.111] => (item=revocation)
skipping: [198.211.117.111] => (item=pkcs8)
changed: [198.211.117.111] => (item=test-vectors)
changed: [198.211.117.111] => (item=md4)
skipping: [198.211.117.111] => (item=kernel-netlink)
changed: [198.211.117.111] => (item=md5)
skipping: [198.211.117.111] => (item=pkcs7)
changed: [198.211.117.111] => (item=fips-prf)
skipping: [198.211.117.111] => (item=openssl)
changed: [198.211.117.111] => (item=updown)
changed: [198.211.117.111] => (item=resolve)
skipping: [198.211.117.111] => (item=pkcs12)
skipping: [198.211.117.111] => (item=socket-default)
skipping: [198.211.117.111] => (item=aes)
skipping: [198.211.117.111] => (item=random)
changed: [198.211.117.111] => (item=gmp)
changed: [198.211.117.111] => (item=sha1)

TASK [vpn : Ensure that required plugins are enabled] **************************
changed: [198.211.117.111] => (item=pem)
changed: [198.211.117.111] => (item=sha2)
changed: [198.211.117.111] => (item=hmac)
skipping: [198.211.117.111] => (item=sshkey)
skipping: [198.211.117.111] => (item=constraints)
skipping: [198.211.117.111] => (item=dnskey)
changed: [198.211.117.111] => (item=pubkey)
changed: [198.211.117.111] => (item=x509)
skipping: [198.211.117.111] => (item=attr)
skipping: [198.211.117.111] => (item=pkcs1)
skipping: [198.211.117.111] => (item=connmark)
changed: [198.211.117.111] => (item=stroke)
skipping: [198.211.117.111] => (item=rc2)
changed: [198.211.117.111] => (item=gcm)
skipping: [198.211.117.111] => (item=agent)
skipping: [198.211.117.111] => (item=xcbc)
changed: [198.211.117.111] => (item=nonce)
changed: [198.211.117.111] => (item=pgp)
changed: [198.211.117.111] => (item=revocation)
changed: [198.211.117.111] => (item=pkcs8)
skipping: [198.211.117.111] => (item=test-vectors)
skipping: [198.211.117.111] => (item=md4)
changed: [198.211.117.111] => (item=kernel-netlink)
skipping: [198.211.117.111] => (item=md5)
changed: [198.211.117.111] => (item=pkcs7)
skipping: [198.211.117.111] => (item=fips-prf)
changed: [198.211.117.111] => (item=openssl)
skipping: [198.211.117.111] => (item=updown)
skipping: [198.211.117.111] => (item=resolve)
changed: [198.211.117.111] => (item=pkcs12)
changed: [198.211.117.111] => (item=socket-default)
changed: [198.211.117.111] => (item=aes)
changed: [198.211.117.111] => (item=random)
skipping: [198.211.117.111] => (item=gmp)
skipping: [198.211.117.111] => (item=sha1)

TASK [vpn : Ensure the pki directory is not exist] *****************************
skipping: [198.211.117.111]

TASK [vpn : Ensure the pki directories are exist] ******************************
changed: [198.211.117.111 -> localhost] => (item=ecparams)
changed: [198.211.117.111 -> localhost] => (item=certs)
changed: [198.211.117.111 -> localhost] => (item=crl)
changed: [198.211.117.111 -> localhost] => (item=newcerts)
changed: [198.211.117.111 -> localhost] => (item=private)
changed: [198.211.117.111 -> localhost] => (item=reqs)

TASK [vpn : Ensure the files are exist] ****************************************
changed: [198.211.117.111 -> localhost] => (item=.rnd)
changed: [198.211.117.111 -> localhost] => (item=private/.rnd)
changed: [198.211.117.111 -> localhost] => (item=index.txt)
changed: [198.211.117.111 -> localhost] => (item=index.txt.attr)
changed: [198.211.117.111 -> localhost] => (item=serial)

TASK [vpn : Generate the openssl server configs] *******************************
changed: [198.211.117.111 -> localhost]

TASK [vpn : Build the CA pair] *************************************************
changed: [198.211.117.111 -> localhost]

TASK [vpn : Copy the CA certificate] *******************************************
changed: [198.211.117.111 -> localhost]

TASK [vpn : Generate the serial number] ****************************************
changed: [198.211.117.111 -> localhost]

TASK [vpn : Build the server pair] *********************************************
changed: [198.211.117.111 -> localhost]

TASK [vpn : Build the client's pair] *******************************************
changed: [198.211.117.111 -> localhost] => (item=machito)

TASK [vpn : Build the client's p12] ********************************************
changed: [198.211.117.111 -> localhost] => (item=machito)

TASK [vpn : Copy the p12 certificates] *****************************************
changed: [198.211.117.111 -> localhost] => (item=machito)

TASK [vpn : Copy the keys to the strongswan directory] *************************
changed: [198.211.117.111] => (item={u'dest': u'/etc/ipsec.d/cacerts/ca.crt', u'src': u'configs/198.211.117.111/pki/cacert.pem', u'group': u'root', u'mode': u'0600', u'owner': u'strongswan'})
changed: [198.211.117.111] => (item={u'dest': u'/etc/ipsec.d/certs/198.211.117.111.crt', u'src': u'configs/198.211.117.111/pki/certs/198.211.117.111.crt', u'group': u'root', u'mode': u'0600', u'owner': u'strongswan'})
changed: [198.211.117.111] => (item={u'dest': u'/etc/ipsec.d/private/198.211.117.111.key', u'src': u'configs/198.211.117.111/pki/private/198.211.117.111.key', u'group': u'root', u'mode': u'0600', u'owner': u'strongswan'})

TASK [vpn : Register p12 PayloadContent] ***************************************
changed: [198.211.117.111 -> localhost] => (item=machito)

TASK [vpn : Set facts for mobileconfigs] ***************************************
ok: [198.211.117.111]

TASK [vpn : Build the mobileconfigs] *******************************************
changed: [198.211.117.111 -> localhost] => (item=(censored due to no_log))

TASK [vpn : Build the strongswan app android config] ***************************
changed: [198.211.117.111 -> localhost] => (item=(censored due to no_log))

TASK [vpn : Build the client ipsec config file] ********************************
changed: [198.211.117.111 -> localhost] => (item=machito)

TASK [vpn : Build the client ipsec secret file] ********************************
changed: [198.211.117.111 -> localhost] => (item=machito)

TASK [vpn : Build the windows client powershell script] ************************
skipping: [198.211.117.111] => (item=machito)

TASK [vpn : Restrict permissions for the local private directories] ************
changed: [198.211.117.111 -> localhost] => (item=configs/198.211.117.111)

RUNNING HANDLER [security : restart ssh] ***************************************
changed: [198.211.117.111]

RUNNING HANDLER [vpn : restart strongswan] *************************************
changed: [198.211.117.111]

RUNNING HANDLER [vpn : daemon-reload] ******************************************
changed: [198.211.117.111]

RUNNING HANDLER [vpn : restart iptables] ***************************************
changed: [198.211.117.111]

TASK [vpn : strongSwan started] ************************************************
ok: [198.211.117.111]

TASK [debug] *******************************************************************
ok: [198.211.117.111] => {
    "msg": [
        [
            "\"#                          Congratulations!                            #\"",
            "\"#                     Your Algo server is running.                     #\"",
            "\"#    Config files and certificates are in the ./configs/ directory.    #\"",
            "\"#              Go to https://whoer.net/ after connecting               #\"",
            "\"#        and ensure that all your traffic passes through the VPN.      #\"",
            "\"#               Local DNS resolver 172.16.0.1              #\"",
            ""
        ],
        "    \"#                The p12 and SSH keys password is xxxxxxxxx            #\"\n",
        "    ",
        "    \"#      Shell access: ssh -i configs/algo.pem root@198.211.117.111        #\"\n"
    ]
}

TASK [Delete the CA key] *******************************************************
changed: [198.211.117.111 -> localhost]

PLAY RECAP *********************************************************************
198.211.117.111            : ok=70   changed=56   unreachable=0    failed=0
localhost                  : ok=19   changed=5    unreachable=0    failed=0

**Comment by jplock** [comment]
Did you provide any WiFi networks to exclude when you configured Algo and are now trying to connect to the VPN while on the network? That happened to me until I figured out what was happening.

**Comment by dguido** [comment]
Yes, please follow the issue template. That's why we ask those questions.

All of this should work fine, regardless of the mobileconfig settings. You might want to SSH to the server, shot down strongswan (I think `service ipsec stop`) and then start it in no forking mode for a good debug log (`ipsec start --nofork`).

**Comment by bshiznit** [comment]
`sudo ipsec restart --nofork`
got my server into logging mode

**Comment by arvdsn** [comment]
Having the same issue here, but on local installation. I don't know if this helps you or if it's related (it looks like it's the same issue), but here's my log when running in --nofork-mode.

> 09[NET] received packet: from 10.0.0.1[500] to 10.0.0.15[500]
09[NET] waiting for data on sockets
12[MGR] checkout IKE_SA by message
12[MGR] created IKE_SA (unnamed)[7]
12[NET] received packet: from 10.0.0.1[500] to 10.0.0.15[500] (240 bytes)
12[ENC] parsed IKE_SA_INIT request 0 [ SA KE No N(NATD_S_IP) N(NATD_D_IP) N(FRAG_SUP) ]
12[CFG] looking for an ike config for 10.0.0.15...10.0.0.1
12[CFG]   candidate: %any...%any, prio 28
12[CFG] found matching ike config: %any...%any with prio 28
12[IKE] 10.0.0.1 is initiating an IKE_SA
12[IKE] IKE_SA (unnamed)[7] state change: CREATED => CONNECTING
12[CFG] selecting proposal:
12[CFG]   proposal matches
12[CFG] received proposals: IKE:AES_GCM_16_128/PRF_HMAC_SHA2_512/ECP_256
12[CFG] configured proposals: IKE:AES_GCM_16_128/PRF_HMAC_SHA2_512/ECP_256, IKE:AES_CBC_128/HMAC_SHA2_512_256/PRF_HMAC_SHA2_512/ECP_256, IKE:AES_CBC_128/HMAC_SHA2_384_192/PRF_HMAC_SHA2_384/ECP_256
12[CFG] selected proposal: IKE:AES_GCM_16_128/PRF_HMAC_SHA2_512/ECP_256
12[IKE] local host is behind NAT, sending keep alives
12[IKE] remote host is behind NAT
12[IKE] sending cert request for "CN=xx.xx.xx.45"
12[ENC] generating IKE_SA_INIT response 0 [ SA KE No N(NATD_S_IP) N(NATD_D_IP) CERTREQ N(FRAG_SUP) N(MULT_AUTH) ]
12[NET] sending packet: from 10.0.0.15[500] to 10.0.0.1[500] (273 bytes)
10[NET] sending packet: from 10.0.0.15[500] to 10.0.0.1[500]
12[MGR] checkin IKE_SA (unnamed)[7]
12[MGR] check-in of IKE_SA successful.
09[NET] received packet: from 10.0.0.1[4500] to 10.0.0.15[4500]
09[NET] waiting for data on sockets
13[MGR] checkout IKE_SA by message
13[MGR] IKE_SA (unnamed)[7] successfully checked out
13[NET] received packet: from 10.0.0.1[4500] to 10.0.0.15[4500] (344 bytes)
13[ENC] parsed IKE_AUTH request 1 [ IDi N(INIT_CONTACT) N(MOBIKE_SUP) IDr CERTREQ CPRQ(ADDR DHCP DNS MASK ADDR6 DHCP6 DNS6) N(ESP_TFC_PAD_N) N(NON_FIRST_FRAG) SA TSi TSr ]
13[IKE] received cert request for "CN=xx.xx.xx.45"
13[CFG] looking for peer configs matching 10.0.0.15[xx.xx.xx.45]...10.0.0.1[arvdsn]
13[CFG]   candidate "ikev2-pubkey", match: 20/1/28 (me/other/ike)
13[CFG] selected peer config 'ikev2-pubkey'
13[IKE] peer requested EAP, config inacceptable
13[CFG] no alternative config found
13[IKE] processing INTERNAL_IP4_ADDRESS attribute
13[IKE] processing INTERNAL_IP4_DHCP attribute
13[IKE] processing INTERNAL_IP4_DNS attribute
13[IKE] processing INTERNAL_IP4_NETMASK attribute
13[IKE] processing INTERNAL_IP6_ADDRESS attribute
13[IKE] processing INTERNAL_IP6_DHCP attribute
13[IKE] processing INTERNAL_IP6_DNS attribute
13[IKE] received ESP_TFC_PADDING_NOT_SUPPORTED, not using ESPv3 TFC padding
13[IKE] peer supports MOBIKE
13[ENC] generating IKE_AUTH response 1 [ N(AUTH_FAILED) ]
13[NET] sending packet: from 10.0.0.15[4500] to 10.0.0.1[4500] (65 bytes)
13[MGR] checkin and destroy IKE_SA ikev2-pubkey[7]
13[IKE] IKE_SA ikev2-pubkey[7] state change: CONNECTING => DESTROYING
13[MGR] check-in and destroy of IKE_SA successful
10[NET] sending packet: from 10.0.0.15[4500] to 10.0.0.1[4500]

Note that I'm connecting from within the local network, but the same happens from outside.

**Comment by dguido** [comment]
You may want to inspect the logs on your Mac with the following terminal command:
`log show --predicate 'subsystem == "com.apple.networkextension"' --info --last 1h`

On the server, if you login over ssh and run the following command it may have more useful output:
`journalctl -f -u strongswan`

Please join our Slack for further support.
