### ISSUE TITLE
Incorrect URL to ansible docs

### ISSUE THREAD

**Issue by jtnt** [trailofbits/algo#483]
Link to broken URL - https://github.com/trailofbits/algo/blob/master/docs/deploy-with-ansible.md -appears in the installer (aws access key entry step), the main deployment instructions on Github, and maybe other places.

Correct URL is:
https://github.com/trailofbits/algo/blob/master/docs/deploy-from-ansible.md

**Comment by dguido** [comment]
Ah can you submit a PR to fix that?

**Comment by jtnt** [comment]
Sorry, I'm not a developer. I don't think you want me doing that (even if I knew how).

**Comment by dguido** [comment]
It's really easy! You can do it all with buttons on Github. You click the fork button, make the change, then submit a pull request back.

https://help.github.com/articles/fork-a-repo/

The file to change is here:
https://github.com/trailofbits/algo/blob/master/algo

**Comment by jtnt** [comment]
Thanks for the guidance. Just committed the changes. Hope I did everything the way I was supposed to. Feel free to let me know if I didn't. Always looking to learn. :)
