### ISSUE TITLE
Add support for vultr.com

### ISSUE THREAD

**Issue by eliabieri** [trailofbits/algo#488]
### OS / Environment
na

### Ansible version
na

### The way of deployment (cloud or local)

Would be very cool to have vultr.com support. Their USD 2.5 plan is crazy powerful for the price.

**Comment by bjornlll** [comment]
Agree. I've got mine deployed on Vultr.

Algo's documentation is great, but for those who are looking to get up and running on Vultr, I'll reiterate the steps here:

1. Provision a Vultr server configured with Ubuntu 16.04
2. Log into your new server using the credentials provided in Vultr's UI
3. `sudo apt-get update && sudo apt-get install build-essential libssl-dev libffi-dev python-dev python-pip python-setuptools python-virtualenv -y`
4. `sudo apt-get install software-properties-common && sudo apt-add-repository ppa:ansible/ansible`
5. `sudo apt-get update && sudo apt-get install ansible`
6. `git clone https://github.com/trailofbits/algo`
7. `cd algo`
8. `python -m virtualenv env && source env/bin/activate && python -m pip install -U pip && python -m pip install -r requirements.txt`
9. Edit your `config.cfg` and adapt to your needs e.g. `nano config.cfg`
10. `./algo`
11. Select `local` when asked where to deploy, and provide the Public IP from Vultr's UI when prompted
12. `scp` the files to your local machine, or store on an intermediate server if you've disabled SSH logins, e.g. using http://transfer.sh/ - the latter is obviously a (much!) less secure alternaive 

All the steps above, aside from (12), are taken from the documentation. Hope this helps anyone trying to run algo on Vultr.

I don't know if this is true for others beside me, but for some reason I enjoy much better performance using Vultr than DO from my current location.

**Comment by bjornlll** [comment]
I should add: There might be a much simpler way to get up and running on Vultr than the way I describe above, this just happened to be the way I did it.

**Comment by dguido** [comment]
https://github.com/trailofbits/algo/blob/master/docs/deploy-to-unsupported-cloud.md

**Comment by Starz0r** [comment]
I'm wondering quite honestly if the problem I'm experiencing is a Windows only problem. @ookangzheng said they have it setup with Vultr, but don't seem to use Windows, I'm wondering how he/she might have it setup. 

I'd be happy to get actual support for Vultr going, but I'm going to need some help in the right direction  to be able to debug this efficiently so we can see if there really is a problem.

**Comment by ookangzheng** [comment]
@Starz0r if u want to setup on Vultr u can send me email: okz5289@gmail.com 
let's keep in contact, if u wish to ~~

**Comment by arejay73** [comment]
Here is the link to their API, [Vultr API Docs](https://www.vultr.com/api/).  Maybe simple setup like Digital Ocean.

**Comment by Starz0r** [comment]
@bjornlll Can you provide information on what your client computer is? I find it odd that the only problem Vultr has as a unsupported cloud is that it throttles Windows 10 downstream connections.

**Comment by bjornlll** [comment]
I'm using the base level 2016 MBP running macOS 10.12.4. 

It should be noted that I am currently in China, hence me saying "I enjoy much better performance using Vultr than DO from my current location". For users elsewhere DO might work just as well.

**Comment by Starz0r** [comment]
Did a few more tests and decided to bite the bullet and throw money at Vultr. It seems that not all servers at Vultr are configured properly for this type of setup? And it seems to be random if you deploy a server that has no conflicts with Ansible and Algo. I somehow managed to get a server that worked after trying again, and don't seem to be having any issues so far. Though, proper 100% would be appreciated since it Vultr does seem to have it's own API.

Also in my testing sometimes my VPN would just turn off, this might be because I'm using the built-in Windows Hotspot to connect some of my devices. Can any of the developers confirm this an issue? @dguido @gunph1ld
