### ISSUE TITLE
Request an SRU from Ubuntu for strongSwan

### ISSUE THREAD

**Issue by dguido** [trailofbits/algo#494]
16.04 comes with strongSwan 5.3.5 which has a bug for iOS and macOS clients that causes them to disconnect frequently. In order to workaround the bug, we have to disable dead peer detection. However, with dead peer detection disabled it consumes IPs from the virtual pool until there aren’t any left, then no one can connect.

We can address THAT issue by setting strongSwan to “replace” IPs when they reconnect. However, with "replace" set, any client with the same certificate is considered the same client. So if you gave the same certificate to 3 people, then only 1 of them can use the VPN at a time.

The best fix is to upgrade to strongSwan 5.5.1 which fixes the dead peer detection bug and properly manages the virtual IP pool. But you can’t get 5.5.1 on 16.04. It is, however, available on 17.04.

https://wiki.ubuntu.com/StableReleaseUpdates

Related to #430

**Comment by akiekintveld** [comment]
I'm currently running a 17.04 instance with strongSwan 5.5.1. Upgrading from 16.04 seems to have fixed the issue and I haven't experienced any other bugs or abnormalities. Also, I have the local DNS resolver on. It's been up for around a day now without any issues.

**Comment by sgasean** [comment]
I also upgraded to 17.04 and it seems to work. But do we need to change disabled DPD so the bug is final resolved? If so how? Thanks

**Comment by jbwhaley** [comment]
I upgraded to 17.04 and I am still having massive issues. My Mac will connect, and then when I go to connect my iOS devices they seem to connect at first. But if I switch from WiFi to LTE and back on my iPhone, it will not reconnect at all. Eventually all three devices quit connecting. Same issue, or something different?

**Comment by dguido** [comment]
Please don't use this issue for troubleshooting unrelated problems. This ticket is only for coordinating or performing a request for an SRU for Ubuntu 16.04. Thanks.

**Comment by dguido** [comment]
sgasean: Yes, you can edit the ipsec.conf and set uniqueids to never and dpdaction to clear.

I filed a bug in Ubuntu: https://bugs.launchpad.net/ubuntu/+source/strongswan/+bug/1687711

**Comment by artyomboyko** [comment]
How to upgrade to 17.04 ?

**Comment by gunph1ld** [comment]
They've fixed the problem in the `-proposed`

**Comment by dguido** [comment]
Fix released!
