### ISSUE TITLE
Hangouts outbound call fails over VPN

### ISSUE THREAD

**Issue by Steve9F** [trailofbits/algo#499]
### OS / Environment

Install: Bash on Ubuntu on Windows - Python 2.7.6
Server: Ubuntu 16.04.2 on AWS EC2
Client: Windows 10 Creators Update

### Ansible version

ansible 2.2.0.0

### Version of components from `requirements.txt`

msrestazure 0.4.7
setuptools 35.0.1
ansible 2.2.0.0
dopy 0.3.5
boto 2.46.1
boto3 1.4.4
azure 2.0.0rc5
msrest 0.4.1
apache-libcloud 2.0.0
six 1.10.0
pyOpenSSL 17.0.0
Jinja2 2.8

### Summary of the problem

Google Hangouts on Windows cannot make an outbound call when connected via the VPN. I’ve verified that this is the case from within the Chrome browser on hangouts.google.com, from the Chrome Hangouts app and extension. I’m using Project Fi and have confirmed the issue also exists with Google Voice. The app shows “Call failed to connect or was disconnected. Please try again.” or hangs with "Calling in Project Fi…" in the dialer. 

I can answer inbound calls. If I originate an outbound call w/o VPN and then connect the VPN the call continues without an issue. 
 
Running the Chrome Connectivity Diagnostics passes and I've also confirmed that I can connect to the servers and UDP / TCP ports using netcat. 

### Steps to reproduce the behavior

Connect to VPN
Navigate to http://hangouts.google.com
Attempt to make a phone call to any number

### The way of deployment (cloud or local)

Cloud

### Expected behavior

Phone call connects

### Actual behavior

Call either fails with "Call failed…" message per above or hangs on "Calling in Project Fi…" with no error.

### Full log

  What provider would you like to use?
    1. DigitalOcean
    2. Amazon EC2
    3. Microsoft Azure
    4. Google Compute Engine (only for testing, see issue #369)
    5. Install to existing Ubuntu 16.04 server

Enter the number of your desired provider
: 2

Enter your aws_access_key (http://docs.aws.amazon.com/general/latest/gr/managing-aws-access-keys.html)
Note: Make sure to use an IAM user with an acceptable policy attached (see https://github.com/trailofbits/algo/blob/master/docs/deploy-from-ansible.md).
[pasted values will not be displayed]
[AKIA...]:

Enter your aws_secret_key (http://docs.aws.amazon.com/general/latest/gr/managing-aws-access-keys.html)
[pasted values will not be displayed]
[ABCD...]:

Name the vpn server:
[algo]: algo-test

  What region should the server be located in?
    1.   us-east-1           US East (N. Virginia)
    2.   us-east-2           US East (Ohio)
    3.   us-west-1           US West (N. California)
    4.   us-west-2           US West (Oregon)
    5.   ap-south-1          Asia Pacific (Mumbai)
    6.   ap-northeast-2      Asia Pacific (Seoul)
    7.   ap-southeast-1      Asia Pacific (Singapore)
    8.   ap-southeast-2      Asia Pacific (Sydney)
    9.   ap-northeast-1      Asia Pacific (Tokyo)
    10.  eu-central-1        EU (Frankfurt)
    11.  eu-west-1           EU (Ireland)
    12.  eu-west-2           EU (London)
    13.  ca-central-1        Canada (Central)
    14.  sa-east-1           São Paulo
Enter the number of your desired region:
[1]: 4

Do you want macOS/iOS clients to enable "VPN On Demand" when connected to cellular networks?
[y/N]:

Do you want macOS/iOS clients to enable "VPN On Demand" when connected to Wi-Fi?
[y/N]:

Do you want to install a DNS resolver on this VPN server, to block ads while surfing?
[y/N]:

Do you want each user to have their own account for SSH tunneling?
[y/N]:

Do you want to apply operating system security enhancements on the server? (warning: replaces your sshd_config)
[y/N]:

Do you want the VPN to support Windows 10 or Linux Desktop clients? (enables compatible ciphers and key exchange, less secure)
[y/N]: Y

Do you want to retain the CA key? (required to add users in the future, but less secure)
[y/N]:

PLAY [Configure the server] ****************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Generate the SSH private key] ********************************************
ok: [localhost -> localhost]

TASK [Generate the SSH public key] *********************************************
ok: [localhost -> localhost]

TASK [Change mode for the SSH private key] *************************************
ok: [localhost -> localhost]

TASK [Ensure the dynamic inventory exists] *************************************
ok: [localhost]

TASK [cloud-ec2 : set_fact] ****************************************************
ok: [localhost]

TASK [cloud-ec2 : Locate official AMI for region] ******************************
ok: [localhost]

TASK [cloud-ec2 : set_fact] ****************************************************
ok: [localhost]

TASK [cloud-ec2 : Make a cloudformation template] ******************************
changed: [localhost]

TASK [cloud-ec2 : Deploy the template] *****************************************
changed: [localhost]

TASK [cloud-ec2 : Add new instance to host group] ******************************
changed: [localhost]

TASK [cloud-ec2 : set_fact] ****************************************************
ok: [localhost]

TASK [cloud-ec2 : Get EC2 instances] *******************************************
ok: [localhost]

TASK [cloud-ec2 : Ensure the group ec2 exists in the dynamic inventory file] ***
ok: [localhost]

TASK [cloud-ec2 : Populate the dynamic inventory] ******************************
changed: [localhost] => (item={u'kernel': None, u'instance_profile': None, u'root_device_type': u'ebs', u'private_dns_name': u'ip-172-16-255-127.us-west-2.compute.internal', u'spot_instance_request_id': None, u'source_destination_check': u'true', u'id': u'i-07b819c388370708f', u'ebs_optimized': False, u'state': u'running', u'client_token': u'algo-EC2In-P6SSX9AFTF9A', u'virtualization_type': u'hvm', u'ramdisk': None, u'public_ip_address': u'54.71.187.11', u'block_device_mapping': [{u'status': u'attached', u'volume_id': u'vol-0832d4756cf615223', u'delete_on_termination': True, u'attach_time': u'2017-04-28T00:54:46.000Z', u'device_name': u'/dev/sda1'}], u'key_name': None, u'interfaces': [{u'id': u'eni-a69a789b', u'mac_address': u'06:51:03:9e:f6:db'}], u'image_id': u'ami-efd0428f', u'groups': [{u'id': u'sg-7f3cbf04', u'name': u'algo-test-InstanceSecurityGroup-3PTH5EZHTTAU'}], u'public_dns_name': u'ec2-54-71-187-11.us-west-2.compute.amazonaws.com', u'requester_id': None, u'tags': {u'Environment': u'Algo', u'aws:cloudformation:stack-name': u'algo-test', u'aws:cloudformation:stack-id': u'arn:aws:cloudformation:us-west-2:117590649350:stack/algo-test/13eec080-2bad-11e7-ab25-50a68a20128e', u'Name': u'Algo', u'aws:cloudformation:logical-id': u'EC2Instance'}, u'monitoring_state': u'disabled', u'placement': {u'tenancy': u'default', u'zone': u'us-west-2a'}, u'ami_launch_index': u'0', u'hypervisor': u'xen', u'region': u'us-west-2', u'launch_time': u'2017-04-28T00:54:46.000Z', u'persistent': False, u'architecture': u'x86_64', u'private_ip_address': u'172.16.255.127', u'vpc_id': u'vpc-002b1a67'})
ok: [localhost] => (item={u'kernel': None, u'instance_profile': None, u'root_device_type': u'ebs', u'private_dns_name': u'ip-172-16-254-44.us-west-2.compute.internal', u'spot_instance_request_id': None, u'source_destination_check': u'true', u'id': u'i-0d14929bff657213c', u'ebs_optimized': False, u'state': u'running', u'client_token': u'aglo2-EC2In-1LY6QEMNWC2GY', u'virtualization_type': u'hvm', u'ramdisk': None, u'public_ip_address': u'54.70.4.16', u'block_device_mapping': [{u'status': u'attached', u'volume_id': u'vol-0c5073b96eac347c8', u'delete_on_termination': True, u'attach_time': u'2017-04-27T00:33:03.000Z', u'device_name': u'/dev/sda1'}], u'key_name': None, u'interfaces': [{u'id': u'eni-9c53a9b7', u'mac_address': u'02:4d:b0:49:4f:47'}], u'image_id': u'ami-efd0428f', u'groups': [{u'id': u'sg-ab0482d0', u'name': u'aglo2-InstanceSecurityGroup-X0SJ9FI4SHYM'}], u'public_dns_name': u'ec2-54-70-4-16.us-west-2.compute.amazonaws.com', u'requester_id': None, u'tags': {u'Environment': u'Algo', u'aws:cloudformation:stack-name': u'aglo2', u'aws:cloudformation:stack-id': u'arn:aws:cloudformation:us-west-2:117590649350:stack/aglo2/dd30e720-2ae0-11e7-9d46-503acbd4dc99', u'Name': u'Algo', u'aws:cloudformation:logical-id': u'EC2Instance'}, u'monitoring_state': u'disabled', u'placement': {u'tenancy': u'default', u'zone': u'us-west-2b'}, u'ami_launch_index': u'0', u'hypervisor': u'xen', u'region': u'us-west-2', u'launch_time': u'2017-04-27T00:33:02.000Z', u'persistent': False, u'architecture': u'x86_64', u'private_ip_address': u'172.16.254.44', u'vpc_id': u'vpc-a08eb9c7'})

TASK [Wait until SSH becomes ready...] *****************************************
ok: [localhost -> localhost]

TASK [A short pause, in order to be sure the instance is ready] ****************
Pausing for 10 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)
ok: [localhost]

TASK [Ensure the local ssh directory is exist] *********************************
ok: [localhost -> localhost]

TASK [Copy the algo ssh key to the local ssh directory] ************************
ok: [localhost -> localhost]

PLAY [Configure the server and install required software] **********************

TASK [Check the system] ********************************************************
changed: [54.71.187.11]

TASK [Ubuntu | Install prerequisites] ******************************************
changed: [54.71.187.11]

TASK [Ubuntu | Configure defaults] *********************************************
changed: [54.71.187.11]

TASK [FreeBSD / HardenedBSD | Install prerequisites] ***************************
skipping: [54.71.187.11]

TASK [FreeBSD / HardenedBSD | Configure defaults] ******************************
skipping: [54.71.187.11]

TASK [set_fact] ****************************************************************
skipping: [54.71.187.11]

TASK [Gather Facts] ************************************************************
ok: [54.71.187.11]

TASK [Ensure the algo ssh key exist on the server] *****************************
ok: [54.71.187.11]

TASK [Enable IPv6] *************************************************************
ok: [54.71.187.11]

TASK [Set facts if the deployment in a cloud] **********************************
ok: [54.71.187.11]

TASK [Generate password for the CA key] ****************************************
changed: [54.71.187.11 -> localhost]

TASK [Define password facts] ***************************************************
ok: [54.71.187.11]

TASK [Define the commonName] ***************************************************
ok: [54.71.187.11]

TASK [common : Gather Facts] ***************************************************
ok: [54.71.187.11]

TASK [common : Install software updates] ***************************************
changed: [54.71.187.11]

TASK [common : Check if reboot is required] ************************************
changed: [54.71.187.11]

TASK [common : Reboot] *********************************************************
ok: [54.71.187.11]

TASK [common : Wait until SSH becomes ready...] ********************************
ok: [54.71.187.11 -> localhost]

TASK [common : Disable MOTD on login and SSHD] *********************************
changed: [54.71.187.11] => (item={u'regexp': u'^session.*optional.*pam_motd.so.*', u'line': u'# MOTD DISABLED', u'file': u'/etc/pam.d/login'})
changed: [54.71.187.11] => (item={u'regexp': u'^session.*optional.*pam_motd.so.*', u'line': u'# MOTD DISABLED', u'file': u'/etc/pam.d/sshd'})

TASK [common : Loopback for services configured] *******************************
changed: [54.71.187.11]

TASK [common : Loopback included into the network config] **********************
changed: [54.71.187.11]

RUNNING HANDLER [common : restart loopback] ************************************
changed: [54.71.187.11]

TASK [common : set_fact] *******************************************************
ok: [54.71.187.11]

TASK [common : set_fact] *******************************************************
skipping: [54.71.187.11]

TASK [common : Loopback included into the rc config] ***************************
skipping: [54.71.187.11]

TASK [common : Enable the gateway features] ************************************
skipping: [54.71.187.11] => (item={u'value': u'"YES"', u'param': u'firewall_enable'})
skipping: [54.71.187.11] => (item={u'value': u'"open"', u'param': u'firewall_type'})
skipping: [54.71.187.11] => (item={u'value': u'"YES"', u'param': u'gateway_enable'})
skipping: [54.71.187.11] => (item={u'value': u'"YES"', u'param': u'natd_enable'})
skipping: [54.71.187.11] => (item={u'value': u'""', u'param': u'natd_interface'})
skipping: [54.71.187.11] => (item={u'value': u'"-dynamic -m"', u'param': u'natd_flags'})

TASK [common : Install tools] **************************************************
changed: [54.71.187.11] => (item=[u'git', u'screen', u'apparmor-utils', u'uuid-runtime', u'coreutils', u'sendmail', u'iptables-persistent', u'cgroup-tools', u'openssl'])

TASK [common : Sysctl tuning] **************************************************
changed: [54.71.187.11] => (item={u'item': u'net.ipv4.ip_forward', u'value': 1})
changed: [54.71.187.11] => (item={u'item': u'net.ipv4.conf.all.forwarding', u'value': 1})
changed: [54.71.187.11] => (item={u'item': u'net.ipv6.conf.all.forwarding', u'value': 1})

TASK [vpn : Ensure that the strongswan group exist] ****************************
changed: [54.71.187.11]

TASK [vpn : Ensure that the strongswan user exist] *****************************
changed: [54.71.187.11]

TASK [vpn : set_fact] **********************************************************
ok: [54.71.187.11]

TASK [vpn : Ubuntu | Install strongSwan] ***************************************
changed: [54.71.187.11]

TASK [vpn : Ubuntu | Enforcing ipsec with apparmor] ****************************
skipping: [54.71.187.11] => (item=/usr/lib/ipsec/charon)
skipping: [54.71.187.11] => (item=/usr/lib/ipsec/lookip)
skipping: [54.71.187.11] => (item=/usr/lib/ipsec/stroke)

TASK [vpn : Ubuntu | Enable services] ******************************************
ok: [54.71.187.11] => (item=apparmor)
ok: [54.71.187.11] => (item=strongswan)
ok: [54.71.187.11] => (item=netfilter-persistent)

TASK [vpn : Ubuntu | Ensure that the strongswan service directory exist] *******
changed: [54.71.187.11]

TASK [vpn : Ubuntu | Setup the cgroup limitations for the ipsec daemon] ********
changed: [54.71.187.11]

TASK [vpn : Iptables configured] ***********************************************
changed: [54.71.187.11] => (item={u'dest': u'/etc/iptables/rules.v4', u'src': u'rules.v4.j2'})

TASK [vpn : Iptables configured] ***********************************************
changed: [54.71.187.11] => (item={u'dest': u'/etc/iptables/rules.v6', u'src': u'rules.v6.j2'})

TASK [vpn : FreeBSD / HardenedBSD | Get the existing kernel parameters] ********
skipping: [54.71.187.11]

TASK [vpn : FreeBSD / HardenedBSD | Set the rebuild_needed fact] ***************
skipping: [54.71.187.11] => (item=IPSEC)
skipping: [54.71.187.11] => (item=IPSEC_NAT_T)
skipping: [54.71.187.11] => (item=crypto)

TASK [vpn : FreeBSD / HardenedBSD | Make the kernel config] ********************
skipping: [54.71.187.11]

TASK [vpn : FreeBSD / HardenedBSD | Ensure the all options are enabled] ********
skipping: [54.71.187.11] => (item=options       IPSEC)
skipping: [54.71.187.11] => (item=options IPSEC_NAT_T)
skipping: [54.71.187.11] => (item=device        crypto)

TASK [vpn : HardenedBSD | Determine the sources] *******************************
skipping: [54.71.187.11]

TASK [vpn : FreeBSD | Determine the sources] ***********************************
skipping: [54.71.187.11]

TASK [vpn : FreeBSD / HardenedBSD | Increase the git postBuffer size] **********
skipping: [54.71.187.11]

TASK [vpn : FreeBSD / HardenedBSD | Fetching the sources...] *******************
skipping: [54.71.187.11]

TASK [vpn : FreeBSD / HardenedBSD | Fetching the sources...] *******************
skipping: [54.71.187.11]

TASK [vpn : FreeBSD / HardenedBSD | The kernel is being built...] **************
skipping: [54.71.187.11]

TASK [vpn : FreeBSD / HardenedBSD | The kernel is being built...] **************
skipping: [54.71.187.11]

TASK [vpn : FreeBSD / HardenedBSD | Reboot] ************************************
skipping: [54.71.187.11]

TASK [vpn : FreeBSD / HardenedBSD | Enable strongswan] *************************
skipping: [54.71.187.11]

TASK [vpn : Install strongSwan] ************************************************
ok: [54.71.187.11]

TASK [vpn : Get StrongSwan versions] *******************************************
changed: [54.71.187.11]

TASK [vpn : Setup the config files from our templates] *************************
changed: [54.71.187.11] => (item={u'dest': u'/etc/strongswan.conf', u'src': u'strongswan.conf.j2', u'group': u'root', u'mode': u'0644', u'owner': u'root'})
changed: [54.71.187.11] => (item={u'dest': u'/etc/ipsec.conf', u'src': u'ipsec.conf.j2', u'group': u'root', u'mode': u'0644', u'owner': u'root'})
changed: [54.71.187.11] => (item={u'dest': u'/etc/ipsec.secrets', u'src': u'ipsec.secrets.j2', u'group': u'root', u'mode': u'0600', u'owner': u'strongswan'})

TASK [vpn : Get loaded plugins] ************************************************
changed: [54.71.187.11]

TASK [vpn : Disable unneeded plugins] ******************************************
skipping: [54.71.187.11] => (item=kernel-netlink)
skipping: [54.71.187.11] => (item=stroke)
skipping: [54.71.187.11] => (item=socket-default)
skipping: [54.71.187.11] => (item=pgp)
skipping: [54.71.187.11] => (item=random)
skipping: [54.71.187.11] => (item=hmac)
changed: [54.71.187.11] => (item=fips-prf)
skipping: [54.71.187.11] => (item=aes)
changed: [54.71.187.11] => (item=attr)
changed: [54.71.187.11] => (item=gmp)
skipping: [54.71.187.11] => (item=x509)
changed: [54.71.187.11] => (item=md5)
changed: [54.71.187.11] => (item=connmark)
skipping: [54.71.187.11] => (item=sha2)
changed: [54.71.187.11] => (item=pkcs1)
skipping: [54.71.187.11] => (item=openssl)
changed: [54.71.187.11] => (item=resolve)
changed: [54.71.187.11] => (item=dnskey)
changed: [54.71.187.11] => (item=md4)
changed: [54.71.187.11] => (item=constraints)
changed: [54.71.187.11] => (item=updown)
skipping: [54.71.187.11] => (item=pkcs12)
skipping: [54.71.187.11] => (item=pem)
changed: [54.71.187.11] => (item=test-vectors)
changed: [54.71.187.11] => (item=xcbc)
changed: [54.71.187.11] => (item=agent)
skipping: [54.71.187.11] => (item=pkcs7)
changed: [54.71.187.11] => (item=sshkey)
skipping: [54.71.187.11] => (item=nonce)
changed: [54.71.187.11] => (item=sha1)
skipping: [54.71.187.11] => (item=gcm)
skipping: [54.71.187.11] => (item=pubkey)
changed: [54.71.187.11] => (item=rc2)
skipping: [54.71.187.11] => (item=pkcs8)
skipping: [54.71.187.11] => (item=revocation)

TASK [vpn : Ensure that required plugins are enabled] **************************
changed: [54.71.187.11] => (item=kernel-netlink)
changed: [54.71.187.11] => (item=stroke)
changed: [54.71.187.11] => (item=socket-default)
changed: [54.71.187.11] => (item=pgp)
changed: [54.71.187.11] => (item=random)
changed: [54.71.187.11] => (item=hmac)
skipping: [54.71.187.11] => (item=fips-prf)
changed: [54.71.187.11] => (item=aes)
skipping: [54.71.187.11] => (item=attr)
skipping: [54.71.187.11] => (item=gmp)
changed: [54.71.187.11] => (item=x509)
skipping: [54.71.187.11] => (item=md5)
skipping: [54.71.187.11] => (item=connmark)
changed: [54.71.187.11] => (item=sha2)
skipping: [54.71.187.11] => (item=pkcs1)
changed: [54.71.187.11] => (item=openssl)
skipping: [54.71.187.11] => (item=resolve)
skipping: [54.71.187.11] => (item=dnskey)
skipping: [54.71.187.11] => (item=md4)
skipping: [54.71.187.11] => (item=constraints)
skipping: [54.71.187.11] => (item=updown)
changed: [54.71.187.11] => (item=pkcs12)
changed: [54.71.187.11] => (item=pem)
skipping: [54.71.187.11] => (item=test-vectors)
skipping: [54.71.187.11] => (item=xcbc)
skipping: [54.71.187.11] => (item=agent)
changed: [54.71.187.11] => (item=pkcs7)
skipping: [54.71.187.11] => (item=sshkey)
changed: [54.71.187.11] => (item=nonce)
skipping: [54.71.187.11] => (item=sha1)
changed: [54.71.187.11] => (item=gcm)
changed: [54.71.187.11] => (item=pubkey)
skipping: [54.71.187.11] => (item=rc2)
changed: [54.71.187.11] => (item=pkcs8)
changed: [54.71.187.11] => (item=revocation)

TASK [vpn : Ensure the pki directory is not exist] *****************************
skipping: [54.71.187.11]

TASK [vpn : Ensure the pki directories are exist] ******************************
changed: [54.71.187.11 -> localhost] => (item=ecparams)
changed: [54.71.187.11 -> localhost] => (item=certs)
changed: [54.71.187.11 -> localhost] => (item=crl)
changed: [54.71.187.11 -> localhost] => (item=newcerts)
changed: [54.71.187.11 -> localhost] => (item=private)
changed: [54.71.187.11 -> localhost] => (item=reqs)

TASK [vpn : Ensure the files are exist] ****************************************
changed: [54.71.187.11 -> localhost] => (item=.rnd)
changed: [54.71.187.11 -> localhost] => (item=private/.rnd)
changed: [54.71.187.11 -> localhost] => (item=index.txt)
changed: [54.71.187.11 -> localhost] => (item=index.txt.attr)
changed: [54.71.187.11 -> localhost] => (item=serial)

TASK [vpn : Generate the openssl server configs] *******************************
changed: [54.71.187.11 -> localhost]

TASK [vpn : Build the CA pair] *************************************************
changed: [54.71.187.11 -> localhost]

TASK [vpn : Copy the CA certificate] *******************************************
changed: [54.71.187.11 -> localhost]

TASK [vpn : Generate the serial number] ****************************************
changed: [54.71.187.11 -> localhost]

TASK [vpn : Build the server pair] *********************************************
changed: [54.71.187.11 -> localhost]

TASK [vpn : Build the client's pair] *******************************************
changed: [54.71.187.11 -> localhost] => (item=steve)
changed: [54.71.187.11 -> localhost] => (item=pam)

TASK [vpn : Build the client's p12] ********************************************
changed: [54.71.187.11 -> localhost] => (item=steve)
changed: [54.71.187.11 -> localhost] => (item=pam)

TASK [vpn : Copy the p12 certificates] *****************************************
changed: [54.71.187.11 -> localhost] => (item=steve)
changed: [54.71.187.11 -> localhost] => (item=pam)

TASK [vpn : Copy the keys to the strongswan directory] *************************
changed: [54.71.187.11] => (item={u'dest': u'/etc/ipsec.d/cacerts/ca.crt', u'src': u'configs/54.71.187.11/pki/cacert.pem', u'group': u'root', u'mode': u'0600', u'owner': u'strongswan'})
changed: [54.71.187.11] => (item={u'dest': u'/etc/ipsec.d/certs/54.71.187.11.crt', u'src': u'configs/54.71.187.11/pki/certs/54.71.187.11.crt', u'group': u'root', u'mode': u'0600', u'owner': u'strongswan'})
changed: [54.71.187.11] => (item={u'dest': u'/etc/ipsec.d/private/54.71.187.11.key', u'src': u'configs/54.71.187.11/pki/private/54.71.187.11.key', u'group': u'root', u'mode': u'0600', u'owner': u'strongswan'})

TASK [vpn : Register p12 PayloadContent] ***************************************
changed: [54.71.187.11 -> localhost] => (item=steve)
changed: [54.71.187.11 -> localhost] => (item=pam)

TASK [vpn : Set facts for mobileconfigs] ***************************************
ok: [54.71.187.11]

TASK [vpn : Build the mobileconfigs] *******************************************
changed: [54.71.187.11 -> localhost] => (item=(censored due to no_log))
changed: [54.71.187.11 -> localhost] => (item=(censored due to no_log))

TASK [vpn : Build the strongswan app android config] ***************************
changed: [54.71.187.11 -> localhost] => (item=(censored due to no_log))
changed: [54.71.187.11 -> localhost] => (item=(censored due to no_log))

TASK [vpn : Build the client ipsec config file] ********************************
changed: [54.71.187.11 -> localhost] => (item=steve)
changed: [54.71.187.11 -> localhost] => (item=pam)

TASK [vpn : Build the client ipsec secret file] ********************************
changed: [54.71.187.11 -> localhost] => (item=steve)
changed: [54.71.187.11 -> localhost] => (item=pam)

TASK [vpn : Build the windows client powershell script] ************************
changed: [54.71.187.11 -> localhost] => (item=steve)
changed: [54.71.187.11 -> localhost] => (item=pam)

TASK [vpn : Restrict permissions for the local private directories] ************
changed: [54.71.187.11 -> localhost] => (item=configs/54.71.187.11)

RUNNING HANDLER [vpn : restart strongswan] *************************************
changed: [54.71.187.11]

RUNNING HANDLER [vpn : daemon-reload] ******************************************
changed: [54.71.187.11]

RUNNING HANDLER [vpn : restart iptables] ***************************************
changed: [54.71.187.11]

TASK [vpn : strongSwan started] ************************************************
ok: [54.71.187.11]

TASK [debug] *******************************************************************
ok: [54.71.187.11] => {
    "msg": [
        [
            "\"#                          Congratulations!                            #\"",
            "\"#                     Your Algo server is running.                     #\"",
            "\"#    Config files and certificates are in the ./configs/ directory.    #\"",
            "\"#              Go to https://whoer.net/ after connecting               #\"",
            "\"#        and ensure that all your traffic passes through the VPN.      #\"",
            "\"#               Local DNS resolver 172.16.0.1              #\"",
            ""
        ],
        "    \"#                The p12 and SSH keys password is xxxxxxxx             #\"\n",
        "    ",
        "    \"#      Shell access: ssh -i configs/algo.pem ubuntu@54.71.187.11        #\"\n"
    ]
}

TASK [Delete the CA key] *******************************************************
changed: [54.71.187.11 -> localhost]

PLAY RECAP *********************************************************************
54.71.187.11               : ok=62   changed=46   unreachable=0    failed=0
localhost                  : ok=19   changed=4    unreachable=0    failed=0

**Comment by dguido** [comment]
Sorry, I misread this issue the first time. You included a lot of conflicting information in the issue description (Ubuntu, Project Fi, Google Voice, etc).

I can confirm that Google Hangouts from Windows when connected via Algo VPN works fine.

**Comment by Steve9F** [comment]
@dguido - can you confirm that Google Voice is working? Hangouts text works but my issue is with calling. I've confirmed that I can't make outbound calls with either Google Voice or Project Fi (fi shares the same infrastructure as Google Voice).

**Comment by dguido** [comment]
If you're asking about the Android client now, we have no reported issues when configured with the strongSwan Android app as described in the readme.

**Comment by Steve9F** [comment]
@dguido - no, this is about Window 10 using Hangouts in Chrome.
