### ISSUE TITLE
Measure data usage savings from adblocking/compression

### ISSUE THREAD

**Issue by dguido** [trailofbits/algo#50]
We should do an experiment to see how much of an impact the dns ad-blocking and proxies have.

Visit the Alexa top 100 and record the size of the data transfer and speed:
1. Only the VPN
2. VPN + PageSpeed
3. VPN + DNS ad-blocking
4. VPN + Proxy ad-blocking
5. VPN + DNS and Proxy ad-blocking + PageSpeed

**Comment by dguido** [comment]
$100 bounty! Submit a pull request and email dan@trailofbits.com to claim it. Partial solutions may be rewarded.

**Comment by 211217613** [comment]
Is their some methodology that works for this benchmark? I'm thinking about how to set up the experiment, but wouldn't their be a lot of variability with WiFi and connection reliability? The only way I can think of doing it is just testing multiple times throughout the day and averaging.

**Comment by dguido** [comment]
That sounds like a reasonable approach. I just want to know, given the cost to maintain this functionality, the extra processing overhead, and the administrative issues that people encounter, what are we getting for it? Is the amount of data saved substantial?

**Comment by jauderho** [comment]
I'm pretty happy with my use of ublock origin.

This is not directly representative of what you are asking about/for but using ublock origin does save a fair bit in terms of mem usage and data transfer. See https://github.com/gorhill/uBlock#performance

Personally, I have a combined hosts file from a number of sources that I point dnsmasq to. Seems to work well. 

It depends on how far you want to take this, dnsmasq + dnscrypt shipped as part of algo?
