### ISSUE TITLE
Fatal error on "Build the CA pair" task on new deploy to DigitalOcean

### ISSUE THREAD

**Issue by zanon** [trailofbits/algo#500]
### OS / Environment
macOS 10.12.4, target deployment 512mb DigitalOcean Droplet.

### Ansible version
ansible 2.2.0.0

### Version of components from `requirements.txt`
setuptools: 35.0.2
ansible: 2.2.0.0
dopy: 0.3.5
boto: 2.46.1
boto3:  1.4.4
azure: 2.0.0rc5
msrest: 0.4.1
apache-libcloud: 2.0.0
six: 1.10.0
pyopenssl: 17.0.0
jinja2: 2.8

### Summary of the problem
I attempted to make a brand new algo deployment for the first time to test it out using DigitalOcean as the cloud provider. algo appeared to install and run normally, answered the questions and then it proceeded all the way through until the TASK [vpn : Build the CA pair] at which point it fatally failed. Multiple attempts were made (destroying droplet each time and trying some different question answers) to no avail.

### Steps to reproduce the behavior
Proceed with standard ./algo run and that's it. Answers to questions:
Do you want macOS/iOS clients to enable "VPN On Demand" when connected to cellular networks?
[y/N]: y

Do you want macOS/iOS clients to enable "VPN On Demand" when connected to Wi-Fi?
[y/N]: y

List the names of trusted Wi-Fi networks (if any) that macOS/iOS clients exclude from using the VPN (e.g., your home network. Comma-separated value, e.g., HomeNet,OfficeWifi,AlgoWiFi)
: Office WiFi

Do you want to install a DNS resolver on this VPN server, to block ads while surfing?
[y/N]: y

Do you want each user to have their own account for SSH tunneling?
[y/N]: N

Do you want to apply operating system security enhancements on the server? (warning: replaces your sshd_config)
[y/N]: y

Do you want the VPN to support Windows 10 or Linux Desktop clients? (enables compatible ciphers and key exchange, less secure)
[y/N]: N

Do you want to retain the CA key? (required to add users in the future, but less secure)
[y/N]: y (**Tried this with both yes and no**)

### The way of deployment (cloud or local)
cloud.

### Expected behavior
That it would deploy and give the success message and files in configs as stated in the instructions.

### Actual behavior
It didn't.

### Full log
TASK [vpn : Build the CA pair] *************************************************
fatal: [*droplet.ip_addr* -> localhost]: FAILED! => {"changed": true, "cmd": "openssl ecparam -name prime256v1 -out ecparams/prime256v1.pem &&\n openssl req -utf8 -new -newkey ec:ecparams/prime256v1.pem -config openssl.cnf -keyout private/cakey.pem -out cacert.pem -x509 -days 3650 -batch -passout pass:\"791890a0f4820bca5776d0321c3bda01\" &&\n touch *droplet.ip_addr*_ca_generated", "delta": "0:00:00.022172", "end": "2017-04-28 01:35:28.838806", "failed": true, "rc": 1, "start": "2017-04-28 01:35:28.816634", "stderr": "error on line 113 of openssl.cnf\n140736375227400:error:0EFFF068:configuration file routines:CRYPTO_internal:variable has no value:conf/conf_def.c:563:line 113", "stdout": "", "stdout_lines": [], "warnings": []}

RUNNING HANDLER [dns_adblocking : restart apparmor] ****************************

RUNNING HANDLER [vpn : restart strongswan] *************************************

RUNNING HANDLER [vpn : daemon-reload] ******************************************

RUNNING HANDLER [vpn : restart iptables] ***************************************

PLAY RECAP *********************************************************************
*droplet.ip_addr*              : ok=76   changed=58   unreachable=0    failed=1   
localhost                  : ok=19   changed=6    unreachable=0    failed=0

**Comment by gunph1ld** [comment]
@zanon Can you show the output `openssl version` ?

**Comment by zanon** [comment]
@gunph1ld Thank you, that set me on the right path, interesting. I switched to using libressl exclusively a long time ago and I never had any problems before so I'd forgotten about it.
`openssl version`
`LibreSSL 2.5.3`
Changing my shell environment to point to the default
`which openssl`
`/usr/bin/openssl`
`openssl version`
`OpenSSL 0.9.8zh 14 Jan 2016`
resulted in successful deployment. So there is some difference between the operation of openssl and libressl causing a failure in this case. I'm not sure who to go up the chain to on that. For the time being it'd probably be fine to just note as an errata that system supplied ssl should be used (or do an assert to make sure it's a version you expect) but longer term I think for a security oriented product being able to coexist with libressl would be a benefit. Thanks for the prompt help on a fix here.
