### ISSUE TITLE
Connection on Desktop, possibly too slow?

### ISSUE THREAD

**Issue by Starz0r** [trailofbits/algo#501]
### OS / Environment

Windows 10 - Redstone 2 ~ Client
Ubuntu 16.04 ~ Server

### Ansible version

ansible 2.3.0.0

### Version of components from `requirements.txt`

msrestazure ~ 0.4.7
setuptools ~ 20.7.0
ansible ~ 2.3.0.0
dopy ~ 0.3.7
boto ~ 2.46.1
azure ~ 1.0.3
msrest ~ 0.4.7
apache-libcloud ~ 2
six ~ 1.10.0
pyopenssl ~ 17
jinja2 ~ 2.8

### Summary of the problem
It appears Windows 10 allows me to connect to the VPN, but it appears that the connection to it is getting throttled to just mere bytes, according to GlassWire at least. To test this, I also opened up a bash shell and curl'd ipinfo.io just to test if I was connected to the VPN successfully, and it appears that I was. Steam also connects to the server successfully, showing that I am offline, but applications like Discord refused to connect, and my browser (Chromium based) was just showing an error "Proxy server connection failed", even though this isn't true. I even tried the connection on my Android phone just to make sure, and it works just fine there without an issue.

### Steps to reproduce the behavior
1. Choose a Provider of Choice with a compatible Operating System, here I used Ubuntu 16.04 on Vultr.
2. Follow this [guide](https://github.com/trailofbits/algo/issues/488#issuecomment-296986377)
3. Follow standard Windows setup instructions
4. Start the VPN, if it can't connect, go to step 5, if it does, skip to step 6.
5. Restart the computer, try step 4 again.
6. Open GlassWire and look at the speeds in the Firewall Tab.

### The way of deployment (cloud or local)
[Vultr](https://vultr.com)

### Expected behavior
The connection should not be throttled on Windows 10 Desktop, and should run at full speed.

### Actual behavior
The connection is throttled below a few bytes, making the service unusable on Desktop.

**Comment by dguido** [comment]
What happens if you deploy on a supported provider?

**Comment by Starz0r** [comment]
No way for me to test since I don't have an account with any other provider listed. Plus, none of the other providers have any locations close to me, Vultr is the only VPS provider I found that satisfies this.

**Comment by dguido** [comment]
We can't effectively troubleshoot this issue unless you try another provider, since the issue may be Vultr. There's more to supporting IPSEC than simply providing the right kernel modules. We've found a few VPS providers that limit and interfere with network traffic too.

**Comment by Starz0r** [comment]
I could try DigitalOcean. Is it possible to setup on a Droplet that's already deployed, without messing up things like the Reverse Proxy I use for web hosting? I know the shell script messes with iptables, but I don't exactly know what it does. An uninstall script would be useful in this case.

**Comment by dguido** [comment]
Please do it on a fresh VM so we know it's working.

**Comment by ookangzheng** [comment]
I'm using vultr 17.04 fresh VM in LA, Singapore without any problem
but i haven't tried on Windows 10 , only Mac, Ipad, iPhone, Android

**Comment by Starz0r** [comment]
@dguido Pleasantly surprised that using a DigitalOcean droplet works just fine, while Vultr does not. Although, this isn't an optimal setup for me since the only choices for deployment that DigitalOcean gives is hundreds of miles away from my location, increasing latency by a lot. What does this mean for Vultr then? I imagine there is some way to test what's going wrong on their end?

**Comment by dguido** [comment]
Probably best suited for the ticket already open for Vultr. Glad it worked on one of our supported providers.
