### ISSUE TITLE
Algo stops working roughly 18 hrs after deployment

### ISSUE THREAD

**Issue by wiiind** [trailofbits/algo#503]
### OS / Environment

Azure / AWS

### Ansible version

2.2.0.0

### Version of components from `requirements.txt`

ansible (2.2.0.0)
apache-libcloud (1.5.0)
azure (2.0.0rc5)
boto (2.46.1)
boto3 (1.4.4)
dopy (0.3.5)
Jinja2 (2.8)
msrestazure (0.4.7)
pyOpenSSL (17.0.0)
setuptools (35.0.2)
six (1.10.0)

### Summary of the problem
Freshly deployed algo stops working after roughly 18 hrs ( 0ed68b6c303ef337c07abd98b7956e1b6c5da6e7 ). Tests with ipleak.net when connected to algo would reveal your real IP instead of the server IP on Windows 10. On Apple devices, it would lose internet connection completely even though the VPN conection shows connected.  I am not able to produce logs to demonstrate the problem because "ipsec restart --nofork" would make it work again for another ~18 hrs.

### Steps to reproduce the behavior
Deploy fresh to Azure or AWS and wait roughly 18 hrs. 

### The way of deployment (cloud or local)
cloud

### Expected behavior
Connection should continue to be routed through algo.

### Actual behavior
Connection stops been routed through algo roughly 18 hrs after deployment.

### Full log

  What provider would you like to use?
    1. DigitalOcean
    2. Amazon EC2
    3. Microsoft Azure
    4. Google Compute Engine (only for testing, see issue #369)
    5. Install to existing Ubuntu 16.04 server

Enter the number of your desired provider
: 3

Enter your azure secret id (https://github.com/trailofbits/algo/blob/master/docs/cloud-azure.md)
You can skip this step if you want to use your defaults credentials from ~/.azure/credentials
[pasted values will not be displayed]
[...]:

Enter your azure tenant id (https://github.com/trailofbits/algo/blob/master/docs/cloud-azure.md)
You can skip this step if you want to use your defaults credentials from ~/.azure/credentials
[pasted values will not be displayed]
[...]:

Enter your azure client id (application id) (https://github.com/trailofbits/algo/blob/master/docs/cloud-azure.md)
You can skip this step if you want to use your defaults credentials from ~/.azure/credentials
[pasted values will not be displayed]
[...]:

Enter your azure subscription id (https://github.com/trailofbits/algo/blob/master/docs/cloud-azure.md)
You can skip this step if you want to use your defaults credentials from ~/.azure/credentials
[pasted values will not be displayed]
[...]:

Name the vpn server:
[algo]: algoAzuEaUS

  What region should the server be located in? (https://azure.microsoft.com/en-us/regions/)
    1.  South Central US
    2.  Central US
    3.  North Europe
    4.  West Europe
    5.  Southeast Asia
    6.  Japan West
    7.  Japan East
    8.  Australia Southeast
    9.  Australia East
    10. Canada Central
    11. West US 2
    12. West Central US
    13. UK South
    14. UK West
    15. West US
    16. Brazil South
    17. Canada Central
    18. Central India
    19. East Asia
    20. Germany Central
    21. Germany Northeast
    22. Korea Central
    23. Korea South
    24. North Central US
    25. South India
    26. West India
    27. East US
    28. East US 2

Enter the number of your desired region:
[1]: 27

Do you want macOS/iOS clients to enable "VPN On Demand" when connected to cellular networks?
[y/N]: y

Do you want macOS/iOS clients to enable "VPN On Demand" when connected to Wi-Fi?
[y/N]: y

List the names of trusted Wi-Fi networks (if any) that macOS/iOS clients exclude from using the VPN (e.g., your home network. Comma-separated value, e.g., HomeNet,OfficeWifi,AlgoWiFi)
:

Do you want to install a DNS resolver on this VPN server, to block ads while surfing?
[y/N]:

Do you want each user to have their own account for SSH tunneling?
[y/N]:

Do you want to apply operating system security enhancements on the server? (warning: replaces your sshd_config)
[y/N]: y

Do you want the VPN to support Windows 10 or Linux Desktop clients? (enables compatible ciphers and key exchange, less secure)
[y/N]: y

Do you want to retain the CA key? (required to add users in the future, but less secure)
[y/N]:

**Comment by dguido** [comment]
This issue is probably resolved by this pull request:

https://github.com/trailofbits/algo/pull/498

**Comment by wiiind** [comment]
I tried commit from #498 and that was problematic for Apple devices because of dpd....

**Comment by dguido** [comment]
Upgrade to Ubuntu 17.04

**Comment by wiiind** [comment]
My understanding is that Ubuntu 17.04 is not available for Azure. If Ubuntu 17.04 is recommended, what is the best solution for Azure?

**Comment by dguido** [comment]
There is none.

**Comment by wiiind** [comment]
I see. Thanks!

**Comment by purduepete** [comment]
I'm running on Azure and after the initial install, I upgraded to 17.04 (it's a two step process; 16.04 LTS -> 16.10 -> 17.04)

A bit more work, but resolves problems I was having.

**Comment by wiiind** [comment]
Thanks for the tips @purduepete !

I kicked off the process of upgrading to 16.10. But I got prompted asking whether to keep modified sysctl.conf or install the package maintainer's version. I went with keeping the modifed version. Hope everything works!

**Comment by wiiind** [comment]
I ended up updating to the maintainer's version for some sshd and unattended conf files because there were too much differences between 16.10 and 17.04. But everything seems to be working great so far!
