### ISSUE TITLE
Port forwarding for use with dynamic DNS services

### ISSUE THREAD

**Issue by rkpatel33** [trailofbits/algo#504]
I want to run a local server that can be reached using www.noip.com dynamic DNS service (specifically trying to set this up: https://github.com/rgraciano/echo-sonos).

Is there anything special I need to do in terms of opening up ports on the VPN server (port 5005 in this case) so that I can hit the server from outside my local network?

I am new to using VPNs but I do already have an Amazon VPN server setup and working via this project.

Thx.

**Comment by dguido** [comment]
I'm glad Algo worked for you. This is for reporting bugs and problems with Algo. Since it looks like everything went right, I'm going to close this ticket. You should seek support from the service you want to use, or try our Slack.

**Comment by rkpatel33** [comment]
Thanks. Sorry about that. 

On Apr 29, 2017, at 7:19 PM, Dan Guido <notifications@github.com> wrote:

Closed #504.
