### ISSUE TITLE
Correction to README.md re. SSH

### ISSUE THREAD

**Issue by shawnyeager** [trailofbits/algo#507]
Currently, the instructions for SSH into algo for adminstrative purposes states `ubuntu@ip`, where it should (at least as of my build) be`root@ip`.

**Comment by dguido** [comment]
It depends on the cloud provider you choose

**Comment by shawnyeager** [comment]
I'm referring to this repo's [README](https://github.com/trailofbits/algo/blob/master/README.md#ssh-into-algo-server).

**Comment by dguido** [comment]
Yes, there are differences between cloud providers. For instance, all AWS Ubuntu VMs use `ubuntu` but DigitalOcean use `root`. Those parts of the readme are there as template commands to modify. The correct values are printed out by final message in the deploy along with your keys.
