### ISSUE TITLE
Couldn't update user 

### ISSUE THREAD

**Issue by alechangbiao** [trailofbits/algo#508]
### OS / Environment

macOS

### Ansible version

Sorry I don't know how to check. :-( 

### Version of components from `requirements.txt`

msrestazure
setuptools>=11.3
ansible>=2.1,<2.2.1
dopy==0.3.5
boto>=2.5
boto3
azure==2.0.0rc5
msrest==0.4.1
apache-libcloud
six
pyopenssl
jinja2==2.8

### Summary of the problem

Couldn't update user when following the steps on "Adding or Removing Users", I installed the VPN server on DigitalOcean and it work pretty well, but couldn't add users. 

### Steps to reproduce the behavior

hangbiaodeMacBook-Pro:algo-master HangBiao$ source env/bin/activate
(env) hangbiaodeMacBook-Pro:algo-master HangBiao$ ./algo update-users

Enter the IP address of your server: (or use localhost for local installation)
: 162.243.148.151

What user should we use to login on the server? (note: passwordless login required, or ignore if you're deploying to localhost)
[root]: alechang

Do you want each user to have their own account for SSH tunneling?
[y/N]: y

Enter the public IP address of your server: (IMPORTANT! This IP is used to verify the certificate)
[162.243.148.151]: 162.243.148.151

Enter the password for the private CA key:
[pasted values will not be displayed]
: ./algo: line 443: ansible-playbook: command not found

### The way of deployment (cloud or local)

cloud

### Expected behavior

new user added and username.mobileconfig file generated

### Actual behavior

couldn't add new user for : ./algo: line 443: ansible-playbook: command not found

**Comment by dguido** [comment]
Please read the directions, you're not running Algo properly.

**Comment by alechangbiao** [comment]
I did followed the direction it step by step to installed it

**Comment by alechangbiao** [comment]
couldn't find the algo directory tho
