### ISSUE TITLE
Make ipsec.conf more easily extendable

### ISSUE THREAD

**Issue by davidemyers** [trailofbits/algo#513]
This is an enhancement request.

Please consider moving the non-authentication-related parameters  in `/etc/ipsec.conf` out of `conn %default` and into `conn ikev2-pubkey`, specifically `leftsubnet`, `rightsourceip`, and `rightdns`. This would make it easier to extend an Algo instance to handle additional connections, such as  a site-to-site router connection, by appending an additional `conn` section to the file.

In testing this appears to work fine, but someone with more strongSwan experience than I should have a look at it.

**Comment by adrianz** [comment]
> such as a site-to-site router connection

I've only recently started playing with VPNs and my knowledge and understanding of this topic is far from perfect, so please forgive me for possibly a very basic question: does that mean connecting to an Algo VPN server from a mobile device (laptop, smartphone) from an insecure network would give me a secure access to my local network resources at home/office through Algo's site-to-site connection to my home/office LAN? Like this:

```
iPhone <---> Algo server <--S2S connection--> My home router <---> My LAN
```

If that's the case then I'm  👍

**Comment by davidemyers** [comment]
When I refer to a site-to-site router connection, what I mean is for a home/office router to connect directly to an Algo VPN server so local traffic goes out over the VPN without having to change the configuration of any of the devices on the network.

In theory I guess it could support what you're asking for but not without extra firewall rules on both the Algo server and your router.

**Comment by lance0** [comment]
You just need to make sure you have the IPSec tunnel as your default gateway at your endpoint .

**Comment by davidemyers** [comment]
Closing this request. Turns out you can unset previously defined parameters in a new `conn` section. For example, `rightsourceip=` is legal and removes the previous definition from `conn %default`.
