### ISSUE TITLE
Pycrypto requires custom CFLAGS on macOS with Homebrew gmp

### ISSUE THREAD

**Issue by lazzarello** [trailofbits/algo#516]
### OS / Environment

macOS Sierra

### Ansible version
n/a

### Version of components from `requirements.txt`
(env) [lazzarello@strop algo (master)]$ pip show pycrypto
Name: pycrypto
Version: 2.6.1
Summary: Cryptographic modules for Python.
Home-page: http://www.pycrypto.org/
Author: Dwayne C. Litzenberger
Author-email: dlitz@dlitz.net
License: UNKNOWN
Location: algo/env/lib/python2.7/site-packages
Requires:

### Summary of the problem

pip can't find gmp.h when compiling pycrypto. The solution is to install gmp via homebrew and export custom cflags. Probably a good idea to document this somewhere. Creating an issue for now.

```
brew install gmp
export "CFLAGS=-I/usr/local/include -L/usr/local/lib"
pip install pycrypto
```

**Comment by dguido** [comment]
Thanks! Yeah this might be a good idea for the Troubleshooting page.

**Comment by dguido** [comment]
This does not appear to happen in any default state, only when you've modified your system somehow. I'm not able to reproduce the issue.

**Comment by jereze** [comment]
Thanks, was usefull for me.

**Comment by mhomidi** [comment]
My Mac has this library bulid-in on my Xcode

**Comment by HDallakyan** [comment]
Thank you! works!

**Comment by sairoko12** [comment]
Thank you so much, it works! 🙌
