### ISSUE TITLE
Invalid Payload Received

### ISSUE THREAD

**Issue by doodlemania2** [trailofbits/algo#518]
### OS / Environment
Windows 10 16184 as client.

### Ansible version
Latest (deployed from Linux)

### Version of components from `requirements.txt`
Latest (deployed from Linux)

### Summary of the problem
After configuring on a local Linux box and deploying to Azure, Linux connects great. Brought ps1 files and cert files over to Windows 10 16184 and ran cleanly. Attempt to connect returns: Invalid Payload Received.

### Steps to reproduce the behavior
Deploy from Linux to Azure
Confirm VPN connects good from Linux
Move ps1 files and certs to Windows 10
Execute as admin
Attempt to connect

### The way of deployment (cloud or local)
Local deployed Azure

### Expected behavior
Good connection

### Actual behavior
Invalid Payload Received

**Comment by Starz0r** [comment]
You'll need to install the Redstone 2 update if you plan on using Windows 10 as the Client computer.

**Comment by dguido** [comment]
No, that's not it. I think Windows 10 build 16184 is current enough to work.

doodlemania2, your Windows 10 VPN is not configured to use the proper ciphers. Make sure the PowerShell script was applied successfully and changed the parameters that the VPN uses to connect. You can also see #514 for how you can get info from the server that might help you troubleshoot it.

**Comment by doodlemania2** [comment]
Yeah, Win10 16184 is Redstone 2 + a few builds.

Deleted and re-reran the script:
![image](https://cloud.githubusercontent.com/assets/5252217/25724262/f2edf5ac-30e0-11e7-9fa8-d2ee7e0ef028.png)

Same error :(

**Comment by Starz0r** [comment]
Are you running the script as Admin?

**Comment by doodlemania2** [comment]
Yes indeed, is there a log from the server I can grab that might help?
