### ISSUE TITLE
Support local installation

### ISSUE THREAD

**Issue by dguido** [trailofbits/algo#52]
We support "remote" installation where we provide the IP and a username to access a device. However, "local" installation is where the user has downloaded algo directly to the server they want to install to. In this mode of installation, there is no need to use SSH.

There are a few issues to overcome to support running the playbooks directly on the target server:

1. The UI for initial installation and user management. We want to keep both of them as simple as possible. That means avoid creating new options where possible.
2. The documentation. We need to add something to the readme that is easy to understand. In order to install algo on Ubuntu locally, you need to install ansible first. Installing ansible via pip requires pulling in a lot of dependencies, including a full compiler suite. It is easier to use apt, however, Ubuntu 16.04 only comes with ansible 2.0.0.2. Therefore, to use apt you must use the ansible PPA and using a PPA requires installing `software-properties-common`.

3. The bash script does not run in Ubuntu 16.04. /bin/sh on Ubuntu is the `dash` shell, not bash, and the `-s` option is not valid. We need to edit the run script to deploy from Ubuntu. The one place in particular where we run into this issue is prompting for the certificate password, which we could remove from the shell script and add to the ansible script.

Here are the dependencies we need for local installation on Ubuntu 16.04:
```
sudo apt-get install software-properties-common && sudo apt-add-repository ppa:ansible/ansible
sudo apt-get update && sudo apt-get install ansible
```

@computerality opened a pull request (#47) where some of these issues were discussed.

Sidenote: we may want to use the [shellcheck](https://github.com/koalaman/shellcheck) [linter](https://www.shellcheck.net/) to polish up the initial script and find and fix any other compatibility issues.

**Comment by gunph1ld** [comment]
Merged
