### ISSUE TITLE
deploy_client.yml requires sudo and fails without previous sudo elevation

### ISSUE THREAD

**Issue by GMNGeoffrey** [trailofbits/algo#529]
### OS / Environment
Ubuntu 16.04

### Ansible version
2.2.0.0

### Summary of the problem
When I run deploy_client.yml, it tries to sudo, which fails if I haven't recently sudo-ed.

### Steps to reproduce the behavior
Run the command [here](https://github.com/trailofbits/algo/blob/master/docs/client-linux.md) in a new terminal. It fails, asking for the sudo password. Run sudo anything and type in password. Run command again and it proceeds.

### The way of deployment (cloud or local)
Cloud

### Expected behavior
The command should acquire the elevated privileges it needs in a way that succeeds every time.

### Actual behavior
The command fails if you have not recently sudo-ed (and so the sudo password is required).

### Full log
```
$ ansible-playbook deploy_client.yml -e 'client_ip=localhost vpn_user=gcmn server_ip=104.198.8.238 server_ssh_user=root'

PLAY [Configure the client] ****************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Add the droplet to an inventory group] ***********************************
changed: [localhost]

PLAY [Configure the client and install required software] **********************

TASK [Get the OS] **************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "failed": true, "rc": 1, "stderr": "sudo: a password is required\n", "stdout": "", "stdout_lines": []}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=1   

$ sudo echo hello
[sudo] password for geoffrey: 
hello

$ ansible-playbook deploy_client.yml -e 'client_ip=localhost vpn_user=gcmn server_ip=104.198.8.238 server_ssh_user=root'

PLAY [Configure the client] ****************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Add the droplet to an inventory group] ***********************************
changed: [localhost]

PLAY [Configure the client and install required software] **********************

TASK [Get the OS] **************************************************************
changed: [localhost]
...[truncated]
```

**Comment by gunph1ld** [comment]
Not a bug actually. See the commit above or lookup for the [Ansible Privilege Escalation](http://docs.ansible.com/ansible/become.html#become-privilege-escalation)

**Comment by rozza-m** [comment]
This should be documented in the main https://github.com/trailofbits/algo/blob/master/README.md or, preferably, the ./algo install script should be fixed to not need it or gracefully handle it.
