### ISSUE TITLE
OS X error "boto required for this module" during installation

### ISSUE THREAD

**Issue by dschuetz** [trailofbits/algo#53]
Though I'd installed boto as required, I still got errors on OS X El Capitan with the system not finding boto. Turns out there's a known issue with ansible: https://github.com/ansible/ansible/issues/15019

As suggested, added "ansible_python_interpreter=python" to the "localhost" line in inventory, and it worked fine.

Suggestion: consider adding that setting to the default inventory file, or adding to the README as a possible item needing attention.

**Comment by gunph1ld** [comment]
Good remark, thanks.
