### ISSUE TITLE
IKEv2 Fragmentation Windows 8.1

### ISSUE THREAD

**Issue by GeneralZero** [trailofbits/algo#534]
### Summary of the problem
I set up my server and am able to connect to it using my Android using strongSwan VPN Client. Both use the same network so not a problem with my router/AP. I am not able to connect to it using my Windows 8.1 Computer I get a 809 Error which I have viewed in wireshark and is IP Fragmentation.

### Expected behavior
Connection to VPN.

Fragmented IP packet size of 1514. Max IP packet size in network is around 1470.

Anyone have some way further troubleshoot or fix the problem.

**Comment by dguido** [comment]
This is covered in the FAQ, and we do not support Windows 8.1

**Comment by GeneralZero** [comment]
I dont see it in the [FAQ](https://github.com/trailofbits/algo/blob/master/docs/faq.md). Also the mention of Windows is only on the Deployment of Algo and not on the connection to a Algo VPN.

If this is still true it might be helpfull to update the [FAQ](https://github.com/trailofbits/algo/blob/master/docs/faq.md) or add information to the [Readme](https://github.com/trailofbits/algo/blob/master/README.md).

**Comment by dguido** [comment]
https://github.com/trailofbits/algo/blob/master/docs/troubleshooting.md#error-809-or-ike_auth-requests-that-never-make-it-to-the-server

https://github.com/trailofbits/algo/blob/master/CONTRIBUTING.md

**Comment by libreswan** [comment]
You need Windows 10 v1803 April 2018 update which adds IKEv2 fragmentation support. 

See https://msdn.microsoft.com/en-us/library/cc233476.aspx
