### ISSUE TITLE
Add support for DNS-over-HTTPS

### ISSUE THREAD

**Issue by spoxaka** [trailofbits/algo#535]
This is an enhancement request. I think it would be useful to have an option to tunnel DNS requests over HTTPS using Google service. There is a project here (https://github.com/fardog/secureoperator) which provides such proxy. It works quite well when configured manually and I think it would be nice to have it integrated into Algo for automated setup.

**Comment by Manouchehri** [comment]
@spoxaka I use DNS over HTTP/HTTPS for restricted networks, but I'm not sure I see the benefit over DNSCrypt on unrestricted networks?

**Comment by spoxaka** [comment]
@Manouchehri Well the idea is to keep using Google Public DNS which unfortunately does not support DNSCrypt yet. The HTTPS part here just ensures that DNS lookups will not be snooped into by the malicious actor potentially controlling network hardware on the remote side of the connection.

**Comment by Manouchehri** [comment]
@spoxaka Since Google uses anycast and peers directly with most/all cloud providers, there isn't much to sniff without comprising/attacking an internet exchange.

e.g. DigitalOcean to Google in Toronto doesn't cross any third party networks except the floor at TorIX.

```
dave@pulse:~$ mtr --aslook -c 50 8.8.8.8 -r --report-wide --show-ips
Start: Fri Sep  8 16:46:52 2017
HOST: pulse                                                        Loss%   Snt   Last   Avg  Best  Wrst StDev
  1. AS14061 138.197.144.253                                        0.0%    50    0.6   1.6   0.3  30.6   5.0
  2. AS???   138.197.249.88                                         0.0%    50    0.3   0.4   0.3   1.2   0.0
  3. AS???   google.ip4.torontointernetxchange.net (206.108.34.6)   0.0%    50    0.6   1.1   0.4  19.3   2.7
  4. AS15169 108.170.250.225                                        0.0%    50    0.6   0.7   0.5   1.1   0.0
  5. AS15169 108.170.227.37                                         0.0%    50    0.8   0.6   0.5   1.3   0.0
  6. AS15169 google-public-dns-a.google.com (8.8.8.8)               0.0%    50    0.5   0.7   0.5   2.8   0.4
```

**Comment by jackivanov** [comment]
Implemented
