### ISSUE TITLE
Consider setting TCP congestion algo to BBR.

### ISSUE THREAD

**Issue by jauderho** [trailofbits/algo#538]
To enable, put the following in /etc/sysctl.conf for Ubuntu 17.04 deployments

`net.core.default_qdisc=fq_codel`
`net.ipv4.tcp_congestion_control=bbr`

https://blog.apnic.net/2017/05/09/bbr-new-kid-tcp-block/

**Comment by Thermi** [comment]
What for? What is it supposed t o accelerate regarding the IPsec VPN? It doesn't use TCP.

**Comment by jauderho** [comment]
This would be from the VPN server out to the internet.

**Comment by Thermi** [comment]
It's still pretty much irrelevant for the VPN, because there's no proxy. Adding this sysctl setting would pretty much only ever pertain package updates and scp.

Am 16. Mai 2017 01:32:27 MESZ schrieb Jauder Ho <notifications@github.com>:
>This would be from the VPN server out to the internet.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/trailofbits/algo/issues/538#issuecomment-301633528

-- 
Sent from mobile
