### ISSUE TITLE
Multiple Private LAN Settings for Passthrough

### ISSUE THREAD

**Issue by arejay73** [trailofbits/algo#541]
### OS / Environment
Ubuntu 16.04

### Ansible version
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

### Summary of the problem
Is it possible to have multiple private LANs defined in the /etc/ipsec.conf?  Like the example, but one for each of my private LAN.  I connect to 3 private LANs on a regular basis and they all have different subnets. 10.0..., 192.168...

conn lan-passthrough_01
leftsubnet=192.168.1.1/24 # Replace with your LAN subnet
rightsubnet=192.168.1.1/24 # Replac with your LAND subnet
authby=never # No authentication necessary
type=pass # passthrough
auto=route # no need to ipsec up lan-passthrough

conn lan-passthrough_02
leftsubnet=10.0.0.1/24 # Replace with your LAN subnet
rightsubnet=10.0.0.1/24 # Replac with your LAND subnet
authby=never # No authentication necessary
type=pass # passthrough
auto=route # no need to ipsec up lan-passthrough

conn lan-passthrough_03
leftsubnet=192.168.7.1/24 # Replace with your LAN subnet
rightsubnet=192.168.7.1/24 # Replac with your LAND subnet
authby=never # No authentication necessary
type=pass # passthrough
auto=route # no need to ipsec up lan-passthrough

### Expected behavior
Would like the VPN to bypass the LAN for multiple LANs I connect to.

**Comment by dguido** [comment]
We're targeting simpler use cases. If you want to set something like this up, then you're on your own to do it.
