### ISSUE TITLE
Updating Users Changes The p12 and SSH keys password

### ISSUE THREAD

**Issue by williamthrilliam** [trailofbits/algo#545]
### Summary of the problem
Updating users changes the p12 and SSH keys password, and a new one isn't presented after the update. Is there a way to display the Congratulations! message?

### Steps to reproduce the behavior
Update the users list in your config.cfg
Open a terminal, cd to the algo directory, and activate the virtual environment with source env/bin/activate
Run the command: ./algo update-users

### The way of deployment (cloud or local)
Amazon AWS

### Expected behavior
The P12 and SSH keys password doesn't change.

### Actual behavior
The password primarily displayed after install no longer decrypts certificates.

**Comment by niektemme** [comment]
I do not know if this is still relevant. But I experienced the same problem. For me the solution was to explicitly set the p12_password variable when running the users.yml playbook. As far as I can see this is not documented. The documentation mentions setting the ca_password variable. Setting the p12_password variable works, so to see, the same way. Se example code below.


```
ansible-playbook users.yml -e "provider=local
                                server=<change>
                                endpoint=<change>
                                ssh_user=<change>
                                ansible_ssh_private_key_file=<change>
                                server_name=<change>
                                store_pki=true
                                p12_password=<change>
                                ca_password=<change>
                                "
```

**Comment by Fuckmylimpdick** [comment]
Y
