### ISSUE TITLE
Suggestion: Separate config with user list

### ISSUE THREAD

**Issue by tony199555** [trailofbits/algo#546]
The current plan is working great, but it fails short when users want to create different instances with different users within a single algo controller.

### For example:
Friend A asks me to create a vpn specifically for him, then I create one with a set of user list. But friend B also wants to create a vpn exclusively for him, too, which I have to delete the old one and add the new ones into the list. Say if friend A wants to delete a user but the list is already changed, that means I have to change it back again. 

### Problem:
This is annoying for the maintainer like me who is trying to help 10ish friends who need a vpn to browse. To create a separate controller for each friend is not only unrealistic but also waste of money. (For DigitalOcean, the cheapest is ((1+n)5)x, 1 being the controller and n being how many vpn they need or want, that comes out 20 dollars with 2 people with only 1 vpn for each, vs 15 for 2 people, just do it 5 times you have 100 vs 55.)

### Possible better solutions:
Ask for user list config when creating the vpn.

P.S. I know this is not safe but is there a way I could just save DigitalOcean API token in the config file?

**Comment by dguido** [comment]
You can store the DigitalOcean API key in an environment variable and the script will pick it up.

I assume you're already using the [Ansible deployment](https://github.com/trailofbits/algo/blob/master/docs/deploy-from-ansible.md) method?

In general, we recommend *not maintaining* the servers you setup. Just recreate them from scratch if people need changes.

**Comment by tony199555** [comment]
I know it is better to deploy another one. But due to the droplet will not be destroyed, I just reuse it. Despite that, I still have to change user list every time I deploy a new one (if it is different).

I use both method, and basically does not make much of difference.

**Comment by dguido** [comment]
We're not going to fix this issue in this version of Algo
