### ISSUE TITLE
support split tunneling

### ISSUE THREAD

**Issue by eleith** [trailofbits/algo#551]
strongswan is a great client to pair with algo. 

one feature strongswan supports is split tunneling. in reading into strongswan's support for it, it seems like this needs to be supported on the server itself to respond back appropriately to let the vpn client to know when to use the local network instead.

https://wiki.strongswan.org/projects/strongswan/wiki/ForwardingAndSplitTunneling

is this of interest to this project?

**Comment by Thermi** [comment]
" it seems like this needs to be supported on the server itself to respond back appropriately to let the vpn client to know when to use the local network instead."
No. The client can narrow the traffic selector without any other configuration on the server. Usually, that is what the client does (it just proposes a narrower traffic selector).

Split-tunneling on proprietary installations is usually done either via proprietary IKE extensions that send the possible profiles to the client or by using different IDs for either configuration (if PSK authentication is used). The latter obviously does not work for certificates and the first isn't implemented in strongSwan or any client.

You can not do split tunneling right now without the client using pubkey authentication, except if you use different CAs or any other means that the server can distinguish the clients that want either profile.

**Comment by eleith** [comment]
awesome.thanks for the details / correction

**Comment by jjssoftware** [comment]
It's not entirely clear to me how the VPN is being connected to from strongswan to algo here but I can say that in my setup, split tunneling is 100% working fine with strongswan and algo. 

I have strongswan installed on a local linux client connecting to the remote algo VPN over IKEV2 certificate auth.  Here's a snip of the connections within my ipsec.conf (passthrough-1 takes care of avoiding use of the VPN for local LAN traffic):

```
conn ikev2-<MY_ALGO_VPN_IP>
    fragmentation=yes
    rekey=no
    dpdaction=clear
    keyexchange=ikev2
    compress=no
    dpddelay=35s

    ike=aes128gcm16-prfsha512-ecp256,aes128-sha2_512-prfsha512-ecp256,aes128-sha2_384-prfsha384-ecp256!
    esp=aes128gcm16-ecp256,aes128-sha2_512-prfsha512-ecp256!

    right=<MY_ALGO_VPN_IP>
    rightid=<MY_ALGO_VPN_IP>
    rightsubnet=0.0.0.0/0
    rightauth=pubkey

    leftsourceip=%config
    leftauth=pubkey
    leftcert=joe.crt
    leftfirewall=yes
    left=%defaultroute

    auto=start

conn passthrough-1
    left=127.0.0.1
    right=127.0.0.1
    leftsubnet=192.168.0.1/24
    rightsubnet=192.168.0.1/24
    authby=never
    type=pass
    auto=route
```

**Comment by Thermi** [comment]
> , split tunneling is 100% working fine with strongswan and algo.

>     rightsubnet=0.0.0.0/0

That's not split-tunneling.

**Comment by eleith** [comment]
are there other ways to get local addresses routed not through algo, without turning off our VPN clients?

**Comment by Thermi** [comment]
You can push local-lan attributes via configuration payloads to the client and the client is supposed to install passthrough policies for those networks, but there's no way to get the local network from the client, so that can be sent back to it, AFAIK. The passthrough installation for its local networks must be done by the client.
