### ISSUE TITLE
MTU / MSS help

### ISSUE THREAD

**Issue by jjssoftware** [trailofbits/algo#552]
### OS / Environment
Remote Algo VPN host:  Amazon EC2 t2 micro / Ubuntu 16.04 xenial
VPN Client: Linux Mint 18.1 Serena (Ubuntu 16.04 xenial)

### Summary of the problem
This is one of these issues: https://github.com/trailofbits/algo/blob/master/docs/troubleshooting.md#various-websites-appear-to-be-offline-through-the-vpn

https://packages.microsoft.com/ fails to resolve / respond. 

This issue is MTU / MSS related and I've managed to get this working by adjusting the MTU. Then having proved that works I rolled back the MTU change and adjusted the MSS via iptables and proved that also worked.

Incidentally I have raised an issue with strongswan here https://wiki.strongswan.org/issues/2325 and someone has responded with what looks like an opinion that modifying MSS is preferable to modifying MTU. This level of thinking is beyond me to be completely honest because it's in the realm of network engineering / wireshark pcap / packet analysis troubleshooting. 

So this is basically why I'm raising this issue here because most advice suggests that adjusting MTU is the way to go for issues like this, however adjusting MSS clearly also works. Is there any further advice here? Thanks! 

### Steps to reproduce the behavior

1. Deploy algo to Amazon EC2 in eu-west-1
2. Connect a Linux Mint local client machine to the remote algo VPN via strongswan on the client side
3. Attempt to navigate to https://packages.microsoft.com/repos/vscode/ in a browser and watch it hang and eventually fail
4. Disconnect from the VPN and verify it works
5. Adjust MTU or MSS, reconnect to the remote algo VPN and verify it works

### The way of deployment (cloud or local)
cloud

### Expected behavior
tcp/ip traffic flows

### Actual behavior
tcp/ip stops

**Comment by kiratp** [comment]
sudo iptables -t mangle -A FORWARD -s {{ vpn_network }} -p tcp -m tcp --tcp-flags SYN,RST SYN -j TCPMSS --set-mss {{ max_mss }}

where the default vpn_network = 10.19.48.0/24
and 1280 <= max_mss <=1460

1280 is will be your most compatible setting and I suggest just using that. 

If you want peak performance then you need to run ping tests with fragmentation - https://networkcanuck.com/2013/06/10/troubleshooting-mtu-size-over-ipsec-vpn/

There used to be a setting (max_mss) in the config file when creating the server but it might have been removed.

**Comment by jjssoftware** [comment]
Thanks for that comment @kiratp but this doesn't tell me anything I didn't already know. 

I know how to adjust both MSS and MTU and as previously mentioned I've raised this issue here because most advice suggests that adjusting MTU is the way to go for issues like this, however adjusting MSS clearly also works.

I've settled on MSS adjustment for the moment but the open question that remains are: 

1. why is adjusting MSS a better solution than adjusting MTU?
2. if adjusting MSS is a better solution, why does most available advice suggest adjusting MTU?

**Comment by Thermi** [comment]
As I wrote in the issue tracker on strongSwan, the best solution is to set the MTU for the routes that charon inserts into table 220. The key for that is charon.plugins.kernel-netlink.mtu. You can do the same for the MSS with charon.plugins.kernel-netlink.mss. An application does not necessarily care about the path MTU or MSS (especially the latter), so you can enforce the MSS by setting it with iptables.

The one thing I said was bad was to set the MTU on the *interface*.

**Comment by jjssoftware** [comment]
Perhaps I'm asking the wrong questions because no-one is answering what I'm trying to get answered. There is advice coming and I really do appreciate the efforts but no-one is giving explanation or concrete justification for the advice being being offered. I could guess the answers or try and piece together an answer from other advice elsewhere but I'd rather not :)

I'll try some slightly different questions:

1. Specifically why is it bad to set the MTU on the interface rather than on the StrongSwan inserted route? 
2. How does adjusting MSS affect the MTU (if at all)?

**Comment by Thermi** [comment]
1. Because the MTU on the interface pertains all packets, not just the ones over the VPN. Only the MTU for the traffic over the VPN needs to be lowered, not the traffic for other traffic.
2. It doesn't. The MTU affects the MSS. The MTU is the maximum transmission unit of the link layer. The MSS is the maximum data length in a single TCP packet. The set MSS has to adjust for the different headers between the link-level frame and all the headers and trailers in front and after the TCP data field.

**Comment by jjssoftware** [comment]
thanks to everyone who helped
