### ISSUE TITLE
strongswan logs

### ISSUE THREAD

**Issue by bit-herder** [trailofbits/algo#553]
### OS / Environment
ubuntu on aws

### Ansible version
ansible 2.3.0.0

### Summary of the problem
strongswan doesn't generate logfiles 

### Steps to reproduce the behavior
install algo on ubuntu in aws

### The way of deployment (cloud or local)
cloud

### Expected behavior
strongswan will log to a file

```
        filelog {
          /var/log/charon.log {
              time_format = %b %e %T
              ike_name = yes
              append = no
              default = 1
              flush_line = yes
          }
```

### Actual behavior

the file is not created, i can't find any charon logs. 
Is this by design?

**Comment by gunph1ld** [comment]
>ansible 2.3.0.0

We don't support ansible 2.3 yet.

>strongswan will log to a file 

No. It's for *BSDs only. journald is collecting logs

> i can't find any charon logs.

Use `journalctl` to get the logs you need.
