### ISSUE TITLE
constraint check failed:

### ISSUE THREAD

**Issue by Longshot** [trailofbits/algo#556]
### OS / Environment

Ubuntu 16.04 lcontainer on Ubuntu 16.04 host

### Ansible version

Where can I find that

### Summary of the problem

I've succesfully installed Algo but after connecting with my Galaxy S7 I get the following error in the client:

constraint check failed: identity 'my.domain.com' required
selected peer config 'android' inacceptable: constraint checking failed

A google search tells me:
The failure occurred because Android can read only the first Subject Alternative Name extension 
but I have no clue what to do with information.

### Steps to reproduce the behavior

Install Algo
Install strongSwan VPN client
Install p12 cert
Try to connect

### The way of deployment (cloud or local)

local

### Expected behavior

Connect to VPN

### Actual behavior

Unable to connect to VPN

### Full log

I would if I'd know where the log file was located

**Comment by gunph1ld** [comment]
Android version? StrongSwan app version?

**Comment by Thermi** [comment]
Certificate validation is done in the app without external libraries. Please provide your server certificate, server logs and configuration. I suspect PEBKAC. I don't know where Algo configures the logs to be written to.

**Comment by dguido** [comment]
I'm going to take a wild guess that you tried to assign your server a domain name and use that to connect? Because that won't work.

Also, please follow the issue template and provide the information it asks for. We can't troubleshoot anything without it.

**Comment by Longshot** [comment]
> Android version? StrongSwan app version?

7.0 , 1.8.2

> Please provide your server certificate

I'm not a VPN expert but that doesn't sound like a good idea?

> I'm going to take a wild guess that you tried to assign your server a domain name and use that to connect? Because that won't work.

So I can't connect to my.domain.com but it has to be an IP address?
During the Algo setup I did enter the IP address but in the Android app I've entered my domain name.

> Also, please follow the issue template and provide the information it asks for. We can't troubleshoot anything without it.

I understand, but it's not easy to provide the requested information. 
I will try to find the logfile ater I'm back from work tonight.

**Comment by dguido** [comment]
You have to use the IP address of the server.

**Comment by Thermi** [comment]
The error occurs because the certificate does not authenticate Algo as that domain name.
