### ISSUE TITLE
Admin user name is "root" not "ubuntu"

### ISSUE THREAD

**Issue by bhawkins** [trailofbits/algo#557]
### OS / Environment
Windows 10 / bash

### Ansible version
2.2.0.0

### Version of components from `requirements.txt`
msrestazure==0.4.7
ansible==2.2.0.0
dopy==0.3.5
boto==2.46.1
boto3==1.4.4
azure==2.0.0rc5
msrest==0.4.1
apache-libcloud==2.0.0
six==1.10.0
pyopenssl==17.0.0
setuptools==35.0.2
jinja2==2.8

### Summary of the problem
User name to administer server via SSH is "root" not "ubuntu" as in README and FAQ.

### Steps to reproduce the behavior

Installed Algo VPN to DO by following README using repo at commit 6f1709.

### The way of deployment (cloud or local)

Digital Ocean

### Expected behavior

`ssh ubuntu@ip -i ~/.ssh/algo.pem`

### Actual behavior

`ssh root@ip -i ~/.ssh/algo.pem`

**Comment by dguido** [comment]
You can submit a PR to change it. The default on Amazon is "ubuntu" and that's what I defaulted to, but it makes better sense defaulting to DigitalOcean maybe.

**Comment by bhawkins** [comment]
Change the README/FAQ or change the ansible user name setup? I don't know ansible well enough to do the latter.

Poking around, I'm guessing the `ansible_ssh_user` key in the `roles/cloud-*/tasks/main.yml` files is the user name for each could provider. If so, it looks like it's just `root` on DO and `ubuntu` on all the others. I could update the docs to reflect that.

**Comment by dguido** [comment]
The readme.
