### ISSUE TITLE
No IPv6 configuration on Linux Desktop client through NetworkManager

### ISSUE THREAD

**Issue by miltador** [trailofbits/algo#559]
### OS / Environment

Ubuntu 16.04 / Digital Ocean
Client running Arch Linux

### Summary of the problem
Linux Desktop client doesn't get IPv6 configuration from Algo server using NetworkManager.

### Steps to reproduce the behavior
1. Add a IPsec/IKEv2 (strongswan) connection and set it up.
2. Make sure on IPv6 tab IPv6 is enabled.
3. Connect to VPN.
4. Check for IPv6 on http://test-ipv6.com/
5. Check logs. You will see something like:
```
<info>  [1495349772.2802] vpn-connection[0x22942b0,af2ceb20-9c52-4f17-bc1a-65c7edbdb6fb,"VPN 1",0]: Data: No IPv6 configuration
```

### The way of deployment (cloud or local)
Cloud

### Expected behavior
Getting IPv6 configuration and assigning IPv6 address to Linux Desktop client.

### Actual behavior
No IPv6 configuration is set and no IPv6 address is assigned to Linux Desktop client.

### Additional information
`strongswan` version: 5.5.2
`networkmanager` version: 1.8.0
`networkmanager-strongswan` version:  1.4.1

**Comment by miltador** [comment]
On my Android phone I successfully get IPv6 and all tests pass on http://test-ipv6.com/

**Comment by Ramblurr** [comment]
Unrelated question, but how did you get configure the vpn via NetworkManager?

**Comment by miltador** [comment]
By installing a plugin for `networkmanager` called `networkmanager-strongswan`.

**Comment by Ramblurr** [comment]
Ah :) you are using archlinux which has the latest networkmanager-strongswan-gnome with the cipher configuration.

**Comment by imgx64** [comment]
It seems that `networkmanager-strongswan`/`charon-nm` simply doesn't support IPv6 currently. I looked at the code and it only sets up IPv4. There is no mention of IPv6 whatsoever: [strongswan/src/charon-nm/nm/nm_service.c](https://github.com/strongswan/strongswan/blob/master/src/charon-nm/nm/nm_service.c)

**Comment by imgx64** [comment]
Found an open issue: [Network manager plugin has no support for ipv6](https://wiki.strongswan.org/issues/1143)

**Comment by dguido** [comment]
You're welcome to try wireguard on Linux with the latest Algo installer. There is no way that we can fix this with strongswan.
