### ISSUE TITLE
Android split tunnel - local network

### ISSUE THREAD

**Issue by abitgit** [trailofbits/algo#562]
### OS / Environment

Android 7.1.2

### Summary of the problem
Unable to get split tunnel to work. 

### Steps to reproduce the behavior
Try connecting to router via web browser. Ping router or other devices on LAN.

### The way of deployment (cloud or local)
Digital Ocean

### Expected behavior
Should be able to connect to devices on LAN from Android. It works on iOS and macOS.

### Actual behavior
Can't access router via web-browser. Unable to ping router or other devices on LAN. All packets fail to trasmit.

**Comment by dguido** [comment]
Please follow the issue template

**Comment by eleith** [comment]
@abitgit strongswan android app (1.9, just updated recently) supports client side split tunneling now. just exclude your local subnet on your vpn connection profile and you should be able to ping your devices on your LAN while the VPN connection to algo is active.
