### ISSUE TITLE
Can't access other devices on LAN when using strongSwan Android app

### ISSUE THREAD

**Issue by abitgit** [trailofbits/algo#563]
### OS / Environment

macOS Sierra (10.11.5)

### Ansible version

2.2.0.0

### Version of components from `requirements.txt`

ansible (2.2.0.0)
apache-libcloud (2.0.0)
azure (2.0.0rc5)
boto (2.46.1)
boto3 (1.4.4)
dopy (0.3.5)
Jinja2 (2.8)
msrest (0.4.1)
msrestazure (0.4.7)
pyOpenSSL (17.0.0)
setuptools (35.0.2)
six (1.10.0)

### Summary of the problem
I'm unable to connect to local devices when using the strongSwan app on Android. I can't access my router via the web interface. Also, unable to ping the router or other devices on LAN.

### Steps to reproduce the behavior
Try connecting to a device on LAN (eg. access router via web-url)
IP address of router is 10.1.0.1
Ping 10.1.0.1 from Android phone while connected to Algo VPN server.

### The way of deployment (cloud or local)
Cloud (Digital Ocean)

### Expected behavior
Should still be able to access local devices. It works fine from macOS and iOS.

### Actual behavior
I'm unable to access my router when connected to the Algo VPN from my Android phone. I can't ping the router or other devices. No packets are trasmitted to devices on LAN.

### Full log

No log available.

**Comment by dguido** [comment]
Sorry, this is expected behavior.

**Comment by abitgit** [comment]
Is it an issue with the strongSwan Android app? Why does it work when using macOS as the client?
