### ISSUE TITLE
always on config

### ISSUE THREAD

**Issue by jDevSD** [trailofbits/algo#566]
### OS / Environment

MacOS Siera 10.12.6 Beta (16G8c)

### Ansible version

ansible 2.3.0.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Dec 18 2016, 07:03:39) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]

### Version of components from `requirements.txt`

kraken:~/ $pip show msrestazure setuptools ansible dopy boto boto3 azure msrest apache-libcloud six pypopenssl jinja2
Name: setuptools
Version: 35.0.2
Summary: Easily download, build, install, upgrade, and uninstall Python packages
Home-page: https://github.com/pypa/setuptools
Author: Python Packaging Authority
Author-email: distutils-sig@python.org
License: UNKNOWN
Location: /usr/local/lib/python2.7/site-packages
Requires: six, packaging, appdirs
---
Name: ansible
Version: 2.3.0.0
Summary: Radically simple IT automation
Home-page: https://ansible.com/
Author: Ansible, Inc.
Author-email: info@ansible.com
License: GPLv3
Location: /usr/local/lib/python2.7/site-packages
Requires: pycrypto, paramiko, setuptools, jinja2, PyYAML
---
Name: six
Version: 1.10.0
Summary: Python 2 and 3 compatibility utilities
Home-page: http://pypi.python.org/pypi/six/
Author: Benjamin Peterson
Author-email: benjamin@python.org
License: MIT
Location: /usr/local/lib/python2.7/site-packages
Requires:
---
Name: Jinja2
Version: 2.9.6
Summary: A small but fast and easy to use stand-alone template engine written in pure python.
Home-page: http://jinja.pocoo.org/
Author: Armin Ronacher
Author-email: armin.ronacher@active-4.com
License: BSD
Location: /usr/local/lib/python2.7/site-packages
Requires: MarkupSafe

### Summary of the problem
I have algo running on AWS and trying to get "Always On" to work but have been unsuccessful.  

### The way of deployment (cloud or local)
cloud aws

### Expected behavior
vpn should connect and stay connected. 

### Actual behavior
vpn will not connect at all but will keep trying

**Comment by dguido** [comment]
We don't support beta operating systems
