### ISSUE TITLE
build fails on OS X 10.12.6 Beta

### ISSUE THREAD

**Issue by cockytrumpet** [trailofbits/algo#568]
### OS / Environment
MacOS 10.12.6 Beta
GCC output (crashes):
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

### Ansible version
2.3.0.0

### Summary of the problem
Doesn't compile.

### Steps to reproduce the behavior
run this after following the steps at (https://github.com/trailofbits/algo) :
python -m virtualenv env && source env/bin/activate && python -m pip install -U pip && python -m pip install -r requirements.txt

### The way of deployment (cloud or local)
not relevant

### Expected behavior
installation

### Actual behavior
crash

### Full log
below

**Comment by cockytrumpet** [comment]
Installing collected packages: oauthlib, certifi, chardet, urllib3, idna, requests, requests-oauthlib, enum34, keyring, isodate, msrest, PyJWT, pycparser, cffi, asn1crypto, ipaddress, cryptography, python-dateutil, adal, msrestazure, pycrypto, pyasn1, paramiko, MarkupSafe, jinja2, PyYAML, ansible, dopy, boto, jmespath, docutils, botocore, futures, s3transfer, boto3, azure-nspkg, azure-common, azure-batch, azure-graphrbac, azure-mgmt-nspkg, azure-mgmt-keyvault, azure-mgmt-authorization, azure-mgmt-notificationhubs, azure-mgmt-powerbiembedded, azure-mgmt-commerce, azure-mgmt-cognitiveservices, azure-mgmt-compute, azure-mgmt-storage, azure-mgmt-batch, azure-mgmt-scheduler, azure-mgmt-logic, azure-mgmt-cdn, azure-mgmt-redis, azure-mgmt-web, azure-mgmt-network, azure-mgmt-resource, azure-mgmt, azure-servicebus, azure-servicemanagement-legacy, azure-storage, azure, apache-libcloud, pyopenssl
  Running setup.py install for pycrypto ... error
    Complete output from command /Users/adam/algo-master/env/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/83/m_m89mw53tl1v606h9fb49_c0000gq/T/pip-build-3P2Rwj/pycrypto/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/83/m_m89mw53tl1v606h9fb49_c0000gq/T/pip-Bi1apv-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/adam/algo-master/env/bin/../include/site/python2.7/pycrypto:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.12-x86_64-2.7
    creating build/lib.macosx-10.12-x86_64-2.7/Crypto
    copying lib/Crypto/__init__.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto
    copying lib/Crypto/pct_warnings.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto
    creating build/lib.macosx-10.12-x86_64-2.7/Crypto/Hash
    copying lib/Crypto/Hash/__init__.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/Hash
    copying lib/Crypto/Hash/hashalgo.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/Hash
    copying lib/Crypto/Hash/HMAC.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/Hash
    copying lib/Crypto/Hash/MD2.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/Hash
    copying lib/Crypto/Hash/MD4.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/Hash
    copying lib/Crypto/Hash/MD5.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/Hash
    copying lib/Crypto/Hash/RIPEMD.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/Hash
    copying lib/Crypto/Hash/SHA.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/Hash
    copying lib/Crypto/Hash/SHA224.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/Hash
    copying lib/Crypto/Hash/SHA256.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/Hash
    copying lib/Crypto/Hash/SHA384.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/Hash
    copying lib/Crypto/Hash/SHA512.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/Hash
    creating build/lib.macosx-10.12-x86_64-2.7/Crypto/Cipher
    copying lib/Crypto/Cipher/__init__.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/Cipher
    copying lib/Crypto/Cipher/AES.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/Cipher
    copying lib/Crypto/Cipher/ARC2.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/Cipher
    copying lib/Crypto/Cipher/ARC4.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/Cipher
    copying lib/Crypto/Cipher/blockalgo.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/Cipher
    copying lib/Crypto/Cipher/Blowfish.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/Cipher
    copying lib/Crypto/Cipher/CAST.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/Cipher
    copying lib/Crypto/Cipher/DES.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/Cipher
    copying lib/Crypto/Cipher/DES3.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/Cipher
    copying lib/Crypto/Cipher/PKCS1_OAEP.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/Cipher
    copying lib/Crypto/Cipher/PKCS1_v1_5.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/Cipher
    copying lib/Crypto/Cipher/XOR.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/Cipher
    creating build/lib.macosx-10.12-x86_64-2.7/Crypto/Util
    copying lib/Crypto/Util/__init__.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/Util
    copying lib/Crypto/Util/_number_new.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/Util
    copying lib/Crypto/Util/asn1.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/Util
    copying lib/Crypto/Util/Counter.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/Util
    copying lib/Crypto/Util/number.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/Util
    copying lib/Crypto/Util/py21compat.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/Util
    copying lib/Crypto/Util/py3compat.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/Util
    copying lib/Crypto/Util/randpool.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/Util
    copying lib/Crypto/Util/RFC1751.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/Util
    copying lib/Crypto/Util/winrandom.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/Util
    creating build/lib.macosx-10.12-x86_64-2.7/Crypto/Random
    copying lib/Crypto/Random/__init__.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/Random
    copying lib/Crypto/Random/_UserFriendlyRNG.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/Random
    copying lib/Crypto/Random/random.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/Random
    creating build/lib.macosx-10.12-x86_64-2.7/Crypto/Random/Fortuna
    copying lib/Crypto/Random/Fortuna/__init__.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/Random/Fortuna
    copying lib/Crypto/Random/Fortuna/FortunaAccumulator.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/Random/Fortuna
    copying lib/Crypto/Random/Fortuna/FortunaGenerator.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/Random/Fortuna
    copying lib/Crypto/Random/Fortuna/SHAd256.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/Random/Fortuna
    creating build/lib.macosx-10.12-x86_64-2.7/Crypto/Random/OSRNG
    copying lib/Crypto/Random/OSRNG/__init__.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/Random/OSRNG
    copying lib/Crypto/Random/OSRNG/fallback.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/Random/OSRNG
    copying lib/Crypto/Random/OSRNG/nt.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/Random/OSRNG
    copying lib/Crypto/Random/OSRNG/posix.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/Random/OSRNG
    copying lib/Crypto/Random/OSRNG/rng_base.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/Random/OSRNG
    creating build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest
    copying lib/Crypto/SelfTest/__init__.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest
    copying lib/Crypto/SelfTest/st_common.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest
    creating build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/Cipher
    copying lib/Crypto/SelfTest/Cipher/__init__.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/Cipher
    copying lib/Crypto/SelfTest/Cipher/common.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/Cipher
    copying lib/Crypto/SelfTest/Cipher/test_AES.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/Cipher
    copying lib/Crypto/SelfTest/Cipher/test_ARC2.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/Cipher
    copying lib/Crypto/SelfTest/Cipher/test_ARC4.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/Cipher
    copying lib/Crypto/SelfTest/Cipher/test_Blowfish.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/Cipher
    copying lib/Crypto/SelfTest/Cipher/test_CAST.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/Cipher
    copying lib/Crypto/SelfTest/Cipher/test_DES.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/Cipher
    copying lib/Crypto/SelfTest/Cipher/test_DES3.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/Cipher
    copying lib/Crypto/SelfTest/Cipher/test_pkcs1_15.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/Cipher
    copying lib/Crypto/SelfTest/Cipher/test_pkcs1_oaep.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/Cipher
    copying lib/Crypto/SelfTest/Cipher/test_XOR.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/Cipher
    creating build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/Hash
    copying lib/Crypto/SelfTest/Hash/__init__.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/Hash
    copying lib/Crypto/SelfTest/Hash/common.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/Hash
    copying lib/Crypto/SelfTest/Hash/test_HMAC.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/Hash
    copying lib/Crypto/SelfTest/Hash/test_MD2.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/Hash
    copying lib/Crypto/SelfTest/Hash/test_MD4.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/Hash
    copying lib/Crypto/SelfTest/Hash/test_MD5.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/Hash
    copying lib/Crypto/SelfTest/Hash/test_RIPEMD.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/Hash
    copying lib/Crypto/SelfTest/Hash/test_SHA.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/Hash
    copying lib/Crypto/SelfTest/Hash/test_SHA224.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/Hash
    copying lib/Crypto/SelfTest/Hash/test_SHA256.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/Hash
    copying lib/Crypto/SelfTest/Hash/test_SHA384.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/Hash
    copying lib/Crypto/SelfTest/Hash/test_SHA512.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/Hash
    creating build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/Protocol
    copying lib/Crypto/SelfTest/Protocol/__init__.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/Protocol
    copying lib/Crypto/SelfTest/Protocol/test_AllOrNothing.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/Protocol
    copying lib/Crypto/SelfTest/Protocol/test_chaffing.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/Protocol
    copying lib/Crypto/SelfTest/Protocol/test_KDF.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/Protocol
    copying lib/Crypto/SelfTest/Protocol/test_rfc1751.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/Protocol
    creating build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/PublicKey
    copying lib/Crypto/SelfTest/PublicKey/__init__.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/PublicKey
    copying lib/Crypto/SelfTest/PublicKey/test_DSA.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/PublicKey
    copying lib/Crypto/SelfTest/PublicKey/test_ElGamal.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/PublicKey
    copying lib/Crypto/SelfTest/PublicKey/test_importKey.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/PublicKey
    copying lib/Crypto/SelfTest/PublicKey/test_RSA.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/PublicKey
    creating build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/Random
    copying lib/Crypto/SelfTest/Random/__init__.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/Random
    copying lib/Crypto/SelfTest/Random/test__UserFriendlyRNG.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/Random
    copying lib/Crypto/SelfTest/Random/test_random.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/Random
    copying lib/Crypto/SelfTest/Random/test_rpoolcompat.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/Random
    creating build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/Random/Fortuna
    copying lib/Crypto/SelfTest/Random/Fortuna/__init__.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/Random/Fortuna
    copying lib/Crypto/SelfTest/Random/Fortuna/test_FortunaAccumulator.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/Random/Fortuna
    copying lib/Crypto/SelfTest/Random/Fortuna/test_FortunaGenerator.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/Random/Fortuna
    copying lib/Crypto/SelfTest/Random/Fortuna/test_SHAd256.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/Random/Fortuna
    creating build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/Random/OSRNG
    copying lib/Crypto/SelfTest/Random/OSRNG/__init__.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/Random/OSRNG
    copying lib/Crypto/SelfTest/Random/OSRNG/test_fallback.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/Random/OSRNG
    copying lib/Crypto/SelfTest/Random/OSRNG/test_generic.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/Random/OSRNG
    copying lib/Crypto/SelfTest/Random/OSRNG/test_nt.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/Random/OSRNG
    copying lib/Crypto/SelfTest/Random/OSRNG/test_posix.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/Random/OSRNG
    copying lib/Crypto/SelfTest/Random/OSRNG/test_winrandom.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/Random/OSRNG
    creating build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/Util
    copying lib/Crypto/SelfTest/Util/__init__.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/Util
    copying lib/Crypto/SelfTest/Util/test_asn1.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/Util
    copying lib/Crypto/SelfTest/Util/test_Counter.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/Util
    copying lib/Crypto/SelfTest/Util/test_number.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/Util
    copying lib/Crypto/SelfTest/Util/test_winrandom.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/Util
    creating build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/Signature
    copying lib/Crypto/SelfTest/Signature/__init__.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/Signature
    copying lib/Crypto/SelfTest/Signature/test_pkcs1_15.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/Signature
    copying lib/Crypto/SelfTest/Signature/test_pkcs1_pss.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/SelfTest/Signature
    creating build/lib.macosx-10.12-x86_64-2.7/Crypto/Protocol
    copying lib/Crypto/Protocol/__init__.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/Protocol
    copying lib/Crypto/Protocol/AllOrNothing.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/Protocol
    copying lib/Crypto/Protocol/Chaffing.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/Protocol
    copying lib/Crypto/Protocol/KDF.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/Protocol
    creating build/lib.macosx-10.12-x86_64-2.7/Crypto/PublicKey
    copying lib/Crypto/PublicKey/__init__.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/PublicKey
    copying lib/Crypto/PublicKey/_DSA.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/PublicKey
    copying lib/Crypto/PublicKey/_RSA.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/PublicKey
    copying lib/Crypto/PublicKey/_slowmath.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/PublicKey
    copying lib/Crypto/PublicKey/DSA.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/PublicKey
    copying lib/Crypto/PublicKey/ElGamal.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/PublicKey
    copying lib/Crypto/PublicKey/pubkey.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/PublicKey
    copying lib/Crypto/PublicKey/RSA.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/PublicKey
    creating build/lib.macosx-10.12-x86_64-2.7/Crypto/Signature
    copying lib/Crypto/Signature/__init__.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/Signature
    copying lib/Crypto/Signature/PKCS1_PSS.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/Signature
    copying lib/Crypto/Signature/PKCS1_v1_5.py -> build/lib.macosx-10.12-x86_64-2.7/Crypto/Signature
    running build_ext
    running build_configure
    checking for gcc... /usr/local/bin/gcc-4.7
    checking whether the C compiler works... no
    configure: error: in `/private/var/folders/83/m_m89mw53tl1v606h9fb49_c0000gq/T/pip-build-3P2Rwj/pycrypto':
    configure: error: C compiler cannot create executables
    See `config.log' for more details
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/83/m_m89mw53tl1v606h9fb49_c0000gq/T/pip-build-3P2Rwj/pycrypto/setup.py", line 456, in <module>
        core.setup(**kw)
      File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/Users/adam/algo-master/env/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install.py", line 563, in run
        self.run_command('build')
      File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/build.py", line 127, in run
        self.run_command(cmd_name)
      File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/private/var/folders/83/m_m89mw53tl1v606h9fb49_c0000gq/T/pip-build-3P2Rwj/pycrypto/setup.py", line 251, in run
        self.run_command(cmd_name)
      File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/private/var/folders/83/m_m89mw53tl1v606h9fb49_c0000gq/T/pip-build-3P2Rwj/pycrypto/setup.py", line 278, in run
        raise RuntimeError("autoconf error")
    RuntimeError: autoconf error

    ----------------------------------------
Command "/Users/adam/algo-master/env/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/83/m_m89mw53tl1v606h9fb49_c0000gq/T/pip-build-3P2Rwj/pycrypto/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/83/m_m89mw53tl1v606h9fb49_c0000gq/T/pip-Bi1apv-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/adam/algo-master/env/bin/../include/site/python2.7/pycrypto" failed with error code 1 in /private/var/folders/83/m_m89mw53tl1v606h9fb49_c0000gq/T/pip-build-3P2Rwj/pycrypto/

**Comment by gunph1ld** [comment]
We don't support betas

**Comment by cockytrumpet** [comment]
Your project is broken in a future (beta) version of an OS you "support" and your concern isn't how to get ahead of it or even what has changed... When to abandon a project 101
