### ISSUE TITLE
Document configuration and setup steps

### ISSUE THREAD

**Issue by edermi** [trailofbits/algo#57]
I'd like to use algo on an already running and configured virtual machine (which runs Debian). It is quite time consuming - especially for people not used to Ansible - to find out what algo is actually setting up. Providing the configuration files and commands that are used during and after the setup enables more people to adapt the configuration to their needs/setups and is more transparent to users.

**Comment by defunctio** [comment]
Algo was designed with Ansible at the core to eliminate the need for manual process and configuration. Part of automated infrastructure and deployment is using the tools created with this task in mind such as Ansible, Chef and Puppet. 

Configuration files are generally stored as templates and inject a few variables into them, they can easily be modified to adapt to your environment if changes are needed. Tasks are abstracted into roles to be more manageable, readable and reusable. 

I don't think that providing documentation for an equivalent process is really the solution to this however; I still think many of the roles in Algo could be abstracted even further and that those roles could include additional documentation either inline or as a reference guide. I don't know of any doc generators for yaml though.

**Comment by dguido** [comment]
I agree with defunctio, this is a little outside the scope of what we're trying to do right now. All the configuration files are helpfully organized in the "templates" folder of each role if you want to use them.

Algo can be run on an existing server via the local deployment option in the run script. It's built for Ubuntu 16.04, but Debian is close enough that it might just work out of the box. Try it and let us know.

**Comment by defunctio** [comment]
Closing this issue for now, thanks for the feedback.
