### ISSUE TITLE
File sharing between clients

### ISSUE THREAD

**Issue by jtloper1** [trailofbits/algo#571]
### OS / Environment
Windows 10 digital ocean droplet

### Ansible version

??

### Summary of the problem
Both Windows 10 vpn clients are unable to see each other in "network" I have made both clients discoverable in vpn connection properties. Have also told ufw to allow samba. What configuration changes would need to be made to allow file and printer sharing?

**Comment by dguido** [comment]
Intended default behavior. See config.cfg
