### ISSUE TITLE
VPN connection stops working until I disconnect and reconnect

### ISSUE THREAD

**Issue by bryceliu05** [trailofbits/algo#576]
### OS / Environment
Android 7.1.2

### Ansible version
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

### Version of components from `requirements.txt`
$ for p in msrestazure setuptools ansible dopy boto boto3 azure msrest apache-libcloud six pyopenssl jinja2; do pip show $p; done
Name: setuptools
Version: 20.7.0
Summary: Easily download, build, install, upgrade, and uninstall Python packages
Home-page: https://github.com/pypa/setuptools
Author: Python Packaging Authority
Author-email: distutils-sig@python.org
License: UNKNOWN
Location: /usr/lib/python2.7/dist-packages
Requires: 
Name: ansible
Version: 2.3.0.0
Summary: Radically simple IT automation
Home-page: https://ansible.com/
Author: Ansible, Inc.
Author-email: info@ansible.com
License: GPLv3
Location: /usr/lib/python2.7/dist-packages
Requires: 
Name: six
Version: 1.10.0
Summary: Python 2 and 3 compatibility utilities
Home-page: http://pypi.python.org/pypi/six/
Author: Benjamin Peterson
Author-email: benjamin@python.org
License: MIT
Location: /usr/lib/python2.7/dist-packages
Requires: 
Name: Jinja2
Version: 2.8
Summary: A small but fast and easy to use stand-alone template engine written in pure python.
Home-page: http://jinja.pocoo.org/
Author: Armin Ronacher
Author-email: armin.ronacher@active-4.com
License: BSD
Location: /usr/lib/python2.7/dist-packages
Requires: MarkupSafe

### Summary of the problem
On one particular Wifi network, when I initially connect to my VPN server, everything works fine. Shortly thereafter (usually after 15 minutes or so), the connection silently stops working--if I try to access a website, the connection attempt times out, and eventually Chrome on Android may say that I'm offline due to DNS_PROBE_FINISHED_NO_INTERNET. However, the VPN icon remains, and the Strongswan client claims that I'm still connected.

This only appears to happen on this one specific wifi network.

### Steps to reproduce the behavior
Connect to this one specific wifi network. Connect to VPN. Wait a while. Try to access websites and watch it fail.

### The way of deployment (cloud or local)
Local (on an Amazon EC2 instance I manage myself, instead of created through the algo script)

### Expected behavior
I should still be able to connect to everything.

### Actual behavior
All connections timeout.

### Full log
Sorry, I'm not sure what I'm being asked to do here. I'm attaching the Strongswan logs, though, in case that helps.
[strongswan-1.8.2.log.txt](https://github.com/trailofbits/algo/files/1039710/strongswan-1.8.2.log.txt)

**Comment by dguido** [comment]
Those logs only show that you connected directly. Some networks purposefully interfere with VPN connections and there's not much you can do about it. Check the troubleshooting docs for some brief discussion of issues that bad routers can cause.
