### ISSUE TITLE
Is GCE still only for testing?

### ISSUE THREAD

**Issue by lperry** [trailofbits/algo#577]
Sorry if this has been answered already (I checked the FAQ, troubleshooting docs, and existing issues), but is GCE still only for testing? On [line 412 in algo](https://github.com/trailofbits/algo/blob/master/algo#L412), GCE is called out for testing only, but the issue it references (https://github.com/trailofbits/algo/issues/369) has already been closed (and looks resolved).

Thanks!

**Comment by dguido** [comment]
It should work now
