### ISSUE TITLE
Use Algo with DynDNS?

### ISSUE THREAD

**Issue by TheLux83** [trailofbits/algo#578]
Hey there, I hope I'm in the right area for this kind of question.

I'm using algo at home on my Ubuntu Server. Everything went fine and I can use it from outside my network.

The only thing is: I don't have an external static IP address. So the next time, my provider is kicking me out, algo won't work anymore, because I got another IP address.

Is there a possibility to set up algo with a DynDNS name? In my case I'm using https://freedns.afraid.org/

I'm sorry, if this question was asked before, but I didn't found any answer in my google and github search-fu.

I hope someone can help my with this issue, because I think Algo is awesome and I would like to use it.
Many thanks in advance

**Comment by dguido** [comment]
You would have to recreate all your certs for the domain name you're using. Certs created by Algo are tied to the IP.
