### ISSUE TITLE
Using w/ DNS name pointing to IPv4 and IPv6 records

### ISSUE THREAD

**Issue by MichaelCWarren** [trailofbits/algo#592]
This is more of a question than an issue, but I'm attempting to setup a vpn pointing to a dns name.  When running the install locally on a fresh ubuntu vm, the install fails because of a DNS decrypt issue.  

I believe that's because of the SAN entries on the certs that are generated. By changing that I was able to get the script to run completely.  However, when attempting to connect via IPv6 from my iPhone, the connection always fails.  

Here is the log... Does anyone have any insight into what is going on here?

`Jun  8 10:18:17 abra charon: 07[CFG]   candidate: %any...%any, prio 28
Jun  8 10:18:17 abra charon: 07[CFG] found matching ike config: %any...%any with prio 28
Jun  8 10:18:17 abra charon: 07[IKE] xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx is initiating an IKE_SA
Jun  8 10:18:17 abra charon: 07[IKE] IKE_SA (unnamed)[1] state change: CREATED => CONNECTING
Jun  8 10:18:17 abra charon: 07[CFG] selecting proposal:
Jun  8 10:18:17 abra charon: 07[CFG]   proposal matches
Jun  8 10:18:17 abra charon: 07[CFG] received proposals: IKE:AES_GCM_16_128/PRF_HMAC_SHA2_512/ECP_256
Jun  8 10:18:17 abra charon: 07[CFG] configured proposals: IKE:AES_GCM_16_128/PRF_HMAC_SHA2_512/ECP_256, IKE:AES_CBC_128/HMAC_SHA2_512_256/PRF_HMAC_SHA2_512/ECP_256, IKE:AES_CBC_128/HMAC_SHA2_384_192/PRF_HMAC_SHA2_384/ECP_256
Jun  8 10:18:17 abra charon: 07[CFG] selected proposal: IKE:AES_GCM_16_128/PRF_HMAC_SHA2_512/ECP_256
Jun  8 10:18:17 abra charon: 07[IKE] sending cert request for "CN=xxx.xxxxxxx.xxx"
Jun  8 10:18:17 abra charon: 07[ENC] generating IKE_SA_INIT response 0 [ SA KE No N(NATD_S_IP) N(NATD_D_IP) CERTREQ N(MULT_AUTH) ]
Jun  8 10:18:17 abra charon: 07[NET] sending packet: from xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx[500] to xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx[500] (265 bytes)
Jun  8 10:18:17 abra charon: 07[MGR] checkin IKE_SA (unnamed)[1]
Jun  8 10:18:17 abra charon: 07[MGR] checkin of IKE_SA successful
Jun  8 10:18:17 abra charon: 04[NET] sending packet: from xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx[500] to xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx[500]
Jun  8 10:18:20 abra charon: 03[NET] received packet: from xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx[500] to xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx[500]
Jun  8 10:18:20 abra charon: 03[NET] waiting for data on sockets
Jun  8 10:18:20 abra charon: 08[MGR] checkout IKEv2 SA by message with SPIs 07266fd439bc15bc_i 0000000000000000_r
Jun  8 10:18:20 abra charon: 08[MGR] IKE_SA (unnamed)[1] successfully checked out
Jun  8 10:18:20 abra charon: 08[NET] received packet: from xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx[500] to xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx[500] (240 bytes)
Jun  8 10:18:20 abra charon: 08[ENC] parsed IKE_SA_INIT request 0 [ SA KE No N(NATD_S_IP) N(NATD_D_IP) N(FRAG_SUP) ]
Jun  8 10:18:20 abra charon: 08[IKE] received retransmit of request with ID 0, retransmitting response
Jun  8 10:18:20 abra charon: 08[NET] sending packet: from xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx[500] to xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx[500] (265 bytes)
Jun  8 10:18:20 abra charon: 08[MGR] checkin IKE_SA (unnamed)[1]
Jun  8 10:18:20 abra charon: 08[MGR] checkin of IKE_SA successful
Jun  8 10:18:20 abra charon: 04[NET] sending packet: from xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx[500] to xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx[500]
Jun  8 10:18:23 abra charon: 03[NET] received packet: from xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx[500] to xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx[500]
Jun  8 10:18:23 abra charon: 03[NET] waiting for data on sockets
Jun  8 10:18:23 abra charon: 09[MGR] checkout IKEv2 SA by message with SPIs 07266fd439bc15bc_i 0000000000000000_r
Jun  8 10:18:23 abra charon: 09[MGR] IKE_SA (unnamed)[1] successfully checked out
Jun  8 10:18:23 abra charon: 09[NET] received packet: from xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx[500] to xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx[500] (240 bytes)
Jun  8 10:18:23 abra charon: 09[ENC] parsed IKE_SA_INIT request 0 [ SA KE No N(NATD_S_IP) N(NATD_D_IP) N(FRAG_SUP) ]
Jun  8 10:18:23 abra charon: 09[IKE] received retransmit of request with ID 0, retransmitting response
Jun  8 10:18:23 abra charon: 09[NET] sending packet: from xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx[500] to xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx[500] (265 bytes)
Jun  8 10:18:23 abra charon: 09[MGR] checkin IKE_SA (unnamed)[1]
Jun  8 10:18:23 abra charon: 09[MGR] checkin of IKE_SA successful
Jun  8 10:18:23 abra charon: 04[NET] sending packet: from xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx[500] to xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx[500]
Jun  8 10:18:26 abra charon: 03[NET] received packet: from xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx[500] to xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx[500]
Jun  8 10:18:26 abra charon: 03[NET] waiting for data on sockets
Jun  8 10:18:26 abra charon: 10[MGR] checkout IKEv2 SA by message with SPIs 07266fd439bc15bc_i 0000000000000000_r
Jun  8 10:18:26 abra charon: 10[MGR] IKE_SA (unnamed)[1] successfully checked out
Jun  8 10:18:26 abra charon: 10[NET] received packet: from xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx[500] to xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx[500] (240 bytes)
Jun  8 10:18:26 abra charon: 10[ENC] parsed IKE_SA_INIT request 0 [ SA KE No N(NATD_S_IP) N(NATD_D_IP) N(FRAG_SUP) ]
Jun  8 10:18:26 abra charon: 10[IKE] received retransmit of request with ID 0, retransmitting response
Jun  8 10:18:26 abra charon: 10[NET] sending packet: from xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx[500] to xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx[500] (265 bytes)
Jun  8 10:18:26 abra charon: 10[MGR] checkin IKE_SA (unnamed)[1]
Jun  8 10:18:26 abra charon: 10[MGR] checkin of IKE_SA successful
Jun  8 10:18:26 abra charon: 04[NET] sending packet: from xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx[500] to xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx[500]
Jun  8 10:18:47 abra charon: 11[MGR] checkout IKEv2 SA with SPIs 07266fd439bc15bc_i f59a2a7fa0dd27a5_r
Jun  8 10:18:47 abra charon: 11[MGR] IKE_SA (unnamed)[1] successfully checked out
Jun  8 10:18:47 abra charon: 11[JOB] deleting half open IKE_SA after timeout
Jun  8 10:18:47 abra charon: 11[MGR] checkin and destroy IKE_SA (unnamed)[1]
Jun  8 10:18:47 abra charon: 11[IKE] IKE_SA (unnamed)[1] state change: CONNECTING => DESTROYING
Jun  8 10:18:47 abra charon: 11[MGR] checkin and destroy of IKE_SA successful`

On the iOS Console, I get an error which says something to the effect of "failed to receive IKE_SA INIT"...

The same connection works w/ IPv4.

**Comment by ivanfetch** [comment]
@MichaelCWarren Where / what did you change to successfully use a DNS name with the SAN cert?

**Comment by MichaelCWarren** [comment]
Honestly, I don't remember.  I ended up just installing it myself and creating the certs manually.

On Jun 22, 2017, at 5:15 AM, Ivan Fetch <notifications@github.com<mailto:notifications@github.com>> wrote:


@MichaelCWarren<https://github.com/michaelcwarren> Where / what did you change to successfully use a DNS name with the SAN cert?

**Comment by dguido** [comment]
We're not interesting in supporting this use case, sorry!
