### ISSUE TITLE
Algo gets fatal error (I've confirmed that my API token is not read-only)

### ISSUE THREAD

**Issue by davisx23** [trailofbits/algo#596]
Please don't close my ticket without providing a response. my last issue was closed without a response that provided any guidance on what I'm doing wrong.

### OS / Environment

Windows 10+

### Ansible version

**I wasn't sure how to do check this**
### Version of components from `requirements.txt`

msrestazure
setuptools>=11.3
ansible>=2.1,<2.2.1
dopy==0.3.5
boto>=2.5
boto3
azure==2.0.0rc5
msrest==0.4.1
apache-libcloud
six
pyopenssl
jinja2==2.8

### Summary of the problem
Every time I attempt to run the ./algo (after following every step and trying on two different Windows machines) I encounter a fatal error when it comes to "Delete the existing Algo SSH keys."

### Steps to reproduce the behavior

Followed these steps for Windows: https://github.com/trailofbits/algo/blob/master/docs/deploy-from-windows.md

Continued into these steps when directed: https://github.com/trailofbits/algo

### The way of deployment (cloud or local)

cloud i'm assuming (Digital Ocean)

### Expected behavior

Algo should setup with Digital Ocean

### Actual behavior

fatal error during the setup

### Full log

(env) penguin@DESKTOP-8D6HNQF:~/algo$ ./algo

  What provider would you like to use?
    1. DigitalOcean
    2. Amazon EC2
    3. Microsoft Azure
    4. Google Compute Engine (only for testing, see issue #369)
    5. Install to existing Ubuntu 16.04 server

Enter the number of your desired provider
: 1

Enter your API token. The token must have read and write permissions (https://cloud.digitalocean.com/settings/api/tokens):
[pasted values will not be displayed]
:

Name the vpn server:
[algo.local]: monkeyvpn01

  What region should the server be located in?
    1.  Amsterdam        (Datacenter 2)
    2.  Amsterdam        (Datacenter 3)
    3.  Frankfurt
    4.  London
    5.  New York         (Datacenter 1)
    6.  New York         (Datacenter 2)
    7.  New York         (Datacenter 3)
    8.  San Francisco    (Datacenter 1)
    9.  San Francisco    (Datacenter 2)
    10. Singapore
    11. Toronto
    12. Bangalore
Enter the number of your desired region:
[7]: 11

Do you want macOS/iOS clients to enable "VPN On Demand" when connected to cellular networks?
[y/N]: y

Do you want macOS/iOS clients to enable "VPN On Demand" when connected to Wi-Fi?
[y/N]: y

List the names of trusted Wi-Fi networks (if any) that macOS/iOS clients exclude from using the VPN (e.g., your home network. Comma-separated value, e.g., HomeNet,OfficeWifi,AlgoWiFi)
:

Do you want to install a DNS resolver on this VPN server, to block ads while surfing?
[y/N]: y

Do you want each user to have their own account for SSH tunneling?
[y/N]: n

Do you want to apply operating system security enhancements on the server? (warning: replaces your sshd_config)
[y/N]: n

Do you want the VPN to support Windows 10 or Linux Desktop clients? (enables compatible ciphers and key exchange, less secure)
[y/N]: n

Do you want to retain the CA key? (required to add users in the future, but less secure)
[y/N]: n

PLAY [Configure the server] ****************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Generate the SSH private key] ********************************************
ok: [localhost]

TASK [Generate the SSH public key] *********************************************
ok: [localhost]

TASK [Change mode for the SSH private key] *************************************
ok: [localhost]

TASK [Ensure the dynamic inventory exists] *************************************
ok: [localhost]

TASK [cloud-digitalocean : Set the DigitalOcean Access Token fact] *************
ok: [localhost]

TASK [cloud-digitalocean : Delete the existing Algo SSH keys] ******************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "The conditional check 'ssh_keys.changed != true' failed. The error was: error while evaluating conditional (ssh_keys.changed != true): 'dict object' has no attribute 'changed'"}

TASK [cloud-digitalocean : Collect the fail error] *****************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to load DO_API_TOKEN"}
...ignoring

TASK [cloud-digitalocean : debug] **********************************************
ok: [localhost] => {
    "ssh_keys": {
        "changed": false,
        "failed": true,
        "msg": "Unable to load DO_API_TOKEN"
    }
}

TASK [cloud-digitalocean : fail] ***********************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Please, ensure that your API token is not read-only."}

TASK [cloud-digitalocean : debug] **********************************************
ok: [localhost] => {
    "fail_hint": [
        "Sorry, but something went wrong!",
        "Please check the troubleshooting guide.",
        "https://trailofbits.github.io/algo/troubleshooting.html"
    ]
}

TASK [cloud-digitalocean : fail] ***********************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Failed as requested from task"}

PLAY RECAP *********************************************************************
localhost                  : ok=9    changed=0    unreachable=0    failed=1

(env) penguin@DESKTOP-8D6HNQF:~/algo$

**Comment by dguido** [comment]
This is not a bug in Algo. Please use Slack for support.
