### ISSUE TITLE
IPv6 for EC2

### ISSUE THREAD

**Issue by dguido** [trailofbits/algo#60]
We may want to remove the playbook steps that refer to IPv6 on EC2 and GCE, unless we can get IPv6 working on those clouds.

**Comment by defunctio** [comment]
I can confirm that AWS does not support IPv6 on EC2.

**Comment by gunph1ld** [comment]
> Google Compute Engine networks do not support IPv6 at all.

**Comment by gunph1ld** [comment]
IPv6 enabled only for Digital Ocean, yes, but we need to configure IPv6 local network and a default gateway for a VPN connection, to avoid passing traffic to an ISP network (if an ISP supports IPv6)

**Comment by defunctio** [comment]
https://aws.amazon.com/blogs/aws/new-ipv6-support-for-ec2-instances-in-virtual-private-clouds/

**Comment by dguido** [comment]
https://wiki.strongswan.org/issues/817#note-4

**Comment by samkelleher** [comment]
Just to loop in, AWS EC2 now has IPv6 in [most of its regions](https://aws.amazon.com/blogs/aws/aws-ipv6-update-global-support-spanning-15-regions-multiple-aws-services/).

**Comment by aboutte** [comment]
When #431 is merged this can be closed.
