### ISSUE TITLE
Not getting IP after a few days

### ISSUE THREAD

**Issue by TychoSchenkeveld** [trailofbits/algo#600]
### OS / Environment

Scaleway VPS

### Ansible version

2.1.2.0

### Version of components from `requirements.txt`

Installs successfully. Do you really need this? I don't have the system on which I ran the install anymore :)

### Summary of the problem
Clients don't get IP after a few days

### Steps to reproduce the behavior
After a few days of successful service, Connect to VPN. Connects fine but does not get an IP.

PS: I noticed that the IP address keeps going up over the days - I have a feeling it eventually just runs out of addresses? Apparently it doesn't notice the same device connects and reserves a new IP?

### The way of deployment (cloud or local)
Cloud (Deployed from Ubuntu machine I don't have with me here unfortunately)

### Expected behavior
IP address assigned to client

### Actual behavior
No IP address assigned to client (both Android and iOS). Reboot solves problem.

### Full log

Don't have this anymore unfortunately.

**Comment by dguido** [comment]
Are you running the latest version of Algo? We modified some of the configuration about a month or two ago that turned off and then turned back on the Dead Peer Detection feature of IPSEC.

**Comment by TychoSchenkeveld** [comment]
No, I installed it about 2 months ago. Thanks, I'll try that!

**Comment by dguido** [comment]
You can do that 1 or 2 ways:

1. Setup a new server: tar up the entire pki directory on the server and bring it over to the new one
2. Stick with the existing server: set up the apt package pins to get strongswan 5.5.x on Ubuntu 16.04 and turn on DPD in the settings.

**Comment by TychoSchenkeveld** [comment]
Thanks, that's clear! I'll just redeploy I think.

**Comment by TychoSchenkeveld** [comment]
Hi, sorry to bother you again :)

I decided to try and change the current config as I wanted to become more familiar with the config files anyway, and it sounded like the easier way to go.

I found how to turn on the DPD in ipsec.conf, no issue with that. I used the same settings as are currently deployed by algo (dpdaction=clear).

However, deploying 5.5.1 seems to be harder: It seems like the official repos for Xenial still include 5.3.5 (which is what I have). Even the backports repo does not supply a newer version. The earliest version that supplies 5.5.1 is Zesty (17.04). Are you sure I should force the Zesty package to install? As it could cause loads of library conflicts.

I don't see any attempt in the Algo sources to do this on newly installed servers. Nor do I see it trying to install from another source than the official repo.

Or would you recommend to deploy on Zesty at all? Is there an issue with DPD on 5.3.5?
