### ISSUE TITLE
Can you help me how to retrieve the p12 (user certificate) password? I missed to take note of the key during installation.

### ISSUE THREAD

**Issue by dhalavoi** [trailofbits/algo#603]
### OS / Environment
AWS EC2

### Summary of the problem
Can you help me how to retrieve the p12 (user certificate) password? I missed to take note of the key during installation.

**Comment by dguido** [comment]
You cant

**Comment by dhalavoi** [comment]
Thank you. Algo is amazing!!

**Comment by pconnell99** [comment]
I also misread the installation instructions.  Didn't realise the password was there at end of install (wasn't mentioned in instructions) so closed the window assuming install had gone ahead.  Seems I'll have to wipe/reinstall and try again.  Maybe docs could _**EMPHASISE**_ this?

**Comment by dhalavoi** [comment]
Hi Pconnell99, I believe there is no way to retrieve. You should delete the previous installation and reinstall Algo. All the best.
