### ISSUE TITLE
Warning: Permanently added 'x.x.x.x' (ECDSA) to the list of known hosts.\r\nPermission denied (publickey,password).\r\n", "unreachable

### ISSUE THREAD

**Issue by SawRobinLin** [trailofbits/algo#608]
### OS / Environment

On my own Ubuntu 16.04LTS which is reside in our virtualization host with public ip.

### Summary of the problem
As suggestion of previous, I can't get successfully install even I also deleted to algo certificate which is under configs directory 
![image](https://user-images.githubusercontent.com/20481586/27525509-75379a2a-5a64-11e7-828d-a5c88d5dc17e.png)

**Comment by GordeevD** [comment]
Same issue. I'm using ssh authorisation on my droplet
