### ISSUE TITLE
Azure IPv6 support

### ISSUE THREAD

**Issue by doodlemania2** [trailofbits/algo#610]
### OS / Environment
Running server in Azure
Client is Linux and Windows

### Ansible version
Whatever happens in virtualenv :)

### Summary of the problem
More of a suggestion - got Algo up and going and showing my IP address as the server deployed elsewhere in the world. IP4 only though. IP6 still shows my local ISP. My ISP prefers IP6 now so things like Facebook and Google go via IP6 instead of IP4 first, rendering Algo not in the picture.

### Expected behavior
Not all cloud deployment models will support IP6 yet. Azure does. Let's use it!

**Comment by defunctio** [comment]
@doodlemania2 Currently I think we only have IPv6 support DO/EC2. We would happily accept a PR for Azure though.

I believe all you would need to do is toggle the `ipv6_support` fact and update the [azure role](https://github.com/trailofbits/algo/blob/master/roles/cloud-azure/tasks/main.yml) for ipv6 details. You can use the defaults defined in [config.cfg](https://github.com/trailofbits/algo/blob/26c202ded5acbd4548bcf9b992dac39dc266531c/config.cfg#L33) and update the role for support. You can use the DO/EC2 roles as a reference if needed.

**Comment by jackivanov** [comment]
No support in Ansible yet

**Comment by jackivanov** [comment]
It is not possible at the moment. 

> The public IPv6 addresses cannot be assigned to a VM. They can only be assigned to a load balancer.

I don't see any reasons to create an extra load balancer. Closing the issue for now.

[details-and-limitations](https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-ipv6-overview?toc=%2fazure%2fvirtual-network%2ftoc.json#details-and-limitations)
