### ISSUE TITLE
Cannot connect to VPN, gives error "received NO_PROPOSAL_CHOSEN notify, no CHILD_SA built"

### ISSUE THREAD

**Issue by frederik3276** [trailofbits/algo#611]
### OS / Environment
Ubuntu 16.04

### Client
Arch Linux 4.11.7-1-ARCH

### Ansible version
ansible 2.0.0.2

### Version of components from `requirements.txt`
Name: msrestazure
Version: 0.4.11

Name: setuptools
Version: 20.7.0

Name: ansible
Version: 2.0.0.2

Name: msrest
Version: 0.4.11

Name: six
Version: 1.10.0

Name: Jinja2
Version: 2.8

### Summary of the problem
Cannot connect to VPN, gives error "received NO_PROPOSAL_CHOSEN notify, no CHILD_SA built", when I'm trying to connect with the command, "ipsec up ikev2-[my ip]". 

I am an newbie to IPsec VPN's, so any help on this issue would be greatly appreciated.

Thanks,
Frederik

### Steps to reproduce the behavior
Run ipsec up ikev2-[my ip]

### The way of deployment (cloud or local)
local

### Expected behavior
To not provide any error - I am newbie, so please bare with me.

### Actual behavior
Provides error, as you can see in the full log section.

### Full log
`# ipsec up ikev2-[my ip]`
initiating IKE_SA ikev2-[my ip][2] to [my ip]
generating IKE_SA_INIT request 0 [ SA KE No N(NATD_S_IP) N(NATD_D_IP) N(FRAG_SUP) N(HASH_ALG) N(REDIR_SUP) ]
sending packet: from 10.24.13.17[500] to [my ip][500] (354 bytes)
received packet: from [my ip][500] to 10.24.13.17[500] (289 bytes)
parsed IKE_SA_INIT response 0 [ SA KE No N(NATD_S_IP) N(NATD_D_IP) CERTREQ N(FRAG_SUP) N(HASH_ALG) N(MULT_AUTH) ]
local host is behind NAT, sending keep alives
received cert request for "CN=[my ip]"
sending cert request for "CN=[my ip]"
authentication of 'CN=frederik' (myself) with ECDSA_WITH_SHA256_DER successful
sending end entity cert "CN=frederik"
establishing CHILD_SA ikev2-[my ip]
generating IKE_AUTH request 1 [ IDi CERT N(INIT_CONTACT) CERTREQ IDr AUTH CPRQ(ADDR DNS) SA TSi TSr N(MOBIKE_SUP) N(NO_ADD_ADDR) N(MULT_AUTH) N(EAP_ONLY) N(MSG_ID_SYN_SUP) ]
sending packet: from 10.24.13.17[4500] to [my ip][4500] (894 bytes)
received packet: from [my ip][4500] to 10.24.13.17[4500] (544 bytes)
parsed IKE_AUTH response 1 [ EF(1/2) ]
received fragment #1 of 2, waiting for complete IKE message
received packet: from [my ip][4500] to 10.24.13.17[4500] (241 bytes)
parsed IKE_AUTH response 1 [ EF(2/2) ]
received fragment #2 of 2, reassembling fragmented IKE message
parsed IKE_AUTH response 1 [ IDr CERT AUTH CPRP(ADDR DNS) N(MOBIKE_SUP) N(NO_ADD_ADDR) N(NO_PROP) ]
received end entity cert "CN=[my ip]"
  using certificate "CN=[my ip]"
  using trusted ca certificate "CN=[my ip]"
checking certificate status of "CN=[my ip]"
certificate status is not available
  reached self-signed root ca with a path length of 0
authentication of '[my ip]' with ECDSA_WITH_SHA256_DER successful
IKE_SA ikev2-[my ip][2] established between 10.24.13.17[CN=frederik]...[my ip][[my ip]]
installing DNS server 172.16.0.1 via resolvconf
installing new virtual IP 10.19.48.1
received NO_PROPOSAL_CHOSEN notify, no CHILD_SA built
failed to establish CHILD_SA, keeping IKE_SA
establishing connection 'ikev2-[my ip]' failed

**Comment by dguido** [comment]
What client are you connecting with?

**Comment by frederik3276** [comment]
Hello dguido,

Thank you for the reply, I am connecting with the client Arch Linux 4.11.7-1-ARCH.

Best,
Frederik

**Comment by dguido** [comment]
You need to build with the VPN with the Linux question checked Y and set up Network Manager accordingly on the client. If you don't, you'll get an error that looks like this one.
