### ISSUE TITLE
Documentation re Elastic IP usage 

### ISSUE THREAD

**Issue by bluetardis** [trailofbits/algo#612]
### OS / Environment

AWS

### Summary of the problem
I need to rebuild my AWS VPNs as due to maintenance on rebuild they all have new Public IP Addresses.

Looking through the issues I can see references to several previous issues/pull requests that are now marked as closed.

Problem: 
What is the process when setup to use Elastic IP as it doesn't seem to be documented?

**Comment by bluetardis** [comment]
Is there anything anyone can point me to?

**Comment by dguido** [comment]
We already use ElasticIP. Maybe you're on an old version?

https://github.com/trailofbits/algo/blob/a225bde2b8454380017e09ac23ac8d876594311f/roles/cloud-ec2/templates/stack.yml.j2#L187-L194

**Comment by bluetardis** [comment]
so....
I am using the latest version/build and there were elastic IPs available.

I was able to get it work by watching the script and manually assigning an Elastic IP using the AWS Console during reboot phase.

It wasn't finding it by default
