### ISSUE TITLE
PFSense router setup with Algo VPN

### ISSUE THREAD

**Issue by benzin1984** [trailofbits/algo#614]
This isn't an issue, just a write-up on PFSense config to make it work with Algo VPN. A small change is required to /etc/ipsec.conf on the VPS side, to create a profile to match PFSense settings.

I've now used PFSense with this config for a few weeks, with good stability, it works very well for me. Here's my settings:

the vps's ipsec.conf needs to be modified thusly (rest of the lines stay the same as before. Remove single quote):

'#   right=%any
'    rightauth=pubkey
'#   rightsourceip=10.19.48.0/24,fd9d:bc11:4020::/48
'#   rightdns=172.16.0.1_
'
'conn vpn2
'
'   right=%any
'   rightid=my_id
'   rightsubnet=10.19.48.1/24
'   rightdns=172.16.0.1
'   auto=add
'
'conn vpn1
'   
'   right=%any
'   rightsourceip=10.19.48.0/24,fd9d:bc11:4020::/48
'   rightdns=172.16.0.1
'   auto=add

I think the main problem that prevented the default config from working for me was the rightsourceip setting. rightdns is actually not needed, as pfsense won't be able to change it's dns just for vpn tunnel, from my tests.

![phase_1 1](https://user-images.githubusercontent.com/29918328/27862533-feaecc86-61c8-11e7-9200-15809bfc1ee1.png)

![phase_1 2](https://user-images.githubusercontent.com/29918328/27862545-121d5f8a-61c9-11e7-8e49-e32de26a94ba.png)

![phase_2 1](https://user-images.githubusercontent.com/29918328/27862549-1a31267a-61c9-11e7-8545-3e602b374fd2.png)

![phase_2 2](https://user-images.githubusercontent.com/29918328/27862553-1f89e986-61c9-11e7-890e-38cf268b53df.png)

I've created a virtual ip and used nat to translate my lan's opt1 interface to 10.19.48.1/24 that algo vpn needs.
![virtual_ip](https://user-images.githubusercontent.com/29918328/27862561-2a048d08-61c9-11e7-88f4-f566fdf2498d.png)

Advanced ipsec settings are:

![ipsec_advanced_settings](https://user-images.githubusercontent.com/29918328/27862568-2f4125ce-61c9-11e7-90b9-b48b031deecc.png)

MSS clamping doesn't do anything, as ipsec uses UDP protocol, not TCP. I've had issues with black-hole traffic due to MTU size being too large. Can set up an option 26 on DHCP server, to set the MTU. However, not all devices respect that option, so may have to set MTU to 1400 manually on client devices.

Hope someone finds this useful.

**Comment by davidemyers** [comment]
What do you think of my approach documented [here](https://gist.github.com/davidemyers/c74ddbb5d37e4c8288cd60cfb0f1b445)? It doesn't require double-NAT, handles the MSS on the Algo side, and doesn't overlap with the address space used by normal Algo clients.

**Comment by benzin1984** [comment]
Interesting David, I'll test when I have time. My knowledge isn't great, learning as I poke around, sorry if I say something silly.

- My PFSense version is 2.3.4. It worked with certs, had to manually paste them in to the standard PFSense cacert manager window.
- I've only set up ipv4, haven't tested ipv6 at all.
- DNS queries seem to be redirected through algo vpn, though I haven't tested thoroughly. I haven't enabled DNS query service on the opt1 interface, which I use for vpn tunnel. DNS servers dynamically change when I switch from one interface to another, and do dnsleaktest online.
- I use the same algo vps for roaming clients and my pfsense tunnel, seems to work ok. If they end up sharing the same subnet, I don't think it matters to me.
- I haven't found any problems with double-NATting, personally. I know it's frowned upon, but makes it easier for me to configure.
- I thought that MSS clamping didn't matter when I was testing, I think it only affects TCP traffic? And ipsec uses UDP. I'll do some more testing..

Nice script, it's cleaner than my hacked together setup.

**Comment by vrms** [comment]
just clarifying ...

your pfSense is a local machine that routes your local network and when you say **VPS**, you mean a remote Linux Server running an instance of Algo, right?

your local pfSense is just the client that connects to your remote (VPS) Algo Server, so to speak.

I furthermore guess the installation of your remote Algo server has been conducted from a local Linux or Mac computer and not from your pfSense machine?

**Comment by benzin1984** [comment]
Hi vrms. Yes, all you've said is correct, exactly.

On another note, I still don't know what mss clamping does on the pfsense vpn advanced config, doesn't seem to do anything for me. What I did find out though, is that changing mss size on the opt1 interface (in pfsense interface settings) allows some old android devices to connect correctly and use the vpn connection. Previously I couldn't use old unrooted androids via the vpn as the mtu size was being set too high. Now I can.
