### ISSUE TITLE
Potential new VPS providers for the installer

### ISSUE THREAD

**Issue by dguido** [trailofbits/algo#623]
This issue collects all the VPS providers that users have requested we support in the installer.

- [ ] [Vultr](https://github.com/trailofbits/algo/issues/488)
- [x] [Scaleway](https://github.com/trailofbits/algo/issues/384)
- [ ] [now.sh](https://github.com/trailofbits/algo/issues/434)
- [x] [Dreamhost Compute](https://github.com/trailofbits/algo/issues/334)
- [x] [Amazon Lightsail](https://github.com/trailofbits/algo/issues/136)

If you want to try and support any of these providers, read the documentation for [Unsupported Cloud Providers](https://github.com/trailofbits/algo/issues/334) for requirements and tips to get started.

**Comment by tarikd** [comment]
👍

**Comment by lourou** [comment]
Definitely, scaleway!

**Comment by jackivanov** [comment]
now.sh - not sure if it's even possible
vultr - required ansible 2.5 (just released)

**Comment by lodgnewt** [comment]
is it possible add in future arubacloud.com Cloud VPS?
