### ISSUE TITLE
Terraform support

### ISSUE THREAD

**Issue by jackivanov** [trailofbits/algo#626]
We definitely need to consider moving to [terraform](https://www.terraform.io/)
I suggest to replace all the cloud roles to terraform states and keep  the local role only to run ansible after terraform done with clouds.

pros:
1. No python libraries anymore. No mess. Only a file to run all the provides. Very simple installation and configuration.
2. A lot of [provides](https://www.terraform.io/docs/providers/) supported. We can be very flexible and more modular. Related to #623
3. Multi environment support
4. A way to destroy the infrastructure without touching web
5. ... ?

cons:
1. ... ?

**Comment by apolloclark** [comment]
I could write a Packer script to build an Amazon AWS AMI, then a terraform script to deploy the security groups, etc. and the AMI. Sound like a good starting point? I don't know much about Google, Azure, or Digital Ocean.

**Comment by jackivanov** [comment]
Moved to another project https://github.com/trailofbits/algo-ng
