### ISSUE TITLE
Syntax Error while loading YAML

### ISSUE THREAD

**Issue by khiren** [trailofbits/algo#627]
### OS / Environment

Windows 10

### Ansible version

2.2.0.0

### Summary of the problem
ERROR! Syntax Error while loading YAML.

The error appears to have been in '/root/algo/config.cfg': line 5, column 1, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

# Credentials will be generated for each one.
users:
^ here

I Keep getting this error when i try to finish setting up my vpn. Can you help if possible.
thanks

**Comment by gunph1ld** [comment]
You made a syntax error in the file. Try from scratch and use a yaml validator
