### ISSUE TITLE
Consider restricting the resource utilization of the services

### ISSUE THREAD

**Issue by dguido** [trailofbits/algo#63]
That way a single service does not necessarily crash or hang a node. E.g. charon doesn't need 100MB of memory to itself.

**Comment by gunph1ld** [comment]
I think cgroups is the best way. any thoughts?

**Comment by gunph1ld** [comment]
We may add CPU, Network, IO limitations also

**Comment by dguido** [comment]
I would bet that it is one of the proxies that are most likely to go haywire.
