### ISSUE TITLE
Add hardware requirements to README

### ISSUE THREAD

**Issue by deanishe** [trailofbits/algo#632]
Could you add the hardware requirements to the README?

I wasted a few hours trying to get algo running on an OpenVZ system before heavy Googling made clear that it isn't compatible. 

Now I'd like to try again, but there's no info on whether algo can run on the ARM hardware I have in mind. 

What about 32/64-bit support?

Thanks,
Dean

**Comment by dguido** [comment]
https://github.com/trailofbits/algo/blob/master/docs/deploy-to-unsupported-cloud.md

**Comment by deanishe** [comment]
ARM? 32/64-bit?

**Comment by dguido** [comment]
Not a problem

**Comment by deanishe** [comment]
Awesome. Thanks.
