### ISSUE TITLE
Add ability to use Floating IP on DigitalOcean?

### ISSUE THREAD

**Issue by bennettrogers** [trailofbits/algo#635]
### OS / Environment
MacOS

### Ansible version
2.2.0.0

### Summary of the problem
I see that AWS Elastic IPs are supported for EC2 instances. Would it be possible to add the same feature for DigitalOcean? DigitalOcean has the same feature, but they call them "Floating IPs".

The reason this came up is that the DigitalOcean instance that got created by Algo was assigned an IP that has apparently been blacklisted by spam detection services. This means that many sites I would visit from my new VPN would ask me to prove that I'm not a robot/spammer. If I could provision a Floating IP that I know is clean, and then assign that to my new VPN instance, I could avoid this issue.

For now I think I'll just destroy my Algo instance and create a new one, and cross my fingers that the new IP is clean.

**Comment by dguido** [comment]
Does this have cost implications?

**Comment by bennettrogers** [comment]
It works the same as Elastic IPs in AWS. There is an hourly charge for any Floating IPs that are not assigned to running instances. Otherwise they are free.

https://www.digitalocean.com/help/pricing-and-billing/general/

**Comment by gunph1ld** [comment]
Right now if a user deletes a VM the FIP will not be deleter and it will cause additional charges. Doesn't make any sense unless DO provide any orchestration support.

**Comment by bennettrogers** [comment]
I believe that is the same behavior as with EC2 elastic IP addresses. How does Algo handle the case where a user has an elastic IP assigned and then stops/terminates their VM?

**Comment by gunph1ld** [comment]
@bennettrogers CloudFormation
