### ISSUE TITLE
On-Demand for Bluetooth?

### ISSUE THREAD

**Issue by Manouchehri** [trailofbits/algo#638]
### OS / Environment

Client: macOS High Sierra

### Summary of the problem

At the moment the On-Demand rules only cover cellular and WiFi connections, not Bluetooth (e.g. tethering from an Android phone).

Would be nice if we could add another On-Demand entry for Bluetooth connections.

### Steps to reproduce the behavior

1. Set On-Demand for cellular and WiFi.
2. Connect via Bluetooth on macOS.

**Comment by gunph1ld** [comment]
[Supported values are Ethernet, WiFi, and Cellular.](https://developer.apple.com/library/content/featuredarticles/iPhoneConfigurationProfileRef/Introduction/Introduction.html#//apple_ref/doc/uid/TP40010206-CH1-SW27)

**Comment by Manouchehri** [comment]
@gunph1ld So by disabling and then enabling `Connect on Demand`, somehow that causes the VPN to reconnect on Bluetooth. 

![image](https://user-images.githubusercontent.com/7232674/30221464-5a726c12-9491-11e7-923d-f915f4f34e99.png)
![image](https://user-images.githubusercontent.com/7232674/30221469-61ae3a74-9491-11e7-9f87-63320636650a.png)

I guess if no `InterfaceTypeMatch` is set, then Bluetooth is included?
