### ISSUE TITLE
Add documentation for client to client communication

### ISSUE THREAD

**Issue by peterk** [trailofbits/algo#640]
Algo VPN would be perfect for talking to drones over a shared VLAN. I have successfully set up a Raspberry PI with Raspbian as a client. However, it is not clear from the documentation how clients need to be configured to be able to talk to each other when connected to the Algo VPN server. E.g. pinging or SSH:ing other 10.19.48.xx addresses does not work. Would it be possible to add this to the documentation?

**Comment by peterk** [comment]
The following changes on the VPS server allows for client to client communication. 

1. Change /etc/iptables/rules.v4 and make sure subnet communication is allowed:
`-A FORWARD -s 10.19.48.0/24 -d 10.19.48.0/24 -j ACCEPT`

2. Change /etc/ipsec.conf and add set leftsubnet to:
`leftsubnet=10.19.48.0/24`

I am no expert on ipsec or iptables rules so please have a look at the docs to verify they are correct for your use case.

**Comment by peterk** [comment]
Ideally this would be a question in the Algo setup process "Would you like clients to be able to communicate with each other?" which would result in these settings in the firewall and also apply sticky virtual IP:s to connecting clients.

**Comment by dguido** [comment]
Thanks for submitting this issue, however, we won't be adding more questions to the installer at this time. Each new question makes it more complicated for new users to get started and very few of them will understand or care what client to client communication means.

Btw, the setting for client to client communication is documented in the cfg file with the rest of the settings. Change the N to a Y and it works!
