### ISSUE TITLE
Improve readability of UserDefinedName and PayloadDisplayName in Config Profile

### ISSUE THREAD

**Issue by omarkassim** [trailofbits/algo#641]
### OS / Environment

macOS

### Ansible version

2.2.0.0

### Summary of the problem

I wanted to put in a quick request to see if we could get a few more user defined options to set the UserDefinedName and PayloadDisplayName in user.mobilconfig or alternatively set those variables automatically for better readability.

For example, I thought it would be a nice to allow a naming schema that helps identify hostname, city, country and IP address. For example:

[hostname] [Datacenter City] [Unicode Country Flag] [IP Address]

This will also help tremendously when someone has multiple VPNs that they're running at the same time.

I tested this on macOS and iOS and the Unicode Flag (i.e. an emoji) doesn't seem to break the config profile.

**macOS**
![screen shot 2017-07-29 at 18 21 30](https://user-images.githubusercontent.com/544282/28746053-e3e9b278-7495-11e7-978b-d21a9ffbe9b7.png)

![screen shot 2017-07-29 at 19 35 29](https://user-images.githubusercontent.com/544282/28746089-778c4f36-7496-11e7-8139-22a864d0321d.png)

**iOS**
![screen shot 2017-07-29 at 18 36 00](https://user-images.githubusercontent.com/544282/28746059-f6e6a7d2-7495-11e7-9763-dd4f5bd320f8.png)

**Comment by jackivanov** [comment]
Here is the initial naming issue - https://github.com/trailofbits/algo/issues/491
