### ISSUE TITLE
Trouble with MTU and Vodafone Fiber / Deutsche Bahn

### ISSUE THREAD

**Issue by klausbreyer** [trailofbits/algo#644]
### OS / Environment
The client runs on mac os. 

### Summary of the problem
On various networks (Deutsche Bahn Wifi on ICE, but also Vodafone Fiber via Cable 200mbit) various websites (including the one of my own company) seems down. 
Google works everywhere. 
From DSL and iPhoneTethering everything is fine. 

### Steps to reproduce the behavior
I tried to determine the correct mtu size, like I read in the readme. 
```
➜  test ping -s 1373 -D cloud.buzzbird.de
PING buzzbird-cloud.eu-central-1.elasticbeanstalk.com (52.28.197.157): 1373 data bytes
ping: sendto: Message too long
^C
--- buzzbird-cloud.eu-central-1.elasticbeanstalk.com ping statistics ---
1 packets transmitted, 0 packets received, 100.0% packet loss
➜  test ping -s 1372 -D cloud.buzzbird.de
PING buzzbird-cloud.eu-central-1.elasticbeanstalk.com (52.28.197.157): 1372 data bytes
1380 bytes from 52.28.197.157: icmp_seq=0 ttl=253 time=35.296 ms
^C
--- buzzbird-cloud.eu-central-1.elasticbeanstalk.com ping statistics ---
1 packets transmitted, 1 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 35.296/35.296/35.296/0.000 ms
➜  test sudo ifconfig en0 mtu 1372
```

but various websites (including our own) are still not accessible. 
```
➜  test wget cloud.buzzbird.de
--2017-08-01 15:25:23--  http://cloud.buzzbird.de/
Resolving cloud.buzzbird.de... 35.158.56.62, 52.28.197.157
Connecting to cloud.buzzbird.de|35.158.56.62|:80... connected.
HTTP request sent, awaiting response... ^C
➜  test
```

### The way of deployment (cloud or local)
cloud / ec2

**Comment by davesteele** [comment]
I had this problem with Linux as well. Solved as follows (per https://www.zeitgeist.se/2013/11/26/mtu-woes-in-ipsec-tunnels-how-to-fix/):

    $ iptables -t mangle -A FORWARD -o eth0 \
     -p tcp -m tcp --tcp-flags SYN,RST SYN \
     -m tcpmss --mss 1361:1536 \
     -j TCPMSS --set-mss 1360
    
    $ echo 1 >/proc/sys/net/ipv4/ip_no_pmtu_disc

**Comment by dguido** [comment]
@davesteele: If the troubleshooting guide needs an update then I would really appreciate a PR with better instructions. Thanks!

**Comment by davesteele** [comment]
This is not a troubleshooting problem. It is a bug. Someone with better Ansible experience should fix it.

**Comment by dguido** [comment]
Happy to take a closer look at it with @gunph1ld, but there is generally not much you can do to universally solve MTU problems. It's not a simple as an "ansible problem."

**Comment by davesteele** [comment]
It's not an ansible problem, it's a configuration problem that can be solved with ansible. Keeping the overall packet size within 1500 bytes would go a long way towards improving interoperability. The two commands above should be a pretty good first stab at the fix. There is a more general candidate solution in the comments at the referenced link that may or may not work.

**Comment by klausbreyer** [comment]
Yes, the 2 commands fixed it for me. Why not implement them as default, if so many people experience this problem?

**Comment by dguido** [comment]
What works for you will not for everyone else. You're oversimplifying a complex problem.

**Comment by klausbreyer** [comment]
I am not a networking export. What can be negative side-effects from this settings?

**Comment by davesteele** [comment]
There is a simple solution attached to [gce](https://github.com/trailofbits/algo/issues/686), This appears to be the reason the problem doesn't appear on everyone's radar.
