### ISSUE TITLE
docs/deploy-to-ubuntu.md should clarify that editing config.cfg is necessary

### ISSUE THREAD

**Issue by dmick** [trailofbits/algo#649]
Deployment from localhost with cloud provisioning mentions this, but deploy-to-ubuntu does not.

**Comment by OmgImAlexis** [comment]
Also that the requirements from the readme need to be installed before running the scripts on the ubuntu page.

**Comment by dguido** [comment]
Happy to accept a PR!

**Comment by OmgImAlexis** [comment]
@dguido if you're "happy to accept a PR" then why close this?

**Comment by dguido** [comment]
It's not a bug, and I'd like to reduce the clutter.

**Comment by OmgImAlexis** [comment]
This is exactly how you drive people away. If someone wants to help and sees an issue closed they'll expect it's been fixed.

**Comment by dmick** [comment]
I thought issues were for tracking things somewhere besides my head. Silly me.

**Comment by dguido** [comment]
Thanks for your thoughts on the matter, but I still do not consider this a bug and no issue needs to remain open for it. I'll repeat, if you care about this as much as it appears you do, then please submit a simple PR to address your concern and I'll gladly accept it. Insulting a project maintainer is generally frowned upon.

**Comment by dmick** [comment]
No one's insulting you.
