### ISSUE TITLE
blocked my other VPN ?

### ISSUE THREAD

**Issue by anarcheuz** [trailofbits/algo#651]
### OS / Environment

Linux ip-172-31-16-71 4.4.0-1030-aws #39-Ubuntu SMP Wed Aug 9 09:43:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### Ansible version

ansible 2.2.0.0
  config file = /home/ubuntu/algo-master/ansible.cfg
  configured module search path = Default w/o overrides

### Summary of the problem
Hi, I just setup Algo on my amazon EC2 instance to find out that my shadowsocks server cannot receive connections anymore, server is up but clients cannot connect to server. I suspect this is due to some firewall / ipsec rules dropping incoming packets ? 
I would like to keep shadowsocks just the time to fully test out algo. Is there a way I can make them co-exist ?

**Comment by dguido** [comment]
Algo rewrites your iptables rules
