### ISSUE TITLE
Can't install certificate through strongSwan on Amazon Fire TV Stick

### ISSUE THREAD

**Issue by notasausage** [trailofbits/algo#653]
I know this is a very specific request, but if anyone has ideas why I can't get this to work, I'd appreciate the help. I'm willing to share my process in getting this working if I can just get this last step...

### OS / Environment
I've setup algo using macOS Sierra 10.12 and I've got it deployed to Amazon EC2 without any issues. My Mac and iPhone are connected to the VPN, but in trying to get my Fire TV Stick to connect, I've run into an issue where the certificate cannot be installed.

It's a brand new Fire TV Stick (Fire OS 5.2.4.2, Fire TV Home Version 5.7.3-17) that I've installed ES File Explorer and Downloader on, and then sideloaded the latest version of the Chrome browser as well as the latest (1.9.2) strongSwan app for Android.

### Ansible version
ansible 2.2.0.0

### Summary of the problem
After setting up algo and deploying to EC2 successfully for 3 users (me, my wife, and the Fire TV Stick), I have the usual set of config files in `algo-master/configs/xx.xx.xx.xx` locally that I've used to setup my VPN profile on my MacBook Pro and my iPhone. I cannot get swanSong to connect though due to the fact that it does not install the certificate after importing the VPN profile. The VPN profile imports just fine, and the certificate is extracted from the `.sswan` file after I enter the password from Terminal, but it won't actually install the certificate. I get ```The certificate is not installed.```

### Steps to reproduce the behavior
Setup algo on macOS, deploy to EC2 with 3 users. Install [latest version of swanSong for Android](https://download.strongswan.org/Android/) on new Fire TV Stick. Copy Android `.sswan` config file created by algo setup process on MacBook Pro to Fire TV Stick via ES File Explorer's Dropbox connection (along with `.p12` file and `cacert.pem` certificate).

Run swanSong app and attempt to import `.sswan` file saved in Android filesystem using ```Import VPN profile``` option, get a JSON error:

`Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject`

Next step was to try and install with algo's included Android helper HTML file. Uploaded both that file and the `.sswan` VPN profile config to my own webserver via FTP, and pointed the Fire TV Stick's Chrome browser to the HTML file. Clicked on the single link from that HTML file in Chrome using Mouse Toggle, which properly imported the VPN profile using strongSwan. Then clicked `Import Certificate from VPN Profile` at the bottom of the screen, typed in the password I received in Terminal when algo was finished deploying to EC2, and the Certificate Installer popped up with the embedded p12 cert.

It asked for a name (prefilled with ```Certificate for "Algo xx.xx.xxx```, which included all but the last 2 digits of my server's IP), and Credential Use (```VPN and apps```). It also says:

```
The package contains:
one user key
one user certificate
one CA certificate
```

I clicked OK and got an error:

```The certificate is not installed.```

I've tried this several times, renaming the Certificate Name with a few different options (remove the rogue double quote for starters), switching Credential Use to ```Wi-Fi```, and nothing seems to do the trick.

Just for kicks, I also tried to manually import the p12 certificate from the Android filesystem (copied over from Dropbox), following [the Android client setup instructions](https://github.com/trailofbits/algo/blob/master/docs/client-android.md), with both swanSong and the default Certificate Installer in Android, and neither of them will install it.

### The way of deployment (cloud or local)
Deployed to AWS EC2 Free Tier server.

### Expected behavior
Expected to import the VPN profile into swanSong and have it connect my Amazon Fire TV Stick to my new algo VPN.

### Actual behavior
VPN profile is imported into swanSong, but certificate cannot be installed and swanSong cannot proceed to connect to the algo VPN.

### Full log
The swanSong log is empty (because it never tries to connect), but I did manage to use ADB (Android Debug Bridge) on the command line with `logcat` to get an idea of what was failing. Here's a bit of the log as the certificate import failed:

```
W/System.err( 1508): android.security.KeyChainException: java.lang.IllegalStateException: keystore is UNINITIALIZED
W/System.err( 1508): 	at android.security.KeyChain.getCertificateChain(KeyChain.java:383)
W/System.err( 1508): 	at org.strongswan.android.ui.VpnProfileImportActivity$UserCertificateLoader.loadInBackground(VpnProfileImportActivity.java:848)
W/System.err( 1508): 	at org.strongswan.android.ui.VpnProfileImportActivity$UserCertificateLoader.loadInBackground(VpnProfileImportActivity.java:831)
W/System.err( 1508): 	at android.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:312)
W/System.err( 1508): 	at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:69)
W/System.err( 1508): 	at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:57)
W/System.err( 1508): 	at android.os.AsyncTask$2.call(AsyncTask.java:292)
W/System.err( 1508): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err( 1508): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err( 1508): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err( 1508): 	at java.lang.Thread.run(Thread.java:818)
W/System.err( 1508): Caused by: java.lang.IllegalStateException: keystore is UNINITIALIZED
W/System.err( 1508): 	at android.os.Parcel.readException(Parcel.java:1556)
W/System.err( 1508): 	at android.os.Parcel.readException(Parcel.java:1501)
W/System.err( 1508): 	at android.security.IKeyChainService$Stub$Proxy.getCertificate(IKeyChainService.java:246)
W/System.err( 1508): 	at android.security.KeyChain.getCertificateChain(KeyChain.java:368)
W/System.err( 1508): 	... 10 more
```

**Comment by notasausage** [comment]
Just uninstalled strongSwan 1.9.2 and used 1.8.2 just for kicks. Same issue.

**Comment by notasausage** [comment]
It appears that swanSong is launching the Android system app Certificate Installer when clicking `Import Certificate from VPN Profile` after the `.sswan` file import, rather than extracting the certificate directly by itself. Not sure how to disable the Certificate Installer system app on my Fire TV Stick as the ES App Locker app doesn't seem to work on the device and I can't delete the system app without root access...

**Comment by gunph1ld** [comment]
It looks like a problem on the APP side and should be delegated to the strongswan dev team

**Comment by markl55** [comment]
@notasausage - have you raised this with the strongswan team - I'm having the same issue.

**Comment by notasausage** [comment]
@markl55 I created an issue with strongSwan today, we'll see if they address it. Probably not a top priority though.

[Importing .sswan VPN profile on Fire TV Stick opens Android Certificate Installer for embedded .p12](https://wiki.strongswan.org/issues/2418)

**Comment by notasausage** [comment]
According to the strongSwan folks, the system-wide KeyChain keystore is not initialized on a Fire TV Stick, and therefore the certificate cannot be imported (Certificate Installer is supposed to do this after all). Is there any way to use EAP with a username & password on an Algo VPN?

**Comment by ohjk** [comment]
did you get anywhere with EAP & user/pass?  Im trying to accomplish the same thing you are.

**Comment by notasausage** [comment]
> did you get anywhere with EAP & user/pass? Im trying to accomplish the same thing you are.

Not yet, I'm not really use how to use EAP. I just posed the question on the strongSwan wiki and I'm looking into it. I'll follow up here once I have more information though.

**Comment by jackivanov** [comment]
Closing for now
