### ISSUE TITLE
Windows 10 - Policy Match Error

### ISSUE THREAD

**Issue by QuentinMoss** [trailofbits/algo#659]
The algo deployment I am referencing is using the code from master at the date of this Issue creation. The deployment is working on OS X and iOS.

### OS / Environment
Windows 10
Version 1607
OS Build 14393.1593

### Summary of the problem
Deployed the most recent version of Algo to digital ocean and i receive Policy Match error on windows 10

### Steps to reproduce the behavior
Deploy aglo on Digital Ocean, follow the instructions for Windows on the Algo README, then try to connect to the VPN on Windows 10.

### The way of deployment (cloud or local)
Cloud

### Expected behavior
When I click "Connect" to VPN I expect a successful connection.

### Actual behavior
When I click "Connect" I receive "Policy Match" error.

**Comment by KennethSchlatter** [comment]
I'm having the same issue. You closed this issue, so did you manage to solve it? If so, how?

**Comment by QuentinMoss** [comment]
@KennethSchlatter tbh i reinstalled Windows 10. I was testing PrivacyBadger out and I think it changed some settings. I don't know enough about windows to debug.

**Comment by Lars-bs** [comment]
Has anyone found a fix for this yet?
