### ISSUE TITLE
Consider using swanctl rather than ipsec

### ISSUE THREAD

**Issue by dguido** [trailofbits/algo#66]
That way, the user charon runs as (or ipsec starter) doesn't need to be able to read the configuration files or secrets.

**Comment by gunph1ld** [comment]
swanctl is enabled by default since 5.4.0. by default in Strongswan 5.4.0, but Ubuntu 16.04 has 5.3.5.

**Comment by gunph1ld** [comment]
Will be implemented after https://github.com/trailofbits/algo/issues/12

**Comment by dguido** [comment]
This will come for free whenever we move off Ubuntu 16.04

**Comment by TC1977** [comment]
Is it time to do this? Would swanctl better help with these connect/reconnect loops and orphaned policies as in #963?
