### ISSUE TITLE
Ubuntu 16.04

### ISSUE THREAD

**Issue by mbettan** [trailofbits/algo#660]
### OS / Environment
Ubuntu 16.04

### Summary of the problem
TASK [common : Install tools] **************************************************
failed: [localhost] (item=[u'git', u'screen', u'apparmor-utils', u'uuid-runtime', u'coreutils', u'sendmail', u'iptables-persistent', u'cgroup-tools', u'openssl']) => {"failed": true, "item": ["git", "screen", "apparmor-utils", "uuid-runtime", "coreutils", "sendmail", "iptables-persistent", "cgroup-tools", "openssl"], "msg": "No package matching 'cgroup-tools' is available"}

### Full log
TASK [common : Install tools] **************************************************
failed: [localhost] (item=[u'git', u'screen', u'apparmor-utils', u'uuid-runtime', u'coreutils', u'sendmail', u'iptables-persistent', u'cgroup-tools', u'openssl']) => {"failed": true, "item": ["git", "screen", "apparmor-utils", "uuid-runtime", "coreutils", "sendmail", "iptables-persistent", "cgroup-tools", "openssl"], "msg": "No package matching 'cgroup-tools' is available"}

TASK [common : debug] **********************************************************
ok: [localhost] => {
    "fail_hint": [
        "Sorry, but something went wrong!", 
        "Please check the troubleshooting guide.", 
        "https://trailofbits.github.io/algo/troubleshooting.html"
    ]
}
TASK [common : fail] ***********************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Failed as
 requested from task"}
PLAY RECAP *********************************************************************
localhost                  : ok=20   changed=5    unreachable=0    failed=1

**Comment by mbettan** [comment]
TASK [vpn : Ubuntu | Enable services] ******************************************
ok: [localhost] => (item=apparmor)
ok: [localhost] => (item=strongswan)
failed: [localhost] (item=netfilter-persistent) => {"failed": true, "item": "netfil
ter-persistent", "msg": "no service or tool found for: netfilter-persistent"}

**Comment by mbettan** [comment]
RUNNING HANDLER [vpn : restart strongswan] *************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "start: Job failed to start\n"}

RUNNING HANDLER [vpn : daemon-reload] ******************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "systemctl daemon-reload", "delta": "0:00:00.001958", "end": "2017-09-05 02:51:59.837780", "failed": true, "rc": 127, "start": "2017-09-05 02:51:59.835822", "stderr": "/bin/sh: 1: systemctl: not found", "stdout": "", "stdout_lines": [], "warnings": []}

RUNNING HANDLER [vpn : restart iptables] ***************************************

PLAY RECAP *********************************************************************
localhost                  : ok=57   changed=34   unreachable=0    failed=1

**Comment by mbettan** [comment]
I tried with ubuntu 16.04 all working fine, I guess 14.04 is not supported?
I found what are the issues in the ipsec.conf file

**Comment by dguido** [comment]
Correct

**Comment by mbettan** [comment]
I suggest to be clarify in the documentation on the supported OS?
