### ISSUE TITLE
Network speed acceleration?

### ISSUE THREAD

**Issue by mbettan** [trailofbits/algo#661]
### OS / Environment
Ubuntu 16.04 / Google Instance East

### Summary of the problem
My Internet connection is 300+ mbits and with the vpn it is something like 100 mbits.
Any chance to increase the network speed?
Thank you

**Comment by dguido** [comment]
Change the instance size before spinning it up

**Comment by mbettan** [comment]
What are the recommandations? 1vCPU, 4 go RAM is not enough?

**Comment by dguido** [comment]
You'll want to run your own tests. Most people aren't pumping 300mbps through Algo on their cell phone.
