### ISSUE TITLE
Algo final installation on Ubuntu 16

### ISSUE THREAD

**Issue by jpzun23** [trailofbits/algo#664]

**Comment by jpzun23** [comment]
when finishing installation i get this error?

TASK [Check the system] *******************************************************************
fatal: [server ip]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: Permanently added 'server ip' (ECDSA) to the list of known hosts.\r\nPermission denied (publickey).\r\n", "unreachable": true}

any help would be greatly appreciative.

**Comment by krisleech** [comment]
Same here, yet I can ssh to my server as the root user.

Using options 5, deploy to existing Ubuntu 16.04 server.

* Server: Ubuntu 16.04 (freshly made, has my ssh public key)
* Desktop: Ubuntu 16.04
* Ansible: 2.3
* Python 2.7

**Comment by krisleech** [comment]
Why closed, error not related to algo?
