### ISSUE TITLE
Here's an easy way to find the "nearest" DO data center for your VPN

### ISSUE THREAD

**Issue by quinncomendant** [trailofbits/algo#665]
TIL DigitalOcean has setup [speedtest servers](http://speedtest-nyc1.digitalocean.com/) for all of its data centers. This makes it easy to find the best location for a VPN in the region you desire, relative to your current location. For example, I'm now traveling in India, and from here, NYC1 has ~ 25 ms shorter latency than SFO1. 

Here's a bash one-liner that prints the average ping times for all 12 locations (takes a few minutes to run):

    for DC in nyc1 nyc2 nyc3 ams2 ams3 sfo1 sfo2 sgp1 lon1 fra1 tor1 blr1; do echo "$DC: $(ping -i .2 -c 75 -q speedtest-$DC.digitalocean.com | awk -F/ '/^round|^rtt/{print $5}')"; done | sort -n -k2

Not sure if there's a place to contribute tips like this, so I'll just leave this here.

**Comment by dguido** [comment]
Thanks! Could you make a PR to the troubleshooting doc? Maybe something like, "How can I choose the fastest DigitalOcean server?" or similar?
