### ISSUE TITLE
Remote Desktop between two systems using VPN Client

### ISSUE THREAD

**Issue by kanwal019** [trailofbits/algo#666]
### OS / Environment

Server deployed on Azure as Ubuntu Server.
Client are two systems running on Windows 10.

### Summary of the problem
I need to connect the two systems connected through the _AlgoVPN_. By default they are assigned the private IPs of the range 10.19.48.0/24(_as defined in the config.cfg_). Hence both of them are on the same network. I tried to use the remote desktop connection from one of the systems using the private IP generated by the VPN, but I wasn't able to connect. The firewall settings are also supportive of the connection. I wasn't able to perform the ping on each of the generated IP addresses.

### Expected behavior
These systems should be able to connect remotely as they are under the same network(_VPN_).

### Actual behavior
The remote desktop connection is unsuccessful and even the PING fails.

**Comment by dguido** [comment]
See config.cfg
