### ISSUE TITLE
Random disconnecting of On Demand profile on macOS with no automatic reconnect

### ISSUE THREAD

**Issue by fortunateLeopard** [trailofbits/algo#667]
### OS / Environment

macOS Sierra 10.12.6
Algo hosted on AWS

### Summary of the problem
Random disconnection of On Demand profile, without attempting to reconnect.

### Steps to reproduce the behavior
Wait an undetermined amount of time or wake after sleep, or unplug and plug in ethernet cable, or ... seems completely random

### Expected behavior
On Demand profile should always try to reconnect after disconnecting.

### Actual behavior
VPN gets disconnected, never tries to reconnect, manual reconnect works. But often I don't notice the VPN was dropped until it's obvious from web traffic (like a different country of Google from my VPN connection).

I have no idea how to troubleshoot this, my apologies if this is the wrong place to post this problem.

**Comment by Manouchehri** [comment]
Yeah, I've experienced this as well. Do you have power nap enabled? Sometimes I get stuck on "Connecting..." after turning the screen back on, and I have to toggle WiFi or wait awhile for connectivity.

**Comment by dguido** [comment]
I can't control the behavior of macOS, sorry! :-(
