### ISSUE TITLE
Make the local resolver configurable

### ISSUE THREAD

**Issue by dguido** [trailofbits/algo#67]
The local resolver does not always have to be 172.16.0.1. We may want to add a dummy device, as well as a private IP to that dummy device where we then dnsmasq and DNAT the DNS traffic to. Then make dnsmasq use the settings from resolv.conf.

Telling dnsmasq to use the resolver at /etc/resolv.conf won't help with the resolver knowing what DNS server to use. The RW should get the "real" IP of the local dnsmasq instance instead of always silently DNATing the queries. Doing it the way way above would allow a server operator to review what clients do not respect the pushed DNS server and which actually do.

**Comment by gunph1ld** [comment]
DNAT disabled also
