### ISSUE TITLE
How to restart algo automatically or manually?

### ISSUE THREAD

**Issue by mbettan** [trailofbits/algo#670]
### OS / Environment
Ubuntu 16.04

### Summary of the problem
What is the process to restart Algo avec reboot please? Any way to configure an automatic restart?
Thank syou

### Steps to reproduce the behavior
Ubuntu 16.04

### The way of deployment (cloud or local)
local

### Expected behavior
Algo restart

### Actual behavior
Algo does not restart

**Comment by dguido** [comment]
It depends on your cloud provider. Login to whoever it is and restart the vm.

**Comment by mbettan** [comment]
LOL... of course

I mean how to restart the algo linux service? After restarting the machine virtual, vpn is not working anymore, I can connect

**Comment by dguido** [comment]
Everything will come back up normally unless you did a custom install and broke something.

**Comment by mbettan** [comment]
Ok, another reboot and it worked again, Thanks

**Comment by NightMachinary** [comment]
I have this problem, too, algo is down after reboot.
