### ISSUE TITLE
Windows 10 Powershell and priv/nonpriv account issues

### ISSUE THREAD

**Issue by sp3nx0r** [trailofbits/algo#672]
### OS / Environment
Windows 10 Home (Version	10.0.15063 Build 15063) - client
Ubuntu 16.04 LTS - installation via AWS EC2

Algo VPN installs successfully, able to connect to it just fine (after adjusting for below issue)

### Summary of the problem
When executing Powershell script to add VPN connection, VPN does not show up for normal non-admin users but does show up for administrator users. 

### Steps to reproduce the behavior
Create two userids, one with and one without local administrator access. Execute the Powershell script to create VPN using local admin and one without local admin. Local admin will create the VPN for just that local admin user (as intended), whereas normal user executing the same PS script will create the VPN connection (shows via Get-VPNConnection cmdlet) but not visible/selectable under Settings->VPN or under Network & Internet settings and thus not usable. 

### The way of deployment (cloud or local)
Cloud

### Expected behavior
Might want to include the parameter for -AllUserConnection in the PS script (or at least the detailed notes) to help troubleshooting this particular issue. Wouldn't be an issue for folks running one userid, but for folks who have split userids (a priv and nonpriv account), this can be an issue they'll run into when just running the stock script.

**Comment by amad3usX** [comment]
+1 to this. Would be great to see an option added to the script. For anyone stuck in the meantime, you can go through the [Manual Installation](https://github.com/trailofbits/algo/blob/master/docs/client-windows.md) process and insert `AllUserConnection = $true` under `$addVpnParams` so it looks like this:

`$addVpnParams = @{
    Name = $VpnName
    ServerAddress = $VpnServerAddress
    TunnelType = "IKEv2"
    AuthenticationMethod = "MachineCertificate"
    EncryptionLevel = "Required"
    AllUserConnection = $true
}`

Once you complete the rest of the installation process, you'll be able to use the VPN as a non-Admin user.

**Comment by TC1977** [comment]
The fix in #1093 is actually the one documented here by @amad3usX. All credit to you.
