### ISSUE TITLE
Feature Request: Support VMWare ESXi as a Cloud Provider

### ISSUE THREAD

**Issue by jaredledvina** [trailofbits/algo#673]
### Summary of the problem
I'd like to be able to deploy an Algo box on top of an existing VMWare ESXi host. Many hosting providers allow you to rent a dedicated host running VMWare ESXi. I reviewed the Ansible Cloud providers and I think Algo can support ESXi as a cloud provider using the native modules:
http://docs.ansible.com/ansible/latest/list_of_cloud_modules.html#vmware

Specifically, looks like the following, at least, will work/be needed:
http://docs.ansible.com/ansible/latest/vsphere_copy_module.html # To get an Ubuntu ISO on the host(?)
http://docs.ansible.com/ansible/latest/vsphere_guest_module.html # To launch the instance

**Comment by unstatusthequo** [comment]
Why not just setup a VM Ubuntu instance on ESXi and install it there? I have my Algo server under XenServer and it works great. Also very easy to redeploy with snapshots if things so sideways for whatever reason.

**Comment by jaredledvina** [comment]
@unstatusthequo - Yeah, that works, I filed this since it looks like Ansible will provide the necessary modules to directly launch the VM and then provision it as well.

**Comment by Mrdindon** [comment]
Thats also what I did, (running a ubuntu vm on esx) but I'm still unable to make it to work with a dns name instead of a public ip... I'm using IOS mobile profiles... could you figure out something for people with dynamic ip ? 
Thanks !

**Comment by Mrdindon** [comment]
I'm just wondering if it is possible somehow to install it behind some nat setup ?
I've setup my domain to point to my router and then made the appropriate port forwarding rules. but running the setup fails...
