### ISSUE TITLE
 StrongSwan IKEv2 VPN with PSK?

### ISSUE THREAD

**Issue by viniciusmo** [trailofbits/algo#675]
I'm looking for a configuration instructions for IKEv2 VPN that uses pre-shared keys instead of certs.

My question is what needs to be changed so that it would use PSK instead? I'd assume changes in /etc/ipsec.secrets and /etc/ipsec.conf are to be made.

ipsec.conf

```
config setup
    uniqueids=never # allow multiple connections per user
    charondebug="ike 2, knl 2, cfg 2, net 2, esp 2, dmn 2,  mgr 2"
conn %default
    fragmentation=yes
    rekey=no
    dpdaction=clear
    keyexchange=ikev2
    compress=yes
    dpddelay=35s
    ike=aes128gcm16-prfsha512-ecp256!
    esp=aes128gcm16-ecp256!
    left=%any
    leftauth=pubkey
    leftid=<server_ip>
    leftcert=<server_ip>.crt
    leftsendcert=always
    leftsubnet=0.0.0.0/0,::/0
    right=%any
    rightauth=pubkey
    rightsourceip=10.19.48.0/24,fd9d:bc11:4020::/48
    rightdns=8.8.8.8,8.8.4.4
conn ikev2-pubkey
    auto=add

```
ipsec.secrets

`: ECDSA <server_ip>.key`

**Comment by dguido** [comment]
We don't support PSK for security reasons. You should check the StrongSwan docs if you want to change from certificates to PSK.
