### ISSUE TITLE
“DoError: Region is not available” (when using DO’s nyc2)

### ISSUE THREAD

**Issue by quinncomendant** [trailofbits/algo#677]
### OS / Environment
macOS 10.12.6

### Ansible version
    ansible 2.2.0.0
      config file = /Users/q/src/algo/ansible.cfg
      configured module search path = Default w/o overrides

### Version of components from `requirements.txt`
    Name: msrestazure
    Version: 0.4.7
    Summary: AutoRest swagger generator Python client runtime. Azure-specific module.
    Home-page: https://github.com/Azure/msrestazure-for-python
    Author: Microsoft Corporation
    Author-email: UNKNOWN
    License: MIT License
    Location: /Users/q/src/algo/env/lib/python2.7/site-packages
    Requires: keyring, adal, msrest
    ---
    Name: boto3
    Version: 1.4.4
    Summary: The AWS SDK for Python
    Home-page: https://github.com/boto/boto3
    Author: Amazon Web Services
    Author-email: UNKNOWN
    License: Apache License 2.0
    Location: /Users/q/src/algo/env/lib/python2.7/site-packages
    Requires: jmespath, s3transfer, botocore
    ---
    Name: apache-libcloud
    Version: 2.0.0
    Summary: A standard Python library that abstracts away differences among multiple cloud provider APIs. For more information and documentation, please see http://libcloud.apache.org
    Home-page: http://libcloud.apache.org/
    Author: Apache Software Foundation
    Author-email: dev@libcloud.apache.org
    License: Apache License (2.0)
    Location: /Users/q/src/algo/env/lib/python2.7/site-packages
    Requires: requests
    ---
    Name: six
    Version: 1.10.0
    Summary: Python 2 and 3 compatibility utilities
    Home-page: http://pypi.python.org/pypi/six/
    Author: Benjamin Peterson
    Author-email: benjamin@python.org
    License: MIT
    Location: /Users/q/src/algo/env/lib/python2.7/site-packages
    Requires:
    ---
    Name: pyOpenSSL
    Version: 17.0.0
    Summary: Python wrapper module around the OpenSSL library
    Home-page: https://pyopenssl.readthedocs.io/
    Author: Hynek Schlawack
    Author-email: hs@ox.cx
    License: Apache License, Version 2.0
    Location: /Users/q/src/algo/env/lib/python2.7/site-packages
    Requires: six, cryptography

### Summary of the problem

I'm unable to create a VPN in DigitalOcean region nyc2. The error message is: `DoError: Region is not available`. I wonder if it is related to [this issue](https://github.com/digitalocean/godo/issues/37)?

### Steps to reproduce the behavior

This happens consistently if I select nyc2 as the region when setting up a new VPN. I'm able to successfully create VPNs in other regions (e.g., nyc1).

### The way of deployment (cloud or local)

I'm running `./algo` locally from my MBP (while connected to another Algo VPN in the nyc1 DC). 

### Expected behavior

A VPN should be setup successfully. Why does nyc2 think it's special?

### Actual behavior

Fail.

### Full log

    [q@x algo] ./algo

      What provider would you like to use?
        1. DigitalOcean
        2. Amazon EC2
        3. Microsoft Azure
        4. Google Compute Engine
        5. Install to existing Ubuntu 16.04 server

    Enter the number of your desired provider
    : 1

    Enter your API token. The token must have read and write permissions (https://cloud.digitalocean.com/settings/api/tokens):
    [pasted values will not be displayed]
    :

    Name the vpn server:
    [algo.local]: algo-nyc2

      What region should the server be located in?
        1.  Amsterdam        (Datacenter 2)
        2.  Amsterdam        (Datacenter 3)
        3.  Frankfurt
        4.  London
        5.  New York         (Datacenter 1)
        6.  New York         (Datacenter 2)
        7.  New York         (Datacenter 3)
        8.  San Francisco    (Datacenter 1)
        9.  San Francisco    (Datacenter 2)
        10. Singapore
        11. Toronto
        12. Bangalore
    Enter the number of your desired region:
    [7]: 6

    Do you want macOS/iOS clients to enable "VPN On Demand" when connected to cellular networks?
    [y/N]: y

    Do you want macOS/iOS clients to enable "VPN On Demand" when connected to Wi-Fi?
    [y/N]: y

    List the names of trusted Wi-Fi networks (if any) that macOS/iOS clients exclude from using the VPN (e.g., your home network. Comma-separated value, e.g., HomeNet,OfficeWifi,AlgoWiFi)
    :

    Do you want to install a DNS resolver on this VPN server, to block ads while surfing?
    [y/N]:

    Do you want each user to have their own account for SSH tunneling?
    [y/N]:

    Do you want to apply operating system security enhancements on the server? (warning: replaces your sshd_config)
    [y/N]: y

    Do you want the VPN to support Windows 10 or Linux Desktop clients? (enables compatible ciphers and key exchange, less secure)
    [y/N]:

    Do you want to retain the CA key? (required to add users in the future, but less secure)
    [y/N]:

    PLAY [Configure the server] ****************************************************

    TASK [setup] *******************************************************************
    ok: [localhost]

    TASK [Generate the SSH private key] ********************************************
    ok: [localhost]

    TASK [Generate the SSH public key] *********************************************
    ok: [localhost]

    TASK [Change mode for the SSH private key] *************************************
    ok: [localhost]

    TASK [Ensure the dynamic inventory exists] *************************************
    ok: [localhost]

    TASK [cloud-digitalocean : Set the DigitalOcean Access Token fact] *************
    ok: [localhost]

    TASK [cloud-digitalocean : Delete the existing Algo SSH keys] ******************
    FAILED - RETRYING: TASK: cloud-digitalocean : Delete the existing Algo SSH keys (10 retries left).
    ok: [localhost]

    TASK [cloud-digitalocean : Upload the SSH key] *********************************
    changed: [localhost]

    TASK [cloud-digitalocean : Creating a droplet...] ******************************
    An exception occurred during task execution. To see the full traceback, use -vvv. The error was: DoError: Region is not available
    fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Region is not available"}

    TASK [cloud-digitalocean : debug] **********************************************
    ok: [localhost] => {
        "fail_hint": [
            "Sorry, but something went wrong!",
            "Please check the troubleshooting guide.",
            "https://trailofbits.github.io/algo/troubleshooting.html"
        ]
    }

    TASK [cloud-digitalocean : fail] ***********************************************
    fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Failed as requested from task"}

    PLAY RECAP *********************************************************************
    localhost                  : ok=9    changed=1    unreachable=0    failed=1

**Comment by davidemyers** [comment]
I think I saw somewhere that NYC2 is basically full, but I don't recall where I saw it.

**Comment by haraldkoch** [comment]
On the create a droplet page, when you hover over ther grayed-out NYC2:

"Due to limited availability we have temporarily disabled droplet creation in this region."

You answer your bug report - NYC2 does think it's special. :)

**Comment by quinncomendant** [comment]
Nice find! I see that too. It looks like this:

<img width="456" alt="screen shot 2017-09-21 at 14 14 56" src="https://user-images.githubusercontent.com/6884276/30686927-56e797a2-9ed7-11e7-97d9-b296f8940150.png">

But nothing is mentioned on their [status page](https://status.digitalocean.com/), where I did go check. ¯\\\_(ツ)_/¯

It might be worth printing a note when this error occurs inside `./algo` that explains what's up. (And maybe a link to this ticket?) 

This info should probably also be added to [the algo troubleshooting page](https://trailofbits.github.io/algo/troubleshooting.html).
