### ISSUE TITLE
Installations hangs when deploying from Ubuntu

### ISSUE THREAD

**Issue by dewang** [trailofbits/algo#678]
### OS / Environment

Ubuntu 17.04

### Ansible version

Not using ansible (pip list show 2.2.0.0)

### Version of components from `requirements.txt`
msrestazure (0.4.14)
setuptools (36.5.0)
ansible (2.2.0.0)
dopy (0.3.5)
boto (2.48.0)
boto3 (1.4.7)
azure (2.0.0rc5)
msrest (0.4.1)
apache-libcloud (2.2.0)
six (1.11.0)
pyOpenSSL (17.3.0)
Jinja2 (2.8)

### Summary of the problem
I run ./algo and answer the questions. The script just hangs on "TASK [setup]" and does not proceed further

### Steps to reproduce the behavior
Rune algo with answers as shown below
./algo

  What provider would you like to use?
    1. DigitalOcean
    2. Amazon EC2
    3. Microsoft Azure
    4. Google Compute Engine
    5. Install to existing Ubuntu 16.04 server

Enter the number of your desired provider
: 2

Enter your aws_access_key (http://docs.aws.amazon.com/general/latest/gr/managing-aws-access-keys.html)
Note: Make sure to use an IAM user with an acceptable policy attached (see https://github.com/trailofbits/algo/blob/master/docs/deploy-from-ansible.md).
[pasted values will not be displayed]
[AKIA...]: 

Enter your aws_secret_key (http://docs.aws.amazon.com/general/latest/gr/managing-aws-access-keys.html)
[pasted values will not be displayed]
[ABCD...]: 

Name the vpn server:
[algo]: algo-vpn

  What region should the server be located in?
    1.   us-east-1           US East (N. Virginia)
    2.   us-east-2           US East (Ohio)
    3.   us-west-1           US West (N. California)
    4.   us-west-2           US West (Oregon)
    5.   ap-south-1          Asia Pacific (Mumbai)
    6.   ap-northeast-2      Asia Pacific (Seoul)
    7.   ap-southeast-1      Asia Pacific (Singapore)
    8.   ap-southeast-2      Asia Pacific (Sydney)
    9.   ap-northeast-1      Asia Pacific (Tokyo)
    10.  eu-central-1        EU (Frankfurt)
    11.  eu-west-1           EU (Ireland)
    12.  eu-west-2           EU (London)
    13.  ca-central-1        Canada (Central)
    14.  sa-east-1           São Paulo
Enter the number of your desired region:
[1]: 11

Do you want macOS/iOS clients to enable "VPN On Demand" when connected to cellular networks?
[y/N]: 

Do you want macOS/iOS clients to enable "VPN On Demand" when connected to Wi-Fi?
[y/N]: 

Do you want to install a DNS resolver on this VPN server, to block ads while surfing?
[y/N]: 

Do you want each user to have their own account for SSH tunneling?
[y/N]: y

Do you want to apply operating system security enhancements on the server? (warning: replaces your sshd_config)
[y/N]: 

Do you want the VPN to support Windows 10 or Linux Desktop clients? (enables compatible ciphers and key exchange, less secure)
[y/N]: y

Do you want to retain the CA key? (required to add users in the future, but less secure)
[y/N]: y

### The way of deployment (cloud or local)
Cloud

### Expected behavior
VPN server should be set up

### Actual behavior
Script hangs at this output

PLAY [Configure the server] ****************************************************

TASK [setup] *******************************************************************

Even after leaving it for about an hour there is no progress

**Comment by dewang** [comment]
Quick update - tried to deploy to Digital Ocean and the same problem comes up

**Comment by dguido** [comment]
This happens sometimes when the connection between you and the data center is very slow. I've had it happen when I try to run a deploy over cellular, for instance.

**Comment by dewang** [comment]
This was over WiFi at work, and I was able to do other operations on AWS (via the cli). I have tried it on two separate occasions and there is no progress indication or error message.

**Comment by tjwebb** [comment]
I am also running into this. exact same behavior, same OS, on GCP. except it hangs on 
```
PLAY [Configure the server and install required software] ***********************************
```

My internet connection is very fast.
