### ISSUE TITLE
Local Deployment Failed

### ISSUE THREAD

**Issue by adamluk** [trailofbits/algo#681]
### OS / Environment
Ubuntu 16.04 KVM VPS - attempting local deployment

### Ansible version
ansible_2.4.0.0-1

### Summary of the problem

I am following the install instructions at: https://github.com/trailofbits/algo/blob/master/docs/deploy-to-ubuntu.md

### Steps to reproduce the behavior

sudo apt-get install software-properties-common && sudo apt-add-repository ppa:ansible/ansible
sudo apt-get update && sudo apt-get install ansible
git clone https://github.com/trailofbits/algo
cd algo && ./algo
**/root/algo/env/bin/activate not found.  Did you follow documentation to install dependencies?**

### The way of deployment (cloud or local)

local

Please can someone help?

**Comment by adamluk** [comment]
I managed to make a little headway, but the install fails with this:

TASK [vpn : Build the client's pair] *******************************************
ok: [localhost -> localhost] => (item=vpnuser)
failed: [localhost -> localhost] (item=None) => {"changed": true, "cmd": "openssl req -utf8 -new -newkey ec:ecparams/prime256v1.pem -config openssl.cnf -keyout private/.key -out reqs/.req -nodes -passin pass:\"a8054379dd1b064e4ef98d6c20c6a4a4\" -subj \"/CN=\" -batch && openssl ca -utf8 -in reqs/.req -out certs/.crt -config openssl.cnf -days 3650 -batch -passin pass:\"a8054379dd1b064e4ef98d6c20c6a4a4\" -subj \"/CN=\" && touch certs/_crt_generated", "delta": "0:00:00.005096", "end": "2017-09-21 21:24:39.362938", "failed": true, "item": null, "msg": "non-zero return code", "rc": 1, "start": "2017-09-21 21:24:39.357842", "stderr": "Generating a 256 bit EC private key\nwriting new private key to 'private/.key'\n-----\nend of string encountered while processing type of subject name element #0\nproblems making Certificate Request", "stderr_lines": ["Generating a 256 bit EC private key", "writing new private key to 'private/.key'", "-----", "end of string encountered while processing type of subject name element #0", "problems making Certificate Request"], "stdout": "", "stdout_lines": []}

TASK [vpn : debug] *************************************************************
ok: [localhost] => {
    "fail_hint": [
        "Sorry, but something went wrong!", 
        "Please check the troubleshooting guide.", 
        "https://trailofbits.github.io/algo/troubleshooting.html"
    ]
}

**Comment by dguido** [comment]
Please install the prereqs as indicated by the documentation.
