### ISSUE TITLE
The TASK [vpn : Build the CA pair] fails on AWS/EC2/Ubuntu 16.04?

### ISSUE THREAD

**Issue by onekiloparsec** [trailofbits/algo#684]
### OS / Environment

macOS 10.13 high sierra

### Ansible version

ansible 2.2.0.0

### Version of components from `requirements.txt`

Name: msrestazure
Version: 0.4.14
Summary: AutoRest swagger generator Python client runtime. Azure-specific module.
Home-page: https://github.com/Azure/msrestazure-for-python
Author: Microsoft Corporation
Author-email: UNKNOWN
License: MIT License
Location: /Users/onekiloparsec/Downloads/algo-master/env/lib/python2.7/site-packages
Requires: adal, keyring, msrest

Name: setuptools
Version: 36.5.0
Summary: Easily download, build, install, upgrade, and uninstall Python packages
Home-page: https://github.com/pypa/setuptools
Author: Python Packaging Authority
Author-email: distutils-sig@python.org
License: UNKNOWN
Location: /Users/onekiloparsec/Downloads/algo-master/env/lib/python2.7/site-packages
Requires: 

Name: ansible
Version: 2.2.0.0
Summary: Radically simple IT automation
Home-page: http://ansible.com/
Author: Ansible, Inc.
Author-email: info@ansible.com
License: GPLv3
Location: /Users/onekiloparsec/Downloads/algo-master/env/lib/python2.7/site-packages
Requires: pycrypto, paramiko, jinja2, setuptools, PyYAML

Name: dopy
Version: 0.3.5
Summary: Python client for the Digital Ocean API
Home-page: https://github.com/devo-ps/dopy
Author: Vincent Viallet
Author-email: vincent@devo.ps
License: The MIT License (MIT)
Location: /Users/onekiloparsec/Downloads/algo-master/env/lib/python2.7/site-packages
Requires: requests

Name: boto
Version: 2.48.0
Summary: Amazon Web Services Library
Home-page: https://github.com/boto/boto/
Author: Mitch Garnaat
Author-email: mitch@garnaat.com
License: MIT
Location: /Users/onekiloparsec/Downloads/algo-master/env/lib/python2.7/site-packages
Requires: 

Name: boto3
Version: 1.4.7
Summary: The AWS SDK for Python
Home-page: https://github.com/boto/boto3
Author: Amazon Web Services
Author-email: UNKNOWN
License: Apache License 2.0
Location: /Users/onekiloparsec/Downloads/algo-master/env/lib/python2.7/site-packages
Requires: s3transfer, jmespath, botocore

Name: azure
Version: 2.0.0rc5
Summary: Microsoft Azure Client Libraries for Python
Home-page: https://github.com/Azure/azure-sdk-for-python
Author: Microsoft Corporation
Author-email: ptvshelp@microsoft.com
License: MIT License
Location: /Users/onekiloparsec/Downloads/algo-master/env/lib/python2.7/site-packages
Requires: azure-storage, azure-mgmt, azure-servicebus, azure-servicemanagement-legacy, azure-batch, azure-graphrbac

Name: msrest
Version: 0.4.1
Summary: AutoRest swagger generator Python client runtime.
Home-page: https://github.com/xingwu1/autorest/tree/python/ClientRuntimes/Python/msrest
Author: Microsoft Corporation
Author-email: UNKNOWN
License: MIT License
Location: /Users/onekiloparsec/Downloads/algo-master/env/lib/python2.7/site-packages
Requires: chardet, certifi, enum34, keyring, isodate, requests, requests-oauthlib

Name: six
Version: 1.11.0
Summary: Python 2 and 3 compatibility utilities
Home-page: http://pypi.python.org/pypi/six/
Author: Benjamin Peterson
Author-email: benjamin@python.org
License: MIT
Location: /Users/onekiloparsec/Downloads/algo-master/env/lib/python2.7/site-packages
Requires: 

Name: pyOpenSSL
Version: 17.3.0
Summary: Python wrapper module around the OpenSSL library
Home-page: https://pyopenssl.org/
Author: Hynek Schlawack
Author-email: hs@ox.cx
License: Apache License, Version 2.0
Location: /Users/onekiloparsec/Downloads/algo-master/env/lib/python2.7/site-packages
Requires: six, cryptography

Name: Jinja2
Version: 2.8
Summary: A small but fast and easy to use stand-alone template engine written in pure python.
Home-page: http://jinja.pocoo.org/
Author: Armin Ronacher
Author-email: armin.ronacher@active-4.com
License: BSD
Location: /Users/onekiloparsec/Downloads/algo-master/env/lib/python2.7/site-packages
Requires: MarkupSafe

### Summary of the problem
The TASK [vpn : Build the CA pair] fails

### Steps to reproduce the behavior
- setup AWS IAM user with copy-pasted IAM permissions from https://github.com/trailofbits/algo/blob/master/docs/deploy-from-ansible.md
- run ./algo and answer the questions...
- at some point, I get:

`TASK [vpn : Build the CA pair] *************************************************
fatal: [18.194.145.132 -> localhost]: FAILED! => {"changed": true, "cmd": "openssl ecparam -name prime256v1 -out ecparams/prime256v1.pem && openssl req -utf8 -new -newkey ec:ecparams/prime256v1.pem -config openssl.cnf -keyout private/cakey.pem -out cacert.pem -x509 -days 3650 -batch -passout pass:\"6b11e5a0aa518fa1222227f291572291\" && touch 18.194.145.132_ca_generated", "delta": "0:00:00.021897", "end": "2017-09-25 15:33:00.015107", "failed": true, "rc": 1, "start": "2017-09-25 15:32:59.993210", "stderr": "error on line 113 of openssl.cnf\n140735587025800:error:0E065068:configuration file routines:STR_COPY:variable has no value:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22/libressl/crypto/conf/conf_def.c:573:line 113", "stdout": "", "stdout_lines": [], "warnings": []}
`

### The way of deployment (cloud or local)
cloud

### Expected behavior
I expected a successful deployment.

### Actual behavior
The deployment fails.

### Full log

  What provider would you like to use?
    1. DigitalOcean
    2. Amazon EC2
    3. Microsoft Azure
    4. Google Compute Engine
    5. Install to existing Ubuntu 16.04 server

Enter the number of your desired provider
: 2

Enter your aws_access_key (http://docs.aws.amazon.com/general/latest/gr/managing-aws-access-keys.html)
Note: Make sure to use an IAM user with an acceptable policy attached (see https://github.com/trailofbits/algo/blob/master/docs/deploy-from-ansible.md).
[pasted values will not be displayed]
[AKIA...]: 

Enter your aws_secret_key (http://docs.aws.amazon.com/general/latest/gr/managing-aws-access-keys.html)
[pasted values will not be displayed]
[ABCD...]: 

Name the vpn server:
[algo]: 

  What region should the server be located in?
    1.   us-east-1           US East (N. Virginia)
    2.   us-east-2           US East (Ohio)
    3.   us-west-1           US West (N. California)
    4.   us-west-2           US West (Oregon)
    5.   ap-south-1          Asia Pacific (Mumbai)
    6.   ap-northeast-2      Asia Pacific (Seoul)
    7.   ap-southeast-1      Asia Pacific (Singapore)
    8.   ap-southeast-2      Asia Pacific (Sydney)
    9.   ap-northeast-1      Asia Pacific (Tokyo)
    10.  eu-central-1        EU (Frankfurt)
    11.  eu-west-1           EU (Ireland)
    12.  eu-west-2           EU (London)
    13.  ca-central-1        Canada (Central)
    14.  sa-east-1           São Paulo
Enter the number of your desired region:
[1]: 10

Do you want macOS/iOS clients to enable "VPN On Demand" when connected to cellular networks?
[y/N]: 

Do you want macOS/iOS clients to enable "VPN On Demand" when connected to Wi-Fi?
[y/N]: 

Do you want to install a DNS resolver on this VPN server, to block ads while surfing?
[y/N]: 

Do you want each user to have their own account for SSH tunneling?
[y/N]: 

Do you want to apply operating system security enhancements on the server? (warning: replaces your sshd_config)
[y/N]: 

Do you want the VPN to support Windows 10 or Linux Desktop clients? (enables compatible ciphers and key exchange, less secure)
[y/N]: 

Do you want to retain the CA key? (required to add users in the future, but less secure)
[y/N]: 

PLAY [Configure the server] ****************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Generate the SSH private key] ********************************************
ok: [localhost]

TASK [Generate the SSH public key] *********************************************
ok: [localhost]

TASK [Change mode for the SSH private key] *************************************
ok: [localhost]

TASK [Ensure the dynamic inventory exists] *************************************
ok: [localhost]

TASK [cloud-ec2 : set_fact] ****************************************************
ok: [localhost]

TASK [cloud-ec2 : Locate official AMI for region] ******************************
ok: [localhost]

TASK [cloud-ec2 : set_fact] ****************************************************
ok: [localhost]

TASK [cloud-ec2 : Make a cloudformation template] ******************************
ok: [localhost]

TASK [cloud-ec2 : Deploy the template] *****************************************
ok: [localhost]

TASK [cloud-ec2 : Add new instance to host group] ******************************
changed: [localhost]

TASK [cloud-ec2 : set_fact] ****************************************************
ok: [localhost]

TASK [cloud-ec2 : Get EC2 instances] *******************************************
ok: [localhost]

TASK [cloud-ec2 : Ensure the group ec2 exists in the dynamic inventory file] ***
ok: [localhost]

TASK [cloud-ec2 : Populate the dynamic inventory] ******************************
ok: [localhost] => (item={u'kernel': None, u'instance_profile': None, u'root_device_type': u'ebs', u'private_dns_name': u'ip-172-16-254-194.eu-central-1.compute.internal', u'spot_instance_request_id': None, u'source_destination_check': u'true', u'id': u'i-0ffeea42621989e1d', u'ebs_optimized': False, u'state': u'running', u'client_token': u'algo-EC2Ins-18AH4AP9RWBLI', u'virtualization_type': u'hvm', u'ramdisk': None, u'public_ip_address': u'18.194.145.132', u'block_device_mapping': [{u'status': u'attached', u'volume_id': u'vol-0ae6d3686b44f7759', u'delete_on_termination': True, u'attach_time': u'2017-09-25T13:14:19.000Z', u'device_name': u'/dev/sda1'}], u'key_name': None, u'interfaces': [{u'id': u'eni-dc6396bd', u'mac_address': u'02:bd:14:39:d7:8d'}], u'image_id': u'ami-5a922335', u'groups': [{u'id': u'sg-4752af2d', u'name': u'algo-InstanceSecurityGroup-ACVP8BLY00LL'}], u'public_dns_name': u'ec2-18-194-145-132.eu-central-1.compute.amazonaws.com', u'requester_id': None, u'tags': {u'Environment': u'Algo', u'aws:cloudformation:stack-name': u'algo', u'Name': u'Algo', u'aws:cloudformation:stack-id': u'arn:aws:cloudformation:eu-central-1:184095970184:stack/algo/3f7952d0-a1f3-11e7-81ef-500c44f622fe', u'aws:cloudformation:logical-id': u'EC2Instance'}, u'monitoring_state': u'disabled', u'placement': {u'tenancy': u'default', u'zone': u'eu-central-1a'}, u'ami_launch_index': u'0', u'hypervisor': u'xen', u'region': u'eu-central-1', u'launch_time': u'2017-09-25T13:14:19.000Z', u'persistent': False, u'architecture': u'x86_64', u'private_ip_address': u'172.16.254.194', u'vpc_id': u'vpc-65cdf90d'})

TASK [Wait until SSH becomes ready...] *****************************************
ok: [localhost]

TASK [A short pause, in order to be sure the instance is ready] ****************
Pausing for 20 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)
ok: [localhost]

TASK [Ensure the local ssh directory is exist] *********************************
ok: [localhost]

TASK [Copy the algo ssh key to the local ssh directory] ************************
ok: [localhost]

PLAY [Configure the server and install required software] **********************

TASK [Check the system] ********************************************************
changed: [18.194.145.132]

TASK [Ubuntu | Install prerequisites] ******************************************
changed: [18.194.145.132]

TASK [Ubuntu | Configure defaults] *********************************************
changed: [18.194.145.132]

TASK [FreeBSD / HardenedBSD | Install prerequisites] ***************************
skipping: [18.194.145.132]

TASK [FreeBSD / HardenedBSD | Configure defaults] ******************************
skipping: [18.194.145.132]

TASK [set_fact] ****************************************************************
skipping: [18.194.145.132]

TASK [Gather Facts] ************************************************************
ok: [18.194.145.132]

TASK [Ensure the algo ssh key exist on the server] *****************************
ok: [18.194.145.132]

TASK [Enable IPv6] *************************************************************
ok: [18.194.145.132]

TASK [Set facts if the deployment in a cloud] **********************************
ok: [18.194.145.132]

TASK [Generate password for the CA key] ****************************************
changed: [18.194.145.132 -> localhost]

TASK [Generate p12 export password] ********************************************
changed: [18.194.145.132 -> localhost]

TASK [Define password facts] ***************************************************
ok: [18.194.145.132]

TASK [Define the commonName] ***************************************************
ok: [18.194.145.132]

TASK [common : Install software updates] ***************************************
ok: [18.194.145.132]

TASK [common : Check if reboot is required] ************************************
changed: [18.194.145.132]

TASK [common : Reboot] *********************************************************
skipping: [18.194.145.132]

TASK [common : Wait until SSH becomes ready...] ********************************
skipping: [18.194.145.132]

TASK [common : Disable MOTD on login and SSHD] *********************************
ok: [18.194.145.132] => (item={u'regexp': u'^session.*optional.*pam_motd.so.*', u'line': u'# MOTD DISABLED', u'file': u'/etc/pam.d/login'})
ok: [18.194.145.132] => (item={u'regexp': u'^session.*optional.*pam_motd.so.*', u'line': u'# MOTD DISABLED', u'file': u'/etc/pam.d/sshd'})

TASK [common : Loopback for services configured] *******************************
ok: [18.194.145.132]

TASK [common : Loopback included into the network config] **********************
ok: [18.194.145.132]

TASK [common : set_fact] *******************************************************
ok: [18.194.145.132]

TASK [common : set_fact] *******************************************************
skipping: [18.194.145.132]

TASK [common : Loopback included into the rc config] ***************************
skipping: [18.194.145.132]

TASK [common : Enable the gateway features] ************************************
skipping: [18.194.145.132] => (item={u'value': u'"YES"', u'param': u'firewall_enable'}) 
skipping: [18.194.145.132] => (item={u'value': u'"open"', u'param': u'firewall_type'}) 
skipping: [18.194.145.132] => (item={u'value': u'"YES"', u'param': u'gateway_enable'}) 
skipping: [18.194.145.132] => (item={u'value': u'"YES"', u'param': u'natd_enable'}) 
skipping: [18.194.145.132] => (item={u'value': u'""', u'param': u'natd_interface'}) 
skipping: [18.194.145.132] => (item={u'value': u'"-dynamic -m"', u'param': u'natd_flags'}) 

TASK [common : Install tools] **************************************************
ok: [18.194.145.132] => (item=[u'git', u'screen', u'apparmor-utils', u'uuid-runtime', u'coreutils', u'sendmail', u'iptables-persistent', u'cgroup-tools', u'openssl'])

TASK [common : Sysctl tuning] **************************************************
ok: [18.194.145.132] => (item={u'item': u'net.ipv4.ip_forward', u'value': 1})
ok: [18.194.145.132] => (item={u'item': u'net.ipv4.conf.all.forwarding', u'value': 1})
ok: [18.194.145.132] => (item={u'item': u'net.ipv6.conf.all.forwarding', u'value': 1})

TASK [vpn : Ensure that the strongswan group exist] ****************************
ok: [18.194.145.132]

TASK [vpn : Ensure that the strongswan user exist] *****************************
ok: [18.194.145.132]

TASK [vpn : set_fact] **********************************************************
ok: [18.194.145.132]

TASK [vpn : Ubuntu | Install strongSwan] ***************************************
changed: [18.194.145.132]

TASK [vpn : Ubuntu | Enforcing ipsec with apparmor] ****************************
skipping: [18.194.145.132] => (item=/usr/lib/ipsec/charon) 
skipping: [18.194.145.132] => (item=/usr/lib/ipsec/lookip) 
skipping: [18.194.145.132] => (item=/usr/lib/ipsec/stroke) 

TASK [vpn : Ubuntu | Enable services] ******************************************
ok: [18.194.145.132] => (item=apparmor)
ok: [18.194.145.132] => (item=strongswan)
ok: [18.194.145.132] => (item=netfilter-persistent)

TASK [vpn : Ubuntu | Ensure that the strongswan service directory exist] *******
ok: [18.194.145.132]

TASK [vpn : Ubuntu | Setup the cgroup limitations for the ipsec daemon] ********
ok: [18.194.145.132]

TASK [vpn : Iptables configured] ***********************************************
ok: [18.194.145.132] => (item={u'dest': u'/etc/iptables/rules.v4', u'src': u'rules.v4.j2'})

TASK [vpn : Iptables configured] ***********************************************
ok: [18.194.145.132] => (item={u'dest': u'/etc/iptables/rules.v6', u'src': u'rules.v6.j2'})

TASK [vpn : FreeBSD / HardenedBSD | Get the existing kernel parameters] ********
skipping: [18.194.145.132]

TASK [vpn : FreeBSD / HardenedBSD | Set the rebuild_needed fact] ***************
skipping: [18.194.145.132] => (item=IPSEC) 
skipping: [18.194.145.132] => (item=IPSEC_NAT_T) 
skipping: [18.194.145.132] => (item=crypto) 

TASK [vpn : FreeBSD / HardenedBSD | Make the kernel config] ********************
skipping: [18.194.145.132]

TASK [vpn : FreeBSD / HardenedBSD | Ensure the all options are enabled] ********
skipping: [18.194.145.132] => (item=options	IPSEC) 
skipping: [18.194.145.132] => (item=options IPSEC_NAT_T) 
skipping: [18.194.145.132] => (item=device	crypto) 

TASK [vpn : HardenedBSD | Determine the sources] *******************************
skipping: [18.194.145.132]

TASK [vpn : FreeBSD | Determine the sources] ***********************************
skipping: [18.194.145.132]

TASK [vpn : FreeBSD / HardenedBSD | Increase the git postBuffer size] **********
skipping: [18.194.145.132]

TASK [vpn : FreeBSD / HardenedBSD | Fetching the sources...] *******************
skipping: [18.194.145.132]

TASK [vpn : FreeBSD / HardenedBSD | Fetching the sources...] *******************
skipping: [18.194.145.132]

TASK [vpn : FreeBSD / HardenedBSD | The kernel is being built...] **************
skipping: [18.194.145.132]

TASK [vpn : FreeBSD / HardenedBSD | The kernel is being built...] **************
skipping: [18.194.145.132]

TASK [vpn : FreeBSD / HardenedBSD | Reboot] ************************************
skipping: [18.194.145.132]

TASK [vpn : FreeBSD / HardenedBSD | Enable strongswan] *************************
skipping: [18.194.145.132]

TASK [vpn : Install strongSwan] ************************************************
ok: [18.194.145.132]

TASK [vpn : Setup the config files from our templates] *************************
ok: [18.194.145.132] => (item={u'dest': u'/etc/strongswan.conf', u'src': u'strongswan.conf.j2', u'group': u'root', u'mode': u'0644', u'owner': u'root'})
changed: [18.194.145.132] => (item={u'dest': u'/etc/ipsec.conf', u'src': u'ipsec.conf.j2', u'group': u'root', u'mode': u'0644', u'owner': u'root'})
ok: [18.194.145.132] => (item={u'dest': u'/etc/ipsec.secrets', u'src': u'ipsec.secrets.j2', u'group': u'root', u'mode': u'0600', u'owner': u'strongswan'})

TASK [vpn : Get loaded plugins] ************************************************
changed: [18.194.145.132]

TASK [vpn : Disable unneeded plugins] ******************************************
skipping: [18.194.145.132] => (item=hmac) 
ok: [18.194.145.132] => (item=test-vectors)
skipping: [18.194.145.132] => (item=kernel-netlink) 
ok: [18.194.145.132] => (item=sshkey)
ok: [18.194.145.132] => (item=updown)
skipping: [18.194.145.132] => (item=x509) 
skipping: [18.194.145.132] => (item=pem) 
ok: [18.194.145.132] => (item=attr)
ok: [18.194.145.132] => (item=fips-prf)
skipping: [18.194.145.132] => (item=sha2) 
skipping: [18.194.145.132] => (item=random) 
ok: [18.194.145.132] => (item=connmark)
skipping: [18.194.145.132] => (item=pkcs8) 
ok: [18.194.145.132] => (item=sha1)
skipping: [18.194.145.132] => (item=aes) 
ok: [18.194.145.132] => (item=xcbc)
skipping: [18.194.145.132] => (item=stroke) 
skipping: [18.194.145.132] => (item=openssl) 
ok: [18.194.145.132] => (item=rc2)
skipping: [18.194.145.132] => (item=pubkey) 
ok: [18.194.145.132] => (item=dnskey)
skipping: [18.194.145.132] => (item=socket-default) 
skipping: [18.194.145.132] => (item=nonce) 
skipping: [18.194.145.132] => (item=pkcs7) 
skipping: [18.194.145.132] => (item=pgp) 
ok: [18.194.145.132] => (item=constraints)
skipping: [18.194.145.132] => (item=revocation) 
ok: [18.194.145.132] => (item=md5)
ok: [18.194.145.132] => (item=md4)
skipping: [18.194.145.132] => (item=gcm) 
ok: [18.194.145.132] => (item=pkcs1)
skipping: [18.194.145.132] => (item=pkcs12) 
ok: [18.194.145.132] => (item=resolve)
ok: [18.194.145.132] => (item=agent)
ok: [18.194.145.132] => (item=gmp)

TASK [vpn : Ensure that required plugins are enabled] **************************
ok: [18.194.145.132] => (item=hmac)
skipping: [18.194.145.132] => (item=test-vectors) 
ok: [18.194.145.132] => (item=kernel-netlink)
skipping: [18.194.145.132] => (item=sshkey) 
skipping: [18.194.145.132] => (item=updown) 
ok: [18.194.145.132] => (item=x509)
ok: [18.194.145.132] => (item=pem)
skipping: [18.194.145.132] => (item=attr) 
skipping: [18.194.145.132] => (item=fips-prf) 
ok: [18.194.145.132] => (item=sha2)
ok: [18.194.145.132] => (item=random)
skipping: [18.194.145.132] => (item=connmark) 
ok: [18.194.145.132] => (item=pkcs8)
skipping: [18.194.145.132] => (item=sha1) 
ok: [18.194.145.132] => (item=aes)
skipping: [18.194.145.132] => (item=xcbc) 
ok: [18.194.145.132] => (item=stroke)
ok: [18.194.145.132] => (item=openssl)
skipping: [18.194.145.132] => (item=rc2) 
ok: [18.194.145.132] => (item=pubkey)
skipping: [18.194.145.132] => (item=dnskey) 
ok: [18.194.145.132] => (item=socket-default)
ok: [18.194.145.132] => (item=nonce)
ok: [18.194.145.132] => (item=pkcs7)
ok: [18.194.145.132] => (item=pgp)
skipping: [18.194.145.132] => (item=constraints) 
ok: [18.194.145.132] => (item=revocation)
skipping: [18.194.145.132] => (item=md5) 
skipping: [18.194.145.132] => (item=md4) 
ok: [18.194.145.132] => (item=gcm)
skipping: [18.194.145.132] => (item=pkcs1) 
ok: [18.194.145.132] => (item=pkcs12)
skipping: [18.194.145.132] => (item=resolve) 
skipping: [18.194.145.132] => (item=agent) 
skipping: [18.194.145.132] => (item=gmp) 

TASK [vpn : Ensure the pki directory does not exist] ***************************
skipping: [18.194.145.132]

TASK [vpn : Ensure the pki directories exist] **********************************
ok: [18.194.145.132 -> localhost] => (item=ecparams)
ok: [18.194.145.132 -> localhost] => (item=certs)
ok: [18.194.145.132 -> localhost] => (item=crl)
ok: [18.194.145.132 -> localhost] => (item=newcerts)
ok: [18.194.145.132 -> localhost] => (item=private)
ok: [18.194.145.132 -> localhost] => (item=reqs)

TASK [vpn : Ensure the files exist] ********************************************
changed: [18.194.145.132 -> localhost] => (item=.rnd)
changed: [18.194.145.132 -> localhost] => (item=private/.rnd)
changed: [18.194.145.132 -> localhost] => (item=index.txt)
changed: [18.194.145.132 -> localhost] => (item=index.txt.attr)
changed: [18.194.145.132 -> localhost] => (item=serial)

TASK [vpn : Generate the openssl server configs] *******************************
ok: [18.194.145.132 -> localhost]

TASK [vpn : Build the CA pair] *************************************************
fatal: [18.194.145.132 -> localhost]: FAILED! => {"changed": true, "cmd": "openssl ecparam -name prime256v1 -out ecparams/prime256v1.pem && openssl req -utf8 -new -newkey ec:ecparams/prime256v1.pem -config openssl.cnf -keyout private/cakey.pem -out cacert.pem -x509 -days 3650 -batch -passout pass:\"6b11e5a0aa518fa1222227f291572291\" && touch 18.194.145.132_ca_generated", "delta": "0:00:00.021897", "end": "2017-09-25 15:33:00.015107", "failed": true, "rc": 1, "start": "2017-09-25 15:32:59.993210", "stderr": "error on line 113 of openssl.cnf\n140735587025800:error:0E065068:configuration file routines:STR_COPY:variable has no value:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22/libressl/crypto/conf/conf_def.c:573:line 113", "stdout": "", "stdout_lines": [], "warnings": []}

TASK [vpn : debug] *************************************************************
ok: [18.194.145.132] => {
    "fail_hint": [
        "Sorry, but something went wrong!", 
        "Please check the troubleshooting guide.", 
        "https://trailofbits.github.io/algo/troubleshooting.html"
    ]
}

TASK [vpn : fail] **************************************************************
fatal: [18.194.145.132]: FAILED! => {"changed": false, "failed": true, "msg": "Failed as requested from task"}

RUNNING HANDLER [vpn : restart strongswan] *************************************

PLAY RECAP *********************************************************************
18.194.145.132             : ok=37   changed=10   unreachable=0    failed=1   
localhost                  : ok=19   changed=1    unreachable=0    failed=0

**Comment by dkarter** [comment]
Confirmed.

macOS high sierra

ansible 2.4.0.0

```
fatal: [REDACTED -> localhost]: FAILED! => {"changed": true, "cmd": "openssl
ecparam -name prime256v1 -out ecparams/prime256v1.pem && openssl req -utf8 -new
-newkey ec:ecparams/prime256v1.pem -config openssl.cnf -keyout private/cakey.pem
-out cacert.pem -x509 -days 3650 -batch -passout pass:\"REDACTED\" && touch
REDACTED_ca_generated", "delta": "0:00:00.023617", "end": "2017-09-29 15:37:59.214508", "failed": true, "rc": 1, "start": "2017-09-29 15:37:59.190891", "stderr": "error on line 113 of openssl.cnf\n140736075875208:error:0E065068:configuration file routines:STR_COPY:variable has no value:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22/libressl/crypto/conf/conf_def.c:573:line 113", "stdout": "", "stdout_lines": [], "warnings": []}
```

**Comment by gunph1ld** [comment]
https://github.com/trailofbits/algo/issues/625

**Comment by onekiloparsec** [comment]
Thanks!
