### ISSUE TITLE
IP Packet size is only managed for GCE

### ISSUE THREAD

**Issue by davesteele** [trailofbits/algo#686]
### OS / Environment
NA

### Ansible version
NA

### Version of components from `requirements.txt`
NA

### Summary of the problem
While [MTU Issues](https://github.com/trailofbits/algo/issues?utf8=%E2%9C%93&q=is%3Aissue%20mtu) are fairly prevalent, and seemingly inevitable, some users are able to avoid encountering the issue.

The gce environment alone addresses [reserving](https://github.com/trailofbits/algo/commit/2ec6f41e0ff8fb304e300a872a6f5ffed92e236d) IP packet space for VPN overhead, which is processed by the [vpn role](https://github.com/trailofbits/algo/blob/master/roles/vpn/templates/rules.v4.j2#L7).

This mss management should be extended to the other cloud providers.

### Steps to reproduce the behavior
grep -r mss *

### The way of deployment (cloud or local)
cloud (Actually, I suspect both).

### Expected behavior
Can browse to all web sites over the VPN, using a non-GCE server.

### Actual behavior
About half.

### Full log
<NA>

**Comment by davesteele** [comment]
#185 states that the problem existed for gce, but not ec1. I can confirm that do has the problem as well, and could use a max_mss define.

**Comment by jackivanov** [comment]
https://github.com/trailofbits/algo/pull/1015
