### ISSUE TITLE
Mac OS VPN not connected - Azure & GCE

### ISSUE THREAD

**Issue by yuzhe922** [trailofbits/algo#687]
### OS / Environment

macOS High Sierra 10.3.1 Beta

### Ansible version

NA

### Version of components from `requirements.txt`

NA

### Summary of the problem
I set up a Algo VPN at AWS and works fine. 
Then, at the same Mac OS, I put the Master file into another separate directory and tried to set up two new VPN at Azure & GCE. 
The whole deployment process looks fine, and finally generated two profiles. Then I install the profiles file successfully. However, not like the AWS VPN, in the Preference-Network, I can not connect the new two VPNs. Tried to connect, very quick reply no connect, the Status is always Not Connected. 

### The way of deployment (cloud or local)

Azure & GCE

**Comment by dguido** [comment]
There's not enough info to troubleshoot here, and I can't reproduce the issue. Maybe MTU related? Glad you got it working on AWS!
