### ISSUE TITLE
What ports should I open? 

### ISSUE THREAD

**Issue by 0120139** [trailofbits/algo#688]
### OS / Environment

digital ocean

### Ansible version

Installed last night

### Summary of the problem
I don't what to open all ports to the all world.. I would like to just open the ports needed so algo vpn will work properly...

Thanks!

**Comment by unstatusthequo** [comment]
I'm pretty sure it sets up it's own iptables. I just leave mine in DMZ and let iptables do the work. If it gets popped, I make another instance. Hasn't happened though in months of running it.

**Comment by Kowalski6** [comment]
Hi 0120139,

Just an FYI, the required ports for Algo are TCP/UDP 500 and 4500.  I tried enabling just TCP first but had to add UDP as well.  Hope this helps!

**Comment by 0120139** [comment]
Yes! thank you - I really did not like having to leave the server open for all the ports.
