### ISSUE TITLE
digital ocean ssh through vpn tunnel

### ISSUE THREAD

**Issue by jjssoftware** [trailofbits/algo#690]
### OS / Environment
ubuntu-16-04-x64 512mb droplet Digital Ocean London data centre

### Summary of the problem
When the tunnel is up and I attempt to ssh to the remote instance, ssh is barely usable due to slowness, lag. It feels like a DNS resolution issue. When not using the tunnel, ssh works without any issues.

### Steps to reproduce the behavior
1) Create a new 512mb Digital Ocean droplet in the London data centre via algo setup 
2) Upon setup done of the remote droplet, bring a VPN tunnel up to the droplet then attempt to ssh to the new droplet instance i.e. ssh -i configs/algo.pem root@[new ip address] and watch it hang

### The way of deployment (cloud or local)
cloud

### Expected behavior
ssh to the remote instance through the VPN tunnel works without delays

### Actual behavior
ssh to the remote instance through the VPN tunnel just about sometimes works with delays and lag making the session unusable

**Comment by agarella** [comment]
+1

**Comment by dguido** [comment]
You don't need to SSH to the local instance over the VPN tunnel. Both SSH and the VPN are encrypted tunnels, so SSH by itself should work just fine if you need to admin the server.
