### ISSUE TITLE
(just a general question)

### ISSUE THREAD

**Issue by Zaldara** [trailofbits/algo#692]
Is it possible to change the IP of my VPN / does Algo automatically change?

I've setup my VPN and it works however the network I'm on constantly blocks VPN traffic and I fear that they may somehow block my Algo VPN.

**Comment by dguido** [comment]
You have to regenerate all the keys if you switch to a new IP. Easier to redeploy from scratch.

Filing tickets on Github is generally reserved for bugs. You should ask questions like this in the Gitter.
