### ISSUE TITLE
The 'VPN Service' payload could not be installed. The VPN service could not be created.

### ISSUE THREAD

**Issue by bikr** [trailofbits/algo#701]
### OS / Environment
Mac OSX 10.11 

### Ansible version
ansible 2.2.0.0

### Version of components from `requirements.txt`
(Up To Date) 

### Summary of the problem
MobileConfig fails to install on OSX and installs but fails to connect on iOS.   

### Steps to reproduce the behavior
Installed algo as usual.  Generated users in config file.  
Installed .mobileconfig locally / enter password for p12 per the output in terminal , enter local machine password when prompted and get  

> `The 'VPN Service' payload could not be installed. The VPN service could not be created.`

 

### The way of deployment (cloud or local)

cloud 

### Expected behavior

mobileconfig should install and be connectable

### Actual behavior
The 'VPN Service' payload could not be installed. The VPN service could not be created. on OSX

and on iOS the profile installs but can't be enabled via VPN toggle.

**Comment by bikr** [comment]
``Oct 20 23:45:02 myVPN charon: 08[NET] waiting for data on sockets
Oct 20 23:45:17 myVPN charon: 08[NET] received packet: from 166.172.186.152[33495] to 165.227.49.168[500]
Oct 20 23:45:17 myVPN charon: 09[MGR] checkout IKE_SA by message
Oct 20 23:45:17 myVPN charon: 09[MGR] created IKE_SA (unnamed)[13]
Oct 20 23:45:17 myVPN charon: 09[NET] received packet: from 166.172.186.152[33495] to 165.227.49.168[500] (240 bytes)
Oct 20 23:45:17 myVPN charon: 09[ENC] parsed IKE_SA_INIT request 0 [ SA KE No N(NATD_S_IP) N(NATD_D_IP) N(FRAG_SUP) ]
Oct 20 23:45:17 myVPN charon: 09[CFG] looking for an ike config for 165.227.49.168...166.172.186.152
Oct 20 23:45:17 myVPN charon: 09[CFG]   candidate: %any...%any, prio 28
Oct 20 23:45:17 myVPN charon: 09[CFG] found matching ike config: %any...%any with prio 28
Oct 20 23:45:17 myVPN charon: 09[IKE] 166.172.186.152 is initiating an IKE_SA
Oct 20 23:45:17 myVPN charon: 09[IKE] IKE_SA (unnamed)[13] state change: CREATED => CONNECTING
Oct 20 23:45:17 myVPN charon: 09[CFG] selecting proposal:
Oct 20 23:45:17 myVPN charon: 09[CFG]   proposal matches
Oct 20 23:45:17 myVPN charon: 09[CFG] received proposals: IKE:AES_GCM_16_128/PRF_HMAC_SHA2_512/ECP_256
Oct 20 23:45:17 myVPN charon: 09[CFG] configured proposals: IKE:AES_GCM_16_128/PRF_HMAC_SHA2_512/ECP_256, IKE:AES_CBC_128/HMAC_SHA2_512_256/PRF_HMAC_SHA2_512/ECP_256, IKE:AES_CBC_128/HMAC_SHA2_384_192/PRF_HMAC_SHA2_384/ECP_256
Oct 20 23:45:17 myVPN charon: 09[CFG] selected proposal: IKE:AES_GCM_16_128/PRF_HMAC_SHA2_512/ECP_256
Oct 20 23:45:17 myVPN charon: 09[IKE] remote host is behind NAT
Oct 20 23:45:17 myVPN charon: 09[IKE] sending cert request for "CN=165.227.49.168"
Oct 20 23:45:17 myVPN charon: 09[ENC] generating IKE_SA_INIT response 0 [ SA KE No N(NATD_S_IP) N(NATD_D_IP) CERTREQ N(FRAG_SUP) N(MULT_AUTH) ]
Oct 20 23:45:17 myVPN charon: 09[NET] sending packet: from 165.227.49.168[500] to 166.172.186.152[33495] (273 bytes)
Oct 20 23:45:17 myVPN charon: 05[NET] sending packet: from 165.227.49.168[500] to 166.172.186.152[33495]
Oct 20 23:45:17 myVPN charon: 09[MGR] checkin IKE_SA (unnamed)[13]
Oct 20 23:45:17 myVPN charon: 09[MGR] check-in of IKE_SA successful.
Oct 20 23:45:17 myVPN charon: 08[NET] waiting for data on sockets
Oct 20 23:45:17 myVPN charon: 08[NET] received packet: from 166.172.186.152[4951] to 165.227.49.168[4500]
Oct 20 23:45:17 myVPN charon: 10[MGR] checkout IKE_SA by message
Oct 20 23:45:17 myVPN charon: 10[MGR] IKE_SA (unnamed)[13] successfully checked out
Oct 20 23:45:17 myVPN charon: 10[NET] received packet: from 166.172.186.152[4951] to 165.227.49.168[4500] (540 bytes)
Oct 20 23:45:17 myVPN charon: 10[ENC] parsed IKE_AUTH request 1 [ EF(1/2) ]
Oct 20 23:45:17 myVPN charon: 10[ENC] received fragment #1 of 2, waiting for complete IKE message
Oct 20 23:45:17 myVPN charon: 10[MGR] checkin IKE_SA (unnamed)[13]
Oct 20 23:45:17 myVPN charon: 10[MGR] check-in of IKE_SA successful.
Oct 20 23:45:17 myVPN charon: 08[NET] waiting for data on sockets
Oct 20 23:45:17 myVPN charon: 08[NET] received packet: from 166.172.186.152[4951] to 165.227.49.168[4500]
Oct 20 23:45:17 myVPN charon: 11[MGR] checkout IKE_SA by message
Oct 20 23:45:17 myVPN charon: 11[MGR] IKE_SA (unnamed)[13] successfully checked out
Oct 20 23:45:17 myVPN charon: 11[NET] received packet: from 166.172.186.152[4951] to 165.227.49.168[4500] (452 bytes)
Oct 20 23:45:17 myVPN charon: 11[ENC] parsed IKE_AUTH request 1 [ EF(2/2) ]
Oct 20 23:45:17 myVPN charon: 11[ENC] received fragment #2 of 2, reassembling fragmented IKE message
Oct 20 23:45:17 myVPN charon: 11[ENC] unknown attribute type (25)
Oct 20 23:45:17 myVPN charon: 11[ENC] parsed IKE_AUTH request 1 [ IDi N(INIT_CONTACT) N(MOBIKE_SUP) IDr CERTREQ AUTH CERT CPRQ(ADDR DHCP DNS MASK ADDR6 DHCP6 DNS6 (25)) N(ESP_TFC_PAD_N) N(NON_FIRST_FRAG) SA TSi TSr ]
Oct 20 23:45:17 myVPN charon: 11[IKE] received cert request for "CN=165.227.49.168"
Oct 20 23:45:17 myVPN charon: 11[IKE] received end entity cert "CN=myemail@myemail.net"
Oct 20 23:45:17 myVPN charon: 11[CFG] looking for peer configs matching 165.227.49.168[165.227.49.168]...166.172.186.152[myemail@myemail.net]
Oct 20 23:45:17 myVPN charon: 11[CFG]   candidate "ikev2-pubkey", match: 20/1/28 (me/other/ike)
Oct 20 23:45:17 myVPN charon: 11[CFG] selected peer config 'ikev2-pubkey'
Oct 20 23:45:17 myVPN charon: 11[IKE] no trusted ECDSA public key found for 'myemail@myemail.net'
Oct 20 23:45:17 myVPN charon: 11[IKE] processing INTERNAL_IP4_ADDRESS attribute
Oct 20 23:45:17 myVPN charon: 11[IKE] processing INTERNAL_IP4_DHCP attribute
Oct 20 23:45:17 myVPN charon: 11[IKE] processing INTERNAL_IP4_DNS attribute
Oct 20 23:45:17 myVPN charon: 11[IKE] processing INTERNAL_IP4_NETMASK attribute
Oct 20 23:45:17 myVPN charon: 11[IKE] processing INTERNAL_IP6_ADDRESS attribute
Oct 20 23:45:17 myVPN charon: 11[IKE] processing INTERNAL_IP6_DHCP attribute
Oct 20 23:45:17 myVPN charon: 11[IKE] processing INTERNAL_IP6_DNS attribute
Oct 20 23:45:17 myVPN charon: 11[IKE] processing (25) attribute
Oct 20 23:45:17 myVPN charon: 11[IKE] received ESP_TFC_PADDING_NOT_SUPPORTED, not using ESPv3 TFC padding
Oct 20 23:45:17 myVPN charon: 11[IKE] peer supports MOBIKE
Oct 20 23:45:17 myVPN charon: 11[ENC] generating IKE_AUTH response 1 [ N(AUTH_FAILED) ]
Oct 20 23:45:17 myVPN charon: 11[NET] sending packet: from 165.227.49.168[4500] to 166.172.186.152[4951] (65 bytes)
Oct 20 23:45:17 myVPN charon: 05[NET] sending packet: from 165.227.49.168[4500] to 166.172.186.152[4951]
Oct 20 23:45:17 myVPN charon: 11[MGR] checkin and destroy IKE_SA ikev2-pubkey[13]
Oct 20 23:45:17 myVPN charon: 11[IKE] IKE_SA ikev2-pubkey[13] state change: CONNECTING => DESTROYING
Oct 20 23:45:17 myVPN charon: 11[MGR] check-in and destroy of IKE_SA successful
Oct 20 23:45:17 myVPN charon: 08[NET] waiting for data on sockets
``

**Comment by bikr** [comment]
iOS issue appears to be resolved by not using email addresses for user names.   Still unable to install on OSX.

**Comment by dguido** [comment]
Yes, stick to alphanum for user names

**Comment by bikr** [comment]
@dguido   any help / way to diagnose   

The 'VPN Service' payload could not be installed. The VPN service could not be created.   Tried across El Capitan and Yosemite  same issue..    What else can I check to see why the config won't install on OSX?

**Comment by bikr** [comment]
Trying to load via profile on mac from command line gives an error about missing param "password" I'm guessing because it wants the p12 password but it doesn't prompt for it like it does when you simply run the mobileconfig.

**Comment by bikr** [comment]
Setting up manually after importing the p12 file via terminal with security import and  I get this in the syslog on the remote server: 

`Oct 21 00:44:23 winkalgo charon: 08[NET] received packet: from 75.30.228.47[500] to 162.243.146.189[500]
Oct 21 00:44:23 winkalgo charon: 03[MGR] checkout IKE_SA by message
Oct 21 00:44:23 winkalgo charon: 03[MGR] created IKE_SA (unnamed)[12]
Oct 21 00:44:23 winkalgo charon: 03[NET] received packet: from 75.30.228.47[500] to 162.243.146.189[500] (300 bytes)
Oct 21 00:44:23 winkalgo charon: 03[ENC] parsed IKE_SA_INIT request 0 [ SA KE No N(REDIR_SUP) N(NATD_S_IP) N(NATD_D_IP) N(FRAG_SUP) ]
Oct 21 00:44:23 winkalgo charon: 03[CFG] looking for an ike config for 162.243.146.189...75.30.228.47
Oct 21 00:44:23 winkalgo charon: 03[CFG]   candidate: %any...%any, prio 28
Oct 21 00:44:23 winkalgo charon: 03[CFG] found matching ike config: %any...%any with prio 28
Oct 21 00:44:23 winkalgo charon: 03[IKE] 75.30.228.47 is initiating an IKE_SA
Oct 21 00:44:23 winkalgo charon: 03[IKE] IKE_SA (unnamed)[12] state change: CREATED => CONNECTING
Oct 21 00:44:23 winkalgo charon: 03[CFG] selecting proposal:
Oct 21 00:44:23 winkalgo charon: 03[CFG]   no acceptable ENCRYPTION_ALGORITHM found
Oct 21 00:44:23 winkalgo charon: 03[CFG] selecting proposal:
Oct 21 00:44:23 winkalgo charon: 03[CFG]   no acceptable ENCRYPTION_ALGORITHM found
Oct 21 00:44:23 winkalgo charon: 03[CFG] selecting proposal:
Oct 21 00:44:23 winkalgo charon: 03[CFG]   no acceptable ENCRYPTION_ALGORITHM found
Oct 21 00:44:23 winkalgo charon: 03[CFG] received proposals: IKE:3DES_CBC/HMAC_SHA1_96/PRF_HMAC_SHA1/MODP_1024
Oct 21 00:44:23 winkalgo charon: 03[CFG] configured proposals: IKE:AES_GCM_16_128/PRF_HMAC_SHA2_512/ECP_256, IKE:AES_CBC_128/HMAC_SHA2_512_256/PRF_HMAC_SHA2_512/ECP_256, IKE:AES_CBC_128/HMAC_SHA2_384_192/PRF_HMAC_SHA2_384/ECP_256
Oct 21 00:44:23 winkalgo charon: 03[IKE] remote host is behind NAT
Oct 21 00:44:23 winkalgo charon: 03[IKE] received proposals inacceptable
Oct 21 00:44:23 winkalgo charon: 03[ENC] generating IKE_SA_INIT response 0 [ N(NO_PROP) ]
Oct 21 00:44:23 winkalgo charon: 03[NET] sending packet: from 162.243.146.189[500] to 75.30.228.47[500] (36 bytes)
Oct 21 00:44:23 winkalgo charon: 09[NET] sending packet: from 162.243.146.189[500] to 75.30.228.47[500]
Oct 21 00:44:23 winkalgo charon: 03[MGR] checkin and destroy IKE_SA (unnamed)[12]
Oct 21 00:44:23 winkalgo charon: 03[IKE] IKE_SA (unnamed)[12] state change: CONNECTING => DESTROYING
Oct 21 00:44:23 winkalgo charon: 03[MGR] check-in and destroy of IKE_SA successful
Oct 21 00:44:23 winkalgo charon: 08[NET] waiting for data on sockets`

**Comment by bikr** [comment]
The key  password isn't being created in the mobileconfig , manually creating it and adding the string of the password from the p12 output of algo generates the below when running: 

`/usr/bin/profiles -I -F ~/Downloads/algo-master/configs/138.68.54.89/josh.mobileconfig `

`profiles install for file:'/Users/JoshW/Downloads/algo-master/configs/138.68.54.89/josh.mobileconfig' and user:'JoshW' returned -319 (The 'VPN Service' payload could not be installed. The VPN service could not be created.)`

**Comment by dguido** [comment]
I just tested this on macOS 10.13 and it works fine. I think it's an artifact of you using 10.11. Please upgrade to a newer (and safer) version of macOS and it should work fine. We only maintain official support for the 2 most recent versions of any operating system.

**Comment by bikr** [comment]
Should master be making .p12 passwords with complex characters in it still?

**Comment by bikr** [comment]
![image](https://user-images.githubusercontent.com/1229320/31848254-d6439c9a-b5fb-11e7-848d-b39c2403bded.png)

**Comment by bikr** [comment]
Still no go.  Can this be reopened?

**Comment by bikr** [comment]
@dguido

**Comment by bikr** [comment]
Got it , wasn't OS specific, was a corrupt keychain.  Couldn't even manually import the p12.

**Comment by junv** [comment]
@bikr how were you able to resolve the issue? I am getting the same error message.

**Comment by cwexp** [comment]
I have the same problem with "The 'VPN Service' payload could not be installed. The VPN service could not be created.". I am on MacOS Sierra v. 10.12.6. I'd appreciate any help.

**Comment by peterjcaulfield** [comment]
Same issue. @bikr can you update the thread with what you did to diagnose/solve please?

**Comment by ctindel** [comment]
Try manually adding the ca.crt file and changing the trust preferences on it to "Always Trust".  Then remove the part of the .mobileconfig file that adds that ca.crt and try it again.
