### ISSUE TITLE
Cannot connect SSH Tunnel from windows

### ISSUE THREAD

**Issue by viperz0r** [trailofbits/algo#702]
### OS / Environment
Ubuntu 16.04.3 LTS

### Ansible version
ansible 2.2.0.0

### Version of components from `requirements.txt`

Name: msrestazure
Version: 0.4.15
Summary: AutoRest swagger generator Python client runtime. Azure-specific module.
Home-page: https://github.com/Azure/msrestazure-for-python
Author: Microsoft Corporation
Author-email: azpysdkhelp@microsoft.com
License: MIT License
Location: /root/algo/env/lib/python2.7/site-packages
Requires: keyring, msrest, adal
---
Name: setuptools
Version: 36.6.0
Summary: Easily download, build, install, upgrade, and uninstall Python packages
Home-page: https://github.com/pypa/setuptools
Author: Python Packaging Authority
Author-email: distutils-sig@python.org
License: UNKNOWN
Location: /root/algo/env/lib/python2.7/site-packages
Requires:
---
Name: ansible
Version: 2.2.0.0
Summary: Radically simple IT automation
Home-page: http://ansible.com/
Author: Ansible, Inc.
Author-email: info@ansible.com
License: GPLv3
Location: /root/algo/env/lib/python2.7/site-packages
Requires: PyYAML, setuptools, jinja2, paramiko, pycrypto
---
Name: dopy
Version: 0.3.5
Summary: Python client for the Digital Ocean API
Home-page: https://github.com/devo-ps/dopy
Author: Vincent Viallet
Author-email: vincent@devo.ps
License: The MIT License (MIT)
Location: /root/algo/env/lib/python2.7/site-packages
Requires: requests
---
Name: boto
Version: 2.48.0
Summary: Amazon Web Services Library
Home-page: https://github.com/boto/boto/
Author: Mitch Garnaat
Author-email: mitch@garnaat.com
License: MIT
Location: /root/algo/env/lib/python2.7/site-packages
Requires:
---
Name: boto3
Version: 1.4.7
Summary: The AWS SDK for Python
Home-page: https://github.com/boto/boto3
Author: Amazon Web Services
Author-email: UNKNOWN
License: Apache License 2.0
Location: /root/algo/env/lib/python2.7/site-packages
Requires: botocore, jmespath, s3transfer
---
Name: azure
Version: 2.0.0rc5
Summary: Microsoft Azure Client Libraries for Python
Home-page: https://github.com/Azure/azure-sdk-for-python
Author: Microsoft Corporation
Author-email: ptvshelp@microsoft.com
License: MIT License
Location: /root/algo/env/lib/python2.7/site-packages
Requires: azure-batch, azure-servicemanagement-legacy, azure-graphrbac, azure-storage, azure-mgmt, azure-servicebus
---
Name: msrest
Version: 0.4.1
Summary: AutoRest swagger generator Python client runtime.
Home-page: https://github.com/xingwu1/autorest/tree/python/ClientRuntimes/Python/msrest
Author: Microsoft Corporation
Author-email: UNKNOWN
License: MIT License
Location: /root/algo/env/lib/python2.7/site-packages
Requires: requests, certifi, chardet, requests-oauthlib, keyring, enum34, isodate
---
Name: apache-libcloud
Version: 2.2.1
Summary: A standard Python library that abstracts away differences among multiple cloud provider APIs. For more information and documentation, please see http://libcloud.apache.org
Home-page: http://libcloud.apache.org/
Author: Apache Software Foundation
Author-email: dev@libcloud.apache.org
License: Apache License (2.0)
Location: /root/algo/env/lib/python2.7/site-packages
Requires: requests
---
Name: six
Version: 1.11.0
Summary: Python 2 and 3 compatibility utilities
Home-page: http://pypi.python.org/pypi/six/
Author: Benjamin Peterson
Author-email: benjamin@python.org
License: MIT
Location: /root/algo/env/lib/python2.7/site-packages
Requires:
---
Name: pyOpenSSL
Version: 17.3.0
Summary: Python wrapper module around the OpenSSL library
Home-page: https://pyopenssl.org/
Author: Hynek Schlawack
Author-email: hs@ox.cx
License: Apache License, Version 2.0
Location: /root/algo/env/lib/python2.7/site-packages
Requires: six, cryptography
---
Name: Jinja2
Version: 2.8
Summary: A small but fast and easy to use stand-alone template engine written in pure python.
Home-page: http://jinja.pocoo.org/
Author: Armin Ronacher
Author-email: armin.ronacher@active-4.com
License: BSD
Location: /root/algo/env/lib/python2.7/site-packages
Requires: MarkupSafe

### Summary of the problem
Cannot setup ssh tunel. After typing the passphrase for the ssh.pem certificate connection close.
I tried with cygwin and putty, both with the same problem. 
https://ibb.co/i6qOY6

### Steps to reproduce the behavior
connect to ssh tunnel from a windows machine

### The way of deployment (cloud or local)
local

### Expected behavior
maintain the forwarding connection open and redirect the traffic

### Actual behavior
Connection closes

### Full log
  What provider would you like to use?
    1. DigitalOcean
    2. Amazon EC2
    3. Microsoft Azure
    4. Google Compute Engine
    5. Install to existing Ubuntu 16.04 server

Enter the number of your desired provider
: 5

Enter the IP address of your server: (or use localhost for local installation)
[localhost]: localhost

What user should we use to login on the server? (note: passwordless login requir                                                                                                                                                             ed, or ignore if you're deploying to localhost)
[root]: root

Enter the public IP address of your server: (IMPORTANT! This IP is used to verif                                                                                                                                                             y the certificate)
[]: XXX.XXX.XXX.192

Was this server deployed by Algo previously?
[y/N]: n

Do you want macOS/iOS clients to enable "VPN On Demand" when connected to cellul                                                                                                                                                             ar networks?
[y/N]: n

Do you want macOS/iOS clients to enable "VPN On Demand" when connected to Wi-Fi?
[y/N]: n

Do you want to install a DNS resolver on this VPN server, to block ads while sur                                                                                                                                                             fing?
[y/N]: n

Do you want each user to have their own account for SSH tunneling?
[y/N]: y

Do you want to apply operating system security enhancements on the server? (warn                                                                                                                                                             ing: replaces your sshd_config)
[y/N]: n

Do you want the VPN to support Windows 10 or Linux Desktop clients? (enables com                                                                                                                                                             patible ciphers and key exchange, less secure)
[y/N]: y

Do you want to retain the CA key? (required to add users in the future, but less                                                                                                                                                              secure)
[y/N]: y

PLAY [Configure the server] ****************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Generate the SSH private key] ********************************************
changed: [localhost]

TASK [Generate the SSH public key] *********************************************
ok: [localhost]

TASK [Change mode for the SSH private key] *************************************
ok: [localhost]

TASK [Ensure the dynamic inventory exists] *************************************
changed: [localhost]

TASK [Ensure the local ssh directory is exist] *********************************
skipping: [localhost]

TASK [Copy the algo ssh key to the local ssh directory] ************************
skipping: [localhost]

TASK [local : Add the instance to an inventory group] **************************
skipping: [localhost]

TASK [local : Add the instance to an inventory group] **************************
changed: [localhost]

TASK [local : set_fact] ********************************************************
ok: [localhost]

TASK [local : Ensure the group local exists in the dynamic inventory file] *****
changed: [localhost]

TASK [local : Populate the dynamic inventory] **********************************
changed: [localhost]

PLAY [Configure the server and install required software] **********************

TASK [Check the system] ********************************************************
changed: [localhost]

TASK [Ubuntu | Install prerequisites] ******************************************
changed: [localhost]

TASK [FreeBSD / HardenedBSD | Install prerequisites] ***************************
skipping: [localhost]

TASK [FreeBSD / HardenedBSD | Configure defaults] ******************************
skipping: [localhost]

TASK [set_fact] ****************************************************************
skipping: [localhost]

TASK [Gather Facts] ************************************************************
ok: [localhost]

TASK [Enable IPv6] *************************************************************
skipping: [localhost]

TASK [Generate password for the CA key] ****************************************
changed: [localhost -> localhost]

TASK [Generate p12 export password] ********************************************
changed: [localhost -> localhost]

TASK [Define password facts] ***************************************************
ok: [localhost]

TASK [Define the commonName] ***************************************************
ok: [localhost]

TASK [common : Loopback for services configured] *******************************
changed: [localhost]

TASK [common : Loopback included into the network config] **********************
changed: [localhost]

RUNNING HANDLER [common : restart loopback] ************************************
changed: [localhost]

TASK [common : set_fact] *******************************************************
ok: [localhost]

TASK [common : set_fact] *******************************************************
skipping: [localhost]

TASK [common : Loopback included into the rc config] ***************************
skipping: [localhost]

TASK [common : Enable the gateway features] ************************************
skipping: [localhost] => (item={u'value': u'"YES"', u'param': u'firewall_enable'                                                                                                                                                             })
skipping: [localhost] => (item={u'value': u'"open"', u'param': u'firewall_type'}                                                                                                                                                             )
skipping: [localhost] => (item={u'value': u'"YES"', u'param': u'gateway_enable'}                                                                                                                                                             )
skipping: [localhost] => (item={u'value': u'"YES"', u'param': u'natd_enable'})
skipping: [localhost] => (item={u'value': u'""', u'param': u'natd_interface'})
skipping: [localhost] => (item={u'value': u'"-dynamic -m"', u'param': u'natd_fla                                                                                                                                                             gs'})

TASK [common : Install tools] **************************************************
changed: [localhost] => (item=[u'git', u'screen', u'apparmor-utils', u'uuid-runt                                                                                                                                                             ime', u'coreutils', u'sendmail', u'iptables-persistent', u'cgroup-tools', u'open                                                                                                                                                             ssl'])

TASK [common : Sysctl tuning] **************************************************
changed: [localhost] => (item={u'item': u'net.ipv4.ip_forward', u'value': 1})
changed: [localhost] => (item={u'item': u'net.ipv4.conf.all.forwarding', u'value                                                                                                                                                             ': 1})
changed: [localhost] => (item={u'item': u'net.ipv6.conf.all.forwarding', u'value                                                                                                                                                             ': 1})

TASK [ssh_tunneling : Ensure that the sshd_config file has desired options] ****
changed: [localhost]

TASK [ssh_tunneling : Ensure that the algo group exist] ************************
changed: [localhost]

TASK [ssh_tunneling : Ensure that the jail directory exist] ********************
changed: [localhost]

TASK [ssh_tunneling : Ensure that the SSH users exist] *************************
changed: [localhost] => (item=dan)
changed: [localhost] => (item=jack)

TASK [ssh_tunneling : The authorized keys file created] ************************
changed: [localhost] => (item=dan)
changed: [localhost] => (item=jack)

TASK [ssh_tunneling : Generate SSH fingerprints] *******************************
changed: [localhost]

TASK [ssh_tunneling : Fetch users SSH private keys] ****************************
changed: [localhost] => (item=dan)
changed: [localhost] => (item=jack)

TASK [ssh_tunneling : Change mode for SSH private keys] ************************
changed: [localhost -> localhost] => (item=dan)
changed: [localhost -> localhost] => (item=jack)

TASK [ssh_tunneling : Fetch the known_hosts file] ******************************
changed: [localhost -> localhost]

TASK [ssh_tunneling : Build the client ssh config] *****************************
changed: [localhost -> localhost] => (item=dan)
changed: [localhost -> localhost] => (item=jack)

TASK [ssh_tunneling : SSH | Get active system users] ***************************
skipping: [localhost]

TASK [ssh_tunneling : SSH | Delete non-existing users] *************************
skipping: [localhost] => (item=null)

TASK [vpn : Ensure that the strongswan group exist] ****************************
changed: [localhost]

TASK [vpn : Ensure that the strongswan user exist] *****************************
changed: [localhost]

TASK [vpn : set_fact] **********************************************************
ok: [localhost]

TASK [vpn : Ubuntu | Install strongSwan] ***************************************
changed: [localhost]

TASK [vpn : Ubuntu | Enforcing ipsec with apparmor] ****************************
skipping: [localhost] => (item=/usr/lib/ipsec/charon)
skipping: [localhost] => (item=/usr/lib/ipsec/lookip)
skipping: [localhost] => (item=/usr/lib/ipsec/stroke)

TASK [vpn : Ubuntu | Enable services] ******************************************
changed: [localhost] => (item=apparmor)
ok: [localhost] => (item=strongswan)
ok: [localhost] => (item=netfilter-persistent)

TASK [vpn : Ubuntu | Ensure that the strongswan service directory exist] *******
changed: [localhost]

TASK [vpn : Ubuntu | Setup the cgroup limitations for the ipsec daemon] ********
changed: [localhost]

TASK [vpn : Iptables configured] ***********************************************
changed: [localhost] => (item={u'dest': u'/etc/iptables/rules.v4', u'src': u'rul                                                                                                                                                             es.v4.j2'})

TASK [vpn : Iptables configured] ***********************************************
skipping: [localhost] => (item={u'dest': u'/etc/iptables/rules.v6', u'src': u'ru                                                                                                                                                             les.v6.j2'})

TASK [vpn : FreeBSD / HardenedBSD | Get the existing kernel parameters] ********
skipping: [localhost]

TASK [vpn : FreeBSD / HardenedBSD | Set the rebuild_needed fact] ***************
skipping: [localhost] => (item=IPSEC)
skipping: [localhost] => (item=IPSEC_NAT_T)
skipping: [localhost] => (item=crypto)

TASK [vpn : FreeBSD / HardenedBSD | Make the kernel config] ********************
skipping: [localhost]

TASK [vpn : FreeBSD / HardenedBSD | Ensure the all options are enabled] ********
skipping: [localhost] => (item=options  IPSEC)
skipping: [localhost] => (item=options IPSEC_NAT_T)
skipping: [localhost] => (item=device   crypto)

TASK [vpn : HardenedBSD | Determine the sources] *******************************
skipping: [localhost]

TASK [vpn : FreeBSD | Determine the sources] ***********************************
skipping: [localhost]

TASK [vpn : FreeBSD / HardenedBSD | Increase the git postBuffer size] **********
skipping: [localhost]

TASK [vpn : FreeBSD / HardenedBSD | Fetching the sources...] *******************
skipping: [localhost]

TASK [vpn : FreeBSD / HardenedBSD | Fetching the sources...] *******************
skipping: [localhost]

TASK [vpn : FreeBSD / HardenedBSD | The kernel is being built...] **************
skipping: [localhost]

TASK [vpn : FreeBSD / HardenedBSD | The kernel is being built...] **************
skipping: [localhost]

TASK [vpn : FreeBSD / HardenedBSD | Reboot] ************************************
skipping: [localhost]

TASK [vpn : FreeBSD / HardenedBSD | Enable strongswan] *************************
skipping: [localhost]

TASK [vpn : Install strongSwan] ************************************************
ok: [localhost]

TASK [vpn : Setup the config files from our templates] *************************
changed: [localhost] => (item={u'dest': u'/etc/strongswan.conf', u'src': u'stron                                                                                                                                                             gswan.conf.j2', u'group': u'root', u'mode': u'0644', u'owner': u'root'})
changed: [localhost] => (item={u'dest': u'/etc/ipsec.conf', u'src': u'ipsec.conf                                                                                                                                                             .j2', u'group': u'root', u'mode': u'0644', u'owner': u'root'})
changed: [localhost] => (item={u'dest': u'/etc/ipsec.secrets', u'src': u'ipsec.s                                                                                                                                                             ecrets.j2', u'group': u'root', u'mode': u'0600', u'owner': u'strongswan'})

TASK [vpn : Get loaded plugins] ************************************************
changed: [localhost]

TASK [vpn : Disable unneeded plugins] ******************************************
skipping: [localhost] => (item=nonce)
skipping: [localhost] => (item=hmac)
skipping: [localhost] => (item=stroke)
skipping: [localhost] => (item=pem)
skipping: [localhost] => (item=aes)
changed: [localhost] => (item=constraints)
changed: [localhost] => (item=resolve)
changed: [localhost] => (item=rc2)
changed: [localhost] => (item=pkcs1)
changed: [localhost] => (item=gmp)
changed: [localhost] => (item=test-vectors)
skipping: [localhost] => (item=gcm)
skipping: [localhost] => (item=random)
skipping: [localhost] => (item=pubkey)
changed: [localhost] => (item=attr)
skipping: [localhost] => (item=pkcs12)
changed: [localhost] => (item=xcbc)
skipping: [localhost] => (item=openssl)
skipping: [localhost] => (item=socket-default)
skipping: [localhost] => (item=kernel-netlink)
changed: [localhost] => (item=sshkey)
changed: [localhost] => (item=connmark)
skipping: [localhost] => (item=pkcs8)
skipping: [localhost] => (item=sha2)
skipping: [localhost] => (item=revocation)
skipping: [localhost] => (item=pgp)
changed: [localhost] => (item=fips-prf)
skipping: [localhost] => (item=pkcs7)
skipping: [localhost] => (item=x509)
changed: [localhost] => (item=md5)
changed: [localhost] => (item=dnskey)
changed: [localhost] => (item=md4)
changed: [localhost] => (item=sha1)
changed: [localhost] => (item=updown)
changed: [localhost] => (item=agent)

TASK [vpn : Ensure that required plugins are enabled] **************************
changed: [localhost] => (item=nonce)
changed: [localhost] => (item=hmac)
changed: [localhost] => (item=stroke)
changed: [localhost] => (item=pem)
changed: [localhost] => (item=aes)
skipping: [localhost] => (item=constraints)
skipping: [localhost] => (item=resolve)
skipping: [localhost] => (item=rc2)
skipping: [localhost] => (item=pkcs1)
skipping: [localhost] => (item=gmp)
skipping: [localhost] => (item=test-vectors)
changed: [localhost] => (item=gcm)
changed: [localhost] => (item=random)
changed: [localhost] => (item=pubkey)
skipping: [localhost] => (item=attr)
changed: [localhost] => (item=pkcs12)
skipping: [localhost] => (item=xcbc)
changed: [localhost] => (item=openssl)
changed: [localhost] => (item=socket-default)
changed: [localhost] => (item=kernel-netlink)
skipping: [localhost] => (item=sshkey)
skipping: [localhost] => (item=connmark)
changed: [localhost] => (item=pkcs8)
changed: [localhost] => (item=sha2)
changed: [localhost] => (item=revocation)
changed: [localhost] => (item=pgp)
skipping: [localhost] => (item=fips-prf)
changed: [localhost] => (item=pkcs7)
changed: [localhost] => (item=x509)
skipping: [localhost] => (item=md5)
skipping: [localhost] => (item=dnskey)
skipping: [localhost] => (item=md4)
skipping: [localhost] => (item=sha1)
skipping: [localhost] => (item=updown)
skipping: [localhost] => (item=agent)

TASK [vpn : Ensure the pki directory does not exist] ***************************
skipping: [localhost]

TASK [vpn : Ensure the pki directories exist] **********************************
changed: [localhost -> localhost] => (item=ecparams)
changed: [localhost -> localhost] => (item=certs)
changed: [localhost -> localhost] => (item=crl)
changed: [localhost -> localhost] => (item=newcerts)
changed: [localhost -> localhost] => (item=private)
changed: [localhost -> localhost] => (item=reqs)

TASK [vpn : Ensure the files exist] ********************************************
changed: [localhost -> localhost] => (item=.rnd)
changed: [localhost -> localhost] => (item=private/.rnd)
changed: [localhost -> localhost] => (item=index.txt)
changed: [localhost -> localhost] => (item=index.txt.attr)
changed: [localhost -> localhost] => (item=serial)

TASK [vpn : Generate the openssl server configs] *******************************
changed: [localhost -> localhost]

TASK [vpn : Build the CA pair] *************************************************
changed: [localhost -> localhost]

TASK [vpn : Copy the CA certificate] *******************************************
changed: [localhost -> localhost]

TASK [vpn : Generate the serial number] ****************************************
changed: [localhost -> localhost]

TASK [vpn : Build the server pair] *********************************************
changed: [localhost -> localhost]

TASK [vpn : Build the client's pair] *******************************************
changed: [localhost -> localhost] => (item=dan)
changed: [localhost -> localhost] => (item=jack)

TASK [vpn : Build the client's p12] ********************************************
changed: [localhost -> localhost] => (item=dan)
changed: [localhost -> localhost] => (item=jack)

TASK [vpn : Copy the p12 certificates] *****************************************
changed: [localhost -> localhost] => (item=dan)
changed: [localhost -> localhost] => (item=jack)

TASK [vpn : Get active users] **************************************************
changed: [localhost -> localhost]

TASK [vpn : Revoke non-existing users] *****************************************
skipping: [localhost] => (item=dan)
skipping: [localhost] => (item=jack)

TASK [vpn : Copy the revoked certificates to the vpn server] *******************
skipping: [localhost] => (item=dan)
skipping: [localhost] => (item=jack)

TASK [vpn : Copy the keys to the strongswan directory] *************************
changed: [localhost] => (item={u'dest': u'/etc/ipsec.d/cacerts/ca.crt', u'src':                                                                                                                                                              u'configs/XXX.XXX.XXX.192/pki/cacert.pem', u'group': u'root', u'mode': u'0600',                                                                                                                                                              u'owner': u'strongswan'})
changed: [localhost] => (item={u'dest': u'/etc/ipsec.d/certs/XXX.XXX.XXX.192.crt                                                                                                                                                             ', u'src': u'configs/XXX.XXX.XXX.192/pki/certs/XXX.XXX.XXX.192.crt', u'group': u                                                                                                                                                             'root', u'mode': u'0600', u'owner': u'strongswan'})
changed: [localhost] => (item={u'dest': u'/etc/ipsec.d/private/XXX.XXX.XXX.192.k                                                                                                                                                             ey', u'src': u'configs/XXX.XXX.XXX.192/pki/private/XXX.XXX.XXX.192.key', u'group                                                                                                                                                             ': u'root', u'mode': u'0600', u'owner': u'strongswan'})

TASK [vpn : Register p12 PayloadContent] ***************************************
changed: [localhost -> localhost] => (item=dan)
changed: [localhost -> localhost] => (item=jack)

TASK [vpn : Set facts for mobileconfigs] ***************************************
ok: [localhost -> localhost]

TASK [vpn : Build the mobileconfigs] *******************************************
changed: [localhost -> localhost] => (item=(censored due to no_log))
changed: [localhost -> localhost] => (item=(censored due to no_log))

TASK [vpn : Build the strongswan app android config] ***************************
changed: [localhost -> localhost] => (item=(censored due to no_log))
changed: [localhost -> localhost] => (item=(censored due to no_log))

TASK [vpn : Build the android helper html] *************************************
changed: [localhost -> localhost] => (item=(censored due to no_log))
changed: [localhost -> localhost] => (item=(censored due to no_log))

TASK [vpn : Build the client ipsec config file] ********************************
changed: [localhost -> localhost] => (item=dan)
changed: [localhost -> localhost] => (item=jack)

TASK [vpn : Build the client ipsec secret file] ********************************
changed: [localhost -> localhost] => (item=dan)
changed: [localhost -> localhost] => (item=jack)

TASK [vpn : Create the windows check file] *************************************
changed: [localhost -> localhost]

TASK [vpn : Check if the windows check file exists] ****************************
ok: [localhost -> localhost]

TASK [vpn : Build the windows client powershell script] ************************
changed: [localhost -> localhost] => (item=dan)
changed: [localhost -> localhost] => (item=jack)

TASK [vpn : Restrict permissions for the local private directories] ************
changed: [localhost -> localhost] => (item=configs/XXX.XXX.XXX.192)

RUNNING HANDLER [security : restart ssh] ***************************************
changed: [localhost]

RUNNING HANDLER [vpn : restart strongswan] *************************************
changed: [localhost]

RUNNING HANDLER [vpn : daemon-reload] ******************************************
changed: [localhost]

RUNNING HANDLER [vpn : restart iptables] ***************************************
changed: [localhost]

TASK [vpn : strongSwan started] ************************************************
ok: [localhost]

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": [
        [
            "\"#                          Congratulations!                                                                                                                                                                                         #\"",
            "\"#                     Your Algo server is running.                                                                                                                                                                                  #\"",
            "\"#    Config files and certificates are in the ./configs/ director                                                                                                                                                             y.    #\"",
            "\"#              Go to https://whoer.net/ after connecting                                                                                                                                                                            #\"",
            "\"#        and ensure that all your traffic passes through the VPN.                                                                                                                                                                   #\"",
            "\"#               Local DNS resolver XXXXXX              #\"",
            ""
        ],
        "    \"#                The p12 and SSH keys password for new users is 
            #\"\n",
        "    \"#                  The CA key password is XXXXXXXXXXXXXX                                                                                                                                                            
     #\"\n",
        "    "
    ]
}

TASK [Delete the CA key] *******************************************************
skipping: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=74   changed=60   unreachable=0    failed=0

**Comment by dguido** [comment]
It won't give you a shell, that's intended behavior.

**Comment by viperz0r** [comment]
Sorry, end up discovering that was a misconfiguration in browser connection by using verbose flag.
It´s running at 100%

Whole install process was very easy! Thank you.
