### ISSUE TITLE
Unreachable error when running ./algo update-users

### ISSUE THREAD

**Issue by sorzech** [trailofbits/algo#703]
### OS / Environment
DigitalOcean
Ubuntu 16.04.3 x64

### Ansible version
ansible 2.2.0.0

### Version of components from `requirements.txt`
msrestazure
setuptools>=11.3
ansible>=2.1,<2.2.1
dopy==0.3.5
boto>=2.5
boto3
azure==2.0.0rc5
msrest==0.4.1
apache-libcloud
six
pyopenssl
jinja2==2.8

### Summary of the problem
When running ./algo update-users

fatal: [A.B.C.D]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: Permanently added 'A.B.C.D' (ECDSA) to the list of known hosts.\r\nPermission denied (publickey).\r\n", "unreachable": true}

But I am able to ssh into the server with "ssh root@A.B.C.D"

### Steps to reproduce the behavior
Just run ./algo update-users

### The way of deployment (cloud or local)
cloud

### Expected behavior
Succeeds in updating users

### Actual behavior
Fails in setup "UNREACHABLE"

### Full log
Enter the IP address of your server: (or use localhost for local installation)
: A.B.C.D

What user should we use to login on the server? (note: passwordless login required, or ignore if you're deploying to localhost)
[root]: 

Do you want each user to have their own account for SSH tunneling?
[y/N]: y

Enter the public IP address of your server: (IMPORTANT! This IP is used to verify the certificate)
[A.B.C.D]: A.B.C.D

Enter the password for the private CA key:
[pasted values will not be displayed]
: 
PLAY [localhost] ***************************************************************

TASK [Add the server to the vpn-host group] ************************************
changed: [localhost]

TASK [Wait until SSH becomes ready...] *****************************************
ok: [localhost -> localhost]

PLAY [User management] *********************************************************

TASK [setup] *******************************************************************
fatal: [A.B.C.D]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: Permanently added 'A.B.C.D' (ECDSA) to the list of known hosts.\r\nPermission denied (publickey).\r\n", "unreachable": true}

PLAY RECAP *********************************************************************
A.B.C.D            : ok=0    changed=0    unreachable=1    failed=0   
localhost                  : ok=2    changed=1    unreachable=0    failed=0

**Comment by tradosh** [comment]
yes I have the same issue - I tried to leave first entry with empty field and got this:
Enter the IP address of your server: (or use localhost for local installation)
:

What user should we use to login on the server? (note: passwordless login required, or ignore if you're deploying to localhost)
[root]:

Do you want each user to have their own account for SSH tunneling?
[y/N]: y


Enter the public IP address of your server: (IMPORTANT! This IP is used to verify the certificate)
[]: 13.92.99.13

Enter the password for the private CA key:
[pasted values will not be displayed]
:
PLAY [localhost] ***************************************************************

TASK [Add the server to the vpn-host group] ************************************
changed: [localhost]

TASK [Wait until SSH becomes ready...] *****************************************

fatal: [localhost -> localhost]: FAILED! => {"changed": false, "elapsed": 320, "failed": true, "msg": "Timeout when waiting for search string OpenSSH in :22"}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "fail_hint": [
        "Sorry, but something went wrong!",
        "Please check the troubleshooting guide.",
        "https://trailofbits.github.io/algo/troubleshooting.html"
    ]
}

TASK [fail] ********************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Failed as requested from task"}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=1

**Comment by ogreface** [comment]
Seeing this on a new setup, in EC2.

**Comment by dguido** [comment]
You might want to check that your ssh keys are loaded into memory already before running the update-users script.

**Comment by tradosh** [comment]
I'm running this command locally on the server that is acting as the VPN so not sure what more is needed

**Comment by bradleyd** [comment]
I am seeing the same issue with 
```TASK [Wait until SSH becomes ready...] *****************************************
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "elapsed": 320, "failed": true, "msg": "Timeout when waiting for search string OpenSSH in :22"}
```

on update-users.  Any solutions?
