### ISSUE TITLE
Per App VPN Support?

### ISSUE THREAD

**Issue by fridaynext** [trailofbits/algo#705]
### OS / Environment
iOS11.0.3, macOS 10.13

### Ansible version
2.3.2.0

### Summary of the problem
Is it possible to set up per-app VPN (or somehow edit the generated config profiles) so that the VPN will automatically disconnect when Netflix or Spotify is started?

### The way of deployment (cloud or local)
Cloud

**Comment by dguido** [comment]
Not possible, sorry!
