### ISSUE TITLE
.mobileconfigs now require passwords for .p12?

### ISSUE THREAD

**Issue by lgg** [trailofbits/algo#706]
I have 2 servers:
1. algo server installed in March 2017(serv1)
2. algo server installed today(serv2) (following manual installation steps from README.md)

When i'm adding .mobileconfig on iOS from serv1 - it doesn't require password for .p12.
When i'm adding .mobileconfig on iOS(same device) from serv2 - it requires password for .p12.

How i can disable .p12 password require, when installing .mobileconfig files?
Or how i can add this password directly to .mobileconfig file with algo?

Sum up: I want .mobileconfig behavior like in earlier versions(March 2017) without password require for .p12.

**Comment by ohjk** [comment]
+1
im in a similar position.  if you still have master.zip on serv1 you could use that on serv2..

**Comment by lgg** [comment]
It's bad idea, because there are a lot of fixes and new features in new
releases

чт, 26 окт. 2017 г. в 19:28, ohjk <notifications@github.com>:

**Comment by lgg** [comment]
@ohjk It's bad idea, because there are a lot of fixes and new features in new
releases

**Comment by tony199555** [comment]
We should have the option to disable the feature. But embed the password in the .mobileconfig is ridicious... let alone give the support for it.

**Comment by gunph1ld** [comment]
It does require p12 now. Embedded passwords are now deprecated and removed.

**Comment by yosiyuki** [comment]
I'm new user of Algo and facing same problem with this.
Please tell me what is the solution of this problem.

**Comment by antonavy** [comment]
> It does require p12. Embedded passwords are now deprecated and removed.
How do you find a password?

**Comment by lgg** [comment]
@antonavy it's written after running `./algo` or `./algo --update-users`
