### ISSUE TITLE
ERROR! failed at splitting arguments, either an unbalanced jinja2 block or quotes:

### ISSUE THREAD

**Issue by huntsin2** [trailofbits/algo#708]
Please be patient with me, I tried it again.

### OS / Environment

macOS High Sierra v10.13

### Ansible version

how can I tell?

### Summary of the problem
Receiving an error prior to deployment process completion

### Steps to reproduce the behavior
[vpn2.docx](https://github.com/trailofbits/algo/files/1419540/vpn2.docx)

### The way of deployment (cloud or local)

local I believe

### Expected behavior

deployment process complete

### Actual behavior

ERROR! failed at splitting arguments, either an unbalanced jinja2 block or quotes:

**Comment by dguido** [comment]
Please stop filing issues. These are not issues or bugs with Algo. You are not following the directions and it is expectedly failing.

**Comment by huntsin2** [comment]
Can someone please help me with this, or provide me with a resource that has instructions?

**Comment by huntsin2** [comment]
I found that I had an ' in the name of my server that was causing the issue. I took it out and it went through.
