### ISSUE TITLE
Feature Request: simpler installation to convert page visitors to algo users

### ISSUE THREAD

**Issue by sesam** [trailofbits/algo#709]
Case: As a business traveler, I want to use Algo without first reading long instructions.

Idea: make a github pages landing page, detect OS, show platform chooser. Think Skype.com/download

Idea: publish in App stores, package managers etc (PR welcome?)

Idea: look at rubberducky scripts for short stage-loading solutions that make (RAT) installations easier

Idea: create a tag for simplification tasks, and let non-core programmers help and compete on improving the UX

**Comment by sesam** [comment]
Idea: create links to deploy algo integrated solution on a cloud provider, and let the heavy lifting and platform choosing happen in a web browser that can make intelligent guesses about the user's platform and browser. Think https://camlistore.org/launch/

**Comment by dguido** [comment]
https://github.com/trailofbits/algo/issues/196
