### ISSUE TITLE
Linux client documentation is unclear

### ISSUE THREAD

**Issue by ianwalter** [trailofbits/algo#710]
I followed the steps located at https://github.com/trailofbits/algo/blob/master/docs/client-linux.md
on a Debian derivative without any errors, but then what? iOS setup was pretty straightforward but my Linux client doesn't seem to be connected to the VPN. I'm not familiar with strongSwan, ipsec, etc, but if I run `sudo ipsec statusall` the IKE charon daemon is up, there seems to be a connection to my Algo server, and no "Security Associations". I read through the network manager issue linked to in the README but not sure how it all ties in.

**Comment by gunph1ld** [comment]
All information is in [README.md](https://github.com/trailofbits/algo/blob/master/README.md)
