### ISSUE TITLE
Unblocking specific domains

### ISSUE THREAD

**Issue by adamzolotarev** [trailofbits/algo#713]
### OS / Environment

Ubuntu 17

### Ansible version

2.4.1.0

### Summary of the problem
I would like to unblock specific domains (for example, https://analytics.google.com). Could you point me to a some wiki or guide for doing it?

### Steps to reproduce the behavior
Enable ad blocking when installing algo. Connect to algo vpn and go to https://analytics.google.com. The site will not load.

### The way of deployment (cloud or local)
Local

### Expected behavior
The current behavior is expected, but I would like to have an option to modify it for specific domains.

**Comment by adamzolotarev** [comment]
I guess I could remove these domains form /etc/dnsmasq.d/block.hosts.conf. That seems to work. But not sure if you set up some job that would wipe out the changes.

**Comment by dguido** [comment]
There is no method available for managing this feature. You have to trust what is in the provided rulesets to work. They are conservative, but sometimes still over aggressive. If that's not ok, you can either manually change the configuration or disable this feature entirely.
