### ISSUE TITLE
Android - “failed to load private key.”

### ISSUE THREAD

**Issue by Watney** [trailofbits/algo#714]
Hello,

I ran the scripts today successfully on a MacBook. The iOS configuration files work great. I can readily connect on my iPad or Mac

Unfortunately, the Android one fails. I tried re-running the scripts, but it fails the same every time — “failed to load private key.” Here’s a few lines from the log file. Any suggestions? Thanks!!

`
Nov 3 21:22:22 08[CFG] loaded user certificate 'CN=abc1' and private key. `
`Nov  3 21:22:22 08[CFG] loaded CA certificate 'CN=xxx.yyy.zzz.abc'  `
`Nov 3 21:22:22 08[CFG] failed to load private key. 
`

**Comment by ngalayko** [comment]
i have same issue
looks like it because of android 8.1 beta version of OS
what os version do you have?

**Comment by Watney** [comment]
@ngalayko, I'm running the 8.1 beta too. You are on to something

**Comment by ngalayko** [comment]
so if anyone know other app to set up ikev2 vpn on android, it would be great to have a link
i didn't find one

**Comment by owensan** [comment]
I have had the same issue since upgrading to android 8.1 beta.

**Comment by tobiasbrunner** [comment]
It's a [known issue in the Android 8.1 preview](https://issuetracker.google.com/issues/68371442). Claimed to be fixed in internal builds, which hopefully will make it to the public soon.

**Comment by Watney** [comment]
Just installed 8.1 beta 2, and my algo VPN is working again!
