### ISSUE TITLE
Baking Algo AMIs?

### ISSUE THREAD

**Issue by ervoiox** [trailofbits/algo#715]
Hi,

Algo looks very interesting! Thank you for sharing this with the community.

What would be the steps if we wanted to be build a prebaked AMI with Algo already installed? We are primarily interested in this so deploys are immutable and that we can then place Algo in an autoscaling group (min 1 max 1) and get selfhealing. Though perhaps from a security perspective it is better to let the instance die and manually redeploy?

Well anyway, we wouldn't want to bake the users or any keys into the AMI - so they would have to be retrieved in the instance userdata (ie retrieve keys from SSM parameter store / configs from s3).

So I am interested in knowing what files we need to remove from the AMI and then how to regenerate them at instance runtime.

Thanks!

**Comment by dguido** [comment]
Thank for the suggestion. We opted not to publish our own AMIs for increased trust and transparency.
