### ISSUE TITLE
algo setup script failed

### ISSUE THREAD

**Issue by DeDobbeleer** [trailofbits/algo#716]
### OS / Environment

my own debian 9 server

### Summary of the problem

the ./algo setup script failed with the following errors 

TASK [vpn : Disable unneeded plugins] ******************************************
skipping: [localhost] => (item=x509) 
fatal: [localhost]: FAILED! => {"failed": true, "msg": "The conditional check 'item not in strongswan_enabled_plugins and item not in strongswan_additional_plugins' failed. The error was: error while evaluating conditional (item not in strongswan_enabled_plugins and item not in strongswan_additional_plugins): Unable to look up a name or access an attribute in template string ({% if item not in strongswan_enabled_plugins and item not in strongswan_additional_plugins %} True {% else %} False {% endif %}).\nMake sure your variable name does not contain invalid characters like '-': argument of type 'StrictUndefined' is not iterable\n\nThe error appears to have been in '/home/vnc/algo-master/roles/vpn/tasks/ipec_configuration.yml': line 34, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Disable unneeded plugins\n  ^ here\n"}

TASK [vpn : debug] *************************************************************
ok: [localhost] => {
    "fail_hint": [
        "Sorry, but something went wrong!", 
        "Please check the troubleshooting guide.", 
        "https://trailofbits.github.io/algo/troubleshooting.html"
    ]
}

TASK [vpn : fail] **************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Failed as requested from task"}

RUNNING HANDLER [vpn : restart strongswan] *************************************

PLAY RECAP *********************************************************************
localhost                  : ok=60   changed=14   unreachable=0    failed=1   

could help to solve this issue ?

**Comment by gunph1ld** [comment]
Debian is not supported

**Comment by DeDobbeleer** [comment]
OK thank you for your feedback
