### ISSUE TITLE
Profile Installation Failed

### ISSUE THREAD

**Issue by junv** [trailofbits/algo#718]
### OS / Environment

Debian

### Ansible version

2.2.0.0

### Summary of the problem
I copied *.mobileconfig and *.p12 over to Mac and clicked on the mobileconfig file, I get an error message "Profile Installation Failed", according to the troubleshooting guide I must be running a newer OS, but the thing is I'm already on High Sierra. 

### The way of deployment (cloud or local)
local

**Comment by peterjcaulfield** [comment]
Hey @junv how did you fix your issue?

**Comment by peterjcaulfield** [comment]
I fixed my issue. Problem was not using password provided to stdout when setting up the user initially.
