### ISSUE TITLE
EC2: AWS key env vars

### ISSUE THREAD

**Issue by defunctio** [trailofbits/algo#72]
During the refactor, support for AWS ENV variables was removed in favor of prompts only. 

Add support back to load from the appropriate ENV variables if the prompts are left empty.

**Comment by gunph1ld** [comment]
We don't need to use something like environment/variables files. 
If the prompts are left empty we can use Ansible variables with `default` option - http://docs.ansible.com/ansible/playbooks_filters.html#defaulting-undefined-variables

**Comment by defunctio** [comment]
AWS keys are dynamic per end-user and therefor a static default can't be assigned. 

I've made changes on another feature branch that assign a dynamic 'default' from the appropriate environment variables only when the prompts are left undefined.  It is preferred to use ENV variables over config files when storing keys, as they are destroyed after the session ends.

I'll submit a PR and reference this issue at a later time where it can be decided on whether to merge or not.

**Comment by defunctio** [comment]
Turns out Ansible EC2 modules already do this automatically, no need to change anything. Closing the issue.
