### ISSUE TITLE
Algo VPN on Router

### ISSUE THREAD

**Issue by rossmc** [trailofbits/algo#720]
### OS / Environment
MacOSX / AmazonEC2

Any advice on how I can set up an Algo VPN on a router, specifically a Linksy WRT1200ACv2?  Here is a screenshot from where you add in the VPN setting?
<img width="981" alt="screen shot 2017-11-12 at 13 14 37" src="https://user-images.githubusercontent.com/2452991/32699325-9069c0b6-c7ab-11e7-9118-ed1da087dd95.png">

I did not receive a username and password when I set up my algo VPN on AWS, just a the p12 and SSH keys password.

**Comment by gunph1ld** [comment]
Read the docs, please.
[I can't get my router to connect to the Algo server](https://github.com/trailofbits/algo/blob/master/docs/troubleshooting.md#i-cant-get-my-router-to-connect-to-the-algo-server)
