### ISSUE TITLE
EC2 Ansible Install Failed

### ISSUE THREAD

**Issue by aschuhl** [trailofbits/algo#722]
### OS / Environment
EC2

### Ansible version
ansible 2.1.6.0

### Summary of the problem
ansible-playbook deploy.yml -t ec2 -e 'aws_access_key={aws_access_key} aws_secret_key={aws_secret_key} ssh_public_key=~/.ssh/VPNTestKey.pem region=us-west-1 aws_server_name=Ansible' -vvv

### Steps to reproduce the behavior
Clean repo, just ran the above command

### The way of deployment (cloud or local)
cloud

### Expected behavior
I expected it to install Algo

### Actual behavior
It did not

### Full log

> ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.
> 
> The error appears to have been in '/home/{username}/algo/roles/cloud-digitalocean/tasks/main.yml': line 72, column 7, but may
> be elsewhere in the file depending on the exact syntax problem.
> 
> The offending line appears to be:
> 
> 
>     - name: Tag the droplet
>       ^ here
> 
> 
> The error appears to have been in '/home/{username}/algo/roles/cloud-digitalocean/tasks/main.yml': line 72, column 7, but may
> be elsewhere in the file depending on the exact syntax problem.
> 
> The offending line appears to be:
> 
> 
>     - name: Tag the droplet
>       ^ here
> 

So that error occurs when running the command. I did not select digitalocean, so i am not sure why it is checking there. I deleted the the file  '/home/{username}/algo/roles/cloud-digitalocean/tasks/main.yml' and now it fails with: 

> TASK [cloud-ec2 : Populate the dynamic inventory] ******************************
> task path: /home/{username}/algo/roles/cloud-ec2/tasks/main.yml:56
> fatal: [localhost]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'dict object' has no attribute 'public_ip_address'\n\nThe error appears to have been in '/home/{username}/algo/roles/cloud-ec2/tasks/main.yml': line 56, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Populate the dynamic inventory\n      ^ here\n"}
> 
> 

I tried adding to the dynamic inventory, 

> # BEGIN ALGO MANAGED BLOCK
> [algo:children]
> azure
> gce
> local
> ec2
> digitalocean
> # END ALGO MANAGED BLOCK
> [ec2]
> public_ip_address=52.8.119.147

but I still get the same error. Does anyone have any ideas?

**Comment by gunph1ld** [comment]
Ansible 2.1 isn't supported. Follow the README to build a proper environment
