### ISSUE TITLE
Include SSL obfuscation through stunnel and openconnect

### ISSUE THREAD

**Issue by baimafeima** [trailofbits/algo#725]
It looks like Algo does not support SSL obfuscation out-of-the-box. Please add `stunnel` and `openconnect`. SSL obfuscation (next to obfs4) looks like one of the few possibilities to connect from China and fend off DPI inspection.

**Comment by dguido** [comment]
Thanks, but we are not interested in offering this feature! Contrary to anything you have read, it will not evade the GFC by itself.

**Comment by baimafeima** [comment]
@dguido Any other obfuscation techniques you would recommend? Has there anyone been successful in accessing Algo servers from China for a longer period of time? To my knowledge, `stunnel` and `openconnect` are actually working ok, why not add this and make Algo more broadly available?

**Comment by baimafeima** [comment]
@dguido What is your suggestion regarding getting `Algo` to work for use in China then?

**Comment by dguido** [comment]
I'm not sure. I haven't studied the GFC closely enough to recommend a solution.

**Comment by baimafeima** [comment]
@dguido I have and openconnect and stunnel would be an ideal solution and both are well-respected and secure.
