### ISSUE TITLE
Provide list of ethical VPS and cloud providers

### ISSUE THREAD

**Issue by baimafeima** [trailofbits/algo#726]
Amazon, Google, and Microsoft are no-goes as VPS and cloud providers. It does not make sense to set up an Algo server for privacy reasons with companies not respecting privacy. Could you provide a list of `ethical` VPS cloud providers which support Algo installations?

**Comment by dguido** [comment]
Sorry, I feel exactly the opposite. Amazon, Google, Microsoft, and DigitalOcean are the only providers with the security expertise in house to protect your data. I'm not interested in supporting other platforms beyond Amazon Lightsail.

**Comment by baimafeima** [comment]
@dguido What do you think about Linode?

**Comment by dguido** [comment]
Nopeeeeeeeee

**Comment by baimafeima** [comment]
Reasons? :D

**Comment by baimafeima** [comment]
@dguido I'm very curious to know why you would not recommend Linode.
