### ISSUE TITLE
EC2: hosts no longer added to inventory

### ISSUE THREAD

**Issue by defunctio** [trailofbits/algo#73]
Seems during the refactor to roles that EC2 hosts are no longer added to the local inventory. With dynamic inventory not implemented and this being removed there is currently no way to manage users in your VPN inventory.

I've discussed using EC2 dynamic inventory with tagging in the past #30 but doesn't look like it's been implemented yet.

**Comment by defunctio** [comment]
@dguido @gunph1ld Has the usage of the local inventory been abandoned altogether? This doesn't seem to be unique to EC2 as users playbook now uses only the prompts?

I think we should still have some sort local or dynamic inventory management for all providers.

This also brings up the case of managing multiple sets of user credentials across multiple VPN hosts. This should be another issue though.

**Comment by gunph1ld** [comment]
I see no reason to have local dynamic inventory beside of managing multiple sets of user credentials across multiple VPN hosts, but It should be another issue, yes

**Comment by defunctio** [comment]
Without any sort of inventory management users will be required to enter the IP address of each host to do any future changes. When deploying and destroying VPN hosts all the time or managing multiple hosts this seems quite impractical to me.

Maybe it's out of scope of the projects goals, either way I'll let you guys decide on whether to move forwards or close the issue.
