### ISSUE TITLE
Public PKI for server auth

### ISSUE THREAD

**Issue by leonelwilliams** [trailofbits/algo#74]
Some people I spoke with were less than enthused to have to install a root certificate authority on their device (iOS, macOS) in order to connect to my VPN... would it be possible to use the public PKI (such as Let's Encrypt) for validating the server given a DNS name?

**Comment by gunph1ld** [comment]
It is not possible with authentication by certificates (possible by credentials auth only) authentication by credentials (username+password) less secure than authentication by certificates and I think will not be implemented in Algo

**Comment by leonelwilliams** [comment]
Ah right, I've opened #75 for a possible different direction
