### ISSUE TITLE
Azure: Creating virtual network algo_net fails

### ISSUE THREAD

**Issue by rmshaffer** [trailofbits/algo#741]
### OS / Environment
Mac OS 10.13.1

### Ansible version
ansible 2.2.0.0

### Version of components from `requirements.txt`
(env) ryans-mbp:algo ryan$ pip show msrestazure setuptools ansible doby boto boto3 azure msrest apache-libcloud six pyopenssl jinja2
Name: msrestazure
Version: 0.4.17
Summary: AutoRest swagger generator Python client runtime. Azure-specific module.
Home-page: https://github.com/Azure/msrestazure-for-python
Author: Microsoft Corporation
Author-email: azpysdkhelp@microsoft.com
License: MIT License
Location: /Users/ryan/Documents/GitHub/algo/env/lib/python2.7/site-packages
Requires: adal, msrest, keyring

Name: setuptools
Version: 38.2.0
Summary: Easily download, build, install, upgrade, and uninstall Python packages
Home-page: https://github.com/pypa/setuptools
Author: Python Packaging Authority
Author-email: distutils-sig@python.org
License: UNKNOWN
Location: /Users/ryan/Documents/GitHub/algo/env/lib/python2.7/site-packages
Requires: 

Name: ansible
Version: 2.2.0.0
Summary: Radically simple IT automation
Home-page: http://ansible.com/
Author: Ansible, Inc.
Author-email: info@ansible.com
License: GPLv3
Location: /Users/ryan/Documents/GitHub/algo/env/lib/python2.7/site-packages
Requires: setuptools, pycrypto, paramiko, jinja2, PyYAML

Name: boto
Version: 2.48.0
Summary: Amazon Web Services Library
Home-page: https://github.com/boto/boto/
Author: Mitch Garnaat
Author-email: mitch@garnaat.com
License: MIT
Location: /Users/ryan/Documents/GitHub/algo/env/lib/python2.7/site-packages
Requires: 

Name: boto3
Version: 1.4.8
Summary: The AWS SDK for Python
Home-page: https://github.com/boto/boto3
Author: Amazon Web Services
Author-email: UNKNOWN
License: Apache License 2.0
Location: /Users/ryan/Documents/GitHub/algo/env/lib/python2.7/site-packages
Requires: s3transfer, jmespath, botocore

Name: azure
Version: 2.0.0rc5
Summary: Microsoft Azure Client Libraries for Python
Home-page: https://github.com/Azure/azure-sdk-for-python
Author: Microsoft Corporation
Author-email: ptvshelp@microsoft.com
License: MIT License
Location: /Users/ryan/Documents/GitHub/algo/env/lib/python2.7/site-packages
Requires: azure-graphrbac, azure-batch, azure-mgmt, azure-servicebus, azure-servicemanagement-legacy, azure-storage

Name: msrest
Version: 0.4.1
Summary: AutoRest swagger generator Python client runtime.
Home-page: https://github.com/xingwu1/autorest/tree/python/ClientRuntimes/Python/msrest
Author: Microsoft Corporation
Author-email: UNKNOWN
License: MIT License
Location: /Users/ryan/Documents/GitHub/algo/env/lib/python2.7/site-packages
Requires: requests-oauthlib, chardet, certifi, enum34, keyring, isodate, requests

Name: apache-libcloud
Version: 2.2.1
Summary: A standard Python library that abstracts away differences among multiple cloud provider APIs. For more information and documentation, please see http://libcloud.apache.org
Home-page: http://libcloud.apache.org/
Author: Apache Software Foundation
Author-email: dev@libcloud.apache.org
License: Apache License (2.0)
Location: /Users/ryan/Documents/GitHub/algo/env/lib/python2.7/site-packages
Requires: requests

Name: six
Version: 1.11.0
Summary: Python 2 and 3 compatibility utilities
Home-page: http://pypi.python.org/pypi/six/
Author: Benjamin Peterson
Author-email: benjamin@python.org
License: MIT
Location: /Users/ryan/Documents/GitHub/algo/env/lib/python2.7/site-packages
Requires: 

Name: pyOpenSSL
Version: 17.4.0
Summary: Python wrapper module around the OpenSSL library
Home-page: https://pyopenssl.org/
Author: Hynek Schlawack
Author-email: hs@ox.cx
License: Apache License, Version 2.0
Location: /Users/ryan/Documents/GitHub/algo/env/lib/python2.7/site-packages
Requires: cryptography, six

Name: Jinja2
Version: 2.8
Summary: A small but fast and easy to use stand-alone template engine written in pure python.
Home-page: http://jinja.pocoo.org/
Author: Armin Ronacher
Author-email: armin.ronacher@active-4.com
License: BSD
Location: /Users/ryan/Documents/GitHub/algo/env/lib/python2.7/site-packages
Requires: MarkupSafe

### Summary of the problem
Get the following error message during Azure deployment:
TASK [cloud-azure : Create a virtual network] **********************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error creating or updating virtual network algo_net - 409 Client Error: Conflict for url: https://management.azure.com/subscriptions/********/resourceGroups/Algo_westeurope/providers/Microsoft.Network/virtualnetworks/algo_net?api-version=2016-03-30"}

**I was able to fix this by putting quotes around algo_net in `/roles/cloud-azure/tasks/main.yml`, on line 28:**
`        name: "algo_net"`

Once I did that, the full Azure deployment succeeded and my VPN is working.

I got the idea to try this from the following blog post where someone was hitting a similar error: https://reshmeeauckloo.wordpress.com/tag/subscription-is-not-registered-with-nrp/

### Steps to reproduce the behavior
Cloned algo repository, installed prerequisites, and ran `./algo` choosing Azure as hosting provider.

### The way of deployment (cloud or local)
cloud (Azure)

### Expected behavior
Script should work for Azure without any modification.

### Actual behavior
Azure virtual network creation failed until I made that change.

### Full log
(env) ryans-mbp:algo ryan$ ./algo

  What provider would you like to use?
    1. DigitalOcean
    2. Amazon EC2
    3. Microsoft Azure
    4. Google Compute Engine
    5. Install to existing Ubuntu 16.04 server

Enter the number of your desired provider
: 3

Enter your azure secret id (https://github.com/trailofbits/algo/blob/master/docs/cloud-azure.md)
You can skip this step if you want to use your defaults credentials from ~/.azure/credentials
[pasted values will not be displayed]
[...]: 

Enter your azure tenant id (https://github.com/trailofbits/algo/blob/master/docs/cloud-azure.md)
You can skip this step if you want to use your defaults credentials from ~/.azure/credentials
[pasted values will not be displayed]
[...]: 

Enter your azure client id (application id) (https://github.com/trailofbits/algo/blob/master/docs/cloud-azure.md)
You can skip this step if you want to use your defaults credentials from ~/.azure/credentials
[pasted values will not be displayed]
[...]: 

Enter your azure subscription id (https://github.com/trailofbits/algo/blob/master/docs/cloud-azure.md)
You can skip this step if you want to use your defaults credentials from ~/.azure/credentials
[pasted values will not be displayed]
[...]: 

Name the vpn server:
[algo]: 

  What region should the server be located in? (https://azure.microsoft.com/en-us/regions/)
    1.  South Central US
    2.  Central US
    3.  North Europe
    4.  West Europe
    5.  Southeast Asia
    6.  Japan West
    7.  Japan East
    8.  Australia Southeast
    9.  Australia East
    10. Canada Central
    11. West US 2
    12. West Central US
    13. UK South
    14. UK West
    15. West US
    16. Brazil South
    17. Canada East
    18. Central India
    19. East Asia
    20. Germany Central
    21. Germany Northeast
    22. Korea Central
    23. Korea South
    24. North Central US
    25. South India
    26. West India
    27. East US
    28. East US 2

Enter the number of your desired region:
[1]: 4

Do you want macOS/iOS clients to enable "VPN On Demand" when connected to cellular networks?
[y/N]: y

Do you want macOS/iOS clients to enable "VPN On Demand" when connected to Wi-Fi?
[y/N]: y

List the names of trusted Wi-Fi networks (if any) that macOS/iOS clients exclude from using the VPN (e.g., your home network. Comma-separated value, e.g., HomeNet,OfficeWifi,AlgoWiFi)
: HomeWifi

Do you want to install a DNS resolver on this VPN server, to block ads while surfing?
[y/N]: y

Do you want each user to have their own account for SSH tunneling?
[y/N]: y

Do you want to apply operating system security enhancements on the server? (warning: replaces your sshd_config)
[y/N]: y

Do you want the VPN to support Windows 10 or Linux Desktop clients? (enables compatible ciphers and key exchange, less secure)
[y/N]: y

Do you want to retain the CA key? (required to add users in the future, but less secure)
[y/N]: y

PLAY [Configure the server] ****************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Generate the SSH private key] ********************************************
ok: [localhost]

TASK [Generate the SSH public key] *********************************************
ok: [localhost]

TASK [Change mode for the SSH private key] *************************************
ok: [localhost]

TASK [Ensure the dynamic inventory exists] *************************************
ok: [localhost]

TASK [cloud-azure : set_fact] **************************************************
ok: [localhost]

TASK [cloud-azure : Create a resource group] ***********************************
ok: [localhost]

TASK [cloud-azure : Create a virtual network] **********************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error creating or updating virtual network algo_net - 409 Client Error: Conflict for url: https://management.azure.com/subscriptions/********/resourceGroups/Algo_westeurope/providers/Microsoft.Network/virtualnetworks/algo_net?api-version=2016-03-30"}

TASK [cloud-azure : debug] *****************************************************
ok: [localhost] => {
    "fail_hint": [
        "Sorry, but something went wrong!", 
        "Please check the troubleshooting guide.", 
        "https://trailofbits.github.io/algo/troubleshooting.html"
    ]
}

TASK [cloud-azure : fail] ******************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Failed as requested from task"}

PLAY RECAP *********************************************************************
localhost                  : ok=8    changed=0    unreachable=0    failed=1

**Comment by gunph1ld** [comment]
Can't reproduce. Delete all the resources and try again.

**Comment by rmshaffer** [comment]
I did try deleting all the resources once, but it still reproduced. Then I found the workaround to put quotes around "algo_net" and it started working. Maybe somehow unique to my account.
