### ISSUE TITLE
Question about deploying Algo in the Cloud

### ISSUE THREAD

**Issue by PierfrancescoElia** [trailofbits/algo#742]
Hi, Algo is a strong software, that I love.
I will install Argo on one of my private servers.

I only have one question.
Why does Algo want to know which Cloud platform I'm using, and the respective credentials or root keys?

What does Also do with my cloud service provider?

Thanks to all! :)

**Comment by dguido** [comment]
Hey Pierfrancesco,

Algo deploys a fresh virtual machine to your cloud provider. It needs the access keys for your cloud provider so it can start a new server and set it up for you.
