### ISSUE TITLE
Multiple instances with a Floating IP 

### ISSUE THREAD

**Issue by hlummis** [trailofbits/algo#746]
I'm considering extending the deployment code (at least for DigitalOcean) so that users can create multiple Algo servers pointed to by a single Floating IP. For my purposes, I need a high-availability VPN, so I figured that as long as I have to build it for myself, why not contribute to the repo?

I do have a question before I really get going here: how are the certs, keys, etc generated for each user? If I simply change the IP in the DigitalOcean role tasks to the newly generated Floating IP, will the VPN client configs work across the Algo servers (on the condition that all droplets pointed to by the IP are created from an image made by snapshotting the first droplet)?

**Comment by dguido** [comment]
Certificates are tied to the IPs they are created for. If you change the IP of a VPN server after it's been created, then you'll need to regenerate all the client certs too.
