### ISSUE TITLE
Upload SSH Key Task failing while creating a Digital Ocean vpn

### ISSUE THREAD

**Issue by meggle** [trailofbits/algo#747]
### OS / Environment
macOS 10.13

### Ansible version
2.2.0.0

### Version of components from `requirements.txt`
msrestazure: 0.4.18
setuptools: 38.2.3
dopy: 0.3.5
boto: 2.48.0
boto3: 1.4.8
azure: 2.0.0rc5
msrest: 0.4.1
apache-libcloud: 2.2.1
six: 1.11.0
pyopenssl 17.5.0
jinja2: 2.8

### Summary of the problem

TASK [cloud-digitalocean : Upload the SSH key] fails to upload the ssh key, so I cannot complete setting up a digital ocean vpn.

### Steps to reproduce the behavior

  What provider would you like to use?
    1. DigitalOcean
    2. Amazon EC2
    3. Microsoft Azure
    4. Google Compute Engine
    5. Install to existing Ubuntu 16.04 server

Enter the number of your desired provider
: 1

Enter your API token. The token must have read and write permissions (https://cloud.digitalocean.com/settings/api/tokens):
[pasted values will not be displayed]
: 

Name the vpn server:
[algo.local]: 

  What region should the server be located in?
    1.  Amsterdam        (Datacenter 2)
    2.  Amsterdam        (Datacenter 3)
    3.  Frankfurt
    4.  London
    5.  New York         (Datacenter 1)
    6.  New York         (Datacenter 2)
    7.  New York         (Datacenter 3)
    8.  San Francisco    (Datacenter 1)
    9.  San Francisco    (Datacenter 2)
    10. Singapore
    11. Toronto
    12. Bangalore
Enter the number of your desired region:
[7]: 5

Do you want macOS/iOS clients to enable "VPN On Demand" when connected to cellular networks?
[y/N]: N

Do you want macOS/iOS clients to enable "VPN On Demand" when connected to Wi-Fi?
[y/N]: N

Do you want to install a DNS resolver on this VPN server, to block ads while surfing?
[y/N]: y

Do you want each user to have their own account for SSH tunneling?
[y/N]: y

Do you want to apply operating system security enhancements on the server? (warning: replaces your sshd_config)
[y/N]: y

Do you want the VPN to support Windows 10 or Linux Desktop clients? (enables compatible ciphers and key exchange, less secure)
[y/N]: y

Do you want to retain the CA key? (required to add users in the future, but less secure)
[y/N]: y

### The way of deployment (cloud or local)
cloud

### Expected behavior

algo completes the ssh key upload step and continues through the steps.

### Actual behavior

Task fails with an error: The error was: DoError: Key invalid, key should be of the format `type key [comment]`

### Full log

PLAY [Configure the server] ****************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Generate the SSH private key] ********************************************
ok: [localhost]

TASK [Generate the SSH public key] *********************************************
ok: [localhost]

TASK [Change mode for the SSH private key] *************************************
ok: [localhost]

TASK [Ensure the dynamic inventory exists] *************************************
ok: [localhost]

TASK [cloud-digitalocean : Set the DigitalOcean Access Token fact] *************
ok: [localhost]

TASK [cloud-digitalocean : Delete the existing Algo SSH keys] ******************
ok: [localhost]

TASK [cloud-digitalocean : Upload the SSH key] *********************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: DoError: Key invalid, key should be of the format `type key [comment]`
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Key invalid, key should be of the format `type key [comment]`"}

TASK [cloud-digitalocean : debug] **********************************************
ok: [localhost] => {
    "fail_hint": [
        "Sorry, but something went wrong!", 
        "Please check the troubleshooting guide.", 
        "https://trailofbits.github.io/algo/troubleshooting.html"
    ]
}

TASK [cloud-digitalocean : fail] ***********************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Failed as requested from task"}

PLAY RECAP *********************************************************************
localhost                  : ok=8    changed=0    unreachable=0    failed=1

**Comment by shawnyeager** [comment]
Just experienced the exact same problem.

**Comment by gunph1ld** [comment]
Delete `configs/algo.pem.pub` and try again

**Comment by meggle** [comment]
unfortunately, deleted that file and retried with the same result

**Comment by dguido** [comment]
cannot reproduce, sorry!

**Comment by orenka** [comment]
Happens to me too. I tried several solutions but nothing works.
DigitalOcean does not accept Algo's SSH key:

`TASK [cloud-digitalocean : Upload the SSH key] *********************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: DoError: Key invalid, key should be of the format `type key [comment]`
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Key invalid, key should be of the format `type key [comment]`"}

TASK [cloud-digitalocean : debug] **********************************************
ok: [localhost] => {
    "fail_hint": [
        "Sorry, but something went wrong!",
        "Please check the troubleshooting guide.",
        "https://trailofbits.github.io/algo/troubleshooting.html"
    ]
}

TASK [cloud-digitalocean : fail] ***********************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Failed as requested from task"}

PLAY RECAP *********************************************************************
localhost                  : ok=8    changed=0    unreachable=0    failed=1
`

I'm runnig Ubuntu on WSL (Windows). 
Does anyone have a solution?

**Comment by jackivanov** [comment]
Duplicate
Covered here https://github.com/trailofbits/algo/issues/891
