### ISSUE TITLE
Windows 10 Client Policy Match error.

### ISSUE THREAD

**Issue by Lars-bs** [trailofbits/algo#748]
The algo deployment I am referencing is using the code from master at the date of this Issue creation. The deployment is working on android.

OS / Environment

Windows 10
Version 16299
OS Build Version 10.0.16299

Summary of the problem

Deployed the most recent version of Algo to digital ocean (using local deploy) and i receive Policy Match error on windows 10

Steps to reproduce the behavior

Deploy aglo on Digital Ocean using local deploy, follow the instructions for Windows on the Algo README, then try to connect to the VPN on Windows 10.

The way of deployment (cloud or local)
local

Expected behavior

When I click "Connect" to VPN I expect a successful connection.

Actual behavior

When I click "Connect" I receive "Policy Match" error and 
the following windows event log is created: 
"user SYSTEM dialed a connection named Algo VPN <ip> IKEv2 which has failed. The error code returned on failure is 13868."

**Comment by 3cho529** [comment]
Having the same issue as well.

**Comment by UnclePotatoDev** [comment]
Same😢 (But emoji keyboard still works)

**Comment by 3cho529** [comment]
I re-installed it and there was an option to enable it for windows 10 - something about enabling a weaker encryption algorithm. Then it worked like a charm :).

**Comment by dguido** [comment]
Yup! Most people forget to check that option, then try to get it working on Windows.

**Comment by Lars-bs** [comment]
I did check that option, however i still get the policy match error.
![image](https://user-images.githubusercontent.com/18347384/33827667-63067f04-de69-11e7-9392-acb6acd2b242.png)

**Comment by sarilouis** [comment]
This is still an issue for me. I have no idea how to go about troubleshooting or fixing it. To note: it was working fine but stopped working overnight. It still works when I connect from iOS (Windows 10 is what's not working). I understand it might be something I installed and not Algo's fault (since it's working on iOS), but is there a way to troubleshoot what's happening in the handshake to see how I can make it match?

**Comment by dialbat** [comment]
Same issue after successful setup. powershell script installed with no problems, but get Policy match error. Also did have Win10 support on Y.

**Comment by tharri** [comment]
I'm having the same problem on a fresh Algo install on Amazon EC2. I, too, selected Y for the Windows 10 support. Note that I am using the Spring 2018 Creator's Update of Windows.

**Comment by trochdewei** [comment]
Same issue on Windows 10 Mobile

**Comment by ccsalway** [comment]
Could be the certificate missing the ExtendedKeyUsage ikeIntermediate (1.3.6.1.5.5.8.2.2)

**Comment by Zeushn** [comment]
same issue at the moment, with Windows 10 Pro V .1809 OS Build 17763.195. It works in all my other clients (android, Mac OS, IOS) but stopped working in Windows 10. I have tried to reinstall the VPN connection, erased the driver for the WAN miniport IKEv2, rebuild a new server in a different location in Digital ocean. same results.
