### ISSUE TITLE
Unable to connect to my Webserver after Algo VPN installation

### ISSUE THREAD

**Issue by TDahmen** [trailofbits/algo#751]
Hi,

I successfully installed Algo VPN on my Ubuntu server, everything works well.
But I have an Apache web server running, and now when I type my server's IP address on a browser the connection fails.

How can I fix this ?

Thank you very much in advance

**Comment by dguido** [comment]
It’s probably on your local network. There’s a toggle for allowing that behavior in the config.cfg file when you deploy.
