### ISSUE TITLE
Can't connect to Algo restored from image

### ISSUE THREAD

**Issue by njnrn** [trailofbits/algo#756]
### OS / Environment

Digital Ocean : SG and NY 
Client: Windows 10 and Ubuntu 16.04 Linux 

### Ansible version

Droplet is down. Not able to view.
Recent. Downloaded in Dec 2017.

### Version of components from `requirements.txt`

Droplet is down. Not able to view.
Recent version. Downloaded in Dec 2017.

### Summary of the problem
Worked fine after following instructions. Took snapshot and deleted droplet. Restored droplet from snapshot after days. Digital ocean gave new IP. Change IP of server in client config, but connection fails with IKE auth failed error.

How to handle change in Algo server IP?

### Steps to reproduce the behavior
Change public IP of algo server. No longer able to connect to VPN.

**Comment by gunph1ld** [comment]
It's better to redeploy server from scratch
