### ISSUE TITLE
Plans to implement this on a serverless infrastructure?

### ISSUE THREAD

**Issue by dmonay** [trailofbits/algo#757]
An Algo server on an EC2 instance runs 720 hours a month, even though one may connect to it for one hour a day. Having an implementation that ran on Lambda/Azure Functions would translate to significant cost savings.

Has anyone scoped out the work required to make this happen? Are there fundamental challenges to this?

**Comment by dguido** [comment]
Lambdas only execute small Python functions, not persistent VPN servers. Not possible with current tech, sorry!
