### ISSUE TITLE
Add a powershell run script for Windows

### ISSUE THREAD

**Issue by dguido** [trailofbits/algo#76]
As far as I know, algo still runs on Windows if you know how to install Ansible to get it going. We should make a PowerShell script that is identical to the included shell script.

**Comment by gunph1ld** [comment]
http://docs.ansible.com/ansible/intro_installation.html#control-machine-requirements
**Control Machine Requirements**
Currently Ansible can be run from any machine with Python 2.6 or 2.7 installed (**Windows isn’t supported for the control machine**).
