### ISSUE TITLE
Unable to create VPN Server on AWS C5 Large Instance.

### ISSUE THREAD

**Issue by pravin005** [trailofbits/algo#761]
@jrmalladi @dguido 

### OS / Environment

On my MacBook Pro

### Ansible version

./env/bin/ansible --version
ansible 2.2.0.0
  config file = /Users/pravin/vimana/algo/algo2/ansible.cfg
  configured module search path = Default w/o overrides

### Version of components from `requirements.txt`

setuptools>=11.3
ansible>=2.1,<2.2.1
dopy==0.3.5
boto>=2.5
boto3
azure==2.0.0rc5
msrest==0.4.1
apache-libcloud
six
pyopenssl
jinja2==2.8

### Summary of the problem 
Trying to create Algo on AWS instance C5 Large in Oregon 
1) Downloaded Algo from git and modified the config.cfg as below
ec2:
    size: c5.large
    image:
      name: "ubuntu-xenial-16.04" # ubuntu-xenial-16.04 / ubuntu-zesty-17.04
      owner: "099720109477"
2) Executed Algo script from my laptop trying to create AWS instance C5 Large in Oregon location
3) It fails to get created as SSH authentication fails with the error as below:

TASK [Check the system] ********************************************************
fatal: [34.216.170.47]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: Permanently added '34.216.170.47' (ECDSA) to the list of known hosts.\r\nubuntu@34.216.170.47: Permission denied (publickey).\r\n", "unreachable": true}

PLAY RECAP *********************************************************************
34.216.170.47              : ok=0    changed=0    unreachable=1    failed=0   
localhost                  : ok=19   changed=8    unreachable=0    failed=0

Please look at steps below for additional information and complete execution

### Steps to reproduce the behavior
Pravins-MBP:algo2 pravin$ ./algo

  What provider would you like to use?
    1. DigitalOcean
    2. Amazon EC2
    3. Microsoft Azure
    4. Google Compute Engine
    5. Install to existing Ubuntu 16.04 server

Enter the number of your desired provider
: 2

Enter your aws_access_key (http://docs.aws.amazon.com/general/latest/gr/managing-aws-access-keys.html)
Note: Make sure to use an IAM user with an acceptable policy attached (see https://github.com/trailofbits/algo/blob/master/docs/deploy-from-ansible.md).
[pasted values will not be displayed]
[AKIA...]: 

Enter your aws_secret_key (http://docs.aws.amazon.com/general/latest/gr/managing-aws-access-keys.html)
[pasted values will not be displayed]
[ABCD...]: 

Name the vpn server:
[algo]: algo-vpn-Oregon-C5L

  What region should the server be located in?
    1.   us-east-1           US East (N. Virginia)
    2.   us-east-2           US East (Ohio)
    3.   us-west-1           US West (N. California)
    4.   us-west-2           US West (Oregon)
    5.   ap-south-1          Asia Pacific (Mumbai)
    6.   ap-northeast-2      Asia Pacific (Seoul)
    7.   ap-southeast-1      Asia Pacific (Singapore)
    8.   ap-southeast-2      Asia Pacific (Sydney)
    9.   ap-northeast-1      Asia Pacific (Tokyo)
    10.  eu-central-1        EU (Frankfurt)
    11.  eu-west-1           EU (Ireland)
    12.  eu-west-2           EU (London)
    13.  ca-central-1        Canada (Central)
    14.  sa-east-1           São Paulo
Enter the number of your desired region:
[1]: 4

Do you want macOS/iOS clients to enable "VPN On Demand" when connected to cellular networks?
[y/N]: y

Do you want macOS/iOS clients to enable "VPN On Demand" when connected to Wi-Fi?
[y/N]: y

List the names of trusted Wi-Fi networks (if any) that macOS/iOS clients exclude from using the VPN (e.g., your home network. Comma-separated value, e.g., HomeNet,OfficeWifi,AlgoWiFi)
: 

Do you want to install a DNS resolver on this VPN server, to block ads while surfing?
[y/N]: 

Do you want each user to have their own account for SSH tunneling?
[y/N]: y

Do you want to apply operating system security enhancements on the server? (warning: replaces your sshd_config)
[y/N]: 

Do you want the VPN to support Windows 10 or Linux Desktop clients? (enables compatible ciphers and key exchange, less secure)
[y/N]: 

Do you want to retain the CA key? (required to add users in the future, but less secure)
[y/N]: 

PLAY [Configure the server] ****************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Generate the SSH private key] ********************************************
changed: [localhost]

TASK [Generate the SSH public key] *********************************************
ok: [localhost]

TASK [Change mode for the SSH private key] *************************************
ok: [localhost]

TASK [Ensure the dynamic inventory exists] *************************************
changed: [localhost]

TASK [cloud-ec2 : set_fact] ****************************************************
ok: [localhost]

TASK [cloud-ec2 : Locate official AMI for region] ******************************
ok: [localhost]

TASK [cloud-ec2 : set_fact] ****************************************************
ok: [localhost]

TASK [cloud-ec2 : Make a cloudformation template] ******************************
changed: [localhost]

TASK [cloud-ec2 : Deploy the template] *****************************************
changed: [localhost]

TASK [cloud-ec2 : Add new instance to host group] ******************************
changed: [localhost]

TASK [cloud-ec2 : set_fact] ****************************************************
ok: [localhost]

TASK [cloud-ec2 : Get EC2 instances] *******************************************
ok: [localhost]

TASK [cloud-ec2 : Ensure the group ec2 exists in the dynamic inventory file] ***
changed: [localhost]

TASK [cloud-ec2 : Populate the dynamic inventory] ******************************
changed: [localhost] => (item={u'kernel': None, u'instance_profile': None, u'root_device_type': u'ebs', u'private_dns_name': u'ip-172-16-254-172.us-west-2.compute.internal', u'spot_instance_request_id': None, u'source_destination_check': u'true', u'id': u'i-0b1d20d56606ddedf', u'ebs_optimized': False, u'state': u'running', u'client_token': u'algo-EC2In-OSUAL288OW5B', u'virtualization_type': u'hvm', u'ramdisk': None, u'public_ip_address': u'34.216.170.47', u'block_device_mapping': [{u'status': u'attached', u'volume_id': u'vol-0109ea6c519a4705d', u'delete_on_termination': True, u'attach_time': u'2017-12-25T23:31:42.000Z', u'device_name': u'/dev/sda1'}], u'key_name': None, u'interfaces': [{u'id': u'eni-ba696188', u'mac_address': u'06:6e:7c:cf:a7:e8'}], u'image_id': u'ami-a2e544da', u'groups': [{u'id': u'sg-cadaabb6', u'name': u'algo-vpn-Oregon-C5L-InstanceSecurityGroup-1KQQXQCX0I72D'}], u'public_dns_name': u'ec2-34-216-170-47.us-west-2.compute.amazonaws.com', u'requester_id': None, u'tags': {u'Environment': u'Algo', u'aws:cloudformation:stack-name': u'algo-vpn-Oregon-C5L', u'aws:cloudformation:stack-id': u'arn:aws:cloudformation:us-west-2:616569460123:stack/algo-vpn-Oregon-C5L/933dc020-e9cb-11e7-a369-500c32c86c29', u'Name': u'Algo', u'aws:cloudformation:logical-id': u'EC2Instance'}, u'monitoring_state': u'disabled', u'placement': {u'tenancy': u'default', u'zone': u'us-west-2b'}, u'ami_launch_index': u'0', u'hypervisor': u'xen', u'region': u'us-west-2', u'launch_time': u'2017-12-25T23:31:41.000Z', u'persistent': False, u'architecture': u'x86_64', u'private_ip_address': u'172.16.254.172', u'vpc_id': u'vpc-4911e930'})

TASK [Wait until SSH becomes ready...] *****************************************
ok: [localhost]

TASK [A short pause, in order to be sure the instance is ready] ****************
Pausing for 20 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)
ok: [localhost]

TASK [Ensure the local ssh directory is exist] *********************************
ok: [localhost]

TASK [Copy the algo ssh key to the local ssh directory] ************************
changed: [localhost]

PLAY [Configure the server and install required software] **********************

TASK [Check the system] ********************************************************
fatal: [34.216.170.47]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: Permanently added '34.216.170.47' (ECDSA) to the list of known hosts.\r\nubuntu@34.216.170.47: Permission denied (publickey).\r\n", "unreachable": true}

PLAY RECAP *********************************************************************
34.216.170.47              : ok=0    changed=0    unreachable=1    failed=0   
localhost                  : ok=19   changed=8    unreachable=0    failed=0   

Pravins-MBP:algo2 pravin$ 

### The way of deployment (cloud or local)
AWS Cloud

### Expected behavior
This works as per the default configuration t2.micro and t2.large

**Comment by dguido** [comment]
Duplicate:

https://github.com/trailofbits/algo/issues/429
https://github.com/trailofbits/algo/issues/268
https://github.com/trailofbits/algo/issues/126

**Comment by jrmalladi** [comment]
Dan, This seems to be a different issue, I have tried the mentioned  fixes in the closed PRs.
1. Increased the pause and delay to 300 sec in playbooks/post.yml
2. Redeploy multiple times
3. checked the pem file permissions.

Waited for over 5 minutes still, ssh to the C5.large instance is failing. It almost feels that the 

public key is not copied from the CFN script. I cannot ssh to the instance so i cannot verify this?

Any addition steps i can try ?

**Comment by jrmalladi** [comment]
Another update - 
I added a KeyName to the stack.yml.j2 just so i can login to the server and noticed that the Instance created is an Amazon Linux Instance. So far all other instances were ubuntu. Could this be the issue ? Looks like algo assumes an ubuntu AMI.

Sadas-MacBook:algo.c5 sadamalladi$ git diff roles/cloud-ec2/templates/stack.yml.j2
diff --git a/roles/cloud-ec2/templates/stack.yml.j2 b/roles/cloud-ec2/templates/stack.yml.j2
index 694386f..e9e3dd1 100644
--- a/roles/cloud-ec2/templates/stack.yml.j2
+++ b/roles/cloud-ec2/templates/stack.yml.j2
@@ -158,6 +158,7 @@ Resources:
       SecurityGroupIds:
         - Ref: InstanceSecurityGroup
       ImageId: {{ ami_image }}
+      KeyName: sada-us-west-2
       SubnetId: !Ref Subnet
       Ipv6AddressCount: 1
       UserData:


Sadas-MacBook:algo.c5 sadamalladi$ ssh -i ~/.ssh/sada-us-west-2.pem ec2-user@52.11.36.157
Last login: Wed Jan  3 01:06:22 2018 from 67.21.0.108

       __|  __|_  )
       _|  (     /   Amazon Linux AMI
      ___|\___|___|

https://aws.amazon.com/amazon-linux-ami/2016.03-release-notes/
21 package(s) needed for security, out of 102 available
Run "sudo yum update" to apply all updates.
Amazon Linux version 2017.09 is available.
[ec2-user@ip-172-31-41-198 ~]$

**Comment by jrmalladi** [comment]
Final update- Resolved the issue, here are my observations for the community.
Made the following changes to roles/cloud-ec2/templates/stack.yml.j2
1. Hardcoded the AMI to an ubuntu image in oregon region 
2. Modified the eth0 to ens5 (Looks like the New Instances are not getting eth0 anymore)

Sadas-MacBook:algo.c5 sadamalladi$ git diff roles/cloud-ec2/templates/stack.yml.j2
diff --git a/roles/cloud-ec2/templates/stack.yml.j2 b/roles/cloud-ec2/templates/stack.yml.j2
index 694386f..b4376ae 100644
--- a/roles/cloud-ec2/templates/stack.yml.j2
+++ b/roles/cloud-ec2/templates/stack.yml.j2
@@ -157,7 +157,7 @@ Resources:
       InstanceInitiatedShutdownBehavior: terminate
       SecurityGroupIds:
         - Ref: InstanceSecurityGroup
-      ImageId: {{ ami_image }}
**+      ImageId: ami-0def3275**
       SubnetId: !Ref Subnet
       Ipv6AddressCount: 1
       UserData:
@@ -167,11 +167,11 @@ Resources:
             # http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/vpc-migrate-ipv6.html
             # https://bugs.launchpad.net/ubuntu/+source/ifupdown/+bug/1013597
             cat <<EOF > /etc/network/interfaces.d/60-default-with-ipv6.cfg
-            iface eth0 inet6 dhcp
**+            iface ens5 inet6 dhcp**
                 up sysctl net.ipv6.conf.\$IFACE.accept_ra=2
                 pre-down ip link set dev \$IFACE up
             EOF
-            ifdown eth0; ifup eth0
**+            ifdown ens5; ifup ens5**
             dhclient -6
             apt-get update
