### ISSUE TITLE
Unable to setup Algo Server

### ISSUE THREAD

**Issue by xarlamp** [trailofbits/algo#763]
### OS / Environment

Windows 10 x64 + Ubuntu 16.04 via Linux subsystem for Windows 10

### Ansible version

Name: ansible
Version: 2.2.0.0

### Version of components from `requirements.txt`

Name: msrestazure
Version: 0.4.19

Name: setuptools
Version: 38.2.5

Name: dopy
Version: 0.3.5

Name: boto
Version: 2.48.0

Name: azure
Version: 2.0.0rc5

Name: msrest
Version: 0.4.1

Name: apache-libcloud
Version: 2.2.1

Name: six
Version: 1.11.0

Name: pyOpenSSL
Version: 17.5.0

Name: Jinja2
Version: 2.8

### Summary of the problem
I tryed to setup Algo Server 2 times from different OS, from different computers and only got error

### Steps to reproduce the behavior
Just using "Deploy the Algo Server" instruction

### The way of deployment (cloud or local)
Cloud

### Expected behavior
Congratulations!                      
Your Algo server is running. 

### Actual behavior
ERROR! failed at splitting arguments, either an unbalanced jinja2 block or quotes: do_access_token=1737444ddb5d39c2e402bb4b14061c399beae030962a42ecbe71196d51d7c56b do_server_name=xarlamp's VPN do_region=fra1 Win10_Enabled=Y

### Full log

(env) xarlamp_UNIX@DESKTOP-AV8F7M3:~/algo$ ./algo

  What provider would you like to use?
    1. DigitalOcean
    2. Amazon EC2
    3. Microsoft Azure
    4. Google Compute Engine
    5. Install to existing Ubuntu 16.04 server

Enter the number of your desired provider
: 1

Enter your API token. The token must have read and write permissions (https://cloud.digitalocean.com/settings/api/tokens):
[pasted values will not be displayed]
:

Name the vpn server:
[algo.local]: xarlamp's VPN

  What region should the server be located in?
    1.  Amsterdam        (Datacenter 2)
    2.  Amsterdam        (Datacenter 3)
    3.  Frankfurt
    4.  London
    5.  New York         (Datacenter 1)
    6.  New York         (Datacenter 2)
    7.  New York         (Datacenter 3)
    8.  San Francisco    (Datacenter 1)
    9.  San Francisco    (Datacenter 2)
    10. Singapore
    11. Toronto
    12. Bangalore
Enter the number of your desired region:
[7]: 3

Do you want macOS/iOS clients to enable "VPN On Demand" when connected to cellular networks?
[y/N]: n

Do you want macOS/iOS clients to enable "VPN On Demand" when connected to Wi-Fi?
[y/N]: n

Do you want to install a DNS resolver on this VPN server, to block ads while surfing?
[y/N]: y

Do you want each user to have their own account for SSH tunneling?
[y/N]: n

Do you want to apply operating system security enhancements on the server? (warning: replaces your sshd_config)
[y/N]: n

Do you want the VPN to support Windows 10 or Linux Desktop clients? (enables compatible ciphers and key exchange, less secure)
[y/N]: y

Do you want to retain the CA key? (required to add users in the future, but less secure)
[y/N]: y
ERROR! failed at splitting arguments, either an unbalanced jinja2 block or quotes: do_access_token=1737444ddb5d39c2e402bb4b14061c399beae030962a42ecbe71196d51d7c56b do_server_name=xarlamp's VPN do_region=fra1 Win10_Enabled=Y

**Comment by dguido** [comment]
You probably want to revoke that access token from your digital ocean account.

**Comment by davidemyers** [comment]
Try it without any apostrophes or spaces in the host name.

**Comment by xarlamp** [comment]
@dguido I deleted old API after error messages.
@davidemyers yeah, problem was really - '
Thank you guys for your help.

Problem solved.

**Comment by xarlamp** [comment]
Another problem, server probably working. But somewhy i cant run windows client. 
I trying to use command from instruction powershell -executionpolicy bypass -file .\windows_xarlamp.ps1 Add

But it asking PFX password, which idk. How i can get it?

PS C:\VPN Settings> powershell -executionpolicy bypass -file .\windows_xarlamp.ps1 Add
Введите пароль PFX:
CertUtil: -importPFX команда НЕ ВЫПОЛНЕНА: 0x80070056 (WIN32: 86 ERROR_INVALID_PASSWORD)
CertUtil: Сетевой пароль указан неверно.
Add-VpnConnection :  This VPN connection has already been created. Specify a different VPN profile name. : Невозможно с
оздать файл, так как он уже существует.
C:\VPN Settings\windows_xarlamp.ps1:4 знак:3
+   Add-VpnConnection -name "Algo VPN 46.101.171.57 IKEv2" -ServerAddre ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceExists: (Algo VPN 46.101.171.57 IKEv2:root/Microsoft/...S_VpnConnection) [Add-Vp
   nConnection], CimException
    + FullyQualifiedErrorId : WIN32 183,Add-VpnConnection

PS C:\VPN Settings>

**Comment by ilyaglow** [comment]
Password is printed out to screen after the install is complete
