### ISSUE TITLE
Ubuntu 17.10 Client Not Connecting

### ISSUE THREAD

**Issue by KennyStier61** [trailofbits/algo#764]
### OS / Environment
Server: Ubuntu Server 16.04 in DigitalOcean
Client: Ubuntu 17.10 using Network Manager and network-manager-strongswan
Network Manager version 1.8.4-1ubuntu3
StrongSwan Network Manager version 1.4.2-1 

### Summary of the problem
After installing the network-manager-strongswan package, I followed the Gnome instructions at the bottom of this document (https://github.com/trailofbits/algo/blob/master/docs/client-linux.md).
After finding the entering in my details, I could not get the client to connect. I use the server on my Android phone frequently, and it works great.

### Steps to reproduce the behavior
After deploying...
Install StrongSwan plugin for Network Manager `sudo apt install network-manager-strongswan`
Follow the instructions using the correct keys (under Network Manager Configuration (https://github.com/trailofbits/algo/blob/master/docs/client-linux.md)).
![screenshot from 2017-12-29 11-37-14](https://user-images.githubusercontent.com/4749568/34441960-008d3322-ec8d-11e7-9a25-ae08a8d5a87b.png)
Hit Apply, turn it on

### Expected behavior
It connects to the server

### Actual behavior
![screenshot from 2017-12-29 11-43-12](https://user-images.githubusercontent.com/4749568/34442050-92118faa-ec8d-11e7-9a58-95ab1dee2d43.png)
"Connection Failed" error

### Log
Here's my network-manager log, with the server IP replaced to 1.2.3.4
https://pastebin.ubuntu.com/26279095/

**Comment by dguido** [comment]
The important line is here:

```Dec 29 11:26:10 mtdev-OptiPlex-790 charon-nm[6813]: 08[IKE] received NO_PROPOSAL_CHOSEN notify, no CHILD_SA built```

Maybe it's a cipher mismatch on the ESP handshake? You should probably grab logs from the server to verify.

**Comment by KennyStier61** [comment]
Here's my server log
https://pastebin.ubuntu.com/26283012/
Server IP replaced to 1.2.3.4
Client IP replaced to 199.199.199.199

From what I'm seeing, they can't agree during the handshake...

`no acceptable ENCRYPTION_ALGORITHM found`

`no acceptable PSEUDO_RANDOM_FUNCTION found`

`no acceptable proposal found`

Any ideas on a cause or solution?

**Comment by KennyStier61** [comment]
*bump* @dguido 
If you could check out my server logs when time permits, it would be much appreciated

**Comment by gunph1ld** [comment]
The answer is here, it doesn't seem you configured the right ciphers
```
Dec 30 04:04:14 fs-algo-1 charon[7971]: 14[CFG] received proposals: ESP:AES_CBC_128/AES_CBC_192/AES_CBC_256/3DES_CBC/BLOWFISH_CBC_256/HMAC_SHA2_256_128/HMAC_SHA2_384_192/HMAC_SHA2_512_256/HMAC_SHA1_96/AES_XCBC_96/HMAC_MD5_96/NO_EXT_SEQ
Dec 30 04:04:14 fs-algo-1 charon[7971]: 14[CFG] configured proposals: ESP:AES_GCM_16_128/ECP_256/NO_EXT_SEQ, ESP:AES_CBC_128/HMAC_SHA2_512_256/PRF_HMAC_SHA2_512/ECP_256/NO_EXT_SEQ
Dec 30 04:04:14 fs-algo-1 charon[7971]: 14[IKE] no acceptable proposal found
```

**Comment by treizebee** [comment]
@gunph1ld How would one reconfigure the cipher proposals? 
I'm having the exact same issue in that no proposal is accepted for the ESP ciphers that were provided in the [client-linux.md](https://github.com/trailofbits/algo/blob/master/docs/client-linux.md) instructions (IKE gets matched fine).

`[CFG] received proposals: ESP:AES_CBC_128/AES_CBC_192/AES_CBC_256/3DES_CBC/BLOWFISH_CBC_256/HMAC_SHA2_256_128/HMAC_SHA2_384_192/HMAC_SHA2_512_256/HMAC_SHA1_96/AES_XCBC_96/HMAC_MD5_96/NO_EXT_SEQ`
`[CFG] configured proposals: ESP:AES_GCM_16_128/ECP_256/NO_EXT_SEQ, ESP:AES_CBC_128/HMAC_SHA2_512_256/PRF_HMAC_SHA2_512/ECP_256/NO_EXT_SEQ`
`[IKE] no acceptable proposal found`

**Comment by KennyStier61** [comment]
I have found a solution! I SSH'ed into my Algo server and upgraded it to Ubuntu 17.10 (which has a newer version of strongswan in its repos) and now I can connect via Network Manager just fine.

**Comment by treizebee** [comment]
@KennyStier61 That did it! Thanks, that was a frustrating issue to troubleshoot.
