### ISSUE TITLE
Timeout when waiting for search string OpenSSH in XXX

### ISSUE THREAD

**Issue by aquiveal** [trailofbits/algo#765]
aquiveal@Agorenc:~/algo-master/algo-master$ sudo ./algo
[sudo] password for aquiveal: 

  What provider would you like to use?
    1. DigitalOcean
    2. Amazon EC2
    3. Microsoft Azure
    4. Google Compute Engine
    5. Install to existing Ubuntu 16.04 server

Enter the number of your desired provider
: 2

Enter your aws_access_key (http://docs.aws.amazon.com/general/latest/gr/managing-aws-access-keys.html)
Note: Make sure to use an IAM user with an acceptable policy attached (see https://github.com/trailofbits/algo/blob/master/docs/deploy-from-ansible.md).
[pasted values will not be displayed]
[AKIA...]: 

Enter your aws_secret_key (http://docs.aws.amazon.com/general/latest/gr/managing-aws-access-keys.html)
[pasted values will not be displayed]
[ABCD...]: 

Name the vpn server:
[algo]: Home-VPN

  What region should the server be located in?
    1.   us-east-1           US East (N. Virginia)
    2.   us-east-2           US East (Ohio)
    3.   us-west-1           US West (N. California)
    4.   us-west-2           US West (Oregon)
    5.   ap-south-1          Asia Pacific (Mumbai)
    6.   ap-northeast-2      Asia Pacific (Seoul)
    7.   ap-southeast-1      Asia Pacific (Singapore)
    8.   ap-southeast-2      Asia Pacific (Sydney)
    9.   ap-northeast-1      Asia Pacific (Tokyo)
    10.  eu-central-1        EU (Frankfurt)
    11.  eu-west-1           EU (Ireland)
    12.  eu-west-2           EU (London)
    13.  ca-central-1        Canada (Central)
    14.  sa-east-1           São Paulo
Enter the number of your desired region:
[1]: 2

Do you want macOS/iOS clients to enable "VPN On Demand" when connected to cellular networks?
[y/N]: n

Do you want macOS/iOS clients to enable "VPN On Demand" when connected to Wi-Fi?
[y/N]: n

Do you want to install a DNS resolver on this VPN server, to block ads while surfing?
[y/N]: y

Do you want each user to have their own account for SSH tunneling?
[y/N]: y

Do you want to apply operating system security enhancements on the server? (warning: replaces your sshd_config)
[y/N]: y

Do you want the VPN to support Windows 10 or Linux Desktop clients? (enables compatible ciphers and key exchange, less secure)
[y/N]: y

Do you want to retain the CA key? (required to add users in the future, but less secure)
[y/N]: n

PLAY [Configure the server] ****************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Generate the SSH private key] ********************************************
changed: [localhost]

TASK [Generate the SSH public key] *********************************************
ok: [localhost]

TASK [Change mode for the SSH private key] *************************************
ok: [localhost]

TASK [Ensure the dynamic inventory exists] *************************************
changed: [localhost]

TASK [cloud-ec2 : set_fact] ****************************************************
ok: [localhost]

TASK [cloud-ec2 : Locate official AMI for region] ******************************
ok: [localhost]

TASK [cloud-ec2 : set_fact] ****************************************************
ok: [localhost]

TASK [cloud-ec2 : Make a cloudformation template] ******************************
changed: [localhost]

TASK [cloud-ec2 : Deploy the template] *****************************************
changed: [localhost]

TASK [cloud-ec2 : Add new instance to host group] ******************************
changed: [localhost]

TASK [cloud-ec2 : set_fact] ****************************************************
ok: [localhost]

TASK [cloud-ec2 : Get EC2 instances] *******************************************
ok: [localhost]

TASK [cloud-ec2 : Ensure the group ec2 exists in the dynamic inventory file] ***
changed: [localhost]

TASK [cloud-ec2 : Populate the dynamic inventory] ******************************

TASK [Wait until SSH becomes ready...] *****************************************
fatal: [localhost]: FAILED! => {"changed": false, "elapsed": 321, "failed": true, "msg": "Timeout when waiting for search string OpenSSH in XXX"}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "fail_hint": [
        "Sorry, but something went wrong!", 
        "Please check the troubleshooting guide.", 
        "https://trailofbits.github.io/algo/troubleshooting.html"
    ]
}

TASK [fail] ********************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Failed as requested from task"}

PLAY RECAP *********************************************************************
localhost                  : ok=15   changed=6    unreachable=0    failed=1   

(env)

**Comment by dguido** [comment]
Just try it again. There are variances between EC2 startup times that can cause this to fail.

**Comment by aquiveal** [comment]
Did it multiple times.

**Comment by Paradoxify** [comment]
I'm getting the same thing but this is for Ubuntu 18.04.1 LTS WSL on Windows 10 Pro clean installation.

**Comment by lawzeus** [comment]
hi , 
am getting the same issue from my mac terminal . tried at least 3 times do timezones matter here ?

**Comment by sezna** [comment]
This has just happened to me trying to provision a Digitalocean droplet from Ubuntu 19. I believe this is still an active issue.

**Comment by davidemyers** [comment]
@sezna Any chance you have a previously configured DO firewall applied to all Droplets labelled `Environment:Algo`? The default SSH port has changed to 4160 so an existing firewall needs to be updated before any new deployments.

**Comment by sezna** [comment]
Alas, I was setting this up for my trip to China and did not succeed. I am now in China, and my ability to configure digitalocean is hindered since I don't have a VPN. I'll investigate that when I get back in a couple weeks. 

I did completely delete the environment:algo bit in between attempts. I also reset the ssh keys after the second attempt.

**Comment by srugano** [comment]
Having the same issue.
