### ISSUE TITLE
Add a local user for each VPN user for SSH tunneling

### ISSUE THREAD

**Issue by dguido** [trailofbits/algo#77]
This is only an idea, but maybe we can setup SSH for users to proxy through also? I think this could work if we:

1. Create a new local account for each defined user
2. Create a new authorized key for each user (in OpenSSH and PuTTY formats)
3. Lock down and de-privilege the shell
4. Print out the host key fingerprint to save users the trouble of verifying it

Then for situations where the user did not want to use IPSEC, they could connect through algo with one of the many available SSH proxying options (e.g., `ssh -D`, `ssh -w`, `ssh -L`, `ssh -R`, etc).

What do you think? I think this hinges on whether we can suitably lock down the shell so a rogue user can't just pop the machine with a local-root-of-the-week.

**Comment by gunph1ld** [comment]
Sure, we can use `chroot` at least

**Comment by dguido** [comment]
I'm not sure that chroot is enough... is there a way we can isolate people even more strongly, similar to bubblewrap or seccomp? Does SSH have some built in feature to ensure people only use it for port forwarding and not for an interactive shell?

**Comment by dguido** [comment]
Is setting the user shells to /bin/false enough? I always thought there was a way around that as a security control but maybe I am wrong.

**Comment by dguido** [comment]
The Ubuntu `sshd_config` is pretty large but most of the items are default values. I removed a lot of them (since they are the default) and only kept the ones that we want to be explicit about turning on or off. Many other options that only apply to the SSH Protocol version 1 were removed, like `ServerKeyBits`.

```
Port 22
# ListenAddress ::
# ListenAddress 0.0.0.0
Protocol 2

# LogLevel VERBOSE logs user's key fingerprint on login.
# Needed to have a clear audit track of which key was used to log in.
SyslogFacility AUTH
LogLevel VERBOSE

# Use kernel sandbox mechanisms where possible in unprivilegied processes
# Systrace on OpenBSD, Seccomp on Linux, seatbelt on MacOSX/Darwin, rlimit elsewhere.
UsePrivilegeSeparation sandbox

# Handy for keeping network connections alive
TCPKeepAlive yes
ClientAliveInterval 120

# Authentication
UsePAM yes
PermitRootLogin without-password
StrictModes yes
PubkeyAuthentication yes

# "remote" ensures that you can't make local connections
# We may want to apply this in a "Match User" block to avoid affecting root
AllowTcpForwarding remote

# Turn off a lot of features
AllowAgentForwarding no
IgnoreRhosts yes
RhostsRSAAuthentication no
RSAAuthentication no
HostbasedAuthentication no
PermitEmptyPasswords no
ChallengeResponseAuthentication no
PasswordAuthentication no
UseDNS no
X11Forwarding no

# Do not enable sftp
# If enabled use this line to log which files sftp users read/write
# Subsystem sftp  /usr/lib/ssh/sftp-server -f AUTHPRIV -l INFO

# This makes ansible faster
PrintMotd no
PrintLastLog yes

# Use only modern host keys
HostKey /etc/ssh/ssh_host_ecdsa_key
HostKey /etc/ssh/ssh_host_ed25519_key

# Use only modern ciphers
KexAlgorithms curve25519-sha256@libssh.org,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com

# TODO: Not sure the consequences of leaving this enabled in our setup
AcceptEnv LANG LC_*

# TODO: I haven't seen anyone review these yet
# HostKeyAlgorithms ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519

# TODO: I haven't seen anyone review these yet
# PubkeyAcceptedKeyTypes ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519

# TODO: I think we want to enable tunnels but disable stream local fowarding?
# PermitTunnel yes
# AllowStreamLocalForwarding no
```

We might want to make a new group and apply some of these restrictions selectively like so:

```
Match User forwarding-only
    AllowTcpForwarding remote
    AllowStreamLocalForwarding no
    ...
```

**Comment by gunph1ld** [comment]
The role pushed to the dev branch

**Comment by dguido** [comment]
@gunph1ld I'm worried about local users clobbering their own sshd_config with the one that we have included. Can you add the sshd_config to the security role, then add the "Match User" block to the sshd_config in this role? Also, the security role should be optional.

**Comment by dguido** [comment]
Last point: I think we should put the authorized_keys we create for each user in the `configs` directory alongside all the rest of their certificates.
