### ISSUE TITLE
Apple Profiles don't get installed on iOS 11 devices

### ISSUE THREAD

**Issue by mirkhosro** [trailofbits/algo#771]
### OS / Environment

macOS 10.13.2

### Ansible version

2.4.2.0

### Summary of the problem
When sending the generated Apple Profile to iOS 11 devices it won't get installed. Instead it just opens the profile as a text file and displays its contents.

### Steps to reproduce the behavior
1. Generate Apple profiles by running `./algo`
2. Send the generated profile to an iOS 11 device over email or a messaging app. 
3. Tap on the file on the iOS device. It won't get installed, instead only the contents of the file are shown.

### The way of deployment (cloud or local)
cloud

### Expected behavior
The generated Apple Profile should get installed after it is sent and opened in an iOS device.

### Actual behavior
Only the textual content of the profile is shown when you open it on an iOS 11 device.

**Comment by massimocode** [comment]
@mirkhosro did you try opening it in the iOS Mail app? iMessage doesn't seem to work... I read somewhere that only Safari and the iOS Mail app can open mobileconfig files.
