### ISSUE TITLE
iOS SSH Tunneling Failure

### ISSUE THREAD

**Issue by JackEdgar** [trailofbits/algo#772]
### OS / Environment

Ubuntu (Windows Subsystem for Linux)

### Summary of the problem

I am unable to use the SSH tunneling feature on iOS. I have successfully set up the server and it is working for the VPN on both iOS and Windows 10, as well as SSH tunneling on Windows 10. However, after installing the 'SSH Tunnel' app on iOS and attempting to configure it, the provided SSH PEM keys are proving of no use. The app requires a private OpenSSH key, which I have attempted to convert to using ssh-keygen, openssl and even PuTTYgen in multiple different ways. I have as of yet found no way for the key to be either parsed correctly or accepted by the server.

### Steps to reproduce the behaviour

Install 'SSH Tunnel' on iOS and attempt to import provided SSH keys (Configure device to use SSH tunneling)

### The way of deployment (cloud or local)

Cloud - Amazon Web Services

### Expected behavior

Expected to be able to use the SSH tunneling feature on 127.0.0.1:1080 via iOS

### Actual behavior

SSH tunneling feature is failing to work

**Comment by dguido** [comment]
SSH tunneling will work if you configure it exactly as in the example. It requires a bunch of extra options. I'm not sure if your app supports it.
