### ISSUE TITLE
ssh_public_key variable is erroneously listed as required for AWS and (possibly) GCE

### ISSUE THREAD

**Issue by mrled** [trailofbits/algo#773]
The `ssh_public_key` variable is listed as required for AWS in `docs/deploy-from-ansible.md`, and is passed to Ansible in the `algo` script. However, it doesn't appear that this is consumed anywhere in the Ansible roles used by AWS. 

I deployed to AWS from Ansible, and it appears to work. I can connect from macOS and my traffic is successfully tunneled through the VPN according to whoer.net. After modifying values in `config.cfg` and setting `AWS_ACCESS_KEY` and `AWS_SECRET_KEY` environment variables in my shell, I used this command:

    ansible-playbook deploy.yml -t ec2,vpn,cloud,security,encrypted -e "aws_access_key=$AWS_ACCESS_KEY aws_secret_key=$AWS_SECRET_KEY aws_server_name=newtroy region=us-east-2 Win10_Enabled=Y Store_CAKEY=Y"

The same variable is also listed as required for GCE in the `deploy-from-ansible.md` documentation, but from a cursory glance `cloud-gce` role, it isn't used there either; that role appears to use SSH keys from `config.cfg` instead. That being said, I did not test GCE and may be misunderstanding this.

**Comment by dguido** [comment]
Thanks for noticing this!

**Comment by mrled** [comment]
Thanks to you for maintaining this project :)
