### ISSUE TITLE
A few questions 

### ISSUE THREAD

**Issue by canusuck** [trailofbits/algo#774]
1. How to change the preset vpn: preshared key name and other moments.
2. How to get rid of dnsleaks? Use dnsmasq on the host machine, you can tell by the settings then.
3. Can I do it and if I can do it better: Double / Triple / Quad bundle for VPN
4. How to change ports to others? How to change ports if VPN is already installed on the server? Where to look ?

In advance I thank for answers

**Comment by dguido** [comment]
1. There's no pre-shared key on this VPN. It uses public key authentication.
2. There shouldn't be any DNS leaks in the default configuration.
3. You can change the default DNS settings in config.cfg prior to deployment.
4. You can't, or else IPSEC VPN clients won't be able to connect to it.

**Comment by canusuck** [comment]
Can I install it with my WireGuard?

I can not specify a different port? 500 change to 443 ??

**Comment by canusuck** [comment]
Wireguard + algo?

**Comment by dguido** [comment]
You should look for support from the Gitter. Github is for filing bugs you've found in the code.

You can do whatever you want to the server after it's been deployed.

You cannot change the IPSEC port IPSEC clients typically do not support changing ports.
