### ISSUE TITLE
Azure failed at creating a virtual network task - 409 Client Error - Conflict for Url

### ISSUE THREAD

**Issue by kennydust** [trailofbits/algo#775]
### OS / Environment
macOS version 10.13.2

### Ansible version
2.2.0.0

### Version of components from `requirements.txt`

msrestazure
setuptools>=11.3
ansible>=2.1,<2.2.1
dopy==0.3.5
boto>=2.5
boto3
azure==2.0.0rc5
msrest==0.4.1
apache-libcloud
six
pyopenssl
jinja2==2.8

### Summary of the problem
On my macOs, ran the .algo script to deploy to azure. At the very last step, there was a failure when attempting to create a virtual network:  

409 Client Error: Conflict for url: https://management.azure.com/subscriptions/********/resourceGroups/Algo_eastus/providers/Microsoft.Network/virtualnetworks/algo_net?api-version=2016-03-30

### Steps to reproduce the behavior
./algo

### The way of deployment (cloud or local)
cloud

### Expected behavior
was expected the process to complete.

### Actual behavior
an error occurred for a conflict for url.

### Full log
What provider would you like to use?
    1. DigitalOcean
    2. Amazon EC2
    3. Microsoft Azure
    4. Google Compute Engine
    5. Install to existing Ubuntu 16.04 server

Enter the number of your desired provider
: 3

Enter your azure secret id (https://github.com/trailofbits/algo/blob/master/docs/cloud-azure.md)
You can skip this step if you want to use your defaults credentials from ~/.azure/credentials
[pasted values will not be displayed]
[...]: 

Enter your azure tenant id (https://github.com/trailofbits/algo/blob/master/docs/cloud-azure.md)
You can skip this step if you want to use your defaults credentials from ~/.azure/credentials
[pasted values will not be displayed]
[...]: 

Enter your azure client id (application id) (https://github.com/trailofbits/algo/blob/master/docs/cloud-azure.md)
You can skip this step if you want to use your defaults credentials from ~/.azure/credentials
[pasted values will not be displayed]
[...]: 

Enter your azure subscription id (https://github.com/trailofbits/algo/blob/master/docs/cloud-azure.md)
You can skip this step if you want to use your defaults credentials from ~/.azure/credentials
[pasted values will not be displayed]
[...]: 

Name the vpn server:
[algo]: 

  What region should the server be located in? (https://azure.microsoft.com/en-us/regions/)
    1.  South Central US
    2.  Central US
    3.  North Europe
    4.  West Europe
    5.  Southeast Asia
    6.  Japan West
    7.  Japan East
    8.  Australia Southeast
    9.  Australia East
    10. Canada Central
    11. West US 2
    12. West Central US
    13. UK South
    14. UK West
    15. West US
    16. Brazil South
    17. Canada East
    18. Central India
    19. East Asia
    20. Germany Central
    21. Germany Northeast
    22. Korea Central
    23. Korea South
    24. North Central US
    25. South India
    26. West India
    27. East US
    28. East US 2

Enter the number of your desired region:
[1]: 27

Do you want macOS/iOS clients to enable "VPN On Demand" when connected to cellular networks?
[y/N]: N

Do you want macOS/iOS clients to enable "VPN On Demand" when connected to Wi-Fi?
[y/N]: N

Do you want to install a DNS resolver on this VPN server, to block ads while surfing?
[y/N]: N

Do you want each user to have their own account for SSH tunneling?
[y/N]: N

Do you want to apply operating system security enhancements on the server? (warning: replaces your sshd_config)
[y/N]: N

Do you want the VPN to support Windows 10 or Linux Desktop clients? (enables compatible ciphers and key exchange, less secure)
[y/N]: N

Do you want to retain the CA key? (required to add users in the future, but less secure)
[y/N]: N

PLAY [Configure the server] ****************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Generate the SSH private key] ********************************************
changed: [localhost]

TASK [Generate the SSH public key] *********************************************
ok: [localhost]

TASK [Change mode for the SSH private key] *************************************
ok: [localhost]

TASK [Ensure the dynamic inventory exists] *************************************
changed: [localhost]

TASK [cloud-azure : set_fact] **************************************************
ok: [localhost]

TASK [cloud-azure : Create a resource group] ***********************************
changed: [localhost]

TASK [cloud-azure : Create a virtual network] **********************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error creating or updating virtual network algo_net - 409 Client Error: Conflict for url: https://management.azure.com/subscriptions/********/resourceGroups/Algo_eastus/providers/Microsoft.Network/virtualnetworks/algo_net?api-version=2016-03-30"}

TASK [cloud-azure : debug] *****************************************************
ok: [localhost] => {
    "fail_hint": [
        "Sorry, but something went wrong!", 
        "Please check the troubleshooting guide.", 
        "https://trailofbits.github.io/algo/troubleshooting.html"
    ]
}

TASK [cloud-azure : fail] ******************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Failed as requested from task"}

PLAY RECAP *********************************************************************
localhost                  : ok=8    changed=3    unreachable=0    failed=1

**Comment by jackivanov** [comment]
Unreproducible. Try to clean up the environment and resource groups on the Azure portal
