### ISSUE TITLE
Cannot delete existing Algo SSH keys

### ISSUE THREAD

**Issue by spartanhooah** [trailofbits/algo#776]
### OS / Environment
Ubuntu 17.10

### Ansible version
2.2.0.0

### Version of components from `requirements.txt`
msrestazure: 0.4.19
setuptools: 38.4.0
ansible: 2.2.0.0
dopy: 0.3.5
boto: 2.48.0
boto3: 1.5.9
azure: 2.0.0rc5
msrest: 0.4.1
apache-libcloud: 2.2.1
six: 1.11.0
pyopenssl: 17.5.0
jinja2: 2.8

### Summary of the problem
When I run the script, step "TASK [cloud-digitalocean : Delete the existing Algo SSH keys]" fails. The message says the script failed to delete existing Algo SSH keys. I have no idea where these "existing" keys are, as I don't have a DO droplet yet and I've tried deleting the whole algo directory and re-cloning.

### Steps to reproduce the behavior
1) Clone the repo.
2) Install dependencies for both Ubuntu and Python.
3) Edit config.cfg with the appropriate users.
4) Run the algo script.
5) Choose DigitalOcean.
6) Paste API key.
7) Name the server.
8) Choose my region (9).
9) Answer the next few questions as y, y, <none>, y, n, y, y, n.
10) Get the failure.

### The way of deployment (cloud or local)
DigitalOcean

### Expected behavior
A VPN on a DigitalOcean droplet.

### Actual behavior
Failure starting at step TASK [cloud-digitalocean : Delete the existing Algo SSH keys]

### Full log
`
  What provider would you like to use?
    1. DigitalOcean
    2. Amazon EC2
    3. Microsoft Azure
    4. Google Compute Engine
    5. Install to existing Ubuntu 16.04 server

Enter the number of your desired provider
: 1

Enter your API token. The token must have read and write permissions (https://cloud.digitalocean.com/settings/api/tokens):
[pasted values will not be displayed]
: 

Name the vpn server:
[algo.local]: ScienceFi

  What region should the server be located in?
    1.  Amsterdam        (Datacenter 2)
    2.  Amsterdam        (Datacenter 3)
    3.  Frankfurt
    4.  London
    5.  New York         (Datacenter 1)
    6.  New York         (Datacenter 2)
    7.  New York         (Datacenter 3)
    8.  San Francisco    (Datacenter 1)
    9.  San Francisco    (Datacenter 2)
    10. Singapore
    11. Toronto
    12. Bangalore
Enter the number of your desired region:
[7]: 9

Do you want macOS/iOS clients to enable "VPN On Demand" when connected to cellular networks?
[y/N]: y

Do you want macOS/iOS clients to enable "VPN On Demand" when connected to Wi-Fi?
[y/N]: y

List the names of trusted Wi-Fi networks (if any) that macOS/iOS clients exclude from using the VPN (e.g., your home network. Comma-separated value, e.g., HomeNet,OfficeWifi,AlgoWiFi)
: 

Do you want to install a DNS resolver on this VPN server, to block ads while surfing?
[y/N]: y

Do you want each user to have their own account for SSH tunneling?
[y/N]: n

Do you want to apply operating system security enhancements on the server? (warning: replaces your sshd_config)
[y/N]: y

Do you want the VPN to support Windows 10 or Linux Desktop clients? (enables compatible ciphers and key exchange, less secure)
[y/N]: y

Do you want to retain the CA key? (required to add users in the future, but less secure)
[y/N]: n

PLAY [Configure the server] ****************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Generate the SSH private key] ********************************************
changed: [localhost]

TASK [Generate the SSH public key] *********************************************
ok: [localhost]

TASK [Change mode for the SSH private key] *************************************
ok: [localhost]

TASK [Ensure the dynamic inventory exists] *************************************
changed: [localhost]

TASK [cloud-digitalocean : Set the DigitalOcean Access Token fact] *************
ok: [localhost]

TASK [cloud-digitalocean : Delete the existing Algo SSH keys] ******************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "The conditional check 'ssh_keys.changed != true' failed. The error was: error while evaluating conditional (ssh_keys.changed != true): 'dict object' has no attribute 'changed'"}

TASK [cloud-digitalocean : Collect the fail error] *****************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: DoError: Unable to authenticate you.
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to authenticate you."}
...ignoring

TASK [cloud-digitalocean : debug] **********************************************
ok: [localhost] => {
    "ssh_keys": {
        "changed": false, 
        "exception": "Traceback (most recent call last):\n  File \"/tmp/ansible_ffkTx3/ansible_module_digital_ocean.py\", line 464, in main\n    core(module)\n  File \"/tmp/ansible_ffkTx3/ansible_module_digital_ocean.py\", line 417, in core\n    key = SSH.find(name)\n  File \"/tmp/ansible_ffkTx3/ansible_module_digital_ocean.py\", line 319, in find\n    keys = cls.list_all()\n  File \"/tmp/ansible_ffkTx3/ansible_module_digital_ocean.py\", line 327, in list_all\n    json = cls.manager.all_ssh_keys()\n  File \"/home/ben/Downloads/algo/env/local/lib/********2.7/site-packages/dopy/manager.py\", line 271, in all_ssh_keys\n    json = self.request('/account/keys')\n  File \"/home/ben/Downloads/algo/env/local/lib/********2.7/site-packages/dopy/manager.py\", line 424, in request\n    resp = self.request_v2(url, params=params, headers=headers, method=method)\n  File \"/home/ben/Downloads/algo/env/local/lib/********2.7/site-packages/dopy/manager.py\", line 482, in request_v2\n    raise DoError(json['message'])\nDoError: Unable to authenticate you.\n", 
        "failed": true, 
        "msg": "Unable to authenticate you."
    }
}

TASK [cloud-digitalocean : fail] ***********************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Please, ensure that your API token is not read-only."}

TASK [cloud-digitalocean : debug] **********************************************
ok: [localhost] => {
    "fail_hint": [
        "Sorry, but something went wrong!", 
        "Please check the troubleshooting guide.", 
        "https://trailofbits.github.io/algo/troubleshooting.html"
    ]
}

TASK [cloud-digitalocean : fail] ***********************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Failed as requested from task"}

PLAY RECAP *********************************************************************
localhost                  : ok=9    changed=2    unreachable=0    failed=1   `

**Comment by AUAggy** [comment]
Login to Digital Ocean and navigate to:
Settings > Security
Delete necessary SSH Key.

**Comment by spartanhooah** [comment]
Deleted the algo key, same result. Do I need to create one, or does the script do that?

**Comment by dguido** [comment]
"msg": "Unable to authenticate you."

fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Please, ensure that your API token is not read-only."}

I don't think you're using the right DO API key.

**Comment by spartanhooah** [comment]
Somehow pasting wasn't working. Thanks, bash.
