### ISSUE TITLE
help pls

### ISSUE THREAD

**Issue by canusuck** [trailofbits/algo#777]
1. How many people can simultaneously connect using the L2TP / IPsec protocol?
2. How to get rid of DNSLeaks? For example, I have a server in Sweden, how can I receive only DNS Sweden?
3. How to connect correctly to Linux?
4. Is ikev2 safer than l2tp? Is it faster? How much can it be used at the same time?

Thank you in advance for your response.

**Comment by dguido** [comment]
Sorry, but this is not the correct forum for these questions. Please join the Gitter and read the documentation.

**Comment by canusuck** [comment]
pls bro answer me 

And then I will do as you say.

**Comment by canusuck** [comment]
the issues number is 777 =)
