### ISSUE TITLE
Not having OnDemandEnabled=Y does not allow for "Connect on Demand" to be toggled later

### ISSUE THREAD

**Issue by j-hui** [trailofbits/algo#778]
### OS / Environment
Ubuntu 16.04, on Digital Ocean

### Ansible version
ansible 2.2.0.0

### Summary of the problem
The tutorial indicates that setting the `OnDemandEnabled_*` variables to `=Y` will generate a `.mobileconfig`. Setting these to anything other than `Y` (for example, `N`) produces `.mobileconfig`s that do not have the option to toggle "Connect on Demand".

This a feature request.

### Steps to reproduce the behavior

* Deploy using the `deploy.yml` Ansible playbook, with options: `OnDemandEnabled_WIFI=N OnDemandEnabled_WIFI_EXCLUDE="" OnDemandEnabled_Cellular=N`
* Install `.mobileconfig` on macOS or iOS device

### The way of deployment (cloud or local)
local
(Using scripted local deployment on Digital Ocean instance)

### Expected behavior

Does not Connect on Demand by default, but can be toggled on in preferences after installing `.mobileconfig`.

### Actual behavior

Does not Connect on Demand by default; option to toggle not available.

**Comment by davidemyers** [comment]
Try editing your `.mobileconfig` and changing `Disconnect` to `Ignore` in the On Demand section. It looks like iOS 11 interprets `Disconnect` more strictly than iOS 10 did.

**Comment by j-hui** [comment]
I got it to work by setting `<key>OnDemandEnabled</key>` to `<integer>0</integer>` in the `.mobileconfig`.

But it would be nice if Ansible would do that for me..
