### ISSUE TITLE
Instructions for a disposable VPN

### ISSUE THREAD

**Issue by chrisjensen** [trailofbits/algo#780]
The [TechCrunch](https://techcrunch.com/2017/04/09/how-i-made-my-own-vpn-server-in-15-minutes/) article that I found Algo talks about using it as a "disposable" VPN.

I'd like to script this daily (ie, shutdown he existing server and deploy a new one in it's place with the same config and keys)

Im not familiar with ansible, and haven't been able to figure out what the commands needed would be.
If someone would point me in the right direction I'd be happy to help put together some documentation for others.

**Comment by dguido** [comment]
You just have to run it again and do a new deploy, login to DO and shut down the old one. Remember to rotate any keys on your laptop, iPhone, whatever .

**Comment by chrisjensen** [comment]
Is it possible to do without rotating the keys thought? I use it for our family, so it would be too much hassle if I was having to rotate keys on everyone's phones and laptops.

**Comment by dguido** [comment]
That's the only way you can do it, sorry! In that scenario, keep one server setup and do it once a year IMHO.
