### ISSUE TITLE
Setup on DO Ubuntu droplet fails during tagging

### ISSUE THREAD

**Issue by ktavabi** [trailofbits/algo#781]
### OS / Environment
Ubuntu 16.04.3

### Ansible version
2.4.2.0

### Version of components from `requirements.txt`
msrestazure
setuptools>=11.3
ansible>=2.1,<2.2.1
dopy==0.3.5
boto>=2.5
boto3
azure==2.0.0rc5
msrest==0.4.1
apache-libcloud
six
pyopenssl
jinja2==2.8

### Summary of the problem
Cloud installation of algo vpn `./algo' failes on Digital Ocean droplet trying to tag the VM.

### Steps to reproduce the behavior
After updating to master and rerunning `./algo` script 

### The way of deployment (cloud or local)
cloud

### Expected behavior
Done!

### Actual behavior

> TASK [cloud-digitalocean : Tag the droplet] ************************************
> fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "error tagging resource '79296986': your request is malformed, please check your syntax: json: cannot unmarshal number into Go struct field Resource.resource_id of type string"}
> 
> TASK [cloud-digitalocean : debug] **********************************************
> ok: [localhost] => {
>     "fail_hint": [
>         "Sorry, but something went wrong!", 
>         "Please check the troubleshooting guide.", 
>         "https://trailofbits.github.io/algo/troubleshooting.html"
>     ]
> }
> 
> TASK [cloud-digitalocean : fail] ***********************************************
> fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Failed as requested from task"}
>PLAY RECAP *********************************************************************
localhost                  : ok=12   changed=2    unreachable=0    failed=1 

### Full log

> 
> What provider would you like to use?
>     1. DigitalOcean
>     2. Amazon EC2
>     3. Microsoft Azure
>     4. Google Compute Engine
>     5. Install to existing Ubuntu 16.04 server
> 
> Enter the number of your desired provider
> : 1
> 
> Enter your API token. The token must have read and write permissions (https://cloud.digitalocean.com/settings/api/tokens):
> [pasted values will not be displayed]
> : 
> 
> Name the vpn server:
> [algo.local]: 
> 
> 
>   What region should the server be located in?
>     1.  Amsterdam        (Datacenter 2)
>     2.  Amsterdam        (Datacenter 3)
>     3.  Frankfurt
>     4.  London
>     5.  New York         (Datacenter 1)
>     6.  New York         (Datacenter 2)
>     7.  New York         (Datacenter 3)
>     8.  San Francisco    (Datacenter 1)
>     9.  San Francisco    (Datacenter 2)
>     10. Singapore
>     11. Toronto
>     12. Bangalore
> Enter the number of your desired region:
> [7]: 9
> 
> Do you want macOS/iOS clients to enable "VPN On Demand" when connected to cellular networks?
> [y/N]: y
> 
> Do you want macOS/iOS clients to enable "VPN On Demand" when connected to Wi-Fi?
> [y/N]: y
> 
> List the names of trusted Wi-Fi networks (if any) that macOS/iOS clients exclude from using the VPN (e.g., your home network. Comma-separated value, e.g., HomeNet,OfficeWifi,AlgoWiFi)
> : 
> 
> Do you want to install a DNS resolver on this VPN server, to block ads while surfing?
> [y/N]: y
> 
> Do you want each user to have their own account for SSH tunneling?
> [y/N]: y
> 
> Do you want to apply operating system security enhancements on the server? (warning: replaces your sshd_config)
> [y/N]: y
> 
> Do you want the VPN to support Windows 10 or Linux Desktop clients? (enables compatible ciphers and key exchange, less secure)
> [y/N]: y
> 
> Do you want to retain the CA key? (required to add users in the future, but less secure)
> [y/N]: y
> 
> PLAY [Configure the server] ****************************************************
> 
> TASK [setup] *******************************************************************
> ok: [localhost]
> 
> TASK [Generate the SSH private key] ********************************************
> ok: [localhost]
> 
> TASK [Generate the SSH public key] *********************************************
> ok: [localhost]
> 
> TASK [Change mode for the SSH private key] *************************************
> ok: [localhost]
> 
> TASK [Ensure the dynamic inventory exists] *************************************
> ok: [localhost]
> 
> TASK [cloud-digitalocean : Set the DigitalOcean Access Token fact] *************
> ok: [localhost]
> 
> TASK [cloud-digitalocean : Delete the existing Algo SSH keys] ******************
> FAILED - RETRYING: TASK: cloud-digitalocean : Delete the existing Algo SSH keys (10 retries left).
> ok: [localhost]
> 
> TASK [cloud-digitalocean : Upload the SSH key] *********************************
> changed: [localhost]
> 
> TASK [cloud-digitalocean : Creating a droplet...] ******************************
> ok: [localhost]
> 
> TASK [cloud-digitalocean : Add the droplet to an inventory group] **************
> changed: [localhost]
> 
> TASK [cloud-digitalocean : set_fact] *******************************************
> ok: [localhost]
> 
> TASK [cloud-digitalocean : Tag the droplet] ************************************
> fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "error tagging resource '79296986': your request is malformed, please check your syntax: json: cannot unmarshal number into Go struct field Resource.resource_id of type string"}
> 
> TASK [cloud-digitalocean : debug] **********************************************
> ok: [localhost] => {
>     "fail_hint": [
>         "Sorry, but something went wrong!", 
>         "Please check the troubleshooting guide.", 
>         "https://trailofbits.github.io/algo/troubleshooting.html"
>     ]
> }
> 
> TASK [cloud-digitalocean : fail] ***********************************************
> fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Failed as requested from task"}
> 
> PLAY RECAP *********************************************************************
> localhost                  : ok=12   changed=2    unreachable=0    failed=1

**Comment by gunph1ld** [comment]
Duplicate #744
