### ISSUE TITLE
Install to Digital Ocean fails at SSH step

### ISSUE THREAD

**Issue by gittalicious** [trailofbits/algo#788]
### OS / Environment
Mac OS 10.13.2

### Ansible version
2.4.2.0

### Version of components from `requirements.txt`
Name: setuptools
Version: 18.5

Name: six
Version: 1.4.1

Name: pyOpenSSL
Version: 0.13.1

Name: Jinja2
Version: 2.10

### Summary of the problem
Trying to install to DO.  Installation fails at step after deleting the new Algo SSH key.  This step fails initially and then succeeds when retried.  Then the next step ("Wait until SSH becomes ready...") stalls and eventually fails with the following log output:

What provider would you like to use?
    1. DigitalOcean
    2. Amazon EC2
    3. Microsoft Azure
    4. Google Compute Engine
    5. Install to existing Ubuntu 16.04 server

Enter the number of your desired provider
: 1
Enter your API token. The token must have read and write permissions (https://cloud.digitalocean.com/settings/api/tokens):
[pasted values will not be displayed]
: 

Name the vpn server:
[algo.local]: Algo

  What region should the server be located in?
    1.  Amsterdam        (Datacenter 2)
    2.  Amsterdam        (Datacenter 3)
    3.  Frankfurt
    4.  London
    5.  New York         (Datacenter 1)
    6.  New York         (Datacenter 2)
    7.  New York         (Datacenter 3)
    8.  San Francisco    (Datacenter 1)
    9.  San Francisco    (Datacenter 2)
    10. Singapore
    11. Toronto
    12. Bangalore

Enter the number of your desired region:
[7]: 11

Do you want macOS/iOS clients to enable "VPN On Demand" when connected to cellular networks?
[y/N]: y

Do you want macOS/iOS clients to enable "VPN On Demand" when connected to Wi-Fi?
[y/N]: y

List the names of trusted Wi-Fi networks (if any) that macOS/iOS clients exclude from using the VPN (e.g., your home network. Comma-separated value, e.g., HomeNet,OfficeWifi,AlgoWiFi)
: REDACTED

Do you want to install a DNS resolver on this VPN server, to block ads while surfing?
[y/N]: y

Do you want each user to have their own account for SSH tunneling?
[y/N]: n

Do you want to apply operating system security enhancements on the server? (warning: replaces your sshd_config)
[y/N]: y

Do you want the VPN to support Windows 10 or Linux Desktop clients? (enables compatible ciphers and key exchange, less secure)
[y/N]: n

Do you want to retain the CA key? (required to add users in the future, but less secure)
[y/N]: n

PLAY [Configure the server] ****************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Generate the SSH private key] ********************************************
ok: [localhost]

TASK [Generate the SSH public key] *********************************************
ok: [localhost]

TASK [Change mode for the SSH private key] *************************************
ok: [localhost]

TASK [Ensure the dynamic inventory exists] *************************************
ok: [localhost]

TASK [cloud-digitalocean : Set the DigitalOcean Access Token fact] *************
ok: [localhost]

TASK [cloud-digitalocean : Delete the existing Algo SSH keys] ******************
ok: [localhost]

TASK [cloud-digitalocean : Upload the SSH key] *********************************
changed: [localhost]

TASK [cloud-digitalocean : Creating a droplet...] ******************************
changed: [localhost]

TASK [cloud-digitalocean : Add the droplet to an inventory group] **************
changed: [localhost]

TASK [cloud-digitalocean : set_fact] *******************************************
ok: [localhost]

TASK [cloud-digitalocean : Tag the droplet] ************************************
changed: [localhost]

TASK [cloud-digitalocean : Get droplets] ***************************************
ok: [localhost]

TASK [cloud-digitalocean : Ensure the group digitalocean exists in the dynamic inventory file] ***
ok: [localhost]

TASK [cloud-digitalocean : Populate the dynamic inventory] *********************
changed: [localhost] => (item={u'status': u'active', u'kernel': None, u'volume_ids': [], u'locked': False, u'name': u'Algo', u'backup_ids': [], u'created_at': u'2018-01-22T18:57:05Z', u'snapshot_ids': [], u'size_slug': u'512mb', u'networks': {u'v4': [{u'type': u'public', u'netmask': u'255.255.240.0', u'ip_address': u'138.197.138.208', u'gateway': u'138.197.128.1'}], u'v6': [{u'type': u'public', u'netmask': 64, u'ip_address': u'2604:A880:0CAD:00D0:0000:0000:022D:1001', u'gateway': u'2604:A880:0CAD:00D0:0000:0000:0000:0001'}]}, u'next_backup_window': None, u'vcpus': 1, u'size': {u'price_monthly': 5.0, u'available': True, u'transfer': 1.0, u'price_hourly': 0.00744, u'regions': [u'ams3', u'blr1', u'fra1', u'lon1', u'nyc1', u'nyc2', u'nyc3', u'sfo1', u'sfo2', u'sgp1', u'tor1'], u'vcpus': 1, u'memory': 512, u'disk': 20, u'slug': u'512mb'}, u'image': {u'min_disk_size': 20, u'name': u'16.04.3 x64', u'created_at': u'2018-01-18T00:45:24Z', u'slug': u'ubuntu-16-04-x64', u'regions': [u'nyc1', u'sfo1', u'nyc2', u'ams2', u'sgp1', u'lon1', u'nyc3', u'ams3', u'fra1', u'tor1', u'sfo2', u'blr1'], u'id': 31009407, u'distribution': u'Ubuntu', u'type': u'snapshot', u'public': True, u'size_gigabytes': 0.3}, u'memory': 512, u'region': {u'available': True, u'sizes': [u'512mb', u's-1vcpu-1gb', u'1gb', u's-3vcpu-1gb', u's-1vcpu-2gb', u'2gb', u's-2vcpu-2gb', u's-1vcpu-3gb', u'c-2', u's-2vcpu-4gb', u'4gb', u's-4vcpu-8gb', u'8gb', u'm-1vcpu-8gb', u'16gb', u's-6vcpu-16gb', u's-8vcpu-32gb'], u'slug': u'tor1', u'name': u'Toronto 1', u'features': [u'private_networking', u'backups', u'ipv6', u'metadata', u'install_agent', u'storage']}, u'disk': 20, u'id': 79734572, u'tags': [u'Environment:Algo'], u'features': [u'ipv6']})

TASK [cloud-digitalocean : Delete the new Algo SSH key] ************************
FAILED - RETRYING: TASK: cloud-digitalocean : Delete the new Algo SSH key (10 retries left).

ok: [localhost]

TASK [Wait until SSH becomes ready...] *****************************************
fatal: [localhost]: FAILED! => {"changed": false, "elapsed": 321, "failed": true, "msg": "Timeout when waiting for search string OpenSSH in 138.197.138.208:22"}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "fail_hint": [
        "Sorry, but something went wrong!", 
        "Please check the troubleshooting guide.", 
        "https://trailofbits.github.io/algo/troubleshooting.html"
    ]
}

TASK [fail] ********************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Failed as requested from task"}

PLAY RECAP *********************************************************************
localhost                  : ok=17   changed=5    unreachable=0    failed=1 

### Steps to reproduce the behavior
Follow installation instructions from https://github.com/trailofbits/algo

### The way of deployment (cloud or local)
local

### Expected behavior
A working VPN install

### Actual behavior
Failed install

### Full log
see above

**Comment by dguido** [comment]
This happens from time to time due to delays and inconsistency with Digital Ocean. Try again and it should work.
