### ISSUE TITLE
Re issue 788 (which was closed)

### ISSUE THREAD

**Issue by gittalicious** [trailofbits/algo#789]
Refer to issue 788 https://github.com/trailofbits/algo/issues/788
(I was unable to respond in that thread, I guess because it was closed?)

Your response was that "This happens from time to time due to delays and inconsistency with Digital Ocean. Try again and it should work."

I have tried this more than 2 dozen times over the last 3 days, on two different computers.  Same result every time.  Are you sure there is nothing else going on?

**Comment by dguido** [comment]
It works fine for me on macOS 10.13 with DigitalOcean.
