### ISSUE TITLE
Can't revoke a user cert and create a new one.

### ISSUE THREAD

**Issue by thams** [trailofbits/algo#792]
### Summary of the problem

Can't revoke a user cert and create a new one.

### Steps to reproduce the behavior

It appears that removing a user from config.cfg and re-running algo update-users revokes the certificates of the user.

However, adding the user back and re-running algo update-users seems to create fresh certificates that are nonetheless revoked. How does one revoke a user certificate and create a new one?

### The way of deployment (cloud or local)

cloud

### Expected behavior

revoke cert and get a new one

### Actual behavior

new cert is still revoked.

**Comment by gunph1ld** [comment]
There is no way do to that. You can reinit all the existing certificates by enabling `easyrsa_reinit_existent` in config.cfg
