### ISSUE TITLE
In Network settings on Mac OS, I can not find Algo VPN to connect 

### ISSUE THREAD

**Issue by jesser360** [trailofbits/algo#793]
I have followed all of the steps in setting up the Digital Ocean Droplet, and installing the Algo server.
After going to system preferences and then Network, Algo VPN does not show up as a connection possibility.
I can manually create a VPN but need a server address and Remote IP, any thoughts?
Thank you!

**Comment by dguido** [comment]
Support is available on Gitter. The directions cover all the setup steps! Please checkout the readme again.

**Comment by jesser360** [comment]
Ok I will ask in the gitter. 
This step below is the one I am stuck on. I tried rebooting the machine, but Algo VPN still doesn't appear as an option in left panel. I think it is something super simple like I have not turned on the VPN.. how do I go about doing this? 
'Turn on the VPN. On iOS, connect to the VPN by opening Settings and clicking the toggle next to "VPN" near the top of the list. On macOS, connect to the VPN by opening System Preferences -> Network, finding Algo VPN in the left column and clicking "Connect." On macOS, check "Show VPN status in menu bar" to easily connect and disconnect from the menu bar.'
