### ISSUE TITLE
Suggestions for documentation for local Ubuntu install

### ISSUE THREAD

**Issue by trymes** [trailofbits/algo#796]
### OS / Environment

Ubuntu 16.04 LTS Fresh install

### Ansible version

2.2.0

### Version of components from `requirements.txt`

N/A

### Summary of the problem
Instructions are incomplete.

### Steps to reproduce the behavior
Follow guide here: https://github.com/trailofbits/algo/blob/master/docs/deploy-to-ubuntu.md

### The way of deployment (cloud or local)

Local

### Expected behavior
1.) So far as I can tell, the guide at https://github.com/trailofbits/algo/blob/master/docs/deploy-to-ubuntu.md normally (when working with a cloud provider) configures the server to use public key authentication for SSH and copies the proper key to the user's client PC. However, when running the script while logged into a local Ubuntu machine, this doesn't work, as the user must manually copy the key off of the Ubuntu machine to their client. Instructions for this would be a nice addition to the guide.

2.) Prior to running "./algo", the user should open config.cfg and modify the usernames in the file, or the user will build a configuration that uses the default users "dan" and "jack". Adding a step to the documentation that explains this would prove helpful to users.

### Actual behavior
locked out of ssh until key manually copied and generic usernames used.

### Full log
N/A.

**Comment by gunph1ld** [comment]
All of these are covered in the main [readme](https://github.com/trailofbits/algo#deploy-the-algo-server)

**Comment by trymes** [comment]
I suppose, but the steps in the Ubuntu docs proceed directly from downloading/install running ./algo, and adding a quick note that the user needs to modify config.cfg before actually running ./algo would eliminate any confusion.

Also, the section "SSH into Algo Server" on the main readme assumes that you have the keys on your client, but because the user is running the script directly from the server when installing to a local Ubuntu machine, the SSH keys are left on the server and not copied to the client. If the user logs off before copying the key back to the client via SCP, then s/he will need to get physical access to the console to copy the key, as there is no way to log in via SSH without the key at that point.

Or have I missed something?
