### ISSUE TITLE
Deployed this to my server and now all my websites are gone!

### ISSUE THREAD

**Issue by julien-c** [trailofbits/algo#798]
Deployed `algo` to my server running Ubuntu 16.04 which hosts a bunch of different websites and services.

They are all inaccessible now – what should I do to fix them?

I guess I want to revert my iptables configuration?

**Comment by dguido** [comment]
Yep, please don’t install this on a server you use for anything else. Local installs are your own responsibility. Use the automated cloud deployment methods!

**Comment by julien-c** [comment]
I guess it wouldn't hurt to make that clearer in the README. Thanks!

**Comment by paulschreiber** [comment]
Same thing happened to me. I had to flush iptables, despite my webserver running on a different IP address than my VPN server.

**Comment by paulschreiber** [comment]
The workaround for this is to edit `/etc/iptables/rules.v4` and open those ports.

See https://github.com/paulschreiber/algo/commit/f806ef9ae041ec4a91e1f6a3d72739fdbf5f47fd in branch [fix/iptables](https://github.com/paulschreiber/algo/tree/fix/iptables).
