### ISSUE TITLE
Unable to configure Ubuntu Client - fails after 5 transmission attempts

### ISSUE THREAD

**Issue by InbarRose** [trailofbits/algo#799]
### OS / Environment
Configured on Google Compute, Windows clients can connect with no problem.

### Summary of the problem
When trying to configure an Ubuntu client (17) using the steps provided it is able to establish authentication and I can see logs on the vpn server that show connection attempts, but after 5 transmissions it fails to connect fully.

tried configuring it with all methods I could find, including the ansible-playbook deploy_client.yml method. All the results are the same, it looks like it will work, authentication works, but it just fails...

> user-name@host:~$ sudo ipsec up ikev2-1.2.3.4
[sudo] password for user-name: 
initiating IKE_SA ikev2-1.2.3.4[2] to 1.2.3.4
generating IKE_SA_INIT request 0 [ SA KE No N(NATD_S_IP) N(NATD_D_IP) N(FRAG_SUP) N(HASH_ALG) ]
sending packet: from 192.168.0.11[500] to 1.2.3.4[500] (256 bytes)
received packet: from 1.2.3.4[500] to 192.168.0.11[500] (289 bytes)
parsed IKE_SA_INIT response 0 [ SA KE No N(NATD_S_IP) N(NATD_D_IP) CERTREQ N(FRAG_SUP) N(HASH_ALG) N(MULT_AUTH) ]
local host is behind NAT, sending keep alives
remote host is behind NAT
received cert request for "CN=1.2.3.4"
sending cert request for "CN=1.2.3.4"
authentication of 'CN=user-name' (myself) with ECDSA_WITH_SHA256_DER successful
sending end entity cert "CN=user-name"
establishing CHILD_SA ikev2-1.2.3.4
generating IKE_AUTH request 1 [ IDi CERT N(INIT_CONTACT) CERTREQ IDr AUTH CPRQ(ADDR DNS) SA TSi TSr N(MOBIKE_SUP) N(ADD_4_ADDR) N(ADD_4_ADDR) N(MULT_AUTH) N(EAP_ONLY) ]
splitting IKE message with length of 841 bytes into 2 fragments
generating IKE_AUTH request 1 [ EF(1/2) ]
generating IKE_AUTH request 1 [ EF(2/2) ]
sending packet: from 192.168.0.11[4500] to 1.2.3.4[4500] (544 bytes)
sending packet: from 192.168.0.11[4500] to 1.2.3.4[4500] (362 bytes)
retransmit 1 of request with message ID 1
sending packet: from 192.168.0.11[4500] to 1.2.3.4[4500] (544 bytes)
sending packet: from 192.168.0.11[4500] to 1.2.3.4[4500] (362 bytes)
retransmit 2 of request with message ID 1
sending packet: from 192.168.0.11[4500] to 1.2.3.4[4500] (544 bytes)
sending packet: from 192.168.0.11[4500] to 1.2.3.4[4500] (362 bytes)
retransmit 3 of request with message ID 1
sending packet: from 192.168.0.11[4500] to 1.2.3.4[4500] (544 bytes)
sending packet: from 192.168.0.11[4500] to 1.2.3.4[4500] (362 bytes)
sending keep alive to 1.2.3.4[4500]
retransmit 4 of request with message ID 1
sending packet: from 192.168.0.11[4500] to 1.2.3.4[4500] (544 bytes)
sending packet: from 192.168.0.11[4500] to 1.2.3.4[4500] (362 bytes)
sending keep alive to 1.2.3.4[4500]
sending keep alive to 1.2.3.4[4500]
retransmit 5 of request with message ID 1
sending packet: from 192.168.0.11[4500] to 1.2.3.4[4500] (544 bytes)
sending packet: from 192.168.0.11[4500] to 1.2.3.4[4500] (362 bytes)
sending keep alive to 1.2.3.4[4500]
sending keep alive to 1.2.3.4[4500]
sending keep alive to 1.2.3.4[4500]
giving up after 5 retransmits
peer not responding, trying again (2/3)
establishing connection 'ikev2-1.2.3.4' failed

What can I do? What could the problem be? How to debug this?

**Comment by gunph1ld** [comment]
> What can I do? What could the problem be? How to debug this?
You need to check the strongswan logs on the server.

**Comment by InbarRose** [comment]
I actually eventually managed to solve this with the solution for https://github.com/trailofbits/algo/issues/305

fragmentation=no in ipsec.conf
