### ISSUE TITLE
Configure IPv6 on the VPN

### ISSUE THREAD

**Issue by dguido** [trailofbits/algo#8]
This is such an enormous pain in the ass, but to ensure that clients don't leak IPv6 requests we should configure this too. At least for Digital Ocean, this requires manual setup on their end to enable IPv6 for the VM.

[OpenDNS](https://support.opendns.com/entries/26056194-Does-OpenDNS-support-IPv6-) and [Google DNS](https://developers.google.com/speed/public-dns/docs/using) both have resolvers we can use.

There's something about proxying NDP requests that we need to figure out too, but I'm not sure what that is right now.

I think it's even possible that a client with a configured IPv6 address could leak requests outside the VPN if IPv6 is not supported by it...

**Comment by dguido** [comment]
Hm, I'm not sure this works right.

```
TASK [Setup the ipsec.conf file from our template] *****************************
fatal: [XXX.XXX.XXX.XXX]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'vpn_network_ipv6' is undefined"}
```

**Comment by gunph1ld** [comment]
That should work. What version of ansible do you use?
