### ISSUE TITLE
Switch to tags

### ISSUE THREAD

**Issue by defunctio** [trailofbits/algo#80]
Use tagging in playbooks to enable/disable tasks/roles. 

This would make using Algo much more flexible to be able to run `ansible-playbook ec2.yml -t vpn,sec,proxy` and skip the prompt of these steps.

**Comment by dguido** [comment]
This would make it easier for advanced users to script the install. We can keep the prompts in the bash script for normal people.

**Comment by gunph1ld** [comment]
Now we can use tags and extra-vars in CLI.
Need someone to tidy up readme

**Comment by defunctio** [comment]
I'm sure @dguido will take care of that.

**Comment by gunph1ld** [comment]
released
