### ISSUE TITLE
Digital Ocean DO Agent - Enable Monitoring

### ISSUE THREAD

**Issue by jwebbstevens** [trailofbits/algo#807]
### OS / Environment

VPN is on Digital Ocean UBUNTU 16.04
Local Machine is Mac running macOS High Sierra Version 10.13.3

### Ansible version
`ansible - version 2.2.1`

### Summary of the problem

Not a problem just a question

### Steps to reproduce the behavior

Run _algo_ on a Digital Ocean server

### Actual behavior

Digital Ocean has what they call a DO Agent which you can enable [monitoring](https://www.digitalocean.com/community/tutorials/how-to-install-and-use-the-digitalocean-agent-for-monitoring) on.  When spinning up a server via the UI you can toggle it on or off.  It doesn't look like algo turns this on.

According to them this is what the monitoring with the DO Agent does and does not do.

The DigitalOcean Agent is an open-source Go utility that forwards basic metrics about your Droplet to the DigitalOcean metrics backend.

Without the Agent, Droplet Graphs display information about:

**Public and private bandwidth usage**

- CPU activity
- Disk I/O
- With the Agent, DigitalOcean Monitoring features like alert policies are available, and Droplet Graphs can additionally show:

**Memory Usage**

- Disk Usage
- Top processes sorted by CPU and Memory
- The Agent currently supports Ubuntu 14.04 and higher, CentOS 6 and higher, and Debian 8. Fedora is supported if the Agent is installed manually with the installation script.

Visit the DigitalOcean Agent repository on [GitHub](https://github.com/digitalocean/do-agent) to check out the code itself.

### Question
I'm curious as to what having this on might do in terms of security, etc for running algo. I understand having this on forwards some metrics to Digital Oceans backend, but they seem relatively benign. I couldn't find much on this in the documentation.   If it is benign maybe adding the agent as part of the install process would be a good feature in a future build.

**Comment by jackivanov** [comment]
We would prefer to skip this in the deployment. You may deploy the monitoring agent after the server provisioned at your own risk.
