### ISSUE TITLE
OpenBSD as client?

### ISSUE THREAD

**Issue by rovaughn** [trailofbits/algo#810]
I just recently deployed Algo on AWS and everything appeared to go smoothly.

If this isn't the wrong place to ask, has anyone connected an OpenBSD workstation to the algo vpn?  It looks like it should just require the proper iked.conf information and the right files copied into /etc/iked, but it's unclear to me exactly what the config should look like and which files copied where.

Any insight or help would be appreciated.

**Comment by dguido** [comment]
Use WireGuard

**Comment by jungle-boogie** [comment]
@dguido,

There's one problem with your response. OpenBSD doesn't have support for go on arm64, but iked would work on arm64. That means an inexpensive arm64 device, such as a pine64 board, cannot be used with wireguard with OpenBSD. I can't fault the OpenBSD porters for not wanting to spend time on building go on arm64.
