### ISSUE TITLE
Potential Client App

### ISSUE THREAD

**Issue by Gerzer** [trailofbits/algo#820]
I built an open-source [DigitalOcean management app](https://github.com/Gerzer/Binary-Shark) using their API for iOS and watchOS. I'm looking into implementing the ability for users to quickly deploy an Algo instance. Ideally, I'd like to make it as easy for people to set up Algo as it would be to download a commercial VPN app from the App Store (with all of the well-documented risks that that would entail).

First of all, would this be technically possible? How much work would need to be done to port the Ansible scripts to something that can run in a sandboxed iOS app? Are there any important security considerations (e.g., storing keys/certificates so that Algo users can be added later)? Also, what would the licensing situation be? My app currently uses AGPL-3.0, but I'm open to changing it if there would be conflicts with Algo's MIT license.

Many of these questions I'll likely need to figure out for myself, but I'm seeking guidance and permission before I go down the rabbit hole, so to speak. Thank you in advance!

**Comment by dguido** [comment]
Hey, thanks for the comment! Very interested. Can you get in touch with me? dan@trailofbits.com
