### ISSUE TITLE
Cannot ping IP on algo VPN network

### ISSUE THREAD

**Issue by abhijitnathwani** [trailofbits/algo#821]
### OS / Environment
Amazon EC2 instance, Ubuntu

### Summary of the problem
I could successfully install Algo VPN on Amazon EC2 instance and connect Windows 10 as a client to the VPN Network. While i also did setup Windows 10 client on another system and got connected to the same VPN Network. The PPP Adapter IP address are also of the same subnet. I still cannot ping the IP address of one machine from other. The firewall has been disabled on both the system.

### The way of deployment (cloud or local)
Cloud

**Comment by dguido** [comment]
This is intended behavior, see config.cfg.

**Comment by abhijitnathwani** [comment]
But can you tell me why i cannot ping between two systems ? I could not understand that from `config.cfg`.

**Comment by abhijitnathwani** [comment]
Or can such a use case be achieved using Algo ? @dguido

**Comment by jatsrt** [comment]
@abhijitnathwani did you ever get any resolution on this?  I am looking to let clients connect to a private network that the algo server is part of, not client to client.  Was that your use case?

**Comment by abhijitnathwani** [comment]
Hi @jatsrt , 
No, I could not get any resolution on the said issue. Initially, I had the same use case as yours, however as I dug deeper into Algo, I believe we cannot achieve this.

**Comment by jatsrt** [comment]
So, with AWS this is possible.  Algo sets up a 0.0.0.0/0 route to be pushed to the client, so this essentially makes it an AWS problem more than anything else.  Algo also sets itself up in it's own VPC.   So if you configure VPC peering, configure the route tables to use that peer connection, then allow in from the algo VPC ip addresses what you want, it works.  

Peering .- Between Algo(eg 172.16.0.0/16) VPC and Account VPC(s)(eg 172.31.0.0/16)
Route Table - Add routes for 172.16/16 to 172.31 route tables
Security groups - example: SSH allow in from 172.16/16 to a host in 172.31

**Comment by ptsneves** [comment]
Ok so it seems that people did not do the minimum effort and this is why @dguido did not bother further.
In the config.cfg there is a specific setting to what we are talking about. Honestly without @dguido hint I would have not gotten there.

> # Block traffic between connected clients                                                                     
> BetweenClients_DROP: true

Change it to false.
