### ISSUE TITLE
Certificate Warnings and Root Certificate Warning Messages on iOS and Mac OS devices.

### ISSUE THREAD

**Issue by jwebbstevens** [trailofbits/algo#822]
### OS / Environment

VPN is on Digital Ocean UBUNTU 16.04.3 x64
Local Machine is Mac running macOS High Sierra Version 10.13.3 
and/or
iOS device running iOS 11.2.6

### Ansible version
`ansible - version 2.2.1`

### Summary of the problem

Not a problem just a question about _Certificate Warnings_ and _Root Certificate Warnings_ on  Apple Mac OS and iOS Devices. Are these okay to trust?  What are the steps to trust? I couldn't find in the documentation or I missed it somewhere in there. According to Apple I have to go into Certificate Trust Settings in order to manually trust this certificate [Trust manually installed certificate profiles in iOS](https://support.apple.com/en-us/HT204477). Is this even an issue?  The VPN works just fine if I do nothing. I just get nervous when seeing red unsigned notices and certificate warnings from APPLE that I don't understand.

### The way of deployment (cloud or local)
Cloud

### Steps to reproduce the behavior

- Run _algo_ on a Digital Ocean server
- Add the .mobileconfig file to a Mac OS or iOS Device follow onscreen instructions
- Warning messages provided by Mac OS or iOS Device appear

### Actual behavior

- Get warnings about certifcates and trusting  unsigned profiles, etc.

**Warning Message(s) on iOS Device**

![certificate warning - ios](https://user-images.githubusercontent.com/7277574/36997125-a1ac3488-2086-11e8-888a-77d4f40571df.png)

![root certificate warning - ios](https://user-images.githubusercontent.com/7277574/36997161-bda50f02-2086-11e8-96b7-f1485c05c6b0.png)

**Warning Message on Mac OS Device**

![unsigned on mac os 10 10 3 okay](https://user-images.githubusercontent.com/7277574/36997405-873a14f2-2087-11e8-96b7-7a99e5eed4fc.png)

### Full log

Shouldn't be needed since VPN works fine and these are just questions about how to handle the Certificates in iOS and Mac OS.

**Comment by dguido** [comment]
This is expected behavior. They're self-signed so they have extra warnings, and the only person with the keys is you. This is the whole point of Algo -- you're the only one who gets to see your traffic.

**Comment by jwebbstevens** [comment]
Cool, that makes sense. Thanks @dguido
