### ISSUE TITLE
setup failed

### ISSUE THREAD

**Issue by Nathantrinh** [trailofbits/algo#825]
### OS / Environment

Kali Linux

### Ansible version

2.4.3

### Version of components from `requirements.txt`

Name: setuptools
Version: 38.5.2
Summary: Easily download, build, install, upgrade, and uninstall Python packages
Home-page: https://github.com/pypa/setuptools
Author: Python Packaging Authority
Author-email: distutils-sig@python.org
License: UNKNOWN
Location: /root/algo/env/lib/python2.7/site-packages
Requires: 
---
Name: ansible
Version: 2.4.3.0
Summary: Radically simple IT automation
Home-page: https://ansible.com/
Author: Ansible, Inc.
Author-email: info@ansible.com
License: GPLv3+
Location: /root/algo/env/lib/python2.7/site-packages
Requires: cryptography, paramiko, setuptools, jinja2, PyYAML
---
Name: dopy
Version: 0.3.5
Summary: Python client for the Digital Ocean API
Home-page: https://github.com/devo-ps/dopy
Author: Vincent Viallet
Author-email: vincent@devo.ps
License: The MIT License (MIT)
Location: /root/algo/env/lib/python2.7/site-packages
Requires: requests
---
Name: boto
Version: 2.48.0
Summary: Amazon Web Services Library
Home-page: https://github.com/boto/boto/
Author: Mitch Garnaat
Author-email: mitch@garnaat.com
License: MIT
Location: /root/algo/env/lib/python2.7/site-packages
Requires: 
---
Name: boto3
Version: 1.6.6
Summary: The AWS SDK for Python
Home-page: https://github.com/boto/boto3
Author: Amazon Web Services
Author-email: UNKNOWN
License: Apache License 2.0
Location: /root/algo/env/lib/python2.7/site-packages
Requires: botocore, s3transfer, jmespath
---
Name: apache-libcloud
Version: 2.3.0
Summary: A standard Python library that abstracts away differences among multiple cloud provider APIs. For more information and documentation, please see http://libcloud.apache.org
Home-page: http://libcloud.apache.org/
Author: Apache Software Foundation
Author-email: dev@libcloud.apache.org
License: Apache License (2.0)
Location: /root/algo/env/lib/python2.7/site-packages
Requires: requests
---
Name: six
Version: 1.11.0
Summary: Python 2 and 3 compatibility utilities
Home-page: http://pypi.python.org/pypi/six/
Author: Benjamin Peterson
Author-email: benjamin@python.org
License: MIT
Location: /root/algo/env/lib/python2.7/site-packages
Requires: 
---
Name: pyOpenSSL
Version: 17.5.0
Summary: Python wrapper module around the OpenSSL library
Home-page: https://pyopenssl.org/
Author: Hynek Schlawack
Author-email: hs@ox.cx
License: Apache License, Version 2.0
Location: /root/algo/env/lib/python2.7/site-packages
Requires: cryptography, six
---
Name: Jinja2
Version: 2.8
Summary: A small but fast and easy to use stand-alone template engine written in pure python.
Home-page: http://jinja.pocoo.org/
Author: Armin Ronacher
Author-email: armin.ronacher@active-4.com
License: BSD
Location: /root/algo/env/lib/python2.7/site-packages
Requires: MarkupSafe
---
Name: shade
Version: 1.27.1
Summary: Simple client library for interacting with OpenStack clouds
Home-page: http://docs.openstack.org/shade/latest
Author: OpenStack
Author-email: openstack-dev@lists.openstack.org
License: UNKNOWN
Location: /root/algo/env/lib/python2.7/site-packages
Requires: openstacksdk, os-client-config, pbr
---
Name: pycrypto
Version: 2.6.1
Summary: Cryptographic modules for Python.
Home-page: http://www.pycrypto.org/
Author: Dwayne C. Litzenberger
Author-email: dlitz@dlitz.net
License: UNKNOWN
Location: /root/algo/env/lib/python2.7/site-packages
Requires: 

### Summary of the problem
fatal: [localhost]: FAILED! => {"msg": "The conditional check 'item not in strongswan_enabled_plugins and item not in strongswan_additional_plugins' failed. The error was: error while evaluating conditional (item not in strongswan_enabled_plugins and item not in strongswan_additional_plugins): Unable to look up a name or access an attribute in template string ({% if item not in strongswan_enabled_plugins and item not in strongswan_additional_plugins %} True {% else %} False {% endif %}).\nMake sure your variable name does not contain invalid characters like '-': argument of type 'StrictUndefined' is not iterable\n\nThe error appears to have been in '/root/algo/roles/vpn/tasks/ipec_configuration.yml': line 34, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Disable unneeded plugins\n  ^ here\n"}

### Steps to reproduce the behavior
Just run it in Kali.

### The way of deployment (cloud or local)

local

### Expected behavior

It works without fails.

### Actual behavior
It runs with fails.

### Full log

PLAY [Configure the server] ****************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [Local pre-tasks] *********************************************************
included: /root/algo/playbooks/local.yml for localhost

TASK [Generate the SSH private key] ********************************************
ok: [localhost]

TASK [Generate the SSH public key] *********************************************
ok: [localhost]

TASK [Change mode for the SSH private key] *************************************
ok: [localhost]

TASK [Ensure the dynamic inventory exists] *************************************
ok: [localhost]

TASK [Local pre-tasks] *********************************************************
skipping: [localhost]

TASK [local : Add the instance to an inventory group] **************************
skipping: [localhost]

TASK [local : Add the instance to an inventory group] **************************
changed: [localhost]

TASK [local : set_fact] ********************************************************
ok: [localhost]

TASK [local : Ensure the group local exists in the dynamic inventory file] *****
ok: [localhost]

TASK [local : Populate the dynamic inventory] **********************************
ok: [localhost]

PLAY [Configure the server and install required software] **********************

TASK [Common pre-tasks] ********************************************************
included: /root/algo/playbooks/common.yml for localhost

TASK [Check the system] ********************************************************
changed: [localhost]

TASK [Ubuntu pre-tasks] ********************************************************
skipping: [localhost]

TASK [FreeBSD pre-tasks] *******************************************************
skipping: [localhost]

TASK [include_tasks] ***********************************************************
included: /root/algo/playbooks/facts/main.yml for localhost

TASK [Gather Facts] ************************************************************
ok: [localhost]

TASK [Enable IPv6] *************************************************************
skipping: [localhost]

TASK [Generate password for the CA key] ****************************************
changed: [localhost -> localhost]

TASK [Generate p12 export password] ********************************************
changed: [localhost -> localhost]

TASK [Define password facts] ***************************************************
ok: [localhost]

TASK [Define the commonName] ***************************************************
ok: [localhost]

TASK [common : Install tools] **************************************************

TASK [common : Sysctl tuning] **************************************************

TASK [common : Install tools] **************************************************

TASK [common : Sysctl tuning] **************************************************

TASK [common : include_tasks] **************************************************
skipping: [localhost]

TASK [common : include_tasks] **************************************************
skipping: [localhost]

TASK [common : Install tools] **************************************************

TASK [common : Sysctl tuning] **************************************************

TASK [vpn : Ensure that the strongswan group exist] ****************************
ok: [localhost]

TASK [vpn : Ensure that the strongswan user exist] *****************************
ok: [localhost]

TASK [vpn : include_tasks] *****************************************************
skipping: [localhost]

TASK [vpn : include_tasks] *****************************************************
skipping: [localhost]

TASK [vpn : Install strongSwan] ************************************************
ok: [localhost]

TASK [vpn : include_tasks] *****************************************************
included: /root/algo/roles/vpn/tasks/ipec_configuration.yml for localhost

TASK [vpn : Setup the config files from our templates] *************************
ok: [localhost] => (item={u'dest': u'/etc/strongswan.conf', u'src': u'strongswan.conf.j2', u'group': u'root', u'mode': u'0644', u'owner': u'root'})
changed: [localhost] => (item={u'dest': u'/etc/ipsec.conf', u'src': u'ipsec.conf.j2', u'group': u'root', u'mode': u'0644', u'owner': u'root'})
ok: [localhost] => (item={u'dest': u'/etc/ipsec.secrets', u'src': u'ipsec.secrets.j2', u'group': u'root', u'mode': u'0600', u'owner': u'strongswan'})

TASK [vpn : Get loaded plugins] ************************************************
changed: [localhost]

TASK [vpn : Disable unneeded plugins] ******************************************
fatal: [localhost]: FAILED! => {"msg": "The conditional check 'item not in strongswan_enabled_plugins and item not in strongswan_additional_plugins' failed. The error was: error while evaluating conditional (item not in strongswan_enabled_plugins and item not in strongswan_additional_plugins): Unable to look up a name or access an attribute in template string ({% if item not in strongswan_enabled_plugins and item not in strongswan_additional_plugins %} True {% else %} False {% endif %}).\nMake sure your variable name does not contain invalid characters like '-': argument of type 'StrictUndefined' is not iterable\n\nThe error appears to have been in '/root/algo/roles/vpn/tasks/ipec_configuration.yml': line 34, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Disable unneeded plugins\n  ^ here\n"}

TASK [vpn : debug] *************************************************************
ok: [localhost] => {
    "fail_hint": [
        "Sorry, but something went wrong!", 
        "Please check the troubleshooting guide.", 
        "https://trailofbits.github.io/algo/troubleshooting.html"
    ]
}

TASK [vpn : fail] **************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed as requested from task"}

RUNNING HANDLER [vpn : restart strongswan] *************************************

PLAY RECAP *********************************************************************
localhost                  : ok=25   changed=6    unreachable=0    failed=2

**Comment by dguido** [comment]
Sorry, but we can't answer incomplete bug reports. Please add the missing details. Thanks!

**Comment by Nathantrinh** [comment]
Please help

**Comment by Nathantrinh** [comment]
Please
