### ISSUE TITLE
mobileconfig: container ".p12" must contain only one certificate and its private key on iOS

### ISSUE THREAD

**Issue by joshg** [trailofbits/algo#828]
### OS / Environment (where do you run Algo on)

Darwin Joshs-MBP-2015.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

### Cloud Provider or OS / Environment (where do you deploy Algo to)

Digital Ocean
 
### Summary of the problem

Running latest master (hash 3b19f1308282913bb6ab645bfad3de2846cf4ffd).
Only a single user (joshg) in the config.cfg users list.
Resulting joshg.mobileconfig installs fine on my MacBook pro - VPN is used.

Airdropping this to my iPhone 7 Plus, I get:

The container "joshg.p12" must contain only one certificate and its private key.
It will not install the VPN.

iOS 11.2.6 (Up-to-date as of today)

### Steps to reproduce the behavior

Git clone master
Following instructions w/ Digital Ocean
Airdrop the mobileconfig over to iPhone 7 Plus.
Observe p12 error noted.

**Comment by Benjamin-Lee** [comment]
Still getting this error on iOS 11.4.1, except with two users in the users list.

**Comment by Bozkurttt** [comment]
> ### OS / Environment (where do you run Algo on)
> Darwin Joshs-MBP-2015.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64
> 
> ### Cloud Provider or OS / Environment (where do you deploy Algo to)
> Digital Ocean
> 
> ### Summary of the problem
> Running latest master (hash [3b19f13](https://github.com/trailofbits/algo/commit/3b19f1308282913bb6ab645bfad3de2846cf4ffd)). Only a single user (joshg) in the config.cfg users list. Resulting joshg.mobileconfig installs fine on my MacBook pro - VPN is used.
> 
> Airdropping this to my iPhone 7 Plus, I get:
> 
> The container "joshg.p12" must contain only one certificate and its private key. It will not install the VPN.
> 
> iOS 11.2.6 (Up-to-date as of today)
> 
> ### Steps to reproduce the behavior
> Git clone master Following instructions w/ Digital Ocean Airdrop the mobileconfig over to iPhone 7 Plus. Observe p12 error noted.
