### ISSUE TITLE
Virtualenv Windows Subsystem undetected

### ISSUE THREAD

**Issue by lettucehead** [trailofbits/algo#831]
### OS / Environment (where do you run Algo on)

```
(env) chaznix@DESKTOP:~/algo/env/bin$ uname -a
Linux DESKTOP 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux
```

### Cloud Provider or OS / Environment (where do you deploy Algo to)

```
(env) chaznix@DESKTOP:~/algo/env/bin$ uname -a
Linux DESKTOP 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux
```
 

### Summary of the problem

Followed the instructions but virtualenv is not seen by pip (in ~/USER/algo/env/bin/python) even though it is succesfully installed and upgraded and so on by sudo apt-get.

### Steps to reproduce the behavior

1. Follow instructions
2. Notice the output immediately below
3. Note that this seems to cause the ansible playbook to not be found by the ./algo script
4. Editor's note: No idea why there are strikethroughs in the below, so plz ignore the mark indicating you shouldn't read it and don't ignore it

(env) chaznix@DESKTOP:~/algo$ sudo apt-get update && sudo apt-get install git build-essential libssl-dev libffi-dev python-dev python-pip python-setuptools python-virtualenv -y
Hit:1 http://archive.ubuntu.com/ubuntu xenial InRelease
Get:2 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
Get:3 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]
Get:4 http://archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB]
Fetched 306 kB in 5s (56.1 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
build-essential is already the newest version (12.1ubuntu2).
libffi-dev is already the newest version (3.2.1-4).
python-setuptools is already the newest version (20.7.0-1).
git is already the newest version (1:2.7.4-0ubuntu1.3).
libssl-dev is already the newest version (1.0.2g-1ubuntu4.10).
python-dev is already the newest version (2.7.12-1~16.04).
python-pip is already the newest version (8.1.1-2ubuntu0.4).
python-virtualenv is already the newest version (15.0.1+ds-3ubuntu1).
The following package was automatically installed and is no longer required:
  libfreetype6
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 116 not upgraded.
(env) chaznix@DESKTOP:~/algo$ python -m virtualenv --python=`which python2` env && source env/bin/activate && python -m pip install -U pip && python -m pip install -r requirements.txt
/home/chaznix/algo/env/bin/python: No module named virtualenv

### Full log

```
(env) chaznix@DESKTOP:~/algo/env/bin$ cd ~/algo
(env) chaznix@DESKTOP:~/algo$ ./algo

  What provider would you like to use?
    1. DigitalOcean
    2. Amazon Lightsail
    3. Amazon EC2
    4. Microsoft Azure
    5. Google Compute Engine
    6. Scaleway
    7. OpenStack (DreamCompute optimised)
    8. Install to existing Ubuntu 16.04 server

Enter the number of your desired provider
: 8

Enter the IP address of your server: (or use localhost for local installation)
[localhost]: localhost


What user should we use to login on the server? (note: passwordless login required, or ignore if you're deploying to localhost)
[root]:


Enter the public IP address of your server: (IMPORTANT! This IP is used to verify the certificate)
[]: ^V
no server IP given. exiting.
(env) chaznix@DESKTOP:~/algo$ ./algo

  What provider would you like to use?
    1. DigitalOcean
    2. Amazon Lightsail
    3. Amazon EC2
    4. Microsoft Azure
    5. Google Compute Engine
    6. Scaleway
    7. OpenStack (DreamCompute optimised)
    8. Install to existing Ubuntu 16.04 server

Enter the number of your desired provider
: 8

Enter the IP address of your server: (or use localhost for local installation)
[localhost]:


What user should we use to login on the server? (note: passwordless login required, or ignore if you're deploying to localhost)
[root]:


Enter the public IP address of your server: (IMPORTANT! This IP is used to verify the certificate)
[]: 2601:644:101:39c0:4c3b:ecb8:1bbb:4023


Was this server deployed by Algo previously?
[y/N]: N

Do you want macOS/iOS clients to enable "VPN On Demand" when connected to cellular networks?
[y/N]: N

Do you want macOS/iOS clients to enable "VPN On Demand" when connected to Wi-Fi?
[y/N]: N

Do you want to install a DNS resolver on this VPN server, to block ads while surfing?
[y/N]: y

Do you want each user to have their own account for SSH tunneling?
[y/N]: y

Do you want the VPN to support Windows 10 or Linux Desktop clients? (enables compatible ciphers and key exchange, less secure)
[y/N]: y

Do you want to retain the CA key? (required to add users in the future, but less secure)
[y/N]: N
./algo: line 67: ansible-playbook: command not found
(env) chaznix@DESKTOP:~/algo$
```

**Comment by jackivanov** [comment]
It seems the second command wasn't executed
```
sudo apt-get install git build-essential libssl-dev libffi-dev python-dev python-pip python-setuptools python-virtualenv -y
``

**Comment by lettucehead** [comment]
@jackivanov it seems like you are mixing up the 2nd cmds output with the first - i understand you to be incorrect. see below:
 python-virtualenv is already the newest version (15.0.1+ds-3ubuntu1).
... THATS the output of the 2ND command, just so we're 100% clear here. You may try it yourself (just attempt to install a python package with sudo apt-get install PKGNAME)

**Comment by lettucehead** [comment]
Please note that omitting the --python=`which python2` handled the situation. Guessing a uname -a variable may matter for whether that flag is needed.
