### ISSUE TITLE
Googles Jigsaw launches Outline

### ISSUE THREAD

**Issue by jwebbstevens** [trailofbits/algo#844]
Not an issue but it's interesting that a [Google's Jigsaw](https://jigsaw.google.com/) founded on *ahem* analyzing ones personal data.

Is launching a VPN  [Outline](https://getoutline.org/en/home).

It's great making this more widespread but what are the  high level differences with algo?

Here's the source [Jigsaw Github](https://github.com/Jigsaw-Code/?q=outline)

For that matter is there a non-issue place to discuss algo, like a forum or something? I hate to clog up the chat group.

#Teamalgo

**Comment by dguido** [comment]
I reviewed it briefly and it looks insanely unsafe to use. Besides basing it on a custom VPN protocol and software that has never seriously been studied (Shadowsocks), their server and client software is needlessly complex. I’m hoping we can make a blog post about it next week.

**Comment by davidemyers** [comment]
"Outline: The VPN That's Really Just A Proxy That Doesn't Handle UDP."

**Comment by jwebbstevens** [comment]
This is good to know,  thanks @davidemyers  and @dguido .

Would a client manager(like something built specifically for iOS) for algo introduce too many security issues and require constant updating? Or is a client manager just a vector for insecurity?  I see so many commercial VPN's that have client downloads that have pretty UI's and make it 'easy' to use/manage but they seem like they could be manipulated either by the vendor or some unknown actor.  Plus the maintenance and upgrades with new versions of OS's coming out often.

**Comment by dguido** [comment]
I'm building an iOS app now. It's just going very slowly since I am trying to solve the server setup issues in a zero-trust way so I have no access to any client data. This is tricky to do right.
