### ISSUE TITLE
VPN disconnecting after 10 minutes on macOS

### ISSUE THREAD

**Issue by sizeofcat** [trailofbits/algo#848]
### OS / Environment (where do you run Algo on)

```
Darwin zizoo-1 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64
```

### Cloud Provider (where do you deploy Algo to)

```
Google Compute Engine
```

### Summary of the problem

Every 10 minutes (precisely 10 minutes +/- less than 10 seconds) the VPN gets disconnected, I've read both 1. and I've applied the settings from 2. on both the GCE instance and the local macOS laptop and there is absolutely no change. The strange thing is that if I use a SSH tunnel to the algo instance, everything goes well and the connection is not dropped after 10 minutes. Also, none of the changes in 3. make any difference.

Any ideas?

1. https://cloud.google.com/compute/docs/networks-and-firewalls
2. https://cloud.google.com/compute/docs/troubleshooting/general-tips#communicatewithinternet
3. https://github.com/trailofbits/algo/issues/346

### Steps to reproduce the behavior

1. Deploy a default algo vpn to a Google Compute Engine with all the default settings (if I enable SSH tunnels or not, the disconnects still occur).
2. Doubleclick the .mobileconfig file and install the profile (and VPN).
3. Connect the VPN and after 10 minutes the connection is dropped. If I attempt to reconnect the VPN, it will fail, something might blacklist the connection, it does work after a "cooldown" period (about 2-3 minutes).

### Full log

```
Not sure the log is needed here, it's a default algo deployment, let me know if it's needed and I'll re-do a deploy.
```

**Comment by dguido** [comment]
GCP is pretty notorious for having this issue. I thought we worked around it but apparently not. Please try a different provider.
