### ISSUE TITLE
Windows 10 instructions not complete

### ISSUE THREAD

**Issue by marcovn** [trailofbits/algo#851]
The readme at https://github.com/trailofbits/algo#windows-10 fails to mention that you are required to also copy cacert.pem as well in order for the 'simple' installation to execute correctly.

In the manual instructions this is mentioned correctly.

**Comment by marcovn** [comment]
Following up to my own issue. This seems to have been addressed by PR #840

**Comment by jackivanov** [comment]
PR merged
