### ISSUE TITLE
Issue when installing Algo in ubuntu

### ISSUE THREAD

**Issue by LeilaAhmad** [trailofbits/algo#856]
### OS / Environment 

Ubuntu 16.04.4 x64

### Cloud Provider

digitalocean

### Summary of the problem

I get this error when running .algo

### Full log

[DEPRECATION WARNING]: ec2_ami_find is kept for backwards compatibility but
usage is discouraged. The module documentation details page may explain more
about this rationale.. This feature will be removed in a future release.
Deprecation warnings can be disabled by setting deprecation_warnings=False in
ansible.cfg.

PLAY [Configure the server] ****************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [Local pre-tasks] *********************************************************
included: /root/algo/playbooks/local.yml for localhost

TASK [Local pre-tasks] *********************************************************
skipping: [localhost]

TASK [local : Add the instance to an inventory group] **************************
skipping: [localhost]

TASK [local : Add the instance to an inventory group] **************************
changed: [localhost]

TASK [local : set_fact] ********************************************************
ok: [localhost]

TASK [local : Ensure the group local exists in the dynamic inventory file] *****
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Destination configs/inventory.dynamic does not exist !", "rc": 257}

TASK [local : debug] ***********************************************************
ok: [localhost] => {
    "fail_hint": [
        "Sorry, but something went wrong!",
        "Please check the troubleshooting guide.",
        "https://trailofbits.github.io/algo/troubleshooting.html"
    ]
}

TASK [local : fail] ************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed as requested from task"}

PLAY RECAP *********************************************************************
localhost                  : ok=5    changed=1    unreachable=0    failed=2

**Comment by jackivanov** [comment]
The full log should include how you run algo. 
It seems you don't use the [requirements](https://github.com/trailofbits/algo/blob/master/requirements.txt)
