### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by grcasanova** [trailofbits/algo#86]
I have tried using algo on a Ubuntu 14.04 VM but, although the deployment ends up successfully, no configuration files or certificates are created. Likewise, privoxy, Apache and auditd are not installed at the end of the process (used the default settings when performing the installation).

**Comment by dguido** [comment]
Ubuntu 14.04 is not a supported platform. Please try again on 16.04 and let me know if it works.

**Comment by grcasanova** [comment]
Dear @dguido, I solved doing a release upgrade but I am now facing another issue.
In your Readme there is no reference to the ports to be opened to allow the VPN connections. I supposed traditional IPSec ports (i.e. 500 and 4500), if that is the case it may be worth adding somewhere in the documentation.
Thank you
