### ISSUE TITLE
Issue on mac when setting up new DigitalOcean instance

### ISSUE THREAD

**Issue by lookatmeimdanny** [trailofbits/algo#865]
###

Darwin 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64

Do you want to retain the CA key? (required to add users in the future, but less secure)
[y/N]: y

ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/Users/danny/Projects/algo/roles/cloud-ec2/tasks/main.yml': line 22, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    - include_tasks: encrypt_image.yml
      ^ here

The error appears to have been in '/Users/danny/Projects/algo/roles/cloud-ec2/tasks/main.yml': line 22, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    - include_tasks: encrypt_image.yml
      ^ here

### Cloud Provider (where do you deploy Algo to)

DigitalOcean

### Summary of the problem

You tell me -- not sure why it's suddenly throwing this error.

### Steps to reproduce the behavior

Run algo, try and set up a default new VPN droplet on DigitalOcean?

### Full log

  What provider would you like to use?
    1. DigitalOcean
    2. Amazon Lightsail
    3. Amazon EC2
    4. Microsoft Azure
    5. Google Compute Engine
    6. Scaleway
    7. OpenStack (DreamCompute optimised)
    8. Install to existing Ubuntu 16.04 server (Advanced)

Enter the number of your desired provider
: 1

Enter your API token. The token must have read and write permissions (https://cloud.digitalocean.com/settings/api/tokens):
[pasted values will not be displayed]
: 

Name the vpn server:
[algo.local]: 

  What region should the server be located in?
    1.  Amsterdam        (Datacenter 2)
    2.  Amsterdam        (Datacenter 3)
    3.  Frankfurt
    4.  London
    5.  New York         (Datacenter 1)
    6.  New York         (Datacenter 2)
    7.  New York         (Datacenter 3)
    8.  San Francisco    (Datacenter 1)
    9.  San Francisco    (Datacenter 2)
    10. Singapore
    11. Toronto
    12. Bangalore
Enter the number of your desired region:
[7]: 1

Do you want macOS/iOS clients to enable "VPN On Demand" when connected to cellular networks?
[y/N]: 

Do you want macOS/iOS clients to enable "VPN On Demand" when connected to Wi-Fi?
[y/N]: 

Do you want to install a DNS resolver on this VPN server, to block ads while surfing?
[y/N]: y

Do you want each user to have their own account for SSH tunneling?
[y/N]: 

Do you want the VPN to support Windows 10 or Linux Desktop clients? (enables compatible ciphers and key exchange, less secure)
[y/N]: 

Do you want to retain the CA key? (required to add users in the future, but less secure)
[y/N]: y
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/Users/danny/Projects/algo/roles/cloud-ec2/tasks/main.yml': line 22, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    - include_tasks: encrypt_image.yml
      ^ here

The error appears to have been in '/Users/danny/Projects/algo/roles/cloud-ec2/tasks/main.yml': line 22, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    - include_tasks: encrypt_image.yml
      ^ here

**Comment by jackivanov** [comment]
Follow the [steps](https://github.com/trailofbits/algo#deploy-the-algo-server) and install/upgrade the requirements
