### ISSUE TITLE
Windows generated .ps1 config file has syntax errors with PowerShell run as administrator

### ISSUE THREAD

**Issue by jzxc1** [trailofbits/algo#868]
Windows 8 x64 Latest Updates
Right clicking and running power shell with this command gives an error:

PS C:\Windows\system32> powershell -ExecutionPolicy ByPass -File C:\Users\a\Documents\windows_a.ps1 -Add
At C:\Users\a\Documents\windows_a.ps1:1 char:11
+ #Requires -RunAsAdministrator
+           ~~~~~~~~~~~~~~~~~~~
Parameter RunAsAdministrator requires an argument.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : ParameterRequiresArgument

Deleted 1st line from windows_a.ps1:
#Requires -RunAsAdministrator

Now error:
PS C:\Windows\system32> powershell -ExecutionPolicy ByPass -File C:\Users\a\Documents\windows_a.ps1 -Add
Pkcs12DecryptionPassword: ********
New-TemporaryDirectory : The term 'New-Guid' is not recognized as the name of
a cmdlet, function, script file, or operable program. Check the spelling of
the name, or if a path was included, verify that the path is correct and try
again.
At C:\Users\a\Documents\windows_a.ps1:158 char:16
+     $workDir = New-TemporaryDirectory
+                ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (New-Guid:String) [New-Temporary
   Directory], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException,New-TemporaryDirectory

**Comment by Recluse** [comment]
You need PowerShell 5 for this, else replace `New-Guid` to `[guid]::newguid()` in windows_a.ps1

**Comment by mrled** [comment]
@jzxc1 if you modify the script as @Recluse suggests above, does that fix the problem for you? If so, I can submit a PR with that fix in it.

If it doesn't, I am happy to help continue some Windows 8 troubleshooting. I don't have a Windows 8 machine, so I would request some patience, but if you're willing to work with me on getting it fixed, I will do my best to help.
