### ISSUE TITLE
Test Android support

### ISSUE THREAD

**Issue by TheNomad11** [trailofbits/algo#87]
Hi, I just installed Algo on Ubuntu 16, Digitalocean and tried to connect via Strongswan app on Android. I got the error message "Could not load private key".

I installed the xxxjack.p12 certificate, is there something more I should do? Thanks for your time and patience with a newbee… (connection with ios-mobileconfig device works fine)

**Comment by defunctio** [comment]
I don't think it had actually been tested with Android yet. I've been meaning to look into this but I haven't had the time.

**Comment by TheNomad11** [comment]
Aha, ok, until then it might be a good idea to remove any references to Android in the readme-file. Good luck with the testing!

**Comment by dguido** [comment]
It should work fine, as long as we generate the right file formats. What certificate file formats does the StrongSwan client on Android typically accept? Have you ever gotten it to work before?

**Comment by TheNomad11** [comment]
I've used this here with the StrongSwan app for a few weeks and it is working perfect, it is using a xxx.p12 file in addition to username and password https://expats-in-china.com/t/setup-a-vpn-ipsec-on-centos-7-using-strongswan/27 

I am using another vpn script for iOS always on vpn, so I was hoping your solution would cover both devices. That's another thing I'd like to ask you for: integrate the always-on funtion in the mobileconfig file as done here https://github.com/gaomd/docker-ikev2-vpn-server

**Comment by dguido** [comment]
Silly question, but in addition to the user cert, did you install the CA cert on the Android app? It is [IP]_ca.crt.

**Comment by TheNomad11** [comment]
Yes, I did but it didn't help

**Comment by defunctio** [comment]
Did anyone else have a chance to follow up on this?

**Comment by gunph1ld** [comment]
Just checked on Android 5.0.2. it works perfectly. Of course need to import p12 certificate, that's it.
