### ISSUE TITLE
DHCP Assigning the same ip address

### ISSUE THREAD

**Issue by gustavohellwig** [trailofbits/algo#870]
### OS / Environment (where do you run Algo on)
```
Linux aldo 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

### Cloud Provider (where do you deploy Algo to)

```
Ubuntu 16.04.4 LTS
```

### Summary of the problem

Hi,
Everything looks good in my environment. I changed the rightsourceip=%dhcp and the clients can get an IP address from the DHCP Server and can go to LAN and WAN without any problem, but.....all the clients get the same IP address from the DHCP Server. I have tested with another DHCP Server (1st was a Firewall DHCP and 2nd was a Windows Server DHCP) and it's the same.

My Config files are:
/etc/ipsec.conf
`config setup
    uniqueids=never # allow multiple connections per user
    charondebug="ike 2, knl 2, cfg 2, net 2, esp 2, dmn 2,  mgr 2"

conn %default
    fragmentation=yes
    rekey=no
    dpdaction=clear
    keyexchange=ikev2
    compress=yes
    dpddelay=35s

    ike=aes128gcm16-prfsha512-ecp256,aes128-sha2_512-prfsha512-ecp256,aes128-sha2_384-prfsha384-ecp256!
    esp=aes128gcm16-ecp256,aes128-sha2_512-prfsha512-ecp256!

    left=%any
    leftauth=pubkey
    leftid=10.10.0.22
    leftcert=10.10.0.22.crt
    leftsendcert=always
    leftsubnet=0.0.0.0/0

    right=%any
    rightauth=pubkey
    rightsourceip=%dhcp
    #rightsourceip=172.16.0.0/16
    rightdns=local dns IP address 1, local dns IP address 1
conn ikev2-pubkey
    auto=add

`

/etc/strongswan.d/charon/dhcp.conf
`dhcp {
    force_server_address = yes
    identity_lease = yes
    interface = eth0
    load = yes
    server = 10.10.0.1 #DHCP IP address
}`

Questions 1: How to fix that the DHCP gives a different IP address to each VPN Client ?
Questions 2: If I use this config in the IPSec.conf (rightsourceip=10.10.0.0/16 ), works, but to the firewall, all the connections looks like that come from the same IP address. Like the server have free access to the internet, but the Clients should auth first.

**Comment by gustavohellwig** [comment]
Like...I made a test using rightsourceip=10.10.1.247/32 and the client works with no problem, but for the firewall, looks like the connection comes from the server. The server have free access to the internet, but the Clients should auth first.

How to change the way that the VPN Client go to the LAN, to because a normal client ?
Or how to fix the DHCP Issue that gives the same IP address to all the VPN Client?

**Comment by jackivanov** [comment]
It's not really related to Algo, we use StrongSwan under the hood, If you want to modify something I'd suggest you to dive into the StrongSwan docs.
