### ISSUE TITLE
not installing on debian and centos

### ISSUE THREAD

**Issue by broros** [trailofbits/algo#878]
### OS / Environment (where do you run Algo on)

```
Debian 9,  centos 7
```

### Cloud Provider (where do you deploy Algo to)

```
google cloud vm
```

### Summary of the problem

The current documentation does not work with  debian 9 or centos 7,  can you fix this?

**Comment by dguido** [comment]
No

**Comment by stefaang** [comment]
Here's how to install Algo on Debian Stretch.
You need to install apparmor and enable it in your kernel. See [here](https://wiki.debian.org/AppArmor/HowToUse)
Then install wireguard from the unstable repo, see [here](https://www.wireguard.com/install/).
Then comment the first task in `roles/wireguard/tasks/ubuntu.yml` as your don't need the ubuntu ppa.
Then run the installer for Ubuntu 18.
