### ISSUE TITLE
Slow Connection

### ISSUE THREAD

**Issue by grcasanova** [trailofbits/algo#88]
Dears,
I have run algo script with default setup in a clean ubuntu VM but the Internet speed is highly impacted, so that the overall speed goes down to less than a couple of Kb per second.

**Comment by dguido** [comment]
I'm not sure how to debug this... the speed that your Algo VPN works is entirely dependent on how fast you can reach the VPS it is setup on. Try SSH'ing to your VPS and seeing if the speed is any different. You might also try setting up on a different VPS provider or choosing a different datacenter location.
