### ISSUE TITLE
OnDemand rules is lost when using ./algo update-users

### ISSUE THREAD

**Issue by lgg** [trailofbits/algo#885]
### OS / Environment (where do you run Algo on)
```
Linux vpn1-algo-am 4.4.0-119-generic #143-Ubuntu SMP Mon Apr 2 16:08:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

### Cloud Provider (where do you deploy Algo to)
local server

### Summary of the problem
Expected user.mobileconfig to have 
```
<key>OnDemandEnabled</key>
                <integer>1</integer>
              <key>OnDemandRules</key>
              <array>
                  <dict>
                    <key>Action</key>
                      <string>Connect</string>
                      <key>InterfaceTypeMatch</key>
                      <string>WiFi</string>
                    <key>URLStringProbe</key>
                      <string>http://captive.apple.com/hotspot-detect.html</string>
                  </dict>
                  <dict>
                    <key>Action</key>
                      <string>Connect</string>
                      <key>InterfaceTypeMatch</key>
                      <string>Cellular</string>
                    <key>URLStringProbe</key>
                      <string>http://captive.apple.com/hotspot-detect.html</string>
                  </dict>
                </array>
```
after running `./algo update-users`

But user.mobileconfig doesn't include this part

### Steps to reproduce the behavior
1. Clear install algo from git
2. run `./algo` and answer YES to all OnDemand questions -> now we have OnDemand section in .mobileconfig files
3. add new user to config.cfg
4. run `./algo update-users` -> No questions for OnDemand rule and now OnDemand section on .mobileconfig files

**Comment by digeratus** [comment]
While this is working on the new WIP ansbile2.5 branch, it isn't yet in master. Is the only alternative to wait for the WIP?

**Comment by lgg** [comment]
@digeratus i have forked this repo: https://github.com/lgg/algo-inserted-p12 it hot-fixed there
