### ISSUE TITLE
easyrsa error

### ISSUE THREAD

**Issue by mykesh** [trailofbits/algo#89]
I'm getting the following error:

fatal: [localhost]: FAILED! => {"changed": true, "cmd": "./easyrsa --subject-alt-name='DNS:localhost,IP:localhost' build-server-full localhost nopass && touch '/opt/easy-rsa-ipsec/easyrsa3/pki/server_initialized'", "delta": "0:00:00.021416", "end": "2016-09-25 21:07:12.371746", "failed": true, "rc": 1, "start": "2016-09-25 21:07:12.350330", "stderr": "Error Loading request extension section req_extra\n140669356271256:error:220A4076:X509 V3 routines:a2i_GENERAL_NAME:bad ip address:v3_alt.c:476:value=localhost\n140669356271256:error:22098080:X509 V3 routines:X509V3_EXT_nconf:error in extension:v3_conf.c:95:name=subjectAltName, value=DNS:localhost,IP:localhost\n\nEasy-RSA error:\n\nFailed to generate request", "stdout": "", "stdout_lines": [], "warnings": []}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
localhost                  : ok=29   changed=4    unreachable=0    failed=1

**Comment by dguido** [comment]
What OS did you run the Algo installer on? Which options did you choose?

**Comment by mykesh** [comment]
option 4

version:
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial

**Comment by dguido** [comment]
It looks like you put in "localhost" as the public IP?

**Comment by mykesh** [comment]
nope, used my public IP.

I put 'localhost' in "IP address of your server:"; the second option of "./algo"
