### ISSUE TITLE
Add Wireguard

### ISSUE THREAD

**Issue by dguido** [trailofbits/algo#893]
- Add Wireguard to the default install of Algo
- Make Wireguard the default method for Android users
- Stop making sswan and helper files for IPSEC for Android

**Comment by axiomdata** [comment]
Woo hoo!!! Yes please!

**Comment by jackivanov** [comment]
Found this [here](https://play.google.com/store/apps/details?id=com.wireguard.android&hl=en)
> Alpha software. Use at your own risk. There are certainly scary bugs.
