### ISSUE TITLE
Add optional support for Windows 10

### ISSUE THREAD

**Issue by dguido** [trailofbits/algo#9]
https://wiki.strongswan.org/projects/strongswan/wiki/IKEv2CipherSuites

There are decent docs available for [Windows 7](https://technet.microsoft.com/library/dd125380.aspx) but it's hard to find if anything changed in Windows 10. It looks like some of these might work but more testing is required:

Encryption: aes128
Integrity: sha1
DH Group: modp1024

**Comment by Alekseykua** [comment]
Interested in helping here

**Comment by dguido** [comment]
@Alekseykua Thanks! Install Algo on a cloud server, then set it up on Windows 10. Tell us if it works! StrongSwan is only configured with a single cipher suite right now, so if it works, then we'll know that Windows 10 supports all the same ciphers and modes that iOS, OS X, Android, etc. do.

**Comment by dguido** [comment]
Windows appears to offer to following for IKE

```
12[CFG] received proposals: IKE:3DES_CBC/HMAC_SHA1_96/PRF_HMAC_SHA1/MODP_1024, IKE:3DES_CBC/HMAC_SHA2_256_128/PRF_HMAC_SHA2_256/MODP_1024, IKE:3DES_CBC/HMAC_SHA2_384_192/PRF_HMAC_SHA2_384/MODP_1024, IKE:AES_CBC_128/HMAC_SHA1_96/PRF_HMAC_SHA1/MODP_1024, IKE:AES_CBC_128/HMAC_SHA2_256_128/PRF_HMAC_SHA2_256/MODP_1024, IKE:AES_CBC_128/HMAC_SHA2_384_192/PRF_HMAC_SHA2_384/MODP_1024, IKE:AES_CBC_192/HMAC_SHA1_96/PRF_HMAC_SHA1/MODP_1024, IKE:AES_CBC_192/HMAC_SHA2_256_128/PRF_HMAC_SHA2_256/MODP_1024, IKE:AES_CBC_192/HMAC_SHA2_384_192/PRF_HMAC_SHA2_384/MODP_1024, IKE:AES_CBC_256/HMAC_SHA1_96/PRF_HMAC_SHA1/MODP_1024, IKE:AES_CBC_256/HMAC_SHA2_256_128/PRF_HMAC_SHA2_256/MODP_1024, IKE:AES_CBC_256/HMAC_SHA2_384_192/PRF_HMAC_SHA2_384/MODP_1024
```

**Comment by dguido** [comment]
The [LibreSwan documentation (https://libreswan.org/wiki/VPN_server_for_remote_clients_using_IKEv2) was a little bit more clear on the certificate requirements. In each of the cases below, our certificates were already correctly generated by easy-rsa-ipsec (thank you [ValdikSS](https://github.com/ValdikSS)!)

* The VPN gateway's certificate must have its DNS name as SubjectAltname (SAN) in the certificate. The client then must connect to the VPN using the DNS name. Alternately, the client can connect using the IP if the SAN contains the IP address of the gateway.
* The VPN gateway's certificate must have the Digital Signature and Key Encipherment KU extensions if the SAN and CN use the same, full DNS name. It must also have the serverAuth EKU extension. It may have also have the clientAuth EKU extension.

To import the certs, place the user certificate in LocalMachine->Personal Certificates and the CA certificate to LocalMachine->Trusted Root Certification Authorities. You also need to open the VPN adapter in the network control panel, right click and choose properties, then go to Security->Authentication->Use machine certificates. I would probably choose "Data Encryption: Maximum strength encryption" for good measure too...

In the process of working this out, I discovered that the cipher situation for ESP is even worse than IKE:

```
13[CFG] received proposals:
ESP:AES_CBC_256/HMAC_SHA1_96/NO_EXT_SEQ,
ESP:AES_CBC_128/HMAC_SHA1_96/NO_EXT_SEQ,
ESP:3DES_CBC/HMAC_SHA1_96/NO_EXT_SEQ,
ESP:DES_CBC/HMAC_SHA1_96/NO_EXT_SEQ,
ESP:NULL/HMAC_SHA1_96/NO_EXT_SEQ
```

This means the best setting we can get for ESP is: `aes256-sha1-modp1024`

Now to retry all of this with ECC certificates and see if it fails...

**Comment by dguido** [comment]
Yep, I get an error from Windows that says `IKE failed to find valid machine certificate...` when I redo everything with the original ECC certificate setup. It looks like Windows only works with RSA certificates.

@gunph1ld We need to make a configuration option that asks "Do you want to support Windows VPN clients (enables weak ciphers)? y/n?" Selecting it should do the following:

1. Change easy-rsa-ipsec to build RSA certificates and ipsec.secrets to use an RSA certificate
2. Add the extra set of ciphers to the IKE and ESP parameters in ipsec.conf

**Comment by Thermi** [comment]
You don't necessarily have to *switch* from ECDSA to RSA. You can just run them side by side.

**Comment by finnoybu** [comment]
Is this at all helpful?

https://www.niap-ccevs.org/st/st_vid10529-agd.pdf

Section 2.2.2.2 Configuring DH Group 14 and AES256 for IKEv2 (p.21)

**Comment by Thermi** [comment]
That's actually superbly helpful, if it works.

**Comment by dguido** [comment]
Thanks! It looks like there is a somewhat undocumented `NegotiateDH2048_AES256` registry key that enables modp2048 (Group 14). That improves things out of [WeakDH](https://weakdh.org/) range, but the overall setup still uses AES-CBC, non-ECC DH, and RSA certificates.

That is really good to know. I never would have found this option!

**Comment by sanitybit** [comment]
> Let me know if you think there is something else I can do besides ship a .reg file to set that key and upgrade the DH to modp2048!

If your goal is to avoid shipping a file, you could just tell Windows 10 users to run this as an administrator:

`reg add HKLM\System\CurrentControlSet\Services\Rasman\Parameters /v NegotiateDH2048_AES256 /t REG_DWORD /d 1 /f`

**Comment by Thermi** [comment]
> [...] , especially in quick mode, [...]

It has to be config mode. If quick mode is used, no "virtual" IP and no DNS servers are assigned, making the whole set up useless. Only because Windows supports it doesn't mean it's meaningful. The ciphers do not differ between the modes, though.

**Comment by vdm** [comment]
According to this 29 September blog post, the most secure options are available only through Powershell, not the registry.

http://www.stevenjordan.net/2016/09/secure-ikev2-win-10.html
https://technet.microsoft.com/en-us/library/dn262642.aspx

**Comment by dguido** [comment]
$250 bounty! Submit a pull request and email dan@trailofbits.com to claim it. Partial solutions may be rewarded.

**Comment by andyeff** [comment]
Hi all, gave the latest commit of the win10_support branch a try again today, and was able to get a successful connection to a Digital Ocean droplet through Algo.

There was a curiosity that a MacOS client wasn't able to establish a connection until AFTER a Windows 10 box had tried, I shall attempt to reproduce it later with a new droplet / test and see if if it's a repeatable issue or not.

Thanks @dguido, @gunph1ld, and everyone else for negotiating the minefield of Windows IKEv2 support and getting a working deployment available :)

**Comment by gunph1ld** [comment]
@andyeff As I know It's a restriction of IKEv2. You can't use more then 1 clients behind 1 IP-NAT (say 1 router)

**Comment by andyeff** [comment]
@gunph1ld Ah, this was attempting to connect from a Mac before even trying with Windows, rather than trying to have two stable connections up at once.

I'll fire up another droplet and confirm now. I certainly had no problems going Mac-first over the last couple of days so maybe it was a freak networking issue locally.

**Comment by Thermi** [comment]
@gunph1ld 
" As I know It's a restriction of IKEv2. You can't use more then 1 clients behind 1 IP-NAT (say 1 router)"
That's absolutely wrong. It always works, except when you use naive IPsec with transport mode (and L2TP), then you need to fix it on the server side by using CONNMARK and other fun and semi-complex stuff, or when the NAT router implements broken IPsec "passthrough" (basically NATS all local IKE and NAT-T traffic to port 500), which prevents the router itself from differentiating the two data streams for the two different clients.

**Comment by gunph1ld** [comment]
Then, sorry me, I was wrong, I was thinking about the transport mode. Thanks @Thermi

**Comment by andyeff** [comment]
@gunph1ld New droplet just worked fine first time with MacOS, so as far as I can tell this is now a valid easy deployment VPN for Win10 + Mac (on Digitalocean at least). Thanks!

**Comment by wampum** [comment]
Does this doc provide any useful info regarding ECDSA certs? Also seems to suggest GCM may be doable in quick mode.

[https://www.niap-ccevs.org/st/st_vid10746-agd.pdf](url)

**Comment by Thermi** [comment]
Don't use quick mode. Use config mode. You need to assign virtual IPs to initiators. That forces the use of config mode.

**Comment by jauderho** [comment]
This is the current suggested command to set up VPN.

Set-VpnConnectionIPsecConfiguration -ConnectionName "Algo" -AuthenticationTransformConstants SHA256128 -CipherTransformConstants AES256 -EncryptionMethod AES256 -IntegrityCheckMethod SHA256 -DHGroup Group14 -PfsGroup none

For Windows 10, https://technet.microsoft.com/itpro/powershell/windows/vpnclient/set-vpnconnectionipsecconfiguration suggests that we could utilize some stronger options. 

Maybe, 

- -DHGroup ECP256
- -AuthenticationTransformConstants GCMAES128
- -CipherTransformConstants GCMAES128

Not sure about PfsGroup.

**Comment by dguido** [comment]
I noticed this as well while I was making my IPSEC Crypto Wall of Shame. Worth a second look.

**Comment by Thermi** [comment]
You should definitively use PFS, preferably with a large (strong) group.

**Comment by jauderho** [comment]
This might also make it unnecessary to have a Windows downgrade based on the ciphers picked. 

@dguido per @sanitybit 's registry setting above, the following should be the PowerShell equivalent.

> If (!(Test-Path "HKLM:\System\CurrentControlSet\Services\Rasman\Parameters")) {
>   New-Item -Path "HKLM:\System\CurrentControlSet\Services\Rasman\Parameters" | Out-Null
> }
> Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Services\Rasman\Parameters" -Name "NegotiateDH2048_AES256" -Type DWord -Value 1

**Comment by dguido** [comment]
We couldn't get this to work the last time we tried. Can someone grab a copy of Windows 10 Creators Update and try enabling the ciphers from https://github.com/trailofbits/algo/issues/9#issuecomment-294272215 ? You'll want to setup Algo in the default configuration and see if you can get it to connect.

**Comment by MiWCryptAnalytics** [comment]
I don't believe you need to configure PFS in IKEv2, as it is implicitly FS in all its rekeying.
Explicit PFS group is for IKEv1. StrongSWAN may ignore this anyway with IKEv2 setup.

Ill grab the creators update and try with the strong ciphers. I'm keen to get GCM working hardware acceleration e/d. I noticed it was defaulting to CBC.

**Comment by bshiznit** [comment]
Getting policy mismatch when I update those - I am on build 15063.138 which is creator's update :)

**Comment by Thermi** [comment]
@MiWCryptAnalytics There's no implicit PFS with either IKEv1 or IKev2. PFS requres an explicit KE payload from the peer that initiates the rekeying. PFS only applies to new CHILD_SAs, after the initial one (the first one) was created. I'm testing either combination of proposals now.

**Comment by Thermi** [comment]
When the server only supports PFS, but the client doesn't support it:

```
Sun, 2017-04-16 19:11 27[CFG] <larval-drop-test|12> selecting proposal:
Sun, 2017-04-16 19:11 27[CFG] <larval-drop-test|12>   no acceptable DIFFIE_HELLMAN_GROUP found
Sun, 2017-04-16 19:11 27[CFG] <larval-drop-test|12> received proposals: ESP:CHACHA20_POLY1305_256/NO_EXT_SEQ
Sun, 2017-04-16 19:11 27[CFG] <larval-drop-test|12> configured proposals: ESP:CHACHA20_POLY1305_256/NEWHOPE_128/NO_EXT_SEQ
Sun, 2017-04-16 19:11 27[IKE] <larval-drop-test|12> no acceptable proposal found
Sun, 2017-04-16 19:11 27[IKE] <larval-drop-test|12> failed to establish CHILD_SA, keeping IKE_SA
Sun, 2017-04-16 19:11 27[ENC] <larval-drop-test|12> generating CREATE_CHILD_SA response 5 [ N(NO_PROP) ]
```

When the client supports it, but the server doesn't:
```
Sun, 2017-04-16 19:13 16[NET] <larval-drop-test|13> received packet: from 2a02:8071:9288:7d00:152e:c6ca:a545:f543[4500] to 2a03:4000:13:10a::1[4500] (1228 bytes)
Sun, 2017-04-16 19:13 16[ENC] <larval-drop-test|13> parsed CREATE_CHILD_SA request 2 [ EF(1/2) ]
Sun, 2017-04-16 19:13 16[ENC] <larval-drop-test|13> received fragment #1 of 2, waiting for complete IKE message
Sun, 2017-04-16 19:13 23[NET] <larval-drop-test|13> received packet: from 2a02:8071:9288:7d00:152e:c6ca:a545:f543[4500] to 2a03:4000:13:10a::1[4500] (922 bytes)
Sun, 2017-04-16 19:13 23[ENC] <larval-drop-test|13> parsed CREATE_CHILD_SA request 2 [ EF(2/2) ]
Sun, 2017-04-16 19:13 23[ENC] <larval-drop-test|13> received fragment #2 of 2, reassembling fragmented IKE message
Sun, 2017-04-16 19:13 23[ENC] <larval-drop-test|13> parsed CREATE_CHILD_SA request 2 [ N(REKEY_SA) N(USE_TRANSP) SA No KE TSi TSr ]
Sun, 2017-04-16 19:13 23[CFG] <larval-drop-test|13> selecting proposal:
Sun, 2017-04-16 19:13 23[CFG] <larval-drop-test|13>   no acceptable DIFFIE_HELLMAN_GROUP found
Sun, 2017-04-16 19:13 23[CFG] <larval-drop-test|13> received proposals: ESP:CHACHA20_POLY1305_256/NEWHOPE_128/NO_EXT_SEQ
Sun, 2017-04-16 19:13 23[CFG] <larval-drop-test|13> configured proposals: ESP:CHACHA20_POLY1305_256/NO_EXT_SEQ
Sun, 2017-04-16 19:13 23[IKE] <larval-drop-test|13> no acceptable proposal found
Sun, 2017-04-16 19:13 23[IKE] <larval-drop-test|13> failed to establish CHILD_SA, keeping IKE_SA
Sun, 2017-04-16 19:13 23[ENC] <larval-drop-test|13> generating CREATE_CHILD_SA response 2 [ N(NO_PROP) ]
```

Replace "server" with "responder" and "client" with "initiator", if you prefer proper IPsec speak.

**Comment by jauderho** [comment]
Something strange is going on. Reading your logs, it looks like only CHACHA
is proposed, which does not necessarily make sense since I do not remember
seeing that as an option as a server side option.

While we could probably consider putting chacha as the first item of
choice, I think you might want to take a look at your config to see what
else is going on.

ciphers:

  defaults:

    ike: aes128gcm16-sha2_512-prfsha512-ecp256!

    esp: aes128gcm16-sha2_512-ecp256!

  compat:

    ike:
aes128gcm16-sha2_512-prfsha512-ecp256,aes128-sha2_512-prfsha512-ecp256,aes128-sha2_256-prfsha256-modp2048!

    esp:
aes128gcm16-sha2_512-ecp256,aes128-sha2_512-ecp256,aes128-sha2_256-modp2048!

Is what's listed right now.

**Comment by dguido** [comment]
He was only showing an example of what PFS accept/reject looks like. Thermi has his own install of strongSwan to play with. He's on their development team :-D.

**Comment by Thermi** [comment]
@jauderho I'm not running Algo. I got my own boxes with the most recent version of strongSwan to play with. I used chacha20poly1305, because (as one could tell by the name), I just repurposed an existing connection to test this specific scenario.
Regarding your cipher suites under compat: "aes128gcm16-sha2_512-prfsha512-ecp256" will never use sha2_512 as HMAC, because aes128gcm16 already provides authenticity and sha2_512 is implicitely not used by any peer. Using any specified HMAC when an AEAD algorithm is used is invalid behaviour.
Same with aes128gcm16-sha2_512-ecp256.
With es128-sha2_256-prfsha256-modp2048, you'll have problems with HMAC-SHA2-256 ambiguity with peer that implement the draft of the SHA-2 for IPsec specification (96 bit truncation in the draft vs 128 bit truncation in the final version. That problem is more than a decade old).

@dguido Not on the dev team, but providing the majority of the support.

**Comment by jauderho** [comment]
@Thermi to be clear, I didn't pick that current cipher list but merely referencing what is in place today. I think @dguido would welcome suggestions to fix it up. =)

I believe there was a recent switch to SHA512 instead SHA256 due to what you mention. Maybe `aes128-sha2_256-prfsha256-modp2048` should be dropped or changed to `aes128-sha2_512-prfsha256-modp2048` <-- will this even work?

See https://github.com/trailofbits/algo/blob/master/roles/vpn/defaults/main.yml

**Comment by dguido** [comment]
Oh interesting. Thanks for the tip Thermi! Yes, I guess we need to fixup the default ciphers list then.

I guess something like this? I haven't tested this. I'm just running out the door now!

```
ciphers:
  defaults:
    ike: aes128gcm16-prfsha512-ecp256!
    esp: aes128gcm16-ecp256!
  compat:
    ike: aes128gcm16-prfsha512-ecp256,aes128-sha2_512-prfsha512-ecp256,aes128-sha2_512-prfsha512-modp2048!
    esp: aes128gcm16-ecp256,aes128-sha2_512-ecp256,aes128-sha2_512-prfsha512-modp2048!
```

I really wish someone could figure out how to get Windows to use the ciphers in default...

**Comment by Thermi** [comment]
@jauderho You could change to either sha2_384, sha2_512 or use an AEAD algorithm (preferred!).

@dguido Looks good from my side.

**Comment by jauderho** [comment]
I'll try to get to it if I find some time. 

@dguido There's a great writeup about AEADs by agl if you have not previously seen it. https://www.imperialviolet.org/2015/05/16/aeads.html

**Comment by felipekk** [comment]
I've just installed an algo VPN on DigitalOcean and I'm unable to connect from my Surface Pro 4 running Windows 10 (w/o Creator's Update). Algo works from my Android.
I thought Windows 10 was supported?

```
Apr 23 17:25:44 algo charon: 13[IKE] IKE_SA (unnamed)[45] state change: CREATED => CONNECTING
Apr 23 17:25:44 algo charon: 13[CFG] selecting proposal:
Apr 23 17:25:44 algo charon: 13[CFG]   no acceptable ENCRYPTION_ALGORITHM found
Apr 23 17:25:44 algo charon: 13[CFG] selecting proposal:
Apr 23 17:25:44 algo charon: 13[CFG]   no acceptable PSEUDO_RANDOM_FUNCTION found
Apr 23 17:25:44 algo charon: 13[CFG] selecting proposal:
Apr 23 17:25:44 algo charon: 13[CFG]   no acceptable PSEUDO_RANDOM_FUNCTION found
Apr 23 17:25:44 algo charon: 13[CFG] received proposals: IKE:AES_CBC_128/HMAC_SHA2_256_128/PRF_HMAC_SHA2_256/MODP_2048
Apr 23 17:25:44 algo charon: 13[CFG] configured proposals: IKE:AES_GCM_16_128/PRF_HMAC_SHA2_512/ECP_256, IKE:AES_CBC_128/HMAC_SHA2_512_256/PRF_HMAC_SHA2_512/ECP_256, IKE:AES_CBC_128/HMAC_SHA2_512_256/PRF_HMAC_SHA2_512/MODP_2048
Apr 23 17:25:44 algo charon: 13[IKE] remote host is behind NAT
Apr 23 17:25:44 algo charon: 13[IKE] received proposals inacceptable
```

**Comment by dguido** [comment]
Thanks, but your comment doesn't tell us anything we don't already know. Windows support is broken and there is a pull request in #464, linked directly above your comment, to address it. If you can, please test that PR. We're no longer content weakening and complicating our installs for Windows support. Instead, we are, mostly blindly, working our way through the poor out-of-the-box ciphers, opaque debugging, and manual configuration required on Windows to get it right.

**Comment by dguido** [comment]
We just committed #464. This PR fixes a few issues for Windows clients:

1. ECDSA certificates replace RSA 2048 certificates
2. IKE: SHA2-384 integrity checking replaces SHA2-256 (avoid 96-bit truncation issue on other clients)
3. IKE & ESP: ECP256 diffie hellman replaces modp2048 (no more RSA!)

There are 2 issues that prevent Windows from using the default cipher suite:

1. We can't find a way to get IKE to use AES-GCM
2. The latest version of Windows 10 does not support SHA2-512

Windows connections should work again if anyone wants to try it now.

**Comment by felipekk** [comment]
I've changed my ike setup in ipsec.conf according to #464. I've removed the VPN connection in Windows and updated my script according to #464. I've rerun the script and still can't connect:
```
Apr 23 21:45:21 algo charon: 14[IKE] 95.232.127.134 is initiating an IKE_SA
Apr 23 21:45:21 algo charon: 14[IKE] IKE_SA (unnamed)[5] state change: CREATED => CONNECTING
Apr 23 21:45:21 algo charon: 14[CFG] selecting proposal:
Apr 23 21:45:21 algo charon: 14[CFG]   no acceptable ENCRYPTION_ALGORITHM found
Apr 23 21:45:21 algo charon: 14[CFG] selecting proposal:
Apr 23 21:45:21 algo charon: 14[CFG]   no acceptable PSEUDO_RANDOM_FUNCTION found
Apr 23 21:45:21 algo charon: 14[CFG] selecting proposal:
Apr 23 21:45:21 algo charon: 14[CFG]   no acceptable PSEUDO_RANDOM_FUNCTION found
Apr 23 21:45:21 algo charon: 14[CFG] received proposals: IKE:AES_CBC_128/HMAC_SHA2_256_128/PRF_HMAC_SHA2_256/ECP_256
Apr 23 21:45:21 algo charon: 14[CFG] configured proposals: IKE:AES_GCM_16_128/PRF_HMAC_SHA2_512/ECP_256, IKE:AES_CBC_128/HMAC_SHA2_512_256/PRF_HMAC_SHA2_512/ECP_256, IKE:AES_CBC_128/HMAC_SHA2_384_192/PRF_HMAC_SHA2_384/ECP_256
Apr 23 21:45:21 algo charon: 14[IKE] remote host is behind NAT
Apr 23 21:45:21 algo charon: 14[IKE] received proposals inacceptable
```
Are these changes enough to test #464 or do I need to redeploy?

**Comment by dguido** [comment]
felipekk I think you made a typo when you updated your local PowerShell script. Make sure you replace the SHA2-256 with SHA2-384.

**Comment by felipekk** [comment]
@dguido Please note that the script in #464 does not specify SHA2-384. I've manually changed my PowerShell script to:
`-AuthenticationTransformConstants GCMAES128 -CipherTransformConstants GCMAES128 -EncryptionMethod AES128 -IntegrityCheckMethod SHA384 -DHGroup ECP256 -PfsGroup none`
This time I've got a different error: "IKE failed to find valid machine certificate".
```
Apr 23 21:59:49 algo charon: 11[IKE] 95.232.127.134 is initiating an IKE_SA
Apr 23 21:59:49 algo charon: 11[IKE] IKE_SA (unnamed)[10] state change: CREATED => CONNECTING
Apr 23 21:59:49 algo charon: 11[CFG] selecting proposal:
Apr 23 21:59:49 algo charon: 11[CFG]   no acceptable ENCRYPTION_ALGORITHM found
Apr 23 21:59:49 algo charon: 11[CFG] selecting proposal:
Apr 23 21:59:49 algo charon: 11[CFG]   no acceptable PSEUDO_RANDOM_FUNCTION found
Apr 23 21:59:49 algo charon: 11[CFG] selecting proposal:
Apr 23 21:59:49 algo charon: 11[CFG]   proposal matches
Apr 23 21:59:49 algo charon: 11[CFG] received proposals: IKE:AES_CBC_128/HMAC_SHA2_384_192/PRF_HMAC_SHA2_384/ECP_256
Apr 23 21:59:49 algo charon: 11[CFG] configured proposals: IKE:AES_GCM_16_128/PRF_HMAC_SHA2_512/ECP_256, IKE:AES_CBC_128/HMAC_SHA2_512_256/PRF_HMAC_SHA2_512/ECP_256, IKE:AES_CBC_128/HMAC_SHA2_384_192/PRF_HMAC_SHA2_384/ECP_256
Apr 23 21:59:49 algo charon: 11[CFG] selected proposal: IKE:AES_CBC_128/HMAC_SHA2_384_192/PRF_HMAC_SHA2_384/ECP_256
Apr 23 21:59:49 algo charon: 11[IKE] remote host is behind NAT
```

**Comment by dguido** [comment]
Maybe you and I are not looking at the same script. #464 uses the following line:

```
+Set-VpnConnectionIPsecConfiguration -ConnectionName "Algo VPN {{ IP_subject_alt_name }} IKEv2" -AuthenticationTransformConstants GCMAES128 -CipherTransformConstants GCMAES128 -EncryptionMethod AES128 -IntegrityCheckMethod SHA384 -DHGroup ECP256 -PfsGroup none
View
```

Regardless, your current problem now is that you didn't install the CA certificate. Step 2 from the Windows clients directions indicates: "Import the CA certificate to the local machine Trusted Root certificate store."

**Comment by felipekk** [comment]
We were not looking at the same script, sorry! I was looking at [this](https://github.com/trailofbits/algo/pull/464/commits/1bdf7ee994f4d1c83ccde5f0c1cea45dc96c1b85).
Yeah I figured it's a different problem now, but I don't know what it is since I see the certificate in the Trusted Root Certification Authorities for Local Machine. I've tried removing and re-importing it but no dice.

**Comment by Thermi** [comment]
@dguido 
"IKE & ESP: ECP256 diffie hellman replaces modp2048 (no more RSA!)"
MODP is DH and ECP is DH over an elliptic curve. Neither of those two have anything to do with RSA. The key exchange method and the algorithm and key lengths the certificate use are independent of each other and you can combine any type of key exchange (MODP, ECP, ECP over Brainpool Curves, curve25519, NTRU, NEWHOPE) with any type of certificate (RSA,  DSA/ELGAMAL, ECDSA, BLISS).
This comment's purpose is just to correct this piece of misinformation.

**Comment by dguido** [comment]
Thanks! My vocabulary was a little sloppy, my bad. :-P

**Comment by felipekk** [comment]
Just FYI, I've redeployed and it works, I'm on Windows 10 without Creators Update.
