### ISSUE TITLE
misleading parameter in ipsec.conf

### ISSUE THREAD

**Issue by oleyka** [trailofbits/algo#90]
The default connection has:

    dpdtimeout=300s
    ...
    keyexchange=ikev2

Yet, according to the StrongSwan documentation, the parameter only applies to IKEv1:

> dpdtimeout = 150s | \<time\>
> defines the timeout interval, after which all connections to a peer are deleted in case of inactivity. This only applies to IKEv1, in IKEv2 the default retransmission timeout applies, as every exchange is used to detect dead peers.

**Comment by defunctio** [comment]
You are correct, it seems this was likely overlooked. 

See: https://wiki.strongswan.org/projects/strongswan/wiki/Retransmission
If we would like to deviate from the defaults for re-transmission parameters in strongswan.conf.

**Comment by dguido** [comment]
So, we should just remove this line?

https://github.com/trailofbits/algo/blob/master/roles/vpn/templates/ipsec.conf.j2#L8

**Comment by defunctio** [comment]
Correct, if you are fine with the defaults listed on the link above we don't need to make any other changes either.
