### ISSUE TITLE
Algo in Docker

### ISSUE THREAD

**Issue by HenkiedeHenkie** [trailofbits/algo#901]
Yes, I know I open some issue step last days, but as I'm investigating the use of Algo I have a few questions. One is that I want to use Algo in a Docker and although there is some documentation, I have no clue what the current limitations of this implementation are. I'm looking into running Algo together with some other services on my server and the use of Docker seems ideal for that...

**Comment by dguido** [comment]
This is covered in the documentation already

https://github.com/trailofbits/algo/blob/master/docs/deploy-to-unsupported-cloud.md
