### ISSUE TITLE
TASK [vpn : Build the client's p12] ******************************************** failed

### ISSUE THREAD

**Issue by defensivedental** [trailofbits/algo#91]
TASK [vpn : Build the client's p12] ********************************************
failed: [67.205.136.248] (item=algore - dan - jack) => {"changed": true, "cmd": "openssl pkcs12 -in /opt/easy-rsa-ipsec/easyrsa3//pki/issued/algore - dan - jack.crt -inkey /opt/easy-rsa-ipsec/easyrsa3//pki/private/algore - dan - jack.key -export -name algore - dan - jack -out //opt/easy-rsa-ipsec/easyrsa3//pki/private/algore - dan - jack.p12 -certfile /opt/easy-rsa-ipsec/easyrsa3//pki/ca.crt -passout pass:vpnpws && touch '/opt/easy-rsa-ipsec/easyrsa3/pki/algore - dan - jack_p12_initialized'", "delta": "0:00:00.009040", "end": "2016-09-30 10:42:22.923790", "failed": true, "item": "algore - dan - jack", "rc": 1, "start": "2016-09-30 10:42:22.914750", "stderr": "Usage: pkcs12 [options]\nwhere options are\n-export       output PKCS12 file\n-chain        add certificate chain\n-inkey file   private key if not infile\n-certfile f   add all certs in f\n-CApath arg   - PEM format directory of CA's\n-CAfile arg   - PEM format file of CA's\n-name \"name\"  use name as friendly name\n-caname \"nm\"  use nm as CA friendly name (can be used more than once).\n-in  infile   input filename\n-out outfile  output filename\n-noout        don't output anything, just verify.\n-nomacver     don't verify MAC.\n-nocerts      don't output certificates.\n-clcerts      only output client certificates.\n-cacerts      only output CA certificates.\n-nokeys       don't output private keys.\n-info         give info about PKCS#12 structure.\n-des          encrypt private keys with DES\n-des3         encrypt private keys with triple DES (default)\n-seed         encrypt private keys with seed\n-aes128, -aes192, -aes256\n              encrypt PEM output with cbc aes\n-camellia128, -camellia192, -camellia256\n              encrypt PEM output with cbc camellia\n-nodes        don't encrypt private keys\n-noiter       don't use encryption iteration\n-nomaciter    don't use MAC iteration\n-maciter      use MAC iteration\n-nomac        don't generate MAC\n-twopass      separate MAC, encryption passwords\n-descert      encrypt PKCS#12 certificates with triple DES (default RC2-40)\n-certpbe alg  specify certificate PBE algorithm (default RC2-40)\n-keypbe alg   specify private key PBE algorithm (default 3DES)\n-macalg alg   digest algorithm used in MAC (default SHA1)\n-keyex        set MS key exchange type\n-keysig       set MS key signature type\n-password p   set import/export password source\n-passin p     input file pass phrase source\n-passout p    output file pass phrase source\n-engine e     use engine e, possibly a hardware device.\n-rand file:file:...\n              load the file (or the files in the directory) into\n              the random number generator\n-CSP name     Microsoft CSP name\n-LMK          Add local machine keyset attribute to private key", "stdout": "", "stdout_lines": [], "warnings": []}

NO MORE HOSTS LEFT *************************************************************

**Comment by gunph1ld** [comment]
Which ansible version do you use?
How can I reproduce?
Show me your `config.cfg`

**Comment by defensivedental** [comment]
Ran from a mac, just re did it from debian, now works, thanks.
