### ISSUE TITLE
Intermittent Issues Viewing Twitter Profiles and Conversation Members on iOS

### ISSUE THREAD

**Issue by philkloose** [trailofbits/algo#913]
### OS / Environment (where do you run Algo on)

```
Linux myvpn 4.13.0-1011-gcp #15-Ubuntu SMP Mon Feb 12 16:29:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

### Cloud Provider (where do you deploy Algo to)

```
Google Cloud
```

### Summary of the problem

When using the Twitter app on iOS, loading user profiles and viewing members of a conversation occasionally fail.  I know VPNs are actively blocked on some platforms (e.g. Netflix), but I don't think Twitter is intentionally making my life difficult -- and if they are, they've implemented a very porous defense here.

### Steps to reproduce the behavior

1. While connected to AlgoVPN, open Twitter on iOS.
2. Find a tweet with a user Mention.
3. Click on the name of the user to see their profile.
4. Intermittently (perhaps 20% of the time), I get a blank profile page consisting of nothing but the user's Twitter handle and a message saying "Please tap to retry."

The same issue occurs when checking the "People in this conversation" pane.  I see "Error while downloading the list of users. Please try again later."

If I disconnect from the VPN, everything works fine.  If I disconnect and reconnect, it usually resolves the issue, but the issue will invariably crop up again.  There is no pattern to the profiles affected.

**Comment by dguido** [comment]
There's no good way for me to debug this. It may be a signal strength issue, some packets of yours may be getting dropped on the way to the internet which screws up the tunnel. Try moving to an area with higher signal strength or switching to a different VPS provider (not Google, since they have a few reported issues).

**Comment by domdewom** [comment]
I have exactly the same issue. Any Twitter profile, Tweet threats or Tweet replies I cannot open when connected to my Algo VPN on my iPhone via the Twitter app. In my case it is not 20% but actually 100% of the time. Any other page or app seems to work without issues. I doubt it has to do with connection strength... But any help would be appreciated. 

![image](https://user-images.githubusercontent.com/517299/131838092-100a9149-5627-4531-9112-0f7f672333d3.png)
