### ISSUE TITLE
Algo server management

### ISSUE THREAD

**Issue by movalex** [trailofbits/algo#915]
Hi! Maybe it is a dumb question, but how can I manage my Algo VPN server?
I mean restart, stop, view some useful logs etc? I recently deployed Algo on my VPS, and it is working, but sometimes just stops connecting to Internet. All I have to do is just restart whole machine. 

The only thing I found in syslog upon unsuccessful internet connection via VPN is following:

```
May  1 08:28:06 VPNserv charon: 16[MGR] IKE_SA ikev2-pubkey[18] successfully checked out
May  1 08:28:06 VPNserv charon: 16[KNL] querying policy 10.19.48.1/32 === 0.0.0.0/0 in  (mark 0/0x00000000)
May  1 08:28:06 VPNserv charon: 16[KNL] querying policy 10.19.48.1/32 === 0.0.0.0/0 fwd  (mark 0/0x00000000)
May  1 08:28:06 VPNserv charon: 16[KNL] querying policy fd9d:bc11:4020::1/128 === ::/0 in  (mark 0/0x00000000)
May  1 08:28:06 VPNserv charon: 16[KNL] querying policy fd9d:bc11:4020::1/128 === ::/0 fwd  (mark 0/0x00000000)
May  1 08:28:06 VPNserv charon: 16[MGR] checkin IKE_SA ikev2-pubkey[18]
May  1 08:28:06 VPNserv charon: 16[MGR] check-in of IKE_SA successful.
```

### OS / Environment (where do you run Algo on)
```
Linux 4.4.0-121-generic #145-Ubuntu SMP Fri Apr 13 13:47:23 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

### Summary of the problem
internet connection stops working until restart machine

**Comment by dguido** [comment]
Check dmesg. Did cgroups kill a process? There’s no remote management of Algo built in on purpose.
