### ISSUE TITLE
Win10 Policy match error

### ISSUE THREAD

**Issue by dialbat** [trailofbits/algo#918]
### OS / Environment (where do you run Algo on)

```
Linux DESKTOP-182UCS6 4.4.0-17134-Microsoft #1-Microsoft Tue Apr 10 18:04:00 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
```

### Cloud Provider (where do you deploy Algo to)

```
Azure
```

### Summary of the problem

After successful Algo install and successful ps script ran, i get "Policy match error" when trying to connect.

### Steps to reproduce the behavior

1. Follow install procedures.
2. try to connect

### Full log

```
1.
CoId={D7F76690-EE1C-42E0-9781-C808D1706B4A}: The user SYSTEM has started dialing a VPN connection using a per-user connection profile named Algo VPN ХХ.ХХ.ХХ.ХХ IKEv2. The connection settings are: 
Dial-in User = 
VpnStrategy = IKEv2
DataEncryption = Require
PrerequisiteEntry = 
AutoLogon = No
UseRasCredentials = Yes
Authentication Type = Machine Certificate 
Ipv4DefaultGateway = Yes
Ipv4AddressAssignment = By Server
Ipv4DNSServerAssignment = By Server
Ipv6DefaultGateway = Yes
Ipv6AddressAssignment = By Server
Ipv6DNSServerAssignment = By Server
IpDnsFlags = 
IpNBTEnabled = Yes
UseFlags = Private Connection
ConnectOnWinlogon = No
Mobility enabled for IKEv2 = Yes.

2.
CoId={D7F76690-EE1C-42E0-9781-C808D1706B4A}: The user SYSTEM is trying to establish a link to the Remote Access Server for the connection named Algo VPN ХХ.ХХ.ХХ.ХХ IKEv2 using the following device: 
Server address/Phone Number = ХХ.ХХ.ХХ.ХХ
Device = WAN Miniport (IKEv2)
Port = VPN2-1
MediaType = VPN.
```
3.
CoId={D7F76690-EE1C-42E0-9781-C808D1706B4A}: The user SYSTEM has successfully established a link to the Remote Access Server using the following device: 
Server address/Phone Number = ХХ.ХХ.ХХ.ХХ
Device = WAN Miniport (IKEv2)
Port = VPN2-1
MediaType = VPN.

4.
CoId={D7F76690-EE1C-42E0-9781-C808D1706B4A}: The link to the Remote Access Server has been established by user SYSTEM.

5.
CoId={D7F76690-EE1C-42E0-9781-C808D1706B4A}: The user SYSTEM dialed a connection named Algo VPN ХХ.ХХ.ХХ.ХХ IKEv2 which has failed. The error code returned on failure is 13868.

**Comment by dialbat** [comment]
I've tried registry tweak forcing stronger encryption, but no success.

**Comment by dialbat** [comment]
Anything???
Android works with no problem :/

**Comment by dguido** [comment]
Sorry! We can't debug this. We're sure the instructions work when followed on the latest version of Windows 10.
