### ISSUE TITLE
Can Pkcs12DecryptionPassword be found after i close setup window?

### ISSUE THREAD

**Issue by dialbat** [trailofbits/algo#919]
### OS / Environment (where do you run Algo on)

```
PUT THE OUTPUT HERE
```

### Cloud Provider (where do you deploy Algo to)

```
PUT THE OUTPUT HERE
```

### Steps to reproduce the behavior

1. Do this..
2. Do that..
3. 

### Full log

```
PUT THE OUTPUT HERE
```

**Comment by dguido** [comment]
Nope
