### ISSUE TITLE
Block ips/sites at certain times for individual users

### ISSUE THREAD

**Issue by jeremyfrancis** [trailofbits/algo#926]
I’m making an app that needs to block access to social media like Instagram or Facebook after the user’s desired time. How can I configure it to do this? Not sure where to start I don’t have much experience configuring stuff like this. Can someone point me in the right direction?

I’m using digital ocean on Ubuntu.

**Comment by dguido** [comment]
You may want to review how we block ads to build something comparable to what you want.
