### ISSUE TITLE
Ansible Install Failure on DO with adblock - dnsmasq fails

### ISSUE THREAD

**Issue by jpetermans** [trailofbits/algo#927]
### OS / Environment (where do you run Algo on)

```
Debian Stretch
```

### Cloud Provider (where do you deploy Algo to)

```
DigitalOcean
```

### Summary of the problem

Installation fails when deploying via ansible and using "dns" tag:
```
RUNNING HANDLER [dns_adblocking : restart dnsmasq] 
*********************************************
fatal: [138.68.49.66]: FAILED! => {"changed": false, "msg": "Unable to start service dnsmasq: 
Warning: dnsmasq.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Job for dnsmasq.service failed because the control process exited with error code. 
See \"systemctl status dnsmasq.service\" and \"journalctl -xe\" for details.\n"}
```

### Steps to reproduce the behavior

1. Installed with: 
```
ansible-playbook deploy.yml -t digitalocean,vpn,cloud,ssh_tunneling,dns -e "do_access_token=<token> do_server_name=<name> do_region=<region>"
```

Install completes with no errors when installing via Ansible without "dns" tag completes with no errors using the ./algo script with DNS resolver selected.

On the Droplet the systemclt output gives 
```
dnsmasq: failed to create listening socket for port 53: Address already in use
```
netstat:
```
dnscrypt-proxy tcp 172.16.0.1:53 LISTEN
dnscrypt-proxy tcp 127.0.2.1:53 LISTEN
```
Thanks!

**Comment by jackivanov** [comment]
Covered in https://github.com/trailofbits/algo/issues/933
You can use a workaround for now - `-e local_dns=true`
