### ISSUE TITLE
Slow page loads when Privoxy enabled due to default filter list

### ISSUE THREAD

**Issue by ndtob** [trailofbits/algo#93]
When Algo is setup with Privoxy page loads are delayed by several seconds.

This appears to be due to Privoxy's default filters list (/etc/privoxy/default.filter). With this enabled, the webpage requested is loaded into memory on the server, parsed according to the filter list and passed on to the user. This process takes time and memory to perform.

Disabling default.filter eliminates this delay and does not impact ad blocking functionality.

We may look into specifically isolating which filter in that list is the primary cause or eliminate default.filter completely from the default Algo installation.

**Comment by gunph1ld** [comment]
Disabled.
Btw, DNS adblock more faster than privoxy. If you don't want to slow down your internet, just disable proxy as a service.
