### ISSUE TITLE
Bypass (School) VPN block

### ISSUE THREAD

**Issue by MrBenFTW** [trailofbits/algo#934]
Hello, this works everywhere but my school, I was wondering if there was a way to change the port. Open vpn works as I can change the port on it to a different one as my school only blocks default vpn ports. Thanks!

**Comment by dguido** [comment]
IPSEC doesn't really work like that. It's just one set of ports.

**Comment by dguido** [comment]
Pay attention in school.

**Comment by MrBenFTW** [comment]
Also, you should consider adding Hetzner to a provider. They do cloud servers for $2.50 p/m and have a api. I'll link you :) 

https://www.hetzner.com/cloud

They are billed per hour. But works out to $2.50 if you do it for a whole month.

20GB SSD
2GB ram
1000/1000mbps

**Comment by MrBenFTW** [comment]
Hmmm, would Wireguard work on IOS? seeing as it uses interfaces.

**Comment by dguido** [comment]
It won't, not until someone writes a client library for it.

**Comment by MrBenFTW** [comment]
I just changed the port of my ssh, It wouldn't let me log in, so I set it back to default and now it works, What should I do

**Comment by MrBenFTW** [comment]
Also, if I change the hostname of the server is there anything else I need to change?
