### ISSUE TITLE
Uploading SSH key fails to Digital Ocean

### ISSUE THREAD

**Issue by pixlwave** [trailofbits/algo#939]
### OS / Environment (where do you run Algo on)

```
Ubuntu 16.04 on Windows 10
```

### Cloud Provider (where do you deploy Algo to)

```
Digital Ocean
```

### Summary of the problem

I have downloaded a fresh copy of Algo and am trying to deploy to Digital Ocean. Unfortunately it gets as far as uploading SSH keys and then fails saying `Key invalid: key should be of the format 'type key [comment]'`

### Steps to reproduce the behavior

1. Install algo.
2. Run with Digital Ocean as the host.

### Full log

```
Sorry running on a different machine.
```

**Comment by dguido** [comment]
I can't debug this

**Comment by pixlwave** [comment]
Sorry, thought it was probably a long shot, but wasn't sure if it might be reproducible. How do I get a debug log of the error?

**Comment by pixlwave** [comment]
I've added all the info I can see in the window. Not sure it's really anything extra though.

**Comment by jackivanov** [comment]
Duplicate https://github.com/trailofbits/algo/issues/891

**Comment by pixlwave** [comment]
Perfect, thanks @jackivanov that was the issue. Moving algo outside of /mnt fixed the error. Thanks for spotting that 🙂
