### ISSUE TITLE
Enabling Stronger Windows 10 Encryption

### ISSUE THREAD

**Issue by tharri** [trailofbits/algo#940]
According to the following...

[https://docs.microsoft.com/en-us/powershell/module/vpnclient/set-vpnconnectionipsecconfiguration?view=win10-ps](https://docs.microsoft.com/en-us/powershell/module/vpnclient/set-vpnconnectionipsecconfiguration?view=win10-ps)

AuthenticationTransformConstants could be set to GCMAES256 instead of GCMAES128.

CipherTransformConstants could be set to GCMAES256 instead of GCMAES128.

EncryptionMethod could be set to AES256 instead of AES128.

DHGroup could be set to ECP384 instead of ECP256.

PfsGroup could be set to ECP384 instead of ECP256.

Admittedly, I know next to nothing about this sort of thing, but could the Algo scripts be changed to support these presumably stronger ciphers?

**Comment by dguido** [comment]
Thanks, but the current cipher strengths are sufficient. AES-GCM 128 and ECP-256 provide sufficient safety guarantees for anyone running Algo.
