### ISSUE TITLE
Weak ciphers when protecting client key material

### ISSUE THREAD

**Issue by bytemare** [trailofbits/algo#945]
### Summary of the problem

When setting up algo, the keys created for the client are stored in an .p12 format protected by a password that is prompted at the end of the setup.

When one opens the .p12 file with something like : 
`openssl pkcs12 -info -in user.p12`

Something like this will be shown : 
`$ openssl pkcs12 -info -in user.p12 
Enter Import Password:
MAC:sha1 Iteration 2048
PKCS7 Encrypted data: pbeWithSHA1And40BitRC2-CBC, Iteration 2048
Certificate bag
Bag Attributes
    friendlyName: user
    localKeyID: HE XA HE XA
subject=/CN=user
issuer=/CN=[...]
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
PKCS7 Data
Shrouded Keybag: pbeWithSHA1And3-KeyTripleDES-CBC, Iteration 2048
Bag Attributes
    friendlyName: user
    localKeyID: HE XA HE XA
Key Attributes: <No Attributes>
Enter PEM pass phrase:
Verifying - Enter PEM pass phrase:
-----BEGIN ENCRYPTED PRIVATE KEY-----
...
-----END ENCRYPTED PRIVATE KEY-----`

The thing I want to point out is the use of  pbeWithSHA1And3-KeyTripleDES-CBC for a secret with the same key (password) as a public data protected by pbeWithSHA1And40BitRC2-CBC.
A motivated attacker could brute force one and thus access the other ( but I haven't tested that myself, I'm speculating). Discussing the weaknesses of these ciphers here is not the point.
But strong ciphers could be used here, like AEAD.

### Steps to reproduce the behavior

1. `./algo`
2. Set up whatever server you want
3. ` openssl pkcs12 -info -in [your user].p12`

**Comment by dguido** [comment]
If your computer is compromised to the point that someone retrieves this file, then all is lost. I had advocated not even encrypting it in earlier Algo releases.

Further, did you measure how long it would take to brute force the key in its current configuration?
