### ISSUE TITLE
is SMB port 445 blocked in Algo setup?

### ISSUE THREAD

**Issue by dialbat** [trailofbits/algo#948]
### OS / Environment (where do you run Algo on)

```
PUT THE OUTPUT HERE
```

### Cloud Provider (where do you deploy Algo to)

```
PUT THE OUTPUT HERE
```

### Steps to reproduce the behavior

1. Do this..
2. Do that..
3. 

### Full log

```
PUT THE OUTPUT HERE
```

**Comment by dguido** [comment]
Yes

**Comment by dialbat** [comment]
@dguido 
is this the right commad?
sudo iptables -A OUTPUT -p tcp --dport 445 -j REJECT

**Comment by dialbat** [comment]
I seem to not able to connect to azure file share through VPN.
thats why i thought Algo is blocking it.
i tried 
nc -zv X.X.X.X 445
X.X.X.X my Azure IP
and it shows it can connect :/
