### ISSUE TITLE
Algo default installation blocks Signal for desktop chat

### ISSUE THREAD

**Issue by ndtob** [trailofbits/algo#95]
The IPTABLES firewall rules or some filtering is preventing sending messages from [Signal for Chrome](https://chrome.google.com/webstore/detail/signal-private-messenger/bikioccmkafdpakkkcpdbppfkghcmihk).

I have not investigated or troubleshooted this yet other than confirming it will not send messages but will receive them when on VPN but does send/receive when off VPN.

**Comment by ndtob** [comment]
Confirmed it's specifically related to Privoxy proxy. Algo VPN without Privoxy allows Signal to send/receive messages.

**Comment by gunph1ld** [comment]
You need to disable secure connections via proxy, SSL proxying does not work anyway.

**Comment by gunph1ld** [comment]
Just checked, Signal works.
