### ISSUE TITLE
Just want to know how to setup ASUSWRT router to connect to VPN

### ISSUE THREAD

**Issue by Alejandro1960** [trailofbits/algo#951]
### OS / Environment (where do you run Algo on)

```
Darwin MacBook-Air-de-Alejandro.local 17.5.0 Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64
```

### Cloud Provider (where do you deploy Algo to)

```
DIGITALOCEAN
```

### Summary of the problem

I successfully installed algo on digitalocean using imac. My ip is now DO's ip. 

Now I want to have the asus router connect to vpn; I can use pptp or l2ptp or openvpn 
What do I do now?

### Steps to reproduce the behavior

![captura de pantalla 2018-05-16 a la s 21 12 26](https://user-images.githubusercontent.com/39355608/40153174-0f092798-594e-11e8-9502-7cc8b6c6ff82.png)

**Comment by dguido** [comment]
You can’t

**Comment by Alejandro1960** [comment]
ok, thnx
