### ISSUE TITLE
Windows 10 hotspot with VPN

### ISSUE THREAD

**Issue by RhanCandia** [trailofbits/algo#952]
Has any of you been successful in sharing your VPN connection via Windows 10 hotspot?

I've set up mine and when hotspot works without the VPN. When I turn the VPN on, I lose internet connection on the connected device.

Would appreciate if you guys can help. Thanks.

**Comment by dguido** [comment]
Sorry, we don't support Windows 10 very well because Windows does not support IPSEC very well. I would recommend using a Mac.

**Comment by Firifire** [comment]
well, i got it working. Just open adapters settings, right click algo adpater and go to properties. in Sharing tab, check the first box and select the hotspot adapter, and your good to go.
