### ISSUE TITLE
Unable to connect to Algo VPN on Android StrongSwan App

### ISSUE THREAD

**Issue by owenbutt** [trailofbits/algo#954]
### OS / Environment for Algo

Linux ubuntu-s-1vcpu-1gb-sgp1-01 4.4.0-124-generic #148-Ubuntu SMP Wed May 2 13:00:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Cloud Provider where Algo is Deployed
Currently deployed on Digital Ocean

### Summary of the problem
VPN does not connect to the strongswan app. Everything deployed following the official guide.

### Steps to reproduce the behavior

Profile imported several times and still get a message "Failed to establish VPN: Server is unreachable"
My guess is that it is the firewall that's blocking the connection. Every user has 

### Full log
**Output of Syslog on the server:**

`May 21 08:31:44 ubuntu-s-1vcpu-1gb-sgp1-01 kernel: [426167.581932] [UFW BLOCK] IN=eth0 OUT= MAC=xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx SRC=aa.aa.aa.aa DST=bb.bb.bb.bb LEN=732 TOS=0x00 PREC=0x00 TTL=43 ID=51635 DF PROTO=UDP SPT=35064 DPT=500 LEN=712`

`May 21 08:31:46 ubuntu-s-1vcpu-1gb-sgp1-01 kernel: [426169.581065] [UFW BLOCK] IN=eth0 OUT= MAC=xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx SRC=aa.aa.aa.aa DST=bb.bb.bb.bb LEN=732 TOS=0x00 PREC=0x00 TTL=43 ID=51802 DF PROTO=UDP SPT=35064 DPT=500 LEN=712`

`May 21 08:31:48 ubuntu-s-1vcpu-1gb-sgp1-01 kernel: [426172.395592] [UFW BLOCK] IN=eth0 OUT= MAC=xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx  SRC=aa.aa.aa.aa DST=bb.bb.bb.bb  LEN=732 TOS=0x00 PREC=0x00 TTL=43 ID=51963 DF PROTO=UDP SPT=35064 DPT=500 LEN=712`

`May 21 08:31:52 ubuntu-s-1vcpu-1gb-sgp1-01 kernel: [426176.309579] [UFW BLOCK] IN=eth0 OUT= MAC=xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx SRC=aa.aa.aa.aa DST=bb.bb.bb.bb  LEN=732 TOS=0x00 PREC=0x00 TTL=43 ID=52347 DF PROTO=UDP SPT=35064 DPT=500 LEN=712`

`May 21 08:31:58 ubuntu-s-1vcpu-1gb-sgp1-01 kernel: [426181.812593] [UFW BLOCK] IN=eth0 OUT= MAC=xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx SRC=aa.aa.aa.aa DST=bb.bb.bb.bb  LEN=732 TOS=0x00 PREC=0x00 TTL=43 ID=52422 DF PROTO=UDP SPT=35064 DPT=500 LEN=712`

`May 21 08:32:03 ubuntu-s-1vcpu-1gb-sgp1-01 kernel: [426186.856729] [UFW BLOCK] IN=eth0 OUT= MAC=xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx:xx SRC=aa.aa.aa.aa DST=bb.bb.bb.bb  LEN=40 TOS=0x00 PREC=0x00 TTL=243 ID=11937 PROTO=TCP SPT=48704 DPT=63391 WINDOW=1024 RES=0x00 SYN URGP=0`

`May 21 09:34:13 00[DMN] Starting IKE charon daemon (strongSwan 5.6.1dr3, Android 7.0 - NRD90M.A520FXXS2BQIJ/2017-10-01, SM-A520F - samsung/a5y17ltexx/samsung, Linux 3.18.14-11940524, aarch64)`

`May 21 09:34:13 00[LIB] loaded plugins: androidbridge charon android-log openssl fips-prf random nonce pubkey chapoly curve25519 pkcs1 pkcs8 pem xcbc hmac socket-default revocation eap-identity eap-mschapv2 eap-md5 eap-gtc eap-tls x509`

**Log from the StrongSwan Android App**
`May 21 09:34:13 00[JOB] spawning 16 worker threads
May 21 09:34:13 09[CFG] loaded user certificate 'CN=omarbutt' and private key
May 21 09:34:13 09[IKE] initiating IKE_SA android[2] to 128.199.109.158
May 21 09:34:13 09[ENC] generating IKE_SA_INIT request 0 [ SA KE No N(NATD_S_IP) N(NATD_D_IP) N(FRAG_SUP) N(HASH_ALG) N(REDIR_SUP) ]
May 21 09:34:13 09[NET] sending packet: from 192.168.19.39[59572] to 128.199.109.158[500] (704 bytes)
May 21 09:34:15 10[IKE] retransmit 1 of request with message ID 0
May 21 09:34:15 10[NET] sending packet: from 192.168.19.39[59572] to 128.199.109.158[500] (704 bytes)
May 21 09:34:18 11[IKE] retransmit 2 of request with message ID 0
May 21 09:34:18 11[NET] sending packet: from 192.168.19.39[59572] to 128.199.109.158[500] (704 bytes)
May 21 09:34:22 12[IKE] retransmit 3 of request with message ID 0
May 21 09:34:22 12[NET] sending packet: from 192.168.19.39[59572] to 128.199.109.158[500] (704 bytes)
May 21 09:34:27 13[IKE] giving up after 3 retransmits
May 21 09:34:27 13[IKE] peer not responding, trying again (2/0)
May 21 09:34:27 13[IKE] initiating IKE_SA android[2] to 128.199.109.158
May 21 09:34:27 13[ENC] generating IKE_SA_INIT request 0 [ SA KE No N(NATD_S_IP) N(NATD_D_IP) N(FRAG_SUP) N(HASH_ALG) N(REDIR_SUP) ]
May 21 09:34:27 13[NET] sending packet: from 192.168.19.39[59572] to 128.199.109.158[500] (704 bytes)
May 21 09:34:27 15[IKE] destroying IKE_SA in state CONNECTING without notification`

**Comment by jackivanov** [comment]
Ensure that the server is reachable. And you may want to check logs on the server

**Comment by owenbutt** [comment]
Hi jackivanov. Thanks for getting back. I can connect to the server as can be seen from the syslog in the previous post.

**Comment by davidemyers** [comment]
Why is UFW enabled on the server?

**Comment by dguido** [comment]
Thanks for the bug report owenbutt, however, we are deprecating support for Android with IPSEC and will be moving to WireGuard instead. Please clone this open PR to try it: https://github.com/trailofbits/algo/pull/910
