### ISSUE TITLE
Hanging on 'Waiting SSH to become available' / Reusing old instance

### ISSUE THREAD

**Issue by marinintim** [trailofbits/algo#955]
### OS / Environment (where do you run Algo on)

```
Darwin MBP-timofey 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64 i386 MacBookPro13,2 Darwin
```

### Cloud Provider (where do you deploy Algo to)

```
Digital Ocean
```

### Summary of the problem
Due to Russian mad censoring of the internet, a lot of Digital Ocean IPs are 'banned', that means that Algo's setup scripts hang on `TASK [Wait until SSH becomes ready...]` for a long time before failing, because Digital Ocean unknowingly assigns already banned IP to the new droplet. I have an old Algo instance with not-banned IP, but I've lost keys to this machine.

Is there a way to force it to reuse old droplet, or fail faster while I'm trying to find non-banned ip?

### Steps to reproduce the behavior

1. Connect to the internet from Russia, or just ban on your local network a whole lot of DO IP addresses
2. Run Algo as usual
3. See that it hangs on `TASK [Wait until SSH becomes ready...]`

**Comment by jackivanov** [comment]
Nothing we can do here. You can rebuild the old droplet or [reinit the PKI](https://github.com/trailofbits/algo/blob/master/config.cfg#L13-L14)
