### ISSUE TITLE
Algo at home

### ISSUE THREAD

**Issue by hyperbart** [trailofbits/algo#958]
Seriously, I love algo, stumbled upon this, wonderful thing.

However, it got me thinking, is it possible to deploy algo on a VM at home? Afaics apart from the Ubuntu 16.04 option there is no way to set it up as a VPN appliance at home. I know algo might have not been intended to use in such a way, but the useability of algo surpasses anything I have ever seen before.

Would be great, cheers!

**Comment by dguido** [comment]
That's what the advanced option for local deployment is about. In general, we recommend you stick with the cloud setup unless you know exactly what you're doing.
