### ISSUE TITLE
DNS-over-HTTPS is only working for the clients, not the server.

### ISSUE THREAD

**Issue by ghost** [trailofbits/algo#964]
### OS / Environment (where do you run Algo on)
`Linux ubuntu-s-1vcpu-1gb-nyc3-01 4.15.0-22-generic #24-Ubuntu SMP Wed May 16 12:15:17 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

### Cloud Provider (where do you deploy Algo to)
DigitalOcean

### Summary of the problem
DNS-over-HTTPS is only working for the clients, not the server.

### Steps to reproduce the behavior
When connected via ssh to the server, if you use `dig debug.opendns.com txt` you'll get a blank response. Or using another method, killing the dnscrypt-proxy service, the server is still able to resolve.

I don't know if this is intended behaviour of not, if it is, sorry for the ticket!

**Comment by dguido** [comment]
Thanks! This sounds like a bug.

**Comment by beachfork** [comment]
A quick and dirty fix is to stop and disable systemd-resolved and let dnsmasq do it’s thing, the dnscrypt-proxy PPA package even installs a dnscrypt-proxy.conf over at dnsmasq.d/

**Comment by jackivanov** [comment]
Not a bug really. We use dnsmasq only when adblocking enabled. If not then systemd-resolved and resolvconf take care about `/etc/resolv.conf`. I'm not actually sure if we can guarantee immunity for `resolv.conf` without dirty hacks.

**Comment by faf0** [comment]
FWIW, if you decide to disable systemd-resolved (which can break multiple things), then you will need to change the `fallback_resolver` in `/etc/dnscrypt-proxy/dnscrypt-proxy.toml` from `'127.0.0.53:53'` (systemd-resolved DNS) to, e.g., `1.1.1.1:53`.

**Comment by jackivanov** [comment]
systemd-resolved will not be disabled
