### ISSUE TITLE
Wireguard giving error

### ISSUE THREAD

**Issue by williamthrilliam** [trailofbits/algo#965]
### OS / Environment (where do you run Algo on)

```
Linux  4.15.0-1008-gcp #8-Ubuntu SMP Thu May 17 08:10:14 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

### Cloud Provider (where do you deploy Algo to)

```
Google
```

### Summary of the problem
I'm trying to setup my wireguard client. 
Used latest build of algo (git clone)
latest version of android on a pixel 8.1.0

### Steps to reproduce the behavior

1. Download /wireguard/user.conf onto android
2. Open in wireguard
3. Wireguard gives error

### Full log
"Unable to import tunnel: not a numberic address: xx.xx.xx.xxx/32/DNS = xxx.xx.x.x
![screenshot may 24 2018 4_52_42 pm](https://user-images.githubusercontent.com/3210079/40515825-ee965f7c-5f73-11e8-8b9d-3d15a85d693f.png)

**Comment by dguido** [comment]
Please provide a full build log as requested by the template. We need to know what options you built with.

**Comment by davidemyers** [comment]
Also post the `user.conf` file in question. You should obfuscate the `PrivateKey`.

**Comment by zx2c4** [comment]
How did you transfer the file onto the phone? From the looks of that log, it appears that rather than a newline, your config file has a '/'?

**Comment by williamthrilliam** [comment]
You guys are quick, I didn't get a chance to get the log off my vm. Still need it?

**Comment by dguido** [comment]
Try it again and see
