### ISSUE TITLE
Scaleway Requires Kernel Module Tricks

### ISSUE THREAD

**Issue by zx2c4** [trailofbits/algo#966]
If you run on Scaleway VPSes, then you get to use the distro kernel and everything is fine. But Algo defaults to using baremetal hardware, which means you're stuck with the kernel that Scaleway builds for you. I'd caution against using these kernels, but if you're deadset on using the more expensive baremetal options rather than the VPSes, you'll have to either a) kexec into a distro kernel, or b) download and prepare the right headers for Scaleway's kernel. (a) is fairly straightforward and you can find guides on the Internet. For (b) here's the magic command to run before you start installing things:

`export DEBIAN_FRONTEND=noninteractive; apt update && apt upgrade -y && apt install -y build-essential libssl-dev && arch="$(uname -m)" && release="$(uname -r)" && upstream="${release%%-*}" && local="${release#*-}" && mkdir -p /usr/src && wget -O "/usr/src/linux-${upstream}.tar.xz" "https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-${upstream}.tar.xz" && tar xf "/usr/src/linux-${upstream}.tar.xz" -C /usr/src/ && ln -fns "/usr/src/linux-${upstream}" /usr/src/linux && ln -fns "/usr/src/linux-${upstream}" "/lib/modules/${release}/build" && { zcat /proc/config.gz > /usr/src/linux/.config || wget -O /usr/src/linux/.config "http://mirror.scaleway.com/kernel/${arch}/${release}/config-${release}"; } && printf 'CONFIG_LOCALVERSION="%s"\nCONFIG_CROSS_COMPILE=""\n' "${local:+-$local}" >> /usr/src/linux/.config && wget -O /usr/src/linux/Module.symvers "http://mirror.scaleway.com/kernel/${arch}/${release}/Module.symvers" && make -j$(nproc) -C /usr/src/linux prepare modules_prepare`

That's been sitting around in a file called `scaleway-do-stuff.txt` in my trash directory for about two years now. Maybe it can finally see some use.

**Comment by dguido** [comment]
Hm, I think we'll also consider switching the default VPS from baremetal to another one.

**Comment by jackivanov** [comment]
> But Algo defaults to using baremetal hardware

We use `START1-S` and it's not baremetal, it's a VPS

**Comment by zx2c4** [comment]
Oh, in that case, just toggle the local boot option.
