### ISSUE TITLE
Step 4 Failure (SecretStorage install fail)

### ISSUE THREAD

**Issue by johnboat** [trailofbits/algo#970]
### OS / Environment (where do you run Algo on)

```
Darwin Johns-MacBook-Pro.local 16.7.0 Darwin Kernel Version 16.7.0: Tue Jan 30 11:27:06 PST 2018; root:xnu-3789.73.11~1/RELEASE_X86_64 x86_64
```

### Cloud Provider (where do you deploy Algo to)

```
Could not fetch URL https://pypi.python.org/simple/secretstorage/: There was a problem confirming the ssl certificate: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) - skipping
  Could not find a version that satisfies the requirement SecretStorage<3 (from -r requirements.txt (line 2)) (from versions: )
No matching distribution found for SecretStorage<3 (from -r requirements.txt (line 2))
```

### Summary of the problem

Fails on Step 4, remaining dependencies. I pasted the error output above. SecretStorage is where it is failing. I tried downloading it directly and putting it in directory before running step 4, but that didn't work either.

### Steps to reproduce the behavior

1. Run step 4, dependencies. Fails every time with same error.

### Full log

This (below) is from step 4, not the ./algo script (I did try to run algo even after step 4 failed but couldn't get through it).

Johns-MacBook-Pro:algo-master john$ python -m ensurepip --user
Ignoring indexes: https://pypi.python.org/simple
Requirement already satisfied (use --upgrade to upgrade): setuptools in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python
Requirement already satisfied (use --upgrade to upgrade): pip in /Users/john/Library/Python/2.7/lib/python/site-packages
Johns-MacBook-Pro:algo-master john$ python -m pip install --user --upgrade virtualenv
Requirement already up-to-date: virtualenv in /Users/john/Library/Python/2.7/lib/python/site-packages
Johns-MacBook-Pro:algo-master john$ python -m virtualenv --python=`which python2` env && source env/bin/activate && python -m pip install -U pip && python -m pip install -r requirements.txt
New python executable in /Users/john/Documents/VPN/Algo-20180525/algo-master/env/bin/python
Installing setuptools, pip, wheel...done.
Could not fetch URL https://pypi.python.org/simple/pip/: There was a problem confirming the ssl certificate: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) - skipping
Requirement already up-to-date: pip in ./env/lib/python2.7/site-packages
Requirement already satisfied: setuptools>=11.3 in ./env/lib/python2.7/site-packages (from -r requirements.txt (line 1))
Collecting SecretStorage<3 (from -r requirements.txt (line 2))
  Could not fetch URL https://pypi.python.org/simple/secretstorage/: There was a problem confirming the ssl certificate: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) - skipping
  Could not find a version that satisfies the requirement SecretStorage<3 (from -r requirements.txt (line 2)) (from versions: )
No matching distribution found for SecretStorage<3 (from -r requirements.txt (line 2))

```
I installed the previous version of Algo just fine (March 2018). 
```

**Comment by jackivanov** [comment]
Could you check it now? Probably it was a problem on pypi.python.org with certificates, with your ISP or ca certificates are old on your machine. I can not reproduce the issue

**Comment by jwebbstevens** [comment]
I had the same issue #984 (sorry for duplicating issue)

I have the lastest build of **algo** (grabbed it 10 minutes ago Thursday, May 31, 2018 16:44 EST).

I tried this on several networks (different ISP's) including tethering to my cell through a hotspot (wifi off) through T-mobile. 

I've also tried it on several other machines (also on a different ISP) that have similar builds (all running latest of macOS High Sierra).

Still no dice. 😟

**Comment by jackivanov** [comment]
Hmm, http://pyfound.blogspot.com/2017/01/time-to-upgrade-your-python-tls-v12.html

Seems `brew upgrade python2` may help. Try this out, guys

**Comment by jwebbstevens** [comment]
Thanks @jackivanov I saw algo doesn't support Python 3.6 based on the Readme.md so homebrew is the way to go for MacOS users.

"Mac users should pay special attention. So far, the system Python shipped with MacOS does not yet support TLSv1.2 in any MacOS version; beginning next June these system Pythons will no longer be able to "pip install" packages. 2 Fortunately, it's easy to install a modern Python alongside the MacOS system Python. Either download Python 3.6 from python.org, or for Python 2.7 with the latest TLS, use Homebrew. Both methods of installing Python will continue working after June 2018."

And here's the reference from the link if anyone wants who is experiencing the same issue to fix.

1. To check your Python interpreter's TLS version, install the "requests" package and run a command. For example, for Python 2:

python2 -m pip install --upgrade requests
python2 -c "import requests; print(requests.get('https://www.howsmyssl.com/a/check', verify=False).json()['tls_version'])"

Or Python 3:

python3 -m pip install --upgrade requests
python3 -c "import requests; print(requests.get('https://www.howsmyssl.com/a/check', verify=False).json()['tls_version'])"

If you see "TLS 1.2", your interpreter's TLS is up to date. If you see "TLS 1.0" or an error like "tlsv1 alert protocol version", then you must upgrade. ↩

2. The reason Python's TLS implementation is falling behind on macOS is that Python continues to use OpenSSL, which Apple has stopped updating on macOS. In the coming year, the Python Packaging Authority team will investigate porting pip to Apple's own "SecureTransport" library as an alternative to OpenSSL, which would allow old Python interpreters to use modern TLS with pip only. "This is a non-trivial amount of effort," writes Stufft, "I'm not sure it's going to get done."

In the long run, the Python interpreter itself would easily keep up with TLS versions, if it didn't use OpenSSL on platforms like macOS and Windows where OpenSSL is not shipped with the OS. Cory Benfield and Christian Heimes propose to redesign the standard library's TLS interfaces to make it easier to swap OpenSSL with platform-native TLS implementations. ↩

**Comment by jwebbstevens** [comment]
@johnboat it's definately the issue of using outdate TLS.  I upgraded using the steps above and installed algo just fine.

@jackivanov I think this issue can be closed since it's not a bug with algo but a client issue with an unsupported version of TLS.  So long as users double-check they are running TLSv1.2 before installing algo they won't run into this problem again.  I'll make a PR and submit it to update the [Troubleshooting](https://github.com/trailofbits/algo/blob/master/docs/troubleshooting.md) doc if that helps.

**Comment by johnboat** [comment]
I haven't had a chance to retry yet, but thanks to you both for all the information.

**Comment by jackivanov** [comment]
@jwebbstevens It would be good if you can submit a PR. Thanks!

**Comment by sandyeggoxj** [comment]
I had this issue with osx 10.12 and I had to manually install python2 via homebrew. No issues after that.

**Comment by TC1977** [comment]
For future reference, you can also download python 2.7.x from python.org. I found 2.7.15 at https://www.python.org/downloads/release/python-2715/

This also comes with OpenSSL and pip bundled in it.
