### ISSUE TITLE
Algo VPN Server can't ping clients

### ISSUE THREAD

**Issue by CallMeAreks** [trailofbits/algo#977]
### OS / Environment (where do you run Algo on)

```
Linux PicBattleNet 4.4.0-127-generic #153-Ubuntu SMP Sat May 19 10:58:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

```

### Cloud Provider (where do you deploy Algo to)

```
DigitalOcean
```

### Summary of the problem

I've set up AlgoVPN on a DigitalOcean droplet. My PC at work (Let's call it A) is connected as a client. My server at our other office is also connected (Let's call it B).

I've configured Algo to allow communication between clients and I can successfully ping from A to B. But from the Droplet I can't ping neither of the clients and I have no idea why is that happening.

All firewalls (for test purposes) are disabled. The droplet is a brand new with only Algo (and dependencies) installed and nginx.

### Steps to reproduce the behavior

1. Install Algo
2. Try to ping from server to a client (ex 10.19.48.1)
3. It fails.

**Comment by jackivanov** [comment]
Can't reproduce. ping works on my devices

**Comment by CallMeAreks** [comment]
Can you help me with some insight? I need to get this working and I have near to zero networking knowledge. Do I need any kind of port forwarding? Ip routing? Tunneling? There are a lot of words I don't really understand.

**Comment by CallMeAreks** [comment]
Can you help me with some insight? I need to get this working and I have near to zero networking knowledge. Do I need any kind of port forwarding? Ip routing? Tunneling? There are a lot of words I don't really understand.

**Comment by dguido** [comment]
Can you browse the web with it? That's what Algo is for, reaching the internet. It doesn't allow client-client interactions.
