### ISSUE TITLE
Encountered error on Ubuntu 18.04 Vultr vps

### ISSUE THREAD

**Issue by ookangzheng** [trailofbits/algo#978]
### OS / Environment (where do you run Algo on)
```
Linux jp2 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

### Cloud Provider (where do you deploy Algo to)
```
vultr
```

### Error log 
<img width="1129" alt="screen shot 2018-05-31 at 20 22 48" src="https://user-images.githubusercontent.com/6301735/40782095-d608eb08-6510-11e8-95a4-b57a1e3a3490.png">

**Comment by jackivanov** [comment]
Can't reproduce. We are implementing Vultr native support [here](https://github.com/trailofbits/algo/pull/976). Try this out
