### ISSUE TITLE
Windows 10: Profile only visible for admin, not for user users

### ISSUE THREAD

**Issue by andreasba** [trailofbits/algo#983]
Good evening

thank you for this great piece of software. I am not an expert but managed to install Algo on DigitalOcea/Debian quite quickly.

Now, when it comes to using it via my Windows 10 client, I was following this line out of the [documentation:](https://github.com/trailofbits/algo/blob/master/docs/client-windows.md)
```
powershell -ExecutionPolicy ByPass -File windows_{username}.ps1 -Add
```

Well, it does its trick - the VPN profile is available for the admin account. BUT unfortunately not for the other, normal windows accounts.

Is there a way to achieve this?

Thanks
Andreas

**Comment by jackivanov** [comment]
Won't be enabled by default. You can share the connection between users yourself.
