### ISSUE TITLE
Could not find a version that satisfies the requirement SecretStorage<3

### ISSUE THREAD

**Issue by jwebbstevens** [trailofbits/algo#984]
### OS / Environment (where do you run Algo on)

`macOS High Sierra 10.13.4`

`Darwin macbook.local 17.5.0 Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64`

### Cloud Provider (where do you deploy Algo to)

Didn't get that far to deploy but attempting re-deploy the latest build of _algo_ to [Digital Ocean](https://www.digitalocean.com/)

### Summary of the problem

In the Collecting SecretStorage<3 (from -r requirements.txt (line 2)) part of the remaning dependencies install I get the following red lines

**Collecting SecretStorage<3 (from -r requirements.txt (line 2))**
 
**Could not fetch URL https://pypi.python.org/simple/secretstorage/: There was a problem confirming the ssl certificate: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:661) - skipping**

  **Could not find a version that satisfies the requirement SecretStorage<3 (from -r requirements.txt (line 2)) (from versions: )**

**No matching distribution found for SecretStorage<3 (from -r requirements.txt (line 2))**

The only thing I changed in config was adding a list of users (3 names). Otherwise `algo-master` source is unchanged.

### Steps to reproduce the behavior

1. Grabbed latest version of [algo](https://github.com/trailofbits/algo)
2. Added user list to `config.cfg`
3. `cd` into `algo-master` file directory where unzipped files are using _Terminal_
4. Ran core dependencies
5. Ran remaining dependencies 
6. Tried this (1-5) from my work network (at a WeWork Office Building) as well home and from a personal hotspot got the same errors below and can't run `./algo` successfully

### Full log

macbook:algo-master macbook$ cd /Users/macbook/Desktop/algo-master
macbook:algo-master macbook$ python -m ensurepip --user
Requirement already satisfied: setuptools in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
Requirement already satisfied: pip in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
macbook:algo-master macbook$ python -m pip install --user --upgrade virtualenv

**Could not fetch URL https://pypi.python.org/simple/virtualenv/: There was a problem confirming the ssl certificate: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:661) - skipping**

Requirement already up-to-date: virtualenv in /Users/macbook/Library/Python/2.7/lib/python/site-packages
macbook:algo-master macbook$ python -m virtualenv --python=`which python2` env &&
>     source env/bin/activate &&
>     python -m pip install -U pip &&
>     python -m pip install -r requirements.txt
Running virtualenv with interpreter /Library/Frameworks/Python.framework/Versions/2.7/bin/python2
New python executable in /Users/justinstevens-work/Desktop/algo-master/env/bin/python
Installing setuptools, pip, wheel...done.

**Could not fetch URL https://pypi.python.org/simple/pip/: There was a problem confirming the ssl certificate: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:661) - skipping**

Requirement already up-to-date: pip in ./env/lib/python2.7/site-packages
Requirement already satisfied: setuptools>=11.3 in ./env/lib/python2.7/site-packages (from -r requirements.txt (line 1))

Collecting SecretStorage<3 (from -r requirements.txt (line 2))
  **Could not fetch URL https://pypi.python.org/simple/secretstorage/: There was a problem confirming the ssl certificate: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:661) - skipping**

  **Could not find a version that satisfies the requirement SecretStorage<3 (from -r requirements.txt (line 2)) (from versions: )
No matching distribution found for SecretStorage<3 (from -r requirements.txt (line 2))**

**Comment by jackivanov** [comment]
duplicate https://github.com/trailofbits/algo/issues/970
