### ISSUE TITLE
Request - Add server region to the VPN Service Name in iOS/macos  

### ISSUE THREAD

**Issue by digeratus** [trailofbits/algo#986]
At the moment in iOS/MacOS the name of the VPN has the following naming convention: Algo VPN {{server IP address}} iKEv2 - that's the service name from the profile. What's the best way to include {{do_region}} -to that name? Btw, same applies to AWS, Azure, GCP or any other Algo supported platform. Why? Well, if you have multiple server instances in different parts of the world, it's more intuitive to see the region area right in the name than have to remember where the server is located based on memory and IP.

I'm not super familiar with Ansible, so I can't tell what variables are global, but with a little assistance as to what file needs to be edited - I'm assuming mobileconfig.j2 - and how to declare that variable I can make a PR for this.

Thanks

**Comment by jackivanov** [comment]
Duplicate https://github.com/trailofbits/algo/issues/491
