### ISSUE TITLE
Add Hetzner Cloud

### ISSUE THREAD

**Issue by Trikolon** [trailofbits/algo#988]
Please implement support for [Hetzner Cloud](https://www.hetzner.com/cloud?country=ot). They have very competitive pricing and a lot of bandwidth included.

[They have an API](https://docs.hetzner.cloud/)

This is their smallest server instance:
![image](https://user-images.githubusercontent.com/1077860/40891566-0bd75fc0-6788-11e8-8f2c-e0b232e4662d.png)

**Comment by monouser7dig** [comment]
just ran into this issue as the advanced intrusions for ubuntu 18.04 did not seem to work on hetzner, stuck at `PLAY [Configure the server]`...

**Comment by asmod3us** [comment]
Im running algo on Hetzner cloud. It's not a fully automated process and it probably needs work. Here are my notes:

- create a server

    `hcloud server create --name algo --image ubuntu-18.04 --datacenter nbg1-dc3 --type cx11 --ssh-key YOUR_SSH_KEY`

- i've invoked ansible like this:

    `ansible-playbook deploy.yml -t local,vpn,ssh_tunneling -e 'OnDemandEnabled_WIFI=Y Deployed_By_Algo=n OnDemandEnabled_WIFI_EXCLUDE=YOURWIFI,ANOTHERWIFI OnDemandEnabled_Cellular=Y server_ip=THE_HETZNER_IP server_user=root IP_subject=THE_HETZNER_IP IP_subject_alt_name=THE_HETZNER_IP --skip-tags=_null encrypted,cloud,update-alternatives'`

- use deployment via SSH

HTH

**Comment by monouser7dig** [comment]
I disabled ssh_tunneling but apart from that I just ran through the normal ./algo setup using ssh without error, could connect using my phone standard vpn and Wireguard as well  but there was just not all traffic coming through, especially websites did not load. https://github.com/trailofbits/algo/issues/1130#issuecomment-438641071

**Comment by Trikolon** [comment]
I've just noticed that there is a `hetzner_cloud` branch. Glad to see that's being worked on!
@jackivanov What's the status on that? I could help with some remaining tasks.

**Comment by vrudikov** [comment]
+1

**Comment by Wlanfr3ak** [comment]
+1

**Comment by sullyfischer** [comment]
+1

**Comment by cmersinli** [comment]
+1
