### ISSUE TITLE
nginx server can't access anymore after install algo

### ISSUE THREAD

**Issue by lengerrong** [trailofbits/algo#990]
### OS / Environment (where do you run Algo on)

```
Linux stable 4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10 16:32:20 UTC 2017 x86_64 x86
_64 x86_64 GNU/Linux
```

### Cloud Provider (where do you deploy Algo to)

```
Google Compute Engine
```

### Steps to reproduce the behavior

1. Do this..
2. Do that..
3. 

### Full log

```
I install algo server on a local host.
7. Install to existing Ubuntu 16.04 server (Advanced)
and install a local dns resolver to block ads.

After install algo server, algo server goes well.
but all my nginx server which ran well before install algo server can't access from internet anymore.
Does anyone knows why ?
And how to fix it？
```

**Comment by lengerrong** [comment]
Hi.

I found the issue related to iptables.
I cleaned all rules defined by algo via below commands.
sudo iptables -P INPUT ACCEPT
sudo iptables -F

then I found my nginx server work well.

I found algo set below rules.
I do not know which one caused nginx server can't work.

sudo iptables  -L
Chain INPUT (policy DROP)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     esp  --  anywhere             anywhere            
ACCEPT     ah   --  anywhere             anywhere            
ACCEPT     icmp --  anywhere             anywhere             icmp echo-request limit: up to 5/sec burst 5 mode srcip
ACCEPT     udp  --  anywhere             anywhere             multiport dports isakmp,ipsec-nat-t,51820
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:ssh ctstate NEW
ACCEPT     ipencap--  anywhere             anywhere             policy match dir in pol ipsec proto esp
ACCEPT     udp  --  anywhere             172.16.0.1           udp dpt:domain
Chain FORWARD (policy DROP)
target     prot opt source               destination         
DROP       all  --  10.19.48.0/24        10.19.48.0/24       
DROP       all  --  10.19.48.0/24        10.19.49.0/24       
DROP       all  --  10.19.49.0/24        10.19.48.0/24       
DROP       all  --  10.19.49.0/24        10.19.49.0/24       
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DROP       tcp  --  anywhere             anywhere             tcp dpt:microsoft-ds
DROP       udp  --  anywhere             anywhere             multiport ports netbios-ns,netbios-dgm
DROP       tcp  --  anywhere             anywhere             multiport ports netbios-ns,netbios-ssn
ACCEPT     all  --  10.19.48.0/24        anywhere             ctstate NEW policy match dir in pol ipsec
ACCEPT     all  --  10.19.49.0/24        anywhere             ctstate NEW policy match dir in pol none

**Comment by dguido** [comment]
Installing to your own server is for advanced users only

**Comment by lengerrong** [comment]
@dguido 
so there is a way to balance nginx and algo.
would you like to share the method please ?

**Comment by ahmed2m** [comment]
@dguido Can you like give us some of your knowledge? I don't think I can get `advanced` if everyone just says `for advanced users only`.
Can you with a word or two elaborate more where should I look at? like do I configure the iptable config or the firewall or ipsec?
