### ISSUE TITLE
Wireguard Failing on Private Wifi

### ISSUE THREAD

**Issue by awwong1** [trailofbits/algo#993]
### OS / Environment (where do you run Algo on)
Android `Version 8.0.0`
Android App: `Wireguard 0.0.20180605`

### Cloud Provider (where do you deploy Algo to)
`Digital Ocean`

### Summary of the problem

Wireguard VPN works when I am on LTE and on most other wifi. However, when connected to a private work Wifi (that is known to MITM SSL traffic and is relatively unreliable), my Wireguard VPN no longer functions properly. When trying to browse websites on my phone, I get `DNS_PROBE_FINISHED_NO_INTERNET` errors. An older IPSEC configuration using StrongSwan still works, however.

I'm not sure if this is an Algo problem or a Wireguard problem. I also don't have access to the corporate wifi configuration. 

Even if IPSEC is deprecated, it would be nice to have the old android helper files for strongswan VPN as an option for mobile devices. (I'm still using Strongswan for Linux as well, due to the same problem).

Please bring back the old Android helper scripts until Wireguard is more stable.

### Steps to reproduce the behavior

1. Follow and setup the Algo server/Android client 
2. Connect to private wifi
3. Observe that internet connections are failing due to DNS probe error

### Full log

I'm linking the output of the wireguard app's log. https://gist.github.com/awwong1/6a18b780733faaf81e462277c140c910
Not sure what else would be useful to diagnose this issue.

**Comment by awwong1** [comment]
For anyone else who needs to connect using StrongSwan on their android client, I created my own `*.sswan` file with the following fields as a workaround. Closing this issue, although I still think it'd be a good idea to have kept the old strongswan helper scripts and files.

```json
{
    "uuid": "000aaa00-aaa0-0000-a000-a0a0a0a000aa", // random uuid of your choice
    "name": "Algo 1.2.3.4", // name of your choice
    "type": "ikev2-cert",
    "remote": {
        "addr": "1.2.3.4", // public facing address of server
        "cert": "LS0tLS1..." // copy the $CaCertificateBase64 string in the generated windows_*.ps1 script
    },
    "local": {
        "p12": "MIIEKQIBAzCCA+8GCSqGSIb3DQEHAaCCA+AEggPcMIID2DCCAqcGCSqGSIb3DQEHBqCCApgwgg/bkfEDfBI72mrOZTAxMCEwCQYFKw4DAhoFAAQUm54N6Z2KglA0qm7iEb6+H80qIagECOiPTRUAsxaFAgIIAA==" // copy the $UserPkcs12Base64 string in the generated windows_*.ps1 script, newlines ok
    },
    "ike-proposal": "aes128gcm16-prfsha512-ecp256", // use older alg
    "esp-proposal": "aes128gcm16-ecp256",
    "mtu": 1280
}
```

**Comment by mpottinger** [comment]
I think am having the exact same problem. VPN works great on Linux with IPSEC, can't get Wireguard to work at all following the instructions.

Thanks for the workaround I will try it.

**Comment by awwong1** [comment]
Just out of curiosity @mpottinger , on your Linux machine do you have
certain sites that fail SSL handshakes? One example being Signal Messenger,
another example is https://ualberta.ca

- Sent from my mobile

**Comment by mpottinger** [comment]
@awwong1. Ok I just checked, and sure enough ualberta.ca doesn't work with this StrongSwan setup. My online banking works though thankfully. So it's not quite as perfect as I thought but still better than anything else I've been able to get going so far! Including OpenVPN. I agree that it seems a bit too soon to shut down support for this in favour of Wireguard. I struggled enough with OpenVPN to struggle with something new like that again, when IPSEC just plain seems to work, well, except for this little issue.


Just noticed you're also in Edmonton BTW. What a coincidence. haha.

**Comment by Giampli** [comment]
I had the same problem, I wasn't able to connect with my phone to anything and the log was just like the one in the issue.
I was using amazon EC2 and I set Algo on local.
I found out the problem was that I didn't open all the necessary port for wireguard:
TCP and UDP 53
UDP 51820.

Hope it helped.

**Comment by m3hrdadfi** [comment]
I've tried to use default and clean setup on DO by Algo document, but the wireguard still not received anything. When I try to connect to the outside on Chrome, I get DNS_PROBE_FINISHED_NO_INTERNET errors. This issue comes up only on Private Wifi.
