### ISSUE TITLE
Deploy from ansible playbook fails without facts gathering.

### ISSUE THREAD

**Issue by joiggama** [trailofbits/algo#998]
### OS / Environment (where do you run Algo on)

```
Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64
```

### Cloud Provider (where do you deploy Algo to)

```
vultr
```

### Summary of the problem

`ansible_kernel` is not set as `gather_facts` [is set to false](https://github.com/trailofbits/algo/blob/master/deploy.yml#L47) when deploying via ansible playbook.

### Steps to reproduce the behavior

1. Run `ansible-playbook deploy.yml -t local,vpn -e server_ip=<IP HERE> server_user=root`

### Full log

```
< TASK [common : set_fact] >
 --------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

fatal: []: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'ansible_kernel' is undefined\n\nThe error appears to have been in
'/Users/joiggama/Projects/algo/roles/common/tasks/ubuntu.yml': line 82, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offen
ding line appears to be:\n\n\n- set_fact:\n  ^ here\n"}
```

**Comment by jackivanov** [comment]
Please use a cloud deployment. Local installation is for expert users.

**Comment by joiggama** [comment]
Tehe. OK, I prefer choosing my own provider.

I was just reporting here that, default vars for a deploy from ansible isn't working. I already have my algo instance up and running with a few variable overrides from CLI.
